### ISSUE TITLE
Undefined References when using dim4 operators

### ISSUE THREAD

**Issue by yshady** [arrayfire/arrayfire#1000]
Hello,

I have arrayfire built and linked to successfully. I also have build UNIFIED option to ON. All tests run to completion, and I was able to write my own functions using various array functions. However, when I try to use dim4 arithmetic operators (such as dim4 range = end-start;) I get link errors: undefined reference to `af::operator-(af::dim4 const&, af::dim4 const&)'

**Comment by pavanky** [comment]
@yshady Thanks for catching that. We will fix this shortly. 

For now you can add `AFAPI ` at the beginning of the lines 56, 57 and 58 in the file `af/dim4.hpp`. This should fix the link issues for you.

**Comment by yshady** [comment]
Thanks @pavanky! That did the trick.

**Comment by pavanky** [comment]
This is now fixed in devel.
