### ISSUE TITLE
Using arrayfire with external OpenCL context

### ISSUE THREAD

**Issue by AlexHild** [arrayfire/arrayfire#1002]
To use arrayfire together with external libraries it would be helpful if external contexts could be used.

1) Minimum solution:
Allow the user to call something like afcl_init(device_id, context); before using the library.

2) Great solution:
Allow the user to switch between different contexts, or even different queues calling something like: afcl_set_context(context), afcl_set_device(device_id), afcl_set_queue(queue)

**Comment by pavanky** [comment]
The first option would be easier to implement with the current framework. 

The second one requires some additional investigation.

**Comment by holocronweaver** [comment]
New ArrayFire user here. Hesitant to adopt AF into larger projects until this feature is implemented. CL context control needs to be in hands of users. In most of my cases AF would be an accessory library for making working with OpenCL easier, not the primary OpenCL interface.

**Comment by pavanky** [comment]
@AlexHild @holocronweaver This is now possible with the devel branch in arrayfire. It will make it to the release version of arrayfire in version 3.3.0.

**Comment by Brainiarc7** [comment]
Hello,

Your [documentation](http://arrayfire.org/docs/interop_opencl.htm) still refers to this issue as open.
Please update.

Regards,

Brainiarc7.

**Comment by pavanky** [comment]
@Brainiarc7 The docs are going to be fixed for 3.4.0 based on this PR: https://github.com/arrayfire/arrayfire/pull/1422

**Comment by Brainiarc7** [comment]
Okay.
