### ISSUE TITLE
FFT for a signal of not a power of 2 dimension throws Exception(202) 

### ISSUE THREAD

**Issue by yshady** [arrayfire/arrayfire#1003]
This code:
``array test = randu(32,32);
test = fft2(test);``
builds and runs successfully. While:
``array test = randu(34,34);
test = fft2(test);``
fails with ``ArrayFire Exception(202): Invalid input argument. In ~/arrayfire/src/api/cpp/fft.cpp:29``

Do FFTs only work with power of 2 dimensions?

**Comment by pavanky** [comment]
@yshady The OpenCL version requires the fft lengths to have prime factors among the following {2, 3, 5}.

In this case `34` has a prime factor of 17.  This is not supported.

**Comment by pavanky** [comment]
What are the operations you are doing post fft? In many signal processing applications, you can pad the input with zeros to get the same results as the unpadded versions.

**Comment by yshady** [comment]
I think that's what I'll end up doing. Pad -> FFT -> operations -> IFFT -> truncate. I am mainly using the CUDA backend, and am currently porting some code to arrayfire that used cuFFT without problems.

**Comment by pavanky** [comment]
@yshady That size should be supported on the CUDA backend and only be a problem with OpenCL. Are you sure you are using ArrayFire with the CUDA backend ? 

That said, padding to power of 2 -> fft -> ops -> ifft -> truncate is actually a lot faster than doing operations on non powers of 2. Even if the other sizes are supported, if the algorithm can take benefit of this behavior, it should do so for getting the best performance.

**Comment by yshady** [comment]
I had both backends built, and thought CMAKE will magically pick the best (CUDA) to link against. You are right, after rebuilding arrayfire with just the CUDA backend. The above snippet worked.
