### ISSUE TITLE
CUDA backend activates all available GPUs

### ISSUE THREAD

**Issue by FilipeMaia** [arrayfire/arrayfire#1004]
Currently the CUDA backend activates all available GPUs in `DeviceManager`.

This is a problem in a host with multiple GPUs and where the GPUs are set to Thread or Process Exclusive. If you have two users trying to run arrayfire code, the second one will not find any available GPUs, even though the first user is probably just using one GPU.

Is there a way to tell arrayfire not to be greedy and only take one of the GPUs?

**Comment by pavanky** [comment]
@FilipeMaia I am not sure what you mean "Process Exclusive". With the vanilla configuration I am pretty sure two users can use different gpus of arrayfire at the same time.

**Comment by pavanky** [comment]
After further investigation, short of exporting `CUDA_VISIBLE_DEVICES`, I do not think there is an easy solution for this.

**Comment by marbre** [comment]
@pavanky 

~~~
    CUDA device compute modes
    Values

    cudaComputeModeDefault = 0
        Default compute mode (Multiple threads can use cudaSetDevice() with this device) 
    cudaComputeModeExclusive = 1
        Compute-exclusive-thread mode (Only one thread in one process will be able to use cudaSetDevice() with this device) 
    cudaComputeModeProhibited = 2
        Compute-prohibited mode (No threads can use cudaSetDevice() with this device) 
    cudaComputeModeExclusiveProcess = 3
        Compute-exclusive-process mode (Many threads in one process will be able to use cudaSetDevice() with this device) 
~~~

http://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES `cudaComputeMode`.


This can set on Linux with `nvidia-smi` (snippet of `nvidia-smi --help`):
~~~
    -c,   --compute-mode=       Set MODE for compute applications:
                                0/DEFAULT, 1/EXCLUSIVE_THREAD (deprecated),
                                2/PROHIBITED, 3/EXCLUSIVE_PROCESS

~~~

**Comment by shehzan10** [comment]
I believe (after running simple helloworld tests) that this was fixed by #1180. If someone can double check and close this issue, please do.

**Comment by pavanky** [comment]
@FilipeMaia can you check  this ?

**Comment by FilipeMaia** [comment]
Yes now one process does not block all the GPUs. 
But still problems remain in multi GPU machines.
Arrayfire always picks the same GPU, even if it's already busy and in exclusive mode.
So starting two processes gives the following crash:
```shell
$ ./simple & ./simple
[1] 23832
terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Internal error:998):
In function af_err af_create_handle(void**, unsigned int, const dim_t*, af_dtype)
In file src/api/c/data.cpp:203



In function void af::initEmptyArray(void**, af::dtype, dim_t, dim_t, dim_t, dim_t)
In file src/api/cpp/array.cpp:129
```

**Comment by pavanky** [comment]
@FilipeMaia Ideally the driver should hide the GPU from a secondary process when running in exclusive mode. Showing the GPU and erroring out seems to be a counter intuitive.

Either ways, can you run this with AF_PRINT_ERRORS=1 ? The documentation seems to be scarce about how to deal gracefully with exclusive compute modes. May be we can hack something together for these use cases.

**Comment by FilipeMaia** [comment]
@pavanky I agree the documentation doesn't say much. The initial device you get is guaranteed to be available, but for the others one has to try out and check the error codes. I haven't seen any nicer way to deal with this.

This is the output with AF_PRINT_ERRORS on:
```shell
$ ./simple & ./simple
[1] 24897
In function int cuda::DeviceManager::setActiveDevice(int, int)
In file src/backend/cuda/platform.cpp:398
CUDA Error (46): all CUDA-capable devices are busy or unavailable


In function af_err af_create_handle(void**, unsigned int, const dim_t*, af_dtype)
In file src/api/c/data.cpp:203



terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Internal error:998):
In function af_err af_create_handle(void**, unsigned int, const dim_t*, af_dtype)
In file src/api/c/data.cpp:203



In function void af::initEmptyArray(void**, af::dtype, dim_t, dim_t, dim_t, dim_t)
In file src/api/cpp/array.cpp:129
[1]  + Abort                         ./simple (core dumped)
```

**Comment by pavanky** [comment]
@FilipeMaia can you apply this one patch and see if it changes anything ?


```
$ git di src/backend/cuda/platform.cpp
diff --git a/src/backend/cuda/platform.cpp b/src/backend/cuda/platform.cpp
index f5f6599..e184a27 100644
--- a/src/backend/cuda/platform.cpp
+++ b/src/backend/cuda/platform.cpp
@@ -67,7 +67,7 @@ static inline int compute2cores(int major, int minor)
 //   2. total memory
 
 #define COMPARE(a,b,f) do {                     \
-        return ((a)->f >= (b)->f);              \
+        return ((a)->f > (b)->f);               \
     } while (0);
```

**Comment by shehzan10** [comment]
> Yes now one process does not block all the GPUs. 
> But still problems remain in multi GPU machines.
> Arrayfire always picks the same GPU, even if it's already busy and in exclusive mode.
> So starting two processes gives the following crash:
> 
> $ ./simple & ./simple
> [1] 23832
> terminate called after throwing an instance of 'af::exception'
>   what():  ArrayFire Exception (Internal error:998):
> In function af_err af_create_handle(void**, unsigned int, const dim_t*, af_dtype)
> In file src/api/c/data.cpp:203
> 
> 
> 
> In function void af::initEmptyArray(void**, af::dtype, dim_t, dim_t, dim_t, dim_t)
> In file src/api/cpp/array.cpp:129

This makes sense as its an issue with the CUDA driver. Even on single GPUs its going to be a problem if the user chooses to run it on the same device.

The best we can do, is perhaps "hide" the device from the user if it throws an error at cudaStreamCreate. This was the device manager will pick the next device. Alternatively, instead of hiding the device, we can try to set the next device and see if that is successful.

**Comment by FilipeMaia** [comment]
@pavanky Same error with the patch applied.

@shehzan10 If you're running exclusive process on a single GPU of course you can't run two arrayfire processes. But when you have free GPUs things should just work, and right now they don't because arrayfire it's actively picking a busy device instead of just taking the one that the CUDA driver assigned to it in the beginning of the process.
Not hiding, but trying the next device seems to me like the correct action.
