### ISSUE TITLE
FTBFS on several architectures due to assembly code

### ISSUE THREAD

**Issue by ghisvail** [arrayfire/arrayfire#1015]
The Debian builders reported the following build error (`error: impossible register constraint in 'asm'`) on the following architectures: `arm64`, `mipsel` and `powerpc`.

Individual logs for each build can be found [here](https://buildd.debian.org/status/package.php?p=arrayfire#issues-arrayfire).

**Comment by pavanky** [comment]
We do not use assembly code in arrayfire. The only restriction is C++11.

**Comment by shehzan10** [comment]
@pavanky it is used in cpu/platform.cpp. I believe it was added for the CPU af::info when @9prady9 added new information.

**Comment by pavanky** [comment]
Well shit I take it back. I think we are using it inside platform.

**Comment by 9prady9** [comment]
@pavanky The CPU backend uses it to extract system information, however this code should not execute on ARM as it is defined with a conditional block for `execute if not arm` - which i think explains why it is throwing up for mipsel and powerpc.

**Comment by ghisvail** [comment]
> Well shit I take it back. I think we are using it inside platform.

I was about to say: "but the error message says..."

**Comment by pavanky** [comment]
@9prady9 I checked their logs. It is throwing the errors on `arm64`. Can we flip the condition to be x86 / x86_64 only ?

**Comment by 9prady9** [comment]
We should do that. But out of curiosity, do we even support mipsel and powerpc ?

**Comment by pavanky** [comment]
@9prady9 I was going to clarify that.

@ghisvail 

We can fix trivial things such as this, but for reference we only plan to support ARM (32 bit now, 64 bit in future) and x86 (64 bit regularly, 32 bit when required) for the forseeable future. We might end up supporting PowerPC at some point if we get access to said hardware but we will can not support arrayfire on hardware that we do not have access to.

**Comment by ghisvail** [comment]
> We can fix trivial things such as this, but for reference we only plan to support ARM (32 bit now, 64 bit in future) and x86 (64 bit regularly, 32 bit when required) for the foreseeable future.

Understood. I cannot prevent the builders to work on all  architectures, but I will focus my reporting on bugs affecting the architectures you listed to be officially supported.

**Comment by pavanky** [comment]
We have a fix in hotfixes-3.1.2 branch that should hopefully fix this.

**Comment by pavanky** [comment]
@ghisvail [This](https://github.com/9prady9/arrayfire/commit/e5b8788f7ff5ace55be0c2057c77868336d75780) is the relevant commit in case you are interested in patching 3.1.1. We are planning to release 3.1.2 next Monday in case you want to wait.

**Comment by ghisvail** [comment]
Perfect, thanks for addressing this. I'll submit an update and check the builders. Then, I'll drop the patches once 3.1.2 is out.

**Comment by pavanky** [comment]
@shehzan10 shouldn't we reopen this issue then ?

**Comment by shehzan10** [comment]
I think @9prady9 was working on it. He would be in a better position to decide that.

**Comment by 9prady9** [comment]
@pavanky From the logs provided by @ghisvail the build was a success for `i386` architecture. Also, we were able to build ArrayFire on a 64bit VM (@shehzan tested this out on one of our local machines). So, i guess it is only an issue on VM of 32bit architecture. I don't think we need to reopen this issue.

**Comment by ghisvail** [comment]
I have updated the builders with a patch containing the commit. Now ArrayFire builds on `powerpc` and `mipsel`, but still fails on `arm64` and `ppc64` with the same error. Logs are available [here](https://buildd.debian.org/status/package.php?p=arrayfire#issues-arrayfire).

**Comment by 9prady9** [comment]
Reopening the issue since it is still failing on `arm64` and `ppc64`.

@ghisvail I was under the impression that `powerpc` is nothing but `ppc64`, does just `powerpc` mean 32-bit ?

I might know what is the issue. It is mostly associated with `__LP64__` preprocessor macro, we are checking for to decide when to use `cpuid`, along with other architecture macros. It could be that this is macro `__LP64__` is defined for all 64 bit targets irrespective of vendor hardware which is what is causing this.
I have raised a [PR](https://github.com/arrayfire/arrayfire/pull/1023) for ArrayFire with the fix for this macro.

**Comment by ghisvail** [comment]
@9prady9 yes `powerpc` is 32-bit.

**Comment by shehzan10** [comment]
@ghisvail would it be possible for you to test the PRs #1023 and #1018 on the failing machines? We want to do a code freeze today for 3.1.2 and release the installers by monday. If you can confirm everything is good, that would definitely help.

**Comment by ghisvail** [comment]
I can submit a new release, but I am not sure you will have the results on time for today's code freeze. Is that ok?

**Comment by 9prady9** [comment]
I am fairly confident that this latest fix should resolve the issue. But we can keep this issue open until the release results are available to us.

**Comment by shehzan10** [comment]
Ok I'll shortly merge both those PRs into the hotfixes branch. You can send those off for confirmation. Once its ok from there, we'll merge it into master over the weekend.

**Comment by ghisvail** [comment]
Ok let me know when the merging is done and I'll update the packaging with the corresponding patches.
