### ISSUE TITLE
CUDA examples libafcuda - libnvvm version mismatch

### ISSUE THREAD

**Issue by aelialper** [arrayfire/arrayfire#1019]
The examples do compile with CUDA (version 7.5), but when I try to run them I get the following error: 

dyld: Library not loaded: @rpath/libnvvm.3.dylib
  Referenced from: /usr/local/lib/libafcuda.3.dylib
  Reason: Incompatible library version: libafcuda.3.dylib requires version 3.0.0 or later, but libnvvm.3.0.0.dylib provides version 0.0.0
Trace/BPT trap: 5

**Comment by shehzan10** [comment]
Did you append the NVVM path to your DYLD_LIBRARY_PATH? It should be as follows. 
```
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/usr/local/cuda/nvvm/lib64/:
```

**Comment by aelialper** [comment]
The DYLD_LIBRARY_PATH and the DYLD_FALLBACK_LIBRARY_PATH variables are set, sorry I should have told you what I did already in the first place. Output of otool -L shows the following:

@rpath/libnvvm.3.0.0.dylib (compatibility version 0.0.0, current version 0.0.0)

And the error message says that it requires 3.0.0, so there is one discrepancy there, relevant or not... Only the _cuda binaries have this issue as far as I can tell.

**Comment by shehzan10** [comment]
The information you have provided is consistent with what I'm seeing on our build machine. Unfortunately, our build machine does not have CUDA device so we do not run it through its paces regularly.

From what I understand its a bug from CUDA 7.5. If you see the same lib in CUDA 7.0, it shows the correct compatibility and current version.
```
otool -L /Developer/NVIDIA/CUDA-7.0/nvvm/lib/libnvvm.dylib 
/Developer/NVIDIA/CUDA-7.0/nvvm/lib/libnvvm.dylib:
        @rpath/libnvvm.3.dylib (compatibility version 3.0.0, current version 3.0.0)
```

If you have CUDA 7 installed, you can simply change the NVVM path to point to CUDA 7. The NVVM libs have remained the same between 7.0 and 7.5 so this should work in theory.

Let me know if this works.

**Comment by pavanky** [comment]
@umar456 Can you look at this ?

**Comment by pavanky** [comment]
@aelialper Can you tell us which version of ArrayFire you are using ? And also let us know how you installed it ? (i.e. build from source or did you use the installer ?)

**Comment by aelialper** [comment]
I installed using the binary installer about two weeks ago, and I'm pretty sure I didn't do anything else in between now and then. Here are the versions I found on my machine:

/usr/local/lib/libafcpu.3.1.0.dylib
/usr/local/lib/libafcpu.3.dylib
/usr/local/lib/libafcpu.dylib
/usr/local/lib/libafcuda.3.1.0.dylib
/usr/local/lib/libafcuda.3.dylib
/usr/local/lib/libafcuda.dylib
/usr/local/lib/libafopencl.3.1.0.dylib
/usr/local/lib/libafopencl.3.dylib
/usr/local/lib/libafopencl.dylib

**Comment by umar456** [comment]
Works on my machine™.

This is using a clean install of the CUDA Toolkit 7.5.18 and the latest ArrayFire(v3.1.1) binaries from our website on OSX 10.9.5

```
otool -L /usr/local/lib/libafcuda.3.1.1.dylib                                                                                                                                   !10799
/usr/local/lib/libafcuda.3.1.1.dylib:
        @rpath/libafcuda.3.dylib (compatibility version 3.0.0, current version 3.1.1)
        @rpath/libcudart.7.5.dylib (compatibility version 0.0.0, current version 7.5.18)
        @rpath/libcublas.7.5.dylib (compatibility version 0.0.0, current version 7.5.18)
        @rpath/libcusolver.7.5.dylib (compatibility version 0.0.0, current version 7.5.18)
        @rpath/libcufft.7.5.dylib (compatibility version 0.0.0, current version 7.5.18)
        @rpath/libnvvm.3.0.0.dylib (compatibility version 0.0.0, current version 0.0.0)
        /usr/local/cuda/lib/libcuda.dylib (compatibility version 1.1.0, current version 7.0.29)
        @rpath/libforge.dylib (compatibility version 0.0.0, current version 0.0.0)
        /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
        /System/Library/Frameworks/AGL.framework/Versions/A/AGL (compatibility version 1.0.0, current version 1.0.0)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)

  % ./test
ArrayFire v3.1.1 (CUDA, 64-bit Mac OSX, build 92e08e9)
Platform: CUDA Toolkit 7.5, Driver: CUDA Driver Version: 7050
[0] GeForce GT 750M, 2048 MB, CUDA Compute 3.0
a
[3 3 1 1]
    0.7402     0.9690     0.6673
    0.9210     0.9251     0.1099
    0.0390     0.4464     0.4702
```

Try installing the latest version of ArrayFire and make sure you have the latest CUDA install. Hopefully that will fix the issue.

If that doesn't work you could try to change the install name on the libafcuda.dylib.
```
install_name_tool /usr/local/lib/libafcuda.3.1.1.dylib -change @rpath/libnvvm.3.0.0.dylib /usr/local/cuda/nvvm/lib/libnvvm.3.0.0.dylib
```

**Comment by shehzan10** [comment]
Umar is right. This should work with 3.1.1.

> /usr/local/lib/libafcuda.3.1.0.dylib
> /usr/local/lib/libafcuda.3.dylib
> /usr/local/lib/libafcuda.dylib

CUDA 7.5 build for afcuda was added with v3.1.1. afcuda v3.1.0 was built with CUDA 7. Hence you are seeing the error.

**Comment by aelialper** [comment]
Thank you for your help, I will reinstall and we'll go from there :)
