### ISSUE TITLE
Support for O(1) median filter

### ISSUE THREAD

**Issue by maxineliuqun** [arrayfire/arrayfire#1021]
Hi,

I am using a median filter with the kernel size 129 * 129 for a customer of mine. The traditional median filter is in the complexity of O(n^2logn), and even I use arrayFire median filter, it still runs for 30 mins. Here is a well-known paper that can run median filter with O(1) complexity (http://vision.gel.ulaval.ca/~perreaul/publications/Id699_2007.pdf). OpenCV is using this algorithm, and is very fast. I am thinking if arrayFire could implement this algorithm into the median filter, a lot of users could benefit from it. The algorithm currently only supports 8 bit image, but lots of people are trying to use it on 16 bit images, and so far I have not seen anywhere does 16 bit yet. So if there is anyway arrayFire could also look into that, it will be awesome. Just a random feature request. Thanks!

**Comment by pavanky** [comment]
That is an approximate algorithm and seems to be fairly sequential. It may not be possible to do this in constant time on the GPU.
