### ISSUE TITLE
Design:  out paramter to af_add and other functions

### ISSUE THREAD

**Issue by Pascal-J** [arrayfire/arrayfire#1024]
the call,
 af_add (aptr, aptr, bptr, 0) is an attempt to have the result of add overwrite the lhs argument.

the operation does not raise an error, but accessing aptr afterwards does. the "feature request behaviour" that I'm not sure is possible with current interface:

if out = 0, create new afarray  
if out points to existing afarray (part I'm unsure is possible), then "overwrite" the contents of that afarray

openssl's BigNumber library achieves this functionality by having a pointer to pointer interface for its BN structures (BNs are internal arrays that are polynomial representation of a big integer).  This has no impact on caller, and what the caller is pointing to can be "changed behind the scenes" (create new array, have aptr point to new array, release old aptr array)

**Comment by pavanky** [comment]
@Pascal-J There is no easy way to check for "existing af_array". If the output is not initialized properly to any value, it can randomly point to a pre-allocated pointer. If that occurs you are introducing incorrect releases of memory locations.

The current behavior replaces the array being pointed and **leaks** memory equivalent to the old pointer. It does not crash.

The out parameter is a pointer to a pointer, so you should be calling something like this:

```
af_add(&aptr, aptr, btr, 0); // NOT af_add(aptr, aptr, bptr, 0);
```

**Comment by pavanky** [comment]
Also the behavior you are asking for is to trivial to implement in a language wrapper. This is exactly what we are doing for the Java wrapper.
