### ISSUE TITLE
ArrayFire to OpenGL

### ISSUE THREAD

**Issue by rggjan** [arrayfire/arrayfire#1029]
Is it possible to go from ArrayFire to OpenGL and back using an AMD graphics card?

There is an article on how to do it using CUDA (http://arrayfire.com/remote-off-screen-rendering-with-opengl/). Any hints on using a similar method for OpenCL, so it can be used cross-platform?

What I would like to do in the end is take an af::array, convert it to an OpenGL texture and render it with my custom shader to the screen or to another texture (assuming a given OpenGL context, for example from Qt).

**Comment by 9prady9** [comment]
@rggjan 
As per the current state of the ArrayFire framework, it is not possible to do this over OpenCL backend. Reason being, currently we do not expose the API necessary to allow the user to set an OpenCL context or pass on an OpenGL context for sharing. The issue #1002 is related to the same topic. Once we have the functionality being discussed in #1002 implemented in ArrayFire, you would be able to do what you explained.

Having said that, can you please explain in detail (if that is possible) what this custom shader is doing? 

ArrayFire uses OpenGL-Interoperability for it's graphics. If your custom shader is doing something that others might also use, we are glad to add it as an option for [`af::image`](http://www.arrayfire.com/docs/classaf_1_1Window.htm#aed174450be6db4dfa5ef65b7baccbe57) function in ArrayFire. As of now, we can do the following while displaying an array as image in ArrayFire.
* Set a [ColorMap](http://www.arrayfire.com/docs/defines_8h.htm#a553ceda8a1d8946efac3b08e642574ae) for image display
* Request the ArrayFire to maintain aspect ratio of the image while displaying.

However, if you are planning on use ArrayFire as compute backend for some Qt application, you would have to some data management (copying etc.) like [this](https://github.com/9prady9/wildfire) application (This app is still a work in progress, so it might not be doing everything in an ideal way).

**Comment by rggjan** [comment]
Thanks for the explanations.

My use case is actual 3D rendering: I would like to process an image (out of a video stream) with arrayfire functions, and then use that as a texture in an interactive 3D OpenGL scene.

I don't think rendering triangles and polygons with arrayfire makes a lot of sense, so I would like to go with direct OpenGL for that.

I can currently do this by copying the data from an af::array to the CPU and uploading it again to the GPU as a texture, but that seems like wasted time to me, since it was on the GPU memory anyway. 

(From what I see in your sample application, this is similar to what I want to do. But I see you have the same problem and need to download to CPU and upload again to GPU as a texture...)

**Comment by 9prady9** [comment]
Agree, we currently do not have the capability to render polygons or 3D scene directly through our graphics API. Hopefully, we will reach there at some point in future.

Just to remind you again, the above discussed issue is the case with OpenCL backend only, CUDA works fine since it doesn't need to expose context and related attributes for OpenGL interoperability to work.

**Comment by rggjan** [comment]
Yes, thanks for the reminder. However, we need to run our code also on AMD graphics cards, so the CUDA solution only works in a limited number of cases for us...

**Comment by 9prady9** [comment]
Ah, makes sense.

**Comment by 9prady9** [comment]
@rggjan PR #1140 has been merged into devel now. If you use devel branch and build an executable, in that build of ArrayFire you should be able to do what we were discussing earlier.

The first stable release with this feature will be 3.3.0 release.

**Comment by rggjan** [comment]
Great, thanks :)

**Comment by pavanky** [comment]
@rggjan This is now possible by creating your own OpenCL-OpenGL interop context and adding it to arrayfire.

@bkloppenborg has an example [over here](https://github.com/bkloppenborg/arrayfire-interop-examples/blob/master/opengl/afopengl-opencl.cpp).

We are going to create a blog post / tutorial out of it at some point. I am closing this issue for now. If you feel like this does not resolve your problem please let us know so we can investigate it further.

**Comment by rggjan** [comment]
Awesome, thanks :)
