### ISSUE TITLE
Convolution inside GFOR

### ISSUE THREAD

**Issue by aelialper** [arrayfire/arrayfire#1036]
When I try to do convolution inside a GFOR loop, I get an exception. The convolve documentation says it does up to 3D, and it seems like the 4th dimension is somehow also the "gfor" dimension.  So how do I batch process the convolution in this scenario:

```C++
array A = array(n,m,p);
array kernel = gaussianKernel(k, k);
af_print(A); // prints with dimensions [m, n, p, 1]

gfor(seq ii, p)
{
     af_print( A (span, span, ii);  //prints with dimensions [m,n,1,p]
     array C = convolve(A, kernel); // terminates with ArrayFire Exception(203): Invalid input size
}

```

**Comment by 9prady9** [comment]
Are you trying to batch the data along both 3rd and 4th dimension ? or just 3rd dimension - in this case what is the 4th dimension data holding (for 2d convolution with 2d kernel - Array size [m, n, 1, p] doesn't make much sense ?)

**Comment by pavanky** [comment]
@aelialper you need to use `convolve2` for 2D convolution. The regular `convolve` does not support batch mode.

As @9prady9 mentioned you do not need GFOR for this case. What you want can simply be done like so:

```
array C = convolve2(A, kernel);
```

**Comment by aelialper** [comment]
Yeah, I have to admit that it didn't occur to me to break the loop, convolve, and then restart another loop. Thank you.
