### ISSUE TITLE
Random test failures on arm64 builds

### ISSUE THREAD

**Issue by ghisvail** [arrayfire/arrayfire#1038]
It was [reported](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=800384) to me that the Debian autobuilders experienced random test failures for `arm64`. Each time the build was done on a different machine and the failing test was different. The package eventually build successfully but this is probably symptomatic of a problem.

All the logs are available [here](https://buildd.debian.org/status/logs.php?pkg=arrayfire&ver=3.1.2%2Bdfsg1-1&arch=arm64).

**Comment by shehzan10** [comment]
All the tests in the log that fail are SEGFAULTs that are happening after the tests pass successfully. I'm not sure I can pin point this without having access to one of these type of architectures.

Internally, we test on the tegra which is an armv7l (32 bit) and do not see any such issues.

**Comment by ghisvail** [comment]
> without having access to one of these type of architectures.

I understand. May I propose to leave this issue open, and wait and see what happens with the next couple of releases.

I will soon be pushing an update which will enable builds of ArrayFire for architectures which do not have OpenBLAS. Maybe those will provide us with better pointers as to where the potential problem is. Then, you guys can decide for the best course of actions.

Sorry I cannot be more helpful on that one.

**Comment by pavanky** [comment]
@ghisvail Can you tell us what board is being used by Debian for building 64 bit ARM architectures ? We might consider getting one.

**Comment by ghisvail** [comment]
No idea, I will ask them and report back.

**Comment by ghisvail** [comment]
Information about our `arm64` port are [here](https://wiki.debian.org/Arm64Port).

They mention 2 particular machines used by the porters, [this](https://db.debian.org/machines.cgi?host=asachi) and [this](https://db.debian.org/machines.cgi?host=turfan). Both seems to use the [following board](https://wiki.ubuntu.com/ARM/Server/Install/Mustang).

Hope this helps.

**Comment by pavanky** [comment]
@ghisvail Thanks for that information, We will look into it.

**Comment by ghisvail** [comment]
The new upload (`3.1.2+dfsg1-2`) built the first time this time around on `arm64`. The difference is that we now use standard BLAS / LAPACK for the build instead of OpenBLAS to build on more architectures. OpenBLAS can be selected at install time via `update-alternatives`.

**Comment by ghisvail** [comment]
It is probably unrelated to this issue but I wanted to clarify the difference between the latest build and the one I reported the bug from.

**Comment by ghisvail** [comment]
This issue was not reproduced for the 3.2.x series of packaging. Closing.
