### ISSUE TITLE
Support for 1D median filter

### ISSUE THREAD

**Issue by maxineliuqun** [arrayfire/arrayfire#1039]
Does ArrayFire support 1D median filter? It looks like that the function "af::medfilt" only supports 2D images. Here is a sample code:
		float a[] = { 1, 2, 3, 4, 5, 6, 7, 8, 9 };
		af::array A(9, a);
		af::print("orig A: ", A);
		af::array B = af::medfilt(A, 3, 1);
		af::print("filtered B: ", B);
It breaks on me in the memory. 

Thanks!

**Comment by 9prady9** [comment]
@maxineliuqun Yes, your observation is correct - currently, `af::medfilt` supports only 2D square filter sizes.

**Comment by pavanky** [comment]
This is fixed in devel
