### ISSUE TITLE
undefined reference to `af_save_image_memory' when freeimage is absent

### ISSUE THREAD

**Issue by svenstaro** [arrayfire/arrayfire#1040]
So when compiling the newest release (also happens on git master) I get this:

    [ 45%] Linking CXX executable approx1_cpu
    ../src/backend/cpu/libafcpu.so.3.2.0: undefined reference to `af_save_image_memory'

Using gcc 5.2.

make verbose=1 output is:

    [ 45%] Linking CXX executable approx1_cpu
    cd /home/svenstaro/src/arrayfire/build/test && /usr/bin/cmake -E cmake_link_script    CMakeFiles/approx1_cpu.dir/link.txt --verbose=1
    /usr/bin/c++   -O3 -DNDEBUG   CMakeFiles/approx1_cpu.dir/approx1.cpp.o  -o approx1_cpu -rdynamic ../src/backend/cpu/libafcpu.so.3.2.0 -pthread ../third_party/gtest/src/googletest-build/./libgtest.a   ../third_party/gtest/src/googletest-build/./libgtest_main.a -Wl,- rpath,/home/svenstaro/src/arrayfire/build/src/backend/cpu:/home/svenstaro/src/arrayfire/build/third_party/ forge/src/forge-ext-build/src -Wl,-rpath-link,/home/svenstaro/src/arrayfire/build/third_party/forge/src/forge- ext-build/src

**Comment by pavanky** [comment]
Can you cd into your build directory and run "cmake .." and build again ?

**Comment by pavanky** [comment]
These kind of issues arise when we add new functions to our library that happen to be in new files. CMake does not seem to pick up the new files when building arrayfire.   

running "cmake .." should pick up the new files and fix the compilation issues.

**Comment by svenstaro** [comment]
Well this is a brand new clone so I'm not sure it will result in any changes but I will try.

**Comment by pavanky** [comment]
Ah crap, I see what is happening now. Would it be possible for you to install free image on your machine as a temporary work around ? The symbols implemented when freeimage is not available is still using an older API causing the issue.

**Comment by svenstaro** [comment]
Hang on I will try that.

**Comment by pavanky** [comment]
@svenstaro I am in charge of [the aur package](https://aur4.archlinux.org/packages/arrayfire-git/) as well. I am going to try and implement the suggestions you've made there :)

**Comment by svenstaro** [comment]
Oh cool stuff. I'm in the process of creating an official package in Arch because I like this lib.

**Comment by pavanky** [comment]
@svenstaro Ah much appreciate it :D  I see that you are an Arch developer. Let me know if you want me to hand off the AUR package to you if you want to experiment a bit.

**Comment by svenstaro** [comment]
Nah man it's cool, as long as you do regular releases I'm fine with the stable release. I would just recommend you to always use devtools to build your package even in AUR to build them in an isolated environment. Instead of running makepkg, run extra-x86_64-build. It will error for your package because it is not self-contained and depends on the users system which it shouldn't. I will show you my official package to show you what I mean once it finishes building. :P

**Comment by pavanky** [comment]
@svenstaro Thanks for the feedback, I will look forward to it.

**Comment by pavanky** [comment]
This issue will be on our hotfixes branch pretty soon and in the master in a week or so.

**Comment by pavanky** [comment]
The fix is in hotfixes-3.1.3 branch
