### ISSUE TITLE
Bugs in OpenCL kernels when offset is not added to inputs

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#1042]
Potentially affected kernels include:

- [x] assignKernel (assign.cl)
- [x] locate_features (fast.cl)
- [x] convert (hsv_rgb.cl)
- [x] iir_kernel (iir.cl)
- [x] indexKernel (index.cl)
- [x] lookupND (lookup.cl)
- [x] nearest_neighbour_unroll (nearest_neighbour.cl)
- [x] nearest_neighbour (nearest_neighbour.cl)
- [x] select_matches (nearest_neighbour.cl)
- [x] initial_label (regions.cl)
- [x] scan_dim_kernel (scan.cl)
- [x] select_kernel (select.cl)
- [x] susan (susan.cpp)
- [x] get_out_idx_kernel (where.cl)
- [x] wrap_kernel (wrap.cl)

**Comment by pavanky** [comment]
@shehzan10 do you want to have a go at this ?

**Comment by pavanky** [comment]
nvm I have begun some work on this

**Comment by shehzan10** [comment]
Closed by #1061
