### ISSUE TITLE
Fix windows build with blas excluding MKL

### ISSUE THREAD

**Issue by shehzan10** [arrayfire/arrayfire#1047]
Currently the builds on windows fail when not using MKL.
This is probably because of the cmake options/defines.

**Comment by shehzan10** [comment]
Corresponding user forum post: https://groups.google.com/d/msg/arrayfire-users/vpkoOMR4_8k/0s32iIWmBgAJ

**Comment by pavanky** [comment]
Fixed in hotfixes-3.1.3
