### ISSUE TITLE
Perspective image transforms with ArrayFire?

### ISSUE THREAD

**Issue by rggjan** [arrayfire/arrayfire#1049]
Is there a possibility to do perspective transformations with arrayfire?

There is a function `af::transform`, but it only allows a 3x2 matrix instead of a 3x3 matrix that would be required for perspective transformations....

**Comment by pentschev** [comment]
Hi @rggjan,

I'm planning to add such functionality in the next couple of weeks. Meanwhile, it's fairly simple to do that on top of ArrayFire:

Consider you have four 3D points (3rd dimension is set to 1.0 for all points in this case),
```
    0.0000     0.0000     1.0000
    0.0000   700.0000     1.0000
 1000.0000   700.0000     1.0000
 1000.0000     0.0000     1.0000
```

and a 3x3 transformation matrix,
```
    0.5805    -0.0030    -0.0000
    0.0086     0.5853     0.0000
    9.9359   -16.8133     0.5739
```

The implementation would look like:
```cpp
af::dim4 inDims(4, 3);
float h_in[4*3] = { 0.f,   0.f, 1000.f, 1000.f, 
                    0.f, 700.f,  700.f,    0.f,    
                    1.f,   1.f,    1.f,    1.f };  

af::dim4 HDims(3, 3);
float h_H[3*3] = { 0.580474f, 0.008611f,   9.935852f,
                  -0.003009f, 0.585275f, -16.813293f,
                  -0.000001f, 0.000009f,   0.573907f };

array in(inDims, h_in);
array H(HDims, h_H);

array w = 1.f / matmul(in, H(span, 2));
array xt = matmul(in, H(span, 0)) * w;
array yt = matmul(in, H(span, 1)) * w;
```

In the above sample, xt and yt will both have 4 elements (i.e., x and y coordinates for 4 points), with the transformed points.

I will leave this thread open until a function to perform this operation is added to ArrayFire and hope this helps you for now.

**Comment by rggjan** [comment]
Hi @pentschev thanks for the code! I think thats a good start. What's missing here is of course all the interpolation logic etc for actually interpolating the pixels of an image, and not just 3D vectors.

Looking forward to the 3.2.0 :)

**Comment by pentschev** [comment]
Hi @rggjan, just to be sure we are on the same page, besides the perspective transform (that transform only the coordinates), you would also like to have a function that is sometimes referred as [warp perspective] (http://docs.opencv.org/modules/imgproc/doc/geometric_transformations.html#warpperspective), is that right?

**Comment by rggjan** [comment]
Yes, exactly.

As far as I can see, [af::transform](http://www.arrayfire.com/docs/group__transform__func__transform.htm#ga3677c5a534ca50a9c8a2611fe0728fd8) is pretty much the same as [cv::warpAffine](http://docs.opencv.org/modules/imgproc/doc/geometric_transformations.html#warpaffine), and what would be cool to have is an arrayfire function similar to [cv::warpPerspective](docs.opencv.org/modules/imgproc/doc/geometric_transformations.html#warpperspective) also.

I guess the two functions are very similar, so I guess most of the code of af::transform could be reused...

**Comment by rggjan** [comment]
Looking at the af::transform [cuda kernel](https://github.com/arrayfire/arrayfire/blob/devel/src/backend/cuda/kernel/transform_interp.hpp#L48) for example, I assume its just the lines 48 to 53 that would need to be adapted to the more general transformation matrix.

**Comment by pentschev** [comment]
Thanks for pointing that out, I think you are right, the changes to those lines may be enough. I will certainly try to get this done for 3.2.0.

This thread should remain open until these two functions are implemented:
- [ ] Perspective Transform (compute new coordinates according to a 3x3 transformation matrix);
- [ ] Warp Perspective (interpolate image according to input coordinates and a 3x3 transformation matrix).

**Comment by pavanky** [comment]
@pentschev I am assuming this is done and present in devel?

**Comment by pavanky** [comment]
These features should be in current devel.
