### ISSUE TITLE
Can't find source code for PDE examples

### ISSUE THREAD

**Issue by mchandra** [arrayfire/arrayfire#1058]
Hi, are the following examples still available?

http://blog.accelereyes.com/blog/2013/07/03/arrayfire-examples-part-7-of-8-pde/

**Comment by pavanky** [comment]
We have not added the examples to the open source project yet. We have an issue to do that over here: https://github.com/arrayfire/arrayfire/issues/413

**Comment by 9prady9** [comment]
@mchandra 
Graphics functionality in ArrayFire 3.x is not on feature parity with v2.1 as of now. The example and the blog post you are looking at is published before 3.0 release. We plan to finish the required functions to implement this example by ArrayFire 3.2 release, which is going to be in another couple of weeks. You can follow the progress of these functions on this issue #1057 . As soon as these functions are implemented, we will add the related examples back into the repository.

**Comment by mchandra** [comment]
Thanks. I actually have zero interest in the graphics. My main curiosity is regarding how best to implement differential operators using arrayfire, which I was hoping to glean from those examples.

Should I be doing something like:
```
array x(n, host_array);
dx = shift(x, 1) - shift(x, -1);
```

**Comment by pavanky** [comment]
@mchandra You can find the old examples in here: https://github.com/pavanky/arrayfire_examples/tree/master/pde

The examples may some changes to work with ArrayFire 3.x because of API changes.

**Comment by pavanky** [comment]
As for differential operators, we have [diff1](http://www.arrayfire.com/docs/group__calc__func__diff1.htm), [diff2](http://www.arrayfire.com/docs/group__calc__func__diff2.htm) and [grad](http://www.arrayfire.com/docs/group__calc__func__grad.htm) which may be useful for you.

**Comment by mchandra** [comment]
Thanks for the code. Those functions will work if the underlying data is smooth, but if it has shocks, like in a compressible fluid simulation, then one needs to use slope limited derivatives. See slopeLim() in https://github.com/AFD-Illinois/grim/blob/master/src/reconstruct/reconstruct.c

It basically takes in three values, left, center and right and spits out the slope. I wonder how best that function can be implemented using arrayFire. This information would be very useful because there are a very large number of fluid codes that have routines exactly like the above.
