### ISSUE TITLE
Unified API: Add function to return WHICH backends are available

### ISSUE THREAD

**Issue by jramapuram** [arrayfire/arrayfire#1067]
Currently `af_get_backend_count` returns the number of available backends, however it would be useful to expose **which** backends are available (or separate functions for `af_is_cuda_available`, etc). This calculation is already being done internally during the function call.

**Comment by shehzan10** [comment]
I recommend changing [these](https://github.com/arrayfire/arrayfire/blob/devel/include/af/defines.h#L330) enums to values of 2^x, that way we can return an int which is the sum of all the enabled backends. This way we do not need to add a function/argument for each backend.

The API would then look like
```
int af::getAvailableBackends();
af_err* af_get_available_backends(int *);
```

An alternate to doing this is simply to use try catch as is done in the [unified/basic](https://github.com/arrayfire/arrayfire/blob/devel/examples/unified/basic.cpp) wherein a try-catch block can be used to do the same on the user side.

**Comment by jramapuram** [comment]
Yea, that should work well actually.
I'm currently doing the try/catch scenario, however seems kludgy to have to catch exceptions when the logic is already checking apriori.
