### ISSUE TITLE
convolution with 1D filters for 3D data

### ISSUE THREAD

**Issue by mchandra** [arrayfire/arrayfire#1074]
I need to perform convolve() on data with the input signal

signal(Nx, Ny, Nz, numberOfSignals)

with the following filters

float centralDiff[]  = { 1, 0,-1};
float forwardDiff[]  = { 1,-1, 0};
float backwardDiff[] = { 0, 1,-1};

where centralDiff, forwardDiff, and backwardDiff all need to be applied individually to Nx, Ny  and Nz.

What would the most efficient way to call convolve() to perform this operation? Should I be using gfor() in some way?

I'm wondering if there's an interface where separable filters can be applied, like say the column filter and row filter for 2D data.

Thanks,
Mani

**Comment by mchandra** [comment]
Would this be an optimal code for separable convolution along a single direction in 3D?

    float centralDiff[]  = { 1, 0,-1};
    float forwardDiff[]  = { 1,-1, 0};
    float backwardDiff[] = { 0, 1,-1};
    
    array centralDiff3DAlongX1(3, 1, 1, centralDiff);
    array forwardDiff3DAlongX1(3, 1, 1, forwardDiff);
    array backwardDiff3DAlongX1(3, 1, 1, backwardDiff);

    array filterX1 = af::constant(0, 3, 1, 1, 3);
    filterX1(span, span, span, 0) = centralDiff3DAlongX1;
    filterX1(span, span, span, 1) = forwardDiff3DAlongX1;
    filterX1(span, span, span, 2) = backwardDiff3DAlongX1;

    gfor(seg signalIndex, 0, numberOfSignals)
    {
      input = signal(span, span, span, signalIndex);
      output = convolve(input, filterX1);
      // output has shape (Nx, Ny, Nz, 3) with the last index containing central, forward and backward differences along Nx
    }

**Comment by shehzan10** [comment]
Have you looked at http://www.arrayfire.com/docs/group__convolve__mat.htm?
Also, the way you are creating your filter is highly redundant. You can simply do
```
float h_filter[]  = { 1, 0,-1,
                      1,-1, 0,
                      0, 1,-1};
array filterX1(3, 1, 1, 3, h_filter);
```

**Comment by mchandra** [comment]
Oops you're right, your code is far more elegant. 

The following code is based on the documentation you linked to

```
gfor(seg signalIndex, 0, numberOfSignals)
{
  input = signal(span, span, span, signalIndex);
  output = convolve(input, filterX1);
  // input has shape (Nx, Ny, Nz, 1)
  // output has shape (Nx, Ny, Nz, 3) 
}
```

Is the above ok or do you think there's a better way to use convolve()? Many-to-many batched mode perhaps, where the 3 filters are applied to numberOfSignal inputs simultaneously, instead of using gfor() over the signals? 

Also, when convolve() is called, is it evaluated immediately? or does the JIT compiler assess where the output is being used and then evaluate at the end?

Thanks

**Comment by pavanky** [comment]
`convolve` does not work inside gfor. You should be using `convolve3` for this.

**Comment by mchandra** [comment]
Can `convolve3` be used in the Many-to-Many batched mode? i.e., `Nfilters` with sizes `(N1, N2, N3)` applied to an array with dimensions `(Nx, Ny, Nz, Nsignals)`

Or would it be better to simply write a `for` loop over `Nsignals`?

Thanks

**Comment by pavanky** [comment]
You don't need a for loop. Batch mode should be available for this function.

**Comment by mchandra** [comment]
Is the following correct:
Inputs:
- filter with dimensions  `(N1, N2, N3, Nfilters)`
- signal with dimensions `(Nx, Ny, Nz, Nsignals)`

Output:
- array with dimensions `(Nx, Ny, Nz, Nfilters x Nsignals)`

**Comment by pavanky** [comment]
Sorry I misunderstood your question. 

What you are asking for is not possible.

**Comment by mchandra** [comment]
Yes, you're right. I tried and it failed because of invalid input sizes. I ended up looping over the signals, while using the batched many filter mode.

You can close the issue.

Thanks
