### ISSUE TITLE
 solve() inside gfor() for a large number of independent matrices 

### ISSUE THREAD

**Issue by mchandra** [arrayfire/arrayfire#1075]
Right now, `solve()` is not optimized to solve for a large number of independent linear systems `A_i x_i = b_i`, where `i = 1,..., N`

`solve()` uses `magma_getrf_gpu()` (https://github.com/maxhutch/magma/blob/master/src/sgetrs_gpu.cpp) from Magma as its backend. Magma also has `magma_sgetrs_batched()` (https://github.com/maxhutch/magma/blob/master/src/sgetrs_batched.cpp) which could be used for batch computations (like those inside gfor?)

Possibly connected issue: https://github.com/arrayfire/arrayfire/issues/483

Relevant post on forums: https://groups.google.com/forum/#!topic/arrayfire-users/RZLKGjsJR3g

Details of the batched implementation in Magma:
1) http://icl.cs.utk.edu/news_pub/submissions/batchedlu.pdf
2) http://on-demand.gputechconf.com/gtc/2015/presentation/S5476-Stanimire-Tomov.pdf (starts from slide 36)

**Comment by pavanky** [comment]
@mchandra We use a modified version of clmagma only for OpenCL backend. We use cusolver for CUDA and lapack / mkl for CPU backends. The sgetrs_batched is only supported in magma (not clmagma) as far as I can tell. It would be really hard for us to add a new dependency for just one function.

However we can implement a faster (less stable) implementation of solve for small matrix sizes using Gaussian elimination. We had this functionality in 2.1 and we can try to implement it in the current version as well. It would be helpful if you can tell us the sizes of matrices you are looking at.

**Comment by mchandra** [comment]
I have about `10^5` dense matrices with size `10 x 10`

Note that cuSolver has a batched linear solver too: 
 - http://devblogs.nvidia.com/parallelforall/parallel-direct-solvers-with-cusolver-batched-qr/
 - http://docs.nvidia.com/cuda/cusolver/#glu-intro
