### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [arrayfire/arrayfire#108]
Would you like to [replace any double quotes](https://github.com/arrayfire/arrayfire/blob/617a0de682fb0ba485ce0f9c06b2c1f9edf78d8d/include/arrayfire.h#L11 "Check header file inclusion style") by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html "Source file inclusion") from [the section "16.2 Source file inclusion"](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf "C++ working draft") in the standard specification for the programming language "C++".
```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```

* How do you think about to avoid "a duplicated file search" here?
* Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html "Include syntax description") for header files of your software?

**Comment by pavanky** [comment]
@elfring While that policy is solid in general, `arrayfire.h` should include the header files from the local directory. This is the reason we enforced double quotes instead of the angle brackets. In all other places we follow the standard you mention.

**Comment by elfring** [comment]
There are different opinions about the handling of the involved implementation-defined behaviour.
* I would generally prefer to exclude the potential for the inclusion of header files from unexpected directories. Can such a security detail become a bit more important?
* Is there a speed difference measurable if a file is not found outside the specified include directories and the search will be retried with "the angle brackets inclusion method"?

**Comment by pavanky** [comment]
> I would generally prefer to exclude the potential for the inclusion of header files from unexpected directories. Can such a security detail become a bit more important?

Can you elaborate on this. From my reading of the spec, the compiler will look for `af/defines.h` in the same directory containing `arrayfire.h` is located. *Not* user code.

**Comment by elfring** [comment]
Can it occasionally happen that the "same directory" is not the include folder that you really want to reuse for your application programming interface?

**Comment by pavanky** [comment]
No. It can not from what I understand.

Unless there is a concrete example rather than a thought experiment, this issue is staying closed.
