### ISSUE TITLE
Copy part of array into another array

### ISSUE THREAD

**Issue by mchandra** [arrayfire/arrayfire#1080]
The following seems to give an error:

```
array A = af::randu(10, 10, 10);
array B(10, 10);

B(span, span) = A(0, span, span); /* ArrayFire Exception(203): Invalid input size */
```
How do I copy a subsection of A into B?

Thanks,
Mani

**Comment by shehzan10** [comment]
Although the total number of elements may be the same, the order is not.
You are trying to copy a [1 x 10 x 10] section into a [10 x 10] array.

There are many options to get around it, the simplest one is to do something like:
```
array A = af::randu(10, 10, 10);
array B(10, 10);

B(span, span) = moddims(A(0, span, span), 10, 10);
```

I must point out that when doing indexing, it is best to use the constant value at the highest dimension possible. This results in more memory being coalesced. The way indexing is shown in your example is close to the worst case scenario. There is no pair of elements in such indexing that are sequential. To get from one element to the next, a stride has to be made.

So ideally you want to do something like `B(span, span) = A(span, span, 0);`

**Comment by mchandra** [comment]
Ok thank you. 

To deal with memory coalescing is precisely why I want to copy to B. I have a bunch of operations I want to perform on the data and so instead of doing something like
```
array B = A(0, span, span);
/* Now do work on B */
```
, I want to make a copy and then work on it.

Is the following code equivalent to what you wrote?
```
array tmp = reorder(A, 1, 2, 0);
array B = tmp(span, span, 0);
```

**Comment by shehzan10** [comment]
Well, sometimes you just can't avoid doing some bad memcpys. So its best to keep them to a minimum.

Yes the reorder would do the same thing.

**Comment by mchandra** [comment]
Thanks!

Before closing the issue, I'd just like to point out here for future reference that in arrayfire, even if the array is 1D, 2D, or 3D, when using af_print, it always shows up as a 4D array with the later dimensions set to 1.

**Comment by shehzan10** [comment]
Yes thats how the data is always stored. The higher dimensions are set to singletons.

**Comment by pavanky** [comment]
@mchandra If you want to avoid non-coalesced accesses, I'd suggest using reorder and then indexing on third dimension in the following manner.

```
array B = reorder(A, 1, 2, 0);
// Use B(span, span, 0) instead of A(0, span, span) from now on.
```
