### ISSUE TITLE
Modify the loadImageT functions to specify the return value type.

### ISSUE THREAD

**Issue by umar456** [arrayfire/arrayfire#1082]
The current implementation of the loadImageT function will return a different type based on the format of the input image. This can cause issues in programs which will accept images from its users.

Change the loadImageT function to specify the output image type. If no type is specified then revert to loadImage functionality.

Also change the name of the function. The T is ambiguous. This function could keep the same name as the original function in C++ but with an extra parameter.

**Comment by pavanky** [comment]
@umar456 The goal of loadImageT was to *not* change the data type from what is stored internally. I agree with changing the name, but what you are suggesting should ideally be a different function.

For example:

- loadImage -- loads as chars or floats only
- loadImageNative/loadImageT -- uses native type
- loadImageType or something else -- User specifies the data type.

I strongly disagree with merging the last two functions.

**Comment by shehzan10** [comment]
I agree with @pavanky. The goal of this function is to load the image as-it and not mess with the type/data.

I agree we should change name. I thought this would be done as a part of the PR review but got missed.
Change output type, I disagree. This is essentially the same as using a `.as` on the result array. It does not need to be a part of the load image function. I dont even think we should have the `loadImageType` function that @pavanky mentions. Users can convert the data fairly easily if they so wish.

```
array ftype = u8type / 255.0f;  // converts u8 to f32
array ftype = u16type / 65535.0f;  // converts u16 to f32
array u16type = u8type * 255.0f; // convert u8 to u16
```
