### ISSUE TITLE
Exception thrown in cl::Platform::getDevices when using pocl

### ISSUE THREAD

**Issue by pisto** [arrayfire/arrayfire#1086]
The code uses `clGetDeviceIDs` to find the number of available devices, then allocate an array of `cl_device_id`s and call it again to get the IDs. However, if the platform does not contain GPU devices, an exception will be thrown because `n == 0` and `clGetDeviceIDs` will return `CL_INVALID_VALUE` because the array of `cl_device_id`s will be non-null. Cp https://www.khronos.org/registry/cl/sdk/1.0/docs/man/xhtml/clGetDeviceIDs.html

**Comment by pavanky** [comment]
@pisto This is actually a bug in pocl that I [sent a patch to](https://github.com/pocl/pocl/commit/bfee547c3233656d831fc847354d52463e7d6f73) a while ago.  

If you are using the latest release, it should be fixed.

**Comment by pisto** [comment]
Are you sure? It looks to me that the OpenCL is used incorrectly and it is right that `clGetDecideIDs` returns an error in that case. However, I didn't think about it thoroughly.

**Comment by pavanky** [comment]
@pisto We are using cl.hpp which is distributed by Khronos. The error you are seeing is from an exception being thrown from that file. We are not doing anything special in arrayfire that might break it.

 I sent the patch upstream which I thought was the fix and was accepted by upstream.
