### ISSUE TITLE
Installers built without graphics

### ISSUE THREAD

**Issue by mchandra** [arrayfire/arrayfire#1088]
Hi,

I'd like to request builds without graphics be made available alongside the regular builds. Many clusters don't have the required graphics libs installed and having builds with no graphics would be very convenient.

**Comment by pavanky** [comment]
@mchandra We are going to talk about this internally. But for now, no graphics installers are available CI from here: http://ci.arrayfire.org/userContent/Linux-MKL/ArrayFire-no-gl-v3.1.3_Linux_x86_64.sh

**Comment by mchandra** [comment]
Thanks! These builds are very helpful.
