### ISSUE TITLE
Results from out of bounds indexing is different in CUDA

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#1092]
```
int main()
{
    array a = af::iota(dim4(50, 1, 3)).as(s32);
    uint h_idx[7] = {0, 9, 49, 119, 149, 150, 151};
    array idx(7, h_idx);
    af_print(a);
    af_print(a(idx));
    return 0;
}
```

**Comment by pavanky** [comment]
@9prady9 The problem seems to be the trimIndex function in CUDA backend. More specifically the "abs(ret_val)". I am not sure why that is returning 0. This is causing the out of bounds outputs to be incorrect. Can you look into it?

**Comment by 9prady9** [comment]
@pavanky I really don't understand the error! `abs()` is indeed returning 0's. I did this `val > 0 ? val : -1*val` and it worked as expected. Below change is working as expected, shall we push that as fix ?
```patch
diff --git a/src/backend/cuda/utility.hpp b/src/backend/cuda/utility.hpp
index bae4cc7..e2cb90d 100644
--- a/src/backend/cuda/utility.hpp
+++ b/src/backend/cuda/utility.hpp
@@ -16,8 +16,8 @@ namespace cuda

 static __DH__ dim_t trimIndex(const int &idx, const dim_t &len)
 {
-    int ret_val = idx;
-    int offset  = abs(ret_val)%len;
+    dim_t ret_val = idx;
+    float offset  = fmod(fabs((float)idx), (float)len);
     if (ret_val<0) {
         ret_val = offset-1;
     } else if (ret_val>=len) {
```

**Comment by pavanky** [comment]
@9prady9 If you use fmod, anything above 2^24 will lose precision. I think the problem is occurring because abs is returning float in this particular case.

**Comment by 9prady9** [comment]
True & agree, which is precisely why i didn't send this fix directly. Not sure, one thing i have noticed is that, when i do `abs((long int)ret_val)` it gives correct abs value, but the later operation of modulo `%`  gives 0 always - which is the weird behaviour i was talking about towards end of my previous comment. I will dig more into this today again.
