### ISSUE TITLE
Generic Graph based Automatic Differentiation

### ISSUE THREAD

**Issue by jramapuram** [arrayfire/arrayfire#1098]
So tensorflow is out now. Any thoughts on paralleling graph based auto-differentiation in AF?
Would be really neat to have something like this that works via JIT.

**Comment by jramapuram** [comment]
Hey @pavanky , the reason I added it here is because it is a generic tool, not just ML related. Eg: someone wants to use af to run some physics flow models. That doesn't quite fit into the ML paradigm, but is still graph differentiation. Being able to run an af expression such as 
```c++
auto b = 2 * af::sin(a) +  3; 
auto derivative  = af::diff(b, a);
```
 is a non-ML item. It requires the building of a graph and derivating via application of the chain & product rule. A really good explanation is given my Chris Olah here: http://colah.github.io/posts/2015-08-Backprop/index.html

**Comment by pavanky** [comment]
Reopening the issue because the functionality could be implemented here eventually.

**Comment by bhack** [comment]
@pavanky Do you think that Arrayfire could backend tensorflow instead of Eigen library that is CPU and CUDA only?

**Comment by jramapuram** [comment]
+1

**Comment by pavanky** [comment]
@bhack It could be possible, but we haven't really optimized the CPU backend for performance yet. This could change in the future.

**Comment by bhack** [comment]
@pavanky Seems that their are going ahead with a Sycl eigen backend. See https://github.com/tensorflow/tensorflow/issues/22. What it is really missing in the opensource deeplearning scenario is a vendor neutral high performance cudnn like API implementation

**Comment by pavanky** [comment]
This is going to be dealt with in arrayfire-ml https://github.com/arrayfire/arrayfire-ml/pull/30
