### ISSUE TITLE
"gfor" on CPU backend

### ISSUE THREAD

**Issue by maxineliuqun** [arrayfire/arrayfire#1105]
Does "gfor" work on CPU backend? I know that it would not parallel the computation like what is on GPUs, but I assumed it would just do the sequential computation, like a regular "for" loop. However, I found that it actually crashed the program. Is that true? Just would like to confirm with you. Thanks!

**Comment by shehzan10** [comment]
GFor does work on the CPU backend, but as you rightly pointed out, it would be quite similar in performance to a for loop.

Without looking at your code I cannot tell you why its failing. If you can attach a code segment along with the error you are seeing, that would be helpful.

**Comment by pavanky** [comment]
Closing issue because there hasn't been any further information.
