### ISSUE TITLE
Operator max K values

### ISSUE THREAD

**Issue by botev** [arrayfire/arrayfire#1123]
It would be nice if there is an out of the box operator `max(K)`. This is very similar to `max`, but instead gives back not the maximum, but the K maximum values (and potentially having the same interface for returning the indexes of these values).

**Comment by shehzan10** [comment]
You can do a `sort` followed by indexing as:
```
array maxK = sort(input, 0, false)(seq(K));
```

You can also do the same thing with sortIndex and sortByKey.
Documentation: http://www.arrayfire.com/docs/group__sort__mat.htm

**Comment by Botev** [comment]
That is true, however it will definitely be a lot more computation for a complete sort, especially in the case where `k << n`, compared to a specialized operator.

**Comment by pavanky** [comment]
@Botev This kind of operation is relatively hard to achieve in parallel without performing the sort operation.

**Comment by Botev** [comment]
@pavanky However, essentially you need a partial sort, and more specifically you would prefer something like quick sort, where you can fastly discard and not sort big parts of the arrays. For instance when you partition the array, if the bigger partition has number of elements more than K you can automatically discard the lower partition.

**Comment by mlloreda** [comment]
@botev, this functionality has been implemented in [topk()](http://arrayfire.org/docs/group__stat__func__topk.htm) in ArrayFire v3.6.0.
