### ISSUE TITLE
Crash when using af::replace or af::select

### ISSUE THREAD

**Issue by rggjan** [arrayfire/arrayfire#1126]
When I execute the following code (which should be completely independent and have no side effects):

```
{
    int w = 100;
    int h = 100;
    int dim = 2; // Using dim=1 works fine!

    af::array diffs = af::constant(0, w, h, dim, s32);
    af::array vals = af::constant(128, w, h, dim, u8);
    af::array condition = vals==128;

    int version = 1;

    if (version == 1) // This makes it crash
      af::replace(diffs, condition, af::constant(0, w, h, dim, s32));

    if (version == 2) // This makes it crash
      diffs = af::select(condition, diffs, af::constant(0, w, h, dim, s32));

    if (version == 3) // This works fine!
      diffs = condition*diffs + (!condition)*af::constant(0, w, h, dim, s32);
  }
```

My program starts to crash (after some time) in a completely unrelated function, when I'm creating a new array (I'm sorry I cannot pin it down further):

```
af::array tmp(w, h, data_ptr);
```

Its a really bad crash: I get an arrayfire exception and a message from the NVidia driver, that it stopped and recovered. 

The arrayfire exception is:
```
Exception: ArrayFire Exception(998): Internal error
In C:\workspace\af_inst_source\src\api\cpp\array.cpp:139
```
and an image of some sort of stacktrace is attached.

![stacktrace](https://cloud.githubusercontent.com/assets/128554/11428618/9adfb37a-946d-11e5-9e7d-2907038f4ef9.PNG)

I think it must be a bug, because without these lines, my code runs perfectly fine. Even when using a "custom built" implementation (version 3) of replace, it works fine. Also, using only one dimension instead of two works fine. So I guess some global state or something that must break when using version 1 or 2. 

I'm using arrayfire 3.2.0 on Windows 10 64-bit.

**Comment by pavanky** [comment]
@rggjan We can not reproduce the problem with the code supplied here. If you are building arrayfire from source, can you build it in debug mode and display the error you are seeing ?

**Comment by rggjan** [comment]
I just did. You can see the stacktrace with debugging symbols in the attached screenshots (I can reproduce it every time and easily do more debugging if I can help):

![capture](https://cloud.githubusercontent.com/assets/128554/11472134/b7e29c58-976a-11e5-8279-d109297090e1.PNG)

All version work perfectly fine in the CPU backend. However, using the OpenCL backend also makes it crash (I have no debugging symbols for OpenCL yet):

![capture](https://cloud.githubusercontent.com/assets/128554/11472314/e7a021e4-976b-11e5-8150-ee1fb71f004e.PNG)

**Comment by pavanky** [comment]
Are you using any custom CUDA kernels in your program ?

**Comment by rggjan** [comment]
No, only "pure" ArrayFire. Some stuff in OpenGL runs at the same time, but thats completely independent (no shared context).

**Comment by pavanky** [comment]
Is there anyway we can get a stand alone code to reproduce this ?

**Comment by rggjan** [comment]
Ok, I tried to strip it down as much as possible. I can reliably reproduce it with the following code.

Using version 1 or 2 (as before), I get the following output:
```
0
1
2
ArrayFire Exception(998): Internal error
In C:\workspace\af_inst_source\src\api\cpp\array.cpp:938
```

Using version 3 works fine, and prints all numbers from 1 to 100.

The code might not make a lot of sense anymore at that point, since I tried to remove all parts not essential to the crash. (I hope I didn't introduce any out of boundary accesses or similar).

It was quite hard to remove all unneeded code, since I frequently had **bluescreens because the graphics card driver crashed** when executing version 1 or 2.

```
#include <arrayfire.h>
#include <cinttypes>

std::vector<std::pair<af::seq, af::seq>> Offsets() {
  return {
    {af::seq(0, af::end, 2), af::seq(0, af::end, 2)},
    {af::seq(0, af::end, 2), af::seq(0, af::end, 2)},
    {af::seq(0, af::end, 2), af::seq(0, af::end, 2)},
    {af::seq(0, af::end, 2), af::seq(0, af::end, 2)}
  };
}

void Scale(af::array image, af::array segmentation, af::array &image_scaled, af::array &segmentation_scaled) {
  int w_small = (segmentation.dims(0)+1)/2;
  int h_small = (segmentation.dims(1)+1)/2;
  int w = w_small*2;
  int h = h_small*2;

  segmentation_scaled = af::array(w_small, h_small, u8);
  image_scaled = af::array(w_small, h_small, 3, u8);

  segmentation = af::constant(0, w, h, 1);
  image = af::constant(0, w, h, 3);

  af::array zero_3 = af::constant(0, w_small, h_small, 3, f32);
  af::array gray_average = zero_3;
  af::array white_average = zero_3;
  af::array black_average = zero_3;

  af::array zero = af::constant(0, w_small, h_small, u8);
  af::array white_count = zero;
  af::array black_count = zero;

  for (auto &offset : Offsets()) {
    af::array val = segmentation(offset.first, offset.second);

    af::array white = (val == 0);
    af::array black = (val == 1);
    white_count += white;
    black_count += black;

    af::array color = image(offset.first, offset.second);
    white_average += color*af::tile(white, 1, 1, 3);
    black_average += color*af::tile(black, 1, 1, 3);
    gray_average += color;
  }


  af::array white = white_count && !black_count;
  af::array black = black_count && !white_count;
  af::array gray = !white && !black;

  segmentation_scaled = white*static_cast<uint8_t>(255) + gray*static_cast<uint8_t>(128);
  image_scaled = af::tile(white, 1, 1, 3)*white_average.as(u8) +
                 af::tile(black, 1, 1, 3)*black_average.as(u8) +
                 af::tile(gray, 1, 1, 3)*gray_average.as(u8);
  return;

}

af::array Segment(std::vector<std::vector<af::array>> &images, af::array image, af::array segmentation) {
  // Initialize images
  int w = 2;
  int h = 2;

  images.resize(3);

  images[0].clear();
  images[1].clear();

  while (true) {
    if (images[0].empty()) {
      images[0].push_back(image);
      images[1].push_back(segmentation);
      w = images[0].back().dims(1);
      h = images[0].back().dims(0);
    } else {
      af::array segmentation_scaled, image_scaled;
      Scale(images[0].back(), images[1].back(), image_scaled, segmentation_scaled);

      images[0].push_back(image_scaled);
      images[1].push_back(segmentation_scaled);
    }

    if (w == 1 || h == 1) {
      break;
    }

    w = (w+1)/2;
    h = (h+1)/2;
  }

  {
    int w = 100;
    int h = 100;
    int dim = 2; // Using dim=1 works fine!

    af::array diffs = af::constant(0, w, h, dim, s32);
    af::array vals = af::constant(128, w, h, dim, u8);
    af::array condition = vals==128;

    int version = 1;

    if (version == 1) // This makes it crash
      af::replace(diffs, condition, af::constant(0, w, h, dim, s32));

    if (version == 2) // This makes it crash
      diffs = af::select(condition, diffs, af::constant(0, w, h, dim, s32));

    if (version == 3) // This works fine!
      diffs = condition*diffs + (!condition)*af::constant(0, w, h, dim, s32);
  }

  return af::array();
}

int main(int argc, char **argv) {
  try {

    for (int i=0; i<100; i++) {
      af::array image = af::constant(0, 1280, 720, 3, u8);
      af::array segmentation = af::constant(0, 1280, 720, 1, u16);

      std::vector<std::vector<af::array>> images_;
      Segment(images_, image, segmentation);
      std::cout << i << std::endl;
    }
  } catch (af::exception &ex) {
    std::cout << ex.what() << std::endl;
    exit(1);
  }
}
```

**Comment by pavanky** [comment]
@rggjan Sorry about not following up on this issue earlier! I did not get a notification that you replied to the issue. We fixed a bug recently for in the devel branch that seems to have fixed the issue.

**Comment by rggjan** [comment]
Great, thanks for letting me know :)
