### ISSUE TITLE
Forge enums being used without WITH_GRPAHICS

### ISSUE THREAD

**Issue by shehzan10** [arrayfire/arrayfire#1128]
This causes ArrayFire builds without forge to fail.

See https://github.com/arrayfire/arrayfire/blob/devel/src/api/c/plot.cpp#L60

**Comment by pavanky** [comment]
We also can't have C++ API inside the C function..

**Comment by shehzan10** [comment]
It's not used in the API themselves. It's used inside the C-api and in a common wrapper function.
Additionally, it cannot be used here without the WITH_GRAPHICS definition https://github.com/arrayfire/arrayfire/blob/devel/src/api/c/plot.cpp#L116

**Comment by pavanky** [comment]
Alright :+1:
