### ISSUE TITLE
Question about copy on write behavior

### ISSUE THREAD

**Issue by unbornchikken** [arrayfire/arrayfire#1142]
Let's say, I have something like the following in my code (kinda pseudocode):

```C++
auto arr = array(10);
arr(col(0)) = 0;
arr(3) = 1;
arr(4) = 2;

auto sub = arr(3, 6);
auto sub2 = array(sub, dim4(2, 2));

auto buff = sub2.host<float>();

assert(buff[0] == 1);
assert(buff[1] == 2);

// Mutate the original:
arr(3) = 2;
arr(4) = 3;

// Read again the fragment:
buff = sub2.host<float>();

assert(buff[0] == 1);
assert(buff[1] == 2);
```

So, my assumption is that there is no copy happens till we reach the point of mutation, right? My question is which is the point where `sub2` copies its content from `sub`, and `sub` copies its content form `arr` exactly?

This is important to known to wrap things properly in garbage collected languages, because there can happen that GC doesn't reatin memory of sub and sub2 even they are out of scope, hence useless. But if I mutate their original, then ArrayFire does a bunch of copy opearation for derived regions even they are garbage at that point.

**Comment by pavanky** [comment]
@unbornchikken You are right. But even when the original goes out of scope, the code still works because the arrays are not pointing to original arrays but the shared data pointer held by the original. This means the data is not freed even if the original goes out of scope. It is only freed after all references are destructed.

**Comment by unbornchikken** [comment]
My question was about the situation, when the derived ones goes out of scope in a garbage collected environment. In this case, those are not destroyed yet, so the copy will happen when the original one mutated, beacuse there is no way for ArrayFire to know that the derived ones are garbage till they hasn't get collected.

That's why I'm on implementing an easy to use RAII pattern for ArrayFire.js. I've noticed in the profiler that there are many copy operations running despite my code doesn't hold any reference for their target at that point.

Thanks for the info.
