### ISSUE TITLE
Allow providing an output storage for operators on device.

### ISSUE THREAD

**Issue by Botev** [arrayfire/arrayfire#1150]
Sometimes it could be useful to pass a device pointer to an operator, which to point to an already allocated device memory, and to be used for the outer storage of the operator. 

The use case I have is something along the lines of 
```
array A = randu(1000, 1000);
// use A for some computations 
// from this line onward I know I'm never gona use A, but its not yet out of scope
// Let M be some other 100x1000 matrix and K be 1000x60
array B = dot(M,K);
```
The last line will lead to a new memory allocation. However, knowing the fact that A is no longer used it would be benefitial to be able to explicitly do something like this:
```
array B = dot(M,K, device pointer to A memory)
```
9pardy9 on gitter provided the following alternative for future release of the library:
```
float* ptr = A.device<float>();
array B(dim4(100, 60), stridesFrom(dim4(1000, 1000)), ptr, afDevice); // where second dim4 is the strides and third argument says the pointer is device pointer
```
so that the actual operation does not perform any new memory allocation. 

The actual use case is in Deep Learning, as in some of the large models we have the main bottle neck of the training is memory usage. However, during derivative computation and parameters updates at some points we know exactly which computations are no longer needed. As speed is of great importance, this will save memory  and/or avoid a new allocation.

**Comment by pavanky** [comment]
@Botev We can not do what you are asking for. It breaks API and creates more issues than it is worth. If you really want to do something like this, I suggest using the C API entirely where you have complete control of when an array gets freed.

If you prefer using C++, It is up to the user to do one of the following.

1) Use pointers to arrays and delete them when they are no longer needed.

2) Scope the variables in such a way that the original array gets deleted when it is no longer needed.

**Comment by 9prady9** [comment]
@Botev I wasn't suggesting passing device pointer to functions. Was only saying that you can create a new array from another array's device pointer the way i suggested if we have an additional constructor `array(dim4 dims, dim4 strides, T * ptr, af::source )`
