### ISSUE TITLE
test-select-cpu fails on Ubuntu 16.04 for i686

### ISSUE THREAD

**Issue by ghisvail** [arrayfire/arrayfire#1157]
This issue was reported to me by an Ubuntu contributor. Since Ubuntu 16.04 will become the next LTS, it might be worth also testing future releases of AF for it.

The current Debian package fails to build on Ubuntu 16.04 on their 32-bit architecture (i686). The other architectures build fine. Please find below the relevant section of the build log containing the offending test. Sounds like another tolerance related error.

```
36/89 Test #41: Test_select_cpu ..................***Failed    5.09 sec
Running main() from gtest_main.cc
[==========] Running 37 tests from 13 test cases.
[----------] Global test environment set-up.
[----------] 3 tests from Select/0, where TypeParam = float
[ RUN      ] Select/0.Simple
[       OK ] Select/0.Simple (85 ms)
[ RUN      ] Select/0.RightScalar
[       OK ] Select/0.RightScalar (67 ms)
[ RUN      ] Select/0.LeftScalar
[       OK ] Select/0.LeftScalar (65 ms)
[----------] 3 tests from Select/0 (217 ms total)

[----------] 3 tests from Select/1, where TypeParam = double
[ RUN      ] Select/1.Simple
[       OK ] Select/1.Simple (151 ms)
[ RUN      ] Select/1.RightScalar
[       OK ] Select/1.RightScalar (106 ms)
[ RUN      ] Select/1.LeftScalar
[       OK ] Select/1.LeftScalar (101 ms)
[----------] 3 tests from Select/1 (358 ms total)

[----------] 3 tests from Select/2, where TypeParam = af::af_cfloat
[ RUN      ] Select/2.Simple
[       OK ] Select/2.Simple (180 ms)
[ RUN      ] Select/2.RightScalar
[       OK ] Select/2.RightScalar (129 ms)
[ RUN      ] Select/2.LeftScalar
[       OK ] Select/2.LeftScalar (130 ms)
[----------] 3 tests from Select/2 (439 ms total)

[----------] 3 tests from Select/3, where TypeParam = af::af_cdouble
[ RUN      ] Select/3.Simple
[       OK ] Select/3.Simple (342 ms)
[ RUN      ] Select/3.RightScalar
[       OK ] Select/3.RightScalar (241 ms)
[ RUN      ] Select/3.LeftScalar
[       OK ] Select/3.LeftScalar (233 ms)
[----------] 3 tests from Select/3 (816 ms total)

[----------] 3 tests from Select/4, where TypeParam = unsigned int
[ RUN      ] Select/4.Simple
[       OK ] Select/4.Simple (155 ms)
[ RUN      ] Select/4.RightScalar
[       OK ] Select/4.RightScalar (116 ms)
[ RUN      ] Select/4.LeftScalar
[       OK ] Select/4.LeftScalar (116 ms)
[----------] 3 tests from Select/4 (387 ms total)

[----------] 3 tests from Select/5, where TypeParam = int
[ RUN      ] Select/5.Simple
[       OK ] Select/5.Simple (204 ms)
[ RUN      ] Select/5.RightScalar
[       OK ] Select/5.RightScalar (134 ms)
[ RUN      ] Select/5.LeftScalar
[       OK ] Select/5.LeftScalar (134 ms)
[----------] 3 tests from Select/5 (472 ms total)

[----------] 3 tests from Select/6, where TypeParam = long long
[ RUN      ] Select/6.Simple
[       OK ] Select/6.Simple (345 ms)
[ RUN      ] Select/6.RightScalar
/build/arrayfire-3.2.1+dfsg1/test/select.cpp:83: Failure
Value of: hcond[i] ? ha[i] : b
  Actual: 4.76578e+18
Expected: hc[i]
Which is: 4765783585667689730
[  FAILED  ] Select/6.RightScalar, where TypeParam = long long (218 ms)
[ RUN      ] Select/6.LeftScalar
/build/arrayfire-3.2.1+dfsg1/test/select.cpp:83: Failure
Value of: hcond[i] ? ha[i] : b
  Actual: 8.60665e+18
Expected: hc[i]
Which is: 8606648235303615511
[  FAILED  ] Select/6.LeftScalar, where TypeParam = long long (218 ms)
[----------] 3 tests from Select/6 (781 ms total)

[----------] 3 tests from Select/7, where TypeParam = unsigned long long
[ RUN      ] Select/7.Simple
[       OK ] Select/7.Simple (317 ms)
[ RUN      ] Select/7.RightScalar
[       OK ] Select/7.RightScalar (219 ms)
[ RUN      ] Select/7.LeftScalar
[       OK ] Select/7.LeftScalar (219 ms)
[----------] 3 tests from Select/7 (755 ms total)

[----------] 3 tests from Select/8, where TypeParam = unsigned char
[ RUN      ] Select/8.Simple
[       OK ] Select/8.Simple (71 ms)
[ RUN      ] Select/8.RightScalar
[       OK ] Select/8.RightScalar (51 ms)
[ RUN      ] Select/8.LeftScalar
[       OK ] Select/8.LeftScalar (50 ms)
[----------] 3 tests from Select/8 (172 ms total)

[----------] 3 tests from Select/9, where TypeParam = char
[ RUN      ] Select/9.Simple
[       OK ] Select/9.Simple (78 ms)
[ RUN      ] Select/9.RightScalar
[       OK ] Select/9.RightScalar (62 ms)
[ RUN      ] Select/9.LeftScalar
[       OK ] Select/9.LeftScalar (62 ms)
[----------] 3 tests from Select/9 (202 ms total)

[----------] 3 tests from Select/10, where TypeParam = short
[ RUN      ] Select/10.Simple
[       OK ] Select/10.Simple (73 ms)
[ RUN      ] Select/10.RightScalar
[       OK ] Select/10.RightScalar (51 ms)
[ RUN      ] Select/10.LeftScalar
[       OK ] Select/10.LeftScalar (49 ms)
[----------] 3 tests from Select/10 (173 ms total)

[----------] 3 tests from Select/11, where TypeParam = unsigned short
[ RUN      ] Select/11.Simple
[       OK ] Select/11.Simple (71 ms)
[ RUN      ] Select/11.RightScalar
[       OK ] Select/11.RightScalar (50 ms)
[ RUN      ] Select/11.LeftScalar
[       OK ] Select/11.LeftScalar (50 ms)
[----------] 3 tests from Select/11 (171 ms total)

[----------] 1 test from Select
[ RUN      ] Select.NaN
[       OK ] Select.NaN (131 ms)
[----------] 1 test from Select (131 ms total)

[----------] Global test environment tear-down
[==========] 37 tests from 13 test cases ran. (5076 ms total)
[  PASSED  ] 35 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] Select/6.RightScalar, where TypeParam = long long
[  FAILED  ] Select/6.LeftScalar, where TypeParam = long long

 2 FAILED TESTS
```

**Comment by ghisvail** [comment]
FYI, since `i686` is considered a major architecture in Ubuntu, this FTBFS prevents the migration of version `3.2.x` in the Ubuntu archive. This is why Ubuntu is still stuck at version `3.0.2`, which is the last version that built successfully built on all supported architectures.

**Comment by shehzan10** [comment]
As you know, we don't publish 32-bit support. But just to see if its an easy fix, can you give a link to the build failures?

**Comment by LocutusOfBorg** [comment]
https://launchpad.net/ubuntu/+source/arrayfire/3.2.1+dfsg1-1
here we are!
(sorry for stepping in, I'm the original contributor, and Debian sponsor of the package)

**Comment by pavanky** [comment]
@LocutusOfBorg @ghisvail  Thanks. I think we've found the issue. This should be fixed by 3.2.2. 

So is the plan to include arrayfire in the Ubuntu 16.04 repos ? If so what is the latest you can update the packages ? I am asking because we might have the next major release (3.3) before that point.

**Comment by LocutusOfBorg** [comment]
https://wiki.ubuntu.com/XenialXerus/ReleaseSchedule 18 feb 2016 I think

**Comment by pavanky** [comment]
@LocutusOfBorg excellent. Right now 3.3 is scheduled for February 11. But we can move it forward or test the beta versions to try and get 3.3 into Ubuntu :)

**Comment by ghisvail** [comment]
Thanks Gianfranco for stepping in. The latest update to the packaging, which brings the missing OpenCL and unified backends, is currently waiting in the new queue for approval. Depending on how fast the process is going, I may cherry-pick the fix to this issue to `3.2.1`. Otherwise, it will come with the update to `3.2.2`.

I am happy to coordinate with @pavanky to get `3.3` packaged on time for the freeze of Xenial, but it would be worth allowing ourselves a reasonable margin to make sure the packaging passes the Debian and Ubuntu builders.

How does that sound ?

**Comment by pavanky** [comment]
@ghisvail The last week or so will most likely will be in feature freeze. We can begin testing on the feature branch from the last week of January to ensure it builds and works fine on debian and ubuntu systems.

BTW, would it be possible for ubuntu to have the CUDA library as well ?

**Comment by ghisvail** [comment]
The package has been accepted quicker than I thought so I can submit an update with the cherry-picked fix. Could you guys point me to the exact commit-id of the fix? Cheers.

**Comment by shehzan10** [comment]
This fixes the select tests https://github.com/arrayfire/arrayfire/commit/52a8409cb510083e242cf5280bdc63a173ff7902

**Comment by LocutusOfBorg** [comment]
cherry-picked and build started here
https://launchpad.net/~costamagnagianfranco/+archive/ubuntu/locutusofborg-ppa/+packages

**Comment by ghisvail** [comment]
@LocutusOfBorg do you want to keep the fix downstream in Ubuntu instead? I am fine either or.

**Comment by LocutusOfBorg** [comment]
I can't upload on ubuntu yet, so maybe debian is better :)
just ping me with a dsc ;)

**Comment by ghisvail** [comment]
Good, you'll have something ready later today.

**Comment by LocutusOfBorg** [comment]
wonderful! the package has been successfully built on my ppa, so I can upload as soon as you have a dsc.

**Comment by pavanky** [comment]
Alright, I am closing the issue since it looks like it's resolved. Let me know if we need to reopen this again.
