### ISSUE TITLE
Need help: cannot figure out how indexing works

### ISSUE THREAD

**Issue by unbornchikken** [arrayfire/arrayfire#1160]
Hi,

I have two arrays:

1:
```
[4 1 1 1]
         0 
         1 
         1 
         0 
```
2:
```
[4 2 1 1]
    0.2960     0.6201 
    0.1967     0.4594 
    0.6445     0.8603 
    0.6121     0.5667
```
What I wanna do is select values from array 2 along the first dimension by index of corresponding values from array 1, so:

```
    0.2960     0.6201 : by index 0 = 0.2960
    0.1967     0.4594 : by index 1 = 0.4594
    0.6445     0.8603 : by index 1 = 0.8603
    0.6121     0.5667 : by index 0 = 0.6121
```

So I wanna end up with an array of:
```
[4 1 1 1]
    0.2960
    0.4594
    0.8603
    0.6121
```

Tried `lookup` but that seems does entirely different thing that I want. I can see that there is `af_index` in the C interface, but the documentation doesn't mention any C++ counterpart.

So my question is how I can do the above index based transformation?

**Comment by pavanky** [comment]
There is no function to do this. You can do what you want by doing something like this. Assume array 1 is idx, array 2 is A.

```
array S = range(A.dims(0));
array idx2 = idx * A.dims(0) + S;
array B = A(idx2);
```

**Comment by unbornchikken** [comment]
That will do, thanks.
