### ISSUE TITLE
Do not error out when printing empty arrays.

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#1164]
Just print `<empty>`

**Comment by shehzan10** [comment]
This issue is technically a subset of https://github.com/arrayfire/arrayfire/issues/799

**Comment by pavanky** [comment]
@shehzan10 

Let us deal with trivial ones first. This function does not change the behavior much, so I think it can be done in a bugfix release.

**Comment by shehzan10** [comment]
Merged into hotfixes-3.2.2
