### ISSUE TITLE
Allow specifying the stride when creating arrays from device memory

### ISSUE THREAD

**Issue by FilipeMaia** [arrayfire/arrayfire#1177]
It would be useful if one could pass stride argument to `af_device_array()`.

**Comment by pavanky** [comment]
This will be a bit hard because ArrayFire currently does not support negative strides or strides along the leading dimension. We'll need to add that support internally before we do this.

**Comment by FilipeMaia** [comment]
Sure, you don't have to support all possible strides. I was only thinking of allowing those strides that Arrayfire already does internally. You could document the supported strides and return error for the others.
If more strides became possible in the future it would be easy to adjust things.

**Comment by pavanky** [comment]
Alright, we'll do this alongside this issue: https://github.com/arrayfire/arrayfire/issues/1131
