### ISSUE TITLE
Using arrayfire with cython

### ISSUE THREAD

**Issue by mchandra** [arrayfire/arrayfire#1179]
I have a function in C++

```
void func(array a, array b, array c)
```

which I want to call in python. So I tried wrapping it using Cython, however the `array` object is not a native Cython type and so one needs to declare the type in a .pxd file which is very tedious. Is there an easy way to do this using the existing arrayfire-python bindings?

**Comment by pavanky** [comment]
I am not sure this is the right place for you to ask this question. Our C++ wrapper does not do anything special. You will need to look at cython examples of how to integrate with C++ code.
