### ISSUE TITLE
Look at additional default paths for unified backend

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#1184]
Linux always installs to `/opt/arrayfire-3` and OSX always installs to `/usr/local`

We should perhaps look at these two locations as well when loading `libafcuda`, `libafcpu` and `libafopencl`.

**Comment by pavanky** [comment]
Additionally, it should also set the error string asking the user to set "AF_PATH" when returning the `501` error.

**Comment by shehzan10** [comment]
Adding via #1185 
```
/opt/arrayfire-3/lib
/opt/arrayfire/lib
/usr/local/lib
/usr/local/arrayfire-3/lib
/usr/local/arrayfire/lib
```

Note: This will only lead to finding libaf*. Dependencies such as NVVM etc will have to be added to LD_LIBRARY_PATH as shown in [Unified Backend](http://www.arrayfire.com/docs/unifiedbackend.htm) doc.
