### ISSUE TITLE
Use CPU libraries when possible for CPU OpenCL devices

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#1196]
For example it might be faster to use MKL / OpenBLAS when performing linear algebra functions or FFT operations for CPU devices.

There are two ways it can be achieved.

1) Copy data to "host" memory, do the operation, copy back. This might be useful only after a particular size.

2) Consider using clEnqueueMapBuffer. Check if the performance of this function is faster than dual copies mentioned in (1).

**Comment by pavanky** [comment]
@arrayfire/core-devel Do you guys think we should try to squeeze this in for 3.2.2 ?

**Comment by 9prady9** [comment]
I think option (2) does a hidden copy back to device memory when we un-map the cl_mem object. So, we would still be having two copies.

**Comment by shehzan10** [comment]
I think it should go into 3.3. There is no need to rush it.
