### ISSUE TITLE
Automated way to count flops

### ISSUE THREAD

**Issue by mchandra** [arrayfire/arrayfire#1203]
Is there a function in arrayfire that can be called that can count the flops between a segment of code. Something like:

```
af::start_flops_count();

/* Code here */

totalFlops = af::end_flops_count();

cout << "Flops in code segment = " << totalFlops;

```

**Comment by pavanky** [comment]
@mchandra This is very impractical and provides fairly bad info if we did implement it. Very few algorithms are compute bound so their flop count will be very low.

There are also several algorithms that have different flop counts based on who you ask. I think the best solution would be to provide the raw times and just let the users figure out the flops of the algorithms.

**Comment by mchandra** [comment]
Well, it would also be good to provide the number of memory accesses etc. But I understand what you mean.

**Comment by pavanky** [comment]
@mchandra Alright, I created an issue to deal with the broader profiling issue over here: https://github.com/arrayfire/arrayfire/issues/1204

**Comment by mchandra** [comment]
Thanks!
