### ISSUE TITLE
Build error on OSX

### ISSUE THREAD

**Issue by dpo** [arrayfire/arrayfire#1212]
I'm trying to update the Homebrew formula for `arrayfire` to version 3.2.2 but I'm running into this:
```
In file included from /tmp/arrayfire20160103-56300-15xv3cn/arrayfire-3.2.2/src/backend/cpu/hist_graphics.cpp:12:
In file included from /tmp/arrayfire20160103-56300-15xv3cn/arrayfire-3.2.2/src/backend/cpu/hist_graphics.hpp:14:
/tmp/arrayfire20160103-56300-15xv3cn/arrayfire-3.2.2/src/api/c/graphics_common.hpp:21:1: error: no type named 'dtype' in namespace 'fg'; did you mean 'af::dtype'?
fg::dtype getGLType();
^~~~~~~~~
af::dtype
/tmp/arrayfire20160103-56300-15xv3cn/arrayfire-3.2.2/include/af/defines.h:384:22: note: 'af::dtype' declared here
    typedef af_dtype dtype;
                     ^
```
There are other errors. Here is the [full log](https://gist.github.com/anonymous/a5fed14e8ae209148d3e). I'm on OSX 10.9. I get the same errors with clang and gcc5.

**Comment by shehzan10** [comment]
From your [logs](https://gist.github.com/anonymous/a5fed14e8ae209148d3e#file-01-cmake-L55), I see that you are using the [af3.0.1](https://github.com/arrayfire/forge/tree/af3.0.1) tag of forge.

With each ArrayFire release we create a Forge tag as well. So you should be using Forge tag [af3.2.2](https://github.com/arrayfire/forge/tree/af3.2.2) .

That should fix the issue you are having. You can close this issue once you build successfully.

**Comment by dpo** [comment]
Thanks! It seems to build now, but I'm getting an error during install:
```
CMake Error at cmake_install.cmake:50 (file):
  file INSTALL cannot find
  "/tmp/arrayfire20160103-72539-9t8wpb/arrayfire-3.2.2/assets/examples".
```
I tried configuring CMake with `-DBUILD_EXAMPLES:BOOL=OFF` but that leads to the same error. Any ideas? Here are [update logs](https://gist.github.com/e4c0f6b1f3b95835c362
) (scroll to the bottom of [this log](https://gist.githubusercontent.com/anonymous/e4c0f6b1f3b95835c362/raw/3e2ca231de06466b860cbbaeb218894d78ba5b3e/04.make)).

**Comment by dpo** [comment]
Here's a bit more info:
```
bash-3.2$ pwd
/private/tmp/arrayfire20160103-72539-9t8wpb/arrayfire-3.2.2/build
bash-3.2$ ls
ArrayFireConfig.cmake        CPackConfig.cmake            arch.c                       examples
ArrayFireConfigVersion.cmake CPackSourceConfig.cmake      bin2cpp                      readme.html.out
CMakeCache.txt               Install                      cmake_install.cmake          src
CMakeFiles                   Makefile                     distribution.dist.out        welcome.html.out
bash-3.2$ ls /tmp/arrayfire20160103-72539-9t8wpb/arrayfire-3.2.2/assets/
bash-3.2$ ls examples/
CMakeFiles          cmake_install.cmake getting_started     image_processing    pde
Makefile            computer_vision     graphics            lin_algebra         unified
benchmarks          financial           helloworld          machine_learning
```
(note: `/tmp` and `/private/tmp` are the same location). So `arrayfire-3.2.2/assets` is empty, but there is `arrayfire-3.2.2/build/examples`.

**Comment by shehzan10** [comment]
Did you clone submodules?
You can either do `git clone --recurive` (when cloning) or `git submodule update --init --recursive` after cloning.

**Comment by dpo** [comment]
I downloaded the latest release. I didn't clone the git repository. Homebrew formulas should download a stable release and not rely on a moving target. How are users supposed to get submodules then?

**Comment by dpo** [comment]
Works now. Many thanks!

**Comment by shehzan10** [comment]
Right, we are aware of that and that's why we host our own sources which include the submodules. These are linked under "Release Notes" in each release and will be pointed to by an arrayfire.com/arrayfire_source link. You will be able to find them here http://arrayfire.com/arrayfire_source/

Note: As of posting this message, we are experiencing technical issues with arrayfire.com. You can download these from our CI at http://ci.arrayfire.org/userContent/arrayfire_source/. Will remove this note when arrayfire.com is back up.
