### ISSUE TITLE
Installers linked with CUDA 7.0

### ISSUE THREAD

**Issue by mchandra** [arrayfire/arrayfire#1217]
Hi, are there installers built without graphics linked with CUDA 7.0? Unfortunately, all the clusters I have access to have only CUDA 7.0 and lower (stampede at TACC and UIUC's campus cluster). Thanks!

**Comment by pavanky** [comment]
@mchandra It is fairly easy to build arrayfire. It would strain CI frame work a bit to build / test with older versions of CUDA.

Is there any reason you do not want to build arrayfire from source ? It is fairly easy to build on Linux where all the necessary dependencies exist.

**Comment by mchandra** [comment]
The compilers available on those machines don't support C++11, and I remember trying to compile arrayfire on them and it did not work. Is there a way I can compile on a machine with all the dependencies, package arrayfire as the bash script and then install it on the target machine? Thanks!

**Comment by pavanky** [comment]
If you just want to build the CUDA backend, you don't need C++11. You can disable the remaining backends (and use the libraries from the installers for those backends if needed).

Does the cluster have boost available ?

**Comment by mchandra** [comment]
Yes, boost is available on all the clusters I am using.

**Comment by pavanky** [comment]
@mchandra you should be able to build the CUDA backend just fine without using C++11. You can run the following commands:

```
cd arrayfire
mkdir build
cd build
cmake .. -DBUILD_GRAPHICS=OFF -DBUILD_CPU=OFF -DBUILD_OPENCL=OFF -DBUILD_UNIFIED=OFF -DCMAKE_INSTALL_PREFIX=package
make -j4 install # increase this number if you have more cores available
```
This should create `libafcuda.so` in `arrayfire/build/package/lib`

**Comment by pavanky** [comment]
BTW what is the compiler version available on the cluster ?

**Comment by mchandra** [comment]
Thanks for the instructions! I'll try them out now.

Here's what is available:
```
[manic@golubh3 ~]$ icc -v
icc version 15.0.0 (gcc version 4.4.7 compatibility)

```

**Comment by pavanky** [comment]
Is there no other compiler available on the machine ? What does ``which gcc` -- version`  return

**Comment by mchandra** [comment]
Yes, gcc is available too:

```
[manic@golubh3 build]$ gcc -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) 
```

Btw, I get the following errors during configure:

```
-- The C compiler identification is Intel
-- The CXX compiler identification is Intel
-- Check for working C compiler: /usr/local/intel/intel-15.0/bin/icc
-- Check for working C compiler: /usr/local/intel/intel-15.0/bin/icc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/local/intel/intel-15.0/bin/icpc
-- Check for working CXX compiler: /usr/local/intel/intel-15.0/bin/icpc -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at CMakeModules/FindOpenCL.cmake:69 (include):
  include could not find load file:

    CMakePushCheckState
Call Stack (most recent call first):
  CMakeModules/FindOpenCL.cmake:116 (_FIND_OPENCL_VERSION)
  CMakeLists.txt:22 (FIND_PACKAGE)


-- MIN_BUILD_TIME IS OFF
-- Using Dynamic FreeImage Lib
-- Could NOT find FREEIMAGE (missing:  FREEIMAGE_INCLUDE_PATH FREEIMAGE_LIBRARY) 
WARNING,FreeImage not found!
-- Found CUDA: /usr/local/cuda/7.0 (found version "7.0")
-- Boost version: 1.41.0
-- Using LIBNVVM_HOME: /usr/local/cuda/7.0/nvvm
-- /home/manic/scratch/arrayfire/CMakeModules/cuda_compute_capability.cpp
-- CUDA Compute Detection Output: Couldn't get device count: CUDA driver version is insufficient for CUDA runtime version

-- CUDA Compute Detection Return: 1
-- CUDA Compute Detection Failed
-- No computes detected. Fall back to 20, 30, 50
-- Number of Computes Detected = 3
-- Setting Compute 20 to ON
-- Setting Compute 30 to ON
-- Setting Compute 50 to ON
-- CUDA cusolver library available in CUDA Version 7.0
CMake Error at src/backend/cuda/CMakeLists.txt:268 (CUDA_COMPUTE_SEPARABLE_COMPILATION_OBJECT_FILE_NAME):
  Unknown CMake command
  "CUDA_COMPUTE_SEPARABLE_COMPILATION_OBJECT_FILE_NAME".
Call Stack (most recent call first):
  src/backend/cuda/CMakeLists.txt:295 (MY_CUDA_ADD_LIBRARY)


-- Configuring incomplete, errors occurred!
```

**Comment by pavanky** [comment]
@mchandra looks like it is going to be a bigger hassle to resolve this than create room for one build in our CI.

Can you email technical@arrayfire.com so we can send you the link to an installer with 7.0 sometime later this week ?

**Comment by mchandra** [comment]
Thanks a lot @pavanky 

Is there some bug in the build system that doesn't allow the use of CUDA 7.0? I can open a new issue for that.

**Comment by FilipeMaia** [comment]
```
-- CUDA Compute Detection Output: Couldn't get device count: CUDA driver version is insufficient for CUDA runtime version
```
suggests that even with the right binaries you will need to ask the administrator to upgrade the CUDA driver.

**Comment by pavanky** [comment]
@mchandra can you check what is the driver version you have on the machine ?

`cat /proc/driver/nvidia/version`

**Comment by mchandra** [comment]
```
[manic@golubh4 build]$ cat /proc/driver/nvidia/version
NVRM version: NVIDIA UNIX x86_64 Kernel Module  340.65  Tue Dec  2 09:50:34 PST 2014
GCC version:  gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) 

```

**Comment by pavanky** [comment]
@mchandra This is too old for CUDA 7.0 like @FilipeMaia mentioned. We are not entirely sure which version of CUDA is supported with that driver. perhaps 6.5 ? Any chance you can talk to the admins into upgrading the driver ?

**Comment by mchandra** [comment]
I could, and I know from past experience any package upgrade requests are completely useless. I'm now trying on another machine (TACC Stampede). Will let you know if it works.
