### ISSUE TITLE
expose getActiveBackend()

### ISSUE THREAD

**Issue by Markus-Goetz** [arrayfire/arrayfire#1219]
It would be useful to be able to query which actual backend is currently being used when arrayfire is in the unified backend mode. As far as I can see this information is available internally via the AFSymbolManager class and its getActiveBackend() method, but is not exposed as an API call. Does anything speak against making this call available in the next release?

**Comment by pavanky** [comment]
@Markus-Goetz This can be added easily. It was an oversight we missed it in the last release.

As a hack you can do `getBackendId(constant(0, 1))`; This does not create any device memory so the overhead is fairly low.

**Comment by Markus-Goetz** [comment]
Hi pavanky, thank you, much appreciated!
