### ISSUE TITLE
Difference of Gaussians DoG sigma: change type int/float?

### ISSUE THREAD

**Issue by blazzter** [arrayfire/arrayfire#1233]
Hi, is there a reason why DoG filter takes integers for Gaussian radius/sigma? Such filter is defined generarly with real numbers and even some specific values - e.g. for Laplacian approximation are decimal combinations. This restrict spatial resolition of the filter.

**Comment by pavanky** [comment]
@blazzter A gaussian kernel technically has infinite dimensions with the values becoming smaller as the move out from the center. We need to cut it off at some point to get a discrete kernel that can be used for image processing. The row and column values provide the limits we are considering.

That said, the sigma values are still use double precision. You can choose to create gaussian kernel of your choosing by doing something like this:

gaussianKernel(21, 21, 5.5, 5.5);

**Comment by blazzter** [comment]
Just to confirm, difference of gaussians is based on different sigma values of gaussian smoothing for the same image. 

DoG is defined - you choose 2 radius sizes, gaussian kernel code then assigns sigma according to these - this seems little odd here. Then it does 2 convolutions and difference and gives output

I would suggest to use something like Dog(input, sigma1, sigma2, radius/size)
inside of the DoG function should be 
array gaussDiff = gauss(sigma2) - gauss(sigma2)
output = convolve2D(input,gaussDiff)

In such way you use only 1 convolution operation, sigmas and radius of operation can be all defined.

http://fourier.eng.hmc.edu/e161/lectures/gradient/node9.html
https://en.wikipedia.org/wiki/Difference_of_Gaussians

**Comment by pavanky** [comment]
@blazzter Sorry about that. I did not realize you were talking about dog, I somehow read that as af::gaussianKernel.

We wanted af::dog() to support the basic functionality. But if you wanted more fine grain control, you cal just do the following:

```
auto gaussDiff = af::gaussianKernel(rows, cols, sigma1, sigma1) - af::gaussianKernel(rows, cols, sigma2, sigma2);
output =  convolve2(inpuit, gaussDiff);
```

**Comment by blazzter** [comment]
ok thanks, it was more of a question towards documentation, I do not think it is clear in af::dog case

**Comment by pavanky** [comment]
@blazzter Thanks we will clear up the documentation. The radius is automatically translated into a particular sigma value. We'll just note down the formula we use up front in the documentation.
