### ISSUE TITLE
Optimal cache use using blocking

### ISSUE THREAD

**Issue by mchandra** [arrayfire/arrayfire#1234]
Hi,

Suppose I have a bunch of operations to be performed on the same data, like
```
array data1, data2, data3, data4;
array out1, out2, out3, out4, out5, out6, out7, out8, out9, out10;

out1 = func1(data1, data2, data3, data4);
out2 = func2(data1, data2, data3, data4);
out3 = func3(data1, data2, data3, data4);
out4 = func4(data1, data2, data3, data4);
out5 = func5(data1, data2, data3, data4);
out6 = func6(data1, data2, data3, data4);
out7 = func7(data1, data2, data3, data4);
out8 = func8(data1, data2, data3, data4);
out9 = func9(data1, data2, data3, data4);
out10 = func10(data1, data2, data3, data4);
```

How do I ensure optimal use of the cache? That is, I want to load chunks of `data1, data2, data3, data4` and then use them throughout `func1` to `func10` before moving onto the next chunk. Should I be using `gfor` in some way? I think this has to do with "In-Loop Reuse" in http://www.arrayfire.com/docs/page_gfor.htm , except I'm not sure how to choose the chunk size etc..

Also see  https://github.com/viennacl/viennacl-dev/issues/140

Thanks,
Mani

**Comment by mchandra** [comment]
Would `dist_tile1` in http://arrayfire.com/how-to-write-vectorized-code/ be the solution to this?

**Comment by pavanky** [comment]
@mchandra I don't understand what you are trying to ask. If all of the data is already on the GPU, the only thing that you can do to improve performance is to ensure that the data is continuous. In arrayfire's case the arrays should be continuous along the first dimension.

**Comment by mchandra** [comment]
@pavanky Suppose `data1, data2, data3, data4` are large arrays whose sizes exceed the capacity of the cache of the GPU/CPU. When `func1` is called, there are 5 round trips to the global memory: 4 loads of `data1, data2, data3, data4` and 1 store of `out1`. Now when `func2` is called, again there are 5 round trips to the global memory. So, everytime one of `func` is called, there are global memory accesses that I wish to avoid.

So the question is, can I load chunks (perhaps to `local` memory in `OpenCL`, or `shared` memory in `CUDA`) of `data1, data2, data3, data4` before `func1` is called, call all of `func1, func2...func10` on these chunks, store the result in global memory before moving onto the next set of chunks of  `data1, data2, data3, data4`. The goal here is to try converting a memory bandwidth limited problem to a compute limited one by reusing data already present in the cache.

Something like,

```
/* tileSizeX, tileSizeY, tileSizeZ are small enough such that data1Tile, data2Tile, data3Tile will fit in the cache */
array data1Tile = constant(0, tileSizeX, tileSizeY, tileSizeZ);
array data2Tile = constant(0, tileSizeX, tileSizeY, tileSizeZ);
array data3Tile = constant(0, tileSizeX, tileSizeY, tileSizeZ);
array data4Tile = constant(0, tileSizeX, tileSizeY, tileSizeZ);

/* data1, data2, data3, data4 all have the same sizes */
for (int kTile=0; kTile < data1.dims(2)/tileSizeZ; kTile++)
{
  for (int jTile=0; jTile < data1.dims(1)/tileSizeY; jTile++)
  {
    for (int iTile=0; iTile < data1.dims(0)/tileSizeX; iTile++)
    {
       /* Load the tiles */
       seq tileDomainX(iTile*tileSizeX, (iTile+1)*tileSizeX);
       seq tileDomainY(iTile*tileSizeY, (iTile+1)*tileSizeY);
       seq tileDomainZ(iTile*tileSizeZ, (iTile+1)*tileSizeZ);

       data1Tile(span, span, span) = data1(tileDomainX, tileDomainY, tileDomainZ);
       data2Tile(span, span, span) = data2(tileDomainX, tileDomainY, tileDomainZ);
       data3Tile(span, span, span) = data3(tileDomainX, tileDomainY, tileDomainZ);
       data4Tile(span, span, span) = data4(tileDomainX, tileDomainY, tileDomainZ);
    
      /* Perform computation on the tiles */
      array out1Tile = func1(data1Tile, data2Tile, data3Tile, data4Tile);
      array out2Tile = func2(data1Tile, data2Tile, data3Tile, data4Tile);
      array out3Tile = func3(data1Tile, data2Tile, data3Tile, data4Tile);
      array out4Tile = func4(data1Tile, data2Tile, data3Tile, data4Tile);
      array out5Tile = func5(data1Tile, data2Tile, data3Tile, data4Tile);
      array out6Tile = func6(data1Tile, data2Tile, data3Tile, data4Tile);
      array out7Tile = func7(data1Tile, data2Tile, data3Tile, data4Tile);
      array out8Tile = func8(data1Tile, data2Tile, data3Tile, data4Tile);
      array out9Tile = func8(data1Tile, data2Tile, data3Tile, data4Tile);
      array out10Tile = func8(data1Tile, data2Tile, data3Tile, data4Tile);

     /* Store result in global memory */
     out1(tileDomainX, tileDomanY, tileDomainZ) = out1Tile;
     out2(tileDomainX, tileDomanY, tileDomainZ) = out2Tile;
     out3(tileDomainX, tileDomanY, tileDomainZ) = out3Tile;
     out4(tileDomainX, tileDomanY, tileDomainZ) = out4Tile;
     out5(tileDomainX, tileDomanY, tileDomainZ) = out5Tile;
     out6(tileDomainX, tileDomanY, tileDomainZ) = out6Tile;
     out7(tileDomainX, tileDomanY, tileDomainZ) = out7Tile;
     out8(tileDomainX, tileDomanY, tileDomainZ) = out8Tile;
     out9(tileDomainX, tileDomanY, tileDomainZ) = out9Tile;
     out10(tileDomainX, tileDomanY, tileDomainZ) = out10Tile;
    }
  }
}
```

What do you think?

**Comment by pavanky** [comment]
@mchandra This is going to be much much more slower than not using the for loops at all. Especially because each of the indexing operation is doing twice the amount of reads and writes as opposed to doing a simple operation. You can't control the caching mechanism of the GPU from userland. We assume our algorithms and the GPU are clever enough to handle them properly.
