### ISSUE TITLE
Improve heuristics for Memory Management

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#1239]
Right now the heuristics are fairly simplistic. 

Possible improvements:

- Check for maximum available memory
- Check for alternatives to `std::map` to improve garbage collection performance
- Increase the size of max_buffers
- Allow users to tweak the max_buffers, threshold of max memory

**Comment by mchandra** [comment]
I tried out this merge on an Intel CPU and a NVIDIA GPU. On both platforms, `memsize` returns 0 and so the GC starts after 1 GB. Our application uses much more memory than that. I tweaked the threshold to 4 GB and got much better performance. Would be good if there's an option to set the `max_bytes` limit by hand.
