### ISSUE TITLE
Give users the ability to compile custom JIT kernels.

### ISSUE THREAD

**Issue by mchandra** [arrayfire/arrayfire#1247]
Consider the following code:

```
result1 = a1*x1 + a2*x2 + a3*x3 + a4*x4;
result2 = a1*y1 + a2*y2 + a3*y3 + a4*y4;
result3 = a1*z1 + a2*z2 + a3*z3 + a4*z4;

result1.eval();
result2.eval();
result3.eval();
```

The above code results in the firing of 3 separate kernels and hence 3 round trips to the global memory to fetch `a1, a2, a3, a4`. Instead, if there were a command like `eval(result1, result2, result3)` which fires a single kernel to compute `result1, result2, result3`, the memory would be reused inside the kernel and thus save on global reads.

**Comment by pavanky** [comment]
@mchandra This feature can not be implemented without easily in the way it is written. However we can implement something like this:

```
void my_func(std::vector<af::array> &outputs, const std::vector<af::array> inputs)
{
    outputs[0] = inputs[0] + inputs[1];
    outputs[1] = inputs[0] - inputs[1];
}

int main()
{
 // Generate inputs
auto func = af::compile(my_func);
func(outputs, inputs);
}
```

This may not look as clean as the version you'd like, but it gives more control over our JIT engine to the user.

**Comment by pavanky** [comment]
It could be implemented cleaner if we used more C++11ish stuff as well. I will need to look into it.

**Comment by mchandra** [comment]
Thanks! Our code using arrayfire has a ~ 5x penalty compared to how fast it could be, because of repeated round trips to global memory. This will help a lot. Do you think it will work on all backends?

**Comment by pavanky** [comment]
@mchandra We don't like not having feature parity. If we do it for one backend, we'll do it for everything :)

**Comment by pavanky** [comment]
It may take some time to do this though, we'll need to clean up our JIT code a tiny bit.

**Comment by mchandra** [comment]
No problem. 

Also, right now the arguments of a kernel that JIT produces look like

```
__global double *in0, KParam iInfo0, 
__global double *in1, KParam iInfo1, 
__global double *in3, KParam iInfo3, 
__global double *in4, KParam iInfo4, 
__global double *in7, KParam iInfo7, 
__global double *in8, KParam iInfo8, 
__global double *out, KParam oInfo,
```

It would be a good idea to add the `restrict` keyword to the kernels that the JIT produces, like `_global const double* restrict in0`. I think it explicitly states that the pointers are not aliased, which is indeed the case I think: `in0` and `in1` point to separate memory locations. Stating this allows for more compiler optimizations than otherwise possible.

**Comment by pavanky** [comment]
@mchandra We can't be sure that `in0` and `in1` will not have overlapping memory locations. For example a user could do something like this:

```
array b = a(seq(10)) - a(1 + seq(10));
```

This would involve overlapping memory. We could look for special cases when memories don't overlap, but that will blow up the number of kernels being generated and could potentially increase the runtime because similar code may need to be recompiled again because some of the buffers are overlapping.

Also for simplistic kernels like element wise operations, restrict really does not add much value.

**Comment by mchandra** [comment]
Yeah I agree, too complicated with perhaps not very much gain in performance.

**Comment by mchandra** [comment]
Thank you for addressing this issue. It has improved the performance of our code significantly. The parts of our code which had the above bottlenecks are now getting a good fraction of peak machine bandwidth, and are giving the same speed expected from hand tuned kernels.
