### ISSUE TITLE
How to package correctly?

### ISSUE THREAD

**Issue by mchandra** [arrayfire/arrayfire#1253]
One of the clusters we want to run our application built on arrayfire does not have gcc and arrayfire refuses to compile with icc. So I decided to compile on my own ubuntu machine, package it and then install the package on the cluster. However, I get the following errors:

```
ld: warning: liblapacke.so.3, needed by /global/scratch/manic/arrayfire-no-gl-3.3.0/lib/libafopencl.so.3.3.0, not found (try using -rpath or -rpath-link)
ld: warning: libcblas.so.3, needed by /global/scratch/manic/arrayfire-no-gl-3.3.0/lib/libafopencl.so.3.3.0, not found (try using -rpath or -rpath-link)
```

I don't get the errors when I use the package from here http://ci.arrayfire.org/userContent/Linux/ArrayFire-no-gl-v3.2.2_Linux_x86_64.sh

I followed the build and package instructions on the wiki. Any idea what I'm doing differently than the packages produced on the above website? (I absolutely need a custom build and cannot use the standard arrayfire packages since our application does not like the defaults set in arrayfire)

**Comment by pavanky** [comment]
@mchandra Our installers (including the one linked here) are compiled with MKL. So you should either compile with MKL or install cblas and lapacke on the cluster.

**Comment by mchandra** [comment]
Can you paste the command you guys use for the builds here? Thanks

**Comment by pavanky** [comment]
If you are using devel branch you can simply do the following:

```
cd build
rm -rf *
export INTEL_MKL_ROOT=/path/to/mkl
cmake ..
make -j8
```

**Comment by mchandra** [comment]
Thanks, that worked. Now I get this:

```
/global/scratch/manic/arrayfire-no-gl-3.3.0/lib/libafopencl.so.3.3.0: undefined reference to `memcpy@GLIBC_2.14'
```

Any clue? I built the package on Ubuntu 14.04 LTS with gcc 4.8.4

**Comment by pavanky** [comment]
It looks like the server you are send the library to has an older libstdc++.so

**Comment by mchandra** [comment]
What is the configuration of the machine you do your builds on? I can try to match that since your builds seem to work on the cluster.

**Comment by pavanky** [comment]
We build on centos 6.x so it is forward compatible with all newer distros. If your desktop has a newer libstdc++ than your server you try to package the newer libstdc++ to your home directory and add it to `LD_LIBRARY_PATH`
