### ISSUE TITLE
Empty array exception

### ISSUE THREAD

**Issue by yshady** [arrayfire/arrayfire#1258]
Declaring an empty array throws an exception.
Running this code:
```
int main(int argc, char *argv[])
{
	af::array test;
	return 0;
}
```
outputs the following on the CUDA and OpenCL backends, but passes with no error on the CPU.
```
terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Internal error:998):
In function af_create_handle
In file src/api/c/data.cpp:203



In function void af::initEmptyArray(void**, af::dtype, dim_t, dim_t, dim_t, dim_t)
In file src/api/cpp/array.cpp:129
Aborted (core dumped)
```

Is this something recreatable? Or is it just my build?

**Comment by pavanky** [comment]
Can you print `af::info()` and show us what the output is ?

**Comment by yshady** [comment]
Looks like an error because of updating the nVidia drivers this morning. Sorry for the post.
af::info()
```
terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Internal error:998):
In function DeviceManager
In file src/backend/opencl/platform.cpp:329
OpenCL Error (-1001): Unknown OpenCL Error (-1001) when calling clGetPlatformIDs

In function void af::info()
In file src/api/cpp/device.cpp:54
Aborted (core dumped)
```

**Comment by pavanky** [comment]
Yeah you'll need to restart after installing the driver.

**Comment by yshady** [comment]
Yup. All works now. Thanks for the select/replace bug fix btw :+1:

**Comment by ArchakGoel** [comment]
I am running into exact same issue. What worked for you @ynashed ? Did you have to install a specific driver?
