### ISSUE TITLE
user configurable options

### ISSUE THREAD

**Issue by mchandra** [arrayfire/arrayfire#1261]
Would be good if the user has the option of setting the following variables:

1. `MAX_JIT_LEN` in `src/backend/opencl/Array.cpp`
2. `local_0` in `evalNodes()` in `src/backend/opencl/jit.cpp`

I see ~ 40 % improvement in performance by tweaking those numbers. Currently, I have to recompile `arrayfire` every time I change the above options.

**Comment by pavanky** [comment]
@mchandra I have already added option for MAX_JIT_LEN, but how significant is the performance improvement for local_0?

**Comment by mchandra** [comment]
Most of the 40 % bump I'm seeing on an Intel CPU is by increasing `local_0` from 256 to 1024.

**Comment by pavanky** [comment]
@mchandra I can force it to be 1024 for CPU devices. From my experience it didn't change much for GPUs.

**Comment by mchandra** [comment]
Yeah sure thing.
