### ISSUE TITLE
How to get a video/frame superfast into arrayfire?

### ISSUE THREAD

**Issue by gvgit** [arrayfire/arrayfire#1266]
I'm looking for a way to get a video processed much faster than real-time. I already took a look at [Image Processing with ArrayFire and OpenCV on the GPU](http://blog.accelereyes.com/blog/2012/09/19/image-processing-with-arrayfire-and-opencv/). Two nested for loops are shown there! This is much to slow for my needs.
Is there any other possibility to get the data from openCV into arrayfire? I could try libav or libvlc too. Maybe that would be easier but I don't know.

**Comment by 9prady9** [comment]
The blog you read was quite old and is pertinent to an older version (v2.1) of ArrayFire. It may not be relevant to the current version. Among many differences, the current version supports integral data types (int, uint, char, uchar) apart from floating point types. Also, the double for loop you referred to is basically converting format and transposing the input, both of which can be done of GPU, you might want to try it out.

[reorder](http://www.arrayfire.com/docs/group__manip__func__reorder.htm) can be used to convert non-interleaved channels into interleaved format - ```reorder(input, 2, 1, 0)``` should finish this operation.

[tranpose](http://www.arrayfire.com/docs/group__blas__func__transpose.htm) can be used to convert row-major to column major - This operation may not be needed at all if the image processing you are doing is not effected by major order of matrix(Image).

Natively, ArrayFire doesn't have a specific function/method that lets you extract frames from video/stream in it's `array`. You would have to use an external library that loads the frame and provide it to the `array` constructor.

There is an issue related to this feature #1106 where you can follow the progress of this feature implementation.

**Comment by 9prady9** [comment]
Closing this issue. Feature associated with this discussion is open [here](https://github.com/arrayfire/arrayfire/issues/1106).
