### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by gvgit** [arrayfire/arrayfire#1267]
I try to configure Arrayfire with

`cmake .. -DCMAKE_INSTALL_PREFIX=/opt/arrayfire -DCMAKE_BUILD_TYPE=Release -DBUILD_CUDA=ON -DBUILD_OPENCL=OFF`

but got the error message

`CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find CUDA (missing: CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (found
  version "7.5")
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindCUDA.cmake:806 (find_package_handle_standard_args)
  src/backend/cuda/CMakeLists.txt:3 (FIND_PACKAGE)`

but I have several cuda installations

`ls /usr/local/`
`bin        cuda      cuda-7.0  etc    include  LICENSE  README  share`
`ChangeLog  cuda-6.5  cuda-7.5  games  lib      man      sbin    src`

Is there something wrong?

**Comment by pavanky** [comment]
@gvgit can you do `ls -al /usr/local/cuda-7.5` ?

**Comment by gvgit** [comment]
`ls -al /usr/local/cuda-7.5/`
`total 72`
`drwxr-xr-x 15 root root 4096 Feb  8 19:12 .`
`drwxr-xr-x 13 root root 4096 Feb  8 19:14 ..`
`drwxr-xr-x  3 root root 4096 Feb  8 19:12 bin`
`drwxr-xr-x  5 root root 4096 Feb  8 19:12 doc`
`drwxr-xr-x  4 root root 4096 Feb  8 19:12 extras`
`drwxr-xr-x  2 root root 4096 Feb  8 19:12 include`
`drwxr-xr-x  3 root root 4096 Feb  8 19:14 lib64`
`drwxr-xr-x  8 root root 4096 Feb  8 19:12 libnsight`
`drwxr-xr-x  7 root root 4096 Feb  8 19:12 libnvvp`
`-rw-r--r--  1 root root  365 Aug 15 18:30 LICENSE`
`drwxr-xr-x  7 root root 4096 Feb  8 19:12 nvvm`
`-rw-r--r--  1 root root  365 Aug 15 18:30 README`
`drwxr-xr-x 12 root root 4096 Feb  8 19:13 samples`
`drwxr-xr-x  3 root root 4096 Feb  8 19:12 share`
`drwxr-xr-x  2 root root 4096 Feb  8 19:12 src`
`drwxr-xr-x  3 root root 4096 Feb  8 19:12 targets`
`drwxr-xr-x  2 root root 4096 Feb  8 19:12 tools`
`-rw-r--r--  1 root root   20 Aug 15 17:55 version.txt`

**Comment by gvgit** [comment]
It's working with cuda-7.0 but not with cuda-7.5.

**Comment by pavanky** [comment]
@gvgit what distro are you trying this on ? I'd like to test this out to see if it can be reproduced.

**Comment by pavanky** [comment]
@gvgit I just realized something. Can you try doing this after deleting everything in the build directory ?

If you installed CUDA-7.5 after arrayfire was already configured with CUDA 7.0 in the build directory, it could be causing some issues.

**Comment by gvgit** [comment]
Ubuntu 14.04 AMD64.
I fixed it with new CUDA and new openCV installation.
Thanks
