### ISSUE TITLE
Obtain arrayfire version at runtime

### ISSUE THREAD

**Issue by FilipeMaia** [arrayfire/arrayfire#1280]
It would be very useful to have a function that allows to return the arrayfire version at runtime.
One case where this would be useful is for the python bindings.

**Comment by pavanky** [comment]
This is already available since version 3.0!
you can use `af_get_version(&major, &minor, &patch);`

**Comment by pavanky** [comment]
Clearly not well documented :( , but it exists.

**Comment by FilipeMaia** [comment]
Oops :flushed:, I tried to search through the documentation website, but I didn't grep the headers.

**Comment by pavanky** [comment]
You can also get the commit hash using `char *commit = af_get_revision()` This only exists in devel currently and will be available post 3.3.

**Comment by FilipeMaia** [comment]
That's very thorough, thanks :)
