### ISSUE TITLE
How to restrict the size of retained best features?

### ISSUE THREAD

**Issue by gvgit** [arrayfire/arrayfire#1284]
I'm searching for a way to restrict the size of retained best features. In openCV this is very easy
```
int nfeatures = 400;
Ptr<SIFT> detector = SIFT::create(nfeatures);
```
like described here [cv::xfeatures2d::SIFT Class Reference](http://docs.opencv.org/master/d5/d3c/classcv_1_1xfeatures2d_1_1SIFT.html#gsc.tab=0).

How can I archieve the same with [Arrayfires sift implementation](http://www.arrayfire.com/docs/group__cv__func__sift.htm)?

**Comment by pavanky** [comment]
@gvgit We use feature ratio instead of a maximum number of features.

If you want `N` features you can pass the feature_ratio to be `(float)(N) / in.elements()`

**Comment by gvgit** [comment]
thanks
