### ISSUE TITLE
Cubic / Bicubic interpolation for approx1 and approx2 functions.

### ISSUE THREAD

**Issue by mchandra** [arrayfire/arrayfire#1289]
Documentation indicates the above options : http://www.arrayfire.com/docs/group__signal__func__approx1.htm

Doesn't look like the code exists: https://github.com/arrayfire/arrayfire/blob/devel/src/backend/opencl/approx.cpp

**Comment by pavanky** [comment]
@mchandra `AF_INTERP_BILINEAR` is implemented for `approx2`. for `approx1` you need to use `AF_INTERP_LINEAR`.

As for `AF_INTERP_CUBIC` and `AF_INTERP_BICUBIC`, we put the enums in place before 3.0 was released but decided to error out for now and add it as a feature at a later point.
