### ISSUE TITLE
arrafire, k-means and beeing out of memory

### ISSUE THREAD

**Issue by gvgit** [arrayfire/arrayfire#1290]
My data is too big for any memory, whether gpu or even cpu.

Has anybody implemented something similar to [Fast and Accurate k-means For Large Datasets](http://papers.nips.cc/paper/4362-fast-and-accurate-k-means-for-large-datasets.pdf)?

A dream to let such a k-means running on multiple gpu's.

**Comment by pavanky** [comment]
What k-means are you using ? Our example code ?

**Comment by gvgit** [comment]
Yes and CUDA-Implementations. My multi dimensional array is much larger than 12 GB, so it can't fit into my GPU-Card. I'm looking for some k-Means to handle such big arrays.

**Comment by pavanky** [comment]
You can certainly do this with some effort using arrayfire. There is no ready made solution for this. However I am not sure if this is the right avenue to discuss this issue.
