### ISSUE TITLE
Building with GLEW in non standar location

### ISSUE THREAD

**Issue by afhuertass** [arrayfire/arrayfire#1291]
Hi ! 

more than an issue, is that im trying to build arrayfire in a server in which i have no root access, so i install the GLEW library in my home. I have modified the FindGlew.cmake file and add  my home to some of the paths in that file.. and i can run sucessfully  "cmake . "  but when i run " make "  i get this error: 

-- Using Dynamic GLEWmx Lib
CMake Error at CMakeLists.txt:60 (MESSAGE):
  GLEW-MX not found

So, how can i fix it? 

thanks !

**Comment by shehzan10** [comment]
GLEW is also needed by Forge, which is built as an external project. You can use GLEW_ROOT_DIR to set the path when configuring CMake. 
```
cmake . -DGLEW_ROOT_DIR=/path/to/glew
```
Alternatively, you can also set `BUILD_GRAPHICS` to `OFF`, but this will disable all graphics functions.

**Comment by pavanky** [comment]
@afhuertass Is there any reason you want to build arrayfire with graphics on a server ? You can follow what shehzan said to disable graphics if you are always using it remotely.

**Comment by afhuertass** [comment]
Yes i think i dont need the graphic features... i'm a begginer with this, what kind of features provided by arrayfire? so far i have used it to code some fluid simulations, but for the visualization of the data  i use gnuplot.

**Comment by pavanky** [comment]
Arrayfire has basic plotting functionality but it's primary use case high performance visualization in real time. This is achieved by keeping the data on the GPU for the entire time without having to do round trips to the CPU.

For your usecase gnuplot may be a better solution because it is more feature rich at this moment.
