### ISSUE TITLE
Allow operations on af::seq inside GFOR

### ISSUE THREAD

**Issue by Daniel-Noethen** [arrayfire/arrayfire#1294]
I came up with the following code on the google user group and pavan asked me to create a feature request here on github.

```
int N = 4000;
array ar_window = constant(1, N);
gfor(seq i, 0, N)
{
    ar_window(i) *= 0.54 - 0.46*af::cos((2 * af::Pi * i) / (N - 1));
}
```

**Comment by pavanky** [comment]
@Daniel-Noethen I just realized a couple of things.

1) When using sequences and GFOR, if you just use one parameter it is (0 to N - 1). If you use two parameters, it is from (first to last). In this case it is trying to access `4001` elements and will cause indexing error. In your case you should either use `gfor(seq i, N)` or `gfor(seq i, 0, N-1)`.

2) Once (1) is fixed, a simple work around would be to do `af::Pi * af::array(i)`. This will ensure the code will work as intended.

**Comment by pavanky** [comment]
We are investigating why (2) is necessary at the moment. It looks like multiplying with `i` with `af::Pi` is having some unforseen side effects.
