### ISSUE TITLE
setUnique on GPU

### ISSUE THREAD

**Issue by pglock** [arrayfire/arrayfire#1300]
setUnique() does not work as expected on a GPU, if a row vector is used. 
```cpp
#include <iostream>
#include <arrayfire.h>

int main(void) {
  af::setBackend(AF_BACKEND_CUDA);
  int d[4] = {1,1,2,3};
  af::array col(4,d);
  af_print(col);
  af_print(af::setUnique(col));

  af::array row = af::transpose(col);
  af_print(row);
  af_print(af::setUnique(row));
  return 0;
}
```

For *col* setUnique returns [1,2,3]. For *row* however only 1 is returned.
On the CPU both tests return [1,2,3] as a column vector.

**Comment by pavanky** [comment]
@pglock This is now fixed in devel. `setUnique` will now return whatever shape input was. `setUnion` and `setIntersect` will however return column vectors.
