### ISSUE TITLE
Update doc for exp() that complex input is supported now

### ISSUE THREAD

**Issue by Daniel-Noethen** [arrayfire/arrayfire#1301]
Hi,

I hope this is the right way to tell you that the doc is still noting that complex numbers are not supported for the exp() function. In fact, complex numbers are supported since #944.

Daniel

**Comment by pavanky** [comment]
Thanks for pointing this out Daniel! This has been fixed in our devel branch. Our documentation should be fixed once 3.3 is out in a couple of days.
