### ISSUE TITLE
Fontconfig error: Cannot load default config file on Mac OSX 10.11.3

### ISSUE THREAD

**Issue by dvasiliu** [arrayfire/arrayfire#1302]
Hi Everyone,

I have a MacBook PRO with an NVIDIA discrete graphics card (750m) I succeeded to compile arrayfire without errors but when I try to run filters_cuda for example, I get:

ArrayFire v3.3.0 (CUDA, 64-bit Mac OSX, build fd660a0)
Platform: CUDA Toolkit 7.5, Driver: CUDA Driver Version: 7050
[0] GeForce GT 750M, 2048 MB, CUDA Compute 3.0
Fontconfig error: Cannot load default config file
ArrayFire Exception (Internal error:998):
@Freetype library:217: font face creation failed(3001)

In function void af::Window::initWindow(const int, const int, const char *const)
In file src/api/cpp/graphics.cpp:19
libc++abi.dylib: terminating with uncaught exception of type af::exception: ArrayFire Exception (Internal error:998):
@Freetype library:217: font face creation failed(3001)

In function void af::Window::initWindow(const int, const int, const char *const)
In file src/api/cpp/graphics.cpp:19
Abort trap: 6

I checked with brew install and I have both "fontconfig" and "freetype" libraries.

**Comment by shehzan10** [comment]
We have been able to run this on a OS X 10.11 system. Can you confirm whether you have the **Vera** font installed?

You can run `locate -i vera | grep ttf`. I believe freetype/fontconfig source the font from `/opt/X11/share/fonts/TTF/Vera.ttf`.

**Comment by dvasiliu** [comment]
Yes, when I run this command I get:

/opt/X11/share/fonts/TTF/Vera.ttf
/opt/X11/share/fonts/TTF/VeraBI.ttf
/opt/X11/share/fonts/TTF/VeraBd.ttf
/opt/X11/share/fonts/TTF/VeraIt.ttf
/opt/X11/share/fonts/TTF/VeraMoBI.ttf
/opt/X11/share/fonts/TTF/VeraMoBd.ttf
/opt/X11/share/fonts/TTF/VeraMoIt.ttf
/opt/X11/share/fonts/TTF/VeraMono.ttf
/opt/X11/share/fonts/TTF/VeraSe.ttf
/opt/X11/share/fonts/TTF/VeraSeBd.ttf
/usr/local/lib/python2.7/site-packages/matplotlib/mpl-data/fonts/ttf/Vera.ttf
/usr/local/lib/python2.7/site-packages/matplotlib/mpl-data/fonts/ttf/VeraBI.ttf
/usr/local/lib/python2.7/site-packages/matplotlib/mpl-data/fonts/ttf/VeraBd.ttf
/usr/local/lib/python2.7/site-packages/matplotlib/mpl-data/fonts/ttf/VeraIt.ttf
/usr/local/lib/python2.7/site-packages/matplotlib/mpl-data/fonts/ttf/VeraMoBI.ttf
/usr/local/lib/python2.7/site-packages/matplotlib/mpl-data/fonts/ttf/VeraMoBd.ttf
/usr/local/lib/python2.7/site-packages/matplotlib/mpl-data/fonts/ttf/VeraMoIt.ttf
/usr/local/lib/python2.7/site-packages/matplotlib/mpl-data/fonts/ttf/VeraMono.ttf
/usr/local/lib/python2.7/site-packages/matplotlib/mpl-data/fonts/ttf/VeraSe.ttf
/usr/local/lib/python2.7/site-packages/matplotlib/mpl-data/fonts/ttf/VeraSeBd.ttf

**Comment by pavanky** [comment]
@dvasiliu What version of fontconfig and freetype do you have ?

**Comment by dvasiliu** [comment]
I have fontconfig-2.11.1_2  and  freetype-2.6.3 .

**Comment by dvasiliu** [comment]
I got these packages by using "brew install".

**Comment by 9prady9** [comment]
Can you please check if you have fontconfig installed ?

**Comment by dvasiliu** [comment]
Yes, when I type "brew install fontconfig" I get
Warning: fontconfig-2.11.1_2 already installed"

**Comment by 9prady9** [comment]
@dvasiliu Sorry, it was by mistake, i asked you a redundant question.

**Comment by dvasiliu** [comment]
Sure, no problem. Also if I try to run the OpenCL version of any examples I get

ArrayFire v3.3.0 (OpenCL, 64-bit Mac OSX, build fd660a0)
[0] APPLE   : GeForce GT 750M, 2048 MB
-1- APPLE   : Iris Pro, 1536 MB
Segmentation fault: 11

**Comment by pavanky** [comment]
@dvasiliu what if you have `AF_DISABLE_GRAPHICS=1` before running opencl examples ?

**Comment by dvasiliu** [comment]
I tried it but I get verbatim the same error.

**Comment by 9prady9** [comment]
`FT_New_Face` thats the freetype function that is throwing error, which makes me wonder is the font file really being found by fontconfig on your machine.

**Comment by dvasiliu** [comment]
Very interesting, I also have a Mac desktop where I installed a Titan X card and I am not getting the same errors for OpenCL but if I run the CUDA versions it is either very slow or in many cases freezes the whole computer.

**Comment by dvasiliu** [comment]
How could I check if I have FT_New_Face ?

**Comment by 9prady9** [comment]
did you try reinstalling fontconfig and freetype ?

That is freetype library function, we can't check that unless we write code. You would have to write code using freetype and that would get complicated unless you have experience with freetype. 

Let me get back to you on this.

**Comment by dvasiliu** [comment]
Yes, I tried to reinstall the libraries but I get exactly the same error. Searching for an answer I saw that some people suggest a rebuilt for fontconfig and freetype form scratch (it is a bit delicate on Mac OSX)

http://freetype-devel.nongnu.narkive.com/OZTIXGOL/ft-new-face-undefined-symbol

**Comment by 9prady9** [comment]
I am trying to put together a small code stub that you can compile & run to see what is the issue. Please wait.

**Comment by dvasiliu** [comment]
Sure, thank you very much for all the help.

**Comment by pavanky** [comment]
@dvasiliu We've also tried testing this on one of our developer machines with the exact same hardware (and software) you seem to have. Something weird is happening..

**Comment by pavanky** [comment]
In any case, if you don't need visualization you can build arrayfire with graphics disabled to keep you going.

**Comment by dvasiliu** [comment]
Yes, it is strange as on the Mac desktop I do not get the same error although technically I have the same software and libraries installed. On the desktop the OpenCL versions of all the examples are working but the CUDA ones are very slow and/or freeze the computer.

**Comment by pavanky** [comment]
@dvasiliu for the cuda backend, are you building from scratch or did you build on your laptop and move it to the desktop ?

**Comment by 9prady9** [comment]
Please compile and run [this](https://gist.github.com/9prady9/7625a90600df0a90b2b7) on your machine.

I used the following command to compile it.
```sh
g++ -I /usr/include/freetype2 test.cpp -lfontconfig -lfreetype
```

Can you please run the executable and let me know the result.

**Comment by pavanky** [comment]
It need not be `g++`. You can use `clang++`

**Comment by dvasiliu** [comment]
Yes, because I also have gcc & gfortran 5.3 installed.

**Comment by dvasiliu** [comment]
When I run 
clang++ -I /usr/local/include/freetype2 fc.cpp -o fc  -lfontconfig -lfreetype
it compiles without issues but then when I try to execute fc it shows 
Fontconfig error: Cannot load default config file
1 error code 
Segmentation fault: 11

**Comment by 9prady9** [comment]
Okay, thats good hint. Can you change the code to call the function `loadFont` directly with this path `/opt/X11/share/fonts/TTF/Vera.ttf` i picked up that path from your earlier comment. Please amend it if necessary.

That should narrow the issue.

**Comment by dvasiliu** [comment]
I changed to loadFont("/opt/X11/share/fonts/TTF/Vera.ttf");
and I got Fontconfig error: Cannot load default config file
All is well:)

**Comment by 9prady9** [comment]
fontconfig on your machine is for some reason not able to locate he vera font.

**Comment by dvasiliu** [comment]
It definitely seems so, but I wonder how to fix it.

**Comment by 9prady9** [comment]
Can you try printing the `ttf_file_path` variable value before loadFont is called from loadSystemFont and see what it's returning.

**Comment by dvasiliu** [comment]
What would be the function name to print ttf_file_path ? is it sprintf(ttf_file_path) ?

**Comment by dvasiliu** [comment]
If I try printf(ttf_file_path) I get 
fc.cpp:64:5: error: no matching function for call to 'printf'
    printf(ttf_file_path);
    ^~~~~~
/usr/include/stdio.h:259:6: note: candidate function not viable: no known
      conversion from 'std::string' (aka 'basic_string<char, char_traits<char>,
      allocator<char> >') to 'const char *' for 1st argument
int      printf(const char * __restrict, ...) __printflike(1, 2);
         ^
1 error generated.

**Comment by 9prady9** [comment]
`std::cout<< "file path found is " << ttf_file_path << std::endl;`

**Comment by dvasiliu** [comment]
Thank you ! Now it compiles and says that the file path found is                      (blank)

**Comment by 9prady9** [comment]
looks like fontconfig issue rather than code. Try loading other fonts and see if fontconfig  prints any valid path for those.

**Comment by 9prady9** [comment]
If that didn't give any positive results, i would suggest uninstalling fontconfig completely without a trace, reboot and install it again. Hopefully that will remove the problem.

**Comment by dvasiliu** [comment]
I think I solved the fontconfig problem : I added a line in my .bash_profile such as 
export FONTCONFIG_PATH=/opt/X11/lib/X11/fontconfig:$FONTCONFIG_PATH
But now I get a different error when I try to run filters_cuda (from examples) : 

ArrayFire v3.3.0 (CUDA, 64-bit Mac OSX, build fd660a0)
Platform: CUDA Toolkit 7.5, Driver: CUDA Driver Version: 7050
[0] GeForce GT 750M, 2048 MB, CUDA Compute 3.0
libc++abi.dylib: terminating with uncaught exception of type af::exception
Abort trap: 6

Should I open a different "issue" for this one?

**Comment by dvasiliu** [comment]
Is it possible that if I would work in Linux I will not get such error(s)? Also, what version of Linux would you recommend?

**Comment by 9prady9** [comment]
@dvasiliu Sure, please open a different issue for that. It will be clean and clear to understand for any new readers.

We use wide range of linux distributions among our development machines and build machines, we didn't have to set such an environment variable ever before for fontconfig to function correctly.

Sure, you can give it a try on linux if that is possible for you. Any linux distribution should be fine, I personally use Arch variant - Antergos.

**Comment by katramadosi** [comment]
I also have the same setup and I installed the precompiled Arrayfire library. I get exactly the same error. I tried looking into the Arrayfire source code but couldn't figure out any bugs. Any help would be greatly appreciated. Thanks!

**Comment by katramadosi** [comment]
OK, I found the solution to this problem [here](http://stackoverflow.com/questions/35249881/octave-fontconfig-error). It goes like that:
> You should run command export FONTCONFIG_PATH=/opt/X11/lib/X11/fontconfig to setup fontconfig proper way. Also you can add line export FONTCONFIG_PATH=/opt/X11/lib/X11/fontconfig to your ~/.bash_profile and restart your terminal, so you don't need to run this command anymore.

**Comment by 9prady9** [comment]
This issue seems to be related to improper fontconfig installation. Closing the issue.

@arrayfire/core-devel  May be we can add this information to some OSX page in our documentation ?
