### ISSUE TITLE
Connected component on undirected graphical model

### ISSUE THREAD

**Issue by yunhunJang** [arrayfire/arrayfire#1308]
Hi,

I'm trying to get connected component on the undirected graph.
I have adjacency matrix. (and graph is not fully-connected but their are some missing edges), and with that matrix I'm trying to get the labels of components for each node and number of components.

I've been searching, but there is only regions function which is get the connected component on image.

Are there any implementations or some guide on this?

Any hints would be really appreciated. Thank you!

**Comment by pavanky** [comment]
@yunhunJang How is your adjacency matrix represented ?

**Comment by yunhunJang** [comment]
@pavanky
I have bipartite undirected graph (like rbm).
So my matrix is (num_vdim, num_hdim) dimension. 
Having edge is 1, otherwise 0. 
So, for example, if  row 2, col3 element was 1, second visible node is connected to third hidden node, and if it is 0, they are disconnected

**Comment by 9prady9** [comment]
This operation is not supported with ArrayFire. Although af::array can store adjacency matrix, I am not sure there is an algorithm that operates solely on the adjacency matrix to generated the connected components list of the graph.
