### ISSUE TITLE
Functions to get image moments 

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#1325]
- [x] M00
- [x] M01
- [x] M10
- [x] M11

-----------------------------------------------

Image moments could be used to get the following info about the image regions

- [ ] areas
- [ ] centroids
- [ ] Other central moments

**Comment by syurkevi** [comment]
Proposed function signature:

T moments(const array &image, af::moment=M00);
AFAPI af_err af_moments(af_array *out, const af_array image, af_moment=M00);

where enum af_moment {
M00 = 0,
M01 = 1,
M10 = 2,
M11 = 3
};
