### ISSUE TITLE
Setting up Eclipse for ArrayFire on Linux

### ISSUE THREAD

**Issue by zburazin** [arrayfire/arrayfire#1335]
Hello

I'm very new to ArrayFire and I'm struggling to set things up to use Eclipse.

I tried using the HelloWorld.cpp example code and the "Makefile with Existing Code" option from eclipse, but I didn't manage to **make** the project: 

`No rule to make target`

I guess i need to create a custom make target, but not sure what I need to put in here:

![create make target](https://cloud.githubusercontent.com/assets/16135452/13728525/212b2650-e91c-11e5-964a-a6a8c69c1684.JPG)

I'm aware this is probably a very low level problem but I've been stuck on this for days, unable to compile a HelloWorld example, so any help would be appreciated.

**Comment by pavanky** [comment]
@zburazin ArrayFire uses CMake which can be used to generate Eclipse projects. Are you trying to use it Linux ? If so we can create a wiki page with some instructions.

P.S. Do not wait for days the next time :)

**Comment by zburazin** [comment]
I didn't want to a bother people with stupid questions. :D 

Yes, I'm using Linux (Centos 7.2). How exactly do I generate an Eclipse project? 

For example, in the meanwhile I downloaded the Project Template (https://github.com/arrayfire/arrayfire-project-templates/tree/master/CMake) and followed the short description and I got this:

```
[zburazin@alfa00 build]$ make
Scanning dependencies of target FOO_CORE
[100%] Building CXX object src/CMakeFiles/FOO_CORE.dir/main.cpp.o
[100%] Built target FOO_CORE
Scanning dependencies of target foo-cpu
Linking CXX executable ../../bin/foo-cpu
[100%] Built target foo-cpu
Scanning dependencies of target foo-cuda
Linking CXX executable ../../bin/foo-cuda
/usr/bin/ld: warning: libcudart.so.7.5, needed by /usr/local/lib/libafcuda.so.3.3.0, may conflict with libcudart.so.7.0
[100%] Built target foo-cuda
```

What next?

**Comment by pavanky** [comment]
@zburazin What version of CUDA do you have on your system ? More importantly are you working on 64 bit or 32 bit?

**Comment by zburazin** [comment]
I have both CUDA 7.0 and 7.5 installed. I'm not sure about 32 or 64, but i presume it's 64 since its a machine used for a bunch of calculations and similar work that would benefit from a 64bit system.

I'm working remotely from home on a server at my college, so I don't have a lot of permissions on the machine itself, but i can ask for confirmation if needed.

**Comment by pavanky** [comment]
@zburazin Can you copy  the output of `uname -a` over here?

**Comment by zburazin** [comment]
Linux alfa00 3.10.0-327.4.5.el7.x86_64 #1 SMP Mon Jan 25 22:07:14 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by pavanky** [comment]
@zburazin Excellent this should not be a problem. We will get some instructions about how to use arrayfire with eclipse ASAP.

**Comment by syurkevi** [comment]
@zburazin How are you accessing the remote machine?

**Comment by zburazin** [comment]
Sorry, I forgot to answer this question. I use X2GO + OpenVPN to acces the remote machine

**Comment by zburazin** [comment]
Any progress @syurkevi ? :D

**Comment by syurkevi** [comment]
So to get a minimal helloworld.cpp example working in eclipse:
* New -> Empty C++ Project -> **use defaults in wizard**
* right click on project -> New File (main.cpp) -> copy paste hello world code
* right click on project -> Properties -> Build -> Settings -> Then choose the "Tool Settings" tab
    * under C++ Linker > Libraries
        * add **nvvm**
        * add **afcuda**
    * under C++ Linker > Library search path
        * add **/usr/local/lib**  -- or wherever the Arrayfire libraries are installed
        * add **/usr/local/cuda/nvvm/lib64** -- or wherever you cuda nvvm libraries are installed

That should do the trick!
If you get errors after compilation, go ahead and under 
Project Properties -> Run/Debug Settings
* Edit the project's launch configuration
    * Under the "Environment" tab
       * New -> 

Name = **LD_LIBRARY_PATH**
Value =  **/usr/local/cuda/nvvm/lib64** -- or whatever the library location was in the previous step

The location of any of the needed libraries can be found using the ```locate  {afcuda.so,libnvvm.so}``` command.
Good luck, and let me know if you have any issues!

**Comment by pavanky** [comment]
@zburazin Closing the issue. Let us know if this causing an issue for you.

P.S. You can replace `afcuda` with `af` for unified, `afopencl` for opencl and `afcpu` for cpu backends.

We suggest you add `af` for maximum compatibility. If you do this, you will need to append path to arrayfire libs to `LD_LIBRARY_PATH` flag.
