### ISSUE TITLE
BLAS benchmark not giving the right throughput for CUDA backend

### ISSUE THREAD

**Issue by romeric** [arrayfire/arrayfire#1338]
I have been running the BLAS benchmark found under examples, and the results I am obtaining with CUDA does not look right to me. I am on Intel Xeon E5-2650 v2 @2.6GHz with Nvidia Quadro K4000 GPU.

Here is performance of `matmul` single precision, with MKL backend (compiled with `-lafcpu -O3`)

    ArrayFire v3.3.0 (CPU, 64-bit Linux, build 5842ed2)
    [0] Intel: Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz, 32120 MB, Max threads(16) 
    Benchmark N-by-N matrix multiply
     128 x  128:   164 Gflops
     256 x  256:   246 Gflops
     384 x  384:   284 Gflops
     512 x  512:   298 Gflops
     640 x  640:   303 Gflops
     768 x  768:   316 Gflops
     896 x  896:   318 Gflops
    1024 x 1024:   324 Gflops
    1152 x 1152:   327 Gflops
    1280 x 1280:   333 Gflops
    1408 x 1408:   327 Gflops
    1536 x 1536:   329 Gflops
    1664 x 1664:   322 Gflops
    1792 x 1792:   326 Gflops
    1920 x 1920:   319 Gflops
    2048 x 2048:   316 Gflops
     ### peak 332.538 GFLOPS  

This should be okay as the CPU's theoretical peak performance is 332.8 GLOPS. And now for the  CUDA version (`-lafcuda -lnvvm -O3`)

    ArrayFire v3.3.0 (CUDA, 64-bit Linux, build 5842ed2)
    Platform: CUDA Toolkit 7.5, Driver: 352.63
    [0] Quadro K4000, 3072 MB, CUDA Compute 3.0
    Benchmark N-by-N matrix multiply
     128 x  128:    89 Gflops
     256 x  256:   475 Gflops
     384 x  384:   487 Gflops
     512 x  512:   558 Gflops
     640 x  640:   549 Gflops
     768 x  768:   580 Gflops
     896 x  896:   571 Gflops
    1024 x 1024:   591 Gflops
    1152 x 1152:   584 Gflops
    1280 x 1280:   597 Gflops
    1408 x 1408:   592 Gflops
    1536 x 1536:   601 Gflops
    1664 x 1664:   598 Gflops
    1792 x 1792:   604 Gflops
    1920 x 1920:   601 Gflops
    2048 x 2048:   606 Gflops
     ### peak 605.598 GFLOPS 

According to my calculation and [vendor info](https://en.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units#Quadro_Kxxx_Series) this is essentially half the theoretical performance of the GPU. I am assuming ArrayFire uses cuBLAS in the background, and 50% throughput with cuBLAS just does not look right to me, unless I am missing something obvious. Could some one explain as to what is happening?

**Comment by pavanky** [comment]
@romeric We straight up use cuBLAS without any modifications. Even in NVIDIA's [benchmark figures](https://developer.nvidia.com/cublas) the performance of K40 is a little above 2 TFLOPS while the theoretical limit is > 4 TFLOPS. The reason for discrepency *may be* (I am only guessing here) because of the fact NVIDIA counts the flops based on FMAD operations where as BLAS routines may not be using FMAD because of accuracy concerns.

**Comment by RBdane2** [comment]
I had a similar situation last week when I installed a new gtx970. It turned out I had installed it in a pcie x8 slot (normally x16 unless there is a card in slot1). I was getting exactly half the bandwidth, until I moved slots. Now I get 2.3Tflops on the Blas benchmark.

**Comment by pavanky** [comment]
@RBdane2 According to wikipedia the theoretical peak is 3.5 TFLOPS. Also PCIE should not matter for this benchmark.. All the data is on the GPU while the benchmark is running.

**Comment by romeric** [comment]
@pavanky That makes sense. I have been looking at some other benchmarks, and they also achieve around the 50-60% peak for `sgemm`. For completeness, here are the `opencl` results:

    ArrayFire v3.3.0 (OpenCL, 64-bit Linux, build 5842ed2)                                                
    [0] NVIDIA  : Quadro K4000, 3071 MB
    Benchmark N-by-N matrix multiply
     128 x  128:    57 Gflops
     256 x  256:    66 Gflops
     384 x  384:   170 Gflops
     512 x  512:   240 Gflops
     640 x  640:   233 Gflops
     768 x  768:   173 Gflops
     896 x  896:   240 Gflops
    1024 x 1024:   243 Gflops
    1152 x 1152:   313 Gflops
    1280 x 1280:   244 Gflops
    1408 x 1408:   245 Gflops
    1536 x 1536:   311 Gflops
    1664 x 1664:   246 Gflops
    1792 x 1792:   247 Gflops
    1920 x 1920:   312 Gflops
    2048 x 2048:   246 Gflops
     ### peak 313.091 GFLOPS

Wondering, what implementation of BLAS you guys use for opencl backend? or do you use one at all?

**Comment by pavanky** [comment]
@romeric For OpenCL we statically link with clBLAS by default. clBLAS's default configuration is not super performant on NVIDIA GPUs but it can be tuned to improve performance. We are trying to see how we can integrate the clBLAS tuner into arrayfire.

I am closing the issue because cuBLAS performance is not a  anymore.

**Comment by Brainiarc7** [comment]
Hey there,

I can explain the discrepancy.

in your Nvidia panel, check whether full   FP64  compute is enabled (Double precision).

Some Quadro and Tesla GPUs have such a control, and when enabled, literally halves FP32 and FP16 compute as a saccrice for greater FP64 (Double precision) performance.

Had a similar issue with the original Titan on Linux.

**Comment by Brainiarc7** [comment]
You may want to refer to this on modifying the setting for Double precision on the GPU's panel:

http://forums.evga.com/When-to-Use-Double-Precision-under-NVIDIA-Control-Panel-Manage-3D-Settings-m2252867.aspx

**Comment by Brainiarc7** [comment]
Also, refer to Arrayfire's wiki entry on Double precision perf:

http://arrayfire.com/explaining-fp64-performance-on-gpus/

**Comment by pavanky** [comment]
@Brainiarc7 Our blas example uses single precision. Double precision performance is not relevant here.

**Comment by Brainiarc7** [comment]
Thanks for the clarification, @pavanky 

@romeric , try unchecking the setting for Double precision perf if your Nvidia control panel has it.
When activated, the option cuts GPU perf for FP16 and FP32 math to ~50%.
