### ISSUE TITLE
Support One-to-One batch mode in transform

### ISSUE THREAD

**Issue by shie0041** [arrayfire/arrayfire#1346]
Allow batch-mode processing for translate() to allow

1. The same image to be translated according to specified vectors of row and column shifts.
2. Multiple images to be translated by the same scalar row and column shifts.

This is useful in image processing, for instance, to register and add multiple images to reduce noise. An implementation of this capability in the generalized transform() function would be useful as well.

**Comment by shehzan10** [comment]
In response,
 1. This is supported, but through transform. [This](https://groups.google.com/forum/#!topic/arrayfire-users/0jE6xQD_OVo) is this relevant discussion about how to create the transformation matrices. For each set of row/column shifts, it should be a different channel in the transformation matrix. That is, if you have N shifts, then your transformaion matrix will be of size 3x2xN.
 2. This is already supported in both transform and translate. Multi-images are essentially the same array tiled along the 3rd dimension.

**Comment by shie0041** [comment]
Sorry - in the relevant discussion you linked to, Pavan recommended creating a feature request to support batch mode, hence this request.

One thing I found in regards to this:  I have an array of images called scenes that is 128x128x50x1 and a transform matrix T that is 3x2x50x1.  I thought I would be able to batch-mode transform these via:

array batch = transform(scenes, T, scenes.dims(0), scenes.dims(1), af_interp_type::AF_INTERP_BILINEAR);

I would have thought this would take the nth scene and apply the nth transform matrix so that batch would also be 128x128x50x1 (similar to the Identical Batches option of convolve2).  Instead it is 128x128x2500x1.

**Comment by shehzan10** [comment]
So transform does batch mode both ways. That is if you have an N channel image and M transforms,  then each of N is going to return M images for the transforms.  That's why you see 2500 channels. 
If you are using the same transform and tiling it 50 times, that's wrong. You technically have one transform and you can just use that. It will be applied to all image channels.

**Comment by shie0041** [comment]
How do I get transform() to work in Identical Batches mode?  Based on the documentation for convolve2() I thought I had it write in that both the images and the transform matrix have the same number of elements in the third dimension.

Thanks, by the way.

**Comment by shehzan10** [comment]
Yeah we missed that one-to-one case (my bad). We covered 3 case of batching, but missed one.

The long way around is to run the code and then call indexing to pick out the right channels.
I haven't benchmarked it, but I think for now using a for loop would be the way to go. It should not be a significant performance hit. 
```
array out(scenes.dims());
for(i = 0; i < 50; i++)
    out(span, span, i) = transform(scenes(span, span, i), tf(span, span, i), scenes.dims(0), scenes.dims(1));
```

I'll be renaming the topic and see how we can incorporate a one-to-one batch mode.

**Comment by shie0041** [comment]
Thanks.  I've got the for-loop coded now, so I'll leave it as-is.  I'm in the process of trying to optimize/simplify my code by replacing for loops with vectorized code wherever possible.

**Comment by pavanky** [comment]
The missing case could be fixed easily for our next bugfix release.
