### ISSUE TITLE
Do not destroy externally added device, queue and context for OpenCL backend

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#1350]
This will cause interop problems in languages where the contexts are cleaned up automatically by the other library

**Comment by 9prady9** [comment]
In that case, we probably should do a `retain` on those ocl objects when they are provided to ArrayFire and then a `release` when ArrayFire is done using that object. Right ?

**Comment by pavanky** [comment]
@9prady9 That sounds like the simplest solution yes.

**Comment by pavanky** [comment]
Fixed in hotfix-3.3.2
