### ISSUE TITLE
Uninstaller doesn't remove from non-default install location

### ISSUE THREAD

**Issue by Reithan** [arrayfire/arrayfire#1351]
After acquiring the 3.3.1 no-GL installer, it detects that ArrayFire is already installed and attempts to run the uninstaller. However, uninstaller attempts removal from default location, while my install was at G:\ArrayFire. No actual uninstall took place.

**Comment by shehzan10** [comment]
This is reproduced only when older version is installed to a non-default location and the uninstaller is called by a newer version of the installer. There is an installer available in the older version's non-default install location which still uninstalls the files correctly.

I'm working on a fix for this.

**Comment by shehzan10** [comment]
I've fixed this in the installer generator (not a part of ArrayFire).
The updated installers will be shipped with v3.3.2.
