### ISSUE TITLE
array assignment using arrays as indices needs a lot of memory

### ISSUE THREAD

**Issue by mricherzhagen** [arrayfire/arrayfire#1355]
I have the following code:

	const int N = 70000;

	af::array target = af::constant(0, 10, N, s32);
	target(af::constant(1, N), af::seq(0, N - 1)) = 1;

which fails with 

```
ArrayFire v3.3.1 (CPU, 64-bit Linux, build default)
[0] Intel: Intel(R) Core(TM) i7 CPU       M 620  @ 2.67GHz, 7848 MB, Max threads(4) 

terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Device out of memory:101):
In function virtual void* cpu::MemoryManager::nativeAlloc(size_t)
In file src/backend/cpu/memory.cpp:67
Unable to allocate memory

In function af::array::array_proxy& af::array::array_proxy::operator=(const af::array&)
In file src/api/cpp/array.cpp:516
```

The `af::constant(1, N)` is only for testing purposes.  I tried a normal array with values between 0 and 9 before, but it failed with the same error.

Doing the Math in my head i only see a potential for a ( N * 10 + N + N  ) * 4 Byte memory requirement, which would not be more than 3MB for N = 70 000. And i'm pretty sure that i have 3MB available...

##### What i'm trying to achieve with this code:

I have an array which contains N numbers (`af::constant(1, N)` in the example). I then want to have a 2 dimensional array in which only one row in every column is set to 1. Based on the content of the array.

Maybe this numpy example describes it best:
```python
>>> import numpy as np
>>> a = np.array([0,0,2,2,1])
>>> target = np.zeros((3, 5))
>>> target[a,np.arange(0,5)] = 1
>>> target
array([[ 1.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  1.,  1.,  0.]])
>>> 
```

**Comment by pavanky** [comment]
@mricherzhagen ArrayFire does not do numpy type indexing. In the arrayfire code you showed you are trying to indexing 70000, 70000 array but your input is only 10 x 70000. 

To achieve what you want you need to do something like this in arrayfire:

`target(af::seq(N) * target.dims(0) + a) = 1;`

There is no other solution for now.

**Comment by mricherzhagen** [comment]
The code worked for small N, though... 

Thanks for that workaround.

**Comment by FilipeMaia** [comment]
As pavanky said arrayfire and numpy work differently.  For example if one has [0,1],[0,1] as the two arrays for numpy this would mean that the coordinates retrieved would be [0,0],  [1,1] while for arrayfire it would be [0,0], [0,1], [1,0], [1,1]. Arrayfire takes all possible combinations between the elements of the two arrays instead of combining only those at the same position.

**Comment by pavanky** [comment]
> The code worked for small N, though...

It is either a coincidence it worked or you did not verify the results properly. It *should not* work.

**Comment by pavanky** [comment]
Btw we have this issue open to implement the functionality for indexing: https://github.com/arrayfire/arrayfire/issues/902

I think I will update it to mention assignment as a requirement as well.
