### ISSUE TITLE
Norm not returning same value for [0, 0, 1] and [1, 0, 0] vectors

### ISSUE THREAD

**Issue by 1IfByLAN2IfByC** [arrayfire/arrayfire#1357]
When calling the c++ norm function, if the first element of a row vector is zero _norm_ returns 0. See sample output below.

First element nonzero (correct)
--------------------------------------------------
norm(testme)
[1 1 1 1]
    0.0000 
testme
[1 3 1 1]
    1.0000     0.0000     0.0000 

Second element nonzero (wrong)
----------------------------------------------------
testme
[1 3 1 1]
    0.0000     1.0000     0.0000 
norm(testme)
[1 1 1 1]
    0.0000 

Third element nonzero (wrong)
------------------------------------------------------
testme
[1 3 1 1]
    0.0000     0.0000     1.0000 
norm(testme)
[1 1 1 1]
    0.0000 

tested on arrayfire 3

**Comment by 1IfByLAN2IfByC** [comment]
norm returns a double but can be typecast to an array of length norm. the spookiness was coming from that.

**Comment by pavanky** [comment]
Hmm we should really avoid that.
