### ISSUE TITLE
FTBFS on Fedora 22: CBLAS installed but not found when using GNU GSL BLAS

### ISSUE THREAD

**Issue by eyalroz** [arrayfire/arrayfire#1359]
I have GNU GSL's cblas installed, having

```
/usr/include/cblas.h
/usr/include/gsl/gsl_cblas.h
/usr/lib64/libgslcblas.so
```

etc. on my system (a Fedora 22 on Linux x86_64). And yet, when I cmake ArrayFire, I get:

```
-- CBLAS Symbols NOTFOUND
CMake Error at CMakeModules/FindCBLAS.cmake:336 (MESSAGE):
  CBLAS library not found.  Please specify library location
Call Stack (most recent call first):
  src/backend/cpu/CMakeLists.txt:4 (FIND_PACKAGE)
```

Either this is a bug, or the error message needs to be more specific about what exactly it's missing.

**Comment by pavanky** [comment]
@eyalroz We did not anticipate someone using `libgslcblas.so`.  Up until this point I thought it had a different API. I will look into fixing this.

**Comment by eyalroz** [comment]
For now my sysadmin installed libopenblas-dev (and maybe some other packages), and I got past that issue (and to another one).

**Comment by shehzan10** [comment]
Can you please test this with the current devel branch? This may have been fixed by #1657

**Comment by eyalroz** [comment]
Sorry, I no longer have access to a system on which I can reproduce this...

**Comment by shehzan10** [comment]
Sure. Thanks for that update.
