### ISSUE TITLE
fftconvolve performance

### ISSUE THREAD

**Issue by ZacDiggum** [arrayfire/arrayfire#1361]
In fftconvolve.cpp I noticed nextpow2 several times. Do the fft based convolutions pad to power of 2 sizes? Because clfft 

> supports dimension lengths that can be any combination of powers of 2, 3, 5, and 7.

That might lead to smaller array sizes and thus improved performance and lower memory demands.

**Comment by pavanky** [comment]
@ZacDiggum Here's a demonstration of the performance on a R9 390x:
```
ArrayFire v3.3.2 (OpenCL, 64-bit Linux, build 5409155)
[0] AMD     : Hawaii, 7596 MB
-1- NVIDIA  : GeForce GTX 950, 2047 MB
-2- AMD     : Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz, 14998 MB
Benchmark N-by-N 2D fft
2048 x 2048:  0.001090 secs
1536 x 1536:  0.003835 secs
1920 x 1920:  0.003082 secs
```

The space requirements may be better, but the performance is much lower.

**Comment by pavanky** [comment]
This is how it is on CUDA on a K20

```
./examples/benchmarks/fft_cuda 
ArrayFire v3.3.0 (CUDA, 64-bit Linux, build fd660a0)
Platform: CUDA Toolkit 7.5, Driver: 358.16
[0] Tesla K20c, 5120 MB, CUDA Compute 3.5
-1- Tesla K20c, 4800 MB, CUDA Compute 3.5
-2- Quadro 6000, 6144 MB, CUDA Compute 2.0
Benchmark N-by-N 2D fft
2048 x 2048:  0.001561 secs
1536 x 1536:  0.001496 secs
1920 x 1920:  0.002079 secs
```

**Comment by pavanky** [comment]
FFTW seems to do better on the CPU:
```
$ ./examples/benchmarks/fft_cpu 
ArrayFire v3.3.0 (CPU, 64-bit Linux, build fd660a0)
[0] Intel: Genuine Intel(R) CPU  @ 2.60GHz, 48351 MB, Max threads(16) 
Benchmark N-by-N 2D fft
2048 x 2048:  0.348779 secs
1536 x 1536:  0.194729 secs
1920 x 1920:  0.260875 secs
```

**Comment by ZacDiggum** [comment]
How are 1536 and 1920 powers of 3 or 5? I mean for example an array of size 2049 gets padded to 4096 instead of 2187 (power of 3). Or when convolving two 2049 arrays one could pad to  6561 (power of 3)  instead of 8192...

**Comment by pavanky** [comment]
@ZacDiggum I was checking for a combination of 2, 3 and 5. I could check the sizes you mentioned as well.

**Comment by pavanky** [comment]
As you can see 2187 is faster than 4096, but 6561 is slower than 8192. It'll require a lot of tuning to get the best out of it..

```
ArrayFire v3.3.2 (OpenCL, 64-bit Linux, build 5409155)
[0] AMD     : Hawaii, 7596 MB
-1- NVIDIA  : GeForce GTX 950, 2047 MB
-2- AMD     : Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz, 14998 MB
Benchmark N-by-N 2D fft
4096 x 4096:  0.004945 secs
2187 x 2187:  0.001723 secs
6561 x 6561:  0.038463 secs
8192 x 8192:  0.029124 secs
```

**Comment by ZacDiggum** [comment]
Ah okay, I'm convinced. :-) You also checked the combinations, that's smart. Okay, nevermind.
