### ISSUE TITLE
Bulding on a GPU-less machine: No (obviousl) way to set target CUDA Compute Capability

### ISSUE THREAD

**Issue by eyalroz** [arrayfire/arrayfire#1362]
I'm building (well, trying to build) ArrayFire 3.3.1 on a machine with no relevant GPU (but with CUDA 7.5). What I'm getting is that Compute Capabilities 20, 30 and 50 are enabled. But what if I'm targetting a device with is 35 (3.5) or 52 etc.? 

I should be able to specify - say, in an environment variable - the target compute capability values I want. You'll note that in CUDA's samples Makefiles they use a string with the different SM values relevant; perhaps a CUDA_SM variable with a space-separated list of values? And an indication that instead of the default one can set this value to whatever one would like?

**Comment by shehzan10** [comment]
Those are the default computes ArrayFire picks up when there is no GPU. You have 2 options to specify computes:
* -DCOMPUTES_DETECTED_LIST="SM;SM;SM" (semicolon separated list of 2 digit compute versions). This automatically disables compute detection.
* -DCUDA_COMPUTE_XY=ON, where XY is the 2 digit compute version. If you do not want the CUDA to detect computes, then set -DCUDA_COMPUTE_DETECT=OFF.

All these options are available under CMake's advance options for you to verify.

**Comment by eyalroz** [comment]
@shehzan10 : Perhaps you could consider mentioning these two (or at least the first one) in the message about choosing the default 20-30-50 combination?

**Comment by shehzan10** [comment]
We'll look into it.

**Comment by Brainiarc7** [comment]
Is this documented?

It'd be good to have separate documentation on the same (As regards configuration options available via CMake) to avoid such situations.

**Comment by shehzan10** [comment]
We'll looking into adding a Wiki entry for all the cmake options.

**Comment by shehzan10** [comment]
Added comments in the hotfix-3.2.2 branch to show the compute options when default computes are being used. The CMake entries will be added on a wiki page soon.
