### ISSUE TITLE
Application Doesn't stop after calculations are done

### ISSUE THREAD

**Issue by afhuertass** [arrayfire/arrayfire#1364]
Hi. I have a code with something the next structure 

```
 rhos = this->rho();
  Ux = (this->Jx()/rhos) ;
  Uy = (this->Jy()/rhos) ;
  Uz = (this->Jz()/rhos) ;
  
  array feq = this->feq3( rhos, Ux , Uy , Uz);

  for( int i = 0 ; i < q ; i++){
    fs[i] += beta*( feq(span,span,span,i) - fs[i]);
  }
```
which has to be called thousands of times. Ux, Uy,Uz and rhos are 3D arrays and fs is a  STL vector strcuture. But the problem is that the process never stop once the calculations are done, i check this with a cout in the class destructor. It keeps running and dont release the memory in the GPU. I tested this in a TeslaK40 and in my personal card. 
In my card the process keeps doing nothing for a while and then releases the memory. in the big card... i being waiting for over an hour and still just hanging in there. 

the full code used can be found in my repository : https://github.com/afhuertass/ArrayFireLB/blob/master/src/LBD3Q15.cpp 

Any idea what's going wrong? 
Thanks.

**Comment by pavanky** [comment]
@afhuertass 

1) We need a more stand alone case to reproduce this. The file you linked to is too big to narrow down.

2) What version of arrayfire and what GPU are you using?

**Comment by afhuertass** [comment]
Hi 
@pavanky  here is the af::info() for the GPU used:
```
ArrayFire v3.3.0 (CUDA, 64-bit Linux, build 5842ed2)
Platform: CUDA Toolkit 7.5, Driver: 352.39
[0] Tesla K40m, 11520 MB, CUDA Compute 3.5
-1- Tesla K40m, 11520 MB, CUDA Compute 3.5
```
 The code has a single class and i just realize it hangs even if the programm doest nothing ( setting my step variable to cero ) just creating that Class lead to that behavior. 

I create other repository holding just the headers of the class and the constructor, even that simple code dies runing in the mentioned GPU ( the gpu is a server at my College, is new and maybe there is something wrong with the build of ArrayFire, the operating system is RedHat 7.2 ) 

https://github.com/afhuertass/ArrayFireIssue1364/blob/master/src/main.cpp

**Comment by pavanky** [comment]
@afhuertass Do you see the problem when you run other arrayfire examples?

**Comment by afhuertass** [comment]
yes ... i tested a few, the blas and the examples of a blog post called "How to write vectorize code"

but is really weird cause i remember that before i tested them and worked just fine.  it can be caused by other process running in the GPU? . other guy has a process in there and its being running for several days ( i haven't talk to he, to ask what is doing in the machine) 
here is what the nvidia-smi drops : 
![ssf10](https://cloud.githubusercontent.com/assets/16570373/14062139/535846d0-f362-11e5-943b-3ed3c217bc93.png)
 
if i dont kill the process ./lattice and ./blas_cuda the will keep running like forever. 

And here the results of the blas benchmark. the calculations and doe but... 
![Uploading ssf102.png…]()

**Comment by pavanky** [comment]
@afhuertass FYI you can use https://gist.github.com/ to copy one off files. You dont need to create a new repo.

**Comment by pavanky** [comment]
@afhuertass can you run some cuda samples from the cuda toolkit ? I am not sure what's happening, but could it be that someone else is also using the server right now ?

**Comment by pavanky** [comment]
@afhuertass And yes another GPU process can definitely slow things down. However the `nvidia-smi` is showing that the other process is only happening on GPU0, is your problem happening on GPU1 as well?

**Comment by afhuertass** [comment]
@pavanky 
Yes i run my process in the other GPU ( i run things in GPU1 ) . and there is no other process. I feel realy confused because i been battling with this for weeks. At the begining i thought it was a problem of my code ( something like the implementation of my problem was leaking memory or something ) but now i see it can't run correclty a simple process. with this problem i think that even try to improve the performance of the code is a waste of time. 
Running the code in my personal machine dont leat to that problem. ( just some othe problem like a performance drop after a couple steps) 

I ask the system administrator and he says he install ArrayFire from the binaries. maybe install it from the source could solve the problem? 

I really like the ArrayFire library, but this is driving me crazy. and soon i will have to stop worring about performance and try to get the results for my thesis even with the bad code. 

One more question, the  2900 GFLOPS that are showed in the image for the blas benchmark are correct for this kind of graphic card?

**Comment by pavanky** [comment]
@afhuertass The performance seems to be about par for a K40. I don't think this is a problem with arrayfire.

Can you test any other CUDA program on your machine ?

**Comment by afhuertass** [comment]
Hi  again @pavanky and thank for your time and interest. 

No .. i try the examples in the cuda Toolkit but the same behavior is found, they hang and do nothing forever. At this point for sure is not an ArrayFire issue, but you have any idea of what could be? 

thanks.

**Comment by pavanky** [comment]
@afhuertass a reboot may fix the issue but I am running out of ideas..

**Comment by afhuertass** [comment]
Regarding this issue, there is something new. 

I'm not any more with this problem, the system was not reboot. The only thing different was that the proccess in the other Card stop running.  so i don't know what could be happening... maybe a bad hardware setup? 

Thanks for your time and previus answers.

**Comment by pavanky** [comment]
@afhuertass I should have asked you to try this earlier.. ArrayFire goes through the list of all devices when starting up. Perhaps that was slowing down the startup time..

If you see something like this happening next time try running `export CUDA_VISIBLE_DEVICES=1` (assuming GPU0 is taken up by something else) in command line before running CUDA / arrayfire code. This flag will only show the second GPU to CUDA applications (including arrayfire) and will not cause a slow down.
