### ISSUE TITLE
errors when using ArrayFire v3.3.1 on Ubuntu 14.04, 32bit Linux and ArrayFire-Python

### ISSUE THREAD

**Issue by colbyshores** [arrayfire/arrayfire#1365]
Im getting an error when I try an run the "Hello World" example on Ubuntu 14.04, ArrayFire v3.3.1 using the ArrayFire-Python bindings.
Im on a Tegra K1 based system and it returns the same error in file data.cpp at the same line reguardless of wither I am using Cuda or CPU.
I have attached my output from the python interpreter.  I know that Cuda is working because af.info() is reporting it's detection.  Reached out to, Pavan Yalamanchili and he advised to file a bug report as this to be a bug in the 32bit version on Linux.
Thanks,
Cole

```
Python 2.7.6 (default, Jun 22 2015, 18:31:26) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import arrayfire as af
>>> af.info()
ArrayFire v3.3.1 (CUDA, 32-bit Linux, build f53efc3)
Platform: CUDA Toolkit 6.5, Driver: CUDA Driver Version: 6050
[0] GK20A, 4018 MB, CUDA Compute 3.2
>>> af.display(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'a' is not defined
>>> a = af.randu(5 ,1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/arrayfire/data.py", line 223, in randu
    safe_call(backend.get().af_randu(ct.pointer(out.arr), 4, ct.pointer(dims), dtype.value))
  File "/usr/local/lib/python2.7/dist-packages/arrayfire/util.py", line 75, in safe_call
    raise RuntimeError(to_str(err_str))
RuntimeError: In function verifyDims
In file src/api/c/data.cpp:42
Invalid dimension for argument 2
Expected: dims[i] >= 1

>>> quit()
```

**Comment by pavanky** [comment]
@colbyshores you should be opening python related issues [over here](https://github.com/arrayfire/arrayfire-python/issues). Closing this here and opening in the proper place.
