### ISSUE TITLE
Add option to disable CPUID in cmake

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#1369]
Failing to compile because of `CPUID` on 32bit linux VMS on 64bit machines when using KVM (did not test on virtualbox).

Right now `USE_CPUID` is being picked up automatically based on architecture. We should have an option to disable it from `cmake`.

**Comment by shehzan10** [comment]
I think the thought was that because `USE_CPUID` is defined in the header file, it can be disabled easily. I may be wrong, but I don't think there is a singe rule to govern the availability of CPUID.

**Comment by pavanky** [comment]
@shehzan10 I don't mean to automatically detect in cmake, but give the user the ability to disable it. I am fixing it.

**Comment by pavanky** [comment]
Fixed in hotfix-3.3.2
