### ISSUE TITLE
Performance improvements to BLAS in OpenCL for non AMD GPU hardware

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#1374]
Currently using clBLAS:
- NVIDIA hardware gets about 50% of what cuBLAS delivers.
- Intel GPUs deliver about a 6th of their peak value (could be because of it's vector based architecture)
- CPU performance is about a 6th of their peak value

Some of this can be mitigated by using different parameters in clBLAS build script, but that does not work well with arrayfire. 

There are a few ways we can deal with this:

1) Write specialized kernels for these hardware in arrayfire

2) See if we can push specialized kernels into clBLAS

3) Check how performance varies based by changing [AutoGemm](https://github.com/clMathLibraries/clBLAS/wiki/AutoGemm) parameters affects performance and implement functionality in clBLAS to tweak paramters at runtime.

**Comment by pavanky** [comment]
Relevant Link from Intel:

Getting performance out of [Intel Graphics](https://software.intel.com/en-us/articles/sgemm-for-intel-processor-graphics). It however uses intel specific extensions.

**Comment by pavanky** [comment]
@arrayfire/core-devel thoughts ?

**Comment by bkloppenborg** [comment]
Assuming clBLAS is willing to accept specializations for non-AMD hardware, I'd say we should push the changes upstream. Perhaps there we could do runtime detection of the architecture and then use custom/optimized kernels?

**Comment by guacamoleo** [comment]
If its just GEMM you're referring to, the AutoGEMM framework already supports specific parameters for Hawaii and Fiji as devices, and someone out in the clBLAS ether can add another specification for an Nvidia GPU. That would be relatively easy.

But its also possible that all AutoGEMM kernels will work poorly on Nvidia hardware for some fundamental architectural reason, in which case someone would need write a new kernel-generation script for writing kernels for Nvidia hardware.

If you're talking about more than just GEMM, you'll have to give more details.

**Comment by pavanky** [comment]
@guacamoleo mostly gemm. From what I understand AutoGEMM can only be tweaked at compile time. SO it may not be feasible for us to ship a general version clBLAS that works decently across multiple architectures.

**Comment by kknox** [comment]
@pavanky 
I think it is feasible to support multiple architectures, @guacamoleo was stating you could.  I think the point he is trying to state, is that the nvidia architecture COULD be so different than AMD, that his generator does not even try to emit kernels 'different' enough to be optimal on Nvidia.  If that's the case, then the generator needs to be updated to be 'smarter' to cover those missing strategies.

However, you never know until you measure.  The first step would be to try the current autogemm on an nvidia device and see what it does.

**Comment by pavanky** [comment]
@kknox We are going to do that as the first step and report back.

However there's also the issue with architectures like Intel that require vectorized operations. I think clBLAS just went away from such implementations.

If we had a single path those types of devices could take, would it be OK send it upstream (which means maintaining additional code) or should we handle it in arrayfire?

**Comment by kknox** [comment]
@pavanky 
> However there's also the issue with architectures like Intel that require vectorized operations.

To make sure we are on the same page, are you saying the intel runtime prefers vector registers such as float4, double2?   That would be a perfect example of needing to add a new strategy to the autogemm heuristics.

We would accept upstream contributions such as this as long as we can verify that performance on our own targets isn't degraded.  We have no problems with accepting uplift to other targets; that's beneficial to our library and our end users.

**Comment by pavanky** [comment]
@kknox 

> To make sure we are on the same page, are you saying the intel runtime prefers vector registers such as float4i, double2?

Yes this is what I mean. 

>  That would be a perfect example of needing to add a new strategy to the autogemm heuristics.

I am guessing this is a bit more involved than tweaking the parameters as discussed [in this issue](https://github.com/clMathLibraries/clBLAS/issues/220).

> We would accept upstream contributions such as this as long as we can verify that performance on our own targets isn't degraded. We have no problems with accepting uplift to other targets; that's beneficial to our library and our end users

:+1: Glad to hear.

**Comment by guacamoleo** [comment]
It would be considerable work to vectorize AutoGEMM; here's an example of a 4x4 micro-tile (each thread computes 16 elements of C matrix):
Each work-group is 16x16 threads, with a micro-tile of 4x4 elements, the work-group computes 64x64 elements of C.
Thread 0,0 of the work-group computes C elements:
    0,0; 0,16; 0,32; 0,48
    16,0; 16,16; 16,32; 16,48
    32,0; 32,16; 32,32; 32,48
    48,0; 48,16; 48,32; 48,48

For vectorization, I assume you'd want to make thread 0,0 compute C elements:
    0-3,0-3

So, there would have to be a new mapping of thread id's to matrix indices for

1. From which global memory index does a thread load input; may be difficult.
2. To which local memory index does a thread store input; may be difficult.
3. Micro-tile madd instructions; not too difficult.
4. Write results to global memory; not too difficult.

**Comment by UniqueFool** [comment]
On a more general note, it may be worth looking at dynamic kernel-tuning, even if just as a temporary workaround, e.g. using something like [CLTune](https://github.com/CNugteren/CLTune)

**Comment by pavanky** [comment]
Closing this since we support CLBlast. Any requests for perf improvements can be done upstream.
