### ISSUE TITLE
Bug in seq -> array operator

### ISSUE THREAD

**Issue by shehzan10** [arrayfire/arrayfire#1377]
Reported here: https://groups.google.com/forum/#!topic/arrayfire-users/Zh8fcKXLNk8

``` cpp
af::array x = af::seq(lbound, ubound);
std::cout << x.dims(0) << std::endl;
```

This prints out a dimension of 32.

``` cpp
af::array x = 2 * af::Pi * af::seq(lbound, ubound);
std::cout << x.dims(0) << std::endl;
```

This prints out a dimension of 31.

**Comment by pavanky** [comment]
This is not a bug.

`af::seq` overloads `*` which changes the `start`, and `end` creating a new range.
