### ISSUE TITLE
CPU async causing crashes

### ISSUE THREAD

**Issue by FilipeMaia** [arrayfire/arrayfire#1378]
See arrayfire/arrayfire-python#75.

**Comment by pavanky** [comment]
@FilipeMaia What is the gcc version being used on the travis instance ?

**Comment by FilipeMaia** [comment]
g++-4.8 amd64 4.8.1-2ubuntu1~12.04

**Comment by pavanky** [comment]
@FilipeMaia We've noticed failures on older versions of gcc. From what I remember `gcc-4.8.2` was causing failures but `gcc-4.8.4` was working fine.

Is there anyway the gcc version on the travis instance can be upgraded?

**Comment by FilipeMaia** [comment]
It might be, I'll see if I can get it.

**Comment by FilipeMaia** [comment]
It could be the gcc version. I couldn't get 4.8.4, but I'm trying 4.9.2 and I have 2 runs and no seg faults yet.

**Comment by pavanky** [comment]
@FilipeMaia Let me know if it breaks, I can reopen the issue. If not we'll close it as a known problem for older versions of gcc.

**Comment by FilipeMaia** [comment]
Pretty sure it's a gcc problem. 10 build/runs and no problems with the new gcc. It would be nice to have cmake spit out a warning for such issues.

**Comment by pavanky** [comment]
@FilipeMaia Thanks for the suggestion.
 
@shehzan10 any chance we can have a warning based on gcc version < 4.8.4 saying that CPU async  fails intermittently and ask the user to turn async off ?

**Comment by shehzan10** [comment]
Yeah we could probably do that.

**Comment by shehzan10** [comment]
I'm not entirely sure if ArrayFire built with Async on GCC >= 4.8.4 will run fine on systems with older GCC. Might need to test this one.
