### ISSUE TITLE
rgb2gray misbehaves for non-float inputs

### ISSUE THREAD

**Issue by grzegorz-gutowski** [arrayfire/arrayfire#1386]
The following code:
`auto rgb = af::array(10, 10, 3, af_dtype::u8);`
`auto gray = af::rgb2gray(rgb);`
gives wrong values and segfaults.
I think that the implementation of `rgb2gray` wrongly uses array `in`, where it should use `input` (which is `in` cast to float) (lines 45-47 in arrayfire/src/api/c/rgb_gray.cpp).

**Comment by pavanky** [comment]
@grzegorz-gutowski Can you check if the PR fixes the problems on your end.

**Comment by pavanky** [comment]
Fixed in hotfix-3.3.2 branch.
