### ISSUE TITLE
GPU-dependent sudden fftConvolve slow down

### ISSUE THREAD

**Issue by maciej-bendkowski** [arrayfire/arrayfire#1388]
Profiling a mean filter implementation, I noticed a sudden slow down in fftConvolve applied to a single channel image with a kernel of size 109x109 (constant(1,kernel_size,kernel_size) / (kernel_size * kernel_size)). Using a Tesla C250 2688MB with compute 2.0 the profiled convolution took about 300 us. After a certain (large but always constant) amount of frames, the same convolution took up to 6000 us! Both the frame resolution and kernel size did not change in time. Switching to GeForce GTX 980 4096MB with compute 5.2, the aforementioned slow down does not occur. Fixing the method to AF_CONV_FREQ did not help. Memory profiling did not reveal any change in memory usage, which might cause the problem. Shrinking the kernel to 17 seems to help - it is the maximal power of 2 plus one which does not imply the slow down. I'm using ArrayFire 3.3.1.

**Comment by pavanky** [comment]
@maciej-bendkowski How are you timing the code ? If you are not calling `af::sync()` explicitly before the end of the timer, you are only noticing the time it takes to **launch** the CUDA kernels, not finish them. 

On older hardware (such as the Tesla C2050), the calls become synchronous after the queue gets to a certain length. This may be the reason you are seeing proper times after queuing up certain number of tasks. On newer hardware this queue is longer meaning you may not be hitting the limit.

**Comment by maciej-bendkowski** [comment]
@pavanky I was not synchronizing the device explicitly - thank you for your suggestion. Synchronization yields a steady ~6300 us, which seems to be in accordance with the previous observations. That being said, is there a way I can look up the current task queue size, so to confirm the issue?

**Comment by pavanky** [comment]
@maciej-bendkowski There could be various limitations to this queue size. I don't recall any documentation for this, but just know it from experience and talking to other CUDA programmers.

You could run the program in the NVIDIA profiler to get better information.

I am closing the issue because the original question has been answered.

**Comment by maciej-bendkowski** [comment]
@pavanky Thank you.
