### ISSUE TITLE
integrated / dedicated GPU crash

### ISSUE THREAD

**Issue by ZacDiggum** [arrayfire/arrayfire#1392]
Hi,
my system has an Intel HD 4600 iGPU and an R390X dGPU. When one screen is connected to the dGPU only or two screens are connected to the iGPU and the dGPU respectively, everything works fine. When one screen is connected to the iGPU only, arrayfire_python crashes with:
`OSError: exception: access violation writing 0x0000000000000000`
and examples from arrayfire's install folder also crash.
I tested other OpenCL based apps ([ViennaCLBench](http://viennaclbench.sourceforge.net/) and [LuxMark](http://www.luxmark.info/)). Both work and use the two GPUs no matter where the screen is plugged.

**Comment by pavanky** [comment]
@ZacDiggum can you test our nogl installer from here:
http://ci.arrayfire.org/userContent/Windows/ArrayFire-no-gl-v3.3.1-f53efc3.exe

**Comment by ZacDiggum** [comment]
Yep, that one works without problems. Thanks, I'll keep that in mind.

**Comment by pavanky** [comment]
Related to https://github.com/arrayfire/arrayfire/issues/1276
