### ISSUE TITLE
Improved error messages and fallback options graphics functions

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#1402]
Right now trying to run graphics example on CUDA GPUs without display attached fail with [errors such as these](https://github.com/arrayfire/arrayfire-python/issues/78).

We should look into providing a warning message about GL sharing being unavailable and that it is using fallback instead.

We can sort of do that in OpenCL backend by setting a flag, but the CUDA backend has no such option.

**Comment by shehzan10** [comment]
We could run [cudaGLGetDevices](http://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__OPENGL.html#group__CUDART__OPENGL_1g3471ecaa5b827c94f2c55ab51fde1751) to check if CUDA-OpenGL interop is available.

**Comment by pavanky** [comment]
@shehzan10 go ahead and do it :+1:
