### ISSUE TITLE
Initialize from an existing memory buffer with the CPU backend without copying

### ISSUE THREAD

**Issue by drufat** [arrayfire/arrayfire#1405]
I would like to use arrayfire with the CPU backend, and I am unsure about how to avoid data copying. Is it possible for arrayfire to use an existing memory buffer without copying its content? Essentially, I am looking to create a "view" over existing preallocated data that will allow me to use the functionality that arrayfire provides without having to copy back and forth between my own representation, and the one that arrayfire adopts.

At the moment, when doing arrayfire computations, I am using something that looks like the code below
```
// read data
auto X = array(dim0, dim1, input_buffer);

// arrayfire computations
auto Y = X + 1;

// write data
Y.host(output_buffer);
```

The above code copies the data both at the input stage, and the output stage, which is a wasted effort, when what I am looking to achieve is something like below: 

```
// create views
auto X = array_view(dim0, dim1, input_buffer);
auto Y = array_view(dim0, dim1, output_buffer);

// arrayfire computations
Y(span, span) = X(span, span) + 1;
```
Eigen already provides this functionality with the [Map Class](https://eigen.tuxfamily.org/dox/classEigen_1_1Map.html).

**Comment by pavanky** [comment]
@drufat 

You can avoid additional copy at the beginning and the end by doing the following in the CPU backend:

```
array X(dim0, dim1, input_buffer, afDevice);
array Y = X + 1;
float *yptr = Y.device<float>(); // Arrayfire does not free the memory if you call this function.
```

**Comment by pavanky** [comment]
This works because `afHost` performs an additional copy, where as `afDevice` just wraps an existing pointer.

**Comment by pavanky** [comment]
As for creating view, it may be more complicated than that. We have an open issue to tackle that issue: https://github.com/arrayfire/arrayfire/issues/482

**Comment by drufat** [comment]
Using `Y.device<float>()` would make it hard to seamlessly switch backends though. When using the CPU backend your function would return a pointer to host memory, whereas when using the GPU backend it would return a pointer to device memory. I was hoping to be able to run the same code both on the CPU and the GPU without making any changes to the source code.

**Comment by pavanky** [comment]
@drufat 
The current behavior is to keep the API consistent.. 

- If you use `A.host<T>()` in any backend, modifying the data pointed to does not modify the original array.

- If you use `A.device<T>()` in any backend, modifying the data pointed to modifies the original array.

If we implemented what you are asking, you still have special behavior for one specific backend. You are still handling CPU backend specially..

**Comment by drufat** [comment]
Thank you for the explanation.
