### ISSUE TITLE
How to compute over a subset of an array

### ISSUE THREAD

**Issue by mchandra** [arrayfire/arrayfire#1421]
Consider the following arrays

```
array a = randu(256, 256, 256);
array b = randu(256, 256, 256);
```

How does one compute `c = a + b`, but only over a select few points, say those stored in a separate `array indices`. Something like:

```
array c = a(indices) + b(indices);
```

The idea is to avoid doing the computation over the whole `256 x 256 x 256` domain, and instead do it only over `indices` which in our case is much lesser than the full domain.

**Comment by shehzan10** [comment]
[indexing documentation](http://arrayfire.org/docs/indexing.htm)?

**Comment by mchandra** [comment]
Ah, thanks! Will try that out.

**Comment by pavanky** [comment]
@mchandra you actually gave the solution yourself :-/ `array c = a(indices) + b(indices);` works.
