### ISSUE TITLE
Poor performance of CPU copy kernel

### ISSUE THREAD

**Issue by FloopCZ** [arrayfire/arrayfire#1437]
The CPU copy kernel does not use BLAS, it is single threaded and it is very slow. Its speed is worse than matrix multiplication (even though the corresponding complexities are O(n^2) vs O(n^3)). Consequently, this behavior results in poor performance of slicing.

Consider the following code.
1) It creates a clone of matrix A using multiplication by Identity matrix.
2) It creates a clone of matrix A using the copy() member function of A.
```c++
#include <arrayfire.h>
#include <iostream>
#include <chrono>

using namespace std::chrono;

int main(int argc, char ** argv)
{
  af::setBackend(AF_BACKEND_CPU);
  af::info();
  high_resolution_clock::time_point t1, t2;
  duration<double> time_span;

  int iters = 1000;
  int n = 512;

  af::array A = af::randu(n, n);
  af::array B = af::randu(n, n);
  af::array I = af::identity(n, n);

  af::sync();
  t1 = high_resolution_clock::now();
  for (int t = 0; t < iters; ++t) {
    B = af::matmul(A, I);
    B.eval();
  }
  af::sync();
  t2 = high_resolution_clock::now();
  time_span = duration_cast<duration<double>>(t2 - t1);
  std::cout << "copy by matmul: " << time_span.count() << std::endl;

  af::sync();
  t1 = high_resolution_clock::now();
  for (int t = 0; t < iters; ++t) {
    B = A.copy();
    B.eval();
  }
  af::sync();
  t2 = high_resolution_clock::now();
  time_span = duration_cast<duration<double>>(t2 - t1);
  std::cout << "copy: " << time_span.count() << std::endl;

  return 0;
}
```
The results are:
```
ArrayFire v3.3.2 (CPU, 64-bit Linux, build f65dd97)
[0] Unknown: Unknown, 16001 MB, Max threads(1) 
copy by matmul: 2.25335
copy: 3.34074
```
Note:
Arrayfire is linked against Intel MKL. CPU is Intel(R) Core(TM) i7-2820QM CPU @ 2.30GHz.

**Comment by shehzan10** [comment]
Not being dismissive about the performance. It does make sense.
What you are seeing is true because:
* MKL is multi-threaded whereas ArrayFire's internal deep copy is sequential. So it is not guaranteed that this will be replicated when compiling with other BLAS libraries (something ArrayFire will continue to support).
* You are using square matrices. I'm not completely sure how this would play out with a tall matrix.

**Comment by shehzan10** [comment]
Can you also benchmark std::memcpy by getting the host pointer from the arrays?

**Comment by FloopCZ** [comment]
Sure. I have appended the following code:
```c++
  af::sync();
  t1 = high_resolution_clock::now();
  for (int t = 0; t < iters; ++t) {
    float * data = A.host<float>();
    delete[] data;
  }
  af::sync();
  t2 = high_resolution_clock::now();
  time_span = duration_cast<duration<double>>(t2 - t1);
  std::cout << "memcopy: " << time_span.count() << std::endl;
```
And now, the results are following:
```
ArrayFire v3.3.2 (CPU, 64-bit Linux, build f65dd97)
[0] Unknown: Unknown, 16001 MB, Max threads(1) 
copy by matmul: 2.56093
copy: 3.41259
memcopy: 0.110628
```

**Comment by shehzan10** [comment]
Oh you are not copying it, it's just getting the pointer. You should do
```
for (int t = 0; t < iters; ++t) {
    float * adata = A.host<float>();
    float * bdata = B.host<float>();
    std::memcpy(bdata, adata, A.bytes());
    delete[] adata;
    delete[] bdata;
  }
```

**Comment by FloopCZ** [comment]
Sorry for that. I have fixed the code and the results are following:
```
ArrayFire v3.3.2 (CPU, 64-bit Linux, build f65dd97)
[0] Unknown: Unknown, 16001 MB, Max threads(1) 
copy by matmul: 2.03225
copy: 3.33551
memcopy: 0.353907
```
I do not actually think you do use the std::memcpy internally. If I analyze the code correctly, you use the following nested loops:
[https://github.com/arrayfire/arrayfire/blob/0caaefd8ae2519aa716811dc87a58ae7fb885cd3/src/backend/cpu/kernel/copy.hpp#L40-85](url)

**Comment by FloopCZ** [comment]
Additionally, I believe that calling A.host() copies the data already:
https://github.com/arrayfire/arrayfire/blob/devel/src/api/c/array.cpp#L29-51
so the results might be significantly biased. The first set of results, where only a single memcpy is performed, might be more accurate and it is also in accordance with Python's NumPy:
```python
#!/usr/bin/env python3
from time import time
import numpy as np

iters = 1000
n = 512

A = np.random.rand(n, n).astype(np.float32)
B = np.random.rand(n, n).astype(np.float32)
I = np.eye(n)

start = time()
for t in range(iters):
    B = A.copy()
print('numpy - copy: {}'.format(time() - start))

start = time()
for t in range(iters):
    B = np.dot(A, I)
print('numpy - dot: {}'.format(time() - start))
```
Results:
```
numpy - copy: 0.081756591796875
numpy - dot: 4.763026714324951
```

**Comment by pavanky** [comment]
@FloopCZ you are right. `A.host` performs a memcpy. `A.device` just returns a pointer.

**Comment by FloopCZ** [comment]
Thank you for the fix, however, it only fixes the case of af::array::copy() function. It does not help with the slicing performance, not even when an entire array is spanned. Consider the following code:
```c++
B(af::span, af::span) = A(af::span, af::span);
```
and a more complicated case where the sliced array is not even linear, but still it could be copied column by column:
```c++
B(af::seq(1, af::end), af::span) = A(af::seq(1, af::end), af::span); 
```
Performance of both these cases is still terribly poor:
```
ArrayFire v3.4.0 (CPU, 64-bit Linux, build 103560d)
[0] Unknown: Unknown, 15880 MB, Max threads(1) 
copy by matmul: 0.673972
copy: 0.0693481
memcpy: 0.0401155
full span copy: 2.305
no first row copy: 2.3097
```
I have implemented a functionality, where both these cases are solved a bit more efficiently. It has to be carefully reviewed, however, the idea is to always copy the largest possible blocks using std::memcpy. Its results are following:
```
ArrayFire v3.4.0 (CPU, 64-bit Linux, build 745e47c)
[0] Unknown: Unknown, 15880 MB, Max threads(1) 
copy by matmul: 0.68641
copy: 0.0674441
memcpy: 0.0380654
full span copy: 0.100187
no first row copy: 0.100138
```
I will provide a pull request for review.

**Comment by pavanky** [comment]
@FloopCZ I know, I was working on that yesterday before I had to sleep.

**Comment by pavanky** [comment]
Fixed in devel. Thanks @FloopCZ
