### ISSUE TITLE
ANN/machine learning specific backends ?

### ISSUE THREAD

**Issue by UniqueFool** [arrayfire/arrayfire#1441]
One of the more common/most useful use cases for arrayfire is undoubtedly machine learning using ANNs, and in fact, even the docs/examples specifically discuss artificial neural networks, and @unbornchikken [confirmed that arrayfire works very well](https://github.com/arrayfire/arrayfire-js/issues/10) for this particular use case.

In addition, there is a separate project implementing a deep learning library on top of arrayfire: https://github.com/jeremysalwen/DeepFire

The point of this proposal/RFC is to grow a library of ANN kernels, implemented as [arrayfire backends](https://github.com/arrayfire/arrayfire/tree/devel/src/backend/opencl/kernel) (e.g. OpenCL), for different purposes so that these can be directly exposed (and used) without scripting space frameworks having to explicitly re-implement the corresponding building blocks from scratch (think perceptron, feed forward network, RNN, LSTM), hopefully to help reduce the marshalling overhead from having to pass data unnecessarily between the scripting language and arrayfire, e.g. referring to the arrayfire-js example at: https://github.com/arrayfire/arrayfire-js/blob/master/examples/es6/machine-learning/ann.js

So this is motivated by seeing an increasing number of github projects with ANNs implemented in OpenCL from scratch, without such building blocks being directly available/reusable in arrayfire, so that even if the underlying building blocks are available in arrayfire, ANNs need to be set up in scripting space, which sacrifices some potential performance gains, because arrayfire isn't necessarily aware  that it is actually simulating an ANN. 

* https://github.com/hughperkins/DeepCL/tree/master/cl 
* https://github.com/martin-steinegger/fann-opencl/tree/master/src/optimized/opencl
* https://github.com/fuziluo/DeepNeuralNets/tree/master/DeepNeuralNets/opencl/kernel

**Comment by pavanky** [comment]
@UniqueFool we want to grow [arrayfire-ml](https://github.com/arrayfire/arrayfire-ml) to be that.

**Comment by UniqueFool** [comment]
ok, thanks for clarifying - I wasn't aware of that obviously. At least the idea wasn't totally novel (or bad) then ;-)
