### ISSUE TITLE
Increase the maximum number of fft caches

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#1443]
100 may be?

**Comment by 9prady9** [comment]
I think, the memory usage will bump up if we do this. Won't it ?

May be we can give a function and let the user play with the plan cache size?

**Comment by pavanky** [comment]
I don't think it will. Can you investigate on nvidia gpu + nvidia-smi ?

**Comment by 9prady9** [comment]
Actually, cuFFT has a API function [`cufftGetSize`](http://docs.nvidia.com/cuda/cufft/#function-cufftgetsize) that i added in our plan cacher to spit out work area sizes for each plan we create for the following test example. You can find the example code output below as well.

```cpp
   for (int i=1; i<16; ++i) {
        af::array a = af::randu(100, i*100);
        af::array c = af::fft2(a);
    }
```

```sh
plan 1 work area size is 80.000000 KB
plan 2 work area size is 160.000000 KB
plan 3 work area size is 240.000000 KB
plan 4 work area size is 320.000000 KB
plan 5 work area size is 400.000000 KB
plan 1 work area size is 480.000000 KB
plan 2 work area size is 560.000000 KB
plan 3 work area size is 640.000000 KB
plan 4 work area size is 720.000000 KB
plan 5 work area size is 800.000000 KB
plan 1 work area size is 880.000000 KB
plan 2 work area size is 960.000000 KB
plan 3 work area size is 1040.000000 KB
plan 4 work area size is 1120.000000 KB
plan 5 work area size is 1200.000000 KB
```
The work area size seems to be increasing with the size of inputs.

**Comment by pavanky** [comment]
Can you check for larger sizes (like 4096 x 4096) ?
