### ISSUE TITLE
array.device is sometimes returning raw pointers

### ISSUE THREAD

**Issue by AEHousman** [arrayfire/arrayfire#1450]
I am mixing CUDA and arrayfire code extensively. I am using CUDA surface objects, so I need to do a copy from the arrayfire device memory to the cuda array memory. Currently, I'm using cudaMemcpy3D(), and I am assuming that the arrayfire data is in packed form, in H x W x C order (height varies first.) I'm using float32 elements here.

Here's the code I use:

```
// release any previous content, make a cuda array, copy from arrayfire array
void CudaArray::to_surface(const af::array &in) 
{
	if (in.dims()[3] != 1)
		throw "CudaArray: attempt to allocate a 4D CUDA surface";

	// free up old CUDA array and allocate new one
	free();
	dims_ = in.dims();
	allocate();

	void *d_srcptr = in.device<float>();	// does an implicit eval()
	af::sync();		// ensure all arrayfire work is complete before we trigger CUDA code

	cudaMemcpy3DParms params = { 0 };
	params.srcPtr = make_cudaPitchedPtr(d_srcptr, dims_[0] * sizeof(float), dims_[0], dims_[1]);	// dims[0] is what varies fastest
	params.dstArray = cuda_array;
	params.kind = cudaMemcpyDeviceToDevice;
	params.extent = make_cudaExtent(dims_[0], dims_[1], dims_[2]);

	checkCuda(cudaMemcpy3D(&params));
	in.unlock();                        // done with d_srcptr
}
```

I use the following to get the data out of the surface back to an array:

```
// make a new arrayfire array, copy data from surface to the array
af::array CudaArray::to_array() 
{
	// ensure CUDA is done before we start copying
	checkCuda(cudaDeviceSynchronize());
	checkCuda(cudaGetLastError());

	af::array out(dims_);

	void *d_dstptr = out.device<float>();

	cudaMemcpy3DParms params = { 0 };
	params.srcArray = cuda_array;
	params.dstPtr = make_cudaPitchedPtr(d_dstptr, dims_[0] * sizeof(float), dims_[0], dims_[1]);
	params.kind = cudaMemcpyDeviceToDevice;
	params.extent = make_cudaExtent(dims_[0], dims_[1], dims_[2]);

	checkCuda(cudaMemcpy3D(&params));
	out.unlock();                       // done with d_dstptr

	return out;
}
```

Everything works fine as long as to_surface() is invoked only on a fresh array, i.e., an array created by `array foo = loadImage("file.png", true); CudaArray baz(foo);   // this works just fine`

However, if I do any kind of arrayfire processing on the array, e.g.,
```
array subwindow(const array &in)
{
    int h = in.dims()[0], w = in.dims()[1];
    array out = in(seq(h/4, h/4+h/2-1), seq(w/4, w/4+w/2-1), span);
    return out;
}

int main()
{
    af::setDevice(0); .. make a window ..

    array in = loadImage("baz.jpg", true);
    in = subwindow(in);          // remove this line and the code works
    CudaArray baz(in);
    win.image(in.to_array());  // shows what appears to be result of a bad stride 
}
```

So the question is, after the call to subwindow, is the memory layout of the array in still tightly packed with floats with no padding and a pitch in bytes equal to the height * 4?

**Comment by pavanky** [comment]
@AEHousman What version of arrayfire are you using?

**Comment by AEHousman** [comment]
Arrayfire 3.3.2 (CUDA, 64-bit windows, build f65dd97)
Platform: CUDA Toolkit 7.5, Driver: CUDA Driver Version: 8000
[0] GeForce GTX 970, 4096 MB, CUDA Compute 5.2

**Comment by AEHousman** [comment]
If you need me to, I can pull together a test case you can run. I thought I'd ask the question first, since if the answer is, no the array data isn't always packed, then that's clearly the issue.

**Comment by AEHousman** [comment]
Okay I found a workaround.

If I do `in = subwindow(in).copy();` things work. Ditto if I change subwindow to:

```
array subwindow(const array &in)
{
    int h = in.dims()[0], w = in.dims()[1];
    array out = in(seq(h/4, h/4+h/2-1), seq(w/4, w/4+w/2-1), span).copy();
    return out;
}
```

What's going on?

**Comment by pavanky** [comment]
@AEHousman Hmm. This shouldn't happen in 3.3.2. We implemented [this feature](https://github.com/arrayfire/arrayfire/issues/1131) for 3.3.2 that should have fixed the issue. But if it is still happening, then it is a bug that we need to fix.

In any case, the best way to handle this (if you don't want additional copies) is to call `getRawPtr(in)`, along with `getOffset(in)` and `getStrides(in)` which you can use inside `cudaMemcpy3D`

**Comment by pavanky** [comment]
`.device()` is supposed to perform the memory copy when it is called on indexed arrays. If you are calling an additional copy, something is broken and needs to be fixed.

Once fixed, you can use `.device<>` if you prefer simplicity, or use the technique mentioned in the previous comment if you prefer performance.

**Comment by AEHousman** [comment]
ooh, thanks! I'll go change my code to use getRawPtr() et. al.

**Comment by pavanky** [comment]
FYI `strides[d]` will tell you the distance between consecutive elements along dimension `d`.

**Comment by AEHousman** [comment]
Hmm, I'm still looking for getRawPtr, getOffset, strides[] -- do I need to include something other than arrayfire.h ?

**Comment by pavanky** [comment]
Ah sorry, include `af/internal.h`.

Since this exposes the internals directly, we only wanted people to use them when they *really* need it and know what they are doing :) 

This is, though very unlikely, the behavior of these functions may change slightly in the future. 

We will document them once we feel like the internal layout is not going to change.

**Comment by AEHousman** [comment]
OK, thanks. Since cudaMemcpy3D only allows you to specify one stride (wtf, Nvidia??) I suspect I'll need to make an explicit copy whenever getStrides() returns something that cudaMemcpy3D can't handle.
