### ISSUE TITLE
Failed to build forge on Ubuntu 15.10

### ISSUE THREAD

**Issue by HaDeP** [arrayfire/arrayfire#1451]
Hi,

I'm trying to build ArrayFire. Cmake worked like a charm but the make command failed with:

root@deadman:/home/deadman/Downloads/arrayfire/build# make
Scanning dependencies of target forge-ext
[  0%] Creating directories for 'forge-ext'
[  0%] Performing download step (git clone) for 'forge-ext'
Cloning into 'forge-ext'...
Switched to a new branch 'master'
Branch master set up to track remote branch master from origin.
[  0%] No patch step for 'forge-ext'
[  0%] Performing update step for 'forge-ext'
/bin/sh: 1: -DCMAKE_SOURCE_DIR:PATH=/home/deadman/Downloads/arrayfire/build/third_party/forge/src/forge-ext: not found
CMakeFiles/forge-ext.dir/build.make:94: recipe for target 'third_party/forge/src/forge-ext-stamp/forge-ext-update' failed
make[2]: **\* [third_party/forge/src/forge-ext-stamp/forge-ext-update] Error 127
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/forge-ext.dir/all' failed
make[1]: **\* [CMakeFiles/forge-ext.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: **\* [all] Error 2

After reading all the issues related to forge-ext with ArrayFire and trying the advices proposed I build it now with -DBUILD-GRAPHICS=OFF but this workaround is rather inconvenient.

Any ideas?

**Comment by 9prady9** [comment]
@HaDeP Attached make output doesn't say anything about why forge failed to build, can you run the command `make VERBOSE=1` and see if the output shows anything about why forge failed to build ?

**Comment by HaDeP** [comment]
Thanks 9prady9 for the comment. Running `make VERBOSE=1` doesn't seem to give me an additional hint why forge failed to build. Everything is doing well until:

[  0%] Performing update step for 'forge-ext'
cd /home/deadman/Downloads/arrayfire/build/third_party/forge/src/forge-ext && -DCMAKE_SOURCE_DIR:PATH=/home/deadman/Downloads/arrayfire/build/third_party/forge/src/forge-ext
/bin/sh: 1: -DCMAKE_SOURCE_DIR:PATH=/home/deadman/Downloads/arrayfire/build/third_party/forge/src/forge-ext: not found
CMakeFiles/forge-ext.dir/build.make:94: recipe for target 'third_party/forge/src/forge-ext-stamp/forge-ext-update' failed
make[2]: *** [third_party/forge/src/forge-ext-stamp/forge-ext-update] Error 127

**Comment by shehzan10** [comment]
I assume you are using the arrayfire devel branch to build from source.

Can you print the output of `cmake -LA | grep -i GL`.

Also, to just build forge you can do `make forge-ext`. That way other ArrayFire targets are not built and mix the output.

**Comment by HaDeP** [comment]
Thanks @shehzan10 for the comment. The output you asked for:
-- Removing /home/deadman/Downloads/arrayfire/test/gloh_nonfree.cpp from ctest
-- Removing /home/deadman/Downloads/arrayfire/test/gloh_nonfree.cpp from ctest
BUILD_SINGLE_TEST_FILE:BOOL=OFF
GLEW_INCLUDE_DIR:PATH=/usr/include
GLEWmxd_LIBRARY:FILEPATH=/usr/lib64/libGLEWmx.so
GLEWmxs_LIBRARY:FILEPATH=/usr/lib64/libGLEWmx.a
OPENGL_INCLUDE_DIR:PATH=/usr/include
OPENGL_gl_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libGL.so
OPENGL_glu_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libGLU.so
OPENGL_xmesa_INCLUDE_DIR:PATH=OPENGL_xmesa_INCLUDE_DIR-NOTFOUND
USE_GLEWmx_STATIC:BOOL=OFF

**Comment by shehzan10** [comment]
Can you also print the one from Forge?
If you want you can run it without the pipe-to-grep and paste the output here or link a gist with the output.

**Comment by HaDeP** [comment]
Sure:

-- The C compiler identification is GNU 5.2.1
-- The CXX compiler identification is GNU 5.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Using Dynamic GLEWmx Lib
-- Downloading GLM headers.
-- GLM...
--   getting https://github.com/g-truc/glm/archive/0.9.7.4.tar.gz
--   validating /home/deadman/Downloads/arrayfire/build/third_party/forge/src/forge-ext-build/third_party/glm-0.9.7.4.tar.gz
CMake Warning at CMakeModules/build_glm.cmake:43 (MESSAGE):
  
  /home/deadman/Downloads/arrayfire/build/third_party/forge/src/forge-ext-build/third_party/glm-0.9.7.4.tar.gz:
  Invalid check sum d41d8cd98f00b204e9800998ecf8427e.  Expected was
  475b0092c3baaf6ac899dc0dcd87f898
Call Stack (most recent call first):
  src/CMakeLists.txt:11 (INCLUDE)


-- Trying wget https://github.com/g-truc/glm/archive/0.9.7.4.tar.gz
--2016-06-06 19:12:10--  https://github.com/g-truc/glm/archive/0.9.7.4.tar.gz
Resolving github.com (github.com)... 192.30.252.121
Connecting to github.com (github.com)|192.30.252.121|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/g-truc/glm/tar.gz/0.9.7.4 [following]
--2016-06-06 19:12:11--  https://codeload.github.com/g-truc/glm/tar.gz/0.9.7.4
Resolving codeload.github.com (codeload.github.com)... 192.30.252.162
Connecting to codeload.github.com (codeload.github.com)|192.30.252.162|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘/home/deadman/Downloads/arrayfire/build/third_party/forge/src/forge-ext-build/third_party/glm-0.9.7.4.tar.gz’

     0K .......... .......... .......... .......... ..........  239K
...    
     350K .......... .......... ...                               230M=2.1s

2016-06-06 19:12:14 (1.55 MB/s) - ‘/home/deadman/Downloads/arrayfire/build/third_party/forge/src/forge-ext-build/third_party/glm-0.9.7.4.tar.gz’ saved [3454678]

-- wget successful
--   extracting /home/deadman/Downloads/arrayfire/build/third_party/forge/src/forge-ext-build/third_party/glm-0.9.7.4.tar.gz
-- Downloading and building Freetype libraries.
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- Could NOT find Fontconfig (missing:  FONTCONFIG_LIBRARY FONTCONFIG_INCLUDE_DIR) 
-- GLFW found!
-- CUDA Toolkit not found, not building CUDA examples.
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
FONTCONFIG_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/deadman/Downloads/arrayfire/build/third_party/forge/src/forge-ext/src
   used as include directory in directory /home/deadman/Downloads/arrayfire/build/third_party/forge/src/forge-ext/src
   used as include directory in directory /home/deadman/Downloads/arrayfire/build/third_party/forge/src/forge-ext/src
   used as include directory in directory /home/deadman/Downloads/arrayfire/build/third_party/forge/src/forge-ext/src
   used as include directory in directory /home/deadman/Downloads/arrayfire/build/third_party/forge/src/forge-ext/src
   used as include directory in directory /home/deadman/Downloads/arrayfire/build/third_party/forge/src/forge-ext/src
   used as include directory in directory /home/deadman/Downloads/arrayfire/build/third_party/forge/src/forge-ext/src
   used as include directory in directory /home/deadman/Downloads/arrayfire/build/third_party/forge/src/forge-ext/src
FONTCONFIG_LIBRARY (ADVANCED)
    linked by target "forge" in directory /home/deadman/Downloads/arrayfire/build/third_party/forge/src/forge-ext/src

-- Configuring incomplete, errors occurred!

**Comment by shehzan10** [comment]
@9prady9 maybe we should have a way to make this error more verbose when used with ArrayFire.

**Comment by HaDeP** [comment]
Well, well ... my fault then ... I had the lib in my system but the path was messed up. Build fontconfig again and now it works as it should.
Thanks to both of you and sorry for the inconvenience.

**Comment by shehzan10** [comment]
Sure, no problem.
We'll leave this issue open to investigate how we can best get the errors to show up better.

**Comment by shehzan10** [comment]
@9prady9 Can you test this and see how we can make a CMake error from Forge show up in ArrayFire. The best was to test this would be to modify the build_forge.cmake file and explicitly set fontconfig to empty. Then see if you can make CMake errors from forge show up in ArrayFire.

**Comment by 9prady9** [comment]
We can add the following checks in forge project's [FindFontConfig](https://github.com/arrayfire/forge/blob/devel/CMakeModules/FindFontConfig.cmake) that will stop cmake processing completely if fontconfig files are not found.

```cmake
IF (DEFINED FONTCONFIG_INCLUDE_DIR-NOTFOUND)
    MESSAGE(FATAL_ERROR "FontConfig header files not found")
ENDIF (DEFINED FONTCONFIG_INCLUDE_DIR-NOTFOUND)

IF (DEFINED FONTCONFIG_LIBRARY-NOTFOUND)
    MESSAGE(FATAL_ERROR "FontConfig library files not found")
ENDIF (DEFINED FONTCONFIG_LIBRARY-NOTFOUND)
```
I verified this patch by forcing FONTCONFIG variable values to empty from forge build files in `build/thirdparty` folder.

As far as ArrayFire project is concerned, forge is still able to find FontConfig and it is not used by ArrayFire, so adding checks at ArrayFire won't help us. By adding the checks mentioned above to forge, we can immediately halt the cmake processing in ArrayFire also.

**Comment by shehzan10** [comment]
@9prady9 Can you paste the CMake Log from ArrayFire when Forge as third party build fails to find FontConfig?

**Comment by 9prady9** [comment]
CMake log would not report any errors and it can't unless we add fontconfig dependency inside ArrayFire. However, by adding aforementioned checks to forge's `FindFontConfig` we can ensure the compilation halts completely with last error message similar to the following.

```bash
[  0%] Built target glb-ext
[  0%] Built target cpu_sort_by_key_uchar
[  0%] Built target bin2cpp
[  0%] Built target cpu_sort_by_key_int
[  1%] Built target cpu_sort_by_key_double
[  1%] Built target cpu_sort_by_key_uint
[  1%] Built target cpu_sort_by_key_uintl
[  1%] Built target cpu_sort_by_key_char
[  1%] Built target cpu_sort_by_key_float
[  1%] Built target cpu_sort_by_key_intl
[  1%] Built target cpu_sort_by_key_ushort
[  1%] Built target cpu_sort_by_key_short
[  1%] Built target cuda_libdevice_headers_bin_target
[  2%] Built target cuda_ptx_headers_bin_target
[  5%] Built target opencl_kernel_headers_bin_target
[  6%] Built target cl2hpp-ext
[  7%] Built target clFFT-ext
[  7%] Built target clBLAS-ext
[  7%] Built target googletest
[  7%] Performing configure step for 'forge-ext'
[  7%] Built target cl2hpp
-- Using Dynamic FreeImage Lib
-- Downloading GLM headers.
-- Using System FreeType2
CMake Error at CMakeModules/FindFontConfig.cmake:49 (MESSAGE):
  FontConfig header files not found
Call Stack (most recent call first):
  src/backend/opengl/CMakeLists.txt:39 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/home/pradeep/gitroot/arrayfire/build/debug/third_party/forge/src/forge-ext-build/CMakeFiles/CMakeOutput.log".
CMakeFiles/forge-ext.dir/build.make:106: recipe for target 'third_party/forge/src/forge-ext-stamp/forge-ext-configure' failed
make[2]: *** [third_party/forge/src/forge-ext-stamp/forge-ext-configure] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/forge-ext.dir/all' failed
make[1]: *** [CMakeFiles/forge-ext.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

SInce it is fatal_error, the whole build process will be halted even if you launch other threads `make -j4`.

**Comment by shehzan10** [comment]
Looks good to me. Can you send a PR?

**Comment by 9prady9** [comment]
@shehzan10 The change related to this has been merged into arrayfire i believe, is that correct ?

**Comment by shehzan10** [comment]
No this hasn't. The PR in question https://github.com/arrayfire/forge/pull/116 will be a part of Forge 0.9.1/1.0 and release with ArrayFire 3.4.2.

**Comment by 9prady9** [comment]
ArrayFire 3.4.2 and Forge v0.9.2 have been released and corresponding checks for FontConfig are  now available in their respective release binaries.
