### ISSUE TITLE
NVidia driver crash on reorder with bad sequences.

### ISSUE THREAD

**Issue by Reithan** [arrayfire/arrayfire#1452]
The code:

```
auto testmat = af::constant(5, 20, 20, 20, 1);
testmat = af::reorder(testmat(af::seq(15,-15), af::seq(15,-15)), 3, 2, 0, 1);
```

Produces a crash on NVidia with OpenCL on driver 368.22 on a GTX 970.

**Comment by umar456** [comment]
That is an invalid sequence but we should not crash. We should be performing some error checking.

**Comment by 9prady9** [comment]
It is probably there on OpenCL backend too. I tried it with CUDA backend. I believe the bug is not specific to a backend.
