### ISSUE TITLE
Arrayfire in FPGA

### ISSUE THREAD

**Issue by helian3699** [arrayfire/arrayfire#1458]
I want to know how to use Arrayfire in FPGA by use SDAccel?
In SDAccel, It just say they can support Arrayfire library but do not introduction how to use Arrayfire.

**Comment by bkloppenborg** [comment]
@helian3699 , could you point us to the specific page on the Xilinx website which gave you this impression? I think [it was this page](http://www.xilinx.com/products/design-tools/software-zone/sdaccel.html#libraries) which might have caused some confusion. Our company, called ArrayFire, writes libraries for Xilinx FPGAs and provides training on SDAccel in North America. Our flagship product, also called ArrayFire, is an accelerated computing library for NVIDIA and OpenCL-supporting GPUs, and CPUs. At present, this library does not support deployment within SDAccel. With that said, we were able to port some of the ArrayFire library's functionality to SDAccel for a [demo of computer vision functions[(http://arrayfire.com/feature-detection-on-xilinx-fpgas-using-opencl/); however, this is not generally supported.

I recommended that we schedule a free technical consultation to discuss your project further and answer any questions you might have. When you're ready to set up a tech consult, simply click on the following link and choose the time that works best for you: [http://meetme.so/arrayfire](http://meetme.so/arrayfire). It will automatically reserve the time in our calendar.
