### ISSUE TITLE
Which version of opencl in arrayfire 3.3.2

### ISSUE THREAD

**Issue by itsnarsi** [arrayfire/arrayfire#1461]
I'm just wondering which version of opencl is supported in the newest version of Arrayfire.

It feels like it is version 1.2. If so are there any future plans for opencl 2.0?

**Comment by pavanky** [comment]
@itsnarsi It is just a matter of API. As far as I can tell there's very little that OpenCL 2.0 offers performance wise that improves upon 1.2. If there are any specific instances where this is true, please let us know so we can add that functionality for the devices that do support it.

Also we plan to have base support 1.2 as long as NVIDIA does not move ahead to a newer OpenCL version.
