### ISSUE TITLE
Build failure on devel branch with both CUDA 7.5 and 8.0 on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by Brainiarc7** [arrayfire/arrayfire#1469]
Hello guys,

I'm running into this build failure caused by this specific error:

```
/usr/bin/ld: /usr/local/lib/liblapack.a(sbdsvdx.f.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/liblapack.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src/backend/opencl/CMakeFiles/afopencl.dir/build.make:7987: recipe for target 'src/backend/opencl/libafopencl.so.3.4.0' failed
make[2]: *** [src/backend/opencl/libafopencl.so.3.4.0] Error 1
CMakeFiles/Makefile2:1478: recipe for target 'src/backend/opencl/CMakeFiles/afopencl.dir/all' failed
make[1]: *** [src/backend/opencl/CMakeFiles/afopencl.dir/all] Error 2

```

At first, it looks like a problem with liblapack, yet the issue persists when I explicitly disable the OpenCL back-end. 

To my understanding, lapack (and lapacke) are called upon when building the OpenCL backends (with the non-free methods selected and enabled in cmake).

Let me know if you need any further information on this issue.

Thanks and regards,

Brainiarc7.

**Comment by pavanky** [comment]
Which branch are you testing?

**Comment by shehzan10** [comment]
> Hello guys,
> 
> I'm running into this build failure caused by this specific error:
> 
> /usr/bin/ld: /usr/local/lib/liblapack.a(sbdsvdx.f.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
> /usr/local/lib/liblapack.a: error adding symbols: Bad value
> collect2: error: ld returned 1 exit status
> src/backend/opencl/CMakeFiles/afopencl.dir/build.make:7987: recipe for target 'src/backend/opencl/libafopencl.so.3.4.0' failed
> make[2]: *** [src/backend/opencl/libafopencl.so.3.4.0] Error 1
> CMakeFiles/Makefile2:1478: recipe for target 'src/backend/opencl/CMakeFiles/afopencl.dir/all' failed
> make[1]: *** [src/backend/opencl/CMakeFiles/afopencl.dir/all] Error 2

It looks it you compiled lapack and lapacke from source. As the error says, you should use -fPIC option when compiling lapack and lapacke if using static libraries. This does not affect shared libs.

> At first, it looks like a problem with liblapack, yet the issue persists when I explicitly disable the OpenCL back-end.

Even the CPU backend uses these libraries, so the error must be from afcpu when OpenCL is turned off, 

> To my understanding, lapack (and lapacke) are called upon when building the OpenCL backends (with the non-free methods selected and enabled in cmake).

Use of lapack and lapacke does not depend on the BUILD_NONFREE option. The are always used unless they are not found on the system, in which case the functionality will be disabled.

**Comment by shehzan10** [comment]
Can you provide any update on this?
Also are there any issues related to CUDA in this as the title suggests? I think the issue is more about user compiled lapack/lapacke.

**Comment by Brainiarc7** [comment]
Hello guys,

As previously stated by @pavanky , this was strictly related to lapacke.
An uninstallation of the previous lapacke (user-compiled) fixed the build issue.
The builds and the tests complete successfully with CUDA 8.0, for now.
