### ISSUE TITLE
Can not run computer vision/ image proceeding examples

### ISSUE THREAD

**Issue by kahrabji08** [arrayfire/arrayfire#1480]
Hi,

Am facing trouples with running any example that contain openning a window. specifically from the computer vision or image processing examples. other examples are working fine.

I keep getting this output when I run harris example for instance:
[0] Unknown: Unknown, 15973 MB, Max threads(1) 
** ArrayFire Harris Corner Detector Demo **

GLX: Forward compatibility requested but GLX_ARB_create_context_profile is unavailableError: Could not Create GLFW Window!
OpenGL context creation failed
Not a valid window
Corners found: 390
Not a valid window
Not a valid window

**Comment by 9prady9** [comment]
@kahrabji08 ArrayFire Graphics requires OpenGL 3.3 at the least. It doesn't seem like your rendering hardware doesn't have that capability. Also, I can't tell what is the CPU/GPU from `af::info` call in the examples. What is the configuration of the system your are trying ArrayFire on ?

Alternatively, if you want to ignore graphics for time being. you do the following to disable graphics temporarily.
- `export AF_DISABLE_GRAPHICS=1` on linux
- set an environment variable `AF_DISABLE_GRAPHICS` = 1 on WIndows.

**Comment by kahrabji08** [comment]
My cpu specifications are:
Processor: Intel® Xeon(R) CPU E5-1620 v3 @ 3.50GHz × 8 
Graphics : Gallium 0.4 on llvmpipe (LLVM 3.4, 256 bits)

also from command line using : lspci
03:00.0 VGA compatible controller: NVIDIA Corporation GM107GL [Quadro K620] (rev a2)

I tried to check my OpenGL version using:  
glxinfo | grep "OpenGL version"
OpenGL version string: 2.1 Mesa 10.1.3

I think I don't have the write openGL version, right? could you help me with how to get it?

**Comment by 9prady9** [comment]
Yes, that is correct, the required OpenGL version is >= 3.3. To get latest OpenGL, I think you need to have latest drivers from NVIDIA.

- is your monitor's port connected to graphics card or to the port on motherboard ?
- Are you using open source drivers for your graphics card ?

can you please paste the output of command `nvidia-smi` here.

**Comment by kahrabji08** [comment]
The monitor is connected to graphics card.

Output is:
nvidia-smi: command not found

**Comment by 9prady9** [comment]
Can you try this `locate nvidia-smi` and then run the tool with full path given by locate command?

**Comment by kahrabji08** [comment]
I tried and it gave no output

**Comment by 9prady9** [comment]
That is odd, even if something is wrong. It should say something like error thrown or no device found etc.
Worst case, it should crash. Can you try some standalone cuda examples and check if you are able to run any CUDA program at all ?

Also, we have CPU backends, can you try running `helloworld_cpu` if that is working fine and what device information is that giving ?

**Comment by kahrabji08** [comment]
Am not sure what is wrong.

The output of helloword_cpu:

ArrayFire v3.3.2 (CPU, 64-bit Linux, build f65dd97)
[0] Unknown: Unknown, 15973 MB, Max threads(1) 
Create a 5-by-3 matrix of random floats on the GPU
A
[5 3 1 1]
    0.5488     0.8579     0.6459 
    0.5928     0.5449     0.3844 
    0.7152     0.8473     0.4376 
    0.8443     0.4237     0.2975 
    0.6028     0.6236     0.8918 

Where can I find the cuda examples?

**Comment by 9prady9** [comment]
they should be there in the same folder as cpu examples just with different suffix `_cuda`.

**Comment by kahrabji08** [comment]
I didn't have the rquired driver previously. thus there were no cuda examples. I installed the drivers from [https://developer.nvidia.com/cuda-downloads](url) and rebuilt the library

The output of nvidia-smi and the output for helloword_cuda is shown below:
![image](https://cloud.githubusercontent.com/assets/16088425/16514134/a696de02-3f9c-11e6-9c2d-bbf93ae11e76.png)

But I still get the same error on harris_cpu example

**Comment by 9prady9** [comment]
Makes sense, if you don't have drivers the cmake will automatically skip building CUDA related examples. The drivers i have on my Arch Linux setup are `367.27` but i guess `352.** `is not that old to have an ancient OpenGL version. You should at least have 3.3. Are you able to run any OpenGL application ? Or is it just ArrayFire graphics that is causing the issue ?

**Comment by kahrabji08** [comment]
Am not familair with openGL. I don't have other applications. I just want the Arrayfire.

**Comment by kahrabji08** [comment]
I tried to search about OpenGL installation. I installed some libraries like GLEW and so. but now am not sure whether I have necessary dependencies or not.

**Comment by 9prady9** [comment]
We use an upstream project known as [forge](https://github.com/arrayfire/forge) for graphics in ArrayFire. You can try the examples in that directly. If you have CUDA SDK installed, then forge has CUDA examples also. Those should help us identify/eliminate ArrayFire from cause of issues.

Note: 
You can find the list of dependencies for building ArrayFire [here](https://github.com/arrayfire/arrayfire/wiki/Build-Instructions-for-Linux). Those should be sufficient to have a functional OpenGL based graphics via ArrayFire.

**Comment by kahrabji08** [comment]
I checked the dependencies. Most of them were already installed, but two were new. Then I tried and it did not work.
Then I started the PC and it worked!!!

Am really thankful.
Regards,
