### ISSUE TITLE
Inconclusive error message when using Sift

### ISSUE THREAD

**Issue by gvgit** [arrayfire/arrayfire#1489]
When using Sift without being compiled into Arrayfire, I got a exception wihtout any hint. I've had to ask around in Arrayfires forum to get a hint to set AF_PRINT_ERRORS. A better exception message would have been great.

**Comment by pavanky** [comment]
What error message are you seeing?

**Comment by gvgit** [comment]
this exception is thrown:

terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception(303): Unknown error
In src/api/cpp/sift.cpp:26

**Comment by pavanky** [comment]
What version of ArrayFire are you using ?

**Comment by 9prady9** [comment]
@gvgit ArrayFire 3.6 is released, please check it out. If this is still an issue on 3.6, feel free to reopen this.
