### ISSUE TITLE
Ninja error: "missing and no known rule to make it"

### ISSUE THREAD

**Issue by schuhschuh** [arrayfire/arrayfire#1497]
Using the Ninja generator (or Code Blocks - Ninja), fails with the following error when trying to build right from the start.
- Ubuntu 14.04 / OS X 10.11
- CMake 3.3.1

```
ninja: error: 'third_party/cl2hpp/package/CL/cl2.hpp', needed by 'src/backend/opencl/CMakeFiles/cl2hpp', missing and no known rule to make it
```

**Comment by schuhschuh** [comment]
Changing
```cmake
ADD_CUSTOM_TARGET(cl2hpp DEPENDS "${prefix}/package/CL/cl2.hpp")
ADD_DEPENDENCIES(cl2hpp cl2hpp-ext)
```
to
```cmake
ADD_CUSTOM_TARGET(cl2hpp DEPENDS cl2hpp-ext)
```
in `CMakeModules/build_cl2hpp.cmake` fixes it.

**Comment by 9prady9** [comment]
@schuhschuh Can you please verify if it's still an issue with newer CMake versions and send in a PR for it.

**Comment by IgorGanapolsky** [comment]
I am still getting this error with NDK r13b and cmake 3.6.4111459:
>Error:error: '../../release/armeabi-v7a/CMakeFiles/feature_tests.c', needed by 'CMakeFiles/andros.dir/__/__/release/armeabi-v7a/CMakeFiles/feature_tests.c.o', missing and no known rule to make it
Error:org.gradle.internal.UncheckedException: Build command failed.
Error:error: '../../release/armeabi-v7a/CMakeFiles/feature_tests.c', needed by 'CMakeFiles/andros.dir/__/__/release/armeabi-v7a/CMakeFiles/feature_tests.c.o', missing and no known rule to make it
Error:Build command failed.
Error:error: '../../release/armeabi-v7a/CMakeFiles/feature_tests.c', needed by 'CMakeFiles/andros.dir/__/__/release/armeabi-v7a/CMakeFiles/feature_tests.c.o', missing and no known rule to make it

**Comment by 9prady9** [comment]
@IgorGanapolsky We don't test ArrayFire source against Android NDK on any of our build systems. We don't claim the support as well for any ArrayFire version > 3.0. If you are trying to use it with NDK, that would entail some code tweaking on your part for the aforementioned reason. The only ARM setup we test ArrayFire on our build servers is on NVIDIA Tegra boards. You are always welcome to raise a feature request for Android support over [here](https://github.com/arrayfire/arrayfire/issues).

**Comment by 9prady9** [comment]
@schuhschuh DEPENDS argument in `add_custom_target` can take normal FILES also according to CMake documentation. I tried ninja with latest devel on my Ubuntu(16.04) and the target cl2hpp built fine without any changes to `build_cl2hpp` file. Closing the issue for now. If you are still facing the issue, please reopen.

**Comment by Varadapavani** [comment]
Hi ,
Iam compiling Android7 but i got following error . Please help me in solving this error.
make: *** No rule to make target `out/target/common/obj/JAVA_LIBRARIES/tcmiface_intermediates/classes.jar.toc', needed by `out/target/common/obj/JAVA_LIBRARIES/okhttp_intermediates/classes-full-debug.jar'.  Stop.
