### ISSUE TITLE
Wrong MKL architecture path when building on Ubuntu 14.04 x86_64

### ISSUE THREAD

**Issue by schuhschuh** [arrayfire/arrayfire#1500]
When trying to build the library on Ubuntu 14.04, the following linker error occurs and the Intel MKL linker path in the argument list points to `-L/opt/intel/mkl/lib/ia32` rather than `-L/opt/intel/mkl/lib/intel64`:

```
/usr/bin/ld: skipping incompatible /opt/intel/mkl/lib/ia32/libmkl_rt.so when searching for -lmkl_rt
/usr/bin/ld: cannot find -lmkl_rt
```

Note that in CMake, the following related variables are set as follows:
```
CBLAS_mkl_rt_INCLUDE = /opt/intel/mkl/include
CBLAS_mkl_rt_LIBRARY = CBLAS_mkl_rt_LIBRARY-NOTFOUND
```
Setting the `CBLAS_mkl_rt_LIBRARY` path manually to `/opt/intel/mkl/lib/intel64/libmkl_rt.so` results in the warning:
```
 CMake Warning at src/backend/cpu/CMakeLists.txt:199 (ADD_LIBRARY):
   Cannot generate a safe linker search path for target afcpu because there is
   a cycle in the constraint graph:

     dir 0 is [/opt/intel/mkl/lib/intel64]
       dir 1 must precede it due to link library [libmkl_rt.so]
     dir 1 is [/opt/intel/mkl/lib/ia32]
       dir 0 must precede it due to link library [libmkl_rt.so]

   Some of these libraries may not be found correctly.
```

- CMake 3.3.1

**Comment by schuhschuh** [comment]
Some debug messages printed in `CMakeModules/FindCBLAS.cmake`:
```
SIZE_OF_VOIDP = 8
INTEL_MKL_ROOT_DIR=
CBLAS_LIB_DIR=
CBLAS_LIB32_DIR=
CBLAS_LIB64_DIR=
```

Had to set `INTEL_MKL_ROOT_DIR` to `/opt/intel/mkl`.

Also the LAPACK path was set to `ia32` subdirectory, but setting `LAPACKE_ROOT_DIR` (spelling mistake in `FindLAPACK.cmake`... should be `LAPACK_ROOT_DIR`) to the same path did not help. It still used the library `/opt/intel/mkl/lib/ia32/libmkl_rt.so`. Needed to set it manually to `intel64`.

**Comment by schuhschuh** [comment]
I then get linker errors regarding missing LAPACKE symbols when building `src/backend/opencl/magma/magma_cpu_lapack.h`. Settings LAPACKE_LIBRARY to /usr/lib/liblapacke.a didn't help. Giving up on the Ubuntu 14 build for now...

**Comment by pavanky** [comment]
How are you compiling with MKL support?

**Comment by schuhschuh** [comment]
I've basically followed the [Build Instructions for Linux](https://github.com/arrayfire/arrayfire/wiki/Build-Instructions-for-Linux). First install all the packages listed with apt-get. Then use CMake 3.3.1 to configure the build tree using the Ninja generator. Here it sets the variables as stated in the issue description which result in the reported linker error "/usr/bin/ld: cannot find -lmkl_rt".

Then I was looking at the CMake variables and noticed that it picked up the wrong paths, changed the advanced variables mentioned above manually and tried again. The MKL linker issue was fixed by changing `ia32` to `intel64`, but the next error was regarding undefined LAPACKE symbols needed for `magma_cpu_lapack.h`. I've looked at the output of

```
> nm /opt/intel/mkl/lib/ia32/libmkl_rt.so | grep LAPACKE
```

and the specific missing symbol names. This shows me that the library contains many LAPACKE functions, but not all of them. I would assume that my MKL library version is not recent enough.

```
> dpkg -S libmkl_rt.so
intel-composer-c++: /opt/intel/composerxe-2011.1.107/mkl/lib/ia32/libmkl_rt.so
intel-composer-c++: /opt/intel/composerxe-2011.1.107/mkl/lib/intel64/libmkl_rt.so
> ll /opt/intel/compilerpro-12.0.1.107
lrwxrwxrwx 1 root root 21 Aug 12  2012 /opt/intel/compilerpro-12.0.1.107 -> composerxe-2011.1.107
```

The MKL version seems to be 12.0.1.107.

As far as I recall, I never installed this library myself. It may be our system administrators that installed it. Is there a particular minimum MKL version required by ArrayFire?

**Comment by schuhschuh** [comment]
BTW Using the `/usr/lib/liblapacke.a` library installed by the `liblapacke-dev` package as stated in the build instructions instead of the MKL library didn't help either. It is missing the same symbol definitions.

The issues here are actually somewhat two related separate issues. The one about ArrayFire finding the wrong MKL library if `INTEL_MKL_ROOT_DIR` is not set, and the other of missing symbols in my LAPACKE library.

**Comment by pavanky** [comment]
@schuhschuh

Using MKL in arrayfire is a little bit weird because it's symbols are different than the others.

 Can you try exporting export `INTEL_MKL_ROOT=/opt/intel/composerxe-2011.1.107/mkl` and configuring cmake freshly ?

**Comment by schuhschuh** [comment]
That does seem to work better. Paths for CBLAS/MKL, LAPACKE, and FFTW all point to the MKL library in this root directory after configure. I do get the following warning, though:
```
 CMake Warning at src/backend/cpu/CMakeLists.txt:199 (ADD_LIBRARY):
   Cannot generate a safe linker search path for target afcpu because there is
   a cycle in the constraint graph:

     dir 0 is [/opt/intel/composerxe-2011.1.107/mkl/lib/intel64]
       dir 1 must precede it due to link library [libmkl_rt.so]
     dir 1 is [/opt/intel/composerxe-2011.1.107/mkl/lib/ia32]
       dir 0 must precede it due to link library [libmkl_rt.so]

   Some of these libraries may not be found correctly.
```

**Comment by pavanky** [comment]
@schuhschuh can you test the build with the following patch applied ?

```
diff --git a/CMakeModules/FindFFTW.cmake b/CMakeModules/FindFFTW.cmake
index 2250589..b8f8fa6 100644
--- a/CMakeModules/FindFFTW.cmake
+++ b/CMakeModules/FindFFTW.cmake
@@ -59,20 +59,26 @@ ELSE()
     SET(CMAKE_FIND_LIBRARY_SUFFIXES ${CMAKE_SHARED_LIBRARY_SUFFIX})
 ENDIF()
 
+IF ("${SIZE_OF_VOIDP}" EQUAL 8)
+  SET(MKL_LIB_DIR_SUFFIX "intel64")
+ELSE()
+  SET(MKL_LIB_DIR_SUFFIX "ia32")
+ENDIF()
+
 IF(FFTW_ROOT)
     #find libs
     FIND_LIBRARY(
         FFTW_LIB
         NAMES "fftw3" "libfftw3-3" "fftw3-3" "mkl_rt"
         PATHS ${FFTW_ROOT}
-        PATH_SUFFIXES "lib" "lib64" "lib/intel64"
+        PATH_SUFFIXES "lib" "lib64" "lib/${MKL_LIB_DIR_SUFFIX}"
         NO_DEFAULT_PATH
         )
     FIND_LIBRARY(
         FFTWF_LIB
         NAMES "fftw3f" "libfftw3f-3" "fftw3f-3" "mkl_rt"
         PATHS ${FFTW_ROOT}
-        PATH_SUFFIXES "lib" "lib64" "lib/intel64"
+        PATH_SUFFIXES "lib" "lib64" "lib/${MKL_LIB_DIR_SUFFIX}"
         NO_DEFAULT_PATH
         )
 
diff --git a/CMakeModules/FindLAPACKE.cmake b/CMakeModules/FindLAPACKE.cmake
index 2ebd8dd..b757972 100644
--- a/CMakeModules/FindLAPACKE.cmake
+++ b/CMakeModules/FindLAPACKE.cmake
@@ -66,13 +66,19 @@ IF(PC_LAPACKE_FOUND)
 
 ELSE(PC_LAPACKE_FOUND)
 
+    IF ("${SIZE_OF_VOIDP}" EQUAL 8)
+        SET(MKL_LIB_DIR_SUFFIX "intel64")
+    ELSE()
+        SET(MKL_LIB_DIR_SUFFIX "ia32")
+    ENDIF()
+
     IF(LAPACKE_ROOT_DIR)
         #find libs
         FIND_LIBRARY(
             LAPACKE_LIB
             NAMES "lapacke" "LAPACKE" "liblapacke" "mkl_rt"
             PATHS ${LAPACKE_ROOT_DIR}
-            PATH_SUFFIXES "lib" "lib64" "lib/ia32" "lib/intel64"
+            PATH_SUFFIXES "lib" "lib64" "lib/${MKL_LIB_DIR_SUFFIX}"
             DOC "LAPACKE Library"
             NO_DEFAULT_PATH
             )
@@ -80,7 +86,7 @@ ELSE(PC_LAPACKE_FOUND)
             LAPACK_LIB
             NAMES "lapack" "LAPACK" "liblapack" "mkl_rt"
             PATHS ${LAPACKE_ROOT_DIR}
-            PATH_SUFFIXES "lib" "lib64" "lib/ia32" "lib/intel64"
+            PATH_SUFFIXES "lib" "lib64" "lib/${MKL_LIB_DIR_SUFFIX}"
             DOC "LAPACK Library"
             NO_DEFAULT_PATH
             )
@@ -99,8 +105,7 @@ ELSE(PC_LAPACKE_FOUND)
             PATHS
             ${PC_LAPACKE_LIBRARY_DIRS}
             ${LIB_INSTALL_DIR}
-            /opt/intel/mkl/lib/ia32
-            /opt/intel/mkl/lib/intel64
+            /opt/intel/mkl/lib/${MKL_LIB_DIR_SUFFIX}
             /usr/lib64
             /usr/lib
             /usr/local/lib64
@@ -115,8 +120,7 @@ ELSE(PC_LAPACKE_FOUND)
             PATHS
             ${PC_LAPACKE_LIBRARY_DIRS}
             ${LIB_INSTALL_DIR}
-            /opt/intel/mkl/lib/ia32
-            /opt/intel/mkl/lib/intel64
+            /opt/intel/mkl/lib/${MKL_LIB_DIR_SUFFIX}
             /usr/lib64
             /usr/lib
             /usr/local/lib64
```

**Comment by schuhschuh** [comment]
@pavanky Sorry, I just noticed your comment/patch! Will try.

**Comment by schuhschuh** [comment]
I can confirm that with this patch and exporting `INTEL_MKL_ROOT=/opt/intel/composerxe-2011.1.107/mkl` before running CMake fixes this issue and ArrayFire/CMake picks up the right paths.
