### ISSUE TITLE
API function to query status of device memory user lock

### ISSUE THREAD

**Issue by schuhschuh** [arrayfire/arrayfire#1502]
Functions that access the device memory of an `array` using the `device()` function have to call `unlock()` to unset the user lock when done. However, when the device memory was actually claimed previously by client code that wants to manage the memory itself, this function should indeed not unset the user lock. A function to query the status of the user lock would be needed, such as:

```c++
void foo(af::array &a)
{
  const bool was_locked = a.islocked(); // not yet existing API function
  void *ptr = a.device<char>(); // will set user lock
  // do something with the device memory
  if (!was_locked) a.unlock(); // need to unset user lock if it wasn't set before
}
```

**Comment by pavanky** [comment]
@schuhschuh unlocking multiple times will not cause an issue. If it is causing an issue, there is a bug somewhere.

Is there any other use case for the islocked function ?

**Comment by schuhschuh** [comment]
I'm not concerned about calling unlock twice/unnecessarily. I am concerned about calling it although the function is not supposed to unlock it yet because the caller itself wants to keep the lock.

**Comment by pavanky** [comment]
@schuhschuh ok that makes sense :+1:

**Comment by schuhschuh** [comment]
Another idea would be to instead of (or besides) adding a new `islocked` function, the user lock could as well be a reference counter. Then each `lock` or implicit `device` lock must be matched with a corresponding `unlock` call.

**Comment by pavanky** [comment]
@schuhschuh using a counter based lock will require the user to be extremely careful about the number of locks and unlocks they are calling. 

I think the better solution is to have different unlock mechanisms for stuff that is locked by `array.lock()` and `array.device()` or by using a method to query the status of the lock.
