### ISSUE TITLE
compiling on ubuntu 14.04

### ISSUE THREAD

**Issue by gdkrmr** [arrayfire/arrayfire#1508]
on ubuntu 14.04 running:
`cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_CUDA=ON -DBUILD_OPENCL=ON`
gives me the following error:

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GLEWmxd_LIBRARY
    linked by target "afcpu" in directory /home/xxx/progs/arrayfire/src/backend/cpu
    linked by target "afcuda" in directory /home/xxx/progs/arrayfire/src/backend/cuda
    linked by target "afopencl" in directory /home/xxx/progs/arrayfire/src/backend/opencl
```

I compiled glew (3.2, cloned from the git repository) myself like described here:
https://github.com/arrayfire/arrayfire/wiki/GLFW-for-ArrayFire

then I tried:
`cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_CUDA=ON -DBUILD_OPENCL=ON  -DGLEWmxd_LIBRARY=/usr/local/lib/libglfw.so`

and the build files seem to be ok, but make gives me an error `GLEW-MX not found`

**Comment by pavanky** [comment]
Those are instructions for GLFW not GLEW. You can install GLEW using `sudo apt install libglew-dev`

**Comment by gdkrmr** [comment]
`libglew-dev` is already installed

**Comment by pavanky** [comment]
Forgot to mention that you need `libglewmx-dev` as well.

The instructions to install all dependencies are here: 
https://github.com/arrayfire/arrayfire/wiki/Build-Instructions-for-Linux

**Comment by gdkrmr** [comment]
i just figured that out myself, it is compiling right now, I wonder how I missed it, because I followed the instructions on that page.
Thanks for the prompt reply!
