### ISSUE TITLE
GLEWmx support dropped from GLEW 2.0

### ISSUE THREAD

**Issue by tdsmith** [arrayfire/arrayfire#1515]
Homebrew noticed that GLEW 2.0 dropped support for GLEW MX, which Arrayfire uses. There's some relevant discussion on the glew repo: https://github.com/nigels-com/glew/issues/38 and here's a relevant commit: https://github.com/nigels-com/glew/commit/a4aa9b2717bb62fbd826b960a914a30303fb07af

Just wanted to make sure you were aware. Thanks!

**Comment by 9prady9** [comment]
@tdsmith Thank you for reporting this. Yes we are aware of this change, the graphics upstream [forge](https://github.com/arrayfire/forge) utilizes GLEW, but we will most probably replace GLEW with [glbinding](https://github.com/cginternals/glbinding) via [forge PR](https://github.com/arrayfire/forge/pull/89). Most of the work is already complete, we are in the process of testing it on multiple platforms. Once [forge changes](https://github.com/arrayfire/forge/issues/84) are completed, we are going to push some changes to ArrayFire graphics stack itself.

**Comment by svenstaro** [comment]
In Arch Linux this problem is currently blocking a rebuild and arrayfire and forge might get dropped due to this. Is there a patch for this?

**Comment by pavanky** [comment]
@svenstaro forge was not ready earlier. We just had enough functionality to use with ArrayFire. 

We are in the process of changing a lot of it's API right now. I'd say dropping forge until it hits 1.0 would be the solution.

**Comment by svenstaro** [comment]
Ok.
