### ISSUE TITLE
Indexing question

### ISSUE THREAD

**Issue by mchandra** [arrayfire/arrayfire#1516]
I have a a 4D array `A(N1, N2, N3, N)`, and a list of indices `index(N, N, N)`
I need to do the following:

```
  for (int a=0; a < N; a++)
  {
      for (int k=0; k < N3; k++)
      {
        for (int j=0; j < N2; j++)
        {  
          for (int i=0; i < N1; i++)
          {
            A(i, j, k, a) = A(i,j,k, index(i,j,k) );
          }
        }
      }
   }
```

In the above, `N1, N2, N3` are spatial indices each equal to 64, whereas `N = 10`, and `0 < index(i,j,k) < N`. How do I convert the above into vectorized arrayfire code?

Thanks

**Comment by pavanky** [comment]
```
af::array flat_index = af::flat(index(af::seq(N1), af::seq(N2), af::seq(N3)));
A = A(af::seq(N1), af::seq(N2), af::seq(N3), flat_index);
```

**Comment by pavanky** [comment]
If `index` is of size `[N1, N2, N3]`, you could simply do the following

```
A = A(af::span, af::span, af::span, af::flat(index))
```

**Comment by pavanky** [comment]
OK I see the problem now,

it should be more like

```
A = A(af::span, af::span, af::span, af::tile(af::flat(index), N)));
```

**Comment by mchandra** [comment]
Thanks! Will try it out.

**Comment by mchandra** [comment]
Can you explain what's going on here:

```
A = A(af::span, af::span, af::span, af::tile(af::flat(index), N)));
```
The first three spans I understand, what's the `tile(flat(index), N)` doing?

Thanks

**Comment by mchandra** [comment]
Btw, would the following also work:

```
A = A(af::tile(af::flat(index), N)));
```

**Comment by 9prady9** [comment]
`tile` repeats given array elements along specific dimension. In this case, it is repeating the flattened array index N times along first(0th) dimension.

Doing just `A= A(tile(flat(index), N)))` will only extract the elements indexed using the indices inside array `index`, it won't retain the corresponding elements along first, second and third dimensions which you are trying to keep in the final array.
