### ISSUE TITLE
Benchmarks / Performance Tracking Against Other Frameworks in Comparable Areas

### ISSUE THREAD

**Issue by sirinath** [arrayfire/arrayfire#1518]
A question any person exploring this project the 1st time would be how well do you beat the competition.

Has this being benchmarked against frameworks like [Yeppp!](http://www.yeppp.info/), [NNPACK](https://github.com/Maratyszcza/NNPACK) in comprairable areas? Can the optimisation you have beat a PeachPy kernel in other areas also. I think you should be able as machines can out do hand tuned code.

Perhaps a area for improvement would be to see proof of optimality using superoptimizer techniques like that is found in: https://github.com/google/souper

**Comment by jramapuram** [comment]
+1 : I would like to add it would be useful to benchmark the BLAS / conv routines against the following as well:

  1) tensorflow
  2) torch / pytorch

**Comment by 9prady9** [comment]
A similar discussion is going on in https://github.com/arrayfire/arrayfire/issues/2796 Closing this as duplicate.
