### ISSUE TITLE
Add option to pull in headers from arrayfire-extras to the build / install process

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#1520]
The headers should be pulled into `include/af/extras/` and can be included in examples / other programs by using `#include <af/extras/foo.h>`

**Comment by 9prady9** [comment]
This doesn't seem relevant given that arrayfire-extras is currently empty. We can have an issue/PR to discuss the corresponding changes once arrayfire-extras repository intent/usage is solidified.
