### ISSUE TITLE
facing build issue while compiling usign make

### ISSUE THREAD

**Issue by streamhsa** [arrayfire/arrayfire#1532]
I  was trying to build OpenCL version . CMake was all good, while giving make ,i m facing the below issue . Can you please help me resolve these.

[ 11%] Linking CXX shared library libafopencl.so
[ 43%] Built target afopencl
[ 53%] Built target af
[ 54%] Built target googletest
[ 54%] Built target backend_unified
[ 55%] Linking CXX executable ycbcr_rgb_opencl
//usr/lib/liblapacke.so.3: undefined reference to `cgejsv_'
//usr/lib/liblapacke.so.3: undefined reference to `zggsvd3_'
//usr/lib/liblapacke.so.3: undefined reference to `cggsvd3_'
//usr/lib/liblapacke.so.3: undefined reference to `sgghd3_'
//usr/lib/liblapacke.so.3: undefined reference to `cggev3_'
//usr/lib/liblapacke.so.3: undefined reference to `zgghd3_'
//usr/lib/liblapacke.so.3: undefined reference to `cgges3_'
//usr/lib/liblapacke.so.3: undefined reference to `cgetrf2_'
//usr/lib/liblapacke.so.3: undefined reference to `zgesvj_'
//usr/lib/liblapacke.so.3: undefined reference to `dgetrf2_'
//usr/lib/liblapacke.so.3: undefined reference to `cggsvp3_'
//usr/lib/liblapacke.so.3: undefined reference to `zggsvp3_'
//usr/lib/liblapacke.so.3: undefined reference to `sggev3_'
//usr/lib/liblapacke.so.3: undefined reference to `zggev3_'
//usr/lib/liblapacke.so.3: undefined reference to `zgesvdx_'
//usr/lib/liblapacke.so.3: undefined reference to `spotrf2_'
//usr/lib/liblapacke.so.3: undefined reference to `sgges3_'
//usr/lib/liblapacke.so.3: undefined reference to `sgetrf2_'
//usr/lib/liblapacke.so.3: undefined reference to `cgesvdx_'
//usr/lib/liblapacke.so.3: undefined reference to `zpotrf2_'
//usr/lib/liblapacke.so.3: undefined reference to `dggsvd3_'
//usr/lib/liblapacke.so.3: undefined reference to `dgghd3_'
//usr/lib/liblapacke.so.3: undefined reference to `dggev3_'
//usr/lib/liblapacke.so.3: undefined reference to `zgejsv_'
//usr/lib/liblapacke.so.3: undefined reference to `sbdsvdx_'
//usr/lib/liblapacke.so.3: undefined reference to `dpotrf2_'
//usr/lib/liblapacke.so.3: undefined reference to `sggsvp3_'
//usr/lib/liblapacke.so.3: undefined reference to `dgesvdx_'
//usr/lib/liblapacke.so.3: undefined reference to `dgges3_'
//usr/lib/liblapacke.so.3: undefined reference to `zgges3_'
//usr/lib/liblapacke.so.3: undefined reference to `dbdsvdx_'
//usr/lib/liblapacke.so.3: undefined reference to `zgetrf2_'
//usr/lib/liblapacke.so.3: undefined reference to `cgesvj_'
//usr/lib/liblapacke.so.3: undefined reference to `sgesvdx_'
//usr/lib/liblapacke.so.3: undefined reference to `sggsvd3_'
//usr/lib/liblapacke.so.3: undefined reference to `dggsvp3_'
//usr/lib/liblapacke.so.3: undefined reference to `cpotrf2_'
//usr/lib/liblapacke.so.3: undefined reference to `cgghd3_'
collect2: error: ld returned 1 exit status
test/CMakeFiles/ycbcr_rgb_opencl.dir/build.make:98: recipe for target 'test/ycbcr_rgb_opencl' failed
make[2]: *** [test/ycbcr_rgb_opencl] Error 1
CMakeFiles/Makefile2:1303: recipe for target 'test/CMakeFiles/ycbcr_rgb_opencl.dir/all' failed
make[1]: *** [test/CMakeFiles/ycbcr_rgb_opencl.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by pavanky** [comment]
It looks like you do not have a blas library on your machine. Can you try installing openblas or atlas and see if it resolves the issue?

**Comment by streamhsa** [comment]
thank you pavan, after installing openblas and atlas its building fine.

but while testing 2 tests are failed. (manual_memory_test_opencl , backend_unified)
here providing the specific test results.

root@HY-IN-SC01-958:/opt/arrayfire/build1# cd test/
root@HY-IN-SC01-958:/opt/arrayfire/build1/test# ./manual_memory_test_opencl 
Running main() from gtest_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from Memory
[ RUN      ] Memory.recover
/opt/arrayfire/test/manual_memory_test.cpp:56: Failure
Value of: AF_ERR_NO_MEM
  Actual: 101
Expected: ae.err()
Which is: 998
[  FAILED  ] Memory.recover (241 ms)
[----------] 1 test from Memory (241 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (241 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] Memory.recover

 1 FAILED TEST


root@HY-IN-SC01-958:/opt/arrayfire/build1/test# ./backend_unified 
Running main() from gtest_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from BACKEND_TEST
[ RUN      ] BACKEND_TEST.Basic
/opt/arrayfire/test/backend.cpp:61: Failure
Expected: (backends) != (0), actual: 0 vs 0
[  FAILED  ] BACKEND_TEST.Basic (0 ms)
[----------] 1 test from BACKEND_TEST (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (0 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] BACKEND_TEST.Basic

 1 FAILED TEST

Can you please help me resolve these.

**Comment by shehzan10** [comment]
The manual_memory test is designed to fail by allocating too much memory.

The backend_unified test requires that the AF_PATH/lib/ directory is added to your LD_LIBRARY_PATH.
For this you can do `make install` and then add install_path/lib to LD_LIBRARY_PATH.

**Comment by shehzan10** [comment]
Can you provide an update if the `backend_unified` test has passed? If it has, I think this issue can be closed.

**Comment by streamhsa** [comment]
yes it passed. thank you ..you can close this
