### ISSUE TITLE
Unsupported gpu architecture

### ISSUE THREAD

**Issue by abhijithch** [arrayfire/arrayfire#1535]
While building arrayfire from source, with the given options for `cmake` I am getting the following error, 
```
[ 17%] Building NVCC (Device) object src/backend/cuda/CMakeFiles/afcuda.dir//./afcuda_generated_all.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_60'
CMake Error at afcuda_generated_all.cu.o.cmake:206 (message):
  Error generating
  /home/julia/JC/arrayfire/build/src/backend/cuda/CMakeFiles/afcuda.dir//./afcuda_generated_all.cu.o
```

Is there a way to identify and mention the architecture type? I tried with the option, `-DCUDA_GENERATION=Auto` but this did not help.

**Comment by shehzan10** [comment]
Are you using CUDA 7.5 or CUDA 8.0RC?
CUDA 7.5 does not support any 6x computes as those were released quite recently. You will have to compile with CUDA 8.0RC.

**Comment by UniqueFool** [comment]
is there any way to extend the cmake heuristics to detect this requirement and notify the user accordingly ?

**Comment by pavanky** [comment]
Our CMake file for our CUDA backend is too complicated already. The effort needed to maintain this is too high compared to the amount of times this problem occurs.

**Comment by UniqueFool** [comment]
ok, thanks for the info - just in case, the OpenCV project apparently ran into a similar cuda/cmake issue, and they're discussing a thrust related workaround: https://github.com/opencv/opencv/issues/6632 

http://answers.opencv.org/question/95991/opencv-30-build-error-cuda-80/

(for the record, I obviously don't know if arrayfire is currently using thrust or planning to anytime soon)

**Comment by pavanky** [comment]
@UniqueFool I have been told by @shehzan10 that it is a fairly simple thing to add to CMake. Sorry to jump the gun.

**Comment by abhijithch** [comment]
Thanks, updating CUDA did fix my problem, though temporarily. I am afraid I have got into the Ubuntu login loop problem after now.
