### ISSUE TITLE
MX support likely to be omitted from future releases of GLEW

### ISSUE THREAD

**Issue by drufat** [arrayfire/arrayfire#1540]
According to [this](https://github.com/nigels-com/glew/issues/38#issuecomment-170005710), MX support is going to be removed from GLEW. Currently it does not seem possible to build arrayfire without MX support. Would it be possible to build arrayfire on systems where libGLEWmx.so is missing? For example, the latest version of ArchLinux provides no libGLEWmx.so file.

**Comment by pavanky** [comment]
We are moving away from glew for future releases.

Refer to https://github.com/arrayfire/arrayfire/issues/1515 for more info.
