### ISSUE TITLE
Create array from existing cuda device pointer

### ISSUE THREAD

**Issue by ben310773** [arrayfire/arrayfire#1541]
I tried a simple code and I received a segmentation fault when I ran it. 
--------------------------------------------------------------------
```
float *d_x;
cudaMalloc((void **)&dx, 1024*2048*sizeof(float));
array af_ref(1024, 2048, d_x, afDevice);
```
----------------------------------------------------------------------

Is there a bug in the this array constructor? Or is it something I have done wrong. 
My arrayfire version is 3.3.2 on (CUDA 64-bit Linux) CUDA Toolkit 7.5.

**Comment by FilipeMaia** [comment]
Are you sure the cudaMalloc succeeded?

**Comment by ben310773** [comment]
Yes it succeed. I left out the checkCudaErrors( ) wrapper when I post the msg. I am more inclined to think arrayfire's array constructor of type afDevice failed. Have you tried it in your codes?

**Comment by pavanky** [comment]
Are you sure it is happening at the constructor?

**Comment by ben310773** [comment]
The type afHost works when I allocate memory on the host. But afDevice failed when memory was allocated using cudaMalloc. Nothing is wrong with the cudaMalloc function. The rest of the portions of my code works well. Do you mind elaborate on what you think can go wrong? I mean how to check that it is not happening at the constructor? The documentation doesn't seem to imply the array constructor returns an error code.  I even purposely commented away all sections of  my code and placed the cudaMalloc( ) and the array afDevice constructor at the very front of my code. It still give me seg fault.

**Comment by pavanky** [comment]
Do you by chance have multiple cuda gpus on your machine?

**Comment by ben310773** [comment]
No. I only have a single GPU card in my computer. Quadro 2000.

**Comment by pavanky** [comment]
Can you also replace your cudaMalloc with af::alloc<float>(1024 * 2048); and see if that works?

**Comment by pavanky** [comment]
I mean af::alloc<float>(1024 * 2048)

**Comment by pavanky** [comment]
Damn the mobile version of website is omitting templates. Try this 

af::alloc<float>(1024 * 2048)

**Comment by ben310773** [comment]
I just tried and it failed too. seg fault

**Comment by umar456** [comment]
af::alloc\<float\>(1024*2048)

**Comment by ben310773** [comment]
I mean the af::alloc() didn't return any error but once I called the array afDevice constructor, it failed.

**Comment by pavanky** [comment]
@ben310773 can you post the entire code snippet instead of just the constructor ?

**Comment by ben310773** [comment]
Due to security reasons, my working computer is separate from my internet computer. I have created a small program just to test the array constructor. The entire code is as below:

#include <cuda,h>
#include <arrayfire.h>
using namespace af;
int main(int argc, char **argv){
    cudaDeviceReset();
    float *d_x = NULL;
    d_x = (float *)af::alloc<float>(1024*2048);
    if(d_x == NULL) printf("Error\n");
    array af(1024, 2048, d_x, afDevice);

    return 0;
}

That's the above codes I have used to test the array afDevice constructor.

**Comment by ben310773** [comment]
I don't know why the include header cuda.h and arrayfire.h didn't appear above.

**Comment by ben310773** [comment]
One typo error: 1024 * 2048 in the af::alloc()

**Comment by umar456** [comment]
You have to add backslash before the `<' for it to show up. Also try to use the template version of af::alloc

**Comment by ben310773** [comment]
Ah I see. I did used the template version but it didn't show up over here.

**Comment by ben310773** [comment]
So nobody encounter this fault except me? Did anyone tried it recently and it works?

**Comment by pavanky** [comment]
@ben310773 I have tried this and have not been able to reproduce it on multiple machines. I am not sure why it is failing only your machine..

Can you display the output of `af::info` ?

**Comment by ben310773** [comment]
af::info gives:
ArrayFire v3.3.2 (OpenCL, 64-bit Linux, build f65dd97) 
[0] NVIDIA : Quadro 2000, 961MB

I am using CUDA, may I ask why info specifies OpenCL?

**Comment by pavanky** [comment]
@ben310773 if you are using the unified backend, arrayfire tries to use the following backends in order

- CUDA
- OpenCL
- CPU

If it is going to OpenCL backend, it usually means it can not find `libnvvm`. 

You'll need to `export LD_LIBRARY_PATH` to include `/path/to/cuda/nvvm/lib64`

This should allow you to use CUDA backend

**Comment by ben310773** [comment]
Hi Pavanky,
I think it works now. I realize the backend falls onto OpenCL. I re-read the installation procedure and ensure the LD_LIBRARY_PATH are specified so that CUDA backend can be used. Thanks very much for the af::info tip.
