### ISSUE TITLE
Is arrayfire building and testing applicable for RHEL 7.2?

### ISSUE THREAD

**Issue by streamhsa** [arrayfire/arrayfire#1552]
Hi,
I need some info about support of this app on RHEL 7.2. Is it supported?
This app needs cmake >2.8.12 and RHEL 7.2 has latest package 2.8.11 only on default OS or yum install.

Building cmake 2.8.12 is failing due to dependency issue. I have followed page : http://www.shisaihua.com/install-cmake-2-8-12-on-el7/

Is anyone is facing such issue or have any solution? If any handy page which i can follow to build on RHEL 7.2 is nice.

Thanks

**Comment by pavanky** [comment]
We build our installers on Centos 6.x. We successfully built CMake 2.8 on that machine without any issues. We haven't explicitly tested on 7.x.

That said, if you have root privileges on the redhat machine, can you try enabling the EPEL repos as mentioned here: https://fedoraproject.org/wiki/EPEL

After this you can install cmake 3.x using `yum install cmake3`.

**Comment by WilliamTambellini** [comment]
I m mainly working on CentOS 7.2 and if I remember right cmake 2.8 is too old to build AF examples so I m using cmake 3.

**Comment by streamhsa** [comment]
Thanks. Repos are updated already. I have just installed cmake3 and proceeded. 
Problem is that RHEL does not have all required files for the Arrayfire which we can get easily for Ubuntu.
Can someone help any RHEL files corresponding to install libglew-dev ,libglewmx-dev ,libglfw3-dev using YUM.

**Comment by pavanky** [comment]
@streamhsa if you are not going to use graphics, you do not need any of them. Just pass `-DBUILD_GRAPHICS=OFF` to your cmake config.

**Comment by shehzan10** [comment]
@streamhsa If you wish to build with ArrayFire 3.4.0, then you do not need `libglew-dev` and `libglewmx-dev` anymore, only `libglfw3-dev`.
For yum, the package is `glfw`. Please verify the version of the package to be >= 3.1 (3.0.4 will also work, but there are some bugfixes in 3.1 that fix issues we have discovered). If this package is not available, then we have provided the [build instruction for GLFW](https://github.com/arrayfire/arrayfire/wiki/GLFW-for-ArrayFire).
You can also run the pre-built installers from our website if you so wish.
Let us know if you need any further assistance.

**Comment by shehzan10** [comment]
@streamhsa is this issue resolved?

**Comment by shehzan10** [comment]
Closing this issue until there is further information.
