### ISSUE TITLE
OpenCL test failures with pocl

### ISSUE THREAD

**Issue by ghisvail** [arrayfire/arrayfire#1553]
I compiled the latest tip of ArrayFire in `devel` and tested it against the most recent release of `pocl` available in Debian testing.

Backend details:
```
Running Default Backend...
ArrayFire v3.4.0 (OpenCL, 64-bit Linux, build 73ed507)
[0] POCL    : pthread-Intel(R) Core(TM) i5-4300M CPU @ 2.60GH, 9941 MB
Active Backend Enum = AF_BACKEND_OPENCL
```

Summary of `ctest --output-on-failure --force-new-ctest-process  -R opencl -E "large|dense"`
```
Total Test time (real) = 280.73 sec

The following tests FAILED:
	  1 - Test_approx1_opencl (Failed)
	  2 - Test_approx2_opencl (Failed)
	  3 - Test_array_opencl (Failed)
	  4 - Test_assign_opencl (Failed)
	  5 - Test_backend_opencl (Failed)
	  7 - Test_basic_c_opencl (Failed)
	  9 - Test_binary_opencl (Failed)
	 12 - Test_compare_opencl (Failed)
	 13 - Test_complex_opencl (Failed)
	 15 - Test_convolve_opencl (Failed)
	 18 - Test_diagonal_opencl (Failed)
	 21 - Test_dog_opencl (Failed)
	 23 - Test_empty_opencl (Failed)
	 25 - Test_fft_opencl (Failed)
	 27 - Test_fft_real_opencl (Failed)
	 28 - Test_fftconvolve_opencl (Failed)
	 29 - Test_flat_opencl (Failed)
	 30 - Test_flip_opencl (Failed)
	 32 - Test_gen_assign_opencl (Failed)
	 33 - Test_gen_index_opencl (Failed)
	 34 - Test_getting_started_opencl (Failed)
	 35 - Test_gfor_opencl (Failed)
	 37 - Test_gray_rgb_opencl (Failed)
	 40 - Test_histogram_opencl (Failed)
	 41 - Test_homography_opencl (Failed)
	 43 - Test_iir_opencl (Failed)
	 44 - Test_imageio_opencl (Failed)
	 45 - Test_index_opencl (Failed)
	 46 - Test_info_opencl (Failed)
	 47 - Test_internal_opencl (Failed)
	 50 - Test_ireduce_opencl (Failed)
	 51 - Test_jit_opencl (Failed)
	 52 - Test_join_opencl (Failed)
	 56 - Test_math_opencl (Failed)
	 57 - Test_matrix_manipulation_opencl (Failed)
	 61 - Test_median_opencl (Failed)
	 62 - Test_memory_opencl (Failed)
	 64 - Test_missing_opencl (Failed)
	 67 - Test_morph_opencl (Failed)
	 72 - Test_random_opencl (Failed)
	 75 - Test_reduce_opencl (Failed)
	 78 - Test_replace_opencl (Failed)
	 79 - Test_resize_opencl (Failed)
	 82 - Test_sat_opencl (Failed)
	 84 - Test_select_opencl (Failed)
	 93 - Test_susan_opencl (Failed)
	 99 - Test_transpose_opencl (Failed)
	100 - Test_transpose_inplace_opencl (Failed)
	101 - Test_triangle_opencl (Failed)
	104 - Test_where_opencl (Failed)
	105 - Test_wrap_opencl (Failed)
	106 - Test_write_opencl (Failed)
```

Most errors are of the form:
```
error: Invalid cast (Producer: 'LLVM3.8.0' Reader: 'LLVM 3.8.0')
```

Besides this one:
```
      Start  44: Test_imageio_opencl
42/99 Test  #44: Test_imageio_opencl .................***Failed    0.73 sec
Running main() from gtest_main.cc
[==========] Running 23 tests from 4 test cases.
[----------] Global test environment set-up.
[----------] 6 tests from ImageIO/0, where TypeParam = float
[ RUN      ] ImageIO/0.ColorSmall
[       OK ] ImageIO/0.ColorSmall (28 ms)
[ RUN      ] ImageIO/0.GraySmall
[       OK ] ImageIO/0.GraySmall (0 ms)
[ RUN      ] ImageIO/0.GraySeq
[       OK ] ImageIO/0.GraySeq (0 ms)
[ RUN      ] ImageIO/0.ColorSeq
[       OK ] ImageIO/0.ColorSeq (93 ms)
[ RUN      ] ImageIO/0.InvalidArgsMissingFile
FreeImage Error Handler: FreeImage_Load: failed to open file /home/ghislain/local/src/arrayfire/test/data/imageio/nofile.png
```

Detailed log:
[af-opencl-tests.log.zip](https://github.com/arrayfire/arrayfire/files/437540/af-opencl-tests.log.zip)

**Comment by shehzan10** [comment]
```
FreeImage Error Handler: FreeImage_Load: failed to open file /home/ghislain/local/src/arrayfire/test/data/imageio/nofile.png
```

Actually this is not a failure. It's just printing the statement out from the error log. The test itself is called "InvalidArgsMissingFile", so we are checking if the error is being correctly set.

Of course, eventually this file too fails with the same LLVM error according to the log.

**Comment by ghisvail** [comment]
Could [this](https://github.com/pocl/pocl/issues/360) be related?

**Comment by pavanky** [comment]
@ghisvail can you confirm what the latest release of pocl is in debian ?

**Comment by ghisvail** [comment]
0.13

**Comment by pavanky** [comment]
@ghisvail I tested the devel branch with 0.13. The problem seems to occur somewhere in in the random number generation code. 

I tried replacing `randu(a, b)` with `cpu_randu<float>(af::dim4(a, b))` in a couple of tests and it looks like the tests run fine.

Considering that we are rewriting random number generation, we'll again test it after https://github.com/arrayfire/arrayfire/pull/1551 is merged.

@shehzan10 
If possible we should change all tests to use the test specific function `cpu_randu<float>`

**Comment by shehzan10** [comment]
I think it is a possibility, but the performance would probably take a significant hit.
Additionally, the random test would still need to run those functions, so that would still fail.

Let's take a call after the random number generation is merged.

**Comment by pavanky** [comment]
@ghisvail after I read through the linked issue and removing the cache (as suggested in the last comment) fixed the issue for 1 run. But subsequent runs cause the same issue. Deleting the cache again fixes it for one run. It looks like there's some kind of a bug in pocl's caching mechanism.

**Comment by ghisvail** [comment]
Thanks guys for investigating this. Seems that the problem is located upstream, either in `pocl` or `llvm`. Still worth keeping this issue open anyway. I'll try to keep track with the progress upstream.

**Comment by pavanky** [comment]
@ghisvail #1551 fixed the issue for arrayfire. The problem still exists upstream pocl and may arise in other situations.

I am closing the issue. Let's open a new issue if you any specific failures.
