### ISSUE TITLE
Iterative solvers

### ISSUE THREAD

**Issue by kaatish** [arrayfire/arrayfire#1568]
- [ ] Conjugate Gradient
- [ ] Bi Conjugate Gradient
- [ ] Bi Conjugate Gradient Stabilized
- [ ] Generalized Minimal Residual Method

**Comment by ZacDiggum** [comment]
Hi @kaatish, could you give an ETA for the solvers? I noticed [clSPARSE](https://github.com/clMathLibraries/clSPARSE#clsparse-features) already features CG and BiCGStab.

**Comment by shehzan10** [comment]
As the milestone suggests, we expect these to be a part of the v3.5 release.

We have also added an [example for a CG solver](https://github.com/arrayfire/arrayfire/blob/hotfix-3.4.1/examples/benchmarks/cg.cpp) using both sparse and dense arrays in the hotfixes branch which will be included in the v3.4.1 release.

**Comment by ZacDiggum** [comment]
Thanks for the info...

**Comment by Chronum94** [comment]
Was this moved to v3.6 because of the amount of work required or because of low demand in the community? Because these would be fabulous to have within the lib itself. I imagine a significant number of people currently use self-made implementations using standard matmuls.

**Comment by 9prady9** [comment]
@Chronum94 As always, we love to add new functionality. However, sometimes we are limited by the amount of bandwidth we have to work on a specific feature. We can't give a definitive ETA on this feature but we shall try to work on it as soon as we can.

We also welcome community contributions and can provide assistance to anyone willing to add the feature.
