### ISSUE TITLE
Create a function to return allocated bytes

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#1607]
Currently there is no real way to query the number of bytes being held by the original array after doing something like this:

```
array a = randu(5,5);
array b = a(af::seq(1,3), af::seq(1,3));
//b.allocated() ?
```

**Comment by pavanky** [comment]
See this issue for more information: https://groups.google.com/forum/#!msg/arrayfire-users/ckNHX69iC_4/-dZB6muMAAAJ

**Comment by shehzan10** [comment]
Should this return the total bytes of `a` or the actual bytes used by `b`?

**Comment by pavanky** [comment]
The former.
