### ISSUE TITLE
Feature request: support for sparse matrix/vector addition and subtraction

### ISSUE THREAD

**Issue by villekf** [arrayfire/arrayfire#1618]
Could it be possible to add support for the addition/subtraction of sparse matrix/vector to dense matrix/vector?

**Comment by WilliamTambellini** [comment]
+1

**Comment by shehzan10** [comment]
This feature can use
CPU (MKL): [mkl_sparse_?_add](https://software.intel.com/en-us/node/590132)
CUDA: [cusparse<T>csrgeam](http://docs.nvidia.com/cuda/cusparse/#cusparse-lt-t-gt-csrgeam)

For CPU fallback and OpenCL, code will have to be written from source.

**Comment by pavanky** [comment]
This has been implemented in https://github.com/arrayfire/arrayfire/pull/1696
