### ISSUE TITLE
Bug in af::sparse(const dim_t nRows, const dim_t nCols, const dim_t nNZ, const void *const values, ...)

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#1622]
Source:
const float v[] = { 1,2 };
const int rs[] = { 1,3 };
const int cs[] = { 0,0 };
af::array s = af::sparse(4,1,2,(const void*)&v[0],&rs[0],&cs[0], f32);
af_print(s);

Output:
s
Storage Format : AF_STORAGE_CSR
[4 1 1 1]
s: Values
[2 1 1 1]
    1.0000 
    2.0000 

s: RowIdx
[5 1 1 1]
         1 
         3 
-577531912 
     32767 
1065353216 

s: ColIdx
[2 1 1 1]
         0 
         0 

See that RowIdx is buggyly sized 5.

Compiler: gcc6, centos7, repeated whatever the backend (cuda7.5, opencl, even afcpu).

**Comment by WilliamTambellini** [comment]
Reproduced in both debug and release.
does make AF crash if I try to use the sparse matrix in a matmul:
    af::array dense = af::constant(1, 1,4);
    af_print(dense);
    af_print(af::matmul(s,dense));

**Comment by shehzan10** [comment]
The reason for that is that in CSR format the row index vector is supposed to be of size `nRows + 1` but you are passing only 2 elements.

In CSR format:
values is of size nNZ
rowIdx is of size rows + 1
colIdx is of size nNZ.

The format for which you are actually passing values is `AF_STORAGE_COO`.

Sources: [Wikipedia](https://en.wikipedia.org/wiki/Sparse_matrix#Compressed_sparse_row_.28CSR.2C_CRS_or_Yale_format.29), [MKL - See Three Array Variation of CSR Format](https://software.intel.com/en-us/node/599835)

**Comment by WilliamTambellini** [comment]
ok thanks.
COO to CSR:
https://github.com/scipy/scipy/blob/3b36a57/scipy/sparse/sparsetools/coo.h#L34
