### ISSUE TITLE
ArrayFire v3.4.0

### ISSUE THREAD

**Issue by DOGMAFIlms** [arrayfire/arrayfire#1624]
Hello,

I just tried too install ArrayFire v3.4.0 on a Mac Pro 6,1 with OS Sierra but I get an installation failed message, any advise please?.

Thanks.

**Comment by shehzan10** [comment]
OS X installer can fail due to failure of `brew` commands.
Our [wiki](https://github.com/arrayfire/arrayfire/wiki/Fixing-Common-OS-X-Installer-Failures) has steps to check and correct these errors.
If the examples run fine as shown in the wiki, then the installer worked fine and there should be no problems in running ArrayFire.

**Comment by shehzan10** [comment]
@DOGMAFIlms can you please let us know if the wiki resolved the issues?

**Comment by DOGMAFIlms** [comment]
Hello there, 


I just gave up, trying to install I had to many errors. 

Javier Quito Deidan
Dogma Films Ec.
Dogmafilmsec@icloud.com
Cell.:0979241745

**Comment by shehzan10** [comment]
I think you can give the v3.4.1 installers a try. We have made a few fixes to that and it should be much better and without errors.

**Comment by DOGMAFIlms** [comment]
Hello,



I just tried and I get this error: The operation couldn’t be completed. (com.apple.installer.pagecontroller error -1.)




Javier Quito Deidan
DOGMA Films
dogmafilmsec@icloud.com
Cel. # 0979241745

**Comment by shehzan10** [comment]
Looks like the download did not go through correctly. You can try re-downloading it. You can confirm this by checking the MD5 sum for the installer which is:
`md5 ArrayFire-v3.4.1_OSX.pkg` : **97fccd3e1d2350a99d87785b96f2583e**

**Comment by shehzan10** [comment]
Issue has been resolved.
