### ISSUE TITLE
Can't use `#include <regex>` with ArrayFire

### ISSUE THREAD

**Issue by serialhex** [arrayfire/arrayfire#1644]
I'm not sure if this is a problem with ArrayFire itself or Windows, but I thought I'd get better help faster if I asked here first.  Here is a gist of some example code, and the error I get when I try to compile it.  It doesn't make sense as `std::regex_search` is in a *totally* different namespace from `af::` and I'm not sure why it's barfing.  I know in the example code I don't use *anything* from ArrayFire (besides including the header) but it still dies.

Any help is greatly appreciated!

The aforementioned gist: https://gist.github.com/serialhex/fa874a8122fa6401acbbec73ba65c1e2

**Comment by serialhex** [comment]
Sorry, derpy me more used to Common Lisp development where I don't have to have separate headers and implementation files.  My bad!!

**Comment by umar456** [comment]
Those errors are related to how visual studio defines min and max as macros. See this comment for a solution.
https://github.com/arrayfire/arrayfire/issues/235#issuecomment-67437768
