### ISSUE TITLE
BUG in CUDA / OpenCL JIT

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#1646]
Code to reproduce:
```
af::array test1 = af::randn(10, 10);
af::array test2 = af::randn(10);
af::array test3 = af::randn(10);

for (int i = 0; i < 1000; i++) {
    test3 += af::sum(test1, 1);
    test2 += test3;
}
```

This happens when JIT tries to compile a kernel with too many inputs. The force evaluation criteria should be more strict.

First reported here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/arrayfire-users/nqUT8dtlxeo/Ldbi3EfjBAAJ

**Comment by shehzan10** [comment]
Fixed in hotfix-3.4.2
