### ISSUE TITLE
Incorrect output for regions() with CUDA if full component

### ISSUE THREAD

**Issue by Delgan** [arrayfire/arrayfire#1650]
Hello.

I just wanted to report a bug I encountered with the function regions().

In the case of a binary image fully composed of 1, the resulting array is only composed of 0, while it should be entirely composed of 1.

The bug disappeared if I used `-lafcpu` instead of `-lafcuda`.

Here is the minimal reproducible example:
```c
#include "arrayfire.h"
#include "af/cuda.h"

int main() {
    unsigned char in[8*8];
    for (int i = 0; i < 8*8; i++) in[i] = 1;

    af::array arr = af::array(8, 8, in);
    af::array reg = regions(arr.as(b8), AF_CONNECTIVITY_4);

    af_print(reg);
    return 0;
}
```

**Comment by nikkadim** [comment]
It looks right to me. Because 0 is the index and intensity(label) of first and only founded region.

**Comment by 9prady9** [comment]
I was able to reproduce the difference in behavior which needs to addressed. @Delgan Thank you for reporting it.
