### ISSUE TITLE
Library Bindings for Common Lisp

### ISSUE THREAD

**Issue by serialhex** [arrayfire/arrayfire#1654]
Contrary to popular belief, Common Lisp is alive and well!  I currently work for a company that does the majority of our work *in* Common Lisp.  Unfortunately, we are having to jump through hoops of fire in order to get the (very few) C++ libraries that we need to use working with our system as a whole (hint: it involves ZMQ and *lots* of small utilities).

One way this particular project can help us (and the CL community in general) is to provide library bindings so we can natively play with all the awesomely fast ArrayFire arrays while having the flexibility of Lisp.  I know it's not going to be quite as popular as Python bindings, but it will probably be easier to maintain.

How I would do it (if I had the time) would be to use [cl-autowrap](https://github.com/rpav/cl-autowrap) to wrap the C portion of your library, and then maybe a few helper functions and macros for spice and convienence.  While that isn't guaranteed to work all of the time, he has successfully wrapped SDL2 with minimal overhead using this method, and it seems a lot faster than FFI-ing each function.

Thanks, and just so you know, this library has been a pleasure to work with!  There are a few others we are interfacing with, and this one gives us the fewest headaches!!!

**Comment by pavanky** [comment]
@serialhex This sounds like an interesting project. The rest of @arrayfire/core-devel is busy, but I can help get this started if you are interested in contributing :)

**Comment by serialhex** [comment]
@pavanky I probably won't be able to contribute a lot, but there are a few personal projects I've been thinking about doing where ArrayFire might come in handy (read: critical w/o a massive change in work/life balance).  Let me know if you start a project & I'll fork and give a hand where I can!

I can probably convince my boss to let me hack on this @ work for a little bit here and there (right now we have a *very* tight deadline, and so even an ugly kludge is acceptable if it gets us to the finish line faster! Clean up is for the beta system.)

**Comment by serialhex** [comment]
@pavanky Things change every day!  I got the green light from my boss to work on some CL bindings, as it will speed up the overall workflow.  I won't be able to dedicate a lot time, but with your help it shouldn't take much time to get a workable project up & running.

If you want to talk more directly hit me up at my GitHub username at gmail, or justin dot patera at level3inspection.com.  I have been in touch with Scott Blakeslee at ArrayFire so he has my contact info also.

Take care!

**Comment by pavanky** [comment]
@serialhex I created a repo for this: https://github.com/arrayfire/arrayfire-lisp. We can move the discussion about implementing it there.
