### ISSUE TITLE
Lack of support for zero-length arrays

### ISSUE THREAD

**Issue by arcfide** [arrayfire/arrayfire#1655]
I have the following sample program that fails with an "Invalid input size" error because of the zero-length dimension. 

```
#include <stdio.h>
#include <arrayfire.h>

int main(int argc, char *argv[])
{
	dim_t s = 0;
	af_array a;

	af_err code = af_create_array(&a, NULL, 1, &s, s32);

	if (code != AF_SUCCESS) {
		printf("%s\n", af_err_to_string(code));
		return 1;
	}
	
	af_print_array(a);

	return 0;
}
```

Is there any support for zero length and rank-0 arrays? If not, when is this planned?

**Comment by arcfide** [comment]
Here is an example of a rank-0 array:

```
int main(int argc, char *argv[])
{
	dim_t s = 0;
	af_array a;
	int vals[] = { 1 };

	af_err code = af_create_array(&a, vals, 0, NULL, s32);

	if (code != AF_SUCCESS) {
		printf("%s\n", af_err_to_string(code));
		return 1;
	}
	
	af_print_array(a);

	return 0;
}
```

**Comment by pavanky** [comment]
@arcfide 

``` c
dim_t len = 0
af_create_handle(&a, 1, &len, s32);
```

On a side note, any reason you are using C instead of C++ ?
Any reason you are using C instead

**Comment by pavanky** [comment]
Is the above solution OK, or do you specifically need to create an array using `af_create_array` with 0 elements ?

**Comment by arcfide** [comment]
I'll give this a try and see how it works. I'm using C right now because that's what the rest of the application is written in. Is there a serious performance penalty for using C++ instead of C? Is there some reason not to use C?

**Comment by umar456** [comment]
There is no performance penalty for using the C++ interface. ArrayFire's C++ is much safer and easier to use. It will automatically manage resources and report errors without explicit error checks. Also indexing using the C interface is kind of cumbersome. 

ArrayFire's C interface should only be used if you are interfacing with other languages or if there is an explicit requirement for C for your project.

**Comment by arcfide** [comment]
I'm exploring the use of the C++ interface now and I'll report back if this works for me. What is the recommended way to create zero-length arrays in C++ then?

**Comment by pavanky** [comment]
@arcfide `array a = array()`

**Comment by arcfide** [comment]
That allows me to specify an unspecified array, but I'm talking about an array with a specific rank/shape, but with zero elements. I have two cases that I need to deal with: 1. A scalar array that has rank 0 (no dimensions), but a single scalar value; and 2. an empty array that has no values, but a non-zero rank where one, but not necessarily all, of the dimensions is zero. So, something like this:

    dim4 s(2,[1,0]); array a = array(s,NULL); 

or something like that.

**Comment by pavanky** [comment]
@arcfide Let us say that functionality is implemented, how would you differentiate between the two *after* it is created ?

**Comment by arcfide** [comment]
The primary differences would be in their types and their shapes. For, for instance, an equality test between a `[2, 0, 4]` array and a `[1,0,3]` array would give false. The difference between an array with zero dimensions and an empty array should be obvious, because the one has a single element in it, while the other has no elements, but a rank that is higher, that is a.numdims() != b.numdims().

**Comment by arcfide** [comment]
If this is not currently available I think I can work around not having empty or scalar arrays, but I'd like to be aware of the limitation and the current plans.

**Comment by pavanky** [comment]
@arcfide AFAIK, arrayfire only supports fully empty arrays. What you are asking may be possible to implement in the future but it is not immediately obvious.

**Comment by arcfide** [comment]
Alright, thanks for the information. I'll see what I can do with that.
