### ISSUE TITLE
Memory Leak in CPU regions

### ISSUE THREAD

**Issue by 9prady9** [arrayfire/arrayfire#1664]
`std::map` declared [here](https://github.com/arrayfire/arrayfire/blob/devel/src/backend/cpu/kernel/regions.hpp#L106-L109) is not clearing it's storage properly.

This was reported in google forums and the corresponding post can be found at [this URL](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/arrayfire-users/tldUree9bZE/BFeXtkVUBwAJ).

**Comment by shehzan10** [comment]
Fixed in hotfix-3.4.2
