### ISSUE TITLE
About ArrayFire Exception <Internal error:998>

### ISSUE THREAD

**Issue by liuyang123123** [arrayfire/arrayfire#1669]
My CUDA version is 8.0.44, and ArrayFire Version is v3.4.1, and use the GeFore 710M GPU.
But when I run the svd example , it error. The error is

ArrayFire Exception (Internal error:998):
In function void cuda::kernel::transpose<T, conjugate>(cuda::Param<T>, cuda::CParam<T>, int)
In file src\backend\cuda\kernel/transpose.hpp:109
CUDA Error (8): invalid device function

In function void __cdecl af::svd(class af::array &,class af::array &,class af::array &,const class af::array &)
In file src\api\cpp\lapack.cpp:19
ArrayFire Exception (Internal error:998):
In function void cuda::kernel::transpose<T, conjugate>(cuda::Param<T>, cuda::CParam<T>, int)
In file src\backend\cuda\kernel/transpose.hpp:109
CUDA Error (8): invalid device function

In function void __cdecl af::svd(class af::array &,class af::array &,class af::array &,const class af::array &)
In file src\api\cpp\lapack.cpp:19

I need to know how to solve this problem, Thanks a lot.

**Comment by pavanky** [comment]
@liuyang123123 710M is a Compute 2.1 card. NVIDIA deprecated their support in CUDA 8.0 and will be dropping support from CUDA 8.5

To reduce the installer size, ArrayFire 3.4 was not built with support for this GPU. If you want to continue using this GPU, down this zip files: http://arrayfire.s3.amazonaws.com/3.4.1/afcuda-3.4.1-compute20-windows.zip and replace afcuda.dll (after backing it up) in your install directory with the version in the zip file.

**Comment by mrkwjc** [comment]
I have similar issue with custom build on gentoo against Quadro 2000M. It seems that during compilation the compute 20 is properly recognized, at least configuration says:

-- CUDA Compute Detection Output: 20
-- CUDA Compute Detection Return: 0
-- CUDA Compute Detection Worked
-- Number of Computes Detected = 1
-- Setting Compute 20 to ON

but the examples usually end up with the title error and also the message says that "SM version specified by .target is higher than default SM version assumed". What does it actually mean? And how can i avoid this?

Below output form benchmarks/cg_cuda run:

ArrayFire v3.4.1 (CUDA, 64-bit Linux, build default)
Platform: CUDA Toolkit 8, Driver: 375.26
[0] Quadro 2000M, 1985 MB, CUDA Compute 2.1
terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Internal error:998):
In function cuda::kc_entry_t cuda::compileKernel(const char*, std::string)
In file src/backend/cuda/jit.cpp:494
CU Error (209)
ptxas fatal   : SM version specified by .target is higher than default SM version assumed


In function af::array af::transpose(const af::array&, bool)
In file src/api/cpp/transpose.cpp:20

**Comment by shehzan10** [comment]
Can you paste the first few lines of `arrayfire/build/src/backend/cuda/arith.ptx`, where `build` is the build directory.

These should look like:
```
//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-21124049
// Cuda compilation tools, release 8.0, V8.0.44
// Based on LLVM 3.4svn
//

.version 5.0
.target sm_30
.address_size 64
```

**Comment by mrkwjc** [comment]
That's what i have in arith.ptx:
```
//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-21124049
// Cuda compilation tools, release 8.0, V8.0.44
// Based on LLVM 3.4svn
//

.version 5.0
.target sm_20
.address_size 64
```
Maybe there should be sm_21 because Quadro 2000M has CUDA Compute 2.1?

**Comment by shehzan10** [comment]
Compute 20 is fine. The detection script converts 21 to 20.
Can you do:
```
touch src/backend/cuda/transpose.cu
```
followed by
```
VERSBOSE=1 make afcuda
```

This should give a bit of an output, but there will be one command that will start with NVCC (`/usr/local/cuda/bin/nvcc` or similar). Can you paste that here?

**Comment by mrkwjc** [comment]
Hi!

In the meantime i switched to ArrayFire v3.4.2 (3.4.1 before) and now examples do work as expected, so the problem somehow has gone. Thanks for help!

**Comment by fzimmermann89** [comment]
@pavanky :
Does the replacement of afcuda.dll work with the current 3.5 release of arrayfire? Is there a new compute2.0 compatible dll for this version? Thanks

**Comment by pavanky** [comment]
@fzimmermann89 compute 2.0 will no longer work with cuda backends because nvidia deprecated them. You can use afopencl.dll which will support those devices.

**Comment by fzimmermann89** [comment]
@pavanky 
compute 2.0 is still supported by the current cuda sdk 8 (although deprecated and last version that will support 2.0). Is there a technical reason for not supporting compute2.0 in the current arrayfire version or is it possible to compile it using compute 2?

**Comment by pavanky** [comment]
@fzimmermann89 you can probably compile 3.5.0 / 3.5.1 with compute 2. But I think there were some assumptions made that we are only going to support compute > 2 for a couple of functions.

If this is a huge blocker, we can help you apply the patches to run on your machine.

**Comment by fzimmermann89** [comment]
Thank you, I compiled the current master with compute 2 yesterday and didn't notice any problems so far.

**Comment by pavanky** [comment]
@fzimmermann89 Try running the tests to see if any of them fail :)

**Comment by fzimmermann89** [comment]
@pavanky
I am trying, but all cuda tests hang on  "global test environment teardown" after passing the test steps, regardless of compute version (I tried compute 3.5 on GTX Titan and 2.0 on 580, both on win7 x64). I am currently recompiling with debug information but don't know the test framework and cant recognize which instructions are running after the environment teardown message is printed.

**Comment by fzimmermann89** [comment]
Callstack of the deadlocked thread:
 ntdll.dll!NtReleaseKeyedEvent() 
 ntdll.dll!RtlpWakeConditionVariable() 
 ntdll.dll!RtlWakeConditionVariable() 
 nvcuda.dll!000007fed66d8efa() 
 nvcuda.dll!000007fed6681a21() 
 nvcuda.dll!000007fed6685ae1() 
 nvcuda.dll!000007fed658c19f() 
 nvcuda.dll!000007fed6705fcb() 
 afcuda.dll!cudart::deviceMgr::~deviceMgr(void) 
 afcuda.dll!cudart::globalState::~globalState(void) 
 afcuda.dll!cudart::globalState::registerFatBinary(void * * *,void *) 
 ucrtbase.dll!<lambda>(void)() 
 ucrtbase.dll!__crt_seh_guarded_call<int>::operator()<class <lambda_e24bbb7b643b32fcea6fa61b31d4c984>,class <lambda_275893d493268fdec8709772e3fcec0e> &,class <lambda_9d71df4d7cf3f480f8d633942495c3b0> >(class <lambda_e24bbb7b643b32fcea6fa61b31d4c984> &&,class <lambda_275893d493268fdec8709772e3fcec0e> &,class <lambda_9d71df4d7cf3f480f8d633942495c3b0> &&) 
 ucrtbase.dll!_execute_onexit_table() 
 afcuda.dll!dllmain_crt_process_detach(const bool is_terminating=true) Line 109 
 afcuda.dll!dllmain_dispatch(HINSTANCE__ * const instance=0x000007fe6fc80000, const unsigned long reason=0x00000000, void * const reserved=0x0000000000000001) Line 207 
 ntdll.dll!LdrShutdownProcess() 
 ntdll.dll!RtlExitUserProcess() 
 ucrtbase.dll!exit_or_terminate_process() 
 ucrtbase.dll!common_exit() 
 approx2_cuda.exe!__scrt_common_main_seh() Line 262 
 kernel32.dll!BaseThreadInitThunk() 
 ntdll.dll!RtlUserThreadStart() 

Can you point me in any direction why the tests deadlock?

**Comment by pavanky** [comment]
@mlloreda @umar456 ^

**Comment by fzimmermann89** [comment]
any help?

**Comment by pavanky** [comment]
@fzimmermann89 can you create a separate issue for this?

**Comment by fzimmermann89** [comment]
https://github.com/arrayfire/arrayfire/issues/1950
