### ISSUE TITLE
BUG in array assignment

### ISSUE THREAD

**Issue by vakopian** [arrayfire/arrayfire#1677]
The following code should work, but throws an exception:
```
    dim_t sz = 1;
    array a = constant(1.0f, 3, sz, f32);
    array b = constant(2.0f, 3, sz, f32);
    array cond = constant(0, sz, b8); // all false
    a(span, cond) = b(span, cond);

```
It results in
```
terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Invalid input size:203):
In function void assign(cuda::Array<T>&, const unsigned int&, const af_seq*, const cuda::Array<outType>&) [with Tout = float; Tin = float; af_seq = af_seq]
In file src/api/c/assign.cpp:70
Size mismatch between input and output

In function af::array::array_proxy& af::array::array_proxy::operator=(const af::array&)
In file src/api/cpp/array.cpp:498
```

This seems to be a very corner case: Using `sz` bigger than `1` works fine. Keeping `sz = 1`, but using a condition that's not all false also works fine (e.g. using `cond = constant(1, sz, b8)`). I know empty array handling is pretty new (from https://github.com/arrayfire/arrayfire/pull/1533), so perhaps there is still an issue handling this case.

**Comment by pavanky** [comment]
Fixed in hotfixes-3.5.1
