### ISSUE TITLE
unrwap

### ISSUE THREAD

**Issue by bhack** [arrayfire/arrayfire#168]
[This kind of operation](https://github.com/BVLC/caffe/blob/dev/src/caffe/util/im2col.cu) are needed for preparing image input in convolutional neural network. Do have any interest to have this kind of transformation?

**Comment by bhack** [comment]
It implements the matlab function im2col. The basic format is im2col(A,[m n],block_type).
When block_type is distinct, it pool a m*n distinct block and unwrap it to a colum vector. And when block_type is sliding, it pool each m*n block(like a sliding window) and unwrap it to a colum vector.

**Comment by pavanky** [comment]
An operation like this is useful for 1D data as well (not images).

Requesting good suggestions for names.

**Comment by pavanky** [comment]
The API should look like the following:

```
af_unwrap(af_array *out, const af_array in, 
                 const dim_t wx, const dim_t wy, 
                 const dim_t sx, const dim_t  sy);
```

- wx, wy will give window dimensions
- sx, sy will give stride dimensions
