### ISSUE TITLE
Segmentation faults occur when array from different backend is being destroyed.

### ISSUE THREAD

**Issue by shehzan10** [arrayfire/arrayfire#1685]
Test Code:
```
#include <arrayfire.h>
#include <cstdio>
#include <cstdlib>

using namespace af;
static array A;

int main(int argc, char *argv[])
{
    try {
        setBackend(AF_BACKEND_OPENCL);
        af::info();

        A = randu(5,3, f32);
        af_print(A);

    } catch (af::exception& e) {

        fprintf(stderr, "%s\n", e.what());
        throw;
    }

    return 0;
}
```

The segfault only happens when the setBackend is set to a non-default backend. The default backend does not segfault.

Alternately this can be confirmed by changing the order of [these](https://github.com/arrayfire/arrayfire/blob/devel/src/api/unified/symbol_manager.cpp#L162-L164) and then using the previous "default"  backend. What the reordering does is change the default backend in the unified manager.

**Comment by pavanky** [comment]
This has nothing to do with static arrays. It's because you are using a global variable. The global variable is instantiated when the program starts at which point the backend is the default one. Changing the current backend to non-default one means that the `af_destroy_array` from a different lib is being called which causes the segmentation fault. 

I am willing to bet you can reproduce the same bug by doing the following:

``` cpp
int main(int argc, char *argv[])
{
    af::array A;
   af::setBackend(AF_BACKEND_OPENCL);
   A = af::randu(5, 3);
   af_print(A);
   return 0;
}
```

**Comment by shehzan10** [comment]
Just tested your code. It's working fine.

**Comment by shehzan10** [comment]
That said, if the line `array A` is outside the main() function, then the code segfaults. Doesn't have to be static.

**Comment by pavanky** [comment]
> Thus, the assignment does not need to check for the backend of A.

That is happening on the RHS. Check what happens inside `operator=`. If there is an existing array `af_destroy_array` is called.

**Comment by shehzan10** [comment]
> That is happening on the RHS. Check what happens on LHS inside operator=. If there is an existing array af_release_array is called.

Agreed. But that does not explain why the segfault does not show up if the array is created inside main. Any thoughts there?

**Comment by pavanky** [comment]
@shehzan10 Did you try setting OpenCL backend instead of CPU?

**Comment by shehzan10** [comment]
I did. I tried CUDA (default) with OpenCL and CPU.
And on an AMD system, OpenCL (default) with CPU.

I also tried changing the default order (CUDA > OpenCL > CPU) to make CPU default and then test CUDA and OpenCL.

Results are consistent.

**Comment by pavanky** [comment]
@umar456 @shehzan10 This is a peculiar bug that can happen in other circumstances but is being triggered by this piece of code. Here is what is happening:

The singletons in OpenCL backend (specifically the memory manager) is being destroyed before the global variable in the sample program is being destroyed. This is the cause of the segmentation fault.

I am not sure what the best way to avoid this is. It is weird that this bug doesnt happen when the backend is not changed. 

Strangely, the destructor of AFSymbolManager hasn't been called at this point. So yeah, I am stumped about what to do here.

**Comment by umar456** [comment]
Fixed.
