### ISSUE TITLE
dyld: Library not loaded: @rpath/libforge.0.dylib

### ISSUE THREAD

**Issue by deejayfrankcesco** [arrayfire/arrayfire#1692]
Dear Sir. 
I'm so sorry but I doesn't succeeded to execute the plot2D simple example.
I installed arrayfire 3.4.2 just now and I'd like to try to plot some data.
But I get this output on terminal:

Down of page

What should I do?
Best Regards and many thanks in advance

**Comment by pavanky** [comment]
Did you add arrayfire libraries to the `LD_LIBRARY_PATH` as mentioned in the link from the error?

**Comment by deejayfrankcesco** [comment]
oh yes sorry I pasted the wrong parts. The error is this:

dyld: Library not loaded: @rpath/libforge.0.dylib
  Referenced from: /usr/local/lib/libafcpu.3.dylib
  Reason: image not found

**Comment by pavanky** [comment]
Can you show the output of `ls /usr/local/lib/`

**Comment by shehzan10** [comment]
This should be because `DYLD_LIBRARY_PATH` does not have `/usr/local/lib` as a part of it.
The quickest way to test it would be
`DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/usr/local/lib: /path/to/arrayfire/plot2d_cpu`.

If this works, then you can add `/usr/local/lib` to you `DYLD_LIBRARY_PATH` in `.bashrc`.

**Comment by shehzan10** [comment]
@deejayfrankcesco can you provide an update on this?

**Comment by pavanky** [comment]
@umar456 can you look into this ?

**Comment by pavanky** [comment]
@mlloreda too.

**Comment by mlloreda** [comment]
I've been able to replicate this issue with all OSX installers since v3.2.

Setting `DYLD_LIBRARY_PATH` does not help.

**Comment by wenatgithub** [comment]
any workaround or no arrayfire on osx for now? thanks.

**Comment by mlloreda** [comment]
@wenatgithub, currently working on finding a workaround.

In the meantime, you can build arrayfire from source by following [these instructions](https://github.com/arrayfire/arrayfire/wiki/Build-Instructions-for-OSX)

**Comment by mlloreda** [comment]
@wenatgithub, @deejayfrankcesco here's a temporary work-around:

```
ln -s /usr/local/lib/libforge.0.9.2.dylib /usr/local/lib/libforge.0.dylib
```

Turns out the installer isn't writing out `libforge.0.dylib`, which we'll need to fix.

**Comment by wenatgithub** [comment]
Hi Miguel,

thanks. but I got another one after following your instruction:

dyld: Library not loaded: /usr/local/lib/libglfw3.dylib

  Referenced from: /usr/local/lib/libforge.0.dylib

  Reason: image not found

Trace/BPT trap: 5


Need to install GlFW3?


best,

Wen


________________________________

**Comment by mlloreda** [comment]
@wenatgithub, yes, it looks like you're missing `glfw`, which you can grab via `brew`.

However, unless something went wrong with it, the installer should have taken care of that dependency for you. Did the installer finish successfully for you?

**Comment by wenatgithub** [comment]
yes, installer finished without warning or error.


________________________________

**Comment by shehzan10** [comment]
> I have the same problem with using arrayfire in os x runinng helloworld_cpu.
> my /usr/local/lib content is
> 
> cmake	libafopencl.3.4.2.dylib	libglfw.3.2.dylib
> libaf.3.4.2.dylib	libafopencl.3.dylib	libglfw.3.dylib
> libaf.3.dylib	libafopencl.dylib	libglfw.dylib
> libaf.dylib	libfontconfig.1.dylib	libpng.a
> libafcpu.3.4.2.dylib	libfontconfig.a	libpng.dylib
> libafcpu.3.dylib	libfontconfig.dylib	libpng16.16.dylib
> libafcpu.dylib	libforge.0.9.2.dylib	libpng16.a
> libafcuda.3.4.2.dylib	libfreetype.6.dylib	libpng16.dylib
> libafcuda.3.dylib	libfreetype.a	pkgconfig
> libafcuda.dylib	libfreetype.dylib

@wenatgithub According to this, you have `libglfw.dylib` etc whereas forge is looking for `libglfw3.dylib`. Brew installs libglfw3.dylib. Did you install libglfw2 or have you installed glfw manually?
@mlloreda can you verify that Brew's `glfw3` package installs `libglfw3*.dylib`?

@wenatgithub Can you provide the log `/tmp/AFInstallerForge.err`. This may have been deleted if you restarted your computer, in which case you can simply run the installer once again and it will generate that log.

**Comment by wenatgithub** [comment]
here you go.  it seems GLFW3 was installed...


-------------------

homebrew/core

-------------------

==> Tapping homebrew/versions

Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-versions'...

Tapped 97 formulae (126 files, 436K)

Installing GLFW3

-------------------

==> Downloading https://homebrew.bintray.com/bottles/glfw-3.2.1.el_capitan.bottle.tar.gz

==> Pouring glfw-3.2.1.el_capitan.bottle.tar.gz

~_~M  /usr/local/Cellar/glfw/3.2.1: 14 files, 286.5K

-------------------

Installing FontConfig

-------------------

==> Installing dependencies for fontconfig: libpng, freetype

==> Installing fontconfig dependency: libpng

==> Downloading https://homebrew.bintray.com/bottles/libpng-1.6.28.el_capitan.bottle.tar.gz

==> Pouring libpng-1.6.28.el_capitan.bottle.tar.gz

~_~M  /usr/local/Cellar/libpng/1.6.28: 26 files, 1.2M

==> Installing fontconfig dependency: freetype

==> Downloading https://homebrew.bintray.com/bottles/freetype-2.7.1.el_capitan.bottle.tar.gz

==> Pouring freetype-2.7.1.el_capitan.bottle.tar.gz

~_~M  /usr/local/Cellar/freetype/2.7.1: 62 files, 2.5M

==> Installing fontconfig

==> Downloading https://homebrew.bintray.com/bottles/fontconfig-2.12.1_2.el_capitan.bottle.tar.gz

==> Pouring fontconfig-2.12.1_2.el_capitan.bottle.tar.gz

==> Using the sandbox

==> Regenerating font cache, this may take a while

==> /usr/local/Cellar/fontconfig/2.12.1_2/bin/fc-cache -frv

~_~M  /usr/local/Cellar/fontconfig/2.12.1_2: 468 files, 3M


________________________________

**Comment by mlloreda** [comment]
@shehzan10, yes, `brew` installs `libglfw3*.dylib`.

**Comment by mlloreda** [comment]
@wenatgithub, it appears something went wrong with your installation. Would you be able to move this conversation to our [gitter](https://gitter.im/arrayfire/arrayfire)? You can ping me there directly.

**Comment by islandhx** [comment]
The macOS installer mangled the sym links for libglfw3.dylib and libforge.0.dylib. Both threw similar errors as below:
dyld: Library not loaded: /usr/local/lib/libglfw3.dylib
  Referenced from: /usr/local/lib/libforge.0.dylib
  Reason: image not found

Using the work around mlloreda suggested fixed these issues for my installation:
ln -s /usr/local/lib/libforge.0.9.2.dylib /usr/local/lib/libforge.0.dylib
ln -s /usr/local/lib/libglfw.3.2.dylib /usr/local/lib/libglfw3.dylib

It will compile and run the hello_cpu and hello_opencl
