### ISSUE TITLE
QUESTION: gfor allows adding arrays of different dimensions

### ISSUE THREAD

**Issue by vakopian** [arrayfire/arrayfire#1694]
If I try to add a `3x1` array to a `3x3` array, AF throws an exception about dimensions mismatch, as expected.
However, the following code works and appears to create the correct (intuitive?) result, i.e. it adds the column vector to each of the columns in the array.
```
    gfor (seq i, 1) {
        array a = constant(1.0f, 3, 3, f32);
        array b = constant(2.0f, 3, 1, f32);
        array c = b + a;
        af_print(c);
    }
```
Note that the sequence `i` in `gfor` is actually not used in the code.
Is this an expected and documented behavior?

**Comment by shehzan10** [comment]
You are not allowed to add arrays of different dimensions. If array 1 has dim `x` as `1` and array 2 has dim `x` as `n`, then you have to use `tile`. In this case, tile would be JIT, so it would not result in any additional operations.

**Comment by vakopian** [comment]
ok, shouldn't then the above code throw an exception?

**Comment by shehzan10** [comment]
Ah, sorry misread the question.

The way gfor works is by changing the batch dimension to the 4th dimension. Even if you are not using `i` in the array operations, the "batched" flag internally will be turned true. From there on, it will allow multiple of dimensions - that is - 1xN, 1x1, NxN to be batched.

This is the correct behavior under gfor.

**Comment by pavanky** [comment]
@vakopian to expand on what @shehzan10 has said, GFOR disables dimension checks and performs broadcast operations. This is expected behavior that you are seeing.

If you think GFOR looks weird, arrayfire has another function that can make your code more C++-11y:

You could use the following:
```
af::batchFunc(a, b, [](const &array lhs, const &array rhs){ return lhs + rhs; });
```

**Comment by vakopian** [comment]
@pavanky do you know what's better for performance 
the `batchFunc` in your snippet or `a + tile(b, ...)`?

**Comment by pavanky** [comment]
@vakopian All of them end up doing the same thing internally. We usually suggest tile because it is not hiding internal behavior.
