### ISSUE TITLE
https://arrayfire.com has an invalid certificate

### ISSUE THREAD

**Issue by valarauca** [arrayfire/arrayfire#1698]
The arrayfire ssl certificate was valid from
`Wed, 09 Dec 2015 00:00:00 UTC` to `Fri, 23 Dec 2016 23:59:59 UTC` which has since passed.

I was attempting to register with your website when I noticed this.

I could re-create in

FireFox 50.1.0 (x64 Windows 10 Pro x64)

Chrome 55.0.2883.87m (x64 Windows 10 Pro x64)

Edge 25.10586.672.0 

Mobile Safari (on iOS)

SSL Labs reports the same issue https://www.ssllabs.com/ssltest/analyze.html?d=arrayfire.com

**Comment by mlloreda** [comment]
This has been taken care of. Thanks for reporting @valarauca.

**Comment by mlloreda** [comment]
@pavanky is looking into enabling [Let's Encrypt](https://letsencrypt.org/)

**Comment by pavanky** [comment]
That is going to take a bit of figuring out. But the website is back to what it used to be.

**Comment by StefanBruens** [comment]
It has happened again ...

**Comment by 9prady9** [comment]
@StefanBruens Sorry about the inconvenience. We are aware of the issue and we are looking into it. Thanks for reporting it.
