### ISSUE TITLE
af::free conflicts with MSVC _CRTDBG_MAP_ALLOC

### ISSUE THREAD

**Issue by hypernewbie** [arrayfire/arrayfire#1703]
The msvc library #defines free to internal debug allocator in its library headers.

**Comment by 9prady9** [comment]
@hypernewbie Can you please update the issue description with the full compilation error message.

**Comment by chadwackerman** [comment]
Easy workaround:

```
#pragma push_macro("free")
#undef free
// include the arrayfire headers you need
#pragma pop_macro("free")
```

**Comment by 9prady9** [comment]
The function in question, `free`, is already enclosed in arrayfire(`af`) namespace to avoid conflicts with other similarly named functions in user space. Are you facing the problem even if you do `af::free` (use scope resolution operator to resolve name ambiguity) ?

**Comment by pavanky** [comment]
@9prady9 That doesn't matter for macros.

**Comment by 9prady9** [comment]
@pavanky  In that case, what @chadwackerman suggested is the alternative. We can't fix this in any reliable manner on the library side, am i correct to think so ?

**Comment by pavanky** [comment]
@9prady9 Yep.

**Comment by 9prady9** [comment]
Closing the issue in that case.

**Comment by chadwackerman** [comment]
You could put a guard in device.h. Pretty much everyone on Windows will hit this.

```
#if defined(_MSC_VER) && defined(free) // ...
```

**Comment by pavanky** [comment]
@chadwackerman You are the first one to bring it up. I am not sure about pretty much everyone on windows hitting this.

**Comment by chadwackerman** [comment]
Someone else brought it up. I just happened to have a solution handy from when I hit it, too.

When I'm dealing with quaternions I don't want to Google an obscure compiler error and wind up on GitHub Issue #1703. Other people might be into that sort of thing, who knows.

**Comment by pavanky** [comment]
@shehzan10 thoughts ?

**Comment by pavanky** [comment]
@chadwackerman If you feel like this is going to be a huge problem, can you send in a patch that'll reliably solve the issue ?

**Comment by shehzan10** [comment]
I don't think there is a straight forward way to fix this in all cases. In some ways, this is similar to Windows using min/max as macros and then to use `NOMINMAX` to fix it.
In that case, there is a straight forward fix - adding a preprocessor directive. However, this again is not a universal solution that WE provide since the user still has to add it in their own project.

**Comment by pavanky** [comment]
@shehzan10 won't adding the push pop pre-processors to the header file help ?

**Comment by shehzan10** [comment]
I'm not entirely sure. It would need some testing to get right.
