### ISSUE TITLE
ArrayFire OpenCL fails

### ISSUE THREAD

**Issue by svanschalkwyk** [arrayfire/arrayfire#1712]
Hi
Excellent product, by the way.
I'm having a terrible time getting ArrayFire 3 built on Intel (Parallel Studio 2017 XE, Intel MKL, Intel OpenCL etc.). I used to work on Windows and this is the first excursion with Intel tools on Linux (Centos 7.3).
My setup is as follows: 2xE5-2640, 2xPhi 3020, low-performance NVidia card for display.
I believe I have all the makefile settings correct (https://gist.github.com/svanschalkwyk/4f00487844d34f55b4f5eccaa8fb17d8), and while _cpu tests and examples work, _opencl tests and examples fail with segmentation faults.
Any ideas?

**Comment by pavanky** [comment]
Are you trying to run OpenCL on Xeon Phi or the CPU?

**Comment by svanschalkwyk** [comment]
On both - I wanted to get it running on CPU first, then progress to Phi.

With best regards,
Steph van Schalkwyk

*Steph van Schalkwyk*
Principal, Remcam Search Engines
+1.312.281.8982    step@remcam.net  http://www.remcam.net Skype:
svanschalkwyk <https://mail.google.com/mail/u/0/#> 2223 Park Avenue St.
Louis MO 63104 USA
<http://linkedin.com/in/vanschalkwyk>

**Comment by pavanky** [comment]
@svanschalkwyk can you show the output of clinfo ? There's no reason OpenCL on CPU should cause segmentation faults.

**Comment by pavanky** [comment]
unless there is a problem with graphics. Can you try running the examples with the following environment variable set ?

`export AF_DISABLE_GRAPHICS=1`

**Comment by svanschalkwyk** [comment]
Segmentation fault (core dumped). 
gdb output is:
Missing separate debuginfo for /lib64/libOpenCL.so.1
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/18/de8b5046adcfe0be9627f9cdab1812fe715d89.debug
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Missing separate debuginfo for /lib64/libnvidia-opencl.so.1
Missing separate debuginfo for /lib64/libcuda.so.1

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
Missing separate debuginfos, use: debuginfo-install opencl-1.2-intel-cpu-6.4.0.25-1.x86_64 opencl-2.1-intel-cpu-exp-6.3.0.1904-1.x86_64
Seems it is trying to use CUDA?

**Comment by svanschalkwyk** [comment]
CMakeCache.txt: https://gist.github.com/svanschalkwyk/37de7a8b12903996edd2f1d9d2a888b2

**Comment by pavanky** [comment]
@svanschalkwyk did you try running the examples with `AF_DISABLE_GRAPHICS=1` exported?

**Comment by svanschalkwyk** [comment]
Getting this on build now. Debugging
​
[ 55%] Building C object test/CMakeFiles/basic_c_opencl.dir/basic_c.c.o
[ 55%] Linking CXX executable cast_cpu
[ 55%] Linking C executable basic_c_opencl
[ 55%] Linking CXX executable regions_cpu
../src/backend/opencl/libafopencl.so.3.5.0: undefined reference to
`mkl_blas_xzdotc'
../src/backend/opencl/libafopencl.so.3.5.0: undefined reference to
`mkl_blas_xcdotc'
../src/backend/opencl/libafopencl.so.3.5.0: undefined reference to
`mkl_blas_xizamax'
../src/backend/opencl/libafopencl.so.3.5.0: undefined reference to
`mkl_blas_xisamax'
../src/backend/opencl/libafopencl.so.3.5.0: undefined reference to
`mkl_blas_xicamax'
../src/backend/opencl/libafopencl.so.3.5.0: undefined reference to
`mkl_blas_xcgeru'
../src/backend/opencl/libafopencl.so.3.5.0: undefined reference to
`mkl_blas_xzgeru'
../src/backend/opencl/libafopencl.so.3.5.0: undefined reference to
`mkl_blas_xidamax'
collect2: error: ld returned 1 exit status
make[2]: *** [test/basic_c_opencl] Error 1
make[1]: *** [test/CMakeFiles/basic_c_opencl.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

​Any idea why?​

**Comment by svanschalkwyk** [comment]
Removed and re-cloned arrayfire. Did clean build with devtoolset-4 compiler etc.
All openCL examples fail with segmentation fault. 
So, not an Intel compiler issue.
Andreas' OpenCL tools-master produces this:
./print-devices
platform 0: vendor 'Intel(R) Corporation'
  device 0: '      Intel(R) Xeon(R) CPU E5-2630 v2 @ 2.60GHz'
platform 1: vendor 'Intel(R) Corporation'
  device 0: '      Intel(R) Xeon(R) CPU E5-2630 v2 @ 2.60GHz'
platform 2: vendor 'NVIDIA Corporation'
  device 0: 'NVS 300'
So it seems as if OpenCL should be ok?

**Comment by shehzan10** [comment]
Just curious if you have tried the ArrayFire installer from arrayfire.com/download?

**Comment by svanschalkwyk** [comment]
The ArrayFire*.sh file? I tried it first.

With best regards,
Steph van Schalkwyk

*Steph van Schalkwyk*
Principal, Remcam Search Engines
+1.312.281.8982    step@remcam.net  http://www.remcam.net Skype:
svanschalkwyk <https://mail.google.com/mail/u/0/#> 2223 Park Avenue St.
Louis MO 63104 USA
<http://linkedin.com/in/vanschalkwyk>

**Comment by svanschalkwyk** [comment]
Works on a clean Mint (Ubuntu) install. No Intel OpenCL. No Phis. GTX 960+GTX780.
May be something with Intel compilers and/or Intel OpenCL. No time to waste on them anymore. Anyone want to buy two Phi 3021P with cooling ducts?
