### ISSUE TITLE
Remove limitation of MAX_BIN in CUDA and OpenCL backends

### ISSUE THREAD

**Issue by nikkadim** [arrayfire/arrayfire#1713]
Looks like the maximum (MAX_BIN) is in~3000, so for f32 image I can only count on ~3000 instead of 65535, but it's not documented in here: http://arrayfire.org/docs/group__image__func__histogram.htm

**Comment by pavanky** [comment]
making this duplicate of https://github.com/arrayfire/arrayfire/issues/1379 and fixing the issue.
