### ISSUE TITLE
OpenCL not work with VS 2010

### ISSUE THREAD

**Issue by wenatgithub** [arrayfire/arrayfire#1724]
Hi, 
I only have VS2010 under widows 7 64bit. I installed Arrayfire binaries (3.4.2) and was able to compile and run helloworld example with both cpu and CUDA backend after changing toolset version and platform in the project file.... but I couldn't get it to work with OPENCL. see the attached screenshot. it seems even af::getDevice() will throw an error. I tried this on two machines: one with i7 2700k and Nvidia tesla m2090 and the other one with i7 5820k. both showed the same error. is this because of VS2010? any other settings I have to change to make OpenCL to work.?GPU cap viewer showed both i7 and tesla m2090 support OpenCL. thanks for your help.

best,
Wen
![screen shot 2017-02-05 at 10 25 14 pm](https://cloud.githubusercontent.com/assets/25019249/22633729/055104d4-ebf2-11e6-97b7-91cddb618e4a.png)

**Comment by wenatgithub** [comment]
Hi,
to add more info. I tried this with vs2013. still the same problem. 

best,
Wen

**Comment by pavanky** [comment]
@wenatgithub did you figure out what the issue was?

**Comment by wenatgithub** [comment]
yes, it turns out to be the intel OpenCL driver. after installing it is fine now. surprised how that affect the CUDA card also.

**Comment by pavanky** [comment]
@wenatgithub When arrayfire initializes it tries to query all OpenCL devices. If there is a buggy implementation it could cause issues.
