### ISSUE TITLE
Feature request: Unlimited af_join_many

### ISSUE THREAD

**Issue by alha02** [arrayfire/arrayfire#1729]
I'm assuming that there are performance benefits to calling af_join_many instead of repeatedly calling af_join. If so, it would be great if the 10-array limit was removed. Would that be possible?

**Comment by pavanky** [comment]
Can you show what the use case is where you are joining many arrays ?

**Comment by alha02** [comment]
Basically I have a rather complicated function which returns a column of bools, and
I want to merge them column-wise to a matrix of bools, because that would greatly speed
up calculations down the line.

Now I know that I could pre-allocate the matrix and use assignment to do this, but the
thing is that I am calling the library from another language, so I need to use the C-api.
And the only way to do assign through the C-api is to use the af_assign_gen or af_assign_seq
functions (right?), which are pretty general, which I guessed meant that they were doing some lifting to work out where to assign stuff. So I figured that I would gain performance
by doing joins instead, given that the arrays are column-major behind the scenes.

**Comment by pavanky** [comment]
@alha02 I dont understand why you need `af_join_many` if you just have 1 vector and 1 matrix.. You can call `af_join` along any given dimension..

**Comment by pavanky** [comment]
on a related note, what language are you working on ?

**Comment by alha02** [comment]
Yes, no I know that. But there will be many columns to join, and I dont know beforehand how many they will be. As I mentioned earlier, I was assuming a perf gain by calling join_many instead of repeatedly calling join.

Im working in Julia. Thanks for the quick replies by the way!

**Comment by pavanky** [comment]
@alha02 at larger number of arrays, it really doesnt matter if the function is implemented inside arrayfire or outside. You could create a new function called `join_large` and just call `join_many` in a loop for now.

That said, I still want to see your current code if possible. If you can't send it here, please ping me over here: https://gitter.im/arrayfire/arrayfire

**Comment by alha02** [comment]
I really appreciate the offer to take a closer look, but if you think the performance is about equal for a large number of arrays then I take your word for it. I'll just do a loop on join_many as you said. Thanks again!
