### ISSUE TITLE
negative value of AF_MEM_INFO

### ISSUE THREAD

**Issue by dodobing** [arrayfire/arrayfire#1734]
I tested what is the maximum size of array can be allocated on GTX 980Ti because of this issue. I found that two cases of allocation failure. For the case 1 below, the size of array to be allocated is larger than device memory size, it raises out of memory exception. It is quite reasonable. For the case 2 below, the array size is smaller than device memory size and no exception was occurred. However, the allocated memory size get from AF_MEM_INFO is negative value. Does it mean it fails to allocate memory? If it means allocation failure, is there other factors except device memory size to limit maximum array size?

**Codes**

```
	af::deviceGC();

	AF_MEM_INFO("@0");

	af::array arrIn(nsz0, nsz1, nsz2, c32);
	arrIn.eval();

	AF_MEM_INFO("@1");
```

**Case 1**

nsz0 = 2048
nsz1 = 2048
nsz2 = 100

Array size : 3200.0MB

          Exception
          
unknown file: error: C++ exception with description "ArrayFire Exception (Device out of memory:101):
In function void *__cdecl cuda::MemoryManager::nativeAlloc(const unsigned __int64)
In file src\backend\cuda\memory.cpp:97
CUDA Error (2): out of memory

In function void __cdecl af::initEmptyArray(void **,af_dtype,__int64,__int64,__int64,__int64)
In file src\api\cpp\array.cpp:110" thrown in the test body. 
 
**Case 2**
 
nsz0 = 1946
nsz1 = 1946
nsz2 = 96

Array size : 2773.6MB 

Out of AF_MEM_INFO
 
AF Memory at D:\Programming\Workspace\ArrayFire Eval\EvalProject\src\main.cpp:106: @0
Allocated [ Bytes | Buffers ] = [ 0 | 0 ]
In Use    [ Bytes | Buffers ] = [ 0 | 0 ]
AF Memory at D:\Programming\Workspace\ArrayFire Eval\EvalProject\src\main.cpp:111: @1
Allocated [ Bytes | Buffers ] = [ -1386615808 | 1 ]
In Use    [ Bytes | Buffers ] = [ -1386615808 | 1 ] 
 
Thanks,
Taehong Kim

**Comment by 9prady9** [comment]
@arrayfire/core-devel I have tested this with v3.4.2 on CUDA v7.5 and haven't been able to reproduce it. MAY BE cuda 8.0 on Windows platform might help reproduce it. @pavanky Can you check this on your Linux machine with CUDA 8.0 ? - although i doubt you will see such error.

**Comment by pavanky** [comment]
@dodobing @9prady9 I think it is just the print statement `AF_MEM_INFO` that is bad. It uses`%ld` which converts the data type to `long` before printing. In windows this is 32 bit signed integer type. On Linux it is 64 bit signed integer type.

1946 * 1946 * 96 * 8 = 2908351488. The limit of 32 bit signed integers is 2^31 -1 which is 2147483647. 

@9prady9 you can reproduce this in linux by using `%d` instead of `%ld`

```
$ cat foo.c && gcc foo.c -o foo && ./foo
#include <stdio.h>

int main()
{
    printf("%d\n", (1946 * 1946 * 96 * 8));
    return 0;
}
foo.c: In function ‘main’:
foo.c:5:38: warning: integer overflow in expression [-Woverflow]
     printf("%d\n", (1946 * 1946 * 96 * 8));
                                      ^
-1386615808
```

@dodobing You should be able to fix this in windows by going into `AF_MEM_INFO` and changing `%ld` to `%lld`

**Comment by 9prady9** [comment]
@pavanky Makes sense.

**Comment by dodobing** [comment]
@pavanky Yes, it works. Thanks.

**Comment by pavanky** [comment]
@9prady9 can you fix this in one of the PRs you are sending ?
