### ISSUE TITLE
List projects using ArrayFire

### ISSUE THREAD

**Issue by 9prady9** [arrayfire/arrayfire#1735]
One location to store the list - a markdown file in the ArrayFire repository.
Please post your projects at the following link if you wish to showcase it on our wiki.

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/arrayfire-users/oM20kZd6HOk

**Comment by pavanky** [comment]
@9prady9 This should be a wiki maybe ?

**Comment by pavanky** [comment]
ok nvm, I misread the title.

**Comment by mchandra** [comment]
grim : General Relativistic Implicit Magnetohydrodynamics
http://ascl.net/1702.012

GRIM (General Relativistic Implicit Magnetohydrodynamics) evolves a covariant extended magnetohydrodynamics model derived by treating non-ideal effects as a perturbation of ideal magnetohydrodynamics. Non-ideal effects are modeled through heat conduction along magnetic field lines and a difference between the pressure parallel and perpendicular to the field lines. The model relies on an effective collisionality in the disc from wave-particle scattering and velocity-space (mirror and firehose) instabilities. GRIM, which runs on CPUs as well as on GPUs, combines time evolution and primitive variable inversion needed for conservative schemes into a single step using only the residuals of the governing equations as inputs. This enables the code to be physics agnostic as well as flexible regarding time-stepping schemes.

**Comment by 9prady9** [comment]
FDBB: Fluid Dynamics Building Blocks
https://gitlab.com/mmoelle1/FDBB

Fluid Dynamics Building Blocks (FDBB) is an expression template library for building CFD simulation tools. It provides the building blocks like inviscid and viscous fluxes, Jacobian matrices, eigenvalues/-vectors, etc

**Comment by umar456** [comment]
Hey guys,

I have created a post on our Google Groups forums for people to post projects using ArrayFire. I think that is a more appropriate platform for this type of discussion. This issue will eventually be closed but I don't want to discourage others to showcase their work. Please post your projects at the following link and we will periodically add them to the list.

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/arrayfire-users/oM20kZd6HOk
