### ISSUE TITLE
How to achieve CUDA Heterogeneous parallel computing function with Arrayfire?

### ISSUE THREAD

**Issue by HongChenGuaiKe** [arrayfire/arrayfire#1736]
I would like to add an Arrayfire code to an existing CPU program,passing the data in memory  into the GPU and using CUDA to accelerate computing, then return the results to memory finally .

## The higher goal is to achieve heterogeneous parallel computing,which means the GPU reads data from memory and calculates it while the CPU program is running at the same time.So how to achieve this function with Arrayfire?

First,I have tired the Unified Backend like the code shown in the official website:
`#include <arrayfire.h>

void testBackend()
{
	af::info();
	af_print(af::randu(5, 4));
}
int main()
{
	try {
		printf("Trying CPU Backend\n");
		af::setBackend(AF_BACKEND_CPU);
		testBackend();
	}
	catch (af::exception& e) {
		printf("Caught exception when trying CPU backend\n");
		fprintf(stderr, "%s\n", e.what());
	}
	try {
		printf("Trying CUDA Backend\n");
		af::setBackend(AF_BACKEND_CUDA);
		testBackend();
	}
	catch (af::exception& e) {
		printf("Caught exception when trying CUDA backend\n");
		fprintf(stderr, "%s\n", e.what());
	}
	try {
		printf("Trying OpenCL Backend\n");
		af::setBackend(AF_BACKEND_OPENCL);
		testBackend();
	}
	catch (af::exception& e) {
		printf("Caught exception when trying OpenCL backend\n");
		fprintf(stderr, "%s\n", e.what());
	}
	return 0;
}`

But turn out this error:

`af::randu(5, 4)
[5 4 1 1]
    0.3990     0.2727     0.1296     0.0050
    0.8805     0.5652     0.7023     0.1318
    0.7357     0.0689     0.0491     0.8732
    0.6055     0.8790     0.0141     0.7400
    0.7739     0.4668     0.8877     0.2540

Trying CUDA Backend
Caught exception when trying CUDA backend
ArrayFire Exception (Invalid input argument:202):
In function af_err __cdecl af_set_backend(const af_backend)
In file src\api\c\device.cpp:27
Invalid argument at index 0
Expected: bknd==getBackend()

In function void __cdecl af::setBackend(const af_backend)
In file src\api\cpp\device.cpp:22
Trying OpenCL Backend
Caught exception when trying OpenCL backend
ArrayFire Exception (Invalid input argument:202):
In function af_err __cdecl af_set_backend(const af_backend)
In file src\api\c\device.cpp:27
Invalid argument at index 0
Expected: bknd==getBackend()

In function void __cdecl af::setBackend(const af_backend)
In file src\api\cpp\device.cpp:22`

Then I realized:

> Don't: Do not use arrays between different backends
ArrayFire checks the input arrays to functions for mismatches with the active backend. If an array created on one backend, but used when another backend is set to active, an exception with code 503 (AF_ERR_ARR_BKND_MISMATCH) is thrown.

That means this feature can not achieve data transfer function.

Then I tried the CUDA custom kernels:

`//CPU code has pre-processed the data
//CUDA custom kernels
//Ensure any JIT kernels have executed

GE.eval();GH.eval();cu_invMx.eval();cu_Point_Source.eval();cu_dot.eval();
val_EE.eval();val_EH.eval();val_HE.eval();
row_EE.eval();row_EH.eval();row_HE.eval();
col_EE.eval();col_EH.eval();col_HE.eval();

//Obtain device pointers from ArrayFire array objects using

float *d_cu_invMx = cu_invMx.device<float>();float *d_cu_Point_Source = cu_Point_Source.device<float>();float *d_cu_dot = cu_dot.device<float>();
float *d_GE = GE.device<float>();float *d_GH = GH.device<float>();
float *d_val_EE = val_EE.device<float>();float *d_val_EH = val_EH.device<float>();float *d_val_HE = val_HE.device<float>();
float *d_row_EE = row_EE.device<float>();float *d_row_EH = row_EH.device<float>();float *d_row_HE = row_HE.device<float>();
float *d_col_EE = col_EE.device<float>();float *d_col_EH = col_EH.device<float>();float *d_col_HE = col_HE.device<float>();

//Determine ArrayFire's CUDA stream

int af_id = af::getDevice();
int cuda_id = afcu::getNativeId(af_id);
cudaStream_t af_cuda_stream = afcu::getStream(cuda_id);

//Set arguments and run kernel in ArrayFire's stream
//CUDA krenels

af::array EE = af::sparse(NumUnknown, NumUnknown, val_EE, row_EE, col_EE, AF_STORAGE_COO);
EE = af::sparseConvertTo(EE, AF_STORAGE_CSR);
af::array EH = af::sparse(NumUnknown, NumUnknown, val_EH, row_EH, col_EH, AF_STORAGE_COO);
EH = af::sparseConvertTo(EH, AF_STORAGE_CSR);
af::array HE = af::sparse(NumUnknown, NumUnknown, val_HE, row_HE, col_HE, AF_STORAGE_COO);
HE = af::sparseConvertTo(HE, AF_STORAGE_CSR);
int permutation4EH[2][2] = {
        { 0,1 },{ 1,0 }
};
int idxE0, idxE1, idxPermu;
while (t < FinalTime) {
        if (t + dt > FinalTime) dt = FinalTime - t;
        idxPermu = step % 2;
        idxE0 = permutation4EH[idxPermu][0];
        idxE1 = permutation4EH[idxPermu][1];
...................................//some computing code
        t += dt;
	step++;
}

// Return control of af::array memory to ArrayFire using

cu_invMx.unlock();cu_Point_Source.unlock();cu_dot.unlock();
val_EE.unlock();val_EH.unlock();val_HE.unlock();
row_EE.unlock();row_EH.unlock();row_HE.unlock();
col_EE.unlock();col_EH.unlock();col_HE.unlock();

//&& return to CPU kernels$$

af::print("GE(0, idxE1)=", GE(0, idxE1), 8);`

It could run and get the correct result,but###  still used the CPU computing without any acceleration.

I just learned programming and Arrayfire with a short time,so please help me.Thank you!

**Comment by pavanky** [comment]
What have you tried and how did it fail ? Please show some code.
