### ISSUE TITLE
Special Instructions for Arrayfire on Ubuntu VM?

### ISSUE THREAD

**Issue by Chronum94** [arrayfire/arrayfire#1738]
Is there anything special we should keep in mind when installing Arrayfire on a VM? I know that installing on a VM is obviously stripping it of the GPU capabilities, and this is obviously more for testing than production code, but I wanted to clear a few things up.

1. Is it a good idea to keep graphics building off? I imagine graphics building takes OpenGL, and Forge seems to be failing to build.
2. Are there any specific flags to use when building on an Ubuntu VM?

On a related, but possibly lower-priority note, would it be possible to make a Wiki entry that lists the CMake options? I know that the CMakeLists.txt file lists this, but it would be nice to have them in one place instead of scrolling down the entire file. Again, implementing this is fairly low-priority (assuming it doesn't already exist)

**Comment by pavanky** [comment]
> I know that the CMakeLists.txt file lists this, but it would be nice to have them in one place instead of scrolling down the entire file. 

This is a good suggestion. I think this can be done. I am sure it would be hard to make it exhaustive, but we can put in the most common ones and go from there.

As for building in a VM, there shouldn't be any need for special care when installing in a VM. You can disable graphics by passing `-DBUILD_GRAPHICS=OFF` to cmake.

**Comment by Chronum94** [comment]
I did. And it was building fine. But then the scan_by_key.cpp file takes an uncharacteristically large amount of time to compile (left it there for an hour, didn't move, nothing).

I've build AF from source a few times on Ubuntu 14.04/15.04/15.10/16.04, but this is not an issue I remember having before the last 2-3 attempts.

**Comment by Chronum94** [comment]
I tried that, and it's building fine. But now it's gets stuck at scan by key. Not breaks out stuck, but compiling for literally 45 minutes with no progress stuck. I see it sometimes on the cpu scan by key, sometimes on the OpenCL version. The screenshot shows it stuck on the OpenCL version. It's been ~15 minutes on this line.

![screenshot 1135](https://cloud.githubusercontent.com/assets/6704979/23982342/646a1e06-09e3-11e7-89e7-3aa127c445e0.png)

**Comment by pavanky** [comment]
scan_by_key and sort_by_key take a lot of time.. there are many templated instantiations in that file.

**Comment by Chronum94** [comment]
Thanks for the heads-up. At the risk of taking up too much time, should I be looking at CPU usage or disk usage? Because right now I'm using make -j4, and my CPU usage is at ~10% (afcpu.dir/sort_by_key.cpp.o), but my disk usage is redlined at 100%. Just want to make sure that leaving this overnight is an option.

**Comment by pavanky** [comment]
@Chronum94 The compilation is fairly memory and disk bound. Are you trying to build arrayfire devel branch or are you OK with 3.4 ? 

If 3.4 is OK, you could try downloading the installer

**Comment by Chronum94** [comment]
Just started the download on the installer. I may or may not have overlooked that there was/is a Linux installer...

Guess compiling from source just made me feel good. Aight, will install using installer.

**Comment by pavanky** [comment]
You can use this file if you dont want the graphics version: http://ci.arrayfire.org/userContent/Linux/ArrayFire-no-gl-v3.4.2_Linux_x86_64.sh

The installers from the website usually contain graphics dependencies.

**Comment by Chronum94** [comment]
Installed the one right from the website (still has a Login wall, don't know if that's intentional or not). Had to add /usr/local/lib to LD_LIBRARY_PATH, and now everything appears to work using lafcpu (lafopencl throws an exception, I imagine because of the VM situation).

Either way, AF works now on the VM. Thank you so much for all your help at this ungodly hour. Issue can be closed unless we're planning to implement the build options list.

**Comment by pavanky** [comment]
@Chronum94 closing this issue. Can you open a new one regarding the BUILD options thing?
