### ISSUE TITLE
List of CMake Build Options

### ISSUE THREAD

**Issue by Chronum94** [arrayfire/arrayfire#1741]
It would be a good idea to have a near-comprehensive list of build options for Arrayfire all in one place. One can obviously go and sift the entire CMakeLists file, but this addition would be great to the Wiki. It would also be a good idea to have the default values in the list, and potentially a one-line commend explaining what they do.

I can potentially compile a list of the options, so the devs can make the final formatted list/commenting, if that makes anyone's life easier.

**Comment by pavanky** [comment]
btw, I just `cmake -LAH` gives you the list of all the options being used and a little bit of their explanation.

Can you check if that output is enough or if you need more info ?

**Comment by Chronum94** [comment]
This is actually _exactly_ what I was talking about. Whether a separate list of 'commonly used options' is seen as necessary is up to the devs. Otherwise, this can be closed. Hopefully, other people looking for this feature will be led to this thread.

**Comment by pavanky** [comment]
tagging it as a question and closing the issue! I'll edit the build instructions to add commonly used options at a later point.
