### ISSUE TITLE
AF_STORAGE_CSC is not supported

### ISSUE THREAD

**Issue by gaika** [arrayfire/arrayfire#1744]
Trying to map Julia's `SparseMatrixCSC` to ArrayFire `AF_STORAGE_CSC` and it fails with:

```
In file src/api/c/sparse.cpp:190
Storage type is out of range/unsupported
```

Was removed by https://github.com/arrayfire/arrayfire/commit/0bb9f3dedbb229b8c82702856e1a74237bfef711

Any plans to support it again?

**Comment by gaika** [comment]
Workaround from https://github.com/arrayfire/arrayfire/issues/1739 to create CSR instead doesn't help as it creates a transpose of the original matrix. `af_transpose` fails with:

```
ERROR: ArrayFire Error (202) : Invalid input argument
In function const ArrayInfo& getInfo(af_array, bool, bool)
In file src/api/c/array.cpp:26
Invalid argument at index 0
Expected: info->isSparse() == false
```

**Comment by pavanky** [comment]
@gaika CSC never worked across all backends. The work around from #1739 is to use matmulTN to peform matrix multiplication. transpose doesn't work. If you *really* want to store in CSC format, you should multiply by an dense identity matrix which is not efficient.

**Comment by gaika** [comment]
Ok, so a proper workaround is to transpose the sparse matrix before converting to ArrayFire.

**Comment by pavanky** [comment]
I say leave this open for now. May be we can handle some of the fancy stuff internally.

**Comment by pavanky** [comment]
Closing this because #1739 deals with similar issues.
