### ISSUE TITLE
af_create_sparse_array is happy to accept Int64 indexes

### ISSUE THREAD

**Issue by gaika** [arrayfire/arrayfire#1745]
but the implementation expects Int32 row and column indexes resulting in silent corruption of the matrix.

**Comment by pavanky** [comment]
Hmm that should not be happenning. Thanks for raising the issue.

**Comment by mlloreda** [comment]
Code to replicate:

```
array A = af::randu(4, 4);
A(1, span) = 0; A(2, span) = 0;

array idx = where(A);
array data = A(idx);
array rows_idx = (idx / A.dims()[0]); // s64
array cols_idx = (idx % A.dims()[0]); // s64

af_array A_sparse;
af_create_sparse_array(&A_sparse, A.dims(0), A.dims(1), data.get(), rows_idx.get(), cols_idx.get(), AF_STORAGE_CSR);
```

**Comment by pavanky** [comment]
@mlloreda there are no checks in `af_create_sparse_array` to see if input is of the requested type.

@umar456 `getArray<int>` seems to work just fine even when the original was created as `Array<long long>`. Anyway we can automatically error out in those cases ?

**Comment by umar456** [comment]
static_asserts are the way to go for something like this. enable_if is another approach but its uglier.

**Comment by pavanky** [comment]
where would the static_assert go ?

**Comment by umar456** [comment]
it would go in the getArray<T> funciton. Something like `static_assert(std::is_same<T, int>::value)`

**Comment by pavanky** [comment]
Fixed in devel.
