### ISSUE TITLE
Limit factorization and decomposition functions to 2D inputs

### ISSUE THREAD

**Issue by mlloreda** [arrayfire/arrayfire#1748]
`lu()`, `qr()`, `svd()`, `cholesky()`, and `solve()` all need to error for 3-dimensional inputs and greater.

Relevant issue: https://github.com/arrayfire/arrayfire-rust/issues/123

**Comment by pavanky** [comment]
This is only until https://github.com/arrayfire/arrayfire/issues/483 is implemented. The current functions are not erroring out correctly.
