### ISSUE TITLE
Copy one array to another in GFOR without additional memory consumption

### ISSUE THREAD

**Issue by pavolmarak** [arrayfire/arrayfire#1756]
Hi everyone,

I would like to ask the ArrayFire community for help. I have the following problem:

1. I have matrix A with dimensions 2 x 2 x 3 (3D matrix, each slice has 2x2). I have another matrix B with dimensions 2 x 2. 
2. I want to multiply matrix B (2x2) with each slice in A(2x2x3), (3 multiplications in total) and I want to copy/assign the result of each slice multiplication back to the original slice in A without allocating additional memory space during assignment.
3. To perform all multiplications in parallel I use gfor-loop.
4. For purposes of copying newly obtained matrix back to original slice, I use void af::copy() function, which I guess, does not perform copy on write or in other words it does not allocate temporary buffer to carry out assignment. This is something I am not really sure about. I want to avoid additional memory consumptions in assignment because when working with larger matrices, it exceeds memory of my GPU and my program fails.

This how my code looks right now:

```
float data[] = {0,1,2,3,4,5,6,7,8,9,10,11};
af::array A(2,2,3,data);
af::array B(2,2,data+4); 


gfor(af::seq i,A.dims(2)){
     af::copy(A,A(af::span,af::span,i)*B,af::span,af::span,i); // this causes the problem, I feel something is wrong with passing "i" as argument to af::copy()
     // A(af::span,af::span,i) =  A(af::span,af::span,i) *  B; // this works, but during assignment it requires additional memory allocation and when I work with larger matrices this is serious problem
}
```

This code throws an exception saying:

```
ArrayFire Exception (Invalid input size:203):
In function void __cdecl assign<float,float>(class cuda::Array<float> &,const unsigned int &,const struct af_seq *,const class cuda::Array<float> &)
In file src\api\c\assign.cpp:35
Invalid dimension for argument 0
Expected: (outDs.ndims()>=iDims.ndims())

In function void __cdecl af::copy(class af::array &,const class af::array &,const class af::index &,const class af::index &,const class af::index &,const class af::index &)
In file src\api\cpp\index.cpp:41
```

**Is there anyone who can help me fix this?** What is the most efficient solution to my problem?

I will appreciate any kind of help. Thank you and all developers of ArrayFire for such an outstanding library that helps me in my research in the field biometrics. Strength of this library is unparalleled.

Paul.

af::info() output:

```
ArrayFire v3.4.2 (CUDA, 64-bit Windows, build 2da9967)
Platform: CUDA Toolkit 8, Driver: CUDA Driver Version: 8000
[0] GeForce GTX 650, 2048 MB, CUDA Compute 3.0
```

**Comment by pavanky** [comment]
There is no way to do what you are asking for right now.

**Comment by pavolmarak** [comment]
Could this be done without using gfor?

**Comment by pavanky** [comment]
@pavolmarak There's no way to call a function in arrayfire and not assign it to a new array. This is always  going to happen with the existing setup.

**Comment by pavanky** [comment]
But there are plans that will make it easier: https://github.com/arrayfire/arrayfire/issues/482

Please follow the discussion there.

**Comment by pavolmarak** [comment]
Or more generally, is it possible to rewrite the code and avoid additional memory allocation on assignment:

gfor(seq i,A.dims(2)){
   A(span,span,i) = A(span,span,i) *  B;
}

Thank you, I will follow the discussion you mentioned.

**Comment by pavanky** [comment]
@pavolmarak If the functionality in #482 was implemented, you'd be able to do something like this:

```
auto A_i = af::view(A, span, span, i);
A_i = A_i * B;
```

**Comment by pavolmarak** [comment]
Sorry for bothering you again, but maybe if I explain my problem in different way there will be some ideas how to improve my current situation.

I have only 1 GB GPU memory on my notebook GT730M card, so I cannot afford allocating too much memory.

This is my real situation that I cannot solve, this code does not work because I get out of memory message:

```
    int size =289;
    af::array A(size,size,812); // f32 array
    af::array B(size); // f32 array

    AF_MEM_INFO("BEFORE");
    try{
        gfor(af::seq i,A.dims(2)){
            A(af::span,af::span,i) =  A(af::span,af::span,i) * af::tile(B,1,size);
        }
    }
    catch(af::exception e){
        qDebug() << "Exception: " << e.what();
    }
    AF_MEM_INFO("AFTER");
```
I need to make it working for **size=289**, but the largest possible value that works for me without "Out of memory" errors is **size=247**. 

In case of size=247 I get this AF_MEM_INFO message:

```
AF Memory at curvedgaborgui.cpp:29: BEFORE
Allocated [ Bytes | Buffers ] = [ 198158336 | 2 ]
In Use    [ Bytes | Buffers ] = [ 198158336 | 2 ]
AF Memory at curvedgaborgui.cpp:47: AFTER
Allocated [ Bytes | Buffers ] = [ 792630272 | 5 ]
In Use    [ Bytes | Buffers ] = [ 198158336 | 2 ]
```

So my question is: **Is it possible to rewrite my code to make it working with size=289?** or maybe **is it possible to rewrite this code to not to consume more than 800MB GPU memory simultaneously?** 

It would be great if anyone shares any idea how to do it more memory efficiently because it prevents me from continuing in my project for a couple of days. I have read articles how to combine for and gfor if memory is the problem, but it increases my program run time heavily. Maybe there is some already prepared ArrayFire vectorized function that I am not aware of.  

Many thanks.
Paul

**Comment by pavolmarak** [comment]
This is my `af::info()` output:

```
ArrayFire v3.4.2 (CUDA, 64-bit Windows, build 2da9967)
Platform: CUDA Toolkit 8, Driver: CUDA Driver Version: 8000
[0] GeForce GT 730M, 1024 MB, CUDA Compute 3.5
```

**Comment by pavanky** [comment]
Have you simple tried the following ?

```
A = A * tile(B, 1, size, 812);
```

The tile will not increase the memory of B. This operation should take about 2x the memory of A. this should still fit in your memory.

**Comment by pavolmarak** [comment]
Perfect. It works. But .....

I realized that I posted old version of my code, what I really need is this :

```
    int size =289;
    af::array A(size,size,812); // f32 array
    af::array B(size,812); // f32 array


    AF_MEM_INFO("BEFORE");
    try{
        gfor(af::seq i,A.dims(2)){
        A(af::span,af::span,i)= A(af::span,af::span,i) * af::tile(B(af::span,i), 1, size); // each column in B is different
        }
    }
    catch(af::exception e){
        qDebug() << "Exception: " << e.what();
    }
    AF_MEM_INFO("AFTER");
```

Thank for your quick responses.

**Comment by pavanky** [comment]
@pavolmarak try the following:

```
af::array B1 = af::moddims(B, size, 1, 812);
A = A * af::tile(B1, 1, size);
```

**Comment by pavolmarak** [comment]
@pavanky Right now, Mr. Pavanky, you just **saved my life**. Thank you for this fantastic help, I have been fighting with this for days, I drew sketches of arrays of all possible dimensions, nothing helped. It really needs time, experience and advice from experts like you Pavanky to start thinking in "vectorized" manner. These tricks with af::moddims, af::tile, they are simply amazing.

**Comment by pavanky** [comment]
@pavolmarak There is also an example called vectorize.cpp which you may want to check out.

**Comment by pavolmarak** [comment]
Yes, of course I will definitely check this out. I have read the article about writing vectorized code but I was not able to transfer knowledge from it to my scenario. 

Now, after resolving this issue, I can continue with my fingerprint recognition project, more specifically I am implementing a GPU version of Gabor filtering and I will also check out GPU accelerated convolution from your library.
