### ISSUE TITLE
Re-writing ArrayFire code to consume less GPU memory

### ISSUE THREAD

**Issue by pavolmarak** [arrayfire/arrayfire#1759]
Dear ArrayFire community,

I am writing to ask you for help in my **problem related to memory/managment** in my code. I will start with code snippet which I am not able to run succesfully because I am getting "Out of memory" exception (the line that triggers exception is denoted in the comment next to it). I have only 800 MB GPU memory available before computation.

Code snippet:

```cpp
    try{
        af::array A = af::randu(289,260100); // this takes approx. 286 MB
         { // scope start
            af::array B = af::randu(289,260100); // this takes approx. 286 MB
            A *= B; // I want to multiply A * B and save it back to A
         } // scope end ... I wanted B to be existing only temporarily - I thought that B's memory will be flagged as re-usable after scope ends

         // here, I want B not to occupy GPU memory since I do not need B any more
        AF_MEM_INFO("BEFORE");
        af::printMemInfo("Memory before:");

        A = af::transpose(A,false); // this is line where I get "Out of memory" exception
        af::array result = af::sum(A,1); // sum along 1st dimension

        AF_MEM_INFO("AFTER");
        af::printMemInfo("Memory after:");
    }
    catch(af::exception e){
        qDebug() << e.what();
    }
```

**Short description of my situation:**

I have two matrices A and B filled with random numbers. They both occupy approximately 286 MB (A) + 286 MB (B)  = 572 MB. I intentionally created B matrix within short scope - I thought it will make B temporary (living only inside `{...}`). In this scope, I use B to perform operation A *=B. I hoped that memory of B would be flagged as reusable after scope ends or simply would allow other arrays to use its memory. Most probably, my thinking is wrong and B's memory is still used by ArrayFire and that prevents me from doing next computation step (`af::transpose()`) as I am running out of total GPU memory.

After I computed A *=B, I proceed to transposition of A and this is where my program fails because of "Out of memory" exception. 

I have very limited GPU memory of 800 MB and I want this code snippet to run even with this limitation.

**My questions:**

1. Is it possible to re-write this code snippet to run with 800 MB of memory?
2. How can I tell ArrayFire that I no longer need B? Is it possible to solve using scopes like in my code snippet? (_I want to remind that without memory occupied by B I would be able to successfully run the code_)

**This is `AF_MEM_INFO` output:**

```
AF Memory at curvedgaborgui.cpp:17: BEFORE
Allocated [ Bytes | Buffers ] = [ 601352192 | 2 ]
In Use    [ Bytes | Buffers ] = [ 601352192 | 2 ]
```

Here I expected to have only half of 601352192 bytes being currently in use.

**This is `af::printMemInfo()` output:**

```
Memory before:
---------------------------------------------------------
|     POINTER      |    SIZE    |  AF LOCK  | USER LOCK |
---------------------------------------------------------
|  0000000700DA0000  |   286.7 MB |       Yes |        No |
|  0000000712C60000  |   286.7 MB |       Yes |        No |
---------------------------------------------------------
```

**This is my `af::info()` output:**

```
ArrayFire v3.4.2 (CUDA, 64-bit Windows, build 2da9967)
Platform: CUDA Toolkit 8, Driver: CUDA Driver Version: 8000
[0] GeForce GT 730M, 1024 MB, CUDA Compute 3.5
```

**Comment by pavanky** [comment]
In this particular case, you will need to run `af::eval(A)` in the short scope.

**Comment by pavolmarak** [comment]
@pavanky  Thank you pavanky for your quick response. I rewrote the code according to your recommendation this way (I added `eval()` function as the last line in the scope):

```cpp
try{
        af::array A = af::randu(289,260100); // this takes approx. 286 MB
         { // scope start
            af::array B = af::randu(289,260100); // this takes approx. 286 MB
            A *= B; // I want to multiply A * B and save it back to A
            af::eval(A);
         } // scope end ... I thought that B's memory will be flagged as re-usable after scope ends

         // here, I want B not to occupy GPU memory since I do not need B any more
        AF_MEM_INFO("BEFORE");
        af::printMemInfo("Memory before:");

        A = af::transpose(A,false); // this is line where I get "Out of memory" exception
        af::array result = af::sum(A,1); // sum along 1st dimension

        AF_MEM_INFO("AFTER");
        af::printMemInfo("Memory after:");
    }
    catch(af::exception e){
        qDebug() << e.what();
    }
```

But now when I run this code I get "Out of Memory" exception in `eval()` line.

**Comment by pavanky** [comment]
Unfortunately `A *= B` is the same as the following

```
af::array tmp = A * B;
A = tmp;
```

This means there need to exist 3 arrays in memory which means it is about 790 MB

**Comment by pavolmarak** [comment]
So it seems there is no way to overcome this problem?

**Comment by pavolmarak** [comment]
In the meanwhile, I have tried to resolve my problem, I am close to solution, but another error occured. I have this piece of code:

```cpp
        int w = 17;
        int tx = 30;
        int ty = 30;
    af::array A(w*w,w,tx*ty*w);
    A= af::moddims(A, w*w,w*w*ty*tx);
```

I get this exception/error:

```
ArrayFire Exception (Internal error:998):
In function void __cdecl cuda::evalNodes<float>(class std::vector<struct cuda::Param<float>,class std::allocator<struct cuda::Param<float> > > &,class std::vector<class cuda::JIT::Node *,class std::allocator<class cuda::JIT::Node *> >)
In file src\backend\cuda\jit.cpp:658
CU Error (1)


In function class af::array __cdecl af::moddims(const class af::array &,const unsigned int,const __int64 *const )
In file src\api\cpp\data.cpp:191
```

What causes this?

My `af::info()`:

ArrayFire v3.4.2 (CUDA, 64-bit Windows, build 2da9967)
Platform: CUDA Toolkit 8, Driver: CUDA Driver Version: 8000
[0] GeForce GT 730M, 1024 MB, CUDA Compute 3.5
