### ISSUE TITLE
Internal Error 998 caused by af::moddims() function

### ISSUE THREAD

**Issue by pavolmarak** [arrayfire/arrayfire#1760]
Hello everyone,

I have very simple code snippet which I am not able to run because everytime I receive **998 Internal error exception**. 

**This is how my code looks like:**

```cpp
try{
        int w = 17;
        int tx = 30;
        int ty = 30;

        af::array A(w*w,w*w*ty*tx);
        af::array B(w*w,1,w*ty*tx);

        A= af::moddims(A,w*w,w,w*ty*tx);   
        A=  A* af::tile(B,1,w); // multiplication - when I comment this line, it works without 998 exception
        A= af::moddims(A,w*w,w*w*ty*tx);
}
    catch(af::exception e)
    {
        qDebug() << e.what();
    }
```

**This is my error message:**

```cpp
ArrayFire Exception (Internal error:998):
In function void __cdecl cuda::evalNodes<float>(class std::vector<struct cuda::Param<float>,class std::allocator<struct cuda::Param<float> > > &,class std::vector<class cuda::JIT::Node *,class std::allocator<class cuda::JIT::Node *> >)
In file src\backend\cuda\jit.cpp:658
CU Error (1)

In function class af::array __cdecl af::moddims(const class af::array &,const unsigned int,const __int64 *const )
In file src\api\cpp\data.cpp:191
```

I tried doing `af::eval(A)` before and after the line with multiplication with no effect, I thought it has something to do with lazy evaluation. However, when I leave out the line with multiplication, it works without any problem. 

Is there someone who could help me with this?

Thank you.

`af::info():`

```cpp
ArrayFire v3.4.2 (CUDA, 64-bit Windows, build 2da9967)
Platform: CUDA Toolkit 8, Driver: CUDA Driver Version: 8000
[0] GeForce GT 730M, 1024 MB, CUDA Compute 3.5
```

**Comment by pavanky** [comment]
Can you run your program from commandline with `AF_PRINT_ERRORS=1` exported ?

**Comment by pavolmarak** [comment]
I launched it from CMD and got this:

```
In function void __cdecl cuda::evalNodes<float>(class std::vector<struct cuda::Param<float>,class std::allocator<struct cuda::Param<float> > > &,class std::vector<class cuda::JIT::Node *,class std::allocator<class cuda::JIT::Node *> >)
In file src\backend\cuda\jit.cpp:658
CU Error (1)
```

I am not sure if I set AF_PRINT_ERRORS correctly. I followed [(this)](https://groups.google.com/forum/#!searchin/arrayfire-users/AF_PRINT_ERRORS%7Csort:relevance/arrayfire-users/kj5r-AtBAyU/B_Zu2goODAAJ) to set it in VS2015 in Windows 10.

Go to Project Properties -> Configuration Properties -> Debugging -> Environment. Type "AF_PRINT_ERRORS=1".

**Comment by pavolmarak** [comment]
Now I launched it again and this is what I received:

![image](https://cloud.githubusercontent.com/assets/23128885/25098439/d91f9f12-23a8-11e7-86bf-6e08b90db388.png)

**Comment by mlloreda** [comment]
Issue #133 might be relevant given the fact the issue only occurs on the CUDA backend.

**Comment by pavolmarak** [comment]
I want to run it on CUDA backend. On OpenCL backend, it works.

**Comment by pavolmarak** [comment]
When I replace the line with multiplication `A=  A* af::tile(B,1,w);` by this line `A=  A* A;` there is no 998 exception. This is interesting.  It seems that `af::tile(B,1,w)` being on the right side of multiplication causes the problem.

**Comment by pavolmarak** [comment]
I found that there is a problem with the length of z-dimension (3rd dimension). If I reshape matrix `af::tile(B,1,w)` from being too deep along 3rd dimension to be too wide along 2nd dimension, it also works.

**Comment by pavolmarak** [comment]
Problem **solved**. I rewrote my program to work with matrices having not so long 3rd dimension. I moved the data from the 3rd dimension to the 2nd dimension, retaining the order by using `af::reorder()` and now everything works perfectly. Closing this issue.

**Comment by pavanky** [comment]
@pavolmarak Sorry about the bug. This is a long standing bug that should be resolved. I am going to fix this asap.

**Comment by pavolmarak** [comment]
@pavanky It is OK, I am happy that I found a way out. Maybe one more question, is there any more efficient way of doing `af::reorder()` ?

I have `af::array A(289,17,13804)` and then I want to reorder it using `af::reorder(A,0,2,1)` to get array of dimensions 289x13804x17 (I am swapping 1st and 2nd dimension). This operation takes approximately 0.0512 s and so far is the slowest stage in my algorithm. 

Could this be done even faster?

**Comment by pavolmarak** [comment]
I wrote something down on a piece of paper. This is what I want. From matrix A (2,8) I want to obtain new  matrix A (2,4,2).

Matrix A (2,8):
![a_old](https://cloud.githubusercontent.com/assets/23128885/25109212/79726a80-23db-11e7-9109-1055a15c988d.jpg)

Matrix A (2,4,2):
![a_new](https://cloud.githubusercontent.com/assets/23128885/25109225/8a0daf62-23db-11e7-9bc0-e0c9b5deed36.jpg)

**Comment by pavanky** [comment]
Hmm, there could be an optimization (by just changing the metadata internally) for this that isn't implemented when reorder doesn't mess with dim == 0.

**Comment by pavolmarak** [comment]
I moved it to separate issue #1761
