### ISSUE TITLE
Improve performance of reorder

### ISSUE THREAD

**Issue by pavolmarak** [arrayfire/arrayfire#1761]
Hello,

I wrote something down on a piece of paper. This is what I want. From matrix A (2,8) I want to obtain new  matrix A (2,4,2).

Matrix A (2,8):
![a_old](https://cloud.githubusercontent.com/assets/23128885/25109212/79726a80-23db-11e7-9109-1055a15c988d.jpg)

Matrix A (2,4,2):
![a_new](https://cloud.githubusercontent.com/assets/23128885/25109225/8a0daf62-23db-11e7-9bc0-e0c9b5deed36.jpg)

I want to obtain this **only by `af::moddims()`** because `af::reorder()` is very time expensive. 

Now I can do it only by:

```cpp
    float data[] = {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16};
    af::array A(2,8,data);

    A=  af::moddims(A,2,2,4);
    A= af::reorder(A,0,2,1); // this cost too much time with large arrays
```

**Comment by pavanky** [comment]
@pavolmarak I realized there is a work around that can be done using existing functionality until this issue is fixed. It involves using functions from internal.h, I'll need some time to investigate this.

**Comment by pavolmarak** [comment]
@pavanky Perfect, I am very glad to hear that. If I got this fixed it would drastically improve my algorithm running time by reducing it by more than half. I will be trying to do that with some combination of moddims() and/or tile().

**Comment by pavolmarak** [comment]
@pavanky

Hello pavanky,
any progress on this?

**Comment by pavanky** [comment]
@pavolmarak can you try the PR from #1766 ?

**Comment by pavanky** [comment]
Sorry about the delay!
