### ISSUE TITLE
Assignment broken on CPU backend.

### ISSUE THREAD

**Issue by pthon** [arrayfire/arrayfire#1764]
Array value assignment changes the copied values when running on CPU using python wrapping:

*a=af.randu(2,2,2)
print a[1]
a[0] =a[1]
print a[1]*

After the assignment, the values of *a[1]* changed unexpectedly. This behaviour is not observed running on CUDA backend. 
I am using ArrayFire v3.5.0 (CPU, 64-bit Linux, build 251e942) on Intel(R) Xeon(R) CPU E5-2630 0 and the current python wrapper development version.

**Comment by mlloreda** [comment]
@pthon, can you raise this issue in [arrayfire-python](https://github.com/arrayfire/arrayfire-python), instead?

**Comment by mlloreda** [comment]
Thanks!

**Comment by pavanky** [comment]
@pthon thanks for reporting this. I was able to reproduce this in C++ with the following code:

```
int main(int argc, char *argv[])
{
    try {
        af::array a = af::randu(2,2,2);
	af_print(a);
	a(0, span, span) = a(1, span, span);
	af_print(a);
    } catch (af::exception& e) {
	fprintf(stderr, "%s\n", e.what());
	throw;
    }
    return 0;
}
```

And you are right, this does not happen with CUDA backend.

**Comment by pavanky** [comment]
This is broken in 3.4.2. Could potentially be broken from earlier.
