### ISSUE TITLE
Nonsensical OpenCL build error

### ISSUE THREAD

**Issue by saethlin** [arrayfire/arrayfire#1779]
`Could NOT find OpenCL (missing: OpenCL_LIBRARY) (found version "2.0")`

I have `opencl-headers` installed. What does this error message mean?

**Comment by 9prady9** [comment]
It seems like you have installed only headers. I assume this some Linux distribution, did you install the OpenCL binary package ? Please show the output of the following command
```
cmake <path to CMakeLists.txt in repo root> -LA | grep -i opencl
```

**Comment by saethlin** [comment]
Yes, I am using Ubuntu 16.04.

I installed `ocl-icd-opencl-dev` which appears to be the `.so` for OpenCL, but:
```
-- TESTS: OpenCL backend is OFF. afopencl was not found
-- EXAMPLES: OpenCL backend is OFF. afopencl was not found
BUILD_OPENCL:BOOL=OFF
OpenCL_INCLUDE_DIR:PATH=/usr/include
OpenCL_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libOpenCL.so
```

**Comment by pavanky** [comment]
That isn't an OpenCL driver as far as I can tell.

**Comment by saethlin** [comment]
Nope, managed to find an SDK and it builds now.
Still salty about that error message though.

**Comment by pavanky** [comment]
That is standard CMake boilerplate.

**Comment by hex-344505** [comment]
Have same trouble on Ubuntu 16.04
just set cmake .. -DOpenCL_LIBRARY=/opt/amdgpu-pro/lib/x86_64-linux-gnu/libOpenCL.so.1
and it works

**Comment by 9prady9** [comment]
@hex-344505 
On Linux, I think it is pretty much a standard for all shared libraries to have symlinks defined in similar fashion as shown below
```
$ ls -l /usr/lib/libOpenCL.so*
lrwxrwxrwx 1 root root     18 Jan 19 19:32 /usr/lib/libOpenCL.so -> libOpenCL.so.1.0.0
lrwxrwxrwx 1 root root     18 Jan 19 19:32 /usr/lib/libOpenCL.so.1 -> libOpenCL.so.1.0.0
-rwxr-xr-x 1 root root 132952 Jan 19 19:32 /usr/lib/libOpenCL.so.1.0.0
```

The CUDA toolkit's own libOpenCL also does the same.
```
$ ls -l /opt/cuda/lib64/libOpenCL.so*
lrwxrwxrwx 1 root root    14 Mar  5 19:48 /opt/cuda/lib64/libOpenCL.so -> libOpenCL.so.1
lrwxrwxrwx 1 root root    16 Mar  5 19:48 /opt/cuda/lib64/libOpenCL.so.1 -> libOpenCL.so.1.0
lrwxrwxrwx 1 root root    18 Mar  5 19:48 /opt/cuda/lib64/libOpenCL.so.1.0 -> libOpenCL.so.1.0.0
-rw-r--r-- 1 root root 26080 Mar  5 19:48 /opt/cuda/lib64/libOpenCL.so.1.0.0
```

I would guess the amdgpu-pro is not doing something similar, more specifically it is not creating the simple `.so` symlink shown in the first bash output above. Hence, it worked fine when you have overwritten the `OpenCL_LIBRARY` variable with the SONAME file `.so.1` path.
