### ISSUE TITLE
clfft Teardown warning being generated when unloading OpenCL library

### ISSUE THREAD

**Issue by Thormidable** [arrayfire/arrayfire#1781]
**Version:**
 - V3.4.2

**Branch**
- master

**Issue:**
 - AF OpenCL library generates a warning indicating that clfft teardown has not been called.
 - Warning is generated when unloading a dll linked against the AF OpenCL library. 
 - Linking dll against clfft and calling clfftteardown as the last call during unloading does not remove the warning.

**Comment by 9prady9** [comment]
On Windows, Intel's OpenCL implementation had a bug(at the time of fft feature addition) that causes the program to crash on exit even though the program execution reached end of `main()` and all resources are freed appropriately. AMD's OpenCL lib didn't exhibit such behaviour. Therefore, for Windows we skip calling `clfftTeardown` while releasing the library resources.

**Comment by 9prady9** [comment]
If you are building on devel branch, you can edit [this section](https://github.com/arrayfire/arrayfire/blob/devel/src/backend/opencl/fft.cpp#L55-L65) of code to fix the warning for your system. Note that this change might break the program on Intel's devices.

**Comment by Thormidable** [comment]
Thank you, I'll close the issue and investigate a work around at our end.
