### ISSUE TITLE
Crash on Intel Beignet when calling clGetGLContextInfoKHR in markDeviceForInterop

### ISSUE THREAD

**Issue by mabl** [arrayfire/arrayfire#1782]
Dear all,

I am not sure, if this is a Beignet bug, or if arrayfire is to blame here. I would still like to document my findings:

I have a segmentation fault when calling into `clGetGLContextInfoKHR` in `DeviceManager::markDeviceForInterop` . I'm still building a debug beignet build to see what is going on there. Still, this problem can be circumvented when running without graphics (setting env variable AF_DISABLE_GRAPHICS=1)

In this case af_info() then gives me:

```
ArrayFire v3.4.2 (OpenCL, 64-bit Linux, build default)
[0] BEIGNET : Intel(R) HD Graphics Haswell Ultrabook GT2 Mobile, 2048 MB -- OpenCL 1.2 beignet 1.4 (git-448f8f7a) -- Device driver 1.4 -- FP64 Support: False -- Unified Memory (True)
```

**Comment by mabl** [comment]
Judging from the issues page of beignet it says:

```
* cl\_khr\_gl\_sharing.
  This extension is partially implemented(the most commonly used part), and we will implement
  other parts based on requirement.
```

I just wonder why I hit this now and not earlier....

**Comment by pavanky** [comment]
@mabl Closing the issue because it looks like it is not an issue in arrayfire.
