### ISSUE TITLE
crash in cuda::compileKernel() when multithreading

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#1801]
Using : 
- AF devel (commit e59eb93c16b08ff790a68b6be85ba1b51773ad01)
- dozen of cpu threads, 
- AF crashs in cuda::compileKernel() in backend/cuda/jit,cpp:

cuda::compileKernel() calls: 
    CU_CHECK(cuLinkComplete(linkState, &cubin, &cubinSize));
    CU_CHECK(cuModuleLoadDataEx(&module, cubin, 0, 0, 0));
    CU_CHECK(cuModuleGetFunction(&kernel, module, ker_name + 1));

People on the web seem to wonder whether these cuXXX commands are really threadsafe or not. 
I indeed dont see any mutex locks in AF cuda::compileKernel().
@9prady9  : are you sure cuda::compileKernel() does NOT need any threadsafe protection ?
Regards

**Comment by pavanky** [comment]
@WilliamTambellini without showing what the error is it is really hard to tell what the problem is. Btw the commit you linked to is NOT master. It is still in development branch.

**Comment by WilliamTambellini** [comment]
Hi @pavanky 
Sure, here is the stack trace:
3  qsort qsort.c                      
9  cuModuleLoadDataEx 
10 cuda::compileKernel(const char *, std::string) 
11 cuda::getKernel(std::vector<cuda::JIT::Node *> const&, std::vector<int> const&, std::vector<cuda::JIT::Node *> const&, std::vector<cuda::JIT::Node_ids> const&, bool) [clone .constprop.380] 
12 void cuda::evalNodes<float>(std::vector<cuda::Param<float>>&, std::vector<cuda::JIT::Node *>)  
13 void cuda::evalNodes<float>(cuda::Param<float>&, cuda::JIT::Node *)
14 cuda::Array<float>::eval() 
15 cuda::Array<float> modDims<float>(cuda::Array<float> const&, af::dim4 const&)
16 void assign<float, float>(cuda::Array<float>&, unsigned int const&, af_seq const *, cuda::Array<float> const&)
17 void assign_helper<float>(cuda::Array<float>&, unsigned int const&, af_seq const *, void * const&)
18 af_assign_seq
19 af_err unified::AFSymbolManager::call<void * *, void *, unsigned int, af_seq const *, void *>(const char *, void * *, void *, unsigned int, af_seq const *, void *)
20 af_assign_seq
21 af_assign_gen
22 af_err unified::AFSymbolManager::call<void * *, void *, long long, af_index_t const *, void *>(const char *, void * *, void *, long long, af_index_t const *, void *) 0x7fffe74d2bff
23 af_assign_gen 
24 af::array::array_proxy::operator=(af::array const&) 0x7fffe755659b 
I see another thread also in cuda::compileKernel(const char *, std::string) when crash happens.

My bad: I m in devel branch but perhaps it does nt matter as threasafety is supposed to be done in this branch too.

**Comment by pavanky** [comment]
@WilliamTambellini The thread safety branch was merged because it was stable enough for other developers to start testing it,  work on it and figure out the bugs. There's some kinks to work out. This is a development branch for a reason..

**Comment by WilliamTambellini** [comment]
@pavanky thanks. Just retried using the master branch and see the same crash:

3  qst      qsort.c                       150  0x7ffff44d8e0e 
4  qst      qsort.c                       196  0x7ffff44d902c 
5  qsort    qsort.c                       49   0x7ffff44d92c8  
11 cuModuleLoadDataEx  0x7fff9eb0af35 
12 cuda::compileKernel(const char *, std::string)
13 cuda::getKernel(std::vector<cuda::JIT::Node *> const&, std::vector<int> const&, std::vector<cuda::JIT::Node *> const&, std::vector<cuda::JIT::Node_ids> const&, bool) [clone .constprop.380]
14 void cuda::evalNodes<float>(std::vector<cuda::Param<float>>&, std::vector<cuda::JIT::Node *>) 
15 void cuda::evalNodes<float>(cuda::Param<float>&, cuda::JIT::Node *)
16 cuda::Array<float>::eval() 
17 af_eval 
18 af_err unified::AFSymbolManager::call<void *>(const char *, void *) 
19 af_eval  
20 af::array::eval() const

Do you think cuModuleLoadDataEx is threadsafe ?
Cheers

**Comment by pavanky** [comment]
master branch is not thread safe at all. The thread safety is still under devleopment in the devel branch.

**Comment by WilliamTambellini** [comment]
In in cuda/jit.cpp cuda::getKernel(), locking just before searching for kernels seems to avoid the crash:
...
 std::lock_guard<std::mutex> lock(getKernelMutex);
 kc_t::iterator idx = kernelCaches[device].find(funcName);
...
@umar456 @pavanky : would there be better/faster ?
Regards
WT

**Comment by WilliamTambellini** [comment]
https://github.com/arrayfire/arrayfire/pull/1815

**Comment by pavanky** [comment]
@WilliamTambellini is this issue fixed by #1815 ?

**Comment by WilliamTambellini** [comment]
This issue is prehaps fixed with this one but probably some other recent changes about multithreading.
I would need to retry with the very latest devel branch. 
Has anyone multithreaded the NeuralNetwork MNIST AF example to try on your side ?

**Comment by pavanky** [comment]
@WilliamTambellini I can give it a shot. Do you want me to multi thread this along the data ?

**Comment by WilliamTambellini** [comment]
We could probably close this one but state of the art CI would indeed impose to multithread for instance the NMIST example. But lets speak about that in another item. Tks.

**Comment by WilliamTambellini** [comment]
Ok I have just retried with 3.6.2 and no crash at least with afcuda : 

single thread (running on 1 GPU):
ArrayFire v3.6.2 (CUDA, 64-bit Linux, build dc38ef1)
Platform: CUDA Toolkit 9.2, Driver: 396.37
[0] GeForce GTX 1080, 8120 MB, CUDA Compute 6.1
-1- TITAN V, 12067 MB, CUDA Compute 7.0
ArrayFire ANN Demo
Starting new learner thread on device 0
Starting demo on device 0 ...
Device: 0, Epoch:   10, Error: 10.3298
Device: 0, Epoch:   20, Error: 10.3311
Device: 0, Epoch:   30, Error: 10.3291
Device: 0, Epoch:   40, Error: 9.9394
Device: 0, Epoch:   50, Error: 9.0665
Device: 0, Epoch:   60, Error: 8.9774
Device: 0, Epoch:   70, Error: 7.3782
Device: 0, Epoch:   80, Error: 4.0790
Device: 0, Epoch:   90, Error: 2.9410
Device: 0, Epoch:  100, Error: 2.5688
Device: 0, Epoch:  110, Error: 2.4399
Device: 0, Epoch:  120, Error: 2.3670
Device: 0, Epoch:  130, Error: 2.3240
Device: 0, Epoch:  140, Error: 2.2669
Device: 0, Epoch:  150, Error: 2.2290
Device: 0, Epoch:  160, Error: 2.2312
Device: 0, Epoch:  170, Error: 2.2150
Device: 0, Epoch:  180, Error: 2.2012
Device: 0, Epoch:  190, Error: 2.2017
Device: 0, Epoch:  200, Error: 2.2029
Device: 0, Epoch:  210, Error: 2.2075
Device: 0, Epoch:  220, Error: 2.2155
Device: 0, Epoch:  230, Error: 2.2403
Device: 0, Epoch:  240, Error: 2.2144
Device: 0, Epoch:  250, Error: 2.1935
Accuracy on training data: 98.82 device: 0
Accuracy on testing  data: 94.25 device: 0
Training time on device 0: 6.9829 s
Prediction time on device 0: 0.0004 s


Multithreaded : 1 GPU per thread : 
ArrayFire v3.6.2 (CUDA, 64-bit Linux, build dc38ef1)
Platform: CUDA Toolkit 9.2, Driver: 396.37
[0] GeForce GTX 1080, 8120 MB, CUDA Compute 6.1
-1- TITAN V, 12067 MB, CUDA Compute 7.0
ArrayFire ANN Demo 
Starting new learner thread on device 0
Starting new learner thread on device 1
Starting demo on device 0 ...
Starting demo on device 1 ...
Device: 0, Epoch:   10, Error: 10.3298
Device: 0, Epoch:   20, Error: 10.3311
Device: 0, Epoch:   30, Error: 10.3291
Device: 0, Epoch:   40, Error: 9.9394
Device: 0, Epoch:   50, Error: 9.0665
Device: 1, Epoch:   10, Error: 10.3298
Device: 0, Epoch:   60, Error: 8.9774
Device: 1, Epoch:   20, Error: 10.3311
Device: 0, Epoch:   70, Error: 7.3782
Device: 1, Epoch:   30, Error: 10.3291
Device: 0, Epoch:   80, Error: 4.0790
Device: 1, Epoch:   40, Error: 9.9395
Device: 0, Epoch:   90, Error: 2.9410
Device: 1, Epoch:   50, Error: 9.0665
Device: 0, Epoch:  100, Error: 2.5688
Device: 1, Epoch:   60, Error: 8.9774
Device: 0, Epoch:  110, Error: 2.4399
Device: 1, Epoch:   70, Error: 7.3789
Device: 0, Epoch:  120, Error: 2.3670
Device: 1, Epoch:   80, Error: 4.0787
Device: 0, Epoch:  130, Error: 2.3240
Device: 1, Epoch:   90, Error: 2.9413
Device: 0, Epoch:  140, Error: 2.2669
Device: 0, Epoch:  150, Error: 2.2290
Device: 1, Epoch:  100, Error: 2.5687
Device: 0, Epoch:  160, Error: 2.2312
Device: 1, Epoch:  110, Error: 2.4398
Device: 0, Epoch:  170, Error: 2.2150
Device: 1, Epoch:  120, Error: 2.3667
Device: 0, Epoch:  180, Error: 2.2012
Device: 1, Epoch:  130, Error: 2.3236
Device: 0, Epoch:  190, Error: 2.2017
Device: 1, Epoch:  140, Error: 2.2669
Device: 0, Epoch:  200, Error: 2.2029
Device: 1, Epoch:  150, Error: 2.2284
Device: 0, Epoch:  210, Error: 2.2075
Device: 1, Epoch:  160, Error: 2.2302
Device: 0, Epoch:  220, Error: 2.2155
Device: 1, Epoch:  170, Error: 2.2143
Device: 0, Epoch:  230, Error: 2.2403
Device: 1, Epoch:  180, Error: 2.2008
Device: 0, Epoch:  240, Error: 2.2144
Device: 1, Epoch:  190, Error: 2.2003
Device: 0, Epoch:  250, Error: 2.1935
Accuracy on training data: 98.82 device: 0
Accuracy on testing  data: 94.25 device: 0
Training time on device 0: 8.2506 s
Prediction time on device 0: 0.0004 s
Device: 1, Epoch:  200, Error: 2.2020
Device: 1, Epoch:  210, Error: 2.2070
Device: 1, Epoch:  220, Error: 2.2149
Device: 1, Epoch:  230, Error: 2.2417
Device: 1, Epoch:  240, Error: 2.2145
Device: 1, Epoch:  250, Error: 2.1924
Accuracy on training data: 98.82 device: 1
Accuracy on testing  data: 94.22 device: 1
Training time on device 1: 7.9557 s
Prediction time on device 1: 0.0002 s


I guess that issue could eventually be closed.
Tks

**Comment by 9prady9** [comment]
Seems like this issue has been eventually addressed and the relevant fixes are in 3.7.2. @WilliamTambellini If that is the case, can you please close this issue. Thank you.

**Comment by WilliamTambellini** [comment]
Yes tks.
