### ISSUE TITLE
Add bits to build instruction on Linux

### ISSUE THREAD

**Issue by Chronum94** [arrayfire/arrayfire#1802]
The build instructions for Linux are somewhat lacking in a few critical details:

1. AMDAPPSDK-3.0 installs with a broken symlink: https://community.amd.com/thread/202003 There is already an issue on this, and the suggestion there is to go to /opt/AMDAPPSDK-3.0/lib/x86_64, and then executing `sudo ln -sf sdk/libOpenCL.so.1 libOpenCL.so`.

2. On Ubuntu 17.04 (and almost certainly a few more recent versions, `libfontconfig1-dev` needs to be installed separately since it's not preinstalled.

I typically run into a fair few shenanigans when trying to install AF for OpenCL, both from the CI website, as well as from source. These are often problems for which there are no issues yet, and are reasonably easily solved, but nevertheless, could do with at least a mention in the build instructions page.

For now, those 2 suggestions up there would be really good for potential users, considering both of them have issues, and neither of them have made it to the build instructions page.

**Comment by pavanky** [comment]
The wiki is can be edited by anyone. Can you go ahead and do it?
