### ISSUE TITLE
Access violation on exit of simple CCL application

### ISSUE THREAD

**Issue by mhdarr** [arrayfire/arrayfire#1808]
Using OpenCL backend
A simple program using CCL throws an exception on exit. 
Issue does not occur on CUDA or CPU backend.
When rolled back from latest NVIDIA driver back to older one, problem is fixed as well.
![exception](https://cloud.githubusercontent.com/assets/13642399/26634861/ce830c54-460f-11e7-8cbb-29cea8be5bae.png)
![callstack](https://cloud.githubusercontent.com/assets/13642399/26634880/d7796f38-460f-11e7-8d6e-c6ed0286ecbf.png)

PC specs:
![systemspecs](https://cloud.githubusercontent.com/assets/13642399/26634919/04228ec0-4610-11e7-9760-8a5c8be8057e.PNG)

NVIDIA driver which failed: 381.65
NVIDIA driver which passed: 368.81

**Comment by mlloreda** [comment]
@mhdarr this appears to be an issue with the driver, thus probably out of our control.

Would you be able to post relevant code for us to reproduce the issue?

**Comment by mhdarr** [comment]
Currently avoiding issue by reverting to older driver, will put together a working example soon

**Comment by pavanky** [comment]
If the issue is avoided by reverting to an older driver, it is a driver problem not from arrayfire.

**Comment by Lokkij** [comment]
I am getting this exact same behaviour with an AMD R9 Fury with the following drivers (latest) and code:
```
Radeon Settings Version - 2017.0720.1902.32426
Driver Packaging Version - 17.30.1041-170720a-316467C-CrimsonReLive
Provider - Advanced Micro Devices, Inc.
2D Driver Version - 8.1.1.1614
Direct3D® Version - 9.14.10.01292
OpenGL® Version - 6.14.10.13491
OpenCL™ Version - 22.19.662.4
AMD Mantle Version - 9.1.10.0220
AMD Mantle API Version - 102400
AMD Audio Driver Version - 10.0.1.1
Vulkan™ Driver Version - 1.6.0
Vulkan™ API Version - 1.0.51
```

```cpp
int main(int argc, char *argv[])
{
    af::array zeros = af::constant(0, 3);
    return EXIT_SUCCESS;
}
```

I will try rolling back to various driver versions tomorrow, but the fact that this happens on both NVIDIA and AMD cards is interesting -- do both of them have the exact same issue in their drivers, or is there something else going on?

**Comment by mlloreda** [comment]
@Lokkij were you able to resolve this?

**Comment by Lokkij** [comment]
Unfortunately not. I tried a couple different driver versions (though forgot to document which ones) which did not help. 
The issue does not appear when calling the compiled program from the command line, so it's not a huge issue for me -- I can deal with an annoying popup in Visual Studio. Since the issue occurs on exit, I'm not sure whether it still happens but is silently ignored when calling from the command line or if it disappears entirely. Either way, it does not appear to affect behaviour so it's not a huge deal. 😃

**Comment by umar456** [comment]
@Lokkij We made some changes recently which may alleviate the issues you are experiencing. Could you try to update ArrayFire to v3.5.1 to see if it is still throwing that exception?

**Comment by Lokkij** [comment]
Upgrading to ArrayFire v3.5.1 did not resolve the issue, it is still throwing the same exception:
```
Exception thrown at 0x00007FF8A3F20E01 (ntdll.dll) in WCN.exe: 0xC0000005: Access violation reading location 0x0000000000000010.
```

**Comment by Benoit-Julien** [comment]
Hi, I have the same problem with OpenCl on Windows. I had installed the last driver of my GPU.
`Exception thrown at 0x00007FFE36B2AE20 (ntdll.dll) in TestArrayFire.exe : 0xC0000005 : Access violation reading location 0x0000000000000010.`
