### ISSUE TITLE
crash in af_sparse_matmul when multithreading

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#1811]
My app is crashing in af_sparse_matmul() when multithreaded:
- AF devel branch commit e59eb93c16b08ff790a68b6be85ba1b51773ad01
- os: ubuntu 16
- gcc 6
- backend : cuda via AF unified

bt from gdb:
3  qsort qsort.c                       79   0x7ffff44d7cf8 
20 cuda::Array<float> cuda::matmul<float>(common::SparseArray<float>, cuda::Array<float>, af_mat_prop, af_mat_prop)
21 af_sparse_matmul(void * *, void *, void *, af_mat_prop, af_mat_prop)
22 af_matmul
23 af_err unified::AFSymbolManager::call<void * *, void *, void *, af_mat_prop, af_mat_prop>(const char *, void * *, void *, void *, af_mat_prop, af_mat_prop)
24 af_matmul
25 af::matmul(af::array const&, af::array const&, af_mat_prop, af_mat_prop)  

If that could help, when crashing, I see some other threads in AF doing:
- af_eval()
- af_assign_seq() > cuLaunchKernel()
- af::cuda::copyArray() > copyWrapper()
- 2 other threads also in af_sparse_matmul()

**Comment by pavanky** [comment]
We really need reproducible code.. without it there's no guarantee that this isn't because of user error.

**Comment by WilliamTambellini** [comment]
seems to be fixed by
https://github.com/arrayfire/arrayfire/pull/1815
