### ISSUE TITLE
Scalar replace a single row/column

### ISSUE THREAD

**Issue by polarathene** [arrayfire/arrayfire#1819]
[Feature requested on the Rust wrapper repo](https://github.com/arrayfire/arrayfire-rust/issues/145#issuecomment-307546606), redirected to the main repo to raise the request:

I am wanting to efficiently update a single column with a large amount of rows to a single value. This is apparently in the works for `select()` as linked below. I've been directed here to request equivalent improvement/support for the `replace()`(particularly the scalar variant) method which could avoid creating another Array.

Example params:
```
input: [300mil, 5, 1, 1] // an Array, dims shown for example purposes
dim: 1 // targeting columns
index: 0 // 1st column in this case, 
            could also be an array of columns if that would be more useful
value: 97 // scalar value to apply to all elements in the column
```

As I want to do this with quite a few values and process each result, it would require n const Arrays * total amount of values and large column size used with `set_col()` which won't work due to vRAM limits. 

Alternatively the scalar `replace` is similar requiring a full array matching inputs dims with values of 1 except for the target column which would be value of 0. This can also be a memory issue depending on other dims lengths in addition to requiring more work to shift the column when targeting another column on input array(or switching to rows). Batch might work?

> If the following issue goes through, you can achieve same behavior using out = select(a, a != x_tiled, y_tiled); arrayfire/arrayfire#1345

**Comment by umar456** [comment]
This can also be performed by indexing.

```cpp
#include <arrayfire.h>
using namespace af;

int main() {
  array a    = randu(10, 5, u8);
  af_print(a);

  a(span, 1) = 97;
  af_print(a);
}

```

```
a
[10 5 1 1]
       232         39        213        213        197 
       105        141        141        172         87 
        76         76        219          0        216 
       216        175         32         82         82 
       134        207        244        244        130 
       179         12         12        187        165 
        91         91        169          3         85 
        85         69        130         54         54 
       224         42         60         60        192 
       202        190        190        213        146 

a
[10 5 1 1]
       232         97        213        213        197 
       105         97        141        172         87 
        76         97        219          0        216 
       216         97         32         82         82 
       134         97        244        244        130 
       179         97         12        187        165 
        91         97        169          3         85 
        85         97        130         54         54 
       224         97         60         60        192 
       202         97        190        213        146 
```

I am going to leave this issue open because I may not have understood your qestion.

**Comment by polarathene** [comment]
I'm not sure if the same can be done via the Rust wrapper, from memory indexing returned a new array of the indices you provided, rather than allowing you to only apply an operation to a subset of the original array. 

Hence the request, perhaps the Rust wrapper just needs to provide a method to do this, on the related thread `replace()` and `select()` were mentioned as solutions when updated in future release to support this.

Here is how indexing works as far as I understand via Rust, you can see values are untouched:

```Rust
// Creates an array with values 0-25 then reshapes to 5x5 grid
    let mut range_25 = af::range::<u32>(dims_25x1, 0);
    range_25 = af::moddims(&range_25, dims_5x5);

    // Selects rows 2 to 4 and spans columns
    let seqs = &[Seq::new(2, 4, 1), Seq::default()];
    // The index method returns the subset of rows from range_25
    let mut rows_2t4  = index(&range_25, seqs);

    // See original values
    af_print!("range_25: ", range_25);
    // [5 5 1 1]
    //      0          5         10         15         20
    //      1          6         11         16         21
    //      2          7         12         17         22
    //      3          8         13         18         23
    //      4          9         14         19         24

    af_print!("rows_2t4: ", rows_2t4);
    // [3 5 1 1]
    //      2          7         12         17         22
    //      3          8         13         18         23
    //      4          9         14         19         24


    // Multiply by 20, batching set to true
    rows_2t4 = mul(&rows_2t4, &20, true);
    af_print!("rows_2t4 *= 20: ", rows_2t4);
    // [3 5 1 1]
    //     40        140        240        340        440
    //     60        160        260        360        460
    //     80        180        280        380        480

    // Original array is untouched by the above changes
    af_print!("range_25 not affected by multiply: ", range_25);
    // [5 5 1 1]
    //      0          5         10         15         20
    //      1          6         11         16         21
    //      2          7         12         17         22
    //      3          8         13         18         23
    //      4          9         14         19         24
```

**Comment by 9prady9** [comment]
I am not sure why and how I missed this at the time this issue was raised. There are equivalent functions and features in rust wrapper too @polarathene 

Please look at the following tutorial (http://arrayfire.org/arrayfire-rust/arrayfire/book/indexing.html) - needs more improvements, but it does mention how to set columns and rows in the last section.

You would have to create a constant(http://arrayfire.org/arrayfire-rust/arrayfire/fn.constant.html) Array and pass it as second argument. 

Just in case, a more generalized version of indexing can be done using http://arrayfire.org/arrayfire-rust/arrayfire/struct.Indexer.html in rust wrapper.

I am closing this issue since it is more of question of how to do certain operation using rust wrapper for arrayfire at this point. Please follow the examples from above shared URLs to create a snippet that replaces a given column. If you still have any issues, feel free to contact me on our slack channel https://join.slack.com/t/arrayfire-org/shared_invite/MjI4MjIzMDMzMTczLTE1MDI5ODg4NzYtN2QwNGE3ODA5OQ
