### ISSUE TITLE
af::setDevice() bug when multithreading

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#1823]
Good morning
Here is a bug I see when multithreading using the latest AF devel branch commit 269bb5b31248d6855867966fa670c9e55e5326f8
using the cuda backend :
- on a multi gpu machine (I experiment on a 4 titanX machine, but should nt matter which model)
- call af::setDevice(0) from the main thread at program init
- create different matrices from different threads
- see (using for example nvidia-smi) that the per thread matrices are generated on different (random ?) gpus, not only on GPU 0
- do some computation and see the program will crash later with:
ArrayFire Exception (Unknown error:208):
In function const ArrayInfo& getInfo(af_array, bool, bool)
In file src/api/c/array.cpp:30
Input Array not created on current device

cheers

**Comment by pavanky** [comment]
This change may cause issues on some machines if running in exclusive mode: 
https://github.com/arrayfire/arrayfire/commit/2ad3f93727a1fbce97fbd3934daf02dff7ae57dd#diff-f5155a3669ca28eba996382dcede4d7dR77

**Comment by WilliamTambellini** [comment]
I just checked and all my gpus are in "default" mode : 
$ nvidia-smi  --query | grep 'Compute Mode'
    Compute Mode                    : Default
    Compute Mode                    : Default
    Compute Mode                    : Default
    Compute Mode                    : Default

From man nvidia-smi :
"Default" means multiple contexts are allowed per device.

But still, AF seems to spread arrays over multiple gpus...

**Comment by WilliamTambellini** [comment]
Here is the current devel cuda setActiveDevice():

`int DeviceManager::setActiveDevice(int device, int nId)
{
    thread_local bool retryFlag = true;

    int numDevices = cuDevices.size();

    if (device > numDevices)
        return -1;

    int old = getActiveDeviceId();

    if(nId == -1)
        nId = getDeviceNativeId(device);

    cudaError_t err = cudaSetDevice(nId);

    if (err == cudaSuccess) {
        tlocalActiveDeviceId() = device;
        return old;
    }

    // For the first time a thread calls setDevice,
    // if the requested device is unavailable, try checking
    // for other available devices - while loop below
    if (!retryFlag) {
        CUDA_CHECK(err);
        return old;
    }

    // Comes only when retryFlag is true. Set it to false
    retryFlag = false;

    while(true) {
        // Check for errors other than DevicesUnavailable
        // If success, return. Else throw error
        // If DevicesUnavailable, try other devices (while loop below)
        if (err != cudaErrorDeviceAlreadyInUse) {
            CUDA_CHECK(err);
            tlocalActiveDeviceId() = device;
            return old;
        }
        cudaGetLastError(); // Reset error stack
#ifndef NDEBUG
        printf("Warning: Device %d is unavailable. Incrementing to next device \n", device);
#endif
        // Comes here is the device is in exclusive mode or
        // otherwise fails streamCreate with this error.
        // All other errors will error out
        device++;
        if (device >= numDevices) break;

        // Can't call getNativeId here as it will cause an infinite loop with the constructor
        nId = cuDevices[device].nativeId;

        err = cudaSetDevice(nId);
    }

    // If all devices fail with DeviceAlreadyInUse, then throw this error
    CUDA_CHECK(err);

    return old;
}`

**Comment by WilliamTambellini** [comment]
Strange, cudaErrorDeviceAlreadyInUse seems legitimate:

cudaErrorDeviceAlreadyInUse = 54
    This indicates that a call tried to access an exclusive-thread device that is already in use by a different thread. 

Should I call setDevice() from all my threads ?

**Comment by pavanky** [comment]
@WilliamTambellini Can you try that, but this may still cause the same error.

**Comment by WilliamTambellini** [comment]
@umar456  @pavanky  ok so just tried to call af::setDevice(0) from all my threads including the main one and still see different GPUs being used. 
AF 3.4.2 works ok.
Should nt you mark this bug as a AF 3.5 release blocker ?

**Comment by umar456** [comment]
I am unable to reproduce this on a 4x K80 instance. Here is what I executed:

```cpp
#include <arrayfire.h>
#include <cstdio>
#include <cstdlib>
#include <vector>
#include <thread>

using namespace af;
using std::thread;
using std::vector;

int main(int argc, char *argv[])
{
    try {
      setDevice(0);
      af::info();

      vector<thread> threads;
      for(int i = 0; i < 4; i++) {
        threads.emplace_back([=]() {
		setDevice(0);
		af::info();
		    for(int i = 0; i < 100; i++) {
		      array a = constant(1, 1000, 1000);
		      array b = randu(1000, 1000);
		      array c = matmul(b, a);
		      c.eval();
		      }
		      });
      }
      for(auto& t : threads) { t.join(); }

    } catch (af::exception& e) {
      fprintf(stderr, "%s\n", e.what());
      throw;
    }

    return 0;
}
```

The code executes as expected on the same GPU as the main thread. @WilliamTambellini Can you try to see if this works on your system.

**Comment by WilliamTambellini** [comment]
Hi @umar456  it worked. You can close this one. Tks.
