### ISSUE TITLE
Whining/Squeal caused by ArrayFire program

### ISSUE THREAD

**Issue by polarathene** [arrayfire/arrayfire#1825]
I'm using the Rust wrapper for several weeks now. My current program immediately causes a whining sound now for some reason until stopped. I'm a bit concerned if this could lead to hardware component damage.

It may only allocate a few hunded MB and only use 33% GPU load. Another compute program Hashcat can put the GPU at 100% load and use much more vRAM while not causing the squealing sound(presumably a capacity from some component in my system). So what could be going on with ArrayFire that might cause this?

I did use nvvp to profile the CUDA backend and it looks rather fragmented. I'm not quite sure what this should normally look like for a good GPU program.

**Comment by pavanky** [comment]
Are you sure the sound is coming from the gpu and not the cpu fan ?

**Comment by polarathene** [comment]
@pavanky I just stressed the CPU to full load with

```
for _ in 0..4 { std::thread::spawn(|| loop { print!(""); }); }; loop { print!(""); };
```

I undid the changes in my ArrayFire program and the squealing is removed. I've implemented processing chunks of tiled data, taking my tiled permutations of 26^5 u64 elements and chunking that into two arrays to process was fine, when I chunked it to 26^4 u64 the squealing happens...

**Comment by pavanky** [comment]
I don't think this has anything to do with arrayfire. This sounds like the GPU fans kicking in when under load.

**Comment by polarathene** [comment]
@pavanky it is not the fans and it is not under load. I have a reproducible config for my program. It's not a high pitch noise, I think the term might be coil whine. I can give it lighter work or more heavy stressful work that willl put it under load or get the fans going, this is not that.

I have identified `locate()` and the main arithmetic function in my algorithm to contribute to the noise, commenting them out will remove it, but as mentinoed it's only under a specific workload/arraysize.

I will provide example code here when I've got it on github. If you're able to reproduce it you'll see what I mean.

**Comment by pavanky** [comment]
@polarathene Even if we are, there is nothing much that can be done. The only thing that we can solve is if the program fails to finish (or errors out) which would mean we have an infinite loop somewhere.

**Comment by polarathene** [comment]
@pavanky, I'm just curious what causes it and if I should be concerned about having the program run for long while that noise is made, it starts immediately and stops immediately when I stop my program. My nvidia control panel only indicates a load of 30% and no fans, temperature at normal levels etc.

It's alright since I intend the program to put the GPU under more load where this doesn't seem to happen, I figured you shouold know if it was possibly something going wrong with the JIT. I've not run the program to completion personally, but it seems to be working fine otherwise and probably would complete just fine.

**Comment by pavanky** [comment]
@polarathene If there is some reproducible code it would be interesting to test it out. But I am not entirely sure this is unnatural behavior. GPUs make sounds under various kinds of loads. If the temperature is not rising, I wouldn't be too worried. That said, take my advice with a grain of salt.

The whine could also be coming from the power circuitry at certain power loads. If you have a way to check how much power is being used, that would be another interesting data point.
