### ISSUE TITLE
issue with strong bilateral

### ISSUE THREAD

**Issue by ultimaRatio** [arrayfire/arrayfire#1827]
Hi,

i've run into an issue when using strong sigma values.
I've used this [image](https://upload.wikimedia.org/wikipedia/commons/a/a2/505_W._Wisconsin_St._-_panoramio.jpg) for my example, but i could reproduce this behavior with other images.
```    
    init();
    set_backend(Backend::CUDA);
    let truc = af::load_image("image.jpg".into(), true);
    let bilateral = af::bilateral(&truc, 21f32, 26f32, true);
    af::save_image("result.png".into(),&bilateral);
```
and the result if sometimes full of 16 pixels-wide colored artefacts (like on this [image](https://mega.nz/#!2MMm3YrJ!r8AycVbsuPDDtnKZoGSvdqpxDdIjQ9jk_MXuex17RnU))

Sadly, I don't have access to other GPU to run more tests (maybe mine is faulty but as every other Cuda code runs fine ...)

my setup : fedora 25/64 bits, geforce 970 / Cuda 8.0.61

**Comment by pavanky** [comment]
@9prady9 any progress on this?

**Comment by 9prady9** [comment]
Haven't looked into it yet.

**Comment by 9prady9** [comment]
@ultimaRatio Sorry about the delay in looking into this. I have checked with large spatial sigmas (even 21f you use in your example) that are possible on my device with a smaller image and I didn't notice any artifacts.

I was able to test until `10` spatial sigma with your 4kx3k image and didn't notice artifacts. For more larger sigmas, my machines hangs after a while though or the kernel times out. As far as the core algorithm is concerned, I think it's solid. Can you try the same code against `v3.5` and let me know if you still see artifacts. (Rust wrapper for v3.5 has also been released)

**Comment by 9prady9** [comment]
Closing the issue as it has been inactive for a while. @ultimaRatio Please reopen if you are still facing the issue with newer fix release.
