### ISSUE TITLE
Transpose failed with Large Single Dimension

### ISSUE THREAD

**Issue by mhdarr** [arrayfire/arrayfire#1829]
Transposing an af::array with one dimension of a value much greater than 1024*1024.
Fails on GPU but passes on CPU

Min Working Example: 
[AF Minimal working Example Transpose Issue.zip](https://github.com/arrayfire/arrayfire/files/1081226/AF.Minimal.working.Example.Transpose.Issue.zip)
PC specs:
![specs](https://user-images.githubusercontent.com/13642399/27233242-bf279812-52b0-11e7-96fe-6f703731931c.PNG)

**Comment by mlloreda** [comment]
@mhdarr can you describe how things are failing for you?

**Comment by mhdarr** [comment]
Unhandled exception at 0x000007FEFD85A06D in AFMinExampleTransposeProblem.exe: Microsoft C++ exception: af::exception at memory location 0x000000000020EBF0.

is the message thats thrown after I call transpose on my input array

**Comment by pavanky** [comment]
@mhdarr you should put an exception handler in your `main` and show what the message is..

**Comment by mhdarr** [comment]
![exception](https://user-images.githubusercontent.com/13642399/27280485-faa2a144-54df-11e7-922c-49a515781d37.png)

**Comment by mhdarr** [comment]
![exception message](https://user-images.githubusercontent.com/13642399/27280502-0d397b8e-54e0-11e7-813c-83baece9ceb9.PNG)

**Comment by pavanky** [comment]
This issue is being dealt with in https://github.com/arrayfire/arrayfire/pull/1807

**Comment by umar456** [comment]
Fixed in #1807
