### ISSUE TITLE
Could I just shutdown JIT and execute my codes directly?

### ISSUE THREAD

**Issue by BookmanHan** [arrayfire/arrayfire#1838]
JIT makes my program extremely slow, for which I would like to shutdown JIT.
Could I just shutdown JIT and execute the code directly?

Specifically, there will be a very long time for my program to speedup.
Could I just shut the JIT down?

Thanks, a lot.

**Comment by 9prady9** [comment]
@BookmanHan I don't think JIT can be disabled. Can you please share with us a code snippet with which we can reproduce the problem you are experiencing.

**Comment by BookmanHan** [comment]
I am very sorry for being unfamiliar with AF, which is indeed a powerful tool.
I use 'for' instead of 'gfor', to make this mistake.

Friendly, if someone encounters my problem (waiting a long time to speed up), he should check the code to replace 'for' with 'gfor'.

Thanks, a lot.
