### ISSUE TITLE
Why my code is slow?

### ISSUE THREAD

**Issue by BookmanHan** [arrayfire/arrayfire#1841]
Code: https://github.com/BookmanHan/CalGraph

I am implementing a computation graph similar as Tensorflow.
Code is in Main.cu, which involves Symbol.hpp and Operation.hpp.

What I encounter is that the code is too slow.
When I implement the same operations with VCL, it is much faster (x10).

ArrayFire performs considerably better than VCL.
I suppose there should be a bug?

How could I fix this problem?

Thanks, a lot.

**Comment by BookmanHan** [comment]
When I run the code.
The memory of GPU is normal, but the load of GPU is almost zero.

**Comment by BookmanHan** [comment]
I find the issue from Solver.hpp.
Specifically, the below function is too slow.

```
			void gradient(
				af::array& derv_grad,
				af::array& derv_x,
				af::array& elem,
				af::array& grad) const
			{
				derv_grad = moment * derv_grad + (1 - moment) * grad * grad;

				derv_grad = moment * derv_grad + (1 - moment) * grad * grad;
				af::array derv_elem = af::sqrt(derv_x + regularization) 
					/ af::sqrt(derv_grad + regularization) * grad;
				derv_x = moment * derv_x + (1 - moment) * derv_elem * derv_elem;

				elem -= derv_elem;
			}
```

**Comment by pavanky** [comment]
How are you benchmarking it? The first iteration is going to be slow because arrayfire compiles kernels using JIT. Subsequent calls should used the cached kernel and be faster.

**Comment by BookmanHan** [comment]
Thanks for response.
Indeed, after 10 iterations, the code speeds up nicely.

However, when I modify the code as 
`
void gradient(
	af::array& derv_grad,
	af::array& derv_x,
	af::array& elem,
	af::array& grad) const
	{
		elem -= derv_elem;
	}
`
Only after one iteration, the code works very well.

Is there any way to shorten the iterations in the previous version?
Current performance is acceptable, but when there are lots of element-wise operations, some concerns may be addressed.

No matter what, ArrayFire is an amazing and exciting library.
Thanks very much for the library and helping me.
Sincerely.

**Comment by pavanky** [comment]
@BookmanHan can you add `af::eval(elem)` at the end of your function ? 

As a general rule of thumb, try to add `af::eval()` around the output of all the functions you have if they mostly consist of element wise operations. If there are multiple outputs (that you passed by reference), you can use `af::eval(X1, X2, .. XN)` (as long as they are the same type and dimensions).

**Comment by BookmanHan** [comment]
Oh, it works.
Finally, when I modify my code as 
`
void gradient(
	af::array& derv_grad,
	af::array& derv_x,
	af::array& elem,
	af::array& grad) const
	{
		derv_grad = moment * derv_grad + (1 - moment) * grad * grad;
		af::eval(derv_grad);

		af::array derv_elem = af::sqrt(derv_x + regularization) 
			/ af::sqrt(derv_grad + regularization) * grad;
		af::eval(derv_elem);

		derv_x = moment * derv_x + (1 - moment) * derv_elem * derv_elem;
		af::eval(derv_x);

		elem -= derv_elem;
		af::eval(elem);
	}
`
it speeds up nicely, right now.

Thank you really very much.

**Comment by BookmanHan** [comment]
Well, your suggestion is much faster.
The problem is solved.

Thanks, again.
