### ISSUE TITLE
bug in fast docs / possible bug in implementation

### ISSUE THREAD

**Issue by ibtaylor** [arrayfire/arrayfire#1842]
https://github.com/arrayfire/arrayfire/blob/2528d711f371b18c0f51d5f545737d5c62ea284f/src/backend/opencl/kernel/fast.cl#L29-L41

- the documentation does not agree with the comments
- the implementation does not agree with the function name
- it likely should be <,>, instead of <=,>=.

I was working on a fast implementation outside of this project and noticed this. Thought I'd drop a quick line.

**Comment by pavanky** [comment]
@9prady9 can you look at this?

**Comment by 9prady9** [comment]
@ibtaylor Thanks for reporting this. I shall send in a fix and this should be available in 3.5.1 release.

**Comment by pavanky** [comment]
Fixed in hotfixes-3.5.1
