### ISSUE TITLE
af_unwrap contains incorrect assertions

### ISSUE THREAD

**Issue by plavin** [arrayfire/arrayfire#1852]
af_unwrap() in src/api/c/unwrap.cpp contains wrong assertions on lines 37 and 38. The maximum size for a window dimension should be dim+2*padding as the padding is applied on both sides of the dimension. 

For example, to following code should be valid but fails the assertion:

```
#include <arrayfire.h>

using namespace af;
int main(){
    array a = constant(1,2,2);
    array b = unwrap(a, 4, 2, 4, 2, 1, 0);
}
```

**Comment by pavanky** [comment]
Fixed in hotfixes-3.5.1
