### ISSUE TITLE
Very long initialization time on GTX 1080

### ISSUE THREAD

**Issue by FloopCZ** [arrayfire/arrayfire#1865]
I have two NVIDIA GPU's in my PC:
```
ArrayFire v3.5.0 (CUDA, 64-bit Linux, build default)
Platform: CUDA Toolkit 8, Driver: 381.22
[0] GeForce GTX 1080, 8100 MB, CUDA Compute 6.1
-1- GeForce GTX 760, 4037 MB, CUDA Compute 3.0
```

Consider this simple program:
```c++
#include <arrayfire.h>
int main()
{
    af::setBackend(AF_BACKEND_CUDA);
    af::info();
    af::array A = af::range(10);
}
```

When it is run on the GTX 760, everything is working as expected. When it is run on the GTX 1080, the `af::range(10)` operation takes 53 seconds to complete. Subsequent operations are fast, though.

```
$ time AF_CUDA_DEFAULT_DEVICE=1 ./a.out
ArrayFire v3.5.0 (CUDA, 64-bit Linux, build default)
Platform: CUDA Toolkit 8, Driver: 381.22
-0- GeForce GTX 1080, 8100 MB, CUDA Compute 6.1
[1] GeForce GTX 760, 4037 MB, CUDA Compute 3.0
AF_CUDA_DEFAULT_DEVICE=1 ./a.out  0.62s user 0.81s system 91% cpu 1.555 total

$ time AF_CUDA_DEFAULT_DEVICE=0 ./a.out
ArrayFire v3.5.0 (CUDA, 64-bit Linux, build default)
Platform: CUDA Toolkit 8, Driver: 381.22
[0] GeForce GTX 1080, 8100 MB, CUDA Compute 6.1
-1- GeForce GTX 760, 4037 MB, CUDA Compute 3.0
AF_CUDA_DEFAULT_DEVICE=0 ./a.out  54.39s user 1.32s system 99% cpu 55.833 total
```

Notes: During the 53 seconds, one CPU thread is fully utilized, GPU seems to be inactive, however, `nvidia-smi` registers the process. The OpenCL backend is not affected. System info:
```
Arch Linux 4.11.9-1-ARCH #1 SMP PREEMPT Wed Jul 5 18:23:08 CEST 2017 x86_64 GNU/Linux
gcc version 7.1.1 20170621
```

Any ideas what may be wrong?

**Comment by pavanky** [comment]
@FloopCZ How did you install arrayfire ? This can happen when a CUDA application was not compiled for the right toolkit. For example if you only ad GTX 760 when you compiled arrayfire, but ended up adding the 1080 afterwards. 

This should't happen if you are using the official installers.

**Comment by FloopCZ** [comment]
Hi, thank you for the info. I have installed ArrayFire from the official Arch Linux repository, which [may be missing](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/arrayfire#n35) the CUDA compute capability 6.1. I will try to build AF manually to see if it the issue persists.

**Comment by FloopCZ** [comment]
@pavanky With the official installer, the initialization time is normal. Thank you for the quick solution. I will fill a bug report on the Arch package.
