### ISSUE TITLE
Memory leak using rows and cols

### ISSUE THREAD

**Issue by Thormidable** [arrayfire/arrayfire#1867]
Have produced a memory leak when using rows and cols.
I have a temporary work around, but thought you would be interested in it.

Attached is a Minimum Working Example

[AF Minimal working Example memory leak.zip](https://github.com/arrayfire/arrayfire/files/1139608/AF.Minimal.working.Example.memory.leak.zip)

**Comment by FloopCZ** [comment]
I am going to paste your code in here, so that others do not have to extract the VC++ project. The code indeed seems to eat up an increasing amount of memory (tested on build `ArrayFire v3.5.0 (CPU, 64-bit Linux, build 05999f3)`)

```c++
#include <arrayfire.h>
using namespace af;

void NoLeak(af::array lImageI)
{
    af::array lRows = lImageI.rows(0, 1023);
    af::array Q3 = lRows.cols(0, 1023);
    Q3.eval();

    af::sync();
}

void CausesLeak(af::array lImageI)
{
    af::array Q3 = lImageI.rows(0, 1023).cols(0, 1023);
    Q3.eval();

    af::sync();
}

void GenerateLeak()
{
    af::array lInput = af::randn(4000, 4000, f32);
    //NoLeak(lInput);
    CausesLeak(lInput);
}

int main()
{
    for (long int lCounter = 0; lCounter < 10000; ++lCounter)
    {
        GenerateLeak();
        af::deviceGC();
    }
}
```

**Comment by pavanky** [comment]
@FloopCZ Thanks for this!

**Comment by pavanky** [comment]
@umar456 replacing `.rows().cols()` with `(af::seq(), af::seq())` doesn't cause the leak. This makes me think something's up with proxy ? We may be basing it on some assumption that we broke in src/api/c..

Here's a slightly modified test to see the memory leak immediately.

```
using namespace af;

void NoLeak(af::array lImageI)
{
    af::array lRows = lImageI.rows(0, 1023);
    af::array Q3 = lRows.cols(0, 1023);
    Q3.eval();
    af::sync();
}

void NoLeak2(af::array lImageI)
{
    af::array Q3 = lImageI(af::seq(0, 1023), af::seq(0, 1023));
    Q3.eval();
    af::sync();
}

void CausesLeak(af::array lImageI)
{
    af::array Q3 = lImageI.rows(0, 1023).cols(0, 1023);
    Q3.eval();
    af::sync();
}

void GenerateLeak()
{
    af::array lInput = af::randn(4000, 4000, f32);
    //NoLeak(lInput);                                                                                                                                                                                       
    //NoLeak2(lInput);                                                                                                                                                                                      
    CausesLeak(lInput);
}

int main()
{
    for (long int lCounter = 0; lCounter < 10; ++lCounter)
    {
        GenerateLeak();
        af::printMemInfo();
    }
}
```

@Thormidable Can you use the work around shown in `NoLeak2` ? They are functionally the same but `NoLeak2` may be faster because it does the operation in a single step instead of 2.

Also to consider, the leak doesnt happen if the array is in the main loop and you call `CausesLeak` from the main loop. I am not sure why this is happening.

**Comment by Thormidable** [comment]
Hey guys, only just seen this last comment. 

That new workaround should suit me nicely. Will test it for speed in the next couple of days,

Thank you!

**Comment by WilliamTambellini** [comment]
This bug prevents us to upgrade to 3.5. 
Could anyone add a "due date" or expected release date to AF 3.5.1 ?
Tks

**Comment by pavanky** [comment]
@WilliamTambellini doesn't the workaround help?

**Comment by pavanky** [comment]
Fixed in hotfixes-3.5.1

**Comment by WilliamTambellini** [comment]
Hi all, I see a crash with AF 3.4 and I m using this kind of chain of rows/cols.
Is nt AF 3.4  also impacted by this bug ?
Kind
W.

**Comment by pavanky** [comment]
@WilliamTambellini Generally the bug fixes are not backported older branches (mostly because there hasn't been a request for it).

 But if you are stuck with 3.4 for various reasons you can talk to @umar456 about creating a custom installer.

Alternatively, this bug only comes into play when you use `A.rows(x).cols(y)`. The simpler thing to do would be to use `A(x, y)` which shouldnt have this issue.

**Comment by WilliamTambellini** [comment]
Hi @pavanky  
I m using
af::array(data_.rows(i,i+p)).cols(j, j+q)
- can I use indexes/af::seq to do that ?
- do you confirm the bug is also in AF 3.4 ?
Cheers

**Comment by pavanky** [comment]
@WilliamTambellini 

code:
```
int main()
{
    af::array a = af::randu(5,5);
    int p = 3;
    int q = 2;
    // do this outside the loop                                                                                                                                                                                      
    af::seq pseq(p);
    af::seq qseq(q);
    af_print(a);

    for (int i = 0; i < 2; i++) {
        for (int j = 0; j < 2; j++) {
             // use double(i), double(j) to avoid warnings.
            af::array b = a(double(i) + pseq,
                            double(j) + qseq);
            af_print(b);
        }
    }
}
```

results:
```
a
[5 5 1 1]
    0.6010     0.7273     0.8704     0.9950     0.7472
    0.1195     0.4348     0.2977     0.8682     0.7051
    0.2643     0.9311     0.9509     0.1268     0.2490
    0.3945     0.1210     0.9859     0.2600     0.3395
    0.2261     0.5332     0.1123     0.7460     0.7763

b
[3 2 1 1]
    0.6010     0.7273
    0.1195     0.4348
    0.2643     0.9311

b
[3 2 1 1]
    0.7273     0.8704
    0.4348     0.2977
    0.9311     0.9509

b
[3 2 1 1]
    0.1195     0.4348
    0.2643     0.9311
    0.3945     0.1210

b
[3 2 1 1]
    0.4348     0.2977
    0.9311     0.9509
    0.1210     0.9859
```

**Comment by pavanky** [comment]
@WilliamTambellini 

> do you confirm the bug is also in AF 3.4 ?

I haven't personally tested this, but the code changed in this pr hasn't been modified in a long time.

**Comment by WilliamTambellini** [comment]
Ok thanks @pavanky. Trying ...

**Comment by WilliamTambellini** [comment]
So, I ve valgrinded before and after doing the change and in both case valgrind does not find any leak. Anyway, seems simply safer with AF 3.4 not to use .rows().cols() but indexing with seq.
Thank you @pavanky 
W.

**Comment by pavanky** [comment]
@WilliamTambellini I am not sure valgrind can catch this (especially if you are not using CPU backend). A simple solution would be to put `af::printMemInfo()` and see if the number of locked buffers are increasing.

**Comment by WilliamTambellini** [comment]
ok thanks P.
