### ISSUE TITLE
Modify FindArrayFire.cmake to resolve dependencies without using other cmake module scripts

### ISSUE THREAD

**Issue by 9prady9** [arrayfire/arrayfire#187]
Dependency Find*.cmake scripts shouldn't needed when ArrayFire is being used by third party applications or libraries, preferably. The same script can be modified to check for necessary dependencies in expected locations, but these changes would be smaller compared to carrying all Find*.cmake scripts where ever ArrayFire goes..

**Comment by bkloppenborg** [comment]
These issues were addressed by #470 .
