### ISSUE TITLE
ReadinG DCOM image files

### ISSUE THREAD

**Issue by QuantScientist** [arrayfire/arrayfire#1878]
Hi,
I am trying to replicate this Kaggle example: https://www.kaggle.com/ankasor/improved-lung-segmentation-using-watershed but using ArrayFire. 

I looked around and couldn't find anything related to that here. I did find other C++/Python libs to read DCOM files, but I want to do everything using ArrayFire. Has anyone done anything like this or will I have to write this on my own? 

Thanks,

**Comment by 9prady9** [comment]
Sorry about the extreme delay, we missed this one. ArrayFire uses freeimage to load images which doesn't support DCOM format yet as far as I know. The work around is to write a DCOM loader or most likely use DCOM loader library.

We may eventually add DCOM loading capability, perhaps as a plugin to https://github.com/arrayfire/arrayfire-extras repository.
