### ISSUE TITLE
Sparse - dense Matmul with transpose

### ISSUE THREAD

**Issue by Tmbao** [arrayfire/arrayfire#1884]
Hello,

I used af::matmul to multiply a sparse matrix and a dense one.

```cpp
#include <arrayfire.h>

int main() {
  auto a = af::sparse(af::randu(10, 20));
  auto b = af::randu(10); 
  af_print(af::matmul(a, b, true, false));
}
```

As sparse matrix type doesn't support transpose, I used the transpose params in the matmul function. However, it threw
```
libc++abi.dylib: terminating with uncaught exception of type af::exception: ArrayFire Exception (Invalid input size:203):
In function af_err af_matmul(af_array *, const af_array, const af_array, const af_mat_prop, const af_mat_prop)
In file src/api/c/blas.cpp:139
Invalid dimension for argument 1
Expected: lhsInfo.dims()[aColDim] == rhsInfo.dims()[bRowDim]
```

Did I use the matmul function correctly?

**Comment by pavanky** [comment]
@Tmbao what's the output of `af::info()` ?

**Comment by pavanky** [comment]
@Tmbao The options for `af::matmul` is an enum. Using bool is causing the issue. try using `af::matmulTN(a, b)` or `af::matmul(a, b, AF_MAT_TRANS, AF_MAT_NONE);`.

This is not a bug.
