### ISSUE TITLE
Crash in af_assign_seq() on AWS P2 K80

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#1887]
Hi all
I m experimenting a crash at least with AF 3.4 with nvidia driver 375.66. Cannot reproduce with older versions like 375.39.
My code (a1 and a2 are 2 dense af arrays):
 a1( af::seq(i, i+a2.dims(0)-1), af::seq(j, j+a2.dims(1)-1) ) = a2;

The bt:
`
(gdb) bt
#0  0x00007f389cae52cc in ?? () from /usr/lib/nvidia-375/libnvidia-ptxjitcompiler.so.375.66
#1  0x00007f389cb2c77d in ?? () from /usr/lib/nvidia-375/libnvidia-ptxjitcompiler.so.375.66
#2  0x00007f389cb2ef4c in ?? () from /usr/lib/nvidia-375/libnvidia-ptxjitcompiler.so.375.66
#3  0x00007f389ccc5b60 in ?? () from /usr/lib/nvidia-375/libnvidia-ptxjitcompiler.so.375.66
#4  0x00007f389cd5ca74 in ?? () from /usr/lib/nvidia-375/libnvidia-ptxjitcompiler.so.375.66
#5  0x00007f389cbaeb3e in ?? () from /usr/lib/nvidia-375/libnvidia-ptxjitcompiler.so.375.66
#6  0x00007f389ccd8e36 in ?? () from /usr/lib/nvidia-375/libnvidia-ptxjitcompiler.so.375.66
#7  0x00007f389ccd9c9e in ?? () from /usr/lib/nvidia-375/libnvidia-ptxjitcompiler.so.375.66
#8  0x00007f389c855eee in ?? () from /usr/lib/nvidia-375/libnvidia-ptxjitcompiler.so.375.66
#9  0x00007f389c85d588 in ?? () from /usr/lib/nvidia-375/libnvidia-ptxjitcompiler.so.375.66
#10 0x00007f389ce57f9d in ?? () from /usr/lib/nvidia-375/libnvidia-ptxjitcompiler.so.375.66
#11 0x00007f389c860c24 in ?? () from /usr/lib/nvidia-375/libnvidia-ptxjitcompiler.so.375.66
#12 0x00007f389c862391 in ?? () from /usr/lib/nvidia-375/libnvidia-ptxjitcompiler.so.375.66
#13 0x00007f389c858aec in __cuda_CallJitEntryPoint () from /usr/lib/nvidia-375/libnvidia-ptxjitcompiler.so.375.66
#14 0x00007f3a00e745c2 in fatBinaryCtl_Compile () from /usr/lib/nvidia-375/libnvidia-fatbinaryloader.so.375.66
#15 0x00007f3a047c8ee2 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#16 0x00007f3a047be08b in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#17 0x00007f3a047be639 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#18 0x00007f3a0480ee8d in cuLinkAddData_v2 () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#19 0x00007f3a14da3845 in ?? () from /home/ubuntu/tmp/xmt3/libafcuda.so.3
#20 0x00007f3a14da9829 in ?? () from /home/ubuntu/tmp/xmt3/libafcuda.so.3
#21 0x00007f3a14db16b5 in ?? () from /home/ubuntu/tmp/xmt3/libafcuda.so.3
#22 0x00007f3a14db1e5c in ?? () from /home/ubuntu/tmp/xmt3/libafcuda.so.3
#23 0x00007f3a14d40d16 in ?? () from /home/ubuntu/tmp/xmt3/libafcuda.so.3
#24 0x00007f3a14fcc390 in ?? () from /home/ubuntu/tmp/xmt3/libafcuda.so.3
#25 0x00007f3a14e21559 in ?? () from /home/ubuntu/tmp/xmt3/libafcuda.so.3
#26 0x00007f3a14e234fa in ?? () from /home/ubuntu/tmp/xmt3/libafcuda.so.3
#27 0x00007f3a14e3784e in af_assign_seq () from /home/ubuntu/tmp/xmt3/libafcuda.so.3
#28 0x00007f3a564e3fcf in af_err unified::AFSymbolManager::call<void**, void*, unsigned int, af_seq const*, void*>(char const*, void**, void*, unsigned int, af_seq const*, void*) () from /home/ubuntu/tmp/xmt3/libaf.so.3
#29 0x00007f3a564dd817 in af_assign_seq () from /home/ubuntu/tmp/xmt3/libaf.so.3
#30 0x00007f3a14e3a602 in af_assign_gen () from /home/ubuntu/tmp/xmt3/libafcuda.so.3
#31 0x00007f3a564e5bff in af_err unified::AFSymbolManager::call<void**, void*, long long, af_index_t const*, void*>(char const*, void**, void*, long long, af_index_t const*, void*) () from /home/ubuntu/tmp/xmt3/libaf.so.3
#32 0x00007f3a564dee67 in af_assign_gen () from /home/ubuntu/tmp/xmt3/libaf.so.3
#33 0x00007f3a5656959b in af::array::array_proxy::operator=(af::array const&) () from /home/ubuntu/tmp/xmt3/libaf.so.3
`

**Comment by pavanky** [comment]
If it is a problem with a particular driver version, I don't know why this is an arrayfire issue.

**Comment by WilliamTambellini** [comment]
corrected with latest investigation: always crash on AWS P2 CentOS7 whatever the nvidia drivers.

**Comment by pavanky** [comment]
Please provide reproducible code. If not there's no way to investigate this.

**Comment by pavanky** [comment]
Issue can be reopened if there's reproducible code.
