### ISSUE TITLE
Documentation: Introduction to vectorization

### ISSUE THREAD

**Issue by JosefJerabek** [arrayfire/arrayfire#1900]
https://arrayfire.com/introduction-to-vectorization/
"The details of this vectorization method can be found in the [GFOR documentation](https://arrayfire.com/introduction-to-vectorization/page_gfor.htm#gfor)." ... The mentioned link is invalid.

**Comment by 9prady9** [comment]
@JosefJerabek They should be fixed now, please check. Sorry for the inconvenience.
