### ISSUE TITLE
gfor example matmul failed

### ISSUE THREAD

**Issue by JosefJerabek** [arrayfire/arrayfire#1901]
The code in example for gfor http://arrayfire.org/docs/page_gfor.htm (most bottom) fails.
```
// BEFORE
gfor (seq k, 400) {
  array B = A(span,k);
  C(span,span,k) = matmulNT(B * B);  // outer product expansion runs out of memory
}
```
Error message: matmul can not be used in batch mode

**Comment by pavanky** [comment]
This is being fixed in https://github.com/arrayfire/arrayfire/pull/1898

**Comment by 9prady9** [comment]
Addressed batched matmul in https://github.com/arrayfire/arrayfire/pull/1898
