### ISSUE TITLE
VC++ nagging warning C4275 on af::exception

### ISSUE THREAD

**Issue by hokiedsp** [arrayfire/arrayfire#1906]
Hi,

Compiling my program with Visual Studio 2017, I get this nagging warning from "af/exception.h" header file:

"warning C4275: non dll-interface class 'std::exception' used as base for dll-interface class 'af::exception"

I doesn't appear to be anything major, but just in case...

Thanks

**Comment by pavanky** [comment]
This is a warning that an be ignored: https://msdn.microsoft.com/en-us/library/3tdb471s.aspx

> C4275 can be ignored in Visual C++ if you are deriving from a type in the Standard C++ Library, compiling a debug release (/MTd) and where the compiler error message refers to _Container_base.

You can disable this in userland using `#pragma warning` 
 https://stackoverflow.com/questions/7159348/disable-single-warning-error
