### ISSUE TITLE
JIT Issue on Tegra TX Devices

### ISSUE THREAD

**Issue by 9prady9** [arrayfire/arrayfire#1910]
NVRTC is failing to compile the kernel strings on tegra devices.

```
C++ exception with description "ArrayFire Exception (Internal error:998):
In function std::vector<char> cuda::compileToPTX(const char*, std::__cxx11::string)
In file src/backend/cuda/jit.cpp:264
NVRTC Error(7): NVRTC_ERROR unknown
```
Reported [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/arrayfire-users/vY-Iex7kuE0/EGQ4SxhQBAAJ) initially. We are also able to reproduce this on our side. [Build server log](http://ci.arrayfire.org/job/arrayfire-tegrax1/job/test/job/devel/49/console).

**Comment by HoneyPatouceul** [comment]
Seems this happened with last release of cuda 8.0.84 in L4T R28.1.
It was working on my TX2 with L4T R27.0.1 having cuda  8.0.64-1 (although several tests were failing).

Is there any know workaround ?

**Comment by pavanky** [comment]
@HoneyPatouceul I suggest sticking with 3.4.2 for now. There is a plan to backport bug fixes from 3.5 to 3.4 at some point.

**Comment by HoneyPatouceul** [comment]
I have the same error with my 3.4.2 archives, as with last version pulled from github.
Seems related to cuda version or some different installed libraries.
Any idea, apart from trying to install an older cuda8 package on my TX2 ?

**Comment by pavanky** [comment]
@HoneyPatouceul I am not really sure there is a work around..
