### ISSUE TITLE
Large array manipulation error (python)

### ISSUE THREAD

**Issue by blazzter** [arrayfire/arrayfire#1913]
I have a large 4D array, i.e.:

`array = af.randu(200,200,200,200)
`

the following operation fails:

`array[:,:,10,10] += 1.0
`

with:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/usr/lib/python3.6/site-packages/arrayfire/array.py in __setitem__(self, key, val)
   1152                                                   self.arr, c_dim_t(n_dims), inds.pointer,
-> 1153                                                   other_arr))
   1154             safe_call(backend.get().af_release_array(self.arr))

/usr/lib/python3.6/site-packages/arrayfire/util.py in safe_call(af_error)
     78         backend.get().af_get_last_error(c_pointer(err_str), c_pointer(err_len))
---> 79         raise RuntimeError(to_str(err_str))
     80 

RuntimeError: In function af_err af_assign_seq(void**, af_array, unsigned int, const af_seq*, af_array)
In file src/api/c/assign.cpp:147




During handling of the above exception, another exception occurred:

IndexError                                Traceback (most recent call last)
<ipython-input-21-8e58703ec4d9> in <module>()
----> 1 array[:,:,10,10] += 1.0

/usr/lib/python3.6/site-packages/arrayfire/array.py in __setitem__(self, key, val)
   1158 
   1159         except RuntimeError as e:
-> 1160             raise IndexError(str(e))
   1161 
   1162     def to_ctype(self, row_major=False, return_shape=False):

IndexError: In function af_err af_assign_seq(void**, af_array, unsigned int, const af_seq*, af_array)
In file src/api/c/assign.cpp:147

```

Device memory is on 7GB, well bellow 11GB available, if the array is randu 100^4, it works.
System is current archlinux with arrayfire from repositories.

af.info():
ArrayFire v3.5.0 (CUDA 64bit)
[0] : GeForce_GTX_1080_Ti (Compute 6.1)

**Comment by pavanky** [comment]
@blazzter This should be fixed in v3.5 and master branches. Can you try building from source ? If you want to wait v3.5.1 should be released in a few days.

**Comment by blazzter** [comment]
I will probably wait it out, tried to compile (from PKGBUILD in arch) but having problems (at forge-ext step)..

```
-- Check for working C compiler: /usr/bin/gcc-5 -- broken
CMake Error at /usr/share/cmake-3.9/Modules/CMakeTestCCompiler.cmake:51 (message):
  The C compiler "/usr/bin/gcc-5" is not able to compile a simple test
  program.
```

**Comment by blazzter** [comment]
I had some compilation problems .. could I suggest an edit in wiki here? 

The line `cmake ..` should include a note to use `CC=/usr/bin/gcc5 CXX=/usr/bin/g++5 cmake ..`
if CUDA is needed.

This would save me probably 2 weeks of my life over last 2 years. As a sort of non-programmer (based in physics) trying to figure things out using PKGBUILDs or git approach shown in wiki never gave me anything. I noticed this in @pavanky comment in [https://github.com/arrayfire/arrayfire/pull/1861](url).
This would make your library more approachable to physics programming, where some ppl like me scrape the internet for any kind of info. 
(arrayfire is absolute killer for any matrix/imaging big data related programming :1st_place_medal: )

**Comment by blazzter** [comment]
with master branch the command works, thanks

**Comment by pavanky** [comment]
@blazzter Sorry about that. I am going to modify arrayfire in AUR to build the master branch. I can modify the instructions on the wiki as well.

If you have questions about using arrayfire, feel free to join the slack channel: https://join.slack.com/t/arrayfire-org/shared_invite/MjI4MjIzMDMzMTczLTE1MDI5ODg4NzYtN2QwNGE3ODA5OQ

**Comment by blazzter** [comment]
cool thanks!
