### ISSUE TITLE
Why login + register to download?

### ISSUE THREAD

**Issue by mgsloan** [arrayfire/arrayfire#1916]
Sorry, I realize this is probably the wrong spot.  But having a registration and login page to download the binaries for arrayfire is not so cool.  Maybe I can understand wanting email addresses, but a huge registration form?  Nope, not filling that out, not going to expect the users of my application to fill that out.  Going to find a different approach than using arrayfire.

**Comment by janisozaur** [comment]
What?

I's readily available:
* https://github.com/arrayfire/arrayfire/releases
* https://www.archlinux.org/packages/community/x86_64/arrayfire/

**Comment by pavanky** [comment]
In addition to that Ubuntu, Debian, Gentoo and Homebrew (for osx) also package arrayfire. You can also build arrayfire yourself.

**Comment by mgsloan** [comment]
Here's what happened:

* From https://github.com/arrayfire/arrayfire-rust
* Followed "Download and install binaries" link, got here: https://arrayfire.com/download-splash/?redirect_to=/download
* See this:
![2017-09-02_776x382_scrot](https://user-images.githubusercontent.com/22570/29999309-32e907a2-8ff8-11e7-8f14-319593865ecf.png)
* Click "Login to Download", find that you can't login + register in one step.
* Go to Register, get this:

![2017-09-02_1330x1221_scrot](https://user-images.githubusercontent.com/22570/29999313-51aab276-8ff8-11e7-9e6a-3cdae774a4a1.png)

Yep, that's how you discourage your software getting used, y putting up barriers.  I realize that, but I have to consider the overhead for anyone else developing on this.  I don't really need arrayfire's unique features, just a decent way to do convolutions and similar filters.  It seems quite cool btw, sorry for ragging on this, I just hate to see a decent looking project sabotage its own adoption.

> It's readily available:
> * https://github.com/arrayfire/arrayfire/releases

Those are just source distributions, not binary

> In addition to that Ubuntu, Debian, Gentoo and Homebrew (for osx) also package arrayfire. You can also build arrayfire yourself.

True, but the latest in apt seems to be 3.2.2, at least for ubuntu 16.04.  The latest rust bindings use 3.5

**Comment by pavanky** [comment]
This is the installer the ci server uses: http://ci.arrayfire.org/userContent/Linux/ArrayFire-v3.5.0_Linux_x86_64.sh

Feel free to download it directly.

**Comment by mgsloan** [comment]
@pavanky Thanks!
