### ISSUE TITLE
Add a wrapper to start/stop backend profiler

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#1919]
Would be convenient for AF to offer a wrapper to play with the backend profiler (if any).
Example for CUDA:
https://devblogs.nvidia.com/parallelforall/cuda-pro-tip-generate-custom-application-profile-timelines-nvtx/

For example: 
af::startProfile(const std::string& rangeName);
af::stopProfile(const std::string& rangeName);

![](http://devblogs.nvidia.com/parallelforall/wp-content/uploads/2013/09/init_host_data_nvtx.png)

**Comment by umar456** [comment]
I have thought about this several times but this is out of the scope for the library. First of all, I am not aware of an OpenCL equivalent and even if there was it would need to support all manufacturers. Secondly, this functionality would be tool specific. It will need to be implemented for Intel tools, AMD tools, etc. Also, something like this is trivial to implement in user code. This function would add little benefit to most users.
