### ISSUE TITLE
Update Windows Build dependencies for VS2015

### ISSUE THREAD

**Issue by fzimmermann89** [arrayfire/arrayfire#1937]
The link in the Windows build instructions on the wiki for the dependencies is out of date, the ci builds use versions compiled for vs2015 (vs2013 doesnt compile AF because of local thread store).
Could you supply the versions used by your CI builds?
Thanks

**Comment by pavanky** [comment]
@mlloreda ?

**Comment by mlloreda** [comment]
Thank you for bringing this to our attention, @fzimmermann89. Please check the link again for the proper VS2015 dependencies.
