### ISSUE TITLE
Forge on Ubuntu could not start.

### ISSUE THREAD

**Issue by BookmanHan** [arrayfire/arrayfire#1938]
I install arrayfire and VNC server on Ubuntu Server.
I login in VNC, then execute my codes.

There is the wrong information:
```
ERROR: GLFW wasn't able to initalize
OpenGL context creation failed
Not a valid window
Not a valid window
Not a valid window
```

How should I do?

**Comment by 9prady9** [comment]
@BookmanHan Have you been able to run any GLFW examples ? I believe this is related to your server setup, does it have any display attached ?

**Comment by 9prady9** [comment]
@BookmanHan I am closing this issue as you have acknowledged this is a setup related issue on [upstream graphics library github issue](https://github.com/arrayfire/forge/issues/151#issuecomment-333292164).
