### ISSUE TITLE
af::array::scalar<T> produces wrong numbers

### ISSUE THREAD

**Issue by FloopCZ** [arrayfire/arrayfire#1949]
## Current behavior:
When using `a.scalar<double>()` on an array of type `af::dtype::f32`, the result is wrong.

## Expected behavior:
`scalar<T>` should behave similarly to e.g., `af::sum<T>` and `af::mean<T>` and produce a correct result even if the array dtype and the C++ type do not match or throw an exception.

## Code to reproduce the issue:
```c++
#include <arrayfire.h>
#include <iostream>
int main()
{
    af::setBackend(AF_BACKEND_CPU);
    af::info();
    af::array a = af::constant(0.2, 1, af::dtype::f32);
    std::cout << "sum: " << af::sum<double>(a) << '\n';
    std::cout << "float scalar: " << a.scalar<float>() << '\n';
    std::cout << "double scalar: " << a.scalar<double>() << '\n';
}
```

Output:
```
ArrayFire v3.5.0 (CPU, 64-bit Linux, build 05999f3)
[0] Intel: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz, 15988 MB, Max threads(8)
sum: 0.2
float scalar: 0.2
double scalar: 5.16408e-315
```

## Arrayfire version:
ArrayFire v3.5.0 (CPU, 64-bit Linux, build 05999f3)
Tested on CPU and CUDA backends.

**Comment by 9prady9** [comment]
`sum<T>` is doing a reduction operation and the template parameter you give to it is the output variable's type. Thus, whatever the result of reduction is cast to the user provide template type.

`scalar<T>` on the other hand is trying to read the first element of the array a.k.a the first element in the GPU data. In your case, the af::array is of type `f32`(float) while you are trying to access it as double. `scalar` method doesn't handle the type coercion here. You have to do that explicitly as follows.

`(double)a.scalar<float>()`.

Having said that, please do note that scalar is made available for debugging purposes and it is quite expensive call.

**Comment by pavanky** [comment]
@9prady9 This shouldn't fail silently. This should throw an exception or return the correct value by copying implicitly.

**Comment by 9prady9** [comment]
@FloopCZ We have fixed the type check in the PR https://github.com/arrayfire/arrayfire/pull/1951

**Comment by FloopCZ** [comment]
Thank you, the type check is definitely useful. Anyway, I still suggest to consider the automatic type conversion including the check whether the array is actually a scalar. Why?

Consider a function like this:

```c++
double time_to_the_end_of_universe(af::dtype dt)
{
    // complex arrayfire computation, transparent to the user of my library
    af::array result = ...;
    return ???;
}
```

Intuitively, I would replace `???` by `result.scalar<double>()` which will, however:
- Throw an exception if the computation is performed with `af::dtype::f32` for no obvious efficiency reason, since the `scalar` function returns the value by value anyway. This makes runtime selection of `dtype` unnecessarily complicated.
- It is discouraged in the documentation because of performance reasons.

So I will probably replace `???` by `af::sum<double>(result)`, which will always work, however, it is even worse:
- It is not intuitive to the reader of the code, since I don't actually want to sum anything.
- Even though the documentation warns about the inefficiency of the `scalar` function, the `sum` has the same performance in the best case (and usually, it is even slightly slower).
- If I made a mistake and the result is not a scalar, the program will quietly produce a wrong result without a shape mismatch error.

This is a food for thought, but all the aforementioned issues would be solved if the `scalar` function would check whether the array is a scalar and than properly return the single value as the type selected by the user. And returning a double from a program is (at least in my case) a very usual computational endpoint.

If I am missing something (which is very possible), please let me know.

Note:
The benchmark of `sum` vs `scalar`:
```c++
#include <arrayfire.h>
#include <iostream>
int main()
{
    af::setBackend(AF_BACKEND_CUDA);
    af::info();

    af::array a = af::constant(0.2, 1, af::dtype::f64);
    af::sync();

    af::timer::start();
    double d = 0;
    for (int i = 0; i < 1000000; ++i) {
        d += a.scalar<double>();
    }
    std::cout << "scalar: " << af::timer::stop() << std::endl;

    af::timer::start();
    d = 0;
    for (int i = 0; i < 1000000; ++i) {
        d += af::sum<double>(a);
    }
    std::cout << "sum: " << af::timer::stop() << std::endl;
}
```
```
[0] Intel: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz, 15988 MB, Max threads(8)
scalar: 4.59234
sum: 4.71377
```

**Comment by pavanky** [comment]
@FloopCZ 

Even though it works in your case there's a lot of cases supporting automatic conversion results in loss of precision. For example if your array was int64 and asked for int32, asking this may result in silently getting incorrect values.

The `sum<double>` function was done without too much consideration for these cases. But breaking that behavior now would be more harmful than otherwise.

That said you can implement your own function shown below to do this i you wish to. This is exactly what arrayfire would have done internally anyway.

```
template<typename T>
T getScalar(const array &arr)
{
  T result;
  switch (arr.type()) {
    case f32: result = arr.scalar<float>(); break;
    case f64: result = arr.scalar<double>(); break;
    // handle other types
    default: throw af::exception("Unsupported data type");
  }
}
```

**Comment by FloopCZ** [comment]
@pavanky Thanks, I see your point. Considering `sum<T>`, it did not occur to me that loss of precision may be an issue. You are probably right that such a change would be too harmful for the upstream users even if arrayfire would just check for lossless conversions. Maybe one day in some major release. :-)
