### ISSUE TITLE
Opencl error "double requires cl_khr_fp64" on Nvidia fermi

### ISSUE THREAD

**Issue by fzimmermann89** [arrayfire/arrayfire#1952]
The following tests fail for datatype=double using a GTX 580 (fermi, opencl 1.1) on windows 7

- cholesky_dense_opencl
- inverse_dense_opencl
- lu_dense_opencl
- solve_dense_opencl

> 
> [----------] 2 tests from Inverse/2, where TypeParam = double
> [ RUN      ] Inverse/2.Square
> OpenCL error -59 on line 1192
> OpenCL error -59 on line 1365
> OpenCL error -11 on line 228
> clBuildProgram Failed
> err = -11
> Error: Failed to build program executable!
> 
> Build Log:
> 
> <kernel>:14:11: error: use of type 'double' requires cl_khr_fp64 extension to be enabled
>  __global double const * restrict A, 
>           ^
> <kernel>:16:11: error: use of type 'double' requires cl_khr_fp64 extension to be enabled
>  __global double *d_dinvA, 
>           ^
> <kernel>:21:2: error: use of type 'double' requires cl_khr_fp64 extension to be enabled
>  double Ystx = 0;
>  ^
> <kernel>:22:10: error: use of type 'double' requires cl_khr_fp64 extension to be enabled
>  __local double *y = 0;
>          ^
> <kernel>:23:2: error: use of type 'double' requires cl_khr_fp64 extension to be enabled
>  double switcher;
>  ^
> <kernel>:24:2: error: use of type 'double' requires cl_khr_fp64 extension to be enabled
>  double neg_switcher;
>  ^
> <kernel>:29:17: error: use of type 'double' requires cl_khr_fp64 extension to be enabled
>  __global const double *Aoff = A + bx*lda*BLOCK_SIZE + bx*BLOCK_SIZE;
>                 ^
> <kernel>:32:10: error: use of type 'double' requires cl_khr_fp64 extension to be enabled
>  __local double Bs[BLOCK_SIZE*BLOCK_SIZE];
>          ^
> <kernel>:33:10: error: use of type 'double' requires cl_khr_fp64 extension to be enabled
>  __local double workspace[BLOCK_SIZE]; 
>          ^
> 
> OpenCL error -45 on line 253
> OpenCL error -48 on line 132
> OpenCL error -48 on line 990
> OpenCL error -48 on line 992
> OpenCL error -48 on line 994
> OpenCL error -48 on line 996
> OpenCL error -48 on line 998
> OpenCL error -48 on line 1000
> OpenCL error -48 on line 1008
> OpenCL error -48 on line 1368
> OpenCL error -59 on line 1192
> OpenCL error -59 on line 1365
> OpenCL error -11 on line 228
> clBuildProgram Failed
> err = -11
> Error: Failed to build program executable!
> 
> 

[clinfo.txt](https://github.com/arrayfire/arrayfire/files/1366854/clinfo.txt)

**Comment by umar456** [comment]
Interesting. Looks like you are using CUDA 9 which has dropped support for the Fermi cards. I wonder if that applies to OpenCL as well. It would have to be supported if those are the only tests that are failing.

**Comment by fzimmermann89** [comment]
I am building with version 8 of the CUDA SDK, most of the CUDA test are passing (most of the failures seem to be intentional decisions to remove fermi support by deleting code path on your side and easy fixable for now).

This issue is with OpenCL 1.1 which needs to have cl_khr_fp64 enabled to support double. Most of the kernels are correctly build with this option. It seems the underlying kernels which affect the test are part of CLBlas, which seems to have a way of specifiying the pragma by defining DOUBLE_PRECISION (see https://github.com/clMathLibraries/clBLAS/blob/master/src/library/blas/gens/clTemplates/dtrsm_gpu.cl#L17) 

I don't know how the kernels are build and where the option has to be enabled..

**Comment by fzimmermann89** [comment]
The following Test fail as well:
- Test_mean_opencl
- Test_var_opencl
- Test_stdev_opencl
- Test_covariance_opencl
all fail for (u)int64 and input>4096

Imho the reason is similar :
All those functions use the mean kernel, which fails to build because cl_khr_fp64 is not enabled.
- In https://github.com/arrayfire/arrayfire/blob/v3.5/src/backend/opencl/kernel/mean.hpp#L176 is a check that enables it if the **input** type is double. -
- But in  https://github.com/arrayfire/arrayfire/blob/master/src/backend/opencl/mean.cpp#L62 the **output** type for (u)int64 is set to double which is not covered.

**Comment by pavanky** [comment]
I am not sure ArrayFire fully supports OpenCL 1.1 anymore.

**Comment by fzimmermann89** [comment]
Right now it doesn't ;) ´
It would be a nice decision to keep supporting Fermi: Those cards have a great fp64/$ value and are therefore still quite common. I can kind of understand why you decided to remove the cuda support (even if it's not strictly necessary as long as you are using cuda 8), but keeping at least opencl 1.1 support doesn't seem like a huge commitment

**Comment by pavanky** [comment]
@fzimmermann89 This was a forced decision because upstream libraries (clBLAS / clFFT) no longer supported OpenCL 1.1

**Comment by fzimmermann89** [comment]
Right now the support in arrayfire is still almost there, and clblas at least has a explicit method of enabling the necessary pragma.
  So it's your decision whether you want to use it and keep supporting opencl 1.1 in your own code

**Comment by fzimmermann89** [comment]
The fix for the statistic functions is quite easy, see PR
The fix for the blas functions is to use clblast, which supports opencl1.1 (after fixing the issues with clblast integration)

After those fixes an opencl1.1 devices can hopefully pass all tests

**Comment by fzimmermann89** [comment]
There is another issue: The bilataral_opencl test fails for double.
In arrayfire/src/backend/opencl/kernel/bilateral.cl exp_native is used for double inputs. But this is not specified in either of the OpenCL specifications even though some implementations seem to support it - Fermi does not ;)

@pavanky already found this issue for POCL (pocl/pocl#385) and @shehzan10 for apple. The current solution is checking for those two platforms before enabling native_exp https://github.com/arrayfire/arrayfire/blob/125100705e4e47e1854735feebce891c103a1b0c/src/backend/opencl/kernel/bilateral.hpp#L52

Maybe there is a better way of fixing it instead of just checking for the platform. If it's not specified I would suggest not using it if USE_DOUBLE is defined. I don't know how to check for existence of native_exp(double)

**Comment by pavanky** [comment]
@fzimmermann89 Can you create a new issue for bilateral ? I merged in your changes for fixing the double precision issue.
