### ISSUE TITLE
glbindings are no longer build on windows

### ISSUE THREAD

**Issue by fzimmermann89** [arrayfire/arrayfire#1953]
After #1861 glbindings are no longer build on windows. The call to build_glbinding was removed. Is this intentional?

**Comment by pavanky** [comment]
@umar456 ?

**Comment by umar456** [comment]
Yes. I want to remove the building of external libraries from the build system. glbinding seems to be pretty easy to obtain and setup on the system. If you download the installer or build it on your system, CMake will be able to find this library automatically. I would like to remove the building of other libraries from ArrayFire and create a separate CMake script that can be used to set up the external dependencies correctly. Let me know if you run into any issues on your system.

**Comment by fzimmermann89** [comment]
ok, thank you. 
(please consider updating your build instructions)
