### ISSUE TITLE
Always get an error after every program is closed

### ISSUE THREAD

**Issue by antibes0415** [arrayfire/arrayfire#1954]
Hi. why do I always get an error after exiting every program, no matter the examples you provided or the programs I write ?
The error message is something like: xxx.exe has stopped working
Maybe the memory is not released in graphic card after exiting the program ?
FYI:
I use the OpenCL backend.
The arrayfire aversion is 3.5.0.
My computer:
i7-4800MQ
Windows 7 Enterprise SP1
Quadro K3100M

Thanks a lot if you can solve this big issue.

**Comment by umar456** [comment]
Can you post the version of the driver you are using? We have noticed issues with the 37x drivers on Windows.

**Comment by antibes0415** [comment]
Hi, my driver version is 385.08

**Comment by umar456** [comment]
Can you try the newest version([v3.5.1](https://arrayfire.com/download/))? We made a couple of changes recently which address those issues.

**Comment by antibes0415** [comment]
Hi. I have tried v3.5.1. My issues seem to be solved :). But my colleague met with the same issues with v3.5.1. His computer hardware is different from mine. He used two laptops and both have this problem.

His computer 1:
Intel HD 6600, Driver date 2016/4/8, version  10.18.14.4432
Windows 7 64bit
Computer 2:
GTX850M, driver version 22.21.13.8854 (385.54),  date:9/1/2017
Windows 10 64bit

Both use OpenCL as backend.

**Comment by antibes0415** [comment]
And for my computer and v3.5.1, I found that all the examples in machine learning folder failed. The program cannot run and pop up the error message "xxx.exe has stopped working". I tried other examples and they seem good up to now.
For my colleague's two laptops, all the examples he tried failed and has this error message ...
By the way, we all use the OpenCL backend.

**Comment by DrOreo** [comment]
Hello

I met the same issue.

Following is my info:
ArrayFire v3.5.1 (OpenCL, 64-bit Windows, build 0a675e8)
[0] NVIDIA: GeForce GTX 1050 Ti, 4096 MB
-1- INTEL: Intel(R) HD Graphics 630, 6492 MB
-2- INTEL: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz, 16252 MB

Thanks a lot if you can solve this issue.

**Comment by 9prady9** [comment]
@DrOreo Which examples are failing for you ? Are they giving sort of error message ? Have you tried setting [AF_PRINT_ERRORS=1](http://arrayfire.org/docs/configuring_environment.htm#af_print_errors) ?

**Comment by DrOreo** [comment]
@9prady9 

Thanks for your reply.

I have tried setting  AF_PRINT_ERRORS=1  in my system's environment variables, but the situation is still happen.

I use arrayfire in my own program, and everything is ok besides close program.
Even I just use the simple code like "af::array test(1,2);", the program still got error when closed.

following code is where the program error :   
extern "C" DECLSPEC_GUARD_SUPPRESS EXCEPTION_DISPOSITION __cdecl __CxxFrameHandler(
    EHExceptionRecord  *pExcept,         // Information for this exception
    EHRegistrationNode RN,               // Dynamic information for this frame
    CONTEXT            *pContext,        // Context info
    DispatcherContext  *pDC              // More dynamic info for this frame
) {
    FuncInfo                *pFuncInfo;
    EXCEPTION_DISPOSITION   result;
    EHRegistrationNode      EstablisherFrame = RN;

    _ImageBase = pDC->ImageBase;
    _ThrowImageBase = (uintptr_t)pExcept->params.pThrowImageBase;
    pFuncInfo = (FuncInfo*)(_ImageBase +*(PULONG)pDC->HandlerData);
    result = __InternalCxxFrameHandler( pExcept, &EstablisherFrame, pContext, pDC, pFuncInfo, 0, nullptr, FALSE );
    return result;
}

**Comment by 9prady9** [comment]
@DrOreo There is known issue with Intel OpenCL drivers where they cause this crash upon program exit while cleaning up resources. Can you remove the Intel OpenCL drivers(i.e. remove intel opencl runtime so that ArrayFire doesn't see Intel OpenCL devices) and then run the program ?

**Comment by DrOreo** [comment]
@9prady9 , I have removed  intel opencl runtime, and the ArrayFire doesn't see Intel OpenCL devices, like below : 
ArrayFire v3.5.1 (OpenCL, 64-bit Windows, build 0a675e8)
[0] NVIDIA: GeForce GTX 1050 Ti, 4096 MB.

But still got error when close program.

**Comment by DrOreo** [comment]
@9prady9 
Yes, this happen with helloworld examples, the code I modify like below:

int main(int argc, char *argv[])
{
	system("pause");   //test point(1)

	// Select a device and display arrayfire info
	int device = argc > 1 ? atoi(argv[1]) : 0;
	af::setDevice(device);
	af::info();

	af::array test(2, 3);    //test point(2)
	system("pause");      //test point(2)
	printf("Create a 5-by-3 matrix of random floats on the GPU\n");
	array A = randu(5, 3, f32);
	af_print(A);
................
}

When I closed program before test point(1), everything is ok obviously, but when I closed program after test point(1), before test point(2), the program got error.

And I got the other question about CUDA mode.
I turn the program to CUDA mode, the program is closed normally.
But the host memory increased about 500mb, just after test point(1) when I start use CUDA.

I appreciate for your reply and help.

**Comment by 9prady9** [comment]
@DrOreo 
Since it is windows, can you try stepping through the code using Visual Studio to see where exactly is the code being thrown off in the example. A stack trace would help a lot. 

It may be a long shot but if the code step through doesn't help, you can try updating your CUDA drivers to latest and see if that resolves the error. If it does not, then try a driver version previous to the one you currently have to narrow down if any driver version actually runs the code fine.

As for the CUDA backend memory usage, it is expected that some additional host memory will be used up by ArrayFire CUDA backend, I know its around 200-300MB on Linux, I would be expect that to be a little bit more on Windows, I can't place the exact figure at the moment although.

@antibes0415 Can you try getting us a stack trace of where exactly the code faults when you run examples using VS code step through. Thank you.

**Comment by 9prady9** [comment]
@antibes0415 Can you try getting us a stack trace of where exactly the code faults when you run examples using VS code step through. Thank you.

**Comment by carstenhag** [comment]
Hey, just downloaded arrayfire and wanted to try out some of the examples.

I've got Windows 10 x64 and a R9 290 with Radeon 18.2.1 Drivers. Here's the output of `clinfo`:
[clinfo.log](https://github.com/arrayfire/arrayfire/files/1708274/clinfo.log)


I've first ran the helloworld example binaries and all of those work fine. The binaries in the financial folder and the benchmarks folder (I've tested those, others will prob. crash too) all crash.
`Ausnahme ausgelöst bei 0x00007FFBA02B66BF (ntdll.dll) in heston_model_debug.exe: 0xC0000005: Zugriffsverletzung beim Lesen an Position 0x0000000000000010.`

Translated: Exception caused at 0x... Read conflic/error/damage at position 0x10.

I think I've got the same bug as OP. Seems like it doesn't depend on the GPU manufacturer.

Gonna try to step through one of the programs now.

**Comment by carstenhag** [comment]
Stepped through `heston_model`, and up until the `return 0` it was fine. After the breakpoint at that line it crashed.

**Comment by 9prady9** [comment]
@carstenhag Looks like it is the resource cleanup issue I was talking about in earlier comments. We didn't notice that on AMD or NVIDIA cards so far. We are going to release 3.6 soon. Hopefully, these at-exit crashes are not an issue on that. The reason I say hopefull is that, I have been playing around with examples from git master branch on Windows box and they seem to be working as expected without crash on exit.

I will udpate this issue as soon as we do the 3.6 release so everyone who experienced the at-exit crashes can test the examples against the latest release.

**Comment by christophe-murphy** [comment]
Closing old issue. If you are still having problems please open a new issue.
