### ISSUE TITLE
Make clblast the default OpenCL blas implementation.

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#1956]
As of now CLBLAST has more support than clBLAS. Some of the issues it would help with:

- https://github.com/arrayfire/arrayfire/issues/1673
- https://github.com/arrayfire/arrayfire/pull/1898

**Comment by pavanky** [comment]
@mlloreda @umar456 This would require changes to both CMake and the build system.

**Comment by fzimmermann89** [comment]
Currently there are at least to minor bugs regarding clbast

- https://github.com/arrayfire/arrayfire/blob/master/CMakeModules/build_CLBlast.cmake#L11
```
 SET(CLBlast_location ${prefix}/${CMAKE_STATIC_LIBRARY_PREFIX}/libclblast${CMAKE_STATIC_LIBRARY_SUFFIX})
```
should probably be 
`${prefix}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}clblast${CMAKE_STATIC_LIBRARY_SUFFIX})
`

- https://github.com/arrayfire/arrayfire/blob/master/src/backend/opencl/err_clblast.hpp

missing `#include <mutex>`

**Comment by fzimmermann89** [comment]
and It would make arrayfire support OpenCl 1.1 again...

**Comment by CNugteren** [comment]
Now that issue #1963 is solved, perhaps it is time to re-evaluate making CLBlast the default back-end? Any thoughts from your side?

**Comment by WilliamTambellini** [comment]
On my side I m interested by both fp16 and batched matmul which are supposed to be already implemented in CLBlast, right ?

**Comment by CNugteren** [comment]
Yes, CLBlast has FP16 and batched GEMM support, but that's not used by ArrayFire. Anyway, that's a separate issue: this is about making CLBlast the default. If you want to use ArrayFire with CLBlast, you can already do so today.

**Comment by WilliamTambellini** [comment]
Hi guys, 
Now that I think about that, switching from the "standard" clblas backend to the CLBlast one imposes today to rebuild/build twice and/or do some hacky libafopencl.so renaming. 
Would nt it be possible to simply create a new ArrayFire backend: for example:  "libafclblast.so" 

typedef enum {
    AF_BACKEND_DEFAULT = 0,  ///< Default backend order: OpenCL -> CUDA -> CPU
    AF_BACKEND_CPU     = 1,  ///< CPU a.k.a sequential algorithms
    AF_BACKEND_CUDA    = 2,  ///< CUDA Compute Backend
    AF_BACKEND_OPENCL  = 4,  ///< OpenCL Compute Backend
    AF_BACKEND_CLBLAST = 5 ///< CLBlast Compute Backend
} af_backend; 

?

**Comment by fzimmermann89** [comment]
I don't understand why a complete switch would make those necessary

**Comment by WilliamTambellini** [comment]
@fzimmermann89  There is a high probability that the clblas backend performs better on some devices and the "standard" clblas performs better on some others. Adding runtime flexibility and also safety in case one of these 2 does nt work in some cases.

**Comment by pavanky** [comment]
> There is a high probability that the CLBlast backend performs better on some devices and the "standard" clblas performs better on some others. Adding runtime flexibility and also safety in case one of these 2 does nt work in some cases.

Not sure how much work this would involve. May be we can implement a way to push additional libraries that unified backend can load? This way you can build two libafopencl libs and store them in separate locations. Then use something like:

```
int id = af::unified::pushLibrary("/path/to/another/libafopencl.so");
af::setBackend(id);
// do calculations
af::popLibrary(id);
```

Or something like this:

```
af::unified::loadLibrary("/path/to/another/libafopencl.so"); // This replaces the current loaded library
//use functions as needed
```

**Comment by pavanky** [comment]
@umar456 what do you think ^ ?

**Comment by 9prady9** [comment]
There is one consequence of allowing runtime switching between CLBlast and clBLAS - we would have to redistribute their runtime binaries along with our installers which we are not doing right now as clBLAS/CLBlast are consumed as static libraries by OpenCL backend.

**Comment by WilliamTambellini** [comment]
- build time : there is absolutely no doubt that for some configs (hardware/driver/OS) Blast is faster than blas but there is high probability that for some other configs clBLAS would do better than Blast. Is it consequently really worth it to try to save some minutes of build time compared to all the advantages of having 2 possible great backends, ie the best of openCL in any cases.
- installer size : it is not such a big drawback to add some MB to the AF installer : it's already 1GB, most would nt care about few additional hundred MB if that allows to get access to 2 OpenCL backends.
What is sure is that today I don't use at all the opencl AF backend because sometimes fast but sometimes not according to the local config/algo : I would certainly reconsider if I could switch at runtime (af unified) between Blast and Blas.

**Comment by sebastienleclaire** [comment]
I think adding a different backend (mention earlier by WilliamTambellini) would be the best idea from the user perspective. 
> typedef enum {
> AF_BACKEND_DEFAULT = 0, ///< Default backend order: OpenCL -> CUDA -> CPU
> AF_BACKEND_CPU = 1, ///< CPU a.k.a sequential algorithms
> AF_BACKEND_CUDA = 2, ///< CUDA Compute Backend
> AF_BACKEND_OPENCL = 4, ///< OpenCL Compute Backend
> AF_BACKEND_CLBLAST = 5 ///< CLBlast Compute Backend
> } af_backend;

Note that replacing a backend by another, which could potentially perform worse for some situations, look like, in my opinion, as a similar event to one that break the API. What I mean is that if some people are using ArrayFire with the current AF_BACKEND_OPENCL and are expecting a certain performance, taking the performance down for them could be really annoying.

On a side note, I would say that the size of the installer is not important, at least not now as the size of ArrayFire installer is rather very small in comparison to other apps that can be installed on a PC. 

Also advertising that ArrayFire support 1 more Backend implementation is good from a business perspective, this would potentially attract new users to the ArrayFire platform in the long run.

**Comment by WilliamTambellini** [comment]
I agree with @sebastienleclaire  
- size of the installer does nt matter
- anyone not interested by opencl could easilly delete locally their libafopencl and/or libafclblast libs
- no speed drop : the default for af unified to remain afopencl (if an opencl device found)
@pavanky  why closing ?

**Comment by pavanky** [comment]
@WilliamTambellini I dont have the time to look at this, but if someone wants to take this up I wouldnt mind.

**Comment by umar456** [comment]
The points you bring up really belong in another issue. This issue was concerned with a making clBlast the default backend which it has been and so it is addressed.

I don't think adding a different backend for selecting the BLAS implementation is a good idea. It can be handled with another API call within the OpenCL backend. Its not a priority for us at the moment and we welcome further discussion in another issue.

**Comment by WilliamTambellini** [comment]
Oh ok, I did nt know clblast was now the default afopencl. Cool tks.
