### ISSUE TITLE
Bilateral uses exp_native(double) even though it's not in the OpenCL specifications

### ISSUE THREAD

**Issue by fzimmermann89** [arrayfire/arrayfire#1966]
The bilataral_opencl test fails for double on Nvidia Fermi
In arrayfire/src/backend/opencl/kernel/bilateral.cl `exp_native` is used for double inputs. But this is not specified in either of the OpenCL specifications even though some implementations seem to support it, the Nvidia OpenCL implementation (at least for Fermi) doesn't

@pavanky already found this issue for POCL (pocl/pocl#385) and @shehzan10 for apple. The current solution is checking for those two platforms before enabling `exp_native` https://github.com/arrayfire/arrayfire/blob/125100705e4e47e1854735feebce891c103a1b0c/src/backend/opencl/kernel/bilateral.hpp#L52

Maybe there is a better way of fixing it instead of just checking for the platform?
I don't know if there is a way  to check for existence of `exp_native(double)`.
Because `expnative(double)` is not specified I would suggest not using it if USE_DOUBLE is defined.

**Comment by pavanky** [comment]
@fzimmermann89 I think you mean `native_exp` and it is part of the spec (since 1.0)
https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/exp.html

**Comment by fzimmermann89** [comment]
yes, sorry.
I meant `native_exp` with input type double.
"We use the generic type name gentype to indicate that the functions in table 6.9 can take
float, float2, float3, float4, float8 or float16 as the type for the
arguments." [opencl2.0-spec](https://www.khronos.org/registry/OpenCL/specs/opencl-2.0-openclc.pdf) p.79

The issue stands that it's not supported for input type double for some platforms without a clear way of checking for support.

**Comment by pavanky** [comment]
@fzimmermann89 Ah I see. Then feel free to send in a patch that disables native_exp for doubles!
