### ISSUE TITLE
Sparse matmul over 20 times slower than dense matmul

### ISSUE THREAD

**Issue by villekf** [arrayfire/arrayfire#1972]
When using the following code, the sparse version is over 20 times slower compared to the dense version, i.e. if the matrix A is dense. 

```
const size_t pikselit = 4096;

array H;

setSeed(10);
array G_f = randn(pikselit, pikselit);
G_f = (G_f + transpose(G_f)) / 2;
	
array T = randu(pikselit, pikselit);
array A = floor(T * 1000);
A = A * ((A % 6) == 0) / 1000;
A = sparse(A);

printf("density = %f\n", 100.f * (float)sparseGetNNZ(A) / (float)A.elements());
    
timer::start();

for (int tt = 0; tt <= 500 - 1; tt++) {
	H = matmul(A, G_f);
}

printf("time = %g\n", timer::stop());
```

ArrayFire v3.5.1 (CUDA, 64-bit Linux, build 0a675e8)
Platform: CUDA Toolkit 8, Driver: 375.66
[0] Tesla P100-PCIE-16GB, 16277 MB, CUDA Compute 6.0
-1- Quadro K620, 1998 MB, CUDA Compute 5.0

**Comment by pavanky** [comment]
@villekf Sparsity of 16% is way too high and 4096 is way too small. Sparse matrix multiplication is optimized for larger sparser matrices.
