### ISSUE TITLE
cmake: lapack on cpu is disabled

### ISSUE THREAD

**Issue by fzimmermann89** [arrayfire/arrayfire#1974]
@umar456 
In src/backend/cpu/cmakelist  used to be:
```
IF(LAPACK_FOUND)
    ADD_DEFINITIONS(-DWITH_CPU_LINEAR_ALGEBRA)
```

this is checked in solve/cholesky/etc. and causes a ""Linear Algebra is _diabled_  (sic!) on CPU" error if not set.

But after #1861 this is no longer set anywhere. I don't know what your plan is and where this should be in the current cmake structure

**Comment by umar456** [comment]
Good catch! I seemed to have overlooked this. I can add this in a couple of hours.
