### ISSUE TITLE
af::sum unclear implementation - Use T as data type to sum into

### ISSUE THREAD

**Issue by Ibex-Bradley** [arrayfire/arrayfire#1976]
When using af::sum<T>(array) the usage of this function is unclear as the type supplied as T is not used as the data type which the sum operation will sum into. This leads to issues when trying to sum an array which has values near the max a datatype can store as the sum operation will be performed and stored in the data type of the underlying array and not type T which if set correctly would prevent the overflow issue.

**Comment by FloopCZ** [comment]
Just one little clarification, the templated version of [`af::sum<T>`](http://arrayfire.org/docs/group__reduce__func__sum.htm#ga27080996b6ea1c422f16da4b06fb76a7) does not perform sum along the first non-one dimension, but across all the elements (right @umar456 ?).
