### ISSUE TITLE
Compile fails on windows - missing include <string>

### ISSUE THREAD

**Issue by fzimmermann89** [arrayfire/arrayfire#1977]
Since (at least) 104ba5669c01a665b67663b5c70177ce63e0d3b2 the build fails on my VS2015 setup.
(I don't know if I changed anything regarding the build setup)
The error is because

https://github.com/arrayfire/arrayfire/blob/104ba5669c01a665b67663b5c70177ce63e0d3b2/src/backend/common/util.hpp#L12
doesn't include `<string>`, so I get an error at
https://github.com/arrayfire/arrayfire/blob/104ba5669c01a665b67663b5c70177ce63e0d3b2/src/backend/common/util.hpp#L16

It seems that on gcc `iosfwd` includes `<string>`, but this is not mandatory.
Should there be an include for string?

**Comment by umar456** [comment]
Odd because we test on Windows with VS2015 (http://ci.arrayfire.org/view/All%20PR/job/arrayfire-windows/job/pr-build-cpu/291/) with no errors. It looks like string should be included there. Could you submit a PR for this as I am not able to reproduce it in our setup?

**Comment by fzimmermann89** [comment]
I will create a pr. 
Do the ci builds cover the unified backend?
Somehow string seems seems coincidentally be included in all other uses of until.hpp
For reference:
C:\Users\thunder\arrayfire\arrayfire\src\backend\common/util.hpp(16): error C2039: "string": Ist kein Element von "std" [C:\Users\thunder\arrayfire\arrayfire\build-CLBlast\src\api\unified\af.vcxproj]

**Comment by umar456** [comment]
Hmm, perhaps that's the problem. I don't think that test is building the unified backend. I will create a build for that in the next couple of days. Thanks for pointing that out.
