### ISSUE TITLE
Compilation error on Ubuntu 14.04 using gcc 4.8.2

### ISSUE THREAD

**Issue by futurely** [arrayfire/arrayfire#198]
```
arrayfire/src/backend/cpu/blas.cpp:66:11: error: invalid conversion from ‘void (*)(CBLAS_ORDER, CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, blasint, blasint, blasint, const float*, const float*, blasint, const float*, blasint, const float*, float*, blasint) {aka void (*)(CBLAS_ORDER, CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, const float*, const float*, int, const float*, int, const float*, float*, int)}’ to ‘cpu::gemm_func_def<std::complex<float>, void> {aka void (*)(CBLAS_ORDER, CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, const void*, const void*, int, const void*, int, const void*, void*, int)}’ [-fpermissive]
 { return &cblas_##PREFIX##FUNC; }
           ^
arrayfire/src/backend/cpu/blas.cpp:77:1: note: in expansion of macro ‘BLAS_FUNC’
 BLAS_FUNC(gemm , cfloat  ,   void, c)
 ^
```

**Comment by EmergentOrder** [comment]
I'm having this very same problem.
Also on Ubuntu 14.04, gcc 4.8.2.
I have tried with both OpenBLAS and ATLAS. Same result.
clBLAS and clFFT compile fine.

**Comment by EmergentOrder** [comment]
My current CBLAS* values:
 CBLAS_atlas_LIBRARY              /usr/lib/libatlas.so.3                                  
 CBLAS_cblas_LIBRARY              /usr/lib/libcblas.so.3                                  
 CBLAS_cblas_atlas_INCLUDE        /usr/local/include

**Comment by EmergentOrder** [comment]
Same problem on Ubuntu 12.04, with gcc 4.8.1

**Comment by pavanky** [comment]
@EmergentOrder CBLAS is only required for the CPU backend. If that is being a problem for you can you turn temporarily BUILD_CPU to OFF and build the other backends?

**Comment by EmergentOrder** [comment]
Thanks, that works, compiles and tests pass (well, all but of them but 1, #47 fails). Any ideas about fixing the CPU backend build though ? I tried two machines, with two different system BLAS libs each [which are definitely working for other purposes].

**Comment by pavanky** [comment]
@shehzan10 @9prady9 @bkloppenborg 

Can one of you look into this ?

**Comment by Mach123** [comment]
Hello, I had a same issue. But I could solve it for my case.
There was cblas.h from OpenBLAS ( http://www.openblas.net/ ) in /usr/local/include .
After removal of that file, no more compilation error occurs.

**Comment by futurely** [comment]
OpenBLAS is multi-threaded and is one of the fastest open source BLAS library. Any way to support it?

**Comment by 9prady9** [comment]
@futurely we did internally test with OpenBLAS and it worked out of the box on Linux, though we had to do some tweaks for Windows. Did you face any issues using OpenBLAS on linux ?

**Comment by Mach123** [comment]
Both OpenBLAS and arrayfire work fine. But there is a conflict between 
blas.cpp (at src/backend/cpu/) and cblas.h (came from OpenBLAS).
cblas.h is included by blas.hpp.

**Comment by pavanky** [comment]
We are in the process of writing the blas.cpp to use BLAS apis instead of CBLAS. This should solve many issues.

**Comment by shehzan10** [comment]
I installed both OpenBLAS and Atlas on my system and it worked fine without any issues. Didn't have to remove any header files either.
It worked fine even with OpenBLAS only and Atlas only. I use gcc 4.8.2.

@pavan We could make it optional to have either atlas or openblas in our build steps.

**Comment by Mach123** [comment]
My information (conflict with OpenBLAS) was not enough.
OpenBLAS-0.2.14.tar.gz  ,got from http://www.openblas.net/ has a conflict.
But OpenBLAS  from github (git clone git://github.com/xianyi/OpenBLAS) works well,

**Comment by shehzan10** [comment]
I got mine from apt-get and it's 0.2.8, so it should not be that different.
My guess would be that the tar ball got installed and over wrote the atlas cblas.h file.

**Comment by pavanky** [comment]
Is this still an issue ? Can we close it ? Perhaps we need to update the wiki to make sure the right steps are followed.

**Comment by EmergentOrder** [comment]
@pavanky Compilation w/ CPU backend works for me now (Ubuntu 14.04, gcc 4.8.2), and all tests pass.
One line in the wiki is somewhat unclear though:
./examples/example_backend
as there are no examples immediately in the examples directory, but in sub-directories to it.

**Comment by shehzan10** [comment]
Thanks for letting us know.
I'll update the wiki.

**Comment by alcinos** [comment]
I'm facing a similar issue. I'm on Arch, and I've openblas-lapack installed (https://aur.archlinux.org/packages/openblas-lapack/). It should provide blas, cblas and lapack, so in my understanding I shouldn't have to install any further library (wiki suggests cblas, but it is conflicting)

Any thoughts ?

**Comment by pavanky** [comment]
@alcinos My main distro is arch, so we sort of test it on a daily basis ;)

If you are on arch, try installing this package: https://aur.archlinux.org/packages/arrayfire-git/

You will need to install openblas from aur and lapack from extra to get the optimum configuration before installing arrayfire. 

If you have issues, don't hesitate to contact me here or on [gitter](https://gitter.im/arrayfire/arrayfire)
