### ISSUE TITLE
Build error when building with OpenCL: ‘cout’ is not a member of ‘std’

### ISSUE THREAD

**Issue by ezavod** [arrayfire/arrayfire#1981]
When I try to build Arrayfire (following the [wiki](https://github.com/arrayfire/arrayfire/wiki/Build-Instructions-for-Linux)) with OpenCL (AMD APP SDK 3.0 or Intel SDK) I get the following error (occurs multiple times in this file):
`In file included from /home/<user>/arrayfire/src/backend/opencl/program.cpp:10:0:
/home/<user>/arrayfire/src/backend/opencl/program.cpp: In function ‘void opencl::buildProgram(cl::Program&, int, const char**, const int*, std::__cxx11::string)’:
/home/<user>/arrayfire/src/backend/opencl/program.hpp:26:18: error: ‘cout’ is not a member of ‘std’
             std::cout << PROG.getBuildInfo<CL_PROGRAM_BUILD_LOG>(       \`

Could be prevented by adding `#include <iostream>` in `src/backend/opencl/program.cpp`, but this is probably not the best way to fix it. Nevertheless build functions normally afterwards.

This error obviously occurs only when enabling OpenCL, the CPU backend works flawless.

OS: openSUSE Tumbleweed 64bit (Kernel 4.13.9-1-default)
ArrayFire: 42a99a76684b662e30c3d76c896069d820ca9a96 (latest master)
cmake: 3.9.4
make: 4.2.1
gcc/g++: 7.2.1

**Comment by umar456** [comment]
Hi @ezavod,
Thanks for pointing this out. Looks like this was introduce because of #1971. I should have a fix for this later tonight. I am planning on replacing std::cout with printf but your change is also an appropriate solution.
