### ISSUE TITLE
Build error: ‘function’ is not a member of ‘std’

### ISSUE THREAD

**Issue by ezavod** [arrayfire/arrayfire#1983]
Hello, thanks very much for the immediate fix of #1981! But it seems that commit c7fd7f8045c31ec2aac0f517f1a8003b49d2cf27 introduces a similar problem:
`#include <functional>` is missing in `src/backend/<backend_name>/memory.hpp`.
I only use cpu and opencl backend but this is probably missing in all backends.

**Comment by umar456** [comment]
I will download gcc-7 later tonight and check it out.
