### ISSUE TITLE
Upgrade to latest Intel-MKL for AVX-512

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#1986]
In order for AF to take advantage of Intel Skylake CPU specially AVX-512, upgrade to the latest/recent Intel MKL SDK: 
https://software.intel.com/en-us/articles/intel-math-kernel-library-intel-mkl-2017-release-notes
https://en.wikipedia.org/wiki/AVX-512

Easy test: AWS C5 instance with Skylake CPU: 
https://aws.amazon.com/about-aws/whats-new/2017/11/introducing-amazon-ec2-c5-instances-the-next-generation-of-compute-optimized-instances/

Intel OpenCL does not seem to be (yet) AVX-512 capable
https://software.intel.com/en-us/forums/opencl/topic/737516 

Cheers
W.

**Comment by pavanky** [comment]
@umar456 can this be done for the next release?

**Comment by umar456** [comment]
We are using MKL 2017.0.098 for the installers. We should be updating to the latest version of MKL with the next release.

**Comment by 9prady9** [comment]
Latest(3.6) release binary was built uding latest(2018) MKL libraries.
