### ISSUE TITLE
Can't set axes title with setAxesTitles  for af::Window

### ISSUE THREAD

**Issue by nikkadim** [arrayfire/arrayfire#1987]
Can't set axes title with setAxesTitles:

> ArrayFire v3.5.1 (CUDA, 64-bit Windows, build 0a675e8)
> Platform: CUDA Toolkit 8, Driver: CUDA Driver Version: 8000
> [0] GeForce GTX 1060 6GB, 6144 MB, CUDA Compute 6.1
> 

Code:
```

	af::setBackend(AF_BACKEND_CUDA);
	af::info();
	af::Window myWindow(512, 512, "Histogram example using ArrayFire");

	const int BINS = 255;
	int SAMPLES = 9162;
	array norm = randn(SAMPLES);
	array hist_arr = histogram(norm, BINS);

        myWindow.setAxesTitles("Bins", "Frequency");
        while (!myWindow.close()) {
            myWindow.hist(hist_arr, 0, 255);
           
        }
```
Output:
![afwind](https://user-images.githubusercontent.com/152394/32676419-8ed30aca-c628-11e7-95d2-73de48f40116.png)

**Comment by 9prady9** [comment]
@nikkadim Thank you for reporting this. We will look into it as soon as we can.
