### ISSUE TITLE
batchFunc only multiplies first column in a sparse matrix

### ISSUE THREAD

**Issue by villekf** [arrayfire/arrayfire#1988]
When using batchFunc to perform element-wise multiplication, only the first column is actually multiplied when using a sparse matrix. 

For example, if G is a square sparse matrix and nw is a dense column vector, the following code only applies the multiplication on the first column of G:

```
array batch_mult(const array &lhs, const array &rhs) {
	return lhs * rhs;
}

array Cw = batchFunc(G, nw, batch_mult); 
```
If G is dense, then everything works fine.

ArrayFire v3.5.1 (CUDA, 64-bit Linux, build 0a675e8)
Platform: CUDA Toolkit 8, Driver: 375.66
[0] Tesla P100-PCIE-16GB, 16277 MB, CUDA Compute 6.0
-1- Quadro K620, 1998 MB, CUDA Compute 5.0

**Comment by pavanky** [comment]
@villekf batchFuc / GFOR wasn't meant to be used with sparse matrices..

**Comment by villekf** [comment]
Some kind of error/warning when used with sparse matrices might be good. Since currently it seems to work, but actually doesn't.

Though I wouldn't mind sparse support for batchFunc also.
