### ISSUE TITLE
Build error: OpenCL with installed Boost greater or equal to 1.61

### ISSUE THREAD

**Issue by meister87** [arrayfire/arrayfire#1994]
Hi,
In the following opencl-based CMakeFiles the target Boost::boost is used:
- src/backend/opencl/kernel/sort_by_key/CMakeLists.txt
- src/backend/opencl/kernel/scan_by_key/CMakeLists.txt
- src/backend/opencl/CMakeLists.txt

The target Boost::boost is only defined in the following file:
- CMakeModules/build_boost_compute.cmake

This file is only included in the following file:
- src/backend/opencl/CMakeLists.txt

```
if("${Boost_VERSION}" VERSION_LESS 106100)
  dependency_check(Boost_FOUND "Boost not found.")
  include(build_boost_compute)
endif()
```
Hence, if already a boost version greater than 1.61 is installed, the target will never be defined and the build fails.

**Comment by 9prady9** [comment]
This has been addressed in 3.6 release.
