### ISSUE TITLE
Could current ArrayFire support Matrix-Multply in batch mode?

### ISSUE THREAD

**Issue by BookmanHan** [arrayfire/arrayfire#1996]
Hi, I have read some issues of batched MM.
I think this may be featured in latest version 3.5.1, because this page (http://arrayfire.org/docs/page_gfor.htm) illustrates an usage of gfor-MM.

But, I can't apply a batched-MM as below.
```
        gfor(af::seq i, n_sample)
        {
            af::array i_left = arr_left(af::span, af::span, i);
            af::array i_right = arr_right(af::span, af::span, i);
            arr(af::span, af::span, i) = af::matmul(i_left, i_right);
        }
```

What should I do?

On the other hand, ArrayFire could not work with OpenMP as below.
```
#pragma omp parallel for
        for(auto i=0; i<n_sample, ++i)
        {
            af::array i_left = arr_left(af::span, af::span, i);
            af::array i_right = arr_right(af::span, af::span, i);
            arr(af::span, af::span, i) = af::matmul(i_left, i_right);
        }
```
It came up with an exception in `af::gen_assign`.
Could this be fixed?

Thanks, a lot.

**Comment by pavanky** [comment]
- Duplicated in #483 
- Being implemented in 1898

**Comment by BookmanHan** [comment]
@pavanky How to use batch-mode? just write it in a gfor?

**Comment by pavanky** [comment]
@BookmanHan It is isnt supported yet. But once #1898  gets merged, yo can simply do:

```
af::array arr = af::matmul(arr_left, arr_right);
```

and it will work for 3D or 4D arrays.

**Comment by BookmanHan** [comment]
@pavanky 
Thanks, very much.
I really need this functionality. 

Expect the good news.

Thanks, again.
