### ISSUE TITLE
Update unified backend doc

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#2008]
Seen on
http://arrayfire.org/docs/unifiedbackend.htm
"On Linux and OSX, add /usr/local/cuda/nvvm/(lib or lib64) to LD_LIBRARY_PATH or DYLD_LIBRARY_PATH."
Is nt nvvm no more needed from 3.5+ ?
Kind

**Comment by 9prady9** [comment]
@WilliamTambellini Yes, we moved to nvrtc as part of this PR https://github.com/arrayfire/arrayfire/pull/1836. I will udpate the documentation in the PR https://github.com/arrayfire/arrayfire/pull/2012.

Thank you for reporting it.
