### ISSUE TITLE
af::lookup fails on CUDA when looking up in a single column array

### ISSUE THREAD

**Issue by munnybearz** [arrayfire/arrayfire#2009]
Hi team,

I think I've found a bug in the af::lookup() method on the CUDA backend. This example demonstrates it:

```
    af::array a = af::range(af::dim4(5, 1));
    af::array idx = af::constant(0, 1, u32);
    af::array l = lookup(a, idx, 1);

    af::print("a", a);
    af::print("idx", idx);
    af::print("l", l);
```

On the CPU backend this produces the correct result:

```
a
[5 1 1 1]
    0.0000 
    1.0000 
    2.0000 
    3.0000 
    4.0000 

idx
[1 1 1 1]
         0 
l
[5 1 1 1]
    0.0000 
    1.0000 
    2.0000 
    3.0000 
    4.0000 
```

However on the CUDA backend the last array is incorrect:

```
a
[5 1 1 1]
    0.0000 
    1.0000 
    2.0000 
    3.0000 
    4.0000 

idx
[1 1 1 1]
         0 
l
[5 1 1 1]
    0.0000 
    0.0000 
    0.0000 
    0.0000 
    0.0000 
```

If the initial array a was a 2+ column array the lookup works as expected on CUDA:

```
a
[5 2 1 1]
    0.0000     0.0000 
    1.0000     1.0000 
    2.0000     2.0000 
    3.0000     3.0000 
    4.0000     4.0000 

idx
[1 1 1 1]
         0 
l
[5 1 1 1]
    0.0000 
    1.0000 
    2.0000 
    3.0000 
    4.0000 
```

It just doesn't seem to work when a is a 1 column array!!

I am using CUDA 8, NVIDIA driver 384.90 on a GTX 1070, Ubuntu 16.04 and latest master arrayfire built from source as of about a month ago.

**Comment by 9prady9** [comment]
@munnybearz I was able to reproduce this on my end, I will look into it. Thank you for reporting it.

**Comment by 9prady9** [comment]
I found the problem. This is a difference in behavior of `lookup` from **CUDA** backend compared to **CPU**/**OpenCL**. **CUDA** backend has a fast path for **1D** arrays where it is computing first-non singleton dimension and then using that `dim` for lookup instead of the one passed down from the API level.

I will send in a PR soon.

**Comment by munnybearz** [comment]
fantastic thank you very much!
