### ISSUE TITLE
Cannot run the examples from the fresh install. 

### ISSUE THREAD

**Issue by syedalamabbas** [arrayfire/arrayfire#2015]
I just downloaded the arrayfire library and installed on my machine. But when I try to run the CUDA platform helloworld, I get these missing dlls error. I wonder if I am missing any settings ? Please take a look at this picture. 
![image](https://user-images.githubusercontent.com/9631714/33861268-d561c02c-de91-11e7-9fc6-23dfe39fbb17.png)

**Comment by syedalamabbas** [comment]
Do I need to install cuBLAS_64, cufft_64 and cusparse_64 separately for CUDA platform arrayfire code to work ?

**Comment by pavanky** [comment]
@syedalamabbas What eversion of CUDA do you have installed on your machine ? I think the latest installers only support CUDA 8.0. 

If you have CUDA 9.0 installed, can you install the CUDA 8.0 as well ? AFAIK you can have multiple cuda toolkits installed at the same time.

**Comment by syedalamabbas** [comment]
Hi Pavan, I tried installing cuda 8.0 but the installer never completes, it says cuBLAS etc already installed.

**Comment by 9prady9** [comment]
@syedalamabbas ArrayFire 3.6 release is out and it comes with dependencies of all backends preinstalled along with our library. Starting from 3.6 release, you would only need to install the drivers of CUDA device to work with ArrayFire. Please try the examples from 3.6 release and let us know if you face any issues. Thank you!
