### ISSUE TITLE
Need to have default value for FFTW_USE_STATIC_LIBS 

### ISSUE THREAD

**Issue by navidR** [arrayfire/arrayfire#2023]
```
cmake -LAH :
// Path to a library.
FFTWF_LIB:FILEPATH=C:/Users/navid/AppData/Roaming/vcpkg/installed/x64-windows/bin/fftw3f.dll
// Path to a file.
FFTW_INCLUDES:PATH=C:/Users/navid/AppData/Roaming/vcpkg/installed/x64-windows/include
// Path to a library.
FFTW_LIB:FILEPATH=C:/Users/navid/AppData/Roaming/vcpkg/installed/x64-windows/bin/fftw3.dll
```

FindFFTW.cmake cannot sync correctly with the build process. For example, default build process in windows uses static linking, but as you can see findFFTW finds dll version because there is no default value for "FFTW_USE_STATIC_LIBS".

I think a better solution would be changing the internal of FindFFTW.cmake file and making static compilation as default one. But for now I only added 
```
set(FFTW_USE_STATIC_LIBS ON)
```
before 
```
FIND_PACKAGE(FFTW REQUIRED)
```

**Comment by umar456** [comment]
Are you compiling using v3.5? If so this should have been addressed with #2021. The FindFFTW.cmake in that case was incorrectly setting the CMAKE_FIND_LIBRARY_SUFFIX to dll on windows. If you run into this issue on master then that needs to be addressed. 

Also I see you are using vcpkg. How do you like it and has it made the build processes easier on Windows?

**Comment by navidR** [comment]
>Are you compiling using v3.5? If so this should have been addressed with #2021. The FindFFTW.cmake in that case was incorrectly setting the CMAKE_FIND_LIBRARY_SUFFIX to dll on windows.

Yes, I was under the impression bugfixes would be backported to latest stable release and I was using v3.5.1. I tried the master and it worked. thx. One quick question though, when 3.5.2 is going to get released? 

>Also I see you are using vcpkg. How do you like it and has it made the build processes easier on Windows?
Actually, it has made my life way easier. I use it all the time for everything and I am writing a small port to have Arrayfire in VCPKG repository so people would be able to install Arrayfire with only 
```
>vcpkg install arrayfire
```

**Comment by 9prady9** [comment]
@navidR Yes, we are backporting fixes. However, the fix needed to resolve your problem hasn't been yet. We will do the next backport to v3.5 branch when we do 3.5.2 release I believe. @umar456 Please confirm.

**Comment by umar456** [comment]
@navidR The change will be backported. Its currently under review #1992 . It has the #2021 change if you want to give it a try. We want to get a release out soon. I was waiting for #2024 but that was merged in this morning so we are pretty close.

**Comment by navidR** [comment]
thanks.
