### ISSUE TITLE
error: thread-local storage is not supported for the current target

### ISSUE THREAD

**Issue by irajdeep** [arrayfire/arrayfire#2034]
Building on macOS Sierra 10.12.6 , I was getting this error

> rdas@C02TX1G1HV2T:~/Documents/arrayfire/build$ make install
-- Found OpenCL: /System/Library/Frameworks/OpenCL.framework (found suitable version "1.2", minimum required is "1.2")
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) (found version "1.0")
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) (found version "1.0")
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Checking for [mkl_rt]
-- Checking for [Accelerate]
-- Includes found
-- CBLAS Symbols FOUND
-- CBLAS library found
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Could NOT find LAPACK (missing: LAPACK_INCLUDE_DIR LAPACK_LIBRARIES)
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Boost version: 1.66.0
-- A library with BLAS API found.
-- A library with LAPACK API found.
-- CUDA Architectures: 3.0;3.5;5.0;5.2;6.0;6.1;6.1+PTX
-- Found OpenCL: /System/Library/Frameworks/OpenCL.framework (found version "1.2")
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/rdas/Documents/arrayfire/build
[  0%] Built target bin2cpp
[  0%] Built target cpu_sort_by_key_uchar
[  0%] Built target cpu_sort_by_key_ushort
[  0%] Built target cpu_sort_by_key_short
[  0%] Built target cpu_sort_by_key_char
[  0%] Built target cpu_sort_by_key_intl
[  0%] Built target cpu_sort_by_key_uint
[  0%] Built target cpu_sort_by_key_uintl
[  0%] Built target cpu_sort_by_key_int
[  0%] Built target cpu_sort_by_key_double
[  0%] Built target cpu_sort_by_key_float
[ 10%] Built target afcpu
[ 10%] Built target cuda_kernel_headers_bin_target
[ 10%] Linking CXX static library libcuda_scan_by_key.a
[ 10%] Built target cuda_scan_by_key
[ 10%] Linking CXX static library libcuda_thrust_sort_by_key.a
[ 11%] Built target cuda_thrust_sort_by_key
[ 11%] Building CXX object src/backend/cuda/CMakeFiles/afcuda.dir/jit.cpp.o
/Users/rdas/Documents/arrayfire/src/backend/cuda/jit.cpp:350:5: error: thread-local storage is not supported for the current target
    thread_local kc_t kernelCaches[DeviceManager::MAX_DEVICES];
    ^
1 error generated.
make[2]: *** [src/backend/cuda/CMakeFiles/afcuda.dir/jit.cpp.o] Error 1
make[1]: *** [src/backend/cuda/CMakeFiles/afcuda.dir/all] Error 2
make: *** [all] Error 2

The issue seemed to be with Apple Clang.

**Comment by irajdeep** [comment]
After a bit of google search the following solved the issue 

Using homebrew clang instead of Apple clang
`brew install llvm --with-clang --with-asan`

Then in the `CMakeCache.txt` change the `CMAKE_CXX_COMPILER` to following:
`//CXX compiler
CMAKE_CXX_COMPILER:FILEPATH=/usr/local/opt/llvm/bin/clang++`

**Comment by pavanky** [comment]
Hmm this shouldnt be happening if you have the latest xcode..

**Comment by irajdeep** [comment]
umm , might be but couldn't use the latest version of xcode because of [this](https://github.com/fireice-uk/xmr-stak-nvidia/issues/137) . Had to downgrade the xcode version to build.

**Comment by pavanky** [comment]
@umar456 ^

**Comment by umar456** [comment]
Which version of clang are you using? I have
```
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
It is working without issues.

**Comment by irajdeep** [comment]
With `(clang-900.0.37` it didn't work then I downgraded it to `clang-703.0.29` which worked.

**Comment by yinjimmy** [comment]
Xcode 10.1 works with https://github.com/tensorflow/tensorflow/issues/20900#issuecomment-406056891
