### ISSUE TITLE
abs() behavior

### ISSUE THREAD

**Issue by nikkadim** [arrayfire/arrayfire#2038]
ArrayFire v3.5.1 (CUDA, 64-bit Windows, build 0a675e8)
Platform: CUDA Toolkit 8, Driver: CUDA Driver Version: 9010
[0] GeForce GTX 1070, 8192 MB, CUDA Compute 6.1

> sobel_hist
> [10 1 1 1]
>          5
>          6
>         19
>          6
>          2
>          9
>          1
>          5
>          4
>          1

and sobel_hist.type() = 6 (which is u32)

```
unsigned int mad_hist = 5;
array tmp = abs(sobel_hist - meann_hist);
```
as a result:
> 
> tmp
> [10 1 1 1]
>          0
>          1
>         14
>          1
> 2147483647
>          4
> 2147483647
>          0
> 2147483647
> 2147483647

is this a right behavior? I guess it should set tmp absolute difference?

**Comment by pavanky** [comment]
@nikkadim sobel_hist is unsigned. The subtract is causing an unsigned underflow. May be cast sobel_hist to int32.

**Comment by nikkadim** [comment]
@pavanky thank you for quick reply
`array tmp = abs(sobel_hist.as(s32) - meann_hist);`
does not help:
> [10 1 1 1]
>     0.0000
>     1.0000
>    14.0000
>     1.0000
> 4294967296.0000
>     4.0000
> 4294967296.0000
>     0.0000
> 4294967296.0000
> 4294967296.0000

**Comment by nikkadim** [comment]
@pavanky it works only if cast to f32
`array tmp = abs(sobel_hist.as(f32) - meann_hist);`

> [10 1 1 1]
>          5
>          6
>         19
>          6
>          2
>          9
>          1
>          5
>          4
>          1
> 

> tmp
> [10 1 1 1]
>     0.0000
>     1.0000
>    14.0000
>     1.0000
>     3.0000
>     4.0000
>     4.0000
>     0.0000
>     1.0000
>     4.0000
> 

but why?

**Comment by pavanky** [comment]
@nikkadim I think the type inference inside arrayfire is screwed up. I'll look into it.

**Comment by mark-poscablo** [comment]
Hi @nikkadim, I've looked closer at this issue and it looks like `meann_hist` is still an unsigned, and even after the suggestion to cast `sobel_hist` to s32, we will still get the underflow results because we're subtracting an unsigned from a signed. Even without arrayfire, we'll still get the same results:
```
    std::cout << (int) 1 - (unsigned) 2 << std::endl; // 4294967295
    std::cout << std::abs((int) 1 - (unsigned) 2) << std::endl; // 4.29497e+09
```
What we can do, however, is have `meann_hist` to be signed also:
```
    std::cout << (int) 1 - (int) 2 << std::endl; // -1
    std::cout << std::abs((int) 1 - (int) 2) << std::endl; // 1

    unsigned int h_sobel_hist[10] = {5, 6, 19, 6, 2, 9, 1, 5, 4, 1};
    array sobel_hist(10, h_sobel_hist);
    int meann_hist = 5;
    af_print(af::abs(sobel_hist.as(s32) - meann_hist));
    //      0.0000
    //      1.0000
    //     14.0000
    //      1.0000
    //      3.0000
    //      4.0000
    //      4.0000
    //      0.0000
    //      1.0000
    //      4.0000
```
Hope this helps!
