### ISSUE TITLE
Why my program interrupts by SIGKILL? 

### ISSUE THREAD

**Issue by BookmanHan** [arrayfire/arrayfire#2044]
My program always stops after running several hours and notice me 
`terminated by signal SIGKILL (Forced quit)` 

Does the error cause by ArrayFire?
Is it possible?
Which is more possible, that something wrong happens to my codes or someone kills my program by hand?

Thanks, a lot.

**Comment by pavanky** [comment]
if you are on a shared machine, there may be limitations on how much time you can use it. Talk to your administrator. ArrayFire shouldnt kill itself using SGKILL.
