### ISSUE TITLE
Continuous resize of arrays - Optimial way

### ISSUE THREAD

**Issue by vineelpratap** [arrayfire/arrayfire#2065]
Hi,
Lets say I have this code... 
 ```
auto A = af::randu(100, 100);
// some other stuff 
auto B = af::randu(200, 100);
A  = B
```
Does arrayfire optimally resize A to a (200, 100) matrix reusing the previously allocated memory if possible. If not, if there a way I can do this. I'm looking for a functionality similar to torch resize option -  https://github.com/torch/torch7/blob/master/doc/tensor.md#resizing

Thanks !

**Comment by umar456** [comment]
ArrayFire uses copy on write when managing memory. In your case, `A` will point to the same memory as `B` until either of those variables are written to. At which time a copy will be performed. I am not sure I understand what torch is doing.

This is more of a question so I am going to close this issue. Questions should be posted on our [Google groups](https://groups.google.com/forum/#!forum/arrayfire-users) or our Slack channel.
