### ISSUE TITLE
SVD fails on OpenCL and CUDA on dimensions [2048, 2048]

### ISSUE THREAD

**Issue by villekf** [arrayfire/arrayfire#2072]
When using SVD with OpenCL with the dimensions [2048, 2048] (every other dimension seems to work fine, eg. 2047 or 2049) the program throws a runtime error. On CUDA, when printing the singular values, the latter values only show 0.0000. CPU backend works fine. This is most easily demonstrated by using the following code:

```
#include <arrayfire.h>

using namespace af;

int main()
{

	info();
	size_t dims = 2048;

	setSeed((uint64_t)10);

	array matriisi = randn(dims, dims, f32);
	array U, S, V;
	svd(U, S, V, matriisi);

	af_print(S);

	return 0;
}
```

AF infos: 
ArrayFire v3.5.1 (CUDA, 64 - bit Windows, build 0a675e8)
Platform: CUDA Toolkit 8, Driver : CUDA Driver Version : 9010
[0] GeForce GTX TITAN, 6144 MB, CUDA Compute 3.5

ArrayFire v3.5.1 (CUDA, 64-bit Linux, build 0a675e8)
Platform: CUDA Toolkit 8, Driver: 387.26
[0] Tesla P100-PCIE-16GB, 16277 MB, CUDA Compute 6.0
-1- Quadro K620, 2001 MB, CUDA Compute 5.0

**Comment by 9prady9** [comment]
@villekf Thank you for reporting it. I was able to reproduce it on master branch as well.

CUDA backend is printing 0.0s towards end(many, not just few zeros) of the array. OpenCL backend is failing with the following for me:
```
ninja: Entering directory `build'
ninja: no work to do.
ArrayFire v3.6.0 (OpenCL, 64-bit Linux, build a6e185a1)
[0] NVIDIA: GeForce GTX 1060 3GB, 3011 MB -- OpenCL 1.2 CUDA -- Device driver 390.25 -- FP64 Support: True -- Unified Memory (False)
OpenCL error -11 on line 244 of /home/pradeep/gitroot/ArrayFireWorkspace/arrayfire/worktrees/deconv/build/third_party/clBLAS/src/clBLAS-ext/src/library/blas/xgemm.cc
helloworld_opencl: /home/pradeep/gitroot/ArrayFireWorkspace/arrayfire/worktrees/deconv/build/third_party/clBLAS/src/clBLAS-ext/src/library/blas/xgemm.cc:244: void makeGemmKernel(_cl_kernel**, cl_command_queue, const char*, const char*, const unsigned char**, size_t*, const char*): Assertion `false' failed.
```
It is failing while building a clBLAS kernel source. We will have to dig further into it to figure out if the problem is from `clBLAS` or if it is related to how ArrayFire is working with clBLAS. @pavanky any thoughts ?

**Comment by 9prady9** [comment]
I found similar behavior to CUDA if I use `CLBlast` as the opencl blas library on current master. Using `clBLAS` causes the crash as earlier.

**Comment by 9prady9** [comment]
Another new find: CPU backend results are different from CUDA & OpenCL.

**Comment by 9prady9** [comment]
Using an `af::array` object created from `rand*` functions is not the correct way to compare results from CPU and CUDA/OpenCL backend. From the looks of it, the only issue that I see is that when clBLAS is used as upstream for ArrayFire, the program fails/crashes. Using CLBlast whowever does produce an output similar to CUDA backend.

I am looking int othe issue of crash when clBLAS is used.

**Comment by 9prady9** [comment]
After discussing with @umar456 we are switching to `CLBlast` as default OpenCL blas upstream instead of clblas. The intention is to drop support for clblas eventually if there are no new releases.
