### ISSUE TITLE
moore penrose inverse

### ISSUE THREAD

**Issue by kimoes** [arrayfire/arrayfire#2074]
Hello, I wanted to ask if Matrix pseudo inverse is supported by arrayfire as I have seen some documents using arrayfire.pinv while I cant use it as its not supported as the arrayfire.inverse for example

**Comment by pavanky** [comment]
@kimoes The regular inverse should do pseudo inverse for non square matrices.

**Comment by kimoes** [comment]
when I use it with non squared matrix it show me an error:

 Inv = af.inverse(a)

in inverse safe_call(backend.get().af_inverse(c_pointer(AI.arr), A.arr, options.value))

in safe_call raise RuntimeError(to_str(err_str))

RuntimeError: In function af_err af_inverse(void**, af_array, af_mat_prop)
In file src/api/c/inverse.cpp:43
Invalid dimension for argument 1
Expected: i_info.dims()[0] == i_info.dims()[1]


The code is:
import arrayfire as af
import numpy as np

Row = 12
Col = 10

a = np.random.randn(Row, Col).astype('float32')
a = af.Array(a.ctypes.data, a.shape, a.dtype.char)

Inv = af.inverse(a)
