### ISSUE TITLE
Inverse non squared matrix

### ISSUE THREAD

**Issue by kimoes** [arrayfire/arrayfire#2077]
Hallo, 
I was told that inverse function in arrayfire works for square and non square matrix 
But, when I use it with non squared matrix it show me an error:

Inv = af.inverse(a)

in inverse safe_call(backend.get().af_inverse(c_pointer(AI.arr), A.arr, options.value))

in safe_call raise RuntimeError(to_str(err_str))

RuntimeError: In function af_err af_inverse(void**, af_array, af_mat_prop)
In file src/api/c/inverse.cpp:43
Invalid dimension for argument 1
Expected: i_info.dims()[0] == i_info.dims()[1]

The code is:
import arrayfire as af
import numpy as np

Row = 12
Col = 10

a = np.random.randn(Row, Col).astype('float32')
A = af.to_array(a) 

Inv = af.inverse(A)

**Comment by rstub** [comment]
> I was told that inverse function in arrayfire works for square and non square matrix

Where did you get this? [The documentation](http://arrayfire.org/docs/group__lapack__ops__func__inv.htm) clearly states "square matrix". It might be interesting to have something like https://en.wikipedia.org/wiki/Moore%E2%80%93Penrose_inverse in ArrayFire, though.

**Comment by kimoes** [comment]
From Pavan Yalamanchili in another issue where he answered me this, then closed it.

Yes, I agree as getting the inverse of a matrix using SVD works but very slow

**Comment by rstub** [comment]
That would be #2074. But note that many algorithms for the pseudo-inverse rely on SVD.

**Comment by kimoes** [comment]
Yes, indeed.

yes, I understand that but when I compared between the SVD function in array fire (af.svd()) and the one in numpy (np.linalg.svd()) on a big matrix like(6000 x 5000), the numpy one is faster and the np.linalg.pinv () is faster than both. while the logic says the SVD by arrayfire should be the fastest as it would be performed using the gpu.

btw I am a beginner in cuda

**Comment by mark-poscablo** [comment]
Hi @kimoes and @rstub, we have just recently implemented pseudoinverse. It's available now if you build ArrayFire from source, but it should also come with the next release with the installers. Please open a new Issue if you have any questions/feedback on it. Thanks.
