### ISSUE TITLE
"malformed object" when doing "make install" on Mac OS X

### ISSUE THREAD

**Issue by YuMan-Tam** [arrayfire/arrayfire#208]
I am using Mac OS X Yosemite with the updated Xcode and its command line tool. At the final step of the installation, i.e. make install, there is a warning/error:
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: 
object: /usr/local/lib/libafcuda.dylib malformed object (load command 23 cmdsize is zero) 
```
Then when I try to compile a simple "Hello world" example using the installed `libafcuda.dylib` (i.e. in /usr/local/lib), the compilation fails:
```
dyld: Library not loaded: libafcuda.dylib
  Referenced from: /Users/ytam1/Downloads/test/./a.out
  Reason: no suitable image found.  Did find:
	/usr/local/lib/libafcuda.dylib: malformed mach-o image: load command #23 length (0) too small in /usr/local/lib/libafcuda.dylib
```
Interestingly, however, when I use the original `libafcuda.dylib` (i.e. in ./src/backend/cuda/), compilation is successful and produces correct result. I am just not sure why.

**Comment by pavanky** [comment]
This issue should be fixed in latest devel.
