### ISSUE TITLE
error 998 running most cuda examples

### ISSUE THREAD

**Issue by avishaibartov** [arrayfire/arrayfire#2083]
Hi,
Working on Ubuntu 16.04

I have built the examples, running fft_cuda works well, for the rest of the examples I get the following, please advise,
thanks,
Avishai

./cg_cuda
ArrayFire v3.5.1 (CUDA, 64-bit Linux, build 0a675e8)
Platform: CUDA Toolkit 8, Driver: 387.34
[0] GeForce GTX 1060 3GB, 3013 MB, CUDA Compute 6.1
terminate called after throwing an instance of 'af::exception'
what():  ArrayFire Exception (Internal error:998):
In function std::vector<char> cuda::compileToPTX(const char*, std::string)
In file src/backend/cuda/jit.cpp:291
NVRTC Error(7): NVRTC_ERROR unknown**

In function af::array af::transpose(const af::array&, bool)
In file src/api/cpp/transpose.cpp:20
Aborted (core dumped)****

**Comment by 9prady9** [comment]
@avishaibartov Does your `LD_LIBRARY_PATH` has the location where `nvrtc` shared library is present on your machine ?

**Comment by avishaibartov** [comment]
LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64


nvrtc is not there - Working on ubuntu 16.04, how should LD_LIBRARY_PATH should be typically set?


I have also installed cuda 8.0 and tried to point there but it didn't help.


I also have Tensor Flow installed on my machine (working fine)


thanks,

Avishai

________________________________

**Comment by 9prady9** [comment]
I have checked on one of our ci machines which has debian and the lib64 of cuda installation should have `nvrtc` libraries too. If they aren't, may be the CUDA installation has gone corrupt. Try reinstallating it.

**Comment by avishaibartov** [comment]
Hi,
Checked again... actually libnvrtc.so exist.

What should be the next step?
thanks,

**Comment by 9prady9** [comment]
May be it is similar to https://github.com/arrayfire/arrayfire/issues/2084 We are looking into it. You can also use the work arounds mentioned in the issue 2084.

**Comment by avishaibartov** [comment]
Thanks for the quick response.
Tried export AF_CUDA_MAX_JIT_LEN=30 but it didn't help, also the error message is somewhat different - any idea how to continue.
BTW, I saw people are using version 3.6 (mine is 3.5.1) - is that a stable version I can install?

**Comment by 9prady9** [comment]
No, 3.6.0 is not released yet. It is the master branch that is being used when you see 3.6.0. I am kind of out of ideas at the moment.

When you say different, how is your error `NVRTC Error(7): NVRTC_ERROR unknown**` different from the other errors ?

Does the pi benchmarks example work fine ?

**Comment by avishaibartov** [comment]
This is the error: The only example I could actually run was cuda_fft

ArrayFire v3.5.1 (CUDA, 64-bit Linux, build 0a675e8)
Platform: CUDA Toolkit 8, Driver: 387.34
[0] GeForce GTX 1060 3GB, 3013 MB, CUDA Compute 6.1
ArrayFire Exception (Internal error:998):
In function std::vector<char> cuda::compileToPTX(const char*, std::string)
In file src/backend/cuda/jit.cpp:291
NVRTC Error(7): NVRTC_ERROR unknown


In function T af::sum(const af::array&) [with T = float]
In file src/api/cpp/reduce.cpp:145
terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Internal error:998):
In function std::vector<char> cuda::compileToPTX(const char*, std::string)
In file src/backend/cuda/jit.cpp:291
NVRTC Error(7): NVRTC_ERROR unknown


In function T af::sum(const af::array&) [with T = float]
In file src/api/cpp/reduce.cpp:145
Aborted (core dumped)

**Comment by avishaibartov** [comment]
I have compiled all the examples again. There are many warnings like:
/usr/bin/ld: warning: libcublas.so.8.0, needed by /usr/local/lib/libafcuda.so.3.5.1, may conflict with libcublas.so.9.0
/usr/bin/ld: warning: libcufft.so.8.0, needed by /usr/local/lib/libafcuda.so.3.5.1, may conflict with libcufft.so.9.0
/usr/bin/ld: warning: libcusparse.so.8.0, needed by /usr/local/lib/libafcuda.so.3.5.1, may conflict with libcusparse.so.9.0
/usr/bin/ld: warning: libcusolver.so.8.0, needed by /usr/local/lib/libafcuda.so.3.5.1, may conflict with libcusolver.so.9.0

Is there a problem running with cuda 9.0?

**Comment by umar456** [comment]
That version of ArrayFire depends on CUDA 8 binaries. It looks like it is linking against CUDA 9 and that is causing the issues here. You should be able to modify the LD_LIBRARY_PATH to point to the CUDA8 libs if you have those installed or you can build the latest ArrayFire to target CUDA 9 but it is currently not supported in the latest release. We should have support for newer versions of CUDA soon.

**Comment by avishaibartov** [comment]
Thanks!

Tried that yesterday but even after modifying the LD_LIBRARY_PATH to point to the CUDA8 libs, it stills linking to cuda9.

Using:  cmake -LA | grep CUDA, it all still points to cuda 9.

What should I do to change it?

Thanks,

Avishai

**Comment by umar456** [comment]
It seems like this is an issue with the system. GitHub issues is not the best place to resolve these. I am going to close this issue but I will be on our slack or you can post on our google groups if you want to debug this.

https://join.slack.com/t/arrayfire-org/shared_invite/MjI4MjIzMDMzMTczLTE1MDI5ODg4NzYtN2QwNGE3ODA5OQ
