### ISSUE TITLE
Incorrect result of scan in combination with OpenCL

### ISSUE THREAD

**Issue by meister87** [arrayfire/arrayfire#2085]
Hi,
The scan operator should calculate the exclusive and inclusive prefix sum if  AF_BINARY_ADD is used, right?

I noticed that the scan does not always correctly compute the prefix sum.

Using the following example
 
            afcl::addDevice(device_id,device_context, command_queue);

            afcl::setDevice(device_id,device_context);

            std::ifstream inFile;
            inFile.open("prefix_sum_array_fire_test_input.txt");
            std::vector<long> numbers;
            long S;
            while (inFile >> S) {
                numbers.emplace_back(S);
            }

            goo::util::opencl::OpenCLMemInput device_numbers(device_context,
                                                             CL_MEM_COPY_HOST_PTR,
                                                             numbers.size()*sizeof(long),
                                                             numbers.data());

            goo::util::opencl::OpenCLMemInput device_result(device_context, numbers.size()*sizeof(long));

            af::sync();

            af::array input = afcl::array(numbers.size(),
                                          device_numbers.getInput(),
                                          s64,
                                          true);

            af::array device_prefix_sum = af::scan(input,
                                            0,
                                            AF_BINARY_ADD,
                                            false);

            af::sync();

            clEnqueueCopyBuffer(command_queue->getValue(),
                                *device_prefix_sum.device<cl_mem>(),
                                device_result.getInput(),
                                0,
                                0,
                                numbers.size() * sizeof(long),
                                0,
                                nullptr,
                                nullptr
            );

            std::vector<long> result(numbers.size());
            device_result.read(command_queue, result.data(), numbers.size()* sizeof(long),true);

            size_t host_prefix_sum = 0;
            for(size_t element_id = 0; element_id < numbers.size();++element_id){
                ASSERT_EQ(host_prefix_sum, result[element_id]);
                host_prefix_sum += numbers[element_id];
            }`
with the following input file: 
[prefix_sum_array_fire_test_input.txt](https://github.com/arrayfire/arrayfire/files/1808161/prefix_sum_array_fire_test_input.txt)

There are some indices where the prefix sum has some strange outliers.
For example, at the positions the 8191-8193 the following sequence is provided: 4427, 8856, 4429 instead of 4427, 4428, 4429 

This repeats multiple times within the given input at the power of two (but not always).

I tested it on two different GPUs(mobile and Tesla) with the same result.
The example still includes some wrapper function of my framework, but the procedure should be clear.

Is it a bug, or a fault of my implementation/ understanding?

**Comment by umar456** [comment]
Hi Thanks for reporting this. I am not familiar with the goo library. Can you give me a link?

**Comment by meister87** [comment]
Hi,
the goo library is just a small private library.
The included parts are just wrapper for clCreateBuffer (OpenCLMemInput) and clEnqueueReadBuffer (read).
I was just too lazy to make the example completely independent of the wrapper, sorry for that.

**Comment by umar456** [comment]
No worries. I will try to reproduce it in a couple of days.

**Comment by 9prady9** [comment]
Below google-test code snippet can reproduce the above bug. It can be run as part of ArrayFire tests from source file `test/ocl_ext_context.cpp` It uses the data file provided earlier by @meister87 , so download that file to run this code.

```cpp
TEST(OCLExtContext, Issue2085)
{
    cl_device_id deviceId = NULL;
    cl_context context = NULL;
    cl_command_queue queue = NULL;

    int dCount = af::getDeviceCount(); //Before user device addition
    af::setDevice(0);
    af::info();
    af::array t = af::randu(5,5);
    af_print(t);

    getExternals(deviceId, context, queue);
    afcl::addDevice(deviceId, context, queue);
    printf("\nBefore setting device to newly added one\n\n");
    af::info();

    afcl::setDevice(deviceId, context);
    printf("\nAfter setting device to newly added one\n\n");
    af::info();

        std::ifstream inFile;
        inFile.open("/home/pradeep/Downloads/prefix_sum_array_fire_test_input.txt");
        std::vector<long> numbers;
        long S;
        while (inFile >> S)
            numbers.push_back(S);

        cl_mem numbers_mem = clCreateBuffer(context,
                                            CL_MEM_COPY_HOST_PTR,
                                            numbers.size()*sizeof(long),
                                            numbers.data(), NULL);
        cl_mem output_mem = clCreateBuffer(context,
                                           CL_MEM_WRITE_ONLY,
                                           numbers.size()*sizeof(long),
                                           NULL, NULL);

        af::sync();

        af::array input = afcl::array(numbers.size(), numbers_mem, s64, true);

        af::array device_prefix_sum = af::scan(input, 0, AF_BINARY_ADD, false);

        af::sync();

        clEnqueueCopyBuffer(queue, *device_prefix_sum.device<cl_mem>(),
                output_mem, 0, 0, numbers.size() * sizeof(long),
                0, NULL, NULL);

        std::vector<long> result(numbers.size());

        clEnqueueReadBuffer(queue,
                output_mem, CL_TRUE,
                0, numbers.size()*sizeof(long), result.data(),
                0, NULL, NULL);

        size_t host_prefix_sum = 0;

        for(size_t element_id = 0; element_id < numbers.size();++element_id)
        {
            ASSERT_EQ(host_prefix_sum, result[element_id]);
            host_prefix_sum += numbers[element_id];
        }
}
```

**Comment by pavanky** [comment]
Weird. Did this not fix the issue: https://github.com/arrayfire/arrayfire/pull/2119 ?

**Comment by 9prady9** [comment]
No

**Comment by Thomasdebodt** [comment]
I noticed a similar issue when using the cuda back-end. The problem only seems to occur when using af::scan in **exclusive** mode (e.g. 4th parameter is set to false). When using af::scan in **inclusive** mode, the result is correct.

I can reproduce with this data (32-bit integers).
1) the input values: [values.txt](https://github.com/arrayfire/arrayfire/files/2619741/values.txt)
2) the result I get (check index 6912): [af_scan_exclusive_result.txt](https://github.com/arrayfire/arrayfire/files/2619740/af_scan_exclusive_result.txt)

Code to reproduce
```c++
int* data = read("values.txt");
auto af_data = af::array(13333, data);
auto af_scan = af::scan(af_data, 0, af::binaryOp::AF_BINARY_ADD, false);
int* scan = new int[13333];
af_scan.host(scan);
write(scan, "af_scan_exclusive_result.txt");
```

My setup
> ArrayFire v3.6.1 (CUDA, 64-bit Linux, build 4fcd0dd)
> Platform: CUDA Toolkit 9.2, Driver: 410.72
> [0] Quadro M2000M, 4043 MB, CUDA Compute 5.0

**Comment by christophe-murphy** [comment]
This appears to be fixed now.
