### ISSUE TITLE
Min function returns different indexes in CPU and OpenCL

### ISSUE THREAD

**Issue by oscartt89** [arrayfire/arrayfire#2088]
When you use the following implementation of the `min` function to retrieve the minimum value of an array and its location:
```C++
AFAPI void af::min(array &val, array &idx, const array & in, const int dim = -1)
```

The index result is different on CPU and OpenCL if the minimum occurs multiple times.

For example, for the array `[0, 1, 2, 3, 0]` with CPU `val` is 0 and `idx` is 0. However, with OpenCL, `val`is 0, but `idx` is 4. I would expect the results to be consistent in the different backends.

We are compiling using the Unified backend.

Environment information:
OS: Mac OS High Sierra 10.13.3
Processor: 2,9 GHz Intel Core i7
Memory: 16GB 2133 MHz LPDDR3
Compiler: Apple LLVM version 9.0.0 (clang-900.0.39.2)
ArrayFire version: 3.5.1 (no-gl) available at [ArrayFire-no-gl-v3.5.1_OSX.pkg](http://www.google.com/url?q=http%3A%2F%2Farrayfire.s3.amazonaws.com%2F3.5.1%2FArrayFire-no-gl-v3.5.1_OSX.pkg&sa=D&sntz=1&usg=AFQjCNHI4uZI-TMTktpEkvVCaWsjmr9O4Q)
OpenCL devices:
0-. AMD Radeon Pro 560 4GB GDDR5
1-. Intel HD Graphics 630 1536MB

**Comment by 9prady9** [comment]
@oscartt89 I don't think our min/max filters do a stable ordering(preserve order of elements in input arrray). There is chance that I am wrong and it is bug, in any case @umar456 can you please confirm if what I said is true or false.

**Comment by umar456** [comment]
Yes, the ordering is not preserved with those operations. You may even get different values from run to run based on how things are scheduled on the device. Guaranteeing that would probably have a performance penalty.

That functionality could only reliably be implemented as a separate function (min_first, min_last, etc...). If you would like something like this please open another issue with that request.

**Comment by pavanky** [comment]
@umar456 ArrayFire may already be guaranteeing the order but may be inconsistent between backends. Can you double check this ?
