### ISSUE TITLE
Examples cmake error with AF 3.6.0 RC1

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#2096]
Hi @umar456 
Little error when cmaking the examples of the RC1 : 
```
cmake .. -DArrayFire_DIR=/tmp/arrayfire-no-gl-3.6.0-rc1/share/ArrayFire/cmake

CMake Error at CMakeLists.txt:22 (file):
   file FILE([TO_CMAKE_PATH|TO_NATIVE_PATH] path result) must be called with
   exactly three arguments.
```

seems to be related to : 
file(TO_NATIVE_PATH ${ASSETS_DIR} ASSETS_DIR)

First should that be named  AF_ASSETS_DIR ?
Then should nt it check if AF_ASSETS_DIR empty before trying to convert it ?

Cheers

**Comment by 9prady9** [comment]
We have a fix for this in https://github.com/arrayfire/arrayfire/pull/2095
You can use the following temporary workaround for master branch examples.
```
cmake .. -DASSETS_DIR:PATH=`pwd`/..
```

**Comment by WilliamTambellini** [comment]
ok thanks @9prady9
