### ISSUE TITLE
Examples OpenCL link failures with AF 3.6.0 RC1 

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#2097]
When trying to make examples with AF 3.6.0 RC1 : 
$ make
Scanning dependencies of target pi_opencl
[  1%] Building CXX object benchmarks/CMakeFiles/pi_opencl.dir/pi.cpp.o
[  1%] Linking CXX executable pi_opencl
/tmp/arrayfire-no-gl-3.6.0-rc1/lib/libafopencl.so.3.6.0: undefined reference to `clReleaseMemObject@OPENCL_1.0'

/tmp/arrayfire-no-gl-3.6.0-rc1/lib/libafopencl.so.3.6.0: undefined reference to `clRetainEvent@OPENCL_1.0'
....

I have at least 2 OpenCL libs on this machine : the one from Intel and the one from nvidia : 
$ sudo locate libOpenCL
/etc/alternatives/opencl-libOpenCL.so
/etc/alternatives/opencl-libOpenCL.so.1
/etc/alternatives/opencl-libOpenCL.so.1.2
/opt/intel/opencl-1.2-4.5.0.8/lib64/libOpenCL.so
/opt/intel/opencl-1.2-4.5.0.8/lib64/libOpenCL.so.1
/opt/intel/opencl-1.2-4.5.0.8/lib64/libOpenCL.so.1.2
/usr/lib64/libOpenCL.so
/usr/lib64/libOpenCL.so.1
/usr/lib64/libOpenCL.so.1.2
/usr/lib64/nvidia/libOpenCL.so
/usr/lib64/nvidia/libOpenCL.so.1
/usr/lib64/nvidia/libOpenCL.so.1.0.0
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libOpenCL.so
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libOpenCL.so.1
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libOpenCL.so.1.0
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libOpenCL.so.1.0.0
/var/lib/alternatives/opencl-libOpenCL.so

Let me turn on verbose makefiles ...

**Comment by 9prady9** [comment]
Examples don't need to be linked with `OpenCL` library directly. OpenCL lib is a transitive dependency here.

Can you please share the outputs of the following commands
`readelf -d <path to your libafopencl.so file>`
`readelf -d <path to the pi_opencl program>`

**Comment by umar456** [comment]
Try deleting the libOpenCL libraries in the CUDA directory. those are known to cause problems. You should download the opencl icd from the Ubuntu repo like this:

```
sudo apt update
sudo apt install ocl-icd-libopencl1
```

**Comment by WilliamTambellini** [comment]
> Examples don't need to be linked with OpenCL library directly. 
Looks they do at least with this RC1

> Can you please share the outputs of the following commands
readelf -d <path to your libafopencl.so file>

`
$readelf -d /tmp/arrayfire-no-gl-3.6.0-rc1/lib/libafopencl.so

Dynamic section at offset 0x3ec6278 contains 34 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libOpenCL.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libmkl_core.so]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libmkl_tbb_thread.so]
 0x0000000000000001 (NEEDED)             Shared library: [libmkl_intel_lp64.so]
 0x0000000000000001 (NEEDED)             Shared library: [libtbb.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
 0x000000000000000e (SONAME)             Library soname: [libafopencl.so.3]
 0x000000000000000c (INIT)               0x44d128
 0x000000000000000d (FINI)               0x27d5b1c
 0x0000000000000019 (INIT_ARRAY)         0x40b4250
 0x000000000000001b (INIT_ARRAYSZ)       2304 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x40b4b50
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x1f0
 0x0000000000000005 (STRTAB)             0x149990
 0x0000000000000006 (SYMTAB)             0x51338
 0x000000000000000a (STRSZ)              2240465 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x40e1e78
 0x0000000000000002 (PLTRELSZ)           290904 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x4060d0
 0x0000000000000007 (RELA)               0x3815a8
 0x0000000000000008 (RELASZ)             543528 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0x381498
 0x000000006fffffff (VERNEEDNUM)         6
 0x000000006ffffff0 (VERSYM)             0x36c962
 0x000000006ffffff9 (RELACOUNT)          4767
 0x0000000000000000 (NULL)               0x0
`



readelf -d <path to the pi_opencl program>
This exec is failing to link so does nt exist.

**Comment by WilliamTambellini** [comment]
> Try deleting the libOpenCL libraries in the CUDA directory. those are known to cause problems. 
My system is currently not pointing to nvidia opencl :  

`
$ ll /usr/lib64/libO*
lrwxrwxrwx 1 root root 37 Jul 13  2017 /usr/lib64/libOpenCL.so -> /etc/alternatives/opencl-libOpenCL.so
lrwxrwxrwx 1 root root 39 Jul 13  2017 /usr/lib64/libOpenCL.so.1 -> /etc/alternatives/opencl-libOpenCL.so.1
lrwxrwxrwx 1 root root 41 Jul 13  2017 /usr/lib64/libOpenCL.so.1.2 -> /etc/alternatives/opencl-libOpenCL.so.1.2
` 

and alternatives is setup to point to Intel OpenCL : 
`
$ alternatives --display opencl-libOpenCL.so
opencl-libOpenCL.so - status is auto.
 link currently points to /opt/intel/opencl-1.2-4.5.0.8/lib64/libOpenCL.so
/opt/intel/opencl-1.2-4.5.0.8/lib64/libOpenCL.so - priority 2147478249
 slave opencl-libOpenCL.so.1: /opt/intel/opencl-1.2-4.5.0.8/lib64/libOpenCL.so.1
 slave opencl-libOpenCL.so.1.2: /opt/intel/opencl-1.2-4.5.0.8/lib64/libOpenCL.so.1.2
Current `best' version is /opt/intel/opencl-1.2-4.5.0.8/lib64/libOpenCL.so.
`

> You should download the opencl icd from the Ubuntu repo like this:\

This is CentOS 6. I have installed : 
 sudo yum install ocl-icd
but still the same linking error.

**Comment by WilliamTambellini** [comment]
I have uninstalled the Intel OpenCL and the nvidia ones.
/usr/lib64/libOpenCL is now the standard ocl-icd one.
Still the same linking error : 

`[  0%] Linking CXX executable pi_opencl
cd /tmp/arrayfire-no-gl-3.6.0-rc1/share/ArrayFire/examples/build/benchmarks && cmake -E cmake_link_script CMakeFiles/pi_opencl.dir/link.txt --verbose=1

/usr/bin/c++     CMakeFiles/pi_opencl.dir/pi.cpp.o  -o pi_opencl -Wl,-rpath,/tmp/arrayfire-no-gl-3.6.0-rc1/lib /tmp/arrayfire-no-gl-3.6.0-rc1/lib/libafopencl.so.3.6.0 

/tmp/arrayfire-no-gl-3.6.0-rc1/lib/libafopencl.so.3.6.0: undefined reference to clReleaseMemObject@OPENCL_1.0 
...
`

To move forward, as libafopencl.so (at least in 3.6 RC1) is needing libOpenCL, how are examples supposed to link without a '-lOpenCL' directive ?

**Comment by 9prady9** [comment]
As I have mentioned earlier, `OpenCL` is a transitive dependency and the examples themselves don't need the `-lOpenCL` link directive. However, the library itself is definitely needed and we have addressed this in https://github.com/arrayfire/arrayfire/pull/2105 and the fix is in master now. 

If you are generating the installer using the current master, please note that you have to set the cmake variable `AF_INSTALL_STANDALONE` to `ON` as follows to package all the necessary dependencies into the installer script.
```
cmake .. -DAF_INSTALL_STANDALONE:BOOL=ON
```
