### ISSUE TITLE
Degraded performance for random array access (compared to native arrays)

### ISSUE THREAD

**Issue by vineelpratap** [arrayfire/arrayfire#2098]
Hi,
 I have noticed this when I was porting one of my projects (which is written in C++) to arrayfire so that it works efficiently on all platforms. I need to write a dynamic programming code where I have use values at time `t-1` for computing values at time `t`. But it seems accessing memory randomly in arrayfire is very inefficient when compared to native C++ arrays. While arrayfire is not specifically optimized for random array access, can I make the code atleast as efficient as native C++ arrays. 
Here is the code which can be used to test - 

```
#include <iostream>
#include "arrayfire.h"
int main() {
  af::info();
  int num_elem = 100000;
  int stride = 100;
  int numtrys = 100;

  // Initialize
  auto A = af::randu(num_elem, af::dtype::s32);
  int B[num_elem];
  for (auto i = 0; i < num_elem; ++i) {
    B[i] = rand();
  }

  // Native arays
  auto t1 = af::timer::start();
  for (auto t = 0; t < numtrys; ++t) {
    for (auto i = stride; i < num_elem; i += stride) {
      B[i] += B[i - stride];
    }
  }
  auto t2 = af::timer::stop(t1);
  std::cout << "Print so that the operations are executed for sure "
            << "and no weird optimizations occur " << B[num_elem - 1] << "\n";
  std::cout << "| Time taken for element access using native arrays "
            << t2* 1000 / numtrys << "msec\n";


  // Arrayfire arrays
  af::sync();
  auto t3 = af::timer::start();
  for (auto t = 0; t < numtrys; ++t) {
    for (auto i = stride; i < num_elem; i += stride) {
      A(i) += A(i - stride);
    }
  }
  A.eval();
  auto t4 = af::timer::stop(t3);
  std::cout << "| Time taken for element access using arrayfire arrays "
            << t4 * 1000/ numtrys  << "msec\n";

  return 0;
}

```

Output (with Arrayfire running on CPU): 
```
ArrayFire v3.6.0 (CUDA, 64-bit Linux, build default)
Platform: CUDA Toolkit 8, Driver: 375.39
[0] Tesla M40, 11443 MB, CUDA Compute 5.2
-1- Tesla M40, 11443 MB, CUDA Compute 5.2
Print so that the operations are executed for sure and no weird optimizations occur 660658275
| Time taken for element access using native arrays 0.00222msec
| Time taken for element access using arrayfire arrays 42.9094msec
```

Output (with Arrayfire running on GPU): 
```
ArrayFire v3.6.0 (CUDA, 64-bit Linux, build default)
Platform: CUDA Toolkit 8, Driver: 375.39
[0] Tesla M40, 11443 MB, CUDA Compute 5.2
-1- Tesla M40, 11443 MB, CUDA Compute 5.2
Print so that the operations are executed for sure and no weird optimizations occur 660658275
| Time taken for element access using native arrays 0.00222msec
| Time taken for element access using arrayfire arrays 33.6345msec
```

**Comment by pavanky** [comment]
You are not using arrayfire as it is intended. The library does not magically make sequential code into a high performant one.

Try replacing:
```
 for (auto i = stride; i < num_elem; i += stride) {
      A(i) += A(i - stride);
    }
```

with 
```
auto seq = af::seq(stride, num_elem, stride);
A(seq) += A(seq - stride);
```

**Comment by pavanky** [comment]
Also don't forget to add `af::sync()` before starting and stopping the timers.

**Comment by pavanky** [comment]
ok, I just realized, the code, I suggested earlier doesn't work.
Another solution is this:

```
A =  af.moddims(A, af::dim4(stride, num_elem / stride));
A = af::accum(A, 1);
```

**Comment by vineelpratap** [comment]
Hi Pavan, 
 Thanks for the reply. The code I wrote above it just to show the point. It is not the original code I'm intending to write. 
 
```
> The library does not magically make sequential code into a high performant one.
```
As I mentioned, my code is a DP - so the operations need to be sequential. I just want my code to be as efficient as native C++ array.

**Comment by vineelpratap** [comment]
Okay. 

I was trying to implement a variant of Viterbi algorithm and really wanted to do this using AF operations since I was operating on AF arrays. Based on your comments, I guess now I will have to get the device pointers for the array and work on them. 

Thanks !
