### ISSUE TITLE
Inconsistency in CMake variables

### ISSUE THREAD

**Issue by FloopCZ** [arrayfire/arrayfire#2099]
This is a low priority. Recently, there has been a change in the `CMakeLists.txt` prefixing most of the variables with `AF_` prefix. Some of the variables, however, are still using their old name. I know about two - `OPENCL_BLAS_LIBRARY` and `BUILD_TESTING`. Was it intentional or just an oversight? Thank you.

**Comment by 9prady9** [comment]
@FloopCZ 

Regarding `BUILD_TESTING` variable - it is created by gtest suite and ArrayFire's CMake doesn't cache this variable so we can't do anything about this one. We can mask this with another variable in ArrayFire CMakeLists.txt file but it would just add one more unncessary variable I believe.

I think @umar456 left out the upstream project options like `MKL_THREAD_LAYER` & `OPENCL_BLAS_LIBRARY` to have the dependency as it's their prefix or may be he just missed them. 

But there are few variables(other than `CMAKE` prefixed) that can be marked as advanced, I believe.

**Comment by FloopCZ** [comment]
Thank you for the information @9prady9. I just wanted to to make sure that this was intentional before v3.6 is released, because changing CMake variable names means some extra digging for quite a few Linux package maintainers.

**Comment by 9prady9** [comment]
The package maintainers would still be able to use old variables too. If
old variables are used a deprecation warning is thrown and the project file
generation wouldn't be effected.
