### ISSUE TITLE
Problem running deep_belief_net/rbm with OpenCL/CUDA

### ISSUE THREAD

**Issue by chrispikula** [arrayfire/arrayfire#2113]
I'm running windows 10, with a GTX 1050.  Visual Studio 2015.  I also have ArrayFire 3.5.1
CUDA Toolkit 8, Driver: CUDA Driver Version: 9010

When I build, from source, the example for the deep_belief_net as a CPU release, it runs fine.
When I build as CDUA release, and run, I get the following output:

```
** ArrayFire DBN Demo **

Training Hidden Layer 0
ArrayFire Exception (Internal error:998):
In function class std::vector<char, class std::allocator<char> > __cdecl cuda::compileToPTX(const char *, class std::basic_string<char, struct std::char_traits<char>,class std::allocator<char> >)
In file src\backent\cuda\jit.cpp:291
NVRTC Error(6): NVRTC_ERROR_COMPILATION

In function class af::array __cdecl af::matmul(const class af::array &, const class af::array &, const af_mat_prop, const af_mat_prop)
In file src\api\cpp\blas.cpp:20
```

I get the same error when I try to build and run the rbm example as well.

When I build deep_belief_net as OpenCL, and run, I get the following output:
```

**ArrayFire DBN Demo**

Training Hidden Layer 0
ArrayFire Exception (Internal error:998):
OpenCL Error (-11): Build Program Failure when calling clBuildProgram
In function class af::array __cdecl af::matmul(const class af::array &, const class af::array &, const af_mat_prop, const af_mat_prop)
In file src\api\cpp\blas.cpp:20
```

I haven't modified the code of the examples in any way, nor have I made any changes to my ArrayFire installation.
The examples for neural_network, knn, and logistic_regression all run when I try them with OpenCL/CUDA/CPU builds.

**Comment by WilliamTambellini** [comment]
Try to play with JIT MAX LEN : 
http://arrayfire.org/docs/configuring_environment.htm

**Comment by chrispikula** [comment]
So I've gone into the Windows Environment Variables, and set the System Variable  AF_OPENCL_MAX_JIT_LEN to 50 and AF_CUDA_MAX_JIT_LEN to 50.  After a restart, both the OpenCL and CUDA demos worked perfectly.  Thanks!
