### ISSUE TITLE
Bug in min with NAN values

### ISSUE THREAD

**Issue by j-kallwies** [arrayfire/arrayfire#2130]
The following code
```
float data[] = { 1, NAN, 5, 0.1, NAN, -0.5, NAN, 0 };

af::array A( 4, 2, data );
af::print( "A:", A );

af::array min_val;
af::array min_idx;
af::min( min_val, min_idx, A );

af::array min = af::min( A );

af::print( "min_val:", min_val );
af::print( "min_idx:", min_idx );
af::print( "min:", min );
```

produces the following output for me (ArrayFire 3.5.1, Linux):
```
A:
[4 2 1 1]
    1.0000        nan 
       nan    -0.5000 
    5.0000        nan 
    0.1000     0.0000 

min_val:
[1 2 1 1]
    1.0000        nan 
min_idx:
[1 2 1 1]
         0          0 
min:
[1 2 1 1]
    0.1000    -0.5000
```

Obviously, the result of `af::min` for getting minimum values and their locations in an array is wrong. Whereas, the result of `af::min` just returning the minimum values is correct.
The documentation claims to ignore NaN values for both variants: http://arrayfire.org/docs/group__reduce__func__min.htm#ga4f4b4607803d8fd4fea8e862d3685d15

The problem does _not_ occur if _no NaN value_ is present in the array.

I would also suggest adding a new test covering this case.

**Comment by mark-poscablo** [comment]
Ran this on my Windows machine on the different backends - I'm getting the same result for CUDA and OpenCL, but for the CPU it's a little different. The CPU is producing the correct value for the first column, but the second column is still getting NaN as the min value. In any case they all do exhibit behavior different from what the doc claims.

Here's what I got:
```
ArrayFire v3.5.1 (CPU, 64-bit Windows, build 0a675e8)
[0] Intel: Intel(R) Core(TM) i7-4712HQ CPU @ 2.30GHz, 16307 MB, Max threads(8)
A:
[4 2 1 1]
    1.0000  -nan(ind)
 -nan(ind)    -0.5000
    5.0000  -nan(ind)
    0.1000     0.0000

min_val:
[1 2 1 1]
    0.1000  -nan(ind)
min_idx:
[1 2 1 1]
         3          0
min:
[1 2 1 1]
    0.1000    -0.5000
	
ArrayFire v3.5.1 (CUDA, 64-bit Windows, build 0a675e8)
Platform: CUDA Toolkit 8, Driver: CUDA Driver Version: 9010
[0] GeForce GTX 850M, 4096 MB, CUDA Compute 5.0
A:
[4 2 1 1]
    1.0000  -nan(ind)
 -nan(ind)    -0.5000
    5.0000  -nan(ind)
    0.1000     0.0000

min_val:
[1 2 1 1]
    1.0000  -nan(ind)
min_idx:
[1 2 1 1]
         0          0
min:
[1 2 1 1]
    0.1000    -0.5000
	
ArrayFire v3.5.1 (OpenCL, 64-bit Windows, build 0a675e8)
[0] NVIDIA: GeForce GTX 850M, 4096 MB
-1- INTEL: Intel(R) HD Graphics 4600, 1982 MB
-2- INTEL: Intel(R) Core(TM) i7-4712HQ CPU @ 2.30GHz, 16307 MB
A:
[4 2 1 1]
    1.0000  -nan(ind)
 -nan(ind)    -0.5000
    5.0000  -nan(ind)
    0.1000     0.0000

min_val:
[1 2 1 1]
    1.0000  -nan(ind)
min_idx:
[1 2 1 1]
         0          0
min:
[1 2 1 1]
    0.1000    -0.5000
```

**Comment by mark-poscablo** [comment]
@j-kallwies The fix for this issue is in, please let us know if you experience any more problems regarding this. Thanks!
