### ISSUE TITLE
Input checking in af::sparse

### ISSUE THREAD

**Issue by rstub** [arrayfire/arrayfire#2134]
This report is motivated by https://stackoverflow.com/questions/49867065/arrayfire-sparse-matrix-issues. In that SO post the OP used input in effectively COO format to create a sparse matrix in CSR format:
```
int row[] = {0,0,0,1,1,2,2};
int col[] = {0,1,2,0,1,0,2};
double values[] = { 3,3, 4,3,10,4,3};
array rr = sparse(3,3,array(7,values),array(7,row),array(7,col));
af_print(rr);
af_print(dense(rr));
```
One can fix this by either using the correct row indices:
```
int row[] = {0,3,5,7};
int col[] = {0,1,2,0,1,0,2};
float values[] = {3,3,4,3,10,4,3};
array rr = sparse(3,3,array(7,values),array(4,row),array(7,col));
af_print(rr);
af_print(dense(rr)); 
```
or the correct format:
```
int row[] = {0,0,0,1,1,2,2};
int col[] = {0,1,2,0,1,0,2};
float values[] = { 3,3, 4,3,10,4,3};
array rr = sparse(3,3,array(7,values),array(7,row),array(7,col), AF_STORAGE_COO);
af_print(rr);
af_print(dense(rr));
```
But why did the OP not get an error when trying to create a CSR matrix with incorrect input?

**Comment by pavanky** [comment]
@rstub short of going through the entire `row` and checking if the elements are sorted, there is no easy way to verify COO vs CSR.

For example

```
```

**Comment by pavanky** [comment]
@rstub Ok I did not realize this was broken. Do you want to send in a patch to fix this ?

**Comment by rstub** [comment]
@pavanky I have created test cases and parameter validation here: https://github.com/RInstitute/arrayfire/tree/sparse
The new tests fail with the current version but succeed with my changes. However, now some other tests are failing, e.g.:

```
[ RUN      ] Sparse/0.DeepCopy
/home/ralf/devel/arrayfire/test/testHelpers.hpp:455: Failure
      Expected: 0u
      Which is: 0
To be equal to: alloc_buffers
      Which is: 9
/home/ralf/devel/arrayfire/test/sparse.cpp:205: Failure
      Expected: size_of_alloc * 2
      Which is: 24576
To be equal to: lock_bytes
      Which is: 15360
The number of bytes allocated by the deep copy do not match the original array
/home/ralf/devel/arrayfire/test/sparse.cpp:209: Failure
      Expected: buffers_per_sparse * 2
      Which is: 24
To be equal to: lock_buffers
      Which is: 15
The number of buffers allocated by the deep copy do not match the original array
[  FAILED  ] Sparse/0.DeepCopy, where TypeParam = float (6 ms)
``` 
Do you know what's going on here? Or should I open a PR anyway to discuss this?

**Comment by pavanky** [comment]
@rstub you will need to destroy the `af_array` you created in the tests. 

Also why not use the C++ API for the tests instead?

**Comment by pavanky** [comment]
@rstub If you want to test for the failure cases, use `EXPECT_THROW` which should work with C++ API.

**Comment by 9prady9** [comment]
@pavanky For tests, we are using C-API alone. I don't remember the exact reason behind it but @umar456 can elaborate on that.

**Comment by rstub** [comment]
@pavanky Thanks, using `af_release_array()` helped. BTW, I used the C API because I used the test ISSUE_1745 as starting point ...
