### ISSUE TITLE
Error finding package on windows

### ISSUE THREAD

**Issue by TianBo-Timothy** [arrayfire/arrayfire#2144]
I assume the included examples are supposed to be able to be built with cmake on windows as there is `IF(WIN32)` statement in the CMakeLists.txt file. However, when I was trying to build the example projects with cmake on windows, I got the following error message:

> c:\Tools\arrayfirev3\examples>cmake -G "Visual Studio 12 2013" .
CMake Error at CMakeLists.txt:27 (FIND_PACKAGE):
>  Could not find a configuration file for package "ArrayFire" that is
  compatible with requested version "".
>
>  The following configuration files were considered but not accepted:
>
>    c:/Tools/arrayfirev3/cmake/ArrayFireConfig.cmake, version: 35 (64bit)
>    C:/Tools/arrayfirev3/cmake/ArrayFireConfig.cmake, version: 35 (64bit)
>    C:/Tools/arrayfirev3/cmake/ArrayFireConfig.cmake, version: 35 (64bit)
>
>
>
> -- Configuring incomplete, errors occurred!
> See also "C:/Tools/arrayfirev3/examples/CMakeFiles/CMakeOutput.log".
> See also "C:/Tools/arrayfirev3/examples/CMakeFiles/CMakeError.log".

I have read the issue #1989 , but I don't think it is relevant.

Can anyone point out what is missing here?

**Comment by 9prady9** [comment]
Hi, the generator `"Visual Studio 12 2013` is for 32 bit applications. You should be able to find another generator by the name `Visual Studio 12 2013 Win64`. On command line, just append the Win64 towards the end with a space before it. To check what generators are available on your system , run `cmake --help` , towards the end of the help text you will find all the available generators. 

Note that the ArrayFire binaries provided on our website are 64 bit.

**Comment by TianBo-Timothy** [comment]
Thanks for the fast response.

I tried the generator "Visual Studio 12 2013 Win64" and got the following error:

> C:\Tools\arrayfirev3\examples>cmake -G "Visual Studio 12 2013 Win64"
> -- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0 (found version "8.0")
-- EXAMPLES: CPU backend is ON.
-- EXAMPLES: UNIFIED backend is ON.
-- EXAMPLES: CUDA backend is ON.
-- EXAMPLES: OPENCL backend is ON.
> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> CUDA_cublas_LIBRARY (ADVANCED)
>    linked by target "example_brain_segmentation_cuda" in directory C:/Tools/arrayfirev3/examples
>    linked by target "example_naive_bayes_cuda" in directory C:/Tools/arrayfirev3/examples
>    linked by target "example_edge_cuda" in directory 
> ...

I checked `CUDA_cublas_LIBRARY`, which is indeed set as `CUDA_cublas_LIBRARY-NOTFOUND`.

I then checked `CUDA_TOOLKIT_ROOT_DIR`, which is correctly set to `C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0`. 

When I checked `CMAKE_SIZEOF_VOID_P`, I noticed it is 4, which I think should be 8 as I am building for win64. But I do not have any idea how could it be incorrect. Can you please give a suggestion to solve the problem?

**Comment by TianBo-Timothy** [comment]
It works now after a few retries... I am not sure what was wrong before.

Anyways, we can close the issue now.
