### ISSUE TITLE
Doesn't compile with gcc 8.1

### ISSUE THREAD

**Issue by svenstaro** [arrayfire/arrayfire#2148]
I get this when trying to compile arrayfire using gcc 8.1: 
[log.txt](https://github.com/arrayfire/arrayfire/files/1981762/log.txt)

**Comment by 9prady9** [comment]
@svenstaro I have sent a PR with the fix for errors I got on Arch GCC8.1. Please use test that patch on your  machine to check if the problem is fixed for you also.
