### ISSUE TITLE
Compilation of arrayfire fails with "is not defined for option std"

### ISSUE THREAD

**Issue by anates** [arrayfire/arrayfire#2151]
I tried to compile the current version of ArrayFire with Cuda 9 & GCC 7, but I get the following error:
`Value 'c++11 -Xcompiler -fPIC -Xcudafe "--diag_suppress=1427"' is not defined for option 'std'`
from nvcc. 
Could it be related to the fact that GCC 7 and Cuda 9 are not officially compatible? Or is there another problem behind?

**Comment by 9prady9** [comment]
I am not sure about the error you are seeing. But you wont be able to compile CUDA backend with GCC 7. You would have to set `CMAKE_CUDA_HOST_COMPILER` to `/usr/bin/gcc-6` if you have GCC6 on your machine or any other GCC that is lower than 7.

**Comment by anates** [comment]
Hmm, I thought it would work, after everything else related to CUDA also works with GCC 7 (with some small hacks). Any other possibility to circumvent the problem without having to install GCC 6?

**Comment by FloopCZ** [comment]
The compiler support is unfortunate. See https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html for the list of supported compilers, not even all versions of GCC6 are actually supported (e.g., gcc 6.4.1 distributed with Arch).

**Comment by 9prady9** [comment]
@anates Don't you have any other version of gcc by any chance ? Which linux distribution is this ? Ubuntu 18.04 ?

**Comment by anates** [comment]
Tumbleweed. Yes, I could install another version, but I would prefer other solutions first, if possible (if not, then I will continue with the CPU module, the PC is for testing only anyway)

**Comment by 9prady9** [comment]
@anates I am closing the issue as it is not related to ArrayFire's build failure. If you are facing any build issues with ArrayFire, feel free to open an issue.
