### ISSUE TITLE
Upgrade to cuda 9.2

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#2172]
From
https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html

The CUDA 9.2 release includes speed-ups for launching CUDA kernels as well as faster performance for GEMM computational performance for half-precision and small N matrices. CUDA 9.2 also fixes a number of issues, including incorrect results with some GEMM calls on V100 Tensor Core GPUs and other BLAS problems.

The CUDA 9.2 release does depend upon the latest NVIDIA 396 series driver. As of writing, NVIDIA has yet to put out a blog post outlining any other changes beyond what is found in the release notes. 

Perhaps possible for AF 3.6.1 ?
Cheers

**Comment by mlloreda** [comment]
@WilliamTambellini, we've updated to CUDA 9.2 in v3.6.1.
