### ISSUE TITLE
ArrayFire 3.6 tries to use CUDA for unsupported graphic card

### ISSUE THREAD

**Issue by net147** [arrayfire/arrayfire#2181]
The official Windows 64-bit ArrayFire 3.6 installers do not support CUDA Compute older than 3.0.
Using ArrayFire 3.6 with GeForce GTX 560, it will automatically select CUDA as the backend but throw an exception when it tries to use it.

af::info() prints:
ArrayFire v3.6.0 (CUDA, 64-bit Windows, build ee21c79)
Platform: CUDA Toolkit 9, Driver: CUDA Driver Version: 9000
[0] GeForce GTX 560, 1024 MB, CUDA Compute 2.1

af::exception, e.what() gives:
ArrayFire Exception (Internal error:998):
In function void cuda::kernel::transpose<T, conjugate>(cuda::Param<T>, cuda::CParam<T>, int)
In file C:/Users/buildbot/bb-worker/windows-nvidia-01/windows-nightly/build/src/backend/cuda\kernel/transpose.hpp:116
CUDA Error (48): no kernel image is available for execution on the device

Should the backend detection only select CUDA if the graphics card is supported - perhaps by checking the compute version against the settings used to compile ArrayFire?

**Comment by 9prady9** [comment]
There are couple of things here:
* CUDA 9.0 stops supporting compute Fermi(compute 2.*) cards.
* The prebuilt binaries on our website are built with 9.0 and thus wont work for 2.* cards.

You should be able to use the Fermi GPU via OpenCL I believe. Try setting the backend using 
`af::setBackend(AF_BACKEND_OPENCL)` as the first statement in your code.

**Comment by net147** [comment]
OpenCL is working. Should ArrayFire do this automatically instead of trying to use CUDA with unsupported card?

**Comment by 9prady9** [comment]
Interesting, Can you check if which device OpenCL is running on ? Is it the Fermi card ?

**Comment by net147** [comment]
Here is af::info() output when the backend is set to OpenCL:
ArrayFire v3.6.0 (OpenCL, 64-bit Windows, build ee21c79)
[0] NVIDIA: GeForce GTX 560, 1024 MB
-1- INTEL: Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz, 10174 MB

**Comment by net147** [comment]
It is definitely using the GPU as "GPU Load" in GPU-Z is more than 70% when using ArrayFire with OpenCL.

**Comment by 9prady9** [comment]
Nice, OpenCL backend is working as I initially expected. Yeah, we should probably do some checks against the CUDA version and supported compute versions. I will look into it, thanks for reporting it!
