### ISSUE TITLE
master branch broken

### ISSUE THREAD

**Issue by FilipeMaia** [arrayfire/arrayfire#2187]
The master branch currently cannot compile as `AF_API_VERSION_CURRENT` is set to 34 while the code assumes 36. I think it would be good to update `AF_API_VERSION_CURRENT` in master to make it compile.

**Comment by 9prady9** [comment]
What is the hash for the latest commit on your master ? The master has been already updated to 3.7 in [this](https://github.com/arrayfire/arrayfire/commit/43458564df6bc6bd1d94a1c112da9bcb5981bc5d) commit.

**Comment by FilipeMaia** [comment]
I just realised that version.h is generated dynamically. But it doesn't seem to be overwritten. So if I just pull the repository and compile it again I end up with the old defines, I think...

**Comment by FilipeMaia** [comment]
BTW the latest commit is 473635ce7bd0f0f211aae711eafe0dfa8573d2a4

**Comment by FilipeMaia** [comment]
I see, during build no version.h is generated in the source directory. But maybe it used to be in older version. Anyway i've fixed the problem by removing the file.

**Comment by 9prady9** [comment]
`version.h` is dynamically generated and it is generated during configure step carried out by cmake. If you have pulled on the repo, `cmake ..` should have updated the autogenerated header. It works as expected on many machines I develop.

**Comment by FilipeMaia** [comment]
Yea it works fine. I think what may have happened was that an old version of arrayfire generated the version.h on the source tree. And that shadowed the one generated in the build directory. After I remove the one from the source directory it all was fine.

**Comment by 9prady9** [comment]
Yeah, that should be it. We moved the generated version.h to build tree as
that is the appropriate location for generated files.
