### ISSUE TITLE
Suppress OpenCL and clFFT warnings

### ISSUE THREAD

**Issue by net147** [arrayfire/arrayfire#2195]
ArrayFire should suppress warnings from the OpenCL runtime (e.g. Intel OpenCL runtime for Intel Core and Xeon processors 16.1.2, pocl 1.1) like:
``
4 warnings generated.
``
and from clFFT like:
``
Warning:  Program terminating, but clFFT resources not freed.
Please consider explicitly calling clfftTeardown( ).
``

These warning messages aren't really useful so they should be suppressed by default.

**Comment by 9prady9** [comment]
@net147 Those warnings are being printed by clFFT and not from ArrayFire code base. We have looked into it in the past and there isn't much we can do inside ArrayFire code to suppress it.

**Comment by net147** [comment]
@9prady9 ArrayFire is using a fork of clFFT (https://github.com/arrayfire/clFFT). Could clFFT be adapted to make this possible either upstream or in the fork?

**Comment by 9prady9** [comment]
Yeah, I guess it is possible to remove the relevant print statements from our fork, but I am not sure if it is good/bad idea. @umar456 What are your thoughts ? From what I see in the fork's history, we never made modifications to it - it is just there for redundancy. Personally I would like to avoid touching upstream code and let them fix it. But in this case, clFFT hasn't seen any releases or commits in almost an year.

May I know why are you concerned over these warnings ? as they say, they are only warnings and printed towards the exit.

**Comment by net147** [comment]
It is just unnecessary noise in my test program output.

**Comment by 9prady9** [comment]
If you are building arrayfire from master, then you can easily apply patch to the relevant file from clFFT and suppress the warnings.

**Comment by net147** [comment]
I am just precompiled releases.

**Comment by umar456** [comment]
We should modify the fork to suppress the warnings. ArrayFire shouldn't be printing anything on the screen.

**Comment by 9prady9** [comment]
@net147 Do you want to submit a PR to clfft fork of arrayfire ?

**Comment by net147** [comment]
@9prady9 Ok. I will prepare the PR.

**Comment by net147** [comment]
@9prady9 I had a look at suppressing the "warnings generated" message but I was unable to find a way to do it. I tried passing "-w" as options argument for clBuildProgram in https://github.com/arrayfire/clFFT/blob/arrayfire-release/src/library/enqueue.cpp#L758  but it did not work.

**Comment by net147** [comment]
I have created the pull request: https://github.com/arrayfire/clFFT/pull/4

**Comment by 9prady9** [comment]
Addressed in https://github.com/arrayfire/clFFT/pull/4
