### ISSUE TITLE
ARG_ASSERT should accept formatted messages

### ISSUE THREAD

**Issue by umar456** [arrayfire/arrayfire#2198]
ARG_ASSERT currently accepts the argument number and a predicate. This is not sufficient to express a meaningful error message. We need to be able to create messages that are easy to parse by the user and express the values that are incorrect.

Current version:
```
ARG_ASSERT(2, dim < 3);
```

Proposal
```
ARG_ASSERT(2, dim < 3, "Invalid dimension. dim has a value of {}.", dim);
```

This can be done using the fmt library for formatting.

**Comment by 9prady9** [comment]
`fmtlib` is not available on Arch pacakge manager or Ubuntu 16.04. Although, it is available on 18.04. That leaves two options:
1. Add it as an external project and link against it.
2. Submodule it and build fmtlib as part of ArrayFire source.

**Comment by FloopCZ** [comment]
@9prady9 If you want something from the repositories, there is `boost::format`. `fmtlib` is preferred, but `boost::format` is probably easier to depend on (at the moment).

A very simple, but hacky solution with no dependencies would be to define the `ARG_ASSERT` similarly to this:
```c++
#include <sstream>

struct ARG_ASSERT {
    bool cond_;
    std::stringstream ss_;

    ARG_ASSERT(bool cond)
      : cond_{cond}
    { }

    template<typename T>
    ARG_ASSERT& operator<<(const T& value)
    {
        ss_ << value;
        return *this;
    }

    ~ARG_ASSERT()
    {
        if (!cond_) throw std::runtime_error{ss_.str()};
    }
};
```

And use it like this:
```c++
int main()
{
    ARG_ASSERT(true) << "Everything ok.";
    ARG_ASSERT(false) << "Invalid argument a=" << 5 << ".";
}
```

**Comment by umar456** [comment]
@FloopCZ I have seen this pattern in logging libraries but I don't think it will work well as an assert. We will need to limit the scope of it by wrapping it with braces in order to throw an exception when its called.

We can probably implement this using simple printf. We probably shouldn't bring in fmtlib unless it's going to add a lot of functionality. Although the logging library we are using already brings in fmtlib.

**Comment by FloopCZ** [comment]
>  We will need to limit the scope of it by wrapping it with braces in order to throw an exception when its called.

That should not be necessary. As long as you don't name the variable, the object will be only temporary and will get destroyed as soon as it reaches the semicolon.
```c++
ARG_ASSERT(true) << "Everything ok";  // good, temporary, will get destroyed immediately
ARG_ASSERT my_assertion(true) << "Everything ok";  // bad, will get destroyed at the end of the scope
````

But sure, there are more approaches and if you already build and use `fmtlib`, maybe that is the best way to go. `printf` and variadic arguments is also a viable possibility for sure.

**Comment by umar456** [comment]
Ahh right I didn't read it like that.

The other reason I don't like this approach is that you will need to build the string every time even if the assertion is true. With the macro approach, you can perform all the operations and string generation inside the condition which checks the assertion.

I am closing this issue and I have expanded the scope to #2274. That PR should cover many of the use cases encountered in the current ArrayFire source code.
