### ISSUE TITLE
stdev/mean RAM leak in CUDA and OPENCL backends

### ISSUE THREAD

**Issue by matkraj** [arrayfire/arrayfire#2203]
The following code generates memory leak. There is no obvious output to RAM in it. It does it for mean and stdev functions, regardless of specified dimension. Memory chart for the process is a nice linear function.
_CUDA 9.1, Ubuntu 18.04, ArrayFire v3.6 binary_
edit: happens with OPENCL too but not in CPU backend
```
af::array R = af::randu(100,100);
af::array meanR;
for (int x; x<1e9;x++){
   meanR = af::mean(R);
}
```
![image](https://user-images.githubusercontent.com/32445707/41582653-8e710de6-73e5-11e8-8f49-efbec29f738b.png)

**Comment by 9prady9** [comment]
There are couple of leaks that we fixed in https://github.com/arrayfire/arrayfire/pull/2201/ Can you please wait for 3.6.1 fix release. We will soon do a 3.6.1 release.

**Comment by matkraj** [comment]
All good in v3.6.1
