### ISSUE TITLE
grid x,y coordinates are not consistent when plotted

### ISSUE THREAD

**Issue by 9prady9** [arrayfire/arrayfire#2204]
I am trying to use window.grid in an organised way, but the images seem to be placed in the window by a different key than `.grid(a,b)`. I tried to swap x,y in myWindow(x,y) which results in overlapping images.

code:

```
unsigned int gridx = 5;
unsigned int gridy = 2;
af::Window myWindow(gridx*64,gridy*64,"disk");
myWindow.grid(gridy,gridx);

myWindow(0,0).image(disk, "0,0 disk");
myWindow(0,1).image(disk, "0,1 disk");
myWindow(0,2).image(disk, "0,2 disk");
myWindow(0,3).image(disk, "0,3 disk");
myWindow(0,4).image(disk, "0,4 disk");

myWindow(1,0).image(disk, "1,0 disk");
myWindow(1,1).image(disk, "1,1 disk");
myWindow(1,2).image(disk, "1,2 disk");
myWindow(1,3).image(disk, "1,3 disk");
myWindow(1,4).image(disk, "1,4 disk");

myWindow.show()
```
results in:
![image](https://user-images.githubusercontent.com/32445707/41636128-f8dba22c-748f-11e8-9160-522834a8bd92.png)

Originally reported in https://github.com/arrayfire/forge/issues/181 by @matkraj

**Comment by matkraj** [comment]
if not enough disks are called e.g grid is 3,2 but I only call 3 images it still does not place them in right coordinates

**Comment by matkraj** [comment]
I just realised this only applies to histograms. I will give example but the https://github.com/arrayfire/arrayfire/pull/2207/commits/dbd3c1ff1702015609e3ce3933ce39e6bb0dfaf4
doesn't include histogram fix

**Comment by matkraj** [comment]
https://github.com/arrayfire/arrayfire/blob/c26152fc46678f59fa516802e26f8fb4532ee451/src/api/c/hist.cpp#L114

**Comment by 9prady9** [comment]
Sorry about it, I missed this file. I will send in a fix for this.

**Comment by 9prady9** [comment]
I have addressed the missing fix in https://github.com/arrayfire/arrayfire/pull/2230 Thank you for reporting the issues!

**Comment by matkraj** [comment]
No problem, thanks!
