### ISSUE TITLE
Backend support: CPU missing with OpenCL backend (OSX)

### ISSUE THREAD

**Issue by MathInside** [arrayfire/arrayfire#2210]
Dear Arrayfire developers,

Arrayfire version: 3.6.0 (build ee21c791)
OS: OSX (Sierra 10.12.6)
CPU: Intel i5-3210M
GPU: Intel HD4000 (no dedicated GPU)

I have installed Arrayfire from the given installer. However, when testing the installation (as proposed in http://arrayfire.org/docs/installing.htm), only the HD4000 gpu is detected by the OpenCL backend.
CPU backend works fine, as well as the OpenCL backend with the HD4000 (except a warning 'clFFT resources not freed' in helloworld, but I guess it is due to the HD4000's specificty).

How can the CPU be targeted using Arrayfire's OpenCL backend ? Isn't OpenCL runtime packed with OSX ?

Thank you for your help.

**Comment by pavanky** [comment]
1) OpenCL support by apple has been atrocious. Especially for the CPU devices.

2) Apple is [deprecating OpenCL and OpenGL](https://developer.apple.com/macos/whats-new/). 

Given this, I dont think this issue can ever be solved.
