### ISSUE TITLE
Missing DLL's on runtime

### ISSUE THREAD

**Issue by solyuina** [arrayfire/arrayfire#2220]
Hello! 
I am currently using Windows 10 and Microsoft Visual Studio 2017 (Community). After installing ArrayFire with the available Windows binary (using the option to include ArrayFire to PATH), I am able to successfully compile the ArrayFire helloworld example in Visual Studio. However, I cannot run the example due to an error that states "The code execution cannot proceed because [afcpu.dll/afcuda.dll] was not found. Reinstalling the program may fix this problem." 
This error message persists despite changing which .lib is included in the Visual Studio linker settings, and even reinstalling ArrayFire does not help. Is there any solution to this problem? I have not been able to find support on this problem online.
Thank you!

**Comment by umar456** [comment]
Can you print out the PATH variable and make sure it's pointing to the correct directory? It should be pointing to the directory with the DLL files.

**Comment by solyuina** [comment]
The PATH variable is currently set to: `%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;C:\Program` Files\Microsoft VS Code\bin;C:\Program Files\ArrayFire\v3\lib;` 
I can confirm that C:\Program Files\ArrayFire\v3\lib includes all necessary .lib and .dll files.

**Comment by 9prady9** [comment]
Can you please try loading your example program exe using [dependency walker ](http://www.dependencywalker.com/)and check which dlls are being found and not-found.

**Comment by solyuina** [comment]
I found that reinstalling Microsoft Visual Studio 2013 runtime executables fixed the problem!
