### ISSUE TITLE
const type vars cause `illegal hardware instruction` fault when arrayfire tries to init from it

### ISSUE THREAD

**Issue by lu4** [arrayfire/arrayfire#2232]
**Platform/OS/Language:** Apple, MacOS High Sierra, 10.13.5, C++
**ArrayFire:** ArrayFire v3.6.0 (OpenCL, 64-bit Mac OSX, build ee21c791)
**Hardware info:**
[0] APPLE: GeForce GT 650M, 1024 MB
-1- APPLE: HD Graphics 4000, 1536 MB

**Build tool:** CMake
**Compiler (used by cmake) path:** /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
**Compiler (used by cmake) info:**
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**XCode: ** Version 9.4.1 (9F2000)

**Failing test case:**
```
#include <arrayfire.h>

int main(int argc, char ** argv)
{
    const float x[] = { 1.0F, 2.0F, 3.0F, 4.0F, 5.0F, 6.0F, 7.0F, 8.0F, 9.0F }; // Note that here is a `const` in type declaration

    af::array A(3, 3, x);

    af::print("abc", A);

    return 0;
}
```

**Working test case:**
```
#include <arrayfire.h>

int main(int argc, char ** argv)
{
    float x[] = { 1.0F, 2.0F, 3.0F, 4.0F, 5.0F, 6.0F, 7.0F, 8.0F, 9.0F }; // Note that here is no `const` in type declaration

    af::array A(3, 3, x);

    af::print("abc", A);

    return 0;
}
```

This issue also affects all existing ArrayFire examples on my machine...

**Comment by pavanky** [comment]
OpenCL + OSX may not be worth supporting anymore:
https://developer.apple.com/macos/whats-new/

OpenCL on OSX has always been buggy,

**Comment by 9prady9** [comment]
We have seen similar issues on OSX, I don't think this needs a fix inside arrayfire code. I believe one of our developers used `std::vector` instead of  `float []` and the issue was resolved. @umar456 Can you please explain what you did ?

**Comment by lu4** [comment]
Ok, no problem with me, just reporting mine findings...

**Comment by 9prady9** [comment]
Can you try `std::vector` and see what happens ? Worth a try I think.

**Comment by lu4** [comment]
Well, something like this:
```
#include <arrayfire.h>
#include <vector>

int main(int argc, char ** argv)
{
    std::vector<float> x;

    for (auto i = 0.0F; i < 9.0F; i += 1.0F) {
        x.push_back(i);
    }

    af::array A(3, 3, &x[0]);

    af::print("abc", A);

    return 0;
}
```

worked fine:

2018-07-06 19:42:58.902369+0300 blas_opencl[58792:2051318] MessageTracer: Falling back to default whitelist
abc
[3 3 1 1]
    0.0000     3.0000     6.0000 
    1.0000     4.0000     7.0000 
    2.0000     5.0000     8.0000 


Process finished with exit code 0

**Comment by lu4** [comment]
But I see no reason to stick to vector if just removing `const` is enough...

**Comment by 9prady9** [comment]
Whichever works, I think it better to stay away from `const float x[]` while feeding the `af::array`. This is only an issue on OSX's OpenCL implementation. 

Perhaps we could add it somewhere in the documentation. But I think this issue would suffice as reference for future OSX users.
