### ISSUE TITLE
Build instructions for Linux metion to use gcc<6.1 together with CUDA

### ISSUE THREAD

**Issue by marbre** [arrayfire/arrayfire#2247]
The [build instructions for Linux](https://github.com/arrayfire/arrayfire/wiki/Build-Instructions-for-Linux#installing-arrayfire) metion that a gcc <6.1 hat to be used together with CUDA:
> NOTE: If the default gcc on your machine is gcc >= 6.1 and you want to use CUDA, you will have to run cmake by using an older gcc.

I assume this information is outdated since CUDA supports newer gcc versions?

**Comment by 9prady9** [comment]
No, this is still valid. Even CUDA 9.2 doesn't support the latest gcc versions. The latest it is known to work with is 6.1. 

https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#system-requirements

**Comment by marbre** [comment]
This is simply wrong. Please see the system requirements yourself, it mentions Ubuntu 17.10 with gcc 7.2.0 as well as Fedora 27 with gcc 7.3.1.

**Comment by 9prady9** [comment]
My bad, I missed the entry for Ubuntu 17.10. I use Arch and Ubuntu 16.04
for development. The former has gcc 8.* and the later has gcc 5.* . I use
gcc 6 on my arch for CUDA backend. Hence, never really tried version 7 so
far. Have you tried using gcc 7 ? If you dint have access to it, I can try
it out later and update the wiki accordingly. Thanks for reporting it.

**Comment by 9prady9** [comment]
I have updated the build instructions to latest gcc that works with CUDA backend as 7.3.1

**Comment by marbre** [comment]
I normally use a gcc 6.4.0, but just tested with a 7.3.0 and at least ArrayFire compiles (no further testing). Thanks for clarification :)

**Comment by 9prady9** [comment]
Yes, I have updated instructions after building ArrayFire with 7.3.1. Thanks for the update!
