### ISSUE TITLE
ACML 6.1 support

### ISSUE THREAD

**Issue by Kerkil** [arrayfire/arrayfire#225]
AMD recently released ACML 6.1 and noted that their power of 2 1D clFFTs, 2D FFTs, and clBLAS sgemm with a few other improvements have been significantly improved. Do you have a plan to integrate this library into the supported platform?

ACML 6.1 release note: http://developer.amd.com/tools-and-sdks/cpu-development/amd-core-math-library-acml/
 
Blog post: http://developer.amd.com/community/blog/2014/11/17/acml-6-1-accelerates-code/

**Comment by shehzan10** [comment]
We have tested this out. The findings are below:
* The BLAS API in ACML is different from CBLAS API that we use. It is possible to create wrappers for it.
* The ACML FFTW is viable replacement for FFTW. We tested this on Windows using the iFortran build. Simply replace the fftw paths with ACML FFTW paths and voila, it works like a charm.
* Its not as straight forwards on Linux. We tried doing the same thing as on windows, but for some reason it tries to load the acml_bridge lib. We are investigating this issue further.

**Comment by Kerkil** [comment]
Thanks for the update. I guess that an issue similar to the Linux one would exist with Mac?

**Comment by shehzan10** [comment]
I don't believe there are binaries available for Mac on the downloads page.

**Comment by Kerkil** [comment]
OK Thanks. 
@shehzan10  Have you observed any performance difference by the replacement?

**Comment by pavanky** [comment]
@Kerkil We have not benchmarked it yet. The BLAS and FFT libraries have support to offload work to the GPU based on some configuration parameters. This would make the routines to perform better for many of the larger cases.

**Comment by Kerkil** [comment]
@pavanky Thanks for the info.
