### ISSUE TITLE
mem leak in af::deviceInfo

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#2266]
Valgring still reports leaks with the latest 3.6.1.1 at least on CentOS 6 :  

==14586== 
==14586== HEAP SUMMARY:
==14586==     in use at exit: 530,274 bytes in 2,538 blocks
==14586==   total heap usage: 391,549 allocs, 389,011 frees, 54,375,774 bytes allocated
==14586== 
==14586== 8 bytes in 1 blocks are indirectly lost in loss record 39 of 2,248
==14586==    at 0x4C29E85: operator new(unsigned long) (vg_replace_malloc.c:333)
==14586==    by 0x2AEB6089: ???
==14586==    by 0x2AEB7808: ???
==14586==    by 0x2B96BEBD: ???
==14586==    by 0x2AEB6994: ???
==14586==    by 0x2AEB001E: ???
==14586==    by 0x2AF4BD55: ???
==14586==    by 0x2AF4C288: ???
==14586==    by 0x2B613DE9: ???
==14586==    by 0x1F0EA6B4: af_err unified::AFSymbolManager::call<char*, char*, char*, char*>(char const*, char*, char*, char*, char*) (in lib/libaf.so.3.6.1)
==14586==    by 0x1F2212A1: af::deviceInfo(char*, char*, char*, char*) (in /lib/libaf.so.3.6.1)

**Comment by umar456** [comment]
I am looking into this. There are some allocations we are not releasing at the end of the application but they shouldn't grow. I have been compiling a set of these in a local suppression file for ASAN but not Valgrind. I don't want to maintain two sets of suppression files.
