### ISSUE TITLE
Current release fails to find async_queue.hpp

### ISSUE THREAD

**Issue by mboisson** [arrayfire/arrayfire#2267]
Hi,
I downloaded the latest release (3.6.1) and the cmake step fails with : 
```
CMake Error at src/backend/cpu/CMakeLists.txt:10 (add_library):
  Cannot find source file:

    /dev/shm/mboisson/avx2/ArrayFire/3.6.1/iimklc-2016.4.90/arrayfire-3.6.1/src/backend/cpu/threads/async_queue.hpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


``` 

Any idea ?

**Comment by umar456** [comment]
I think you didn't bring in the submodules. Run:

    git submodule init
    git submodule update

**Comment by mboisson** [comment]
Mmm, so the releases are not self-contained ?

**Comment by mboisson** [comment]
Also, a release, by definition, is *not* a git repository. 
```[mboisson@build-node arrayfire-3.6.1]$ git submodule init
fatal: Not a git repository (or any parent up to mount point /dev/shm)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[mboisson@build-node arrayfire-3.6.1]$ git submodule update
fatal: Not a git repository (or any parent up to mount point /dev/shm)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set)
```

**Comment by umar456** [comment]
sorry. I thought you did a git clone. Let me check

**Comment by umar456** [comment]
The asset files are created by GitHub. They do not contain the submodules unfortunately. You can download the source for the latest release here:

http://arrayfire.com/arrayfire_source/arrayfire-full-3.6.1.tar.bz2

**Comment by mboisson** [comment]
Thanks, it seems to work with the arrayfire-full-3.6.1.tar.bz2

**Comment by mboisson** [comment]
So, the github releases are basically broken because of the use of submodules. Might want to not publish them (or somehow fix them)

**Comment by umar456** [comment]
There is no way for us to control what they automatically include in the release pages. It might be something to bring up with GitHub.
