### ISSUE TITLE
svdInPlace() does not accept arrays with dim0 > dim1

### ISSUE THREAD

**Issue by mark-poscablo** [arrayfire/arrayfire#2282]
I was playing with svd while testing and benchmarking #2279, and tried out `af::svdInPlace()`. However, I was baffled to get this exception when my array's dim0 is 3000 and dim1 is 2000:

```
ArrayFire v3.7.0 (CPU, 64-bit Linux, build 002e413e)
[0] Intel: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz, 7936 MB, Max threads(8) GNU Compiler Collection(GCC/G++) 5.5.0
ArrayFire Exception (Invalid input size:203):
In function af_err af_svd_inplace(void**, void**, void**, af_array)
In file src/api/c/svd.cpp:110
Invalid dimension for argument 3
Expected: dims[0] <= dims[1]

In function void af::svdInPlace(af::array&, af::array&, af::array&, af::array&)
In file src/api/cpp/lapack.cpp:28
``` 

I looked around svd's code and found this [dim assert that dim0 must <= dim1](https://github.com/arrayfire/arrayfire/blob/b562e974264f5338a14db37a5800e96580205586/src/api/c/svd.cpp#L110). Is there any special reason for this?

**Comment by mark-poscablo** [comment]
While @umar456 and I were working on #2279, we found that the internal `svd` functions on the CUDA and OpenCL backends call the internal `svdInPlace`function underneath, but before doing so, they make a transposed copy of the input array first in case dim0 < dim1 (otherwise it just makes a regular copy and proceeds with `svdInPlace`). This means that the internal `svdInPlace` requires that dim0 >= dim1 (see this mechanism on the [CUDA backend](https://github.com/arrayfire/arrayfire/blob/master/src/backend/cuda/svd.cu#L109) and on the [OpenCL backend](https://github.com/arrayfire/arrayfire/blob/master/src/backend/opencl/svd.cpp#L236)), and for some reason, the `svdInPlace` API puts the direction of the inequality the other way (dim0 <= dim1).

I'll revisit this soon, especially considering that currently, the `svdInPlace` API does not have tests (other than [being called shortly on tests/empty.cpp](https://github.com/arrayfire/arrayfire/blob/master/test/empty.cpp#L167)).

**Comment by christophe-murphy** [comment]
The issue where svdInPlace does not accept arrays with dim0 > dim1 has been fixed now so I will close this. I have created a new feature request issue for support for svdInPlace for dim0 < dim1 #3603
