### ISSUE TITLE
Fontconfig Error on Mac OS 10.13.6

### ISSUE THREAD

**Issue by BookmanHan** [arrayfire/arrayfire#2285]
Dear Sir,
I am installing AF on Mac OS.
There comes out a runtime issue as below:

dyld: Library not loaded: /usr/local/opt/fontconfig/lib/libfontconfig.1.dylib
  Referenced from: /opt/arrayfire/lib/libforge.1.dylib
  Reason: no suitable image found.  Did find:
	/usr/local/opt/fontconfig/lib/libfontconfig.1.dylib: stat() failed with errno=62
Program ended with exit code: 9

How can I fix it?

Thanks, a lot.

**Comment by umar456** [comment]
can you install [brew](https://brew.sh/) and then install fontconfig on your system. I thought we had included this with our installer. Thanks for reporting this.

**Comment by BookmanHan** [comment]
@umar456 I have installed brew and fontconfig. There seems a version mismatch?
Because the program finds the library but just triggers an error.

Thanks, a lot.

**Comment by BookmanHan** [comment]
I have figured it out.
Actually, brew installs the library on Cellar, rather than /usr/local/opt, which makes this issue.

The solution is very easy.
1. Make a dir on /usr/local/opt/fontconfig/lib.
2. link (copy) **all the files** in Cellar/fontconfig/lib into the created dir.

That works.

**Comment by mark-poscablo** [comment]
Thanks @BookmanHan. I encountered this issue also just now but I just had to `brew upgrade fontconfig`. I'll close this now.
