### ISSUE TITLE
Error in pow() with integer type

### ISSUE THREAD

**Issue by FilipeMaia** [arrayfire/arrayfire#2304]
Using arrayfire 3.6.0 with the CUDA backend with the following code:

```c++
#include <arrayfire.h>

int main(){
  af::array A = af::constant(-5,1, s32);
  af_print(A);
  af::array B = af::pow(A,2);
  af_print(B);
  return 0;
}
```

I get:
```shell
$ ./pow
A
[1 1 1 1]
   Offset: 0
   Strides: [1 1 1 1]
        -5
B
[1 1 1 1]
   Offset: 0
   Strides: [1 1 1 1]
        24
``` 

Instead of 25.

This problem was originally reported in https://github.com/arrayfire/arrayfire-python/issues/192

**Comment by FilipeMaia** [comment]
Almost certainly the error is caused by the calculation being done in floating point and then casted to int causing a truncation error. Here's some quick diagnostics using the python interface:

```python
b = af.constant(-7,1,dtype=af.Dtype.f32)
af.display(b**2,precision=13)
b**2,precision=13
[1 1 1 1]
   Offset: 0
   Strides: [1 1 1 1]
   48.9999961853027
```

```python
a = af.constant(-7,1,dtype=af.Dtype.s32)
af.display(a**2,precision=12)
a**2,precision=12
[1 1 1 1]
   Offset: 0
   Strides: [1 1 1 1]
                48
```

**Comment by 9prady9** [comment]
@FilipeMaia I was able to reproduce this on CUDA and OpenCL backends too. CPU backend is giving correct result. Will update here once I have something.

**Comment by 9prady9** [comment]
The problem is as you suggested @FilipeMaia , but I need to fix it properly so that I dont decrease the performance where ever high precision is not needed. Will send in a fix soon.
