### ISSUE TITLE
Add new functions to stream / read / write af::array

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#231]
Function ideas

- For C API
```
af_readarray(af_array *arr, const char *file_name);
af_savearray(const char *file_name, const af_array arr);
``` 

- For C++ API
```
array readArray(std::string file_name);
void saveArray(std::string file_name, const array in);
ostream array::operator<<() 
```

**Comment by shehzan10** [comment]
How about the following:
```
std::vector<array> readArray(const char* filename);
void saveArray(const std::vector<array> arr, const char* filename);
af_err af_readarray(af_array **arr, const unsigned n_arrays, const char * filename);
af_err af_savearray(const char *filename, const af_array *arr, const unsigned n_arrays, const bool append);
```
We will also overload the << and >> operators on the array class.

I think this should allow reading/writing multiple arrays.

Once we settle on an API, then we can discuss the layout of the file.

**Comment by pavanky** [comment]
@shehzan10 no STL in our C++ interface unless the function is self contained in the header.

Can you also add another C function like this:

```
af_err af_stringize(char **output, const array in, int precision); 
```

This is like `af_print` but it stores to char buffer instead of console.
