### ISSUE TITLE
Add runtime backend selection

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#232]
Suggested order of preference for default backend:

- CUDA backend
- OpenCL backend
- CPU backend

If CUDA driver / runtime is not available, the code should fall back to OpenCL.
If OpenCL drivers / runtimes are not present it should fall back to CPU.

It should also be possible to use multiple backends simultaneously similar to what is happening with multiple devices.

**Comment by Kerkil** [comment]
@naspert +1 for allowing users to specify the order of the backends.

**Comment by Kerkil** [comment]
@pavanky Is there a way to change backend at run time now? I'd like to use ArrayFire cpu backend codes for some part and OpenCL/CUDA backend for the other part. If this feature is added, would it be possible to switch back and forth between different backends at runtime?

**Comment by pavanky** [comment]
@Kerkil While this feature is useful, it is neither straightforward nor easy to implement. It could potentially have a significant affect on the C API. We are considering different options at this moment and will present the options publicly once we have all the details.

**Comment by Kerkil** [comment]
@pavanky Thanks. Sounds good. Looking forward to hearing the options.

**Comment by pavanky** [comment]
@munnybearz @Kerkil @naspert Check out #977

**Comment by pavanky** [comment]
This is now present in devel branch as a new backend library.
