### ISSUE TITLE
Sync Problem

### ISSUE THREAD

**Issue by csverma610** [arrayfire/arrayfire#2336]
Hello,

I have some sync problem with Arrayfire.  There are differences in the results
if I comment out the SaveArray. What could be the problem?

af::array accessibleDislocations = projSpace * dislocations;

    cout << " NEW CODE " << endl;

    /*
    char key ;
    af::saveArray(&key, projSpace, "1.png");
    af::saveArray(&key, dislocations,    "2.png");
    af::saveArray(&key, accessibleDislocations,    "3.png");
    */

    cout << "Dislocation " << nonzero( dislocations ) << endl;
    cout << "ProjSpace   " << nonzero( projSpace  ) << endl;
    cout << "Accessible  " << nonzero( accessibleDislocations ) << endl;

**Comment by 9prady9** [comment]
@csverma610 Can you please post a complete snippet to reproduce the issue on our end.

Also, on which backend is this happening on ? Are you seeing same behavior across all backends ?

**Comment by csverma610** [comment]
hello,

i am trying to calculate a large number of ffts. Do i need to call garbage
collection? may be the corruption is caused by this issue.

csv

**Comment by 9prady9** [comment]
`af::deviceGC()` call removes all unused buffers that are managed by ArrayFire, please note that this doesn't include any additional memory allocated/managed by upstream fft libraries: fftw/mkl - CPU backend; cuFFT - CUDA backed; clFFT - OpenCL backend.

I think the problem could be something else as garbage collection is called automatically invoked on a set criteria, such as total memory allocated is greater than a threshold etc. Hence, I am not sure that it could be the issue.

Even if it is bug inside ArrayFire, without looking at the code that can reproduce this issue it is hard to guess what the problem could be.

**Comment by csverma610** [comment]
I will send you the code tomorrow from my office.

Thank you very much for your help.

csv

**Comment by 9prady9** [comment]
Closing the issue due to inactivity. @csverma610  Please feel free to reopen if you are still having the problem.
