### ISSUE TITLE
Official ArrayFire binaries for CUDA 10

### ISSUE THREAD

**Issue by oschulz** [arrayfire/arrayfire#2337]
Are there any short-term plans for official ArrayFire binaries built for CUDA 10?

**Comment by 9prady9** [comment]
We will probably do that with next fix release, 3.6.2. Will keep you posted here.

**Comment by oschulz** [comment]
Thanks!

**Comment by mlloreda** [comment]
@oschulz closing issue now that we've added support for CUDA 10 with latest (v3.6.2) installers.

**Comment by oschulz** [comment]
Thanks for the new release, @mlloreda!
