### ISSUE TITLE
Building inside docker

### ISSUE THREAD

**Issue by tlikhomanenko** [arrayfire/arrayfire#2373]
Hey!

I am trying to build arrayfire in Dockerfile while I am using the image ```nvidia/cuda:9.2-cudnn7-devel-ubuntu16.04```. I am building with configuration (using the current master)
```
cmake .. -DCMAKE_BUILD_TYPE=Release -DAF_BUILD_CPU=OFF -DAF_BUILD_OPENCL=OFF -DAF_BUILD_EXAMPLES=OFF
```
and get the following error:
```
[ 48%] Building NVCC (Device) object src/backend/cuda/CMakeFiles/afcuda.dir/afcuda_generated_wrap.cu.o
In file included from /root/arrayfire/src/backend/common/ArrayInfo.hpp:11:0,
                 from /root/arrayfire/src/backend/cuda/Array.hpp:12,
                 from /root/arrayfire/src/backend/cuda/wrap.cu:10:
/root/arrayfire/src/backend/common/defines.hpp:63:2: error: #error "Unsupported platform"
 #error "Unsupported platform"
  ^
CMake Error at afcuda_generated_wrap.cu.o.cmake:207 (message):
  Error generating
  /root/arrayfire/build/src/backend/cuda/CMakeFiles/afcuda.dir//./afcuda_generated_wrap.cu.o


src/backend/cuda/CMakeFiles/afcuda.dir/build.make:602: recipe for target 'src/backend/cuda/CMakeFiles/afcuda.dir/afcuda_generated_wrap.cu.o' failed
```

You can see that some strange paths are generated
```
/root/arrayfire/build/src/backend/cuda/CMakeFiles/afcuda.dir//./afcuda_generated_wrap.cu.o
```

Do you know what can be a problem?

Thanks for help!

**Comment by 9prady9** [comment]
We heard about a similar issue on our Google forums, but we weren't able to understand what was the reason behind it. The `OS_LNX` was defined appropriately but it wasn't being passed to the compile command of all translation units for some weird reason. Is your problem similar to this ?

Can you please share the dockerfile you are using so that we can try  to reproduce it on our end. Thank you.

**Comment by tlikhomanenko** [comment]
Hey!

- Building with the following dockerfile (`arrayfire v3.6.1` works fine):

```bash
# ==================================================================
# module list
# ------------------------------------------------------------------
# Ubuntu         16.04
# CUDA           9.2
# CuDNN          7-dev
# boost          latest   (apt)
# arrayfire      3.6.1    (git, CUDA backend)
# ==================================================================

FROM nvidia/cuda:9.2-cudnn7-devel-ubuntu16.04

RUN APT_INSTALL="apt-get install -y --no-install-recommends" && \
    rm -rf /var/lib/apt/lists/* \
           /etc/apt/sources.list.d/cuda.list \
           /etc/apt/sources.list.d/nvidia-ml.list && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive $APT_INSTALL \
        build-essential \
        ca-certificates \
        cmake \
        wget \
        git \
        vim \
        emacs \
        nano \
        htop \
        g++ \
        libboost-all-dev && \
# ==================================================================
# arrayfire https://github.com/arrayfire/arrayfire/wiki/
# ------------------------------------------------------------------
    cd /tmp && git clone --recursive https://github.com/arrayfire/arrayfire.git && \
    cd arrayfire && git checkout b443e14 && \
    mkdir build && cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release -DAF_BUILD_CPU=OFF -DAF_BUILD_OPENCL=OFF -DAF_BUILD_EXAMPLES=OFF && \
    make -j8 && \
    make install && \
# ========================================================= =========
# config & cleanup
# ------------------------------------------------------------------
    ldconfig && \
    apt-get clean && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/* /tmp/* ~/*
```

- Building from the current master doesn't work, there is a problem with `glm` (could not find it). Why do I need to install it if I am not going to build openCL (even if I add apt install `libglfw3-dev libfontconfig1-dev libglm-dev` the same problem with `glm` remains)?

- Building with commit d0da171ce8e297cc93d21bc47715d1cc0b61f1bf got the error I posted above. After changing the code at [this location](https://github.com/arrayfire/arrayfire/blob/master/CMakeModules/InternalUtils.cmake#L21-L29) to 

```cmake
function(arrayfire_get_platform_definitions variable)
if(WIN32)
  message("Windows Operating System")
  set(${variable} -DOS_WIN -DWIN32_LEAN_AND_MEAN -DNOMINMAX PARENT_SCOPE)
elseif(APPLE)
  message("Apple Operating System")
  set(${variable} -DOS_MAC PARENT_SCOPE)
elseif(UNIX)
  message("Linux/Unix flavor Operating System")
  set(${variable} -DOS_LNX PARENT_SCOPE)
else()
  message(FATAL_ERROR "Unknown Operating System")
endif()
endfunction()
```
I got the following during cmake:
```make
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - found
-- Could NOT find OpenCL (missing:  OpenCL_LIBRARY) (found version "1.2")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA: /usr/local/cuda (found suitable version "9.2", minimum required is "7.0")
-- Could NOT find OpenCL (missing:  OpenCL_LIBRARY) (found suitable version "1.2", minimum required is "1.2")
-- Could NOT find OpenGL (missing:  OPENGL_gl_LIBRARY OPENGL_INCLUDE_DIR)
-- Found OpenMP_C: -fopenmp (found version "4.0")
-- Found OpenMP_CXX: -fopenmp (found version "4.0")
-- Could NOT find FreeImage (missing:  FreeImage_INCLUDE_DIR FreeImage_LINK_LIBRARY)
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE)
-- Could NOT find FFTW (missing:  FFTW_INCLUDE_DIR FFTW_LIBRARY FFTWF_LIBRARY)
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE)
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Checking for [Accelerate]
-- Checking for [vecLib]
-- Checking for [cblas - atlas]
-- Checking for [openblas]
-- Checking for [cblas]
-- Checking for [blas]
-- CBLAS library not found.
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE)
-- Could NOT find LAPACK (missing:  LAPACK_INCLUDE_DIR LAPACK_LIBRARIES)
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
-- Check size of int
-- Check size of int - done
-- Could NOT find MKL (missing:  MKL_INCLUDE_DIR MKL_Core_LINK_LIBRARY)
-- Boost version: 1.58.0
-- BOOST_COMPUTE: /tmp/arrayfire/build/boost_compute-prefix/src/boost_compute
-- Automatic GPU detection failed. Building for common architectures.
-- CUDA_architecture_build_targets: 3.0;3.5;5.0;5.2;6.0;6.1;7.0;7.0+PTX
Linux/Unix flavor Operating System
Linux/Unix flavor Operating System
Linux/Unix flavor Operating System
-- Performing Test has_ignored_attributes_flag
-- Performing Test has_ignored_attributes_flag - Success
-- CUDA driver library missing. Looking for libcuda stub.
-- CUDA driver stub FOUND: /usr/local/cuda/lib64/stubs/libcuda.so
Linux/Unix flavor Operating System
-- [download 100% complete]
Downloaded Trec4 file from sparse.tamu.edu
Extracted mtx files to test data directory
-- [download 100% complete]
Downloaded bcsstm02 file from sparse.tamu.edu
Extracted mtx files to test data directory
-- [download 0% complete]
-- [download 64% complete]
-- [download 100% complete]
Downloaded young4c file from sparse.tamu.edu
Extracted mtx files to test data directory
-- [download 0% complete]
-- [download 84% complete]
-- [download 100% complete]
Downloaded lpi_vol1 file from sparse.tamu.edu
Extracted mtx files to test data directory
-- [download 0% complete]
-- [download 84% complete]
-- [download 100% complete]
Downloaded lpi_qual file from sparse.tamu.edu
Extracted mtx files to test data directory
-- [download 0% complete]
-- [download 55% complete]
-- [download 100% complete]
Downloaded oscil_dcop_12 file from sparse.tamu.edu
Extracted mtx files to test data directory
-- [download 0% complete]
-- [download 56% complete]
-- [download 100% complete]
Downloaded oscil_dcop_42 file from sparse.tamu.edu
Extracted mtx files to test data directory
Downloaded conf6_0-4x4-20 file from sparse.tamu.edu
Extracted mtx files to test data directory
....
```
and during make:
```make
[ 43%] Building NVCC (Device) object src/backend/cuda/CMakeFiles/afcuda.dir/afcuda_generated_wrap.cu.o
In file included from /tmp/arrayfire/src/backend/common/ArrayInfo.hpp:11:0,
                 from /tmp/arrayfire/src/backend/cuda/Array.hpp:12,
                 from /tmp/arrayfire/src/backend/cuda/wrap.cu:10:
/tmp/arrayfire/src/backend/common/defines.hpp:63:2: error: #error "Unsupported platform"
 #error "Unsupported platform"
  ^
CMake Error at afcuda_generated_wrap.cu.o.cmake:207 (message):
  Error generating
  /tmp/arrayfire/build/src/backend/cuda/CMakeFiles/afcuda.dir//./afcuda_generated_wrap.cu.o


src/backend/cuda/CMakeFiles/afcuda.dir/build.make:602: recipe for target 'src/backend/cuda/CMakeFiles/afcuda.dir/afcuda_generated_wrap.cu.o' failed
make[2]: *** [src/backend/cuda/CMakeFiles/afcuda.dir/afcuda_generated_wrap.cu.o] Error 1
CMakeFiles/Makefile2:1282: recipe for target 'src/backend/cuda/CMakeFiles/afcuda.dir/all' failed
make[1]: *** [src/backend/cuda/CMakeFiles/afcuda.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by 9prady9** [comment]
Thanks for the dockerfile, I will look into it and get back to you once I have something to share.

**Comment by 9prady9** [comment]
https://github.com/arrayfire/arrayfire/issues/2388#issuecomment-450622748

**Comment by 9prady9** [comment]
I have fixed the cmake related configuration of Forge(ArrayFire graphics upstream) for glm and Freetype. This cmake issue seems to happen on Ubuntu 16.04 only - I think it has to do with the older cmake version(3.5) which has few bugs that were fixed in it's later releases.

@tlikhomanenko Once, cmake generation step is finished. You most likely will face an issue about `glad\glad.h` not found while building CUDA backend. I think this is an issue from cmake 3.5 that was fixed in later versions of cmake. The issue is related to `$<JOIN:>` generator expression not working properly.

Although it might be a bit extra work, I think the better work around would be to install latest cmake. Building and installing cmake is pretty easy, I have done it quite a few times without any issues in the past on old linux distros. Feel free to ask us on that on our slack channel.

**Comment by tlikhomanenko** [comment]
I am trying with this config with the latest master of arrayfire

``` bash
# ==================================================================
# module list
# ------------------------------------------------------------------
# Ubuntu         16.04
# CUDA           9.2
# CuDNN          7-dev
# boost          latest   (apt)
# arrayfire      3.6.1    (git, CUDA backend)
# ==================================================================

FROM nvidia/cuda:9.2-cudnn7-devel-ubuntu16.04

RUN APT_INSTALL="apt-get install -y --no-install-recommends" && \
    rm -rf /var/lib/apt/lists/* \
           /etc/apt/sources.list.d/cuda.list \
           /etc/apt/sources.list.d/nvidia-ml.list && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive $APT_INSTALL \
        build-essential \
        ca-certificates \
        cmake \
        wget \
        git \
        vim \
        emacs \
        nano \
        htop \
        g++ \
        libboost-all-dev && \
    apt-get purge -y cmake && \
    version=3.10 && \
    build=3 && \
    mkdir ~/temp && \
    cd ~/temp && \
    wget https://cmake.org/files/v$version/cmake-$version.$build.tar.gz  && \
    tar -xzvf cmake-$version.$build.tar.gz  && \
    cd cmake-$version.$build/  && \
    ./bootstrap   && \
    make -j4 && \
    make install && cmake --version && \
# ==================================================================
# arrayfire https://github.com/arrayfire/arrayfire/wiki/
# ------------------------------------------------------------------
    cd /tmp && git clone --recursive https://github.com/arrayfire/arrayfire.git && \
    cd arrayfire && \
    mkdir build && cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release -DAF_BUILD_CPU=OFF -DAF_BUILD_OPENCL=OFF -DAF_BUILD_EXAMPLES=OFF && \
    make -j8 && \
    make install && \
# ========================================================= =========
# config & cleanup
# ------------------------------------------------------------------
    ldconfig && \
    apt-get clean && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/* /tmp/* ~/*
```

and get the error during cmake

```bash
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - not found
-- Looking for CL_VERSION_1_1
-- Looking for CL_VERSION_1_1 - not found
-- Looking for CL_VERSION_1_0
-- Looking for CL_VERSION_1_0 - not found
-- Could NOT find OpenCL (missing: OpenCL_LIBRARY OpenCL_INCLUDE_DIR)
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA: /usr/local/cuda (found suitable version "9.2", minimum required is "7.0")
-- Could NOT find OpenCL (missing: OpenCL_LIBRARY OpenCL_INCLUDE_DIR) (Required is at least version "1.2")
-- Could NOT find OpenGL (missing: OPENGL_gl_LIBRARY OPENGL_INCLUDE_DIR)
-- Found OpenMP_C: -fopenmp (found version "4.0")
-- Found OpenMP_CXX: -fopenmp (found version "4.0")
-- Could NOT find FreeImage (missing: FreeImage_INCLUDE_DIR FreeImage_LINK_LIBRARY)
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Could NOT find FFTW (missing: FFTW_INCLUDE_DIR FFTW_LIBRARY FFTWF_LIBRARY)
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Checking for [Accelerate]
-- Checking for [vecLib]
-- Checking for [cblas - atlas]
-- Checking for [openblas]
-- Checking for [cblas]
-- Checking for [blas]
-- CBLAS library not found.
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Could NOT find LAPACK (missing: LAPACK_INCLUDE_DIR LAPACK_LIBRARIES)
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Check size of int
-- Check size of int - done
-- Could NOT find MKL (missing: MKL_INCLUDE_DIR MKL_Core_LINK_LIBRARY)
-- Boost version: 1.58.0
-- BOOST_COMPUTE: /tmp/arrayfire/build/boost_compute-prefix/src/boost_compute
CMake Error at /usr/local/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Freetype (missing: FREETYPE_LIBRARY FREETYPE_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.10/Modules/FindFreetype.cmake:157 (find_package_handle_standard_args)
  extern/forge/CMakeLists.txt:48 (find_package)
```

**Comment by umar456** [comment]
Can you install libfreetype6-dev on your system?

**Comment by zhengqun** [comment]
![Uploading error.png…]()

**Comment by zhengqun** [comment]
![error](https://user-images.githubusercontent.com/34435100/50636758-4c39a980-0f92-11e9-89f1-3ef2b199b844.png)

**Comment by WilliamTambellini** [comment]
I got a similar issue on a regular default ubuntu 16 : 
$cmakebin ..
 -DAF_WITH_GRAPHICS=OFF
 -DAF_WITH_STATIC_FREEIMAGE=OFF 
 -DAF_WITH_IMAGEIO=OFF 
...
CMake Error at /home/wtambellini/repos/xmt-externals/FC12/tools/cmake/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Freetype (missing: FREETYPE_LIBRARY) (found version "2.6.1")
Call Stack (most recent call first):
  /home/wtambellini/repos/xmt-externals/FC12/tools/cmake/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  /home/wtambellini/repos/xmt-externals/FC12/tools/cmake/share/cmake-3.9/Modules/FindFreetype.cmake:140 (find_package_handle_standard_args)
  extern/forge/CMakeLists.txt:48 (find_package)

I guess that machine does nt have the freetype dev : 
$ locate libfreetype.
/usr/lib/i386-linux-gnu/libfreetype.so.6
/usr/lib/i386-linux-gnu/libfreetype.so.6.12.1
/usr/lib/x86_64-linux-gnu/libfreetype.a
/usr/lib/x86_64-linux-gnu/libfreetype.la
/usr/lib/x86_64-linux-gnu/libfreetype.so
/usr/lib/x86_64-linux-gnu/libfreetype.so.6
/usr/lib/x86_64-linux-gnu/libfreetype.so.6.12.1

Should nt we be able to build a non graphics AF without the need for freetype ?

**Comment by umar456** [comment]
I am taking a look into this now.

**Comment by tlikhomanenko** [comment]
after adding `apt-get install libfreetype6-dev` it is necessary to install also `pkg-config`, `libfontconfig1-dev`. But after that 
```bash
Could NOT find OpenGL (missing: OPENGL_gl_LIBRARY OPENGL_INCLUDE_DIR)
``` 
Could you fix this also (I am building only CUDA backend)?

**Comment by 9prady9** [comment]
@tlikhomanenko Just to add what I said earlier, `libfontconfig1-dev` is listed among the graphics dependencies in our build instructions. `libfreetype6-dev` is one of the dependencies of fontconfig, hence if fontconfig dev package is installed, freetype should have been installed automatically. So is `pkg-config` - another dependency of fontconfig dev package. `nvidia/cuda:9.2-cudnn7-devel-ubuntu16.04` docker image doesn't have these installed by default. 

Our build wiki assumes, OpenGL dev files are installed, we will update the wiki to reflect that as well. Please install `libglu1-mesa-dev` package for OpenGL headers and libs on your docker image.

@WilliamTambellini We removed the `AF_WITH_GRAPHICS` with the intention to build with graphics code paths enabled in all configurations and disable gfx at runtime if required shared libraries are not available. Are you also building arrayfire using a docker image ? If so, can you please let us know what is the base image.

**Comment by 9prady9** [comment]
@tlikhomanenko You can use https://github.com/arrayfire/arrayfire-docker/blob/master/Dockerfile as reference for coming up with a docker image that meets your requirements. However, you need to install all the necessary dependencies as mentioned in the dockerfile lines 5 to 21

**Comment by 9prady9** [comment]
@tlikhomanenko Here is the dockerfile that finished cmake generation successfully.

```Dockerfile
FROM nvidia/cuda:9.2-cudnn7-devel-ubuntu16.04

RUN APT_INSTALL="apt-get install -y --no-install-recommends" && \
    rm -rf /var/lib/apt/lists/* \
           /etc/apt/sources.list.d/cuda.list \
           /etc/apt/sources.list.d/nvidia-ml.list && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive $APT_INSTALL \
        build-essential \
        ca-certificates \
        cmake \
        wget \
        git \
        vim \
        emacs \
        nano \
        htop \
        g++ \
        libcurl4-openssl-dev \
        libfftw3-dev \
        libglfw3-dev \
        libfreeimage-dev \
        libfontconfig1-dev \
        libglu1-mesa-dev \
        libboost-all-dev && \
    apt-get purge -y cmake && \
    version=3.10 && \
    build=3 && \
    mkdir ~/temp && \
    cd ~/temp && \
    wget https://cmake.org/files/v$version/cmake-$version.$build.tar.gz  && \
    tar -xzvf cmake-$version.$build.tar.gz  && \
    cd cmake-$version.$build/  && \
    ./bootstrap --system-curl && \
    make -j4 && \
    make install && cmake --version && \
# ==================================================================
# arrayfire https://github.com/arrayfire/arrayfire/wiki/
# ------------------------------------------------------------------
    cd /tmp && git clone --recursive https://github.com/arrayfire/arrayfire.git && \
    cd arrayfire && \
    mkdir build && cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release -DAF_BUILD_CPU=OFF -DAF_BUILD_OPENCL=OFF -DAF_BUILD_EXAMPLES=OFF && \
    make && \
    make install && \
# ========================================================= =========
# config & cleanup
# ------------------------------------------------------------------
    ldconfig && \
    apt-get clean && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/* /tmp/* ~/*
```

**Comment by 9prady9** [comment]
Update: I just finished building CUDA backend successfully using the `Dockerfile` I pasted in my most recent comment.

**Comment by WilliamTambellini** [comment]
> @WilliamTambellini We removed the `AF_WITH_GRAPHICS` with the intention to build with graphics code paths enabled in all configurations and disable gfx at runtime if required shared libraries are not available. Are you also building arrayfire using a docker image ? If so, can you please let us know what is the base image.

No, bare metal Ubuntu.

**Comment by tlikhomanenko** [comment]
> @tlikhomanenko Here is the dockerfile that finished cmake generation successfully.
> 
> ```dockerfile
> FROM nvidia/cuda:9.2-cudnn7-devel-ubuntu16.04
> 
> RUN APT_INSTALL="apt-get install -y --no-install-recommends" && \
>     rm -rf /var/lib/apt/lists/* \
>            /etc/apt/sources.list.d/cuda.list \
>            /etc/apt/sources.list.d/nvidia-ml.list && \
>     apt-get update && \
>     DEBIAN_FRONTEND=noninteractive $APT_INSTALL \
>         build-essential \
>         ca-certificates \
>         cmake \
>         wget \
>         git \
>         vim \
>         emacs \
>         nano \
>         htop \
>         g++ \
>         libcurl4-openssl-dev \
>         libfftw3-dev \
>         libglfw3-dev \
>         libfreeimage-dev \
>         libfontconfig1-dev \
>         libglu1-mesa-dev \
>         libboost-all-dev && \
>     apt-get purge -y cmake && \
>     version=3.10 && \
>     build=3 && \
>     mkdir ~/temp && \
>     cd ~/temp && \
>     wget https://cmake.org/files/v$version/cmake-$version.$build.tar.gz  && \
>     tar -xzvf cmake-$version.$build.tar.gz  && \
>     cd cmake-$version.$build/  && \
>     ./bootstrap --system-curl && \
>     make -j4 && \
>     make install && cmake --version && \
> # ==================================================================
> # arrayfire https://github.com/arrayfire/arrayfire/wiki/
> # ------------------------------------------------------------------
>     cd /tmp && git clone --recursive https://github.com/arrayfire/arrayfire.git && \
>     cd arrayfire && \
>     mkdir build && cd build && \
>     cmake .. -DCMAKE_BUILD_TYPE=Release -DAF_BUILD_CPU=OFF -DAF_BUILD_OPENCL=OFF -DAF_BUILD_EXAMPLES=OFF && \
>     make && \
>     make install && \
> # ========================================================= =========
> # config & cleanup
> # ------------------------------------------------------------------
>     ldconfig && \
>     apt-get clean && \
>     apt-get autoremove && \
>     rm -rf /var/lib/apt/lists/* /tmp/* ~/*
> ```

Yep, I have successfully built current master. 
Thanks a lot for your help and fixes! 

I am closing the issue as soon as we have working version of Dockerfile now. If anyone needs, please, reopen the issue.

**Comment by zhengqun** [comment]
![image](https://user-images.githubusercontent.com/34435100/50814381-7f928480-1354-11e9-9745-32f57ea95405.png)

@tlikhomanenko @9prady9 @WilliamTambellini  how can i do ?

**Comment by 9prady9** [comment]
@zhengqun As far as I am aware of, pull access denial happens when the user running the docker commands is not added to the linux user group `docker`.

```bash
grep docker  /etc/group
```
that should show the users in `docker` group. If `arrayfire` isn't in it, please add arrayfire user and retry the commands.

If that also doesn't work, may be it is trying to find a valid docker registry account - which it should for only private images I would think.

**Comment by tlikhomanenko** [comment]
> ![image](https://user-images.githubusercontent.com/34435100/50814381-7f928480-1354-11e9-9745-32f57ea95405.png)
> 
> @tlikhomanenko @9prady9 @WilliamTambellini how can i do ?

Hey! It seems that your image building fails: "returned a non-zero code: 1". This happened because apt additionally ask "would you like to remove" and wait until you enter yes (that cannot be done during the build): "Do you want to continue? [Y/n] Abort" - this fail.

Could you send the full building log: I didn't get the actual command what fails?

**Comment by zhengqun** [comment]
there is my command：
FROM nvidia/cuda:9.2-cudnn7-devel-ubuntu16.04

RUN APT_INSTALL="apt-get install -y --no-install-recommends" && \
    rm -rf /var/lib/apt/lists/* \
           /etc/apt/sources.list.d/cuda.list \
           /etc/apt/sources.list.d/nvidia-ml.list && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive $APT_INSTALL \
        build-essential \
        ca-certificates \
        cmake \
        wget \
        git \
        vim \
        emacs \
        nano \
        htop \
        g++ \
        libcurl4-openssl-dev \
        libfftw3-dev \
        libglfw3-dev \
        libfreeimage-dev \
        libfontconfig1-dev \
        libglu1-mesa-dev \
        libboost-all-dev && \
    apt-get purge -y cmake && \
    version=3.10 && \
    build=3 && \
    mkdir ~/temp && \
    cd ~/temp && \
    wget https://cmake.org/files/v$version/cmake-$version.$build.tar.gz  && \
    tar -xzvf cmake-$version.$build.tar.gz  && \
    cd cmake-$version.$build/  && \
    ./bootstrap --system-curl && \
    make -j4 && \
    make install && cmake --version && \
# ==================================================================
# arrayfire https://github.com/arrayfire/arrayfire/wiki/
# ------------------------------------------------------------------
    cd /tmp && git clone --recursive https://github.com/arrayfire/arrayfire.git && \
    cd arrayfire && \
    mkdir build && cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release -DAF_BUILD_CPU=OFF -DAF_BUILD_OPENCL=OFF -DAF_BUILD_EXAMPLES=OFF && \
    make && \
    make install && \
# ========================================================= =========
# config & cleanup
# ------------------------------------------------------------------
    ldconfig && \
    apt-get clean && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/* /tmp/* ~/*

**Comment by tlikhomanenko** [comment]
Yep, you are using the same Dockerfile as was posted above. Could you send the full log after your docker build command?

**Comment by zhengqun** [comment]
could you please tell me  how can i  find this log ? i  can not find this log

**Comment by tlikhomanenko** [comment]
I meant to send all output which is printed on your screen after run command nvidia-docker build.

**Comment by tlikhomanenko** [comment]
One another solution for OS_LNX to be set is to put `CXXFLAGS=-DOS_LNX` before `cmake`:
```
CXXFLAGS=-DOS_LNX cmake .. 
```
This works fine to build arrayfire 3.6.2 in the docker image for CPU and CUDA backends.

**Comment by 9prady9** [comment]
I understand that change worked but that would be a hack in my opinion because one shouldn't be needed to do it in the first place. Having said that, I am not sure what is going on in your case

**Comment by ty1970s** [comment]
3.6.2 show this error, but 3.6.1 can pass.
