### ISSUE TITLE
Performance issues using eval on multiple arrays

### ISSUE THREAD

**Issue by awni** [arrayfire/arrayfire#2376]
There seems to be a performance bug with calling af::eval on multiple arrays.

For inputs:

```
  auto x = af::randn(10, 10);
  auto y = af::randn(10, 10);
```

Using eval on multiple inputs:

```
    for (int it = 0; it < 100; it++) {
        y = y * 2;
        x = x + y;
        af::eval(y, x);
    }
```

Using eval on single input at a time:
```
    for (int it = 0; it < 100; it++) {
        y = y * 2;
        x = x + y;
        af::eval(y);
        af::eval(x);
    }
```

Timing the former takes 6.94 ms vs the latter which is 2.30 ms for the single version (e.g. ~3x speedup). In some cases we have observed much worse performance hits from using the multi eval.

Is this expected behavior?

System details:
ArrayFire v3.6.1 (CUDA, 64-bit Linux, build default)
Platform: CUDA Toolkit 9.2, Driver: 396.26
[0] Tesla M40, 11449 MB, CUDA Compute 5.2

**Comment by umar456** [comment]
I was able to reproduce this on master. I will investigate further later in the week.

**Comment by umar456** [comment]
Thanks for reporting this. I was able to figure it out the issue and it will be fixed in the next patch release. The issue was only on the CUDA backend. Here are the results for the updated code:
```
  auto x = af::randn(10, 10);
  auto y = af::randn(10, 10);
  af::sync();

  auto start = std::chrono::steady_clock::now();
  for (int it = 0; it < 100; it++) {
      y = y * 2;
      x = x + y;
      af::eval(y);
      af::eval(x);
  }
  af::sync();
  auto duration = std::chrono::duration_cast<std::chrono::microseconds>(std::chrono::steady_clock::now() - start);
  printf("multi eval  %llu us\n", duration.count());

    start = std::chrono::steady_clock::now();
    for (int it = 0; it < 100; it++) {
        y = y * 2;
        x = x + y;
        af::eval(y, x);
    }
    af::sync();
    duration = std::chrono::duration_cast<std::chrono::microseconds>(std::chrono::steady_clock::now() - start);
    printf("single eval %llu us\n", duration.count());
```
```
multi eval  316508 us
single eval 155794 us
```

This is a debug build so your times may be different.

**Comment by awni** [comment]
Thanks for the fix!
