### ISSUE TITLE
Multi-stream support for cuda backend

### ISSUE THREAD

**Issue by vineelpratap** [arrayfire/arrayfire#2378]
Hi, 
  Thanks for proving such a great tensor library. I would like to know if there a plan to support mutiple streams for cuda backend. 

Context: 
    I'm working on machine learning pipeline where data featurization is done in parallel with network forward and backward. Currently, I have implemented all of them using arrayfire operations.  It would be really helpful to have support for multiple stream so that data prefetching can be done in a separate thread on a different stream.

**Comment by 9prady9** [comment]
We don't have anyone actively working on that feature right now. However, we would probably provide multiple stream support at some point in future. We don't have an absolute ETA at the moment.

Having said that, with some extra raw CUDA code, you should be able to load data in different thread using your stream and then pass on that data to ArrayFire for computations. This is not an ideal solution, just putting it out there as a work around for the lack of native support at the moment.
The API you need for this work around is documented here http://arrayfire.org/docs/interop_cuda.htm

You can even interleave some custom CUDA kernels execution using interop API. Note that this interop header is not included by default by `arrayfire.h` and you need explicitly include `af/cuda.h` header after you include `arrayfire.h` to use the interop API.

**Comment by vineelpratap** [comment]
Thanks @9prady9 . Looking forward to multi-stream support in AF.
