### ISSUE TITLE
build ArrayFire error on Ubuntu 16.04

### ISSUE THREAD

**Issue by auvilink** [arrayfire/arrayfire#2388]
Hi, there,

I followed the install instructions and met following errors when do " make -j 8"

/usr/bin/ld: /usr/local/lib/libfftw3.a(apiplan.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libfftw3.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src/backend/cpu/CMakeFiles/afcpu.dir/build.make:7245: recipe for target 'src/backend/cpu/libafcpu.so.3.7.0' failed
make[2]: *** [src/backend/cpu/libafcpu.so.3.7.0] Error 1
CMakeFiles/Makefile2:1766: recipe for target 'src/backend/cpu/CMakeFiles/afcpu.dir/all' failed
make[1]: *** [src/backend/cpu/CMakeFiles/afcpu.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

Does that mean libfftw3.a has to be recompiled with "-fPIC"?
I installed libfftw3 with sudo apt command "sudo apt-get install libopenblas-dev libfftw3-dev liblapacke-dev"

Thank you so much.

**Comment by umar456** [comment]
I don't think apt installs libraries in the /usr/local directory and it doesn't install static libraries. It seems like you have a per-existing install in the /usr/local directory that is conflicting with the one installed in /usr/lib

**Comment by auvilink** [comment]
Thanks for the quick replay. this might be the issue. However, 
"cmake .. -DCMAKE_BUILD_TYPE=Release" give out this error, which might cause the following "make -j8" issue? 

  CMake Error at extern/forge/src/backend/opengl/CMakeLists.txt:5 (add_library):
  Target "forge" links to target "Freetype::Freetype" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

Thanks. again.

**Comment by 9prady9** [comment]
Freetype is a dependency for graphics functionality. On ubuntu, usually when fontconfig is installed, freetype gets installed automatically as it is a transitive dependency. We have listed fontconfig among the required dependencies of our wiki. https://github.com/arrayfire/arrayfire/wiki/Build-Instructions-for-Linux#arrayfire-graphics-library

Can you please check if fontconfig or freetype are installed on your Ubuntu system.

**Comment by auvilink** [comment]
I moved to a new ubuntu machine for the installation. fontconfig is installed, but freetype seems not installed. I manually installed it (which requires HarfBuzz). Anyway, "cmake .. -DCMAKE_BUILD_TYPE=Release" still gives out the same error, but "make -j8" finishes fine.

I also tried to modify "extern/forge/src/backend/opengl/CMakeLists.txt" but without luck.

Thanks.

**Comment by 9prady9** [comment]
ArrayFire builds doesn't need to link against forge as it is dl-loaded at runtime. Hence the make command finishes for you even though forge's cmake generation reports error. Nevertheless, if freetype is installed, forge shouldn't report an error.

Please check this https://packages.ubuntu.com/xenial/libfontconfig1-dev link you can find `libfreetype6-dev` as dependency. I am not sure why it wasn't installed on your machine.

Can you try in a clean build folder. `cd build && rm <all files under build>` and now do a fresh cmake generation.

**Comment by auvilink** [comment]
I tried abain to install from a clean ubuntu 16.04 and followed your instruction: Below are the errors:

-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Check size of int
-- Check size of int - done
-- Could NOT find MKL (missing:  MKL_INCLUDE_DIR MKL_Core_LINK_LIBRARY) 
-- Boost version: 1.58.0
-- BOOST_COMPUTE: /home/asa/facebook/arrayfire/build/boost_compute-prefix/src/boost_compute
CMake Error at extern/forge/CMakeLists.txt:50 (find_package):
  By not providing "Findglm.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "glm", but
  CMake did not find one.

  Could not find a package configuration file provided by "glm" with any of
  the following names:

    glmConfig.cmake
    glm-config.cmake

  Add the installation prefix of "glm" to CMAKE_PREFIX_PATH or set "glm_DIR"
  to a directory containing one of the above files.  If "glm" provides a
  separate development package or SDK, be sure it has been installed.

Should I manually install "glm" first?

Thanks.

**Comment by auvilink** [comment]
I added Findglm.cmake, FindFreetype.cmake (which requires FindPackageMessage.cmake ,FindPackageHandleStandardArgs.cmake ) to  extern/forge/CMakeModules.

Now it builds fine.

**Comment by zdgithub** [comment]
> I added Findglm.cmake, FindFreetype.cmake (which requires FindPackageMessage.cmake ,FindPackageHandleStandardArgs.cmake ) to extern/forge/CMakeModules.
> 
> Now it builds fine.
> 
> Thanks.

I faced the same problem, how to add Findglm.cmake, FindFreetype.cmake? And I couldn't find where the directory extern/forge is.
![image](https://user-images.githubusercontent.com/24309565/50553977-1627cb80-0ced-11e9-9a69-a00f050414df.png)

**Comment by 9prady9** [comment]
There are couple of things here:

Graphics dependencies are a must as mentioned [here](https://github.com/arrayfire/arrayfire/wiki/Build-Instructions-for-Linux#arrayfire-graphics-library) to build with graphics, even though ArrayFire cmake configuation reports it as failure, it is only a cmake generation failure of forge(ArrayFire's graphics upstream) project and ArrayFire can be still built fine. We will look into the ways on how to handle these cmake error messages from forge better.

If you have already installed required graphics dependencies as in the case of @zdgithub , I believe it is an issue from the package itself where they don't ship the necessary `<package>-config.cmake` or `<packageConfig.cmake` files along with the package installation. As far as I am aware, freetype cmake files are provided in all the unix flavor distros(at least most of them) including OSX. You can find out where `glmConfig.cmake` or `glm-config.cmake` files are on your system using `locate` command. Locate command comes with `mlocate` package on Ubuntu 16.04.

**Comment by zdgithub** [comment]
I locate the `glmConfig.cmake` and `glm-config.cmake`, but find nothing. They don't exist.

**Comment by zdgithub** [comment]
After doing  `updatedb`, I still find nothing.

**Comment by 9prady9** [comment]
The problem is with the version of glm package provided by apt package manager. As I suspected earlier, the package installed by apt on ubuntu 16.04 doesn't have necessary cmake configuration files.

I think similar problems with glm can be handled permanently by making glm a submodule for forge. I will test this out and send in a fix for this soon.

Thank you.

**Comment by zhengqun** [comment]
![image](https://user-images.githubusercontent.com/34435100/50671596-ceb37f00-100d-11e9-86d0-1f932480f1bb.png)

**Comment by zhengqun** [comment]
i want to know what should  i do ?

**Comment by 9prady9** [comment]
@zhengqun Is this the issue you reported in #2395 ? Just verifying if it is or not.

**Comment by zhengqun** [comment]
![image](https://user-images.githubusercontent.com/34435100/50720982-95a10a80-10f2-11e9-917a-4c8d189245aa.png)

**Comment by zhengqun** [comment]
![image](https://user-images.githubusercontent.com/34435100/50721818-90e35300-1100-11e9-9fa0-b2970fd1754d.png)
How can i do?

**Comment by 9prady9** [comment]
What are the contents of the folder "extern/glad" under the repository root
?

**Comment by zhengqun** [comment]
@9prady9 yes ,there are glad folder in extern

**Comment by zhengqun** [comment]
@9prady9 And i have done init and update --recursive , every step i have done it

**Comment by 9prady9** [comment]
Can you please send us a dockerfile that can help us reproduce the issue on
our end reliably.
