### ISSUE TITLE
Address binary JIT operations where combined node is too large

### ISSUE THREAD

**Issue by umar456** [arrayfire/arrayfire#2389]
JIT operations that take two or more operands can fail due to a large parameter size in case of non-linear JIT kernels. This sceanario appeared in issue https://github.com/arrayfire/arrayfire-python/issues/199. You can recreate this error using the following C++ code:

```
TEST(JIT, TwoLargeNonLinear) {
  array a(10, 10);
  array b(10, 10);

  for(int i = 0; i < 23; i++) {
    a += tile(randu(10), 1, 10) + randu(10, 10);
  }

  for(int i = 0; i < 23; i++) {
    b += tile(randu(10), 1, 10) + randu(10, 10);
  }


  array c = a + b;
  c.eval();
  af::sync();
}
```

**Comment by 9prady9** [comment]
Fixed in https://github.com/arrayfire/arrayfire/pull/2484
