### ISSUE TITLE
Building arrayfire error: not providing 'Findglm.cmake'

### ISSUE THREAD

**Issue by zdgithub** [arrayfire/arrayfire#2391]
I follow the steps to build ArrayFire in: https://github.com/arrayfire/arrayfire/wiki/Build-Instructions-for-Linux#installing-dependencies
and I have successfully installed the general dependencies and ArrayFire graphics libraries:
![image](https://user-images.githubusercontent.com/24309565/50554495-5770a900-0cf6-11e9-8ccb-2df32ce69811.png)
but when I build, the error occured:
![image](https://user-images.githubusercontent.com/24309565/50554516-af0f1480-0cf6-11e9-83ad-e1e3d5c558ff.png)

I haven't found the right way to solve it.

**Comment by 9prady9** [comment]
@zdgithub I have replied to your question on the other issue where you first asked this question
https://github.com/arrayfire/arrayfire/issues/2388#issuecomment-450614832

Please have a look at it and let me know.

**Comment by zdgithub** [comment]
I'm sorry to tell you that when I build arrayfire a new error occurred:
```
-- Found MKL: /opt/intel/mkl/include  
-- Boost version: 1.64.0
CMake Error at CMakeModules/boost_package.cmake:40 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  Boost::boost
Call Stack (most recent call first):
  CMakeLists.txt:40 (include)

```

**Comment by 9prady9** [comment]
That is odd, I didn't face that error when I tried in fresh 16.04 docker image. Are you using Ubuntu 16.04 ? or different distro ?

**Comment by zdgithub** [comment]
> That is odd, I didn't face that error when I tried in fresh 16.04 docker image. Are you using Ubuntu 16.04 ? or different distro ?

yeah
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
```

**Comment by 9prady9** [comment]
The boost_package cmake script has been working fine and hasn't been touched in a year or so. I wonder why it is misbehaving. Did you try a fresh build folder i.e. cmake and make in a fresh build directory ?

**Comment by zdgithub** [comment]
yes, I have tried to `rm -rf build` and `mkdir build && cd build` ,then execute the cmake, but the error still exists

**Comment by 9prady9** [comment]
hm, I am out of ideas at the moment then. Will look into it a bit later. Also, Can you please open a new github issue regarding this. It is better to keep different problems in different github issues for tracking and future references. Thank you.
