### ISSUE TITLE
Building arrayfire: CMake Error at CMakeModules/boost_package.cmake

### ISSUE THREAD

**Issue by zdgithub** [arrayfire/arrayfire#2393]
when I try to build arrayfire in my Ubuntu16.04, the error occured:
```
-- Found MKL: /opt/intel/mkl/include  
-- Boost version: 1.64.0
CMake Error at CMakeModules/boost_package.cmake:40 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  Boost::boost
Call Stack (most recent call first):
  CMakeLists.txt:40 (include)
...
...

-- Configuring incomplete, errors occurred!
```

**Comment by 9prady9** [comment]
I haven't been able to reproduce it on my end. How did you install boost ? The boost version from apt seems to be 1.58 which is what I have and I am not facing any issue. Hence asked how did you install boost 1.64.

Are you using docker by any chance ? If so, what is the base image ?

**Comment by zdgithub** [comment]
Thank you, I solved it by adding the environment variable `MKLROOT` to `~/.bashrc`
`export MKLROOT=/opt/intel/mkl`

**Comment by 9prady9** [comment]
I am not sure how that will fix it.

**Comment by zdgithub** [comment]
Oh, sorry, I mixed up.  I didn't solve it.
Finally I download the official binary for Linux to avoid the problem.

**Comment by zdgithub** [comment]
I installed the boost1.64. following the steps below
- `wget https://dl.bintray.com/boostorg/release/1.64.0/source/boost_1_64_0.tar.gz`
- `tar zxvf boost_1_64_0.tar.gz`
- `cd boost_1_64_0`
- `./bootstrap.sh`
- `./b2 install`

**Comment by 9prady9** [comment]
I will try it out soon and post an update.

**Comment by 9prady9** [comment]
@zdgithub I was able to use 1.64 boost just fine on clean ubuntu 16.04(docker image). At this point, it is safe to assume the issue is specific to your development setup.

**Comment by zdgithub** [comment]
Okay, Thank you!
