### ISSUE TITLE
lack of glad/glad.h

### ISSUE THREAD

**Issue by zhengqun** [arrayfire/arrayfire#2395]
how can i do?

**Comment by pavanky** [comment]
Install it following the instructions from here: https://github.com/Dav1dde/glad

**Comment by umar456** [comment]
Did you clone recursively? It is brought in as a submodule.

**Comment by zhengqun** [comment]
Yes

发自我的 iPhone

**Comment by zhengqun** [comment]
![error](https://user-images.githubusercontent.com/34435100/50628906-2225be80-0f75-11e9-8bb7-fc3ae0d3c5fc.png)

**Comment by umar456** [comment]
I don't think you have initialized and updated the submodules or didn't recursive clone the repo. Both of those files are provided by submodules. Run these commands in your repo:

```
git submodule init
git submodule update
```

and build again. You should get further along. For these types of items you should go to our google groups forums or the slack chat. We can better help you there.

**Comment by zhengqun** [comment]
![image](https://user-images.githubusercontent.com/34435100/50670008-c0f8fc00-1003-11e9-8e61-b198ae7689d2.png)

**Comment by zhengqun** [comment]
I have done  this step : init and  update   @umar456

**Comment by 9prady9** [comment]
@zhengqun The submodule should be updated as `git submodule update --init --recursive`

**Comment by zhengqun** [comment]
![image](https://user-images.githubusercontent.com/34435100/50720973-7efab380-10f2-11e9-9f17-95e5df292b18.png)

**Comment by 9prady9** [comment]
Was the glad related issue resolved?

Which CUDA version are you using? I believe cublas device library is
removed in CUDA 10 and we made changes with respect to that in master I
believe. I will have to check cmake.

**Comment by 9prady9** [comment]
I am out of ideas, can you please send us a Dockerfile where you are able
to reproduce the issue so that we can reproduce this issue reliably on our
end as well. Thank you.

**Comment by 9prady9** [comment]
@zhengqun I am pretty sure I ran similar dockerfile couple of days ago in #2373 . With this version of the docker config, I was able to successfully build CUDA backend and tests. What is your base image for this dockerfile, I don't see the `FROM` entry in above comment ? 

Also, please clarify if we are still talking about `glad/glad.h` not found error ? or the `CUDA_cublas_device_LIBRARY` variable error in cmake generation step.

**Comment by zhengqun** [comment]
@9prady9  make error

**Comment by zhengqun** [comment]
![image](https://user-images.githubusercontent.com/34435100/50755986-b190e180-1295-11e9-8458-e214087516cb.png)

@9prady9  make error

**Comment by 9prady9** [comment]
Unfortunately, I am unable to reproduce this reliably on my end.

What is the output of "git submodule status" under "arrayfire" source
directory.

Also, please paste the output of "git submodule status" from the folder
"arrayfire/extern/forge".

**Comment by zhengqun** [comment]
![image](https://user-images.githubusercontent.com/34435100/50759361-c70b0900-129f-11e9-89ce-0c8aaf714b63.png)

@9prady9 there is output result

**Comment by 9prady9** [comment]
@zhengqun Can you come online over our slack channel ? Would be easy for quick back-and-forth

**Comment by tiru1930** [comment]
@zhengqun   I had the same error glad.h not found , but when i upgraded cmake to  cmake version 3.13.2
 , i am able to build this without any  erorros

**Comment by 9prady9** [comment]
@tiru1930 That may be true, but I haven't faced the problem he did even with 3.10 cmake. So, it should be working with 3.10 just fine as I was able to using 3.10 cmake on docker image.

@zhengqun A quick question, are you sure you are using 3.10 cmake binary ? Any chance the command `cmake` command is referring to old version binary ?

**Comment by zhengqun** [comment]
![image](https://user-images.githubusercontent.com/34435100/50762144-202a6b00-12a7-11e9-9047-46899f8e914b.png)

@9prady9

**Comment by 9prady9** [comment]
hm. Please give 3.13 cmake a try in that case. I can't think of anything else right now.

**Comment by zhengqun** [comment]
![image](https://user-images.githubusercontent.com/34435100/50765045-a6e34600-12af-11e9-903a-e506ba4d567a.png)
@9prady9 
when i build docker image ,i meet this error

**Comment by zhengqun** [comment]
![image](https://user-images.githubusercontent.com/34435100/50812471-d8125380-134d-11e9-9588-dd1a89432568.png)

@9prady9  hi i use dockerfile ,but meet this error

**Comment by 9prady9** [comment]
@zhengqun I have replied to ryour identical comment on #2373 issue. Please respond in only one location going forward, as it would be difficult to keep track of single issue across multiple github-issues.

**Comment by 9prady9** [comment]
@zhengqun has the issue been resolved at your end?

**Comment by zhengqun** [comment]
yes,Thank s for your help .  I build it in my continer , do not  use Dockfile.
