### ISSUE TITLE
how can I install it on CentOS 7?

### ISSUE THREAD

**Issue by chenbblei** [arrayfire/arrayfire#2397]
I want to install it on CentOS 7,but only installed on Unbuntu is showed

**Comment by umar456** [comment]
We provide RPM files on our website. Check out this [link](http://arrayfire.s3.amazonaws.com/3.6.2/ArrayFire-v3.6.2_Linux_x86_64.rpm).

I  think you can run `yum localinstall ArrayFire-v3.6.2_Linux_x86_64.rpm` to install the library.

**Comment by WilliamTambellini** [comment]
the .sh there should also do the job:
https://arrayfire.com/download/
