### ISSUE TITLE
Remove the need for freetype if not needed

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#2400]
On a regular default ubuntu 16 using AF master (as today) :
$cmakebin ..
-DAF_WITH_GRAPHICS=OFF
-DAF_WITH_STATIC_FREEIMAGE=OFF
-DAF_WITH_IMAGEIO=OFF
...
CMake Error at /home/wtambellini/repos/xmt-externals/FC12/tools/cmake/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
Could NOT find Freetype (missing: FREETYPE_LIBRARY) (found version "2.6.1")
Call Stack (most recent call first):
/home/wtambellini/repos/xmt-externals/FC12/tools/cmake/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
/home/wtambellini/repos/xmt-externals/FC12/tools/cmake/share/cmake-3.9/Modules/FindFreetype.cmake:140 (find_package_handle_standard_args)
extern/forge/CMakeLists.txt:48 (find_package)

That machine does seem to have the freetype dev :
$ locate libfreetype.
/usr/lib/i386-linux-gnu/libfreetype.so.6
/usr/lib/i386-linux-gnu/libfreetype.so.6.12.1
/usr/lib/x86_64-linux-gnu/libfreetype.a
/usr/lib/x86_64-linux-gnu/libfreetype.la
/usr/lib/x86_64-linux-gnu/libfreetype.so
/usr/lib/x86_64-linux-gnu/libfreetype.so.6
/usr/lib/x86_64-linux-gnu/libfreetype.so.6.12.1

$ sudo apt-get install libfreetype6-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libfreetype6-dev is already the newest version (2.6.1-0.1ubuntu2.3).

Should nt we be able to build a non graphics AF without the need for freetype dev if the user does nt need to do any GUI things?

**Comment by WilliamTambellini** [comment]
Note : the build instructions 
https://github.com/arrayfire/arrayfire/wiki/Build-Instructions-for-Linux
mentions
"Recommended: FreeImage (version 3), cmake-curses-gui"
but as today freeimage-dev seems mandatory to build AF.
I m sure freetype was not mandatory few months ago.

**Comment by umar456** [comment]
We are in the process of making the graphics dependencies a runtime dependency and merging the two builds. The current build process may have diverted in the mean time and I am working on fixing it in case there are missing dependencies. I am working on this now and should update the build instructions soon.

**Comment by WilliamTambellini** [comment]
cool thanks.
