### ISSUE TITLE
Sample using the C API is broken

### ISSUE THREAD

**Issue by alessandrobessi** [arrayfire/arrayfire#2405]
The *Sample using the C API* tutorial (http://arrayfire.org/docs/gettingstarted.htm) is broken:
```
#include <arrayfire.h>
// Generate random data and sum and print the result
int main(void)
{
    // generate random values
    int n = 10000;
    af_array a;
    af_randu(&a, n);
    // sum all the values
    float result;
    af_sum_all(&result, a, 0);
    printf("sum: %g\n", sum);
    return 0;
}
```
Indeed, 
- `sum` inside `printf` is not defined (we should use `result`);
- `result` has to be a `double`;
- `af_randu` gets 4 arguments (see: http://arrayfire.org/docs/group__random__func__randu.htm#ga412e2c2f5135bdda218c3487c487d3b5).

Here a working version:
```
// generate random values
af_array a;
int n_dims = 1;
dim_t dims[] = {10000};
af_randu(&a, n_dims, dims, f32);

// sum all the values
double result;
af_sum_all(&result, 0, a);
printf("sum: %g\n", result);
```

**Comment by 9prady9** [comment]
@alessandrobessi Thank you for reporting it. Are you interested in sending a PR for the fix ? If not I can send it in.

**Comment by alessandrobessi** [comment]
@9prady9 I cloned the repo, I created a new branch `bugfix/gettingstarted` to edit the file but I can't push. I get `remote: Permission to arrayfire/arrayfire.git denied to alessandrobessi.
fatal: unable to access 'https://github.com/arrayfire/arrayfire.git/': The requested URL returned error: 403
`
