### ISSUE TITLE
./helloworld/helloworld_{cpu,cuda,opencl} dyld: Library not loaded: /usr/local/opt/glbinding/lib/libglbinding.2.dylib   Referenced from: /opt/arrayfire/lib/libafcpu.3.dylib   Reason: image not found Abort trap: 6

### ISSUE THREAD

**Issue by tranhoangkhuongvn** [arrayfire/arrayfire#2408]
MacOS 10.14
Run time error when running example following this testing installation
http://arrayfire.org/docs/installing.htm
I was able to install, cmake .. and make successfully 
When try to run ./helloworld/helloworld_{cpu,cuda,opencl} then get the above error, copy here for completeness

./helloworld/helloworld_{cpu,cuda,opencl}
dyld: Library not loaded: /usr/local/opt/glbinding/lib/libglbinding.2.dylib
  Referenced from: /opt/arrayfire/lib/libafcpu.3.dylib
  Reason: image not found
Abort trap: 6

Thank you

**Comment by praisethemoon** [comment]
Hello, I just got the same issue, just run 
```brew install glbinding```

Problem. Solved.

**Comment by 9prady9** [comment]
@tranhoangkhuongvn @praisethemoon We are about to make 3.6.3 release and with that glbinding dependency is completely removed and you won't have any issues related to that aspect. I shall update here once we have the 3.6.3 binaries available for download on our website.

**Comment by 9prady9** [comment]
3.6.3 release is out. Please check it out

**Comment by 9prady9** [comment]
Closing since glbinding dependency is removed since 3.6.3
