### ISSUE TITLE
Arrayfire with CUDA 9.1 / Visual studio 15 2017 (build v140) results in DeviceManager(void)

### ISSUE THREAD

**Issue by guatavita** [arrayfire/arrayfire#2409]
Hello,

I am trying to run the arrayfire example "qr_cuda.exe" and its resulting in the following error:

> ArrayFire Exception (Internal error:998):
> In function __cdecl cuda::DeviceManager::DeviceManager(void)
> In file src\backend\cuda\platform.cpp:509
> CUDA Error (35): CUDA driver version is insufficient for CUDA runtime version
> 
> In function void __cdecl af::setDevice(const int)
> In file src\api\cpp\device.cpp:92

Here is the output of the "qr_cpu.exe" example:

> ArrayFire v3.6.2 (CPU, 64-bit Windows, build dc38ef13)
> [0] Intel: Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz, 130993 MB, Max threads(16)

Here is the output of the "qr_opencl.exe" example:

> ArrayFire v3.6.2 (OpenCL, 64-bit Windows, build dc38ef13)
> [0] NVIDIA: Quadro M2000, 4096 MB

I am using CUDA 9.1, Visual Studio community 15 2017 with CMake and the build option v140 to use Visual Studio 2015 (avoid the toolset v141 uncompatibility). My system variables PATH contains the following variables:

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\libnvvp
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\nvvm\bin
%AF_PATH%\lib
C:\Program Files\ArrayFire\v3.6\lib

Do you have any idea of what could cause the problem?

Best regards,

EDIT:
The CUDA examples in "C:\ProgramData\NVIDIA Corporation\CUDA Samples\v9.1\bin\win64\Release" runs well.

Here is the output of "batchCUBLAS.exe":

> batchCUBLAS Starting...
> GPU Device 0: "Quadro M2000" with compute capability 5.2
> [...]
> Test Summary
> 0 error(s)

**Comment by guatavita** [comment]
Any idea?

I am using the NVIDIA Driver 388.19.

**Comment by umar456** [comment]
Can you upgrade your driver? The v3.6.2 installers require version 410.

**Comment by guatavita** [comment]
Hello,

I am coming back on this thread. I have poor performance with CUDA for this qr.cpp example:

> #include <arrayfire.h>
> #include <cstdio>
> #include <cstdlib>
> 
> #include <iostream>
> #include <ctime>
> 
> using namespace af;
> 
> int main(int argc, char *argv[])
> {
>     try {
>         // Select a device and display arrayfire info
>         int device = argc > 1 ? atoi(argv[1]) : 0;
>         af::setDevice(device);
>         af::info();
> 
>         std::clock_t start;
>         double duration;
>         start = std::clock();
> 
>         for (int i = 0; i < 1000; i++) {
>           array in = randu(5, 8);
>           array qin = in.copy();
>           array tau;
>           qrInPlace(tau, qin);
>           array q, r;
>           qr(q, r, tau, in);
>         }
>         duration = (std::clock() - start) / (double)CLOCKS_PER_SEC;
>         std::cout << "printf: " << duration << '\n';
>     } catch (af::exception& e) {
>         fprintf(stderr, "%s\n", e.what());
>         throw;
>     }
>     return 0;
> }

This example runs in 0.058s on an Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz, 130993 MB, Max threads(16) and on 2.775s on a Quadro M2000, 4096 MB, CUDA Compute 5.2.

I wanted to use Arrayfire to convert one of my VTK-based application from CPU to GPU by using af::array and Arrayfire functions compared to looping on VTK points and have something running in few seconds compared to minutes with VTK, but the performance are not here. Any idea why the M2000 is not running faster?

**Comment by guatavita** [comment]
Hello,

I am coming back on this thread. I have poor performance with CUDA for this qr.cpp example:

```
#include <arrayfire.h>
#include <cstdio>
#include <cstdlib>

#include <iostream>
#include <ctime>

using namespace af;

int main(int argc, char *argv[])
{
  try {
    // Select a device and display arrayfire info
    int device = argc > 1 ? atoi(argv[1]) : 0;
    af::setDevice(device);
    af::info();

    std::clock_t start;
    double duration;
    start = std::clock();

    for (int i = 0; i < 1000; i++) {
      array in = randu(5, 8);
      array qin = in.copy();
      array tau;
      qrInPlace(tau, qin);
      array q, r;
      qr(q, r, tau, in);
    }
    duration = (std::clock() - start) / (double)CLOCKS_PER_SEC;
    std::cout << "printf: " << duration << '\n';
  }
  catch (af::exception& e) {
    fprintf(stderr, "%s\n", e.what());
    throw;
  }
  return 0;
}
```

This example runs in 0.058s on an Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz, 130993 MB, Max threads(16) and on 2.775s on a Quadro M2000, 4096 MB, CUDA Compute 5.2.

I wanted to use Arrayfire to convert one of my VTK-based application from CPU to GPU by using af::array and Arrayfire functions compared to looping on VTK points and have something running in few seconds compared to minutes with VTK, but the performance are not here. Any idea why the M2000 is not running faster?

**Comment by umar456** [comment]
Closing in favor or #2410
