### ISSUE TITLE
GPU / CPU matmul performance

### ISSUE THREAD

**Issue by guatavita** [arrayfire/arrayfire#2414]
Hello,

I am trying to convert my application from CPU to GPU to reduce the computation time. I have found a part in my code that i cannot improve.

Here is a simple example of the code that is not working in my algorithm:

```
#include <arrayfire.h>
#include <cstdio>
#include <cstdlib>

using namespace af;

void function();

int main(int argc, char *argv[])
{
  try {
    // Select a device and display arrayfire info
    int device = argc > 1 ? atoi(argv[1]) : 0;
    af::setDevice(device);
    af::info();

    for (int i = 0; i < 1000; i++) {
      function();
    }
  }
  catch (af::exception& e) {
    fprintf(stderr, "%s\n", e.what());
    throw;
  }
  return 0;
}

void function() {
  int N = 2000;
  int D = 3;

  af::array ones = constant(1, N, f64);
  af::array rand1 = randu(N, D, f64);
  af::array q2 = randu(N, N - D - 1, f64);  
  af::array K = randu(N, N, f64);  
  af::array id1 = 0.001 * af::identity(N - D - 1, N - D - 1, f64);

  af::array T = join(1, ones, rand1);

  timer t = timer::start();
  af::array gamma = matmul(inverse(matmul(transpose(q2), K, q2) + id1), transpose(q2), T);
  printf("gamma: %g seconds\n", timer::stop(t));
}
```

When i run this example with ArrayFire::afcpu, some iterations compute gamma in less than 0.001s and some iterations are up to 2-2.5s. 
When i run this example with ArrayFire::afcuda, all the iterations compute gamma in 1.2-1.7s.

I have the feeling that I am using Arrayfire the wrong way or i am missing something that i don't understand. This part of my algorithm is taking a lot of time and i don't know how to improve the performance. 

Any Idea?

PS: 
CPU: Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz, 130993 MB, Max threads(16)
GPU: Quadro M2000, 4096 MB, CUDA Compute 5.2

**Comment by WilliamTambellini** [comment]
1 Try first to run a dummy/warmup call on what you want to compute before starting the timer for af do the one time jit taks.
2 Try to use af::timeit()

**Comment by umar456** [comment]
All ArrayFire calls are asynchronous. After some time some calls block to let the command queue catch up. I think this is what you are seeing on the CPU side. On the CUDA side the inverse call is blocking because there is some synchronization is required to implement that call.

I also noticed you are transposing the array before calling the matrix multiply. You can pass AF_MAT_TRANS as the third argument to let the matmul perform that operation. 

The last thing is that you have a pretty narrow matrix. GPU libraries are not really optimized to perform that operation without a custom kernel. I have been meaning to write one but haven't gotten around to it. I think for these sizes the CPU will be faster than the GPU.

**Comment by guatavita** [comment]
Thank you for your suggestions. 

I have tried with AF_MAT_TRANS, i have better performance for the second part of the matmul but none for the 3 matrices multiplication with the GPU.

However, I measured the computation time using af::timeit and i have longer computation time. Is it because timeit is waiting for the function to completely finish?

For example:

```
#include <arrayfire.h>
#include <cstdio>
#include <cstdlib>

using namespace af;

void function();

int main(int argc, char *argv[])
{
  try {
    // Select a device and display arrayfire info
    int device = argc > 1 ? atoi(argv[1]) : 0;
    af::setDevice(device);
    af::info();

    for (int i = 0; i < 1000; i++) {
      timer t = timer::start();
      printf("timeit: %g seconds\n", timeit(function));
      //function();
      printf("outside t: %g seconds\n", timer::stop(t));
    }
  }
  catch (af::exception& e) {
    fprintf(stderr, "%s\n", e.what());
    throw;
  }
  return 0;
}

void function() {
  int N = 2000;
  int D = 3;
  af::array ones = constant(1, N, f64);
  af::array rand1 = randu(N, D, f64);
  af::array q2 = randu(N, N - D - 1, f64);  // size is [N][N-D-1]  
  af::array K = randu(N, N, f64);  // size is [N][N-D-1]  
  af::array id1 = 0.001 * af::identity(N - D - 1, N - D - 1, f64);
  af::array T = join(1, ones, rand1);
  af::array gamma = matmul(inverse(matmul(matmul(q2, K, AF_MAT_TRANS), q2) + id1), matmul(q2, T, AF_MAT_TRANS));
}
```

Output with CPU:
timeit: 0.840335 seconds
outside t: 12.325 seconds

Output with GPU (second iterations):
timeit: 1.17597 seconds
outside t: 17.6337 seconds

Without the timeit function, the computation seems to be faster, i don't understand. Could you tried the example and see if you have the same pattern?

Best,

**Comment by guatavita** [comment]
I just found out that performance of my algorithm change drastically between using f32 or f64 array.

My algorithm iteration takes 2.6s per iteration with f64 arrays and drops to 0.22s with f32. I need to compute around 160-200 iterations for good convergence, so the computation time is really different.

Do you think it is coming from my GPU?

**Comment by guatavita** [comment]
Thank you for the clarifications, I have read the following articles and i understand better. Dropping the link here for other users that need information like this:

https://arrayfire.com/explaining-fp64-performance-on-gpus/
https://en.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units

Best,

Bastien

**Comment by 9prady9** [comment]
@guatavita Please close the issue if you think all questions have been answered and no issues on your end.
Thank you.
