### ISSUE TITLE
Window::setColorMap() does not work with Window::surface()

### ISSUE THREAD

**Issue by alessandrobessi** [arrayfire/arrayfire#2424]
If I try to use a different colormap instead of the default one (`AF_COLORMAP_DEFAULT`), `Window::surface()` still renders using the default colormap.

Here a piece of reproducible code.
```
/*
g++ surface.cpp -o surface -lm -lafcpu
*/

#include <arrayfire.h>
#include <math.h>
#include <cstdio>

using namespace af;

const int M = 50;
const int N = 2 * M;

int main()
{

    try
    {
        info();
        Window window(800, 800, "3d Surface Example");
        window.setColorMap(AF_COLORMAP_PLASMA);
        window.setAxesTitles("X", "Y", "Z");

        const array x = iota(dim4(N, 1), dim4(1, N)) / M - 1;
        const array y = iota(dim4(1, N), dim4(N, 1)) / M - 1;

        float t = 0;

        while (!window.close())
        {
            t += 0.05;
            array z = cos(2 * y + t) + sin(2 * x + t);
            window.surface(z);
        }
    }
    catch (exception &e)
    {
        fprintf(stderr, "%s\n", e.what());
        throw;
    }
    return 0;
}
```

Indeed, if `void Window::setColorMap(const ColorMap cmap) { _cmap = cmap; }` why then is `void Window::surface(const array& S, const char* const title)` using `AF_COLORMAP_DEFAULT` instead of `_cmap` (code below)?

```
void Window::surface(const array& S, const char* const title) {
    af::array xVals = range(S.dims(0));
    af::array yVals = range(S.dims(1));
    af_cell temp{_r, _c, title, AF_COLORMAP_DEFAULT};
    AF_THROW(af_draw_surface(get(), xVals.get(), yVals.get(), S.get(), &temp));
}
```
For example, `void Window::image(const array& in, const char* const title)` is using `_cmap`:
```
void Window::image(const array& in, const char* const title) {
    af_cell temp{_r, _c, title, _cmap};
    AF_THROW(af_draw_image(get(), in.get(), &temp));
}
```
and indeed it works (see the fractal.cpp example and try using a different colormap).

https://github.com/arrayfire/arrayfire/blob/bef327fe36ff616bef9b7a6a015b6df18ea8f832/src/api/unified/graphics.cpp

**Comment by 9prady9** [comment]
@alessandrobessi color maps were never intended for use on surfaces, not at least until now. They are for images. The way color maps are interpreted in the code doesn't make it suitable for surfaces at the moment.

**Comment by 9prady9** [comment]
If you would want that as a feature, please do raise a feature request and we would be happy to look into it.
