### ISSUE TITLE
BUG ArrayFire af::eval() premature data type mismatch erorr

### ISSUE THREAD

**Issue by CorgiForce** [arrayfire/arrayfire#2426]
This code is giving me datatype mismatch error.

    const double dd = 0.225;
    af::array aa = af::constant(111, 10, f32) + dd;
    af::array bb = af::constant(111, 10, f64) + dd;
    af::eval(aa, bb);

Both aa and bb should be f64 because both add a double value. There shouldn't be a datatype mismatch error.

I have asked this on [stackoverflow](https://stackoverflow.com/questions/54317698/arrayfire-afeval-premature-data-type-mismatch-erorr) and the other guys said the underlying code still keeps the array a f32. Assuming that's true, I am losing precision and it is a lot different than how C++/C#/Java automatically increase the precision when a higher precision value is used in an operation.

Regardless what really is going on, my expectation is, both array should be f64 and the af::eval() will not raise the error. This is two parts issue:
1. If it didn't increase to f64, I really want it fixed. Because it is not easy to hunt down all the code that expects implicit datatype conversion. And a new developer will highly likely make a same mistake because this behave differently than typical C++/C#/Java.
2. If it is just a false alarm raised by af::eval() because of the delayed evaluation and it hasn't evaluated `af::constant(111, 10, f32) + dd`, I would like to know about it and I would consider this a less important issue.

Thank you

**Comment by pavanky** [comment]
@CorgiForce If you use a math op with `af::array` and a scalar, the type of `af::array` is kept. If you two `af::array`s, the higher precision is kept.

This was done because many times people use stuff like this:
```
af::array b = 0.5 * a;
```
When they really mean something like this: 
```
af::array b = 0.5f * a;
```
Automatically assuming users want double precision results in performance degradation a lot of times because double precision on GPUs is sometimes order of magnitude slower than single precision.

In your usecase, you could do something like this:

```
const double d = 0.225;
af::array dd = af::constant(d, 10, f64);
af::array aa = af::constant(111, 10, f32) + dd;
af::array bb = af::constant(111, 10, f64) + dd;
af::eval(aa, bb);
```

**Comment by CorgiForce** [comment]
Hmmmmm.... I guess there won't be any change to this? It does makes sense if we want our method to automatically change precision based on input array without writing if-statements to use the correct scaler datatype. So, it seems to be a good thing actually.

I will let my team know, so, we will program with that in mind.
