### ISSUE TITLE
af::eval() does not accept const array

### ISSUE THREAD

**Issue by CorgiForce** [arrayfire/arrayfire#2427]
This code is cannot be compiled
```
const af::array myConstArray= af::constant(111, 10, f64);
af::eval(myConstArray);
```

But, this code can be compiled
```
const af::array myConstArray= af::constant(111, 10, f64);
myConstArray.eval();
```

Currently I wrote my own af::eval to get around this problem
```
af::eval(const af::array &a, const af::array &b, ...)
{
  a.eval();
  ...
}
```

But, why doesn't af::eval() accept const array? Is this just an oversight or this is intentional? What would be the consequences if I `const_cast<af::array *>(&a)` and feed that into your `af::eval(count, af::array*)` similar to how you wrote your `af::eval(const af::array &a, const af::array &b, ...)`?

Thank you

**Comment by umar456** [comment]
You can do that without issue. There are no consequences for taking that approach. I think the logic for excluding it was that it modifies the internal state but the af::array logically does not change. We can add this API in a future release. If you want to submit a PR you are welcome to do so if you already have something.

**Comment by CorgiForce** [comment]
I will just wait for the future release instead. I don't want to mess up your code. I am not experienced enough to make PR to this, not yet. But, please add a comment here if it is updated. Thank you. :)
