### ISSUE TITLE
random generation not consistent for same seed on GPU vs CPU

### ISSUE THREAD

**Issue by gonzaloiglesiasiglesias** [arrayfire/arrayfire#2429]
I'm feeding a fixed seed to the default random engine; I don't get the same results if I run on CPU vs on GPU, which makes it harder for testing. Is there anything i'm missing that I could do to get identical results?
 
std::shared_ptr<af::randomEngine> rand_;
rand_.reset(new af::randomEngine(AF_RANDOM_ENGINE_DEFAULT, static_cast<uintl>(1234)));
af::randu(someshape, af_dtype::f32, *rand_);

**Comment by umar456** [comment]
We are using the same algorithm for both versions but I think we are propagating the state incorrectly between iterations. Ideally they would be the same. I don't think it would be difficult to fix.

**Comment by 9prady9** [comment]
Addressed in https://github.com/arrayfire/arrayfire/pull/2435
