### ISSUE TITLE
Arrayfire with clFFT backport

### ISSUE THREAD

**Issue by skn123** [arrayfire/arrayfire#2430]
Is there any example in AF that use clFFT for computing a FFT? Please share some pointers to this effect.

**Comment by 9prady9** [comment]
I am not sure if understand your question. OpenCL backend uses clftt by default

**Comment by skn123** [comment]
What I meant is the following: 
a.) There is an example in the examples/benchmarks folder (fft.cpp). I tried digging into the code but could not find anything that uses clFFT. 
b.) There is a fork of clFFT in arrayfire also. What I want is to run the fft1d example of clFFT, but from within arrayfire. 
c.) If not possible, then is there any example to load an array in AF, and run fft but with clFFT as the backend (using OpenCL and a Radeon GPU).

**Comment by skn123** [comment]
Duh.. my bad. Found the usecase. I am closing this issue. It is in fft.cpp in the opencl backend.
