### ISSUE TITLE
CUDA_ERROR_INVALID_IMAGE error when running arrayfire on GPU

### ISSUE THREAD

**Issue by gonzaloiglesiasiglesias** [arrayfire/arrayfire#2436]
I am running into the following error:

terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Internal error:998):
In function cuda::kc_entry_t cuda::compileKernel(const char*, std::string)
In file src/backend/cuda/jit.cpp:342
CU Error CUDA_ERROR_INVALID_IMAGE(200): device kernel image is invalid

In function af::array af::operator+(const af::array&, const af::array&)
In file src/api/cpp/array.cpp:920

Running with AF_CUDA_MAX_JIT_LEN=10 makes the error go away. Also, running on cpu is fine.
Any ideas?

**Comment by 9prady9** [comment]
Can you please give more details such as the following:
- The version of ArrayFire are you using
- The GPU on which ArrayFire is running
- CUDA driver version
- Operating System

**Comment by WilliamTambellini** [comment]
- AF 3.6.2
- GPU : reproduced with both TitanV and TitanX
- NVIDIA-SMI 396.37 
- OS: CentOS Linux release 7.5.1804 (Core)

**Comment by WilliamTambellini** [comment]
Probably similar to 
https://github.com/arrayfire/arrayfire/issues/2084
which has been closed without any fix ?

**Comment by umar456** [comment]
Thats my guess. I have a fix that is in the works. It will take me a bit to get it working. For now you may need to add an eval manually.

**Comment by umar456** [comment]
But this is a different error so I am curious about the kernel generated.

**Comment by WilliamTambellini** [comment]
Also reproduced on GTX1060 using default AF_CUDA_MAX_JIT_LEN=100 : 
terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Internal error:998):
In function cuda::kc_entry_t cuda::compileKernel(const char*, std::string)
In file src/backend/cuda/jit.cpp:342
CU Error CUDA_ERROR_INVALID_IMAGE(200): device kernel image is invalid
In function af::array af::operator+(const af::array&, const af::array&)
In file src/api/cpp/array.cpp:920
Aborted (core dumped)

I have to reduce AF_CUDA_MAX_JIT_LEN down to 20 to make it run.

**Comment by WilliamTambellini** [comment]
The very first step would be to log which kernel is failing to load : 
example : in cache.cpp line 188 : 

    CUresult r = cuModuleLoadDataEx(&module, cubin, 0, 0, 0);
    if (r != CUDA_SUCCESS)
        AF_WARN("buildKernel: cuModuleLoadDataEx failed for kernel " << ker_name);
    CU_CHECK(r);

**Comment by WilliamTambellini** [comment]
Doc about cuModuleLoadDataEx:
https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__MODULE.html#group__CUDA__MODULE_1g9e8047e9dbf725f0cd7cafd18bfd4d12

**Comment by WilliamTambellini** [comment]
from
https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__TYPES.html#group__CUDA__TYPES_1gc6c391505e117393cc2558fff6bfc2e9

CUDA_ERROR_INVALID_IMAGE = 200
    This indicates that the device kernel image is invalid. This can also indicate an invalid CUDA module. 

In my case, the number/size of parameters  is far too long : 

extern "C" __global__ void
KER11182484426184996469(
float *in0_ptr, int in_index0,
float *in1_ptr, int in_index1,
float scalar2, 
float scalar3, 
float scalar4, 
float scalar6, 
float scalar7, 
float *in8_ptr, int in_index8,
float scalar9, 
float scalar13, 
float scalar17, 
float scalar18, 
float scalar20, 
float scalar21, 
float scalar25, 
float scalar29, 
float scalar31, 
float scalar35, 
float scalar38, 
float *in39_ptr, int in_index39,
float scalar41, 
float scalar43, 
float scalar45, 
float *in48_ptr, int in_index48,
float *in49_ptr, int in_index49,
float scalar50, 
float scalar51, 
float scalar52, 
float scalar54, 
float scalar55, 
float *in56_ptr, int in_index56,
float scalar57, 
float scalar61, 
float scalar65, 
float scalar66, 
float scalar68, 
float scalar69, 
float scalar73, 
float scalar77, 
float scalar79, 
float scalar83, 
float scalar86, 
float *in87_ptr, int in_index87,
float scalar89, 
float scalar91, 
float scalar93, 
float *in96_ptr, int in_index96,
float *in97_ptr, int in_index97,
float scalar98, 
float scalar99, 
float scalar100, 
float scalar102, 
float scalar103, 
float *in104_ptr, int in_index104,
float scalar105, 
float scalar109, 
float scalar113, 
float scalar114, 
float scalar116, 
float scalar117, 
float scalar121, 
float scalar125, 
float scalar127, 
float scalar131, 
float scalar134, 
float *in135_ptr, int in_index135,
float scalar137, 
float scalar139, 
float scalar141, 
float *in144_ptr, int in_index144,
float *in145_ptr, int in_index145,
float scalar146, 
float scalar147, 
float scalar148, 
float scalar150, 
float scalar151, 
float *in152_ptr, int in_index152,
float scalar153, 
float scalar157, 
float scalar161, 
float scalar162, 
float scalar164, 
float scalar165, 
float scalar169, 
float scalar173, 
float scalar175, 
float scalar179, 
float scalar182, 
float *in183_ptr, int in_index183,
float scalar185, 
float scalar187, 
float scalar189, 
float *in192_ptr, int in_index192,
float *in193_ptr, int in_index193,
float scalar194, 
float scalar195, 
float scalar196, 
float scalar198, 
float scalar199, 
float *in200_ptr, int in_index200,
float scalar201, 
float scalar205, 
float scalar209, 
float scalar210, 
float scalar212, 
float scalar213, 
float scalar217, 
float scalar221, 
float scalar223, 
float scalar227, 
float scalar230, 
float *in231_ptr, int in_index231,
float scalar233, 
float scalar235, 
float scalar237, 
float *in240_ptr, int in_index240,
float *in241_ptr, int in_index241,
float scalar242, 
float scalar243, 
float scalar244, 
float scalar246, 
float scalar247, 
float *in248_ptr, int in_index248,
float scalar249, 
float scalar253, 
float scalar257, 
float scalar258, 
float scalar260, 
float scalar261, 
float scalar265, 
float scalar269, 
float scalar271, 
float scalar275, 
float scalar278, 
float *in279_ptr, int in_index279,
float scalar281, 
float scalar283, 
float scalar285, 
float *in288_ptr, int in_index288,
float *in289_ptr, int in_index289,
float scalar290, 
float scalar291, 
float scalar292, 
float scalar294, 
float scalar295, 
float *in296_ptr, int in_index296,
float scalar297, 
float scalar301, 
float scalar305, 
float scalar306, 
float scalar308, 
float scalar309, 
float scalar313, 
float scalar317, 
float scalar319, 
float scalar323, 
float scalar326, 
float *in327_ptr, int in_index327,
float scalar329, 
float scalar331, 
float scalar333, 
float *in336_ptr, int in_index336,
float *in337_ptr, int in_index337,
float scalar338, 
float scalar339, 
float scalar340, 
float scalar342, 
float scalar343, 
float *in344_ptr, int in_index344,
float scalar345, 
float scalar349, 
float scalar353, 
float scalar354, 
float scalar356, 
float scalar357, 
float scalar361, 
float scalar365, 
float scalar367, 
float scalar371, 
float scalar374, 
float *in375_ptr, int in_index375,
float scalar377, 
float scalar379, 
float scalar381, 
float *in384_ptr, int in_index384,
float *in385_ptr, int in_index385,
float scalar386, 
float scalar387, 
float scalar388, 
float scalar390, 
float scalar391, 
float *in392_ptr, int in_index392,
float scalar393, 
float scalar397, 
float scalar401, 
float scalar402, 
float scalar404, 
float scalar405, 
float scalar409, 
float scalar413, 
float scalar415, 
float scalar419, 
float scalar422, 
float *in423_ptr, int in_index423,
float scalar425, 
float scalar427, 
float scalar429, 
float *in432_ptr, int in_index432,
float *in433_ptr, int in_index433,
float scalar434, 
float scalar435, 
float scalar436, 
float scalar438, 
float scalar439, 
float *in440_ptr, int in_index440,
float scalar441, 
float scalar445, 
float scalar449, 
float scalar450, 
float scalar452, 
float scalar453, 
float scalar457, 
float scalar461, 
float scalar463, 
float scalar467, 
float scalar470, 
float *in471_ptr, int in_index471,
float scalar473, 
float scalar475, 
float scalar477, 
float *in480_ptr, int in_index480,
float *in481_ptr, int in_index481,
float scalar482, 
float scalar483, 
float scalar484, 
float scalar486, 
float scalar487, 
float *in488_ptr, int in_index488,
float scalar489, 
float scalar493, 
float scalar497, 
float scalar498, 
float scalar500, 
float scalar501, 
float scalar505, 
float scalar509, 
float scalar511, 
float scalar515, 
float scalar518, 
float *in519_ptr, int in_index519,
float scalar521, 
float scalar523, 
float scalar525, 
float *in528_ptr, int in_index528,
float *in529_ptr, int in_index529,
float scalar530, 
float scalar531, 
float scalar532, 
float scalar534, 
float scalar535, 
float *in536_ptr, int in_index536,
float scalar537, 
float scalar541, 
float scalar545, 
float scalar546, 
float scalar548, 
float scalar549, 
float scalar553, 
float scalar557, 
float scalar559, 
float scalar563, 
float scalar566, 
float *in567_ptr, int in_index567,
float scalar569, 
float scalar571, 
float scalar573, 
float *in576_ptr, int in_index576,
float *in577_ptr, int in_index577,
float scalar578, 
float scalar579, 
float scalar580, 
float scalar582, 
float scalar583, 
float *in584_ptr, int in_index584,
float scalar585, 
float scalar589, 
float scalar593, 
float scalar594, 
float scalar596, 
float scalar597, 
float scalar601, 
float scalar605, 
float scalar607, 
float scalar611, 
float scalar614, 
float *in615_ptr, int in_index615,
float scalar617, 
float scalar619, 
float scalar621, 
float *in624_ptr, int in_index624,
float *in625_ptr, int in_index625,
float scalar626, 
float scalar627, 
float scalar628, 
float scalar630, 
float scalar631, 
float *in632_ptr, int in_index632,
float scalar633, 
float scalar637, 
float scalar641, 
float scalar642, 
float scalar644, 
float scalar645, 
float scalar649, 
float scalar653, 
float scalar655, 
float scalar659, 
float scalar662, 
float *in663_ptr, int in_index663,
float scalar665, 
float scalar667, 
float scalar669, 
float *in672_ptr, int in_index672,
float *in673_ptr, int in_index673,
float scalar674, 
float scalar675, 
float scalar676, 
float scalar678, 
float scalar679, 
float *in680_ptr, int in_index680,
float scalar681, 
float scalar685, 
float scalar689, 
float scalar690, 
float scalar692, 
float scalar693, 
float scalar697, 
float scalar701, 
float scalar703, 
float scalar707, 
float scalar710, 
float *in711_ptr, int in_index711,
float scalar713, 
float scalar715, 
float scalar717, 
float *in720_ptr, int in_index720,
float *in721_ptr, int in_index721,
float scalar722, 
float scalar723, 
float scalar724, 
float scalar726, 
float scalar727, 
float *in728_ptr, int in_index728,
float scalar729, 
float scalar733, 
float scalar737, 
float scalar738, 
float scalar740, 
float scalar741, 
float scalar745, 
float scalar749, 
float scalar751, 
float scalar755, 
float scalar758, 
float *in759_ptr, int in_index759,
float scalar761, 
float scalar763, 
float scalar765, 
float *in768_ptr, int in_index768,
float *in769_ptr, int in_index769,
float scalar770, 
float scalar771, 
float scalar772, 
float scalar774, 
float scalar775, 
float *in776_ptr, int in_index776,
float scalar777, 
float scalar781, 
float scalar785, 
float scalar786, 
float scalar788, 
float scalar789, 
float scalar793, 
float scalar797, 
float scalar799, 
float scalar803, 
float scalar806, 
float *in807_ptr, int in_index807,
float scalar809, 
float scalar811, 
float scalar813, 
float *in816_ptr, int in_index816,
float *in817_ptr, int in_index817,
float scalar818, 
float scalar819, 
float scalar820, 
float scalar822, 
float scalar823, 
float *in824_ptr, int in_index824,
float scalar825, 
float scalar829, 
float scalar833, 
float scalar834, 
float scalar836, 
float scalar837, 
float scalar841, 
float scalar845, 
float scalar847, 
float scalar851, 
float scalar854, 
float *in855_ptr, int in_index855,
float scalar857, 
float scalar859, 
float scalar861, 
float scalar864, 
float *in865_ptr, int in_index865,
float *in866_ptr, int in_index866,
float scalar867, 
float *in871_ptr, int in_index871,
float scalar872, 
float scalar873, 
float scalar876, 
float scalar879, 
float scalar882, 
float *in885_ptr, int in_index885,
float scalar886, 
float scalar888, 
float scalar890, 
float scalar893, 
float scalar896, 
float *in897_ptr, int in_index897,
float *in898_ptr, int in_index898,
float scalar899, 
float *in903_ptr, int in_index903,
float scalar904, 
float scalar905, 
float scalar908, 
float scalar911, 
float scalar914, 
float *in917_ptr, int in_index917,
float scalar918, 
float scalar920, 
float scalar922, 
float scalar925, 
float scalar928, 
float *in929_ptr, int in_index929,
float *in930_ptr, int in_index930,
float scalar931, 
float *in935_ptr, int in_index935,
float scalar936, 
float scalar937, 
float scalar940, 
float scalar943, 
float scalar946, 
float *in949_ptr, int in_index949,
float scalar950, 
float scalar952, 
float scalar954, 
float scalar957, 
float scalar960, 
float *in961_ptr, int in_index961,
float *in962_ptr, int in_index962,
float scalar963, 
float *in967_ptr, int in_index967,
float scalar968, 
float scalar969, 
float scalar972, 
float scalar975, 
float scalar978, 
float *in981_ptr, int in_index981,
float scalar982, 
float scalar984, 
float scalar986, 
float scalar989, 
float scalar992, 
float *in993_ptr, int in_index993,
float *in994_ptr, int in_index994,
float scalar995, 
float *in999_ptr, int in_index999,
float scalar1000, 
float scalar1001, 
float scalar1004, 
float scalar1007, 
float scalar1010, 
float *in1013_ptr, int in_index1013,
float scalar1014, 
float scalar1016, 
float scalar1018, 
float scalar1021, 
float scalar1024, 
float *in1025_ptr, int in_index1025,
float *in1026_ptr, int in_index1026,
float scalar1027, 
float *in1031_ptr, int in_index1031,
float scalar1032, 
float scalar1033, 
float scalar1036, 
float scalar1039, 
float scalar1042, 
float *in1045_ptr, int in_index1045,
float scalar1046, 
float scalar1048, 
float scalar1050, 
float scalar1053, 
float scalar1056, 
float *in1057_ptr, int in_index1057,
float *in1058_ptr, int in_index1058,
float scalar1059, 
float *in1063_ptr, int in_index1063,
float scalar1064, 
float scalar1065, 
float scalar1068, 
float scalar1071, 
float scalar1074, 
float *in1077_ptr, int in_index1077,
float scalar1078, 
float scalar1080, 
float scalar1082, 
float scalar1085, 
float scalar1088, 
float *in1089_ptr, int in_index1089,
float *in1090_ptr, int in_index1090,
float scalar1091, 
float *in1095_ptr, int in_index1095,
float scalar1096, 
float scalar1097, 
float scalar1100, 
float scalar1103, 
float scalar1106, 
float *in1109_ptr, int in_index1109,
float scalar1110, 
float scalar1112, 
float scalar1114, 
float scalar1117, 
float scalar1120, 
float *in1121_ptr, int in_index1121,
float *in1122_ptr, int in_index1122,
float scalar1123, 
float *in1127_ptr, int in_index1127,
float scalar1128, 
float scalar1129, 
float scalar1132, 
float scalar1135, 
float scalar1138, 
float *in1141_ptr, int in_index1141,
float scalar1142, 
float scalar1144, 
float scalar1146, 
float scalar1149, 
float scalar1152, 
float *in1153_ptr, int in_index1153,
float *in1154_ptr, int in_index1154,
float scalar1155, 
float *in1159_ptr, int in_index1159,
float scalar1160, 
float scalar1161, 
float scalar1164, 
float scalar1167, 
float scalar1170, 
float *in1173_ptr, int in_index1173,
float scalar1174, 
float scalar1176, 
float scalar1178, 
float scalar1181, 
float scalar1184, 
float *in1185_ptr, int in_index1185,
float *in1186_ptr, int in_index1186,
float scalar1187, 
float *in1191_ptr, int in_index1191,
float scalar1192, 
float scalar1193, 
float scalar1196, 
float scalar1199, 
float scalar1202, 
float *in1205_ptr, int in_index1205,
float scalar1206, 
float scalar1208, 
float scalar1210, 
float scalar1213, 
float scalar1216, 
float *in1217_ptr, int in_index1217,
float *in1218_ptr, int in_index1218,
float scalar1219, 
float *in1223_ptr, int in_index1223,
float scalar1224, 
float scalar1225, 
float scalar1228, 
float scalar1231, 
float scalar1234, 
float *in1237_ptr, int in_index1237,
float scalar1238, 
float scalar1240, 
float scalar1242, 
float scalar1245, 
float scalar1248, 
float *in1249_ptr, int in_index1249,
float *in1250_ptr, int in_index1250,
float scalar1251, 
float *in1255_ptr, int in_index1255,
float scalar1256, 
float scalar1257, 
float scalar1260, 
float scalar1263, 
float scalar1266, 
float *in1269_ptr, int in_index1269,
float scalar1270, 
float scalar1272, 
float scalar1274, 
float scalar1277, 
float scalar1280, 
float *in1281_ptr, int in_index1281,
float *in1282_ptr, int in_index1282,
float scalar1283, 
float *in1287_ptr, int in_index1287,
float scalar1288, 
float scalar1289, 
float scalar1292, 
float scalar1295, 
float scalar1298, 
float *in1301_ptr, int in_index1301,
float scalar1302, 
float scalar1304, 
float scalar1306, 
float scalar1309, 
float scalar1312, 
float *in1313_ptr, int in_index1313,
float *in1314_ptr, int in_index1314,
float scalar1315, 
float *in1319_ptr, int in_index1319,
float scalar1320, 
float scalar1321, 
float scalar1324, 
float scalar1327, 
float scalar1330, 
float *in1333_ptr, int in_index1333,
float scalar1334, 
float scalar1336, 
float scalar1338, 
float scalar1341, 
float scalar1344, 
float *in1345_ptr, int in_index1345,
float *in1346_ptr, int in_index1346,
float scalar1347, 
float *in1351_ptr, int in_index1351,
float scalar1352, 
float scalar1353, 
float scalar1356, 
float scalar1359, 
float scalar1362, 
float *in1365_ptr, int in_index1365,
float scalar1366, 
float scalar1368, 
float scalar1370, 
float scalar1373, 
float scalar1376, 
float *in1377_ptr, int in_index1377,
float *in1378_ptr, int in_index1378,
float scalar1379, 
float *in1383_ptr, int in_index1383,
float scalar1384, 
float scalar1385, 
float scalar1388, 
float scalar1391, 
float scalar1394, 
float *in1397_ptr, int in_index1397,
float scalar1398, 
float scalar1400, 
float scalar1402, 
float scalar1405, 
float scalar1408, 
float *in1409_ptr, int in_index1409,
float *in1410_ptr, int in_index1410,
float scalar1411, 
float *in1415_ptr, int in_index1415,
float scalar1416, 
float scalar1417, 
float scalar1420, 
float scalar1423, 
float scalar1426, 
float *in1429_ptr, int in_index1429,
float scalar1430, 
float scalar1432, 
float scalar1434, 
Param out1436, 
Param* dims, int num_params, uint blocks_x, uint blocks_y, uint blocks_x_total, uint num_odims)

**Comment by 9prady9** [comment]
Thank you for additional logs and information. A brief update from our end, as you might have noticed, we have already began working on the fix for this issue. Please check #2458 PR.

**Comment by WilliamTambellini** [comment]
An example of code making AF to generate such crazy kernel : 
out = data + af::tile(right, 1, 1, ztile)
with 
data being 32 x 512
right being 32 x 512
ztile = 1  (yes, in that case tiling is not needed but is of course needed when ztile > 1)
The tree generating these crazy kernels of course contains dozen of other ops coming from previous AF commands.
