### ISSUE TITLE
release v3.6.2  depends on debug DLL: glbindingd.dll , (and glbinding.dll)

### ISSUE THREAD

**Issue by PeterMJ** [arrayfire/arrayfire#2447]
In the latest release glbinding.dll AND glbindingd.dll have been included and it appears that afcpu.dll afopencl.dll and afcuda.dll depend on both. 

The debug version DLL then relies on microsoft's debug libraries which cannot be distributed, but more practically AF should not be linking a release build with the debug library (and its release version).

I have discovered this whilst testing an application that uses AF, and found that our test machines did not have this installed because we had not installed any development tools as normal. Is there any chance you could re-release 3.6.2 without linking to glbindingd.dll? The released libraries are currently unusable for any deployed application. (I am trying to rebuild the libraries myself, but struggling.)

I have used dependency walker to look at the DLL links, but was first alerted by error prompt directly on the machines refering to Microsoft's debug run-time. It is also clear when you look in the bin directory and see both DLLs have been included, which is a warning all by itself.

Thanks for a great library, I've enjoyed using it and one day will hopefully contribute a bit more than a bug report.

**Comment by 9prady9** [comment]
@PeterMJ we are aware of this issue and have rectified this is current master also.

**Comment by 9prady9** [comment]
@PeterMJ I understand what I am about to suggestion is not a fix but I assume deployed applications don't use graphics functionality and hence you can install [ArrayFire-no-gl.exe](http://arrayfire.s3.amazonaws.com/3.6.2/ArrayFire-no-gl-v3.6.2.exe) which doesn't involve glbinding at all.

**Comment by 9prady9** [comment]
I shall update here once I have new binary that doesn't involve glbinding uploaded into our website.

**Comment by PeterMJ** [comment]
Thank you for your help, I am just downloading the above. I have also tried deleting the debug version and copying and renaming the release version and that works and lets my application run.

**Comment by 9prady9** [comment]
glbinding is not an dependency of arrayfire anymore.
