### ISSUE TITLE
Can you make a release?

### ISSUE THREAD

**Issue by svenstaro** [arrayfire/arrayfire#2456]
The last release is quite long ago and the current release isn't even compatible with your current forge version. Could you cut a release with all the new improvements?

**Comment by 9prady9** [comment]
@svenstaro We do plan on having one by end of this month, hopefully. 

We are keen on pushing half data type support #2413 for 3.7 release. @umar456 is actively working on it and it will be ready very soon. There are couple of other good functions #2254 and #2359 that we are about to merge into master. Once these are in, we will do a release as soon as possible.

**Comment by svenstaro** [comment]
Ok, sounds fair. As a distro maintainer, I'd appreciate slightly smaller incremental releases in the future, though.

**Comment by 9prady9** [comment]
@svenstaro You said something about incompatibility of forge & arrayfire, what exactly do you mean by that ? Can you please elaborate.

**Comment by svenstaro** [comment]
The current most recent release of arrayfire does not build cleanly against
the newest release of forge. I can provide logs if you'd like to see but if
I'm right you should be able to reproduce it on your own. Tell me if you
want the logs from me and I'll so a quick compile.

**Comment by 9prady9** [comment]
@svenstaro Okay, just wanted to make sure if that's you meant - forge 1.0.4 not compiling with arrayfire 3.6.2. We will try our best to push a 3.6.3 with updates before end of month.

**Comment by svenstaro** [comment]
Yes that what I meant. Update would be great.

**Comment by WilliamTambellini** [comment]
3.6.4 released 1 year ago and 3.7.0 few weeks ago.
Could be closed ?
