### ISSUE TITLE
Error running Helloword example

### ISSUE THREAD

**Issue by sanakhamekhem** [arrayfire/arrayfire#2457]
Hi, 
I have an issue when running helloword example:
arrayfire 3.6.2
Cuda 9.2

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.54                 Driver Version: 396.54                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:04:00.0  On |                  N/A |
| 33%   57C    P8    20W / 250W |    180MiB / 11177MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  TITAN Xp            Off  | 00000000:05:00.0 Off |                  N/A |
| 50%   78C    P2   186W / 250W |  11721MiB / 12196MiB |     49%      Default |
+-------------------------------+----------------------+----------------------+

ArrayFire Exception (Internal error:998):
In function cuda::DeviceManager::DeviceManager()
In file src/backend/cuda/platform.cpp:509
CUDA Error (35): CUDA driver version is insufficient for CUDA runtime version

In function void af::setDevice(int)
In file src/api/cpp/device.cpp:92
terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Internal error:998):
In function cuda::DeviceManager::DeviceManager()
In file src/backend/cuda/platform.cpp:509
CUDA Error (35): CUDA driver version is insufficient for CUDA runtime version

In function void af::setDevice(int)
In file src/api/cpp/device.cpp:92
Abandon (core dumped)

**Comment by 9prady9** [comment]
3.6.2 release is built with CUDA 10 and that requires a minimum driver version of Linux(410.48), Windows(411.31).
Please update GPU driver to latest.

**Comment by WilliamTambellini** [comment]
Note : 3.7.0 will kindly print the minimum needed driver version in order for AF to be able to run.
