### ISSUE TITLE
Failure in build for docs

### ISSUE THREAD

**Issue by kgizdov** [arrayfire/arrayfire#2469]
Docs fail to build with warnings as errors set to `ON` (doxygen 1.18.5):
```
build/arrayfire/src/arrayfire-full-3.6.2/docs/pages/configuring_arrayfire_environment.md:9: error: multiple use of section label 'environment_variables' while adding section, (first occurrence: /build/arrayfire/src/arrayfire-full-3.6.2/docs/pages/configuring_arrayfire_environment.md, line 1) (warning treated as error, aborting now)
make[2]: *** [docs/CMakeFiles/docs.dir/build.make:58: docs/CMakeFiles/docs] Error 1
make[1]: *** [CMakeFiles/Makefile2:28212: docs/CMakeFiles/docs.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by umar456** [comment]
I think this is a known issue with older doxygen 1.18.x versions. You can either download latest version of doxygen or disable building of docs. I don't think we can do anything to circumvent this issue.

**Comment by kgizdov** [comment]
@umar456 this is an issue only with doxygen 1.8.7, fixed in 1.8.8 - I am using the latest available 1.18.15.

**Comment by 9prady9** [comment]
I was able to reproduce this on Arch linux, will send in a fix soon. @kgizdov Thanks for reporting it.

**Comment by 9prady9** [comment]
To confirm that issue is with 1.8.15, I have downgraded doxygen to 1.8.14 and the documentation built as expected.

**Comment by kgizdov** [comment]
@9prady9 , thanks for looking into it. it's a shame... in the meantime, I've patched it like so:
```patch
diff --git a/docs/doxygen.mk b/docs/doxygen.mk
index 5d4e0237..05c4e12c 100644
--- a/docs/doxygen.mk
+++ b/docs/doxygen.mk
@@ -769,7 +769,7 @@ WARN_NO_PARAMDOC       = YES
 # a warning is encountered.
 # The default value is: NO.
 
-WARN_AS_ERROR          = YES
+WARN_AS_ERROR          = NO
 
 # The WARN_FORMAT tag determines the format of the warning messages that doxygen
 # can produce. The string should contain the $file, $line, and $text tags, which
```

**Comment by kgizdov** [comment]
Upstream bug - https://github.com/doxygen/doxygen/issues/6779

**Comment by 9prady9** [comment]
Good catch on doxygen issue list. Can you please close this issue since it is not a code issue inside ArrayFire. Thank you.

**Comment by kgizdov** [comment]
Sure.
