### ISSUE TITLE
Titan RTX Cuda backend crashing

### ISSUE THREAD

**Issue by sparsecoder** [arrayfire/arrayfire#2471]
When running benchmarks/blas_cuda I get
```
ArrayFire v3.7.0 (CUDA, 64-bit Linux, build 6da99359)
Platform: CUDA Toolkit 10.0, Driver: 418.43
[0] TITAN RTX, 24191 MB, CUDA Compute 7.5
Benchmark N-by-N matrix multiply
ArrayFire Exception (Internal error:998):
In function cuda::Kernel cuda::buildKernel(const string&, const string&, const std::vector<std::__cxx11::basic_string<char> >&, bool)
In file src/backend/cuda/nvrtc/cache.cpp:157
NVRTC ERROR

In function af::array af::matmul(const af::array&, const af::array&, af::matProp, af::matProp)
In file src/api/cpp/blas.cpp:18
terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Internal error:998):
In function cuda::Kernel cuda::buildKernel(const string&, const string&, const std::vector<std::__cxx11::basic_string<char> >&, bool)
In file src/backend/cuda/nvrtc/cache.cpp:157
NVRTC ERROR

In function af::array af::matmul(const af::array&, const af::array&, af::matProp, af::matProp)
In file src/api/cpp/blas.cpp:18
Aborted (core dumped)
```
I also tried the installer version. The Open CL backend also gives different results and sometimes crashes on my code (comparing against a quadro p2000 mobile). 

Running Linux 4.19.30-1

I checked issue #2343, CMake seems to have found the correct cuda compute (7.5, it is in the output above as well).

**Comment by 9prady9** [comment]
Can you please re-run the code in with arrayfire built in debug mode after setting the following environment variables to suggested values:
- `export AF_PRINT_ERRORS=1`
- `export AF_JIT_KERNEL_TRACE=stdout`

It should print out a good amount information of what caused runtime compilation to fail. Thank you.

**Comment by sparsecoder** [comment]
Thanks

The output is here
https://gist.github.com/sparsecoder/e129c08c2187c14c1646cf32c59db794

**Comment by sparsecoder** [comment]
It seems that when I redirected the output not all of it made it into the file. I'll fix it shortly.

**Comment by sparsecoder** [comment]
The gist is updated now.

**Comment by sparsecoder** [comment]
There seems to be some issue with the logging
Here is the output (not redirected) of the kernel using `AF_JIT_KERNEL_TRACE=stdout`
```
extern "C" __global__ void
KER15803858198028938426(
float scalar0, 
Param<float> out0, 
uint blocks_x, uint blocks_y, uint blocks_x_total, uint num_odims)
{

const Param<float> &outref = out0;

    for (int blockIdx_x = blockIdx.x; blockIdx_x < blocks_x_total; blockIdx_x += gridDim.x) {
    
        uint threadId = threadIdx.x;
        long long idx = blockIdx_x * blockDim.x * blockDim.y + threadId;
        if (idx >= outref.dims[3] * outref.strides[3]) return;
        float val0 = scalar0;
out0.ptr[idx] = val0;
}



In function cuda::Kernel cuda::buildKernel(const string&, const string&, const std::vector<std::__cxx11::basic_string<char> >&, bool)
In file src/backend/cuda/nvrtc/cache.cpp:157
NVRTC ERROR
```

And this is with `AF_JIT_KERNEL_TRACE=stderr`
```
extern "C" __global__ void
KER15803858198028938426(
float scalar0, 
Param<float> out0, 
uint blocks_x, uint blocks_y, uint blocks_x_total, uint num_odims)
{

const Param<float> &outref = out0;

    for (int blockIdx_x = blockIdx.x; blockIdx_x < blocks_x_total; blockIdx_x += gridDim.x) {
    
        uint threadId = threadIdx.x;
        long long idx = blockIdx_x * blockDim.x * blockDim.y + threadId;
        if (idx >= outref.dims[3] * outref.strides[3]) return;
        float val0 = scalar0;
out0.ptr[idx] = val0;
}



}In function cuda::Kernel cuda::buildKernel(const string&, const string&, const std::vector<std::__cxx11::basic_string<char> >&, bool)
In file src/backend/cuda/nvrtc/cache.cpp:157
NVRTC ERROR
```
Note the closing `}`  before the error message (not present in the stdout).

**Comment by 9prady9** [comment]
Yes, that is indeed odd. Final enclosing brace is not present, which is what is probably throwing off the compilation. It is odd though the exact error isn't being printed out. I can see the kernel, but it should print out regularcompilation error message too.

Can you please share the code that is causing this, I will try to reproduce it on my end.

**Comment by sparsecoder** [comment]
I'm running benchmark/blas_cuda.

When I used `AF_JIT_KERNEL_TRACE=stderr` the closing brace is present (but no trailing `\n`).

I think there is a race condition (I don't know if the logging is threaded...), but possibly the stderr output is getting pushed out before stdout finishes and then the abort comes before stdout continues.

**Comment by 9prady9** [comment]
My bad, I am mobile, so didn't notice the benchmark statement. I will check it out and update here once I have something.

**Comment by WilliamTambellini** [comment]
Try 
mkdir /tmp/af
and run with 
AF_JIT_KERNEL_TRACE=/tmp/af
you should see all the jit kernels generated by af in that folder.

**Comment by sparsecoder** [comment]
New gist here
https://gist.github.com/sparsecoder/6ddf826f743d130d489c00cd5c83e70c

Just one file was output to `/tmp/af`.

**Comment by sparsecoder** [comment]
`diff` says the kernel generated on my titan rtx machine is the same as the one on my P2000 mobile...

**Comment by sparsecoder** [comment]
Is there a way to get AF to print the nvrtc result?
https://docs.nvidia.com/cuda/nvrtc/index.html#group__error_1g31e41ef222c0ea75b4c48f715b3cd9f0

Would that be useful?

**Comment by sparsecoder** [comment]
I see in `src/backend/cuda/nvrtc/cache.cpp` that `NVRTC ERROR` prints when `NDBEUG` is defined, otherwise the error number should print. So, I'm not using the compilation with debug flags.

**Comment by sparsecoder** [comment]
`file /usr/local/lib64/libaf.so.3.7.0`
says the debugging symbols are not stripped though.

**Comment by sparsecoder** [comment]
Well, I fixed my local debug problem...
```
NVRTC Error(7): NVRTC_ERROR unknown
```

But the cuda documentation says:
```
NVRTC_ERROR_BUILTIN_OPERATION_FAILURE = 7
```

**Comment by 9prady9** [comment]
I am not sure whats going with the error code, but NVRTC documentation has some incorrect information too, I found out that documentation was wrong about `constant` variables usage. Based on my experience with nvrtc online documentation, I would trust what the error code sent out by code rather than online NVRTC docs.

Yes, the compiler log was supposed to be printed in debug mode. Unfortunately, in my most recent PR I thought the `printf` was a stray `printf` and removed it. Hence, you weren't seeing compile log. I will send in a PR to fix that along with a fix for this issue if it is a bug. 

Can you please apply the following diff to your arrayfire source and rerun the program with `Debug` build type.
```diff
diff --git a/src/backend/cuda/nvrtc/cache.cpp b/src/backend/cuda/nvrtc/cache.cpp
index 176c1dd2..da5ef787 100644
--- a/src/backend/cuda/nvrtc/cache.cpp
+++ b/src/backend/cuda/nvrtc/cache.cpp
@@ -68,6 +68,7 @@ using kc_t = map<string, Kernel>;
         char* logptr = log.get();                      \
         nvrtcGetProgramLog(prog, logptr);              \
         logptr[logSize] = '\x0';                       \
+        printf("Compile log:\n %s\n", logptr);         \
         AF_ERROR("NVRTC ERROR", AF_ERR_INTERNAL);      \
     } while (0)
 #else
```

You can have the other environment variables left out as they are right now.

**Comment by 9prady9** [comment]
@sparsecoder I was able to reproduce this on RTX GPU (T4). I am looking into it and will soon send in a fix. Thanks!

**Comment by 9prady9** [comment]
I found the issue, will soon send in a fix to master.

**Comment by sparsecoder** [comment]
Great! Thank you

**Comment by 9prady9** [comment]
@sparsecoder I have tested this on a T40(compute 7.5) and works as expected. Can you please test PR #2477 on your dev machine too. Thank you.

**Comment by sparsecoder** [comment]
`blas_cuda` works on my Titan RTX now with the #2477 patch. My code is also working.
Thanks!

**Comment by WilliamTambellini** [comment]
Congrats @9prady9. 
Could that one also go into 3.6.3 ?

**Comment by 9prady9** [comment]
This is not needed in 3.6.3 as nvrtc based compilation wasn't added to 3.6.3 PR as of now.
