### ISSUE TITLE
get memory used by an array

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#2474]
Hi, I see 3 methods to get the amount of mem used by an array : 
- bytes()
- allocated()
- elements() * sizeof(datatype)

The doc is pretty light about these methods. 
Could you comment/improve it ?

**Comment by 9prady9** [comment]
I have hyperlinked the relevant docs pages for the following functions. 
- [allocated()](http://arrayfire.org/docs/group__method__mat.htm#ga8bc3e142a14a07815b29e230cefacd3e)
- [bytes()](http://arrayfire.org/docs/group__method__mat.htm#ga3b73c6479b9490ad49b8156e14473541)
- [elements()](http://arrayfire.org/docs/group__method__mat.htm#ga89f91cdf327a8b304589916db5bde3c2)

The size of the internal type can also be found out by `bytes()/elements()`. I think they(function names) are self explanatory to some extent as well. May be some distinction of `allocated` vs `bytes` , but apart from that I don't see any issue.

Kindly elaborate on what you think is missing from their descriptions.

**Comment by WilliamTambellini** [comment]
Yes you are right, the question is just about bytes() vs allocated(). A little example in the doc should be enough.
