### ISSUE TITLE
CUDA Error (11): invalid argument

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#2475]
With AF master compiled in Release with cuda 9.2 : 
ArrayFire v3.7.0 (CUDA, 64-bit Linux, build 6da9935)
Platform: CUDA Toolkit 9.2, Driver: 396.82
[0] GeForce GTX 1060, 6079 MB, CUDA Compute 6.1
...
WARN  AF exception on: 
out = af::matmul(left, right, transposeLeft ? AF_MAT_TRANS : AF_MAT_NONE, transposeRight ? AF_MAT_TRANS : AF_MAT_NONE)
ArrayFire Exception (Internal error:998):
In function cuda::Array<T> cuda::matmul(const cuda::Array<T>&, const cuda::Array<T>&, af_mat_prop, af_mat_prop) [with T = float]
In file src/backend/cuda/blas.cpp:230
CUDA Error (11): invalid argument
In function af::array af::matmul(const af::array&, const af::array&, af::matProp, af::matProp)
In file src/api/cpp/blas.cpp:18
terminate called after throwing an instance of 'std::runtime_error'
  what():  ArrayFire Exception (Internal error:998):
In function cuda::Array<T> cuda::matmul(const cuda::Array<T>&, const cuda::Array<T>&, af_mat_prop, af_mat_prop) [with T = float]
In file src/backend/cuda/blas.cpp:230
CUDA Error (11): invalid argument

It runs well with AF 3.6.2.

**Comment by 9prady9** [comment]
@WilliamTambellini Which code is this from ? helloworld ? or blas benchmark ?

**Comment by umar456** [comment]
Fixed via #2486
