### ISSUE TITLE
Info user on minimum drivers for CUDA toolkits used by ArrayFire binaries

### ISSUE THREAD

**Issue by 9prady9** [arrayfire/arrayfire#2480]

**Comment by 9prady9** [comment]
Upon some discussion over #2483 , we decided to provide this information as part of installer or download page. Hence, the change in title.

**Comment by christophe-murphy** [comment]
Closing for now. The binaries on the website indicate the version of CUDA they were built with. There is a runtime check for a sufficient driver version. This has been updated recently in #3588
