### ISSUE TITLE
speed drops between 3.6.2 and 3.6.3

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#2494]
$ ./miscbench.sh 
gcc version 5.4.0 20160609
ArrayFire v3.6.2 (CUDA, 64-bit Linux, build dc38ef1)
Platform: CUDA Toolkit 9.2, Driver: 418.40.04
[0] GeForce GTX 1060, 6079 MB, CUDA Compute 6.1
greedy3dmatmul: 0.106888
add: 0.003613

gcc version 5.4.0 20160609
ArrayFire v3.6.3 (CUDA, 64-bit Linux, build 25bb360)
Platform: CUDA Toolkit 10.0, Driver: 418.40.04
[0] GeForce GTX 1060, 6079 MB, CUDA Compute 6.1
greedy3dmatmul: 0.156377
add: 0.01505

source code to repro : 
https://gist.github.com/WilliamTambellini/34ccee202c046532494dbecd8f7ceb31

I have noticed other speed drops for some other ops and I will update this issue later. These ones are worry enough.

**Comment by umar456** [comment]
Thanks for posting an example. I will look into this.

**Comment by WilliamTambellini** [comment]
Added a tiled addition bench and moved the sources to a gist : 
3.6.2 : 0.003
3.6.3 : 0.015
5 x slower

**Comment by WilliamTambellini** [comment]
Added a softmax bench: 
3.6.2 : 0.0025
3.6.3 : 0.007
4 x slower

**Comment by WilliamTambellini** [comment]
Added a replace bench (right tiled) : 
3.6.2 : replace: 0.010861
3.6.3 : replace: 0.022672
2 x slower

Tiling seems the culprit.

**Comment by WilliamTambellini** [comment]
Attached the JIT kernels generated by 3.6.3 : 
[jitkernels.zip](https://github.com/arrayfire/arrayfire/files/3109488/jitkernels.zip)

**Comment by WilliamTambellini** [comment]
@umar456 
Comparison of 3.6.2 vs 3.6.3 using the same version of cuda (9.2) : 
3.6.3 built using the remotes/origin/v3.6 branch of https://github.com/arrayfire/arrayfire.git

gcc version 5.4.0 20160609
ArrayFire v3.6.2 (CUDA, 64-bit Linux, build dc38ef1)
Platform: CUDA Toolkit 9.2, Driver: 418.40.04
[0] GeForce GTX 1060, 6079 MB, CUDA Compute 6.1
greedy3dmatmul: 0.106432
add: 0.003582
replace: 0.010867
softmax: 0.001310

gcc version 5.4.0 20160609
ArrayFire v3.6.3 (CUDA, 64-bit Linux, build 25bb360)
Platform: CUDA Toolkit 9.2, Driver: 418.40.04
[0] GeForce GTX 1060, 6079 MB, CUDA Compute 6.1
greedy3dmatmul: 0.155109
add: 0.014985
replace: 0.022663
softmax: 0.004011

About the same speed drop, so the root cause is not cuda 9 vs 10.

**Comment by umar456** [comment]
I was able to find the issue that was causing this slow down. This happened because of the way we were masking the threads in the non-linear kernels. This bug was introduced in #2487. I will be sending a PR soon.

**Comment by WilliamTambellini** [comment]
Tks. Be aware it only resolve some speed drops, not all : 

gcc version 5.4.0 20160609
ArrayFire v3.6.2 (CUDA, 64-bit Linux, build dc38ef1)
Platform: CUDA Toolkit 9.2, Driver: 418.40.04
[0] GeForce GTX 1060, 6079 MB, CUDA Compute 6.1
greedy3dmatmul: 0.108925
add: 0.003665
replace: 0.011018
softmax: 0.001328

./miscbench
gcc version 5.4.0 20160609
ArrayFire v3.7.0 (CUDA, 64-bit Linux, build 5815dec)
Platform: CUDA Toolkit 9.2, Driver: 418.40.04
[0] GeForce GTX 1060, 6079 MB, CUDA Compute 6.1
greedy3dmatmul: 0.126266
add: 0.008744
replace: 0.016283
softmax: 0.002548

so better for replace and softmax but still slower.

**Comment by umar456** [comment]
I have a couple of additional changes that could help improve the runtimes. I should be pushing them soon.

**Comment by WilliamTambellini** [comment]
ArrayFire v3.6.2 (CUDA, 64-bit Linux, build dc38ef1)
Platform: CUDA Toolkit 9.2, Driver: 418.56
[0] GeForce GTX 1060, 6079 MB, CUDA Compute 6.1
greedy3dmatmul: 0.106673
add: 0.003599
replace: 0.010880
softmax: 0.001310

ArrayFire v3.6.4 (CUDA, 64-bit Linux, build 1b8030c)
Platform: CUDA Toolkit 10.0, Driver: 418.56
[0] GeForce GTX 1060, 6079 MB, CUDA Compute 6.1
greedy3dmatmul: 0.106413
add: 0.003601
replace: 0.010802
softmax: 0.001297

Congrats. 
Issue closable I guess.
