### ISSUE TITLE
Unit test memory manager

### ISSUE THREAD

**Issue by umar456** [arrayfire/arrayfire#250]
The memory manager needs additional unit testing. We need to test several scenarios regarding how much memory and how many array objects are allocated for each memory related call.

* Allocation counts(number of af_array objects created)
* Allocation usage(amount of memory allocated)
* Behavior of copy and indexing operations on af_array counts and memory usage
* Parent/child scope behavior

We will need to expose a few functions which will give us memory allocation metrics. These functions do not need to be part of the public API.

**Comment by pentschev** [comment]
Functions that use the memory manager should also be tested to avoid the presence of residual memory after returned.

**Comment by pavanky** [comment]
fixed in devel.
