### ISSUE TITLE
loadImage() and loadImageNative() incorrect results

### ISSUE THREAD

**Issue by kar-dim** [arrayfire/arrayfire#2511]
I know this is probably a FreeImage problem (as I told to 9prary9 via email) but I am not sure.
Specifically I am reading a JPEG image 3 channels.
Some pixels have incorrect values but not for all the channels.
For example a correct rgb value is (249,170,8) but loadImage/Native returns (249,169,8).
I have tested that the (249,170,8) values are correct because
a) Matlab reads these values.
b) CImg library also reads these values.
By using CImg library on my project there are zero errors between the Matlab and CImg loaded images.

**Comment by 9prady9** [comment]
@kar-dim I doubt if it is a bug at all. 

JPEG, in most of the situations, means lossy compression. A maximum of 1-bit difference is acceptable per pixel component while decoding the compressed image data. I have gone through some JPEG related details and [here](https://en.wikipedia.org/wiki/JPEG#Required_precision) are the list of precision requirements mentioned on wikipedia which are to be verified to claim the decoding failed. 

From what you gave and I am aware of JPEG compression, difference of 1is acceptable in decoding output. As far as the results of CImg matching Matlab, I can't comment on it but I know that decoded output definitely changes w.r.t decoding algorithm. 

If you prefer loss-less compression, you should switch to suitable formats such as PNG, GIF, TIFF etc.

I am not sure there is anything we can change in our image loading source code that can modify this behavior of JPEG decoding.

**Comment by kar-dim** [comment]
Ok I understand, thank you.
