### ISSUE TITLE
make-test fails and freezes for cuda backend

### ISSUE THREAD

**Issue by SYnchronYSe** [arrayfire/arrayfire#2524]
I've compiled arrayfire on cuda backend without any errors, but when I run make test, it freezes at test_anisotropic_diffusion cuda. I waited for around 10 minutes, it didn't complete. The CPU and GPU usage was near to zero.

So I ran that test individually to get the following error:

```
Running main() from /home/satishyadav/speech_recognition/arrayfire/test/gtest/googletest/src/gtest_main.cc
[==========] Running 30 tests from 8 test cases.
[----------] Global test environment set-up.
[----------] 4 tests from AnisotropicDiffusion/0, where TypeParam = float
[ RUN      ] AnisotropicDiffusion/0.GradientGrayscale
/home/satishyadav/speech_recognition/arrayfire/test/anisotropic_diffusion.cpp:90: Failure
Expected equality of these values:
  AF_SUCCESS
    Which is: Success
  af_load_image(&_inArray, inFiles[testId].c_str(), isColor)
    Which is: Internal error
[  FAILED  ] AnisotropicDiffusion/0.GradientGrayscale, where TypeParam = float (109 ms)
[ RUN      ] AnisotropicDiffusion/0.GradientColorImage

```
And it freezes at this stage. 
I've tried searching on other threads too.
Any help please?

Specs: 
Nvidia GeForce GT 710
Intel® Core™ i5-8500 CPU @ 3.00GHz × 6 
OS: Ubuntu 16.04LTS
Nvidia driver v384.130
CUDA v10.1

NOTE*: While installing CUDA 10.1, it warned me that it might fail if the driver version is below 417.00
           Could this be a possible reason?

**Comment by 9prady9** [comment]
@SYnchronYSe Yes, that is the reason - you need at least 417 series driver to utilize 10.1 toolkit. It will compile fine, but it will have undefined behavior I would think - I haven't tried running CUDA 10.1 using older driver (i.e. < minimum required 417 series).

**Comment by SYnchronYSe** [comment]
I'll try with a new driver and revert. Thanks.

**Comment by 9prady9** [comment]
Please close this if it is not an issue anymore.

**Comment by SYnchronYSe** [comment]
Thanks. I just tested it again, and it worked.
