### ISSUE TITLE
Cmake not finding Intel Compiler v15 or MKL v11.2 on Windows 7, 64-bit

### ISSUE THREAD

**Issue by tantrev** [arrayfire/arrayfire#254]
Hello,
I've tried to figure out the issue myself but the cmake script is a little beyond me.

When I specify
"INTEL_COMPILER_DIR" as "C:\Program Files (x86)\Intel\Composer XE\compiler"
and
"INTEL_MKL_DIR" as "C:\Program Files (x86)\Intel\Composer XE\mkl"

cmake claims "MKL library not found" and consequently finding CBLAS also fails.  Any ideas on how to fix/update the script for the latest Intel Parallel Studio XE 2015?

**Comment by pavanky** [comment]
@tantrev We are sorry about the delay. Most of us are only coming back this week. We'll try to see if we can solve the issue this week.

As an aside, which backend are you planning to use ? If you are looking to use just CUDA backend, you can skip the CPU parts and build CUDA by using nvcc and visual studio.

**Comment by shehzan10** [comment]
We have been able to use the Intel compiler and MKL to compile (however not the OpenCL backend with the intel compiler).
You can use the arrayfire-windows-scripts (https://github.com/shehzan10/arrayfire-windows-scripts) to use MKL (see the options in common.bat). In rebuild_arrayfire.bat use the following lines just after "echo Generation CMAKE"
```
set CC=C:/Program Files (x86)/Intel/Composer XE 2015/bin/intel64/icl.exe
set CXX=C:/Program Files (x86)/Intel/Composer XE 2015/bin/intel64/icl.exe
%CMAKE% .. %CMAKE_GENERATOR% -T "Intel C++ Compiler XE 15.0" -DCMAKE_CXX_COMPILER:STRING="C:/Program Files (x86)/Intel/Composer XE 2015/bin/intel64/icl.exe" -DCMAKE_C_COMPILER:STRING="C:/Program Files (x86)/Intel/Composer XE 2015/bin/intel64/icl.exe" -DCMAKE_BUILD_TYPE:STRING="%BUILD_TYPE%" -DCMAKE_INSTALL_PREFIX:STRING=%AF_INSTALL_PATH% -DBUILD_TEST:STRING=%TESTS% -DBUILD_GTEST:STRING=%TESTS% -DBUILD_EXAMPLES:STRING=%EXAMPLES% %FREEIMAGE_OPTIONS% %GRAPHICS_OPTIONS% %CPU_OPTIONS% %CUDA_OPTIONS% %OPENCL_OPTIONS%
```
