### ISSUE TITLE
Allow to set cublas MathMode

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#2565]
It looks like cublas (at least 10.0) by default does not use TensorCores.
In order to turn it on, the user must explicitly set the TC math mode : 
https://docs.nvidia.com/cuda/cublas/index.html#cublassetmathmode

"The cublasSetMathMode function enables you to choose whether or not to use Tensor Core operations in the library by setting the math mode to either CUBLAS_TENSOR_OP_MATH or CUBLAS_DEFAULT_MATH. Tensor Core operations perform parallel floating point accumulation of multiple floating point products. Setting the math mode to CUBLAS_TENSOR_OP_MATH indicates that the library will use Tensor Core operations in the functions: cublasHgemm(), cublasGemmEx, cublasSgemmEx(), cublasHgemmBatched() and cublasHgemmStridedBatched(). The math mode default is CUBLAS_DEFAULT_MATH, this default indicates that the Tensor Core operations will be avoided by the library. "

To enable TC : 
cublasSetMathMode(handle, CUBLAS_TENSOR_OP_MATH);

As today, afcuda does not set cublas MathMode, so the default is used : CUBLAS_DEFAULT_MATH.

As a consequence, afcuda today does not take advantage of TensorCores making f16 not really worth it to be used and actually also preventing to use fast f32 low precision gemm.

The goal of this issue is to allow the user of af/afcuda to set the cublas math mode : several options:
1 an environment variable : for example AF_CUDA_MATH_MODE or even AF_MATH_MODE
2 a generic C gemm api : for example: af_gemm_mode(AF_IEEE or AF_LOW_PRECISION ...)
3 a generic set backend option api : example: af_set_backend_option(backend, key, value) : example: af_set_backend_option(AFCUDA, "CUBLAS_MATH_MODE", "CUBLAS_TENSOR_OP_MATH")
4 any other idea

I would prefer option 1 not modifying the AF API, at least time to find a generic API valid for all backends.
Option 3 would be acceptable. 

Kind
WT.

RFC: 
@umar456  @9prady9 @syurkevi  @mark-poscablo  @gonzaloiglesiasiglesias 

Refs: using TC math seems now the default in Tensorflow:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/stream_executor/cuda/cuda_blas.cc
https://fossies.org/linux/tensorflow/tensorflow/stream_executor/cuda/cuda_blas.cc

 // Decide whether to enable TENSOR_OP_MATH
  107 static bool TensorOpMathEnabled() {
  108   static bool is_enabled = [] {
  109     bool is_disabled;
  110     TF_CHECK_OK(
  111         tensorflow::ReadBoolFromEnvVar("TF_DISABLE_CUBLAS_TENSOR_OP_MATH",
  112                                        /*default_val=*/false, &is_disabled));
  113     return !is_disabled;
  114   }();
  115   return is_enabled;
  116 }

**Comment by WilliamTambellini** [comment]
Ok so afcuda does nt use TensorCores because there is just a little bug in: 
https://github.com/arrayfire/arrayfire/blob/master/src/backend/cuda/blas.cpp
Fixing in my next PR.
There is the opportunity to globally enable TC for all cublas using: 
cublasSetMathMode(handle, CUBLAS_TENSOR_OP_MATH);
and speeding up f32 without code change.
TBC

**Comment by umar456** [comment]
Lets move forward with approach number 4. This will allow us to specify optional behavior that may or may not be supported in all backends. Here is the suggested API:

af_err af_set_option(const char* option, const char* value);

This will add a value to the map and change the behaviour of the internals based on this map. Functions can read the map for specific values if necessary.

You can add a map to the DeviceManager class then create a getOption() method which will take a string and return the value of that string if its in the option map. If there is no option in the map then it will return an empty string.

Options will be in the form of:

"af_c_function_name_OPTION_NAME"

Values will be based on the type of option. These values should be documented in the af_set_option api.

You will also need to create an af_get_option function to read these values.

**Comment by WilliamTambellini** [comment]
ok so to summarize : 
- creating/adding af_set_option() in include/af/options.h
- adding a map of string string to DeviceManager
- adding DeviceManager::setOption(const string& key, const string& value)
- adding std::string DeviceManager::getOption(const std::string& key)
- in the cuda DeviceManager (backend/cuda/device_manager.cpp) setOption, call cublasSetMathMode() is the key is CUBLAS_MATH_MODE
- implementing af_set_option() in src/api/c/options.cpp : 
how to find which DeviceManager to use ?

Note: Strangely, there is no DeviceManager base class but several "DeviceManager" classes, in different namespaces, one per backend (cuda, cpu, ...).

**Comment by 9prady9** [comment]
Perhaps we can have a parent class from which each backend's device manager can derive, but I don't see any added advantage other than saving very few lines of code because there are very few commonalities across each backend's DeviceManager class implementation at the moment. Also, DeviceManager's internal API is not needed at `src/api/c/` level and is only required in respective backends. So, I wonder in which use case will this common class would help if there is not much code duplication it is preventing.

**Comment by WilliamTambellini** [comment]
@9prady9 
Well avoiding code duplication is a golden rule in software engineering, even if it s just "few" lines.
Still, an acess to a deviceManager will be needed in af_set_options() in order to set the option in the right backend.
@umar456 in the af_set_option() implementation, how do you propose to find/access the right deviceManager in order to call deviceMgr->setOption(key, value) ?

**Comment by 9prady9** [comment]
In it's current form, the device managers classes of each backend has literally nothing in common to combine the common features into single base class. The only thing they have in common is their name I think, they don't share any logic/algorithm. Hence, what I said earlier and my opinion that it wouldn't have helped this case.

Having said that, if there is new functionality that requires accessing common functionality across all backends that is related to device management, we can take the route of creating base device manager class.

But there is an existing approach where each backend will expose an `setOptions()` function from `cpu`, `cuda` and `opencl` namespaces (`src/backend/{ cpu | cuda | opencl }`), respectively. I prefer this approach to be consistent with everything we have now instead of creating a new base class that has only name in common with the dervied classes(in this case).

**Comment by WilliamTambellini** [comment]
https://github.com/arrayfire/arrayfire/pull/2584

**Comment by 9prady9** [comment]
Addressed in https://github.com/arrayfire/arrayfire/pull/2584

**Comment by ThisIsIsaac** [comment]
@WilliamTambellini

> There is still the opportunity to globally enable TC for all cublas using:
cublasSetMathMode(handle, CUBLAS_TENSOR_OP_MATH);
and speed up f32 without code change.

Tensor Core requires input and weight matrix to be in fp16. So does the above statement mean there is implicit conversion from fp32 -> fp16?
