### ISSUE TITLE
Arrayfire Multithreading

### ISSUE THREAD

**Issue by ZeroCool11000** [arrayfire/arrayfire#2566]
Hello is it possible to have different threads which are using the same GPU, 
just for example doing the same computation but for different data ?

Best regards

**Comment by umar456** [comment]
That is what arrayfire does best. Lets say you have two af::arrays. You can use the join function to combine them into one array that is larger across another dimension and any operation you perform on it will be performed on both arrays. For example:

```c++
array data1 = randu(1000, 10);
array data2 = randu(1000, 10);

// both_data_arrays == dim4(1000, 10, 2);
array both_data_arrays = join(2, data1, data2);

pow(both_data_arrays + both_data_arrays, 2)
```

**Comment by ZeroCool11000** [comment]
thx but why 

pow(both_data_arrays + both_data_arrays, 2) 

i think it should be 

pow(both_data_arrays, 2)

Best regards

**Comment by ZeroCool11000** [comment]
Is it possible to use join for specific number of arrays ? Like for 5 or do i have to use two functions ?

**Comment by umar456** [comment]
It was just an example. I was demonstrating that you can use operators on the array and call pow on it.

Our documentation is available at arrayfire.org. [Here](http://arrayfire.org/docs/group__manip__func__join.htm) is the documentation for join. Looks like you can join up to 4 arrays.
