### ISSUE TITLE
Check correctness of f16 conversions

### ISSUE THREAD

**Issue by umar456** [arrayfire/arrayfire#2570]
We ran into an issue that caused some conversions to be performed incorrectly. It was difficult to identify the issue because it only impacted some of the values. We should have a test that assures that the conversions are reasonable and the result is IEEE compliant.

**Comment by WilliamTambellini** [comment]
Are you referring to the strange result in the half gemm unittest   : 
https://github.com/arrayfire/arrayfire/blob/ca0a896c38a05e0dd03a0b4e59016dc4879291f7/test/blas.cpp#L400
?

**Comment by WilliamTambellini** [comment]
Hum, I dont see anymore the strange behavior we saw 1 month ago :  
when converting f32
30.0000 24.0000 18.0000 
to f16, I got : 
30.2500 24.0000 18.0000

That behavior disappeared with the current master : 

[ RUN      ] MatrixMultiply.half
expected16
[3 3 1 1]
   30.0000    24.0000    18.0000 
   84.0000    69.0000    54.0000 
  138.0000   114.0000    90.0000 

C
[3 3 1 1]
   30.0000    24.0000    18.0000 
   84.0000    69.0000    54.0000 
  138.0000   114.0000    90.0000 

@umar456  did you fix anything recently that could explain that ?

**Comment by umar456** [comment]
Yes that was fixed in #2567

**Comment by WilliamTambellini** [comment]
Cool superb tks.

**Comment by WilliamTambellini** [comment]
To be closed ?
