### ISSUE TITLE
speed drop because of the "enforce deps between alloc and freeze"

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#2573]
The change 
"enforce deps between alloc and freeze" 
86057956bcdeb3ea51773dd9e14af3fc283ab3ef
https://github.com/arrayfire/arrayfire/pull/2526
introduced a 40% speed drop for some non batched neural network inference.
I m trying to identify the culprit ops and will post more info if I find more.
This bug is for sure sensitive to array sizes : I don't see speed drop when training/batched inference so this bug probably hits for small arrays. 

Os: ubuntu 16/CentOS 7
cuda : 10.0
hardware : GTX1060, TitanV, V100

**Comment by WilliamTambellini** [comment]
https://github.com/arrayfire/arrayfire/pull/2574
resolve most of the speed drop

**Comment by umar456** [comment]
Fixed via #2574
