### ISSUE TITLE
Weighted Mean with dim=1

### ISSUE THREAD

**Issue by michaelnowotny** [arrayfire/arrayfire#2594]
Dear ArrayFire developers,

I think I may have discovered an issue with the mean function when providing a set of weights and taking the mean over the second axis (dim=1).

The issue can be reproduced using the following Python code:
----------------------------------------------
import arrayfire as af
import numpy as np

def main():
    af.info()
    a = np.array([[0.2, 1.0, 0.5],
                        [0.4, 0.5, 0.6],
                        [0.7, 0.2, 0.25]],
                       dtype=np.float32)

    weights = np.array([0.2, 0.3, 0.5],
                       dtype=np.float32)

    a_af = af.to_array(a)
    weights_af = af.to_array(weights)

    for axis in (0, 1):
        print(f'axis={axis}')
        average_np = np.average(a, weights=weights, axis=axis)
        average_af = np.array(af.mean(a_af, weights=weights_af, dim=axis))

        print ('numpy results:')
        print(average_np)
        print('arrayfire results')
        print(average_af)

        print(f'results match? {np.allclose(average_np, average_af)}')

    print()

if __name__ == '__main__':
    main()
----------------------------------------------

When using dim=0, ArrayFire produces the same results as NumPy. When using dim=1 the results differ. I have confirmed using the sumproduct function in LibreOffce Calc that NumPy's results are correct.

I am working on the following platform:
Windows 10
Python 3.7.3
ArrayFire 3.6.4
CUDA 9.2

Please let me know if I can provide further information to address this issue.

Thank you,

Michael

**Comment by umar456** [comment]
Hey Michael,

If you transpose the weights array for dim=1 you should get the same results. I think the difference here is due to how each of the libraries are applying the weights.

**Comment by michaelnowotny** [comment]
Yes, that was it. It is working now. Thanks for getting back to me so quickly Umar!
