### ISSUE TITLE
convolve3 Produces wrong numerical results when using AF_CONV_SPATIAL

### ISSUE THREAD

**Issue by NingyuanWang** [arrayfire/arrayfire#2601]
When using af::convolve3 with AF_CONV_SPATIAL, wrong numerical results are reproduced. A minimal example can be seen here using a [7 7 7 1] data with a [3 3 3 1] kernel: 

```
#include <arrayfire.h>
#include <af/cuda.h>
#include <iostream>

int main(int argc, char *argv[]) {
    const double laplace_stencil_h[] = { 1,3,1,3,14,3,1,3,1,3,14,3,14,-128,14,3,14,3,1,3,1,3,14,3,1,3,1 };//27 point stencil known as High-Order compact FD Schemes
                                                                                                          //Ref: https://www.researchgate.net/publication/2591103_High-Order_Compact_Finite_Difference_Schemes_for_Computational_Mechanics/link/00463524456e49822a000000/download page 110(125)
    const double spatial_gridsize = 0.01;
    const double timestep = 0.01;
    const double decay_coefficient = 1e-3;
    const double diffusion_coefficient = 1e-3;
    const af::array laplace_stencil = af::array(3, 3, 3, laplace_stencil_h) * (1 / (spatial_gridsize*spatial_gridsize * 30.0));
    //Initial guess, using explicit method:
    //Eqn to solve: 
    //D*: diffusion coeff. k: decay coeff.
    //(1 + \Delta T k / 2) I - \Delta T D*/2 \nabla^27) u^(n+1) = u^n + \Delta T D* \nabla^27 u^n / 2 - \Delta T k u^n / 2
    //Rewrite as Ax = b. 
    const double identity_stencil_h[] = { 0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0 };
    const af::array identity_stencil = af::array(3, 3, 3, identity_stencil_h);
    const af::array A = -0.5*diffusion_coefficient*timestep * laplace_stencil + (1 + 0.5 * timestep * decay_coefficient) * identity_stencil;
    af::print("A", A);
    const int test_shape_side_length = 7;
    af::array test_array_2 = af::constant(0.0, test_shape_side_length, test_shape_side_length, test_shape_side_length, f64);
    int entry_index = test_shape_side_length * test_shape_side_length * 4 + test_shape_side_length * 5 + 5;
    test_array_2(entry_index) = 1.0;
    test_array_2.eval();
    af::print("test_array_2", test_array_2);
    af::array concept_check_array = af::convolve3(test_array_2, A, af::convMode::AF_CONV_DEFAULT, af::convDomain::AF_CONV_SPATIAL);
    concept_check_array.eval();
    af::print("concept_check_array", concept_check_array);
    std::cout << "End\n";
}
```
At runtime, the text output is as follows: 

> A
[3 3 3 1]
   -0.0017    -0.0050    -0.0017 
   -0.0050    -0.0233    -0.0050 
   -0.0017    -0.0050    -0.0017 

   -0.0050    -0.0233    -0.0050 
   -0.0233     1.2133    -0.0233 
   -0.0050    -0.0233    -0.0050 

   -0.0017    -0.0050    -0.0017 
   -0.0050    -0.0233    -0.0050 
   -0.0017    -0.0050    -0.0017 

test_array_2
[7 7 7 1]
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 

    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 

    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 

    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 

    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     1.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 

    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 

    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 

concept_check_array
[7 7 7 1]
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 

    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 

    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 

    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000    -0.0017    -0.0050    -0.0017 
    0.0000     0.0000     0.0000     0.0000    -0.0050    -0.0233    -0.0050 
    0.0000     0.0000     0.0000     0.0000    -0.0017    -0.0050    -0.0017 

    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     1.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 

    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 

    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 

End

When using AF_CONV_FREQ, the expected numerical values are produced.

**Comment by 9prady9** [comment]
On which backend is this happening ?

I have tried your code on CUDA backend - I have a GTX 1060. I see identical values for `concept_check_array` whether I give AF_CONV_FREQ or AF_CONV_SPATIAL.

Please check the below files.

[out_freq.log](https://github.com/arrayfire/arrayfire/files/3431985/out_freq.log)
[out_spatial.log](https://github.com/arrayfire/arrayfire/files/3431986/out_spatial.log)

**Comment by 9prady9** [comment]
Can you also please update which version you are using.

**Comment by NingyuanWang** [comment]
> 
> 
> Can you also please update which version you are using.

This may be related to the backend I am using. I am using a GTX 970. I am using arrayfire version 3.6.4. The project is developed on Visual Studio 2017. The attachment is the project. 

[Minimal_arrayfire.zip](https://github.com/arrayfire/arrayfire/files/3432159/Minimal_arrayfire.zip)

**Comment by NingyuanWang** [comment]
Also, the CUDA version is 10.1

**Comment by 9prady9** [comment]
The attached zip file looks similar to the code snippet you shared earlier. I have already tried it, please check the results I shared earlier [out_freq.log and out_spatial.log](https://github.com/arrayfire/arrayfire/issues/2601#issuecomment-515065277), they look identical but different from what you posted in the [issue main description](https://github.com/arrayfire/arrayfire/issues/2601#issue-472887346). 

We already fixed this in b5286ef8257993c3edc91317b12d215213ec679a and hence, I wasn't able to reproduce it using master. The fix is already available in master and will be pushed out in next release.

**Comment by NingyuanWang** [comment]
Thanks for the information. I will try using the master instead of the prebuilt binary and see if the issue disappears.

**Comment by 9prady9** [comment]
Please close the issue once every thing checks out on your end. thank you.
