### ISSUE TITLE
Make shouldn't rebuild everything

### ISSUE THREAD

**Issue by r-barnes** [arrayfire/arrayfire#2605]
Doing:

    mkdir build
    cd build
    CXX=g++-6 CC=gcc-6 cmake -DCMAKE_BUILD_TYPE=Release ..
    make

works.

But if I type `make` again it rebuilds _everything_.

This is especially frustrating if I forget to type `make install` the first time.

Can we improve the build process?

**Comment by 9prady9** [comment]
That shouldn't have happened. I just did make on master branch after running a `make` already and it didn't rebuild.
I don't see why it would rebuild everything for you unless some file changed or compiler is changed in your second run.

**Comment by 9prady9** [comment]
What kind of setup are running are you trying to build on ? For which backend are facing this issue ?

**Comment by r-barnes** [comment]
I tried running again and was not able to reproduce the issue. I'll close for now.
