### ISSUE TITLE
Arrayfire from binaries (v3.6.4) built example produce Exception Internal Error:998, CUDA backend 

### ISSUE THREAD

**Issue by mickeyil** [arrayfire/arrayfire#2618]
Hi,

In the process of finding out why our code doesn't work on Ubuntu 18.04 (porting from 16.04), I did a fresh install of the os, installed Arrayfire 3.6.4 from the binary installer, and built the examples in the `share/ArrayFire/examples` folder.

inside the li_algebra, **all** 4 examples fail throwing exception on the cuda backend, but succeed on the cpu and opencl backends.

lu_cuda example. This example builds and runs well on a 16.04 machine with ArrayFire/CUDA, but fails on Ubuntu 18.04:
```
$ ./lu_cuda 
ArrayFire v3.6.4 (CUDA, 64-bit Linux, build 1b8030c)
Platform: CUDA Toolkit 10.0, Driver: 430.26
[0] GeForce RTX 2070 SUPER, 7980 MB, CUDA Compute 7.5
in
[5 8 1 1]
ArrayFire Exception (Internal error:998):
In function void print(const char*, af_array, int, std::ostream&, bool) [with T = float; af_array = void*; std::ostream = std::basic_ostream<char>]
In file src/api/c/print.cpp:87



In function void af::print(const char*, const af::array&)
In file src/api/cpp/util.cpp:19
terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Internal error:998):
In function void print(const char*, af_array, int, std::ostream&, bool) [with T = float; af_array = void*; std::ostream = std::basic_ostream<char>]
In file src/api/c/print.cpp:87



In function void af::print(const char*, const af::array&)
In file src/api/cpp/util.cpp:19
Aborted (core dumped)
```
Additional info on the system:
```
$ uname -a
Linux sbtest1 5.0.0-25-generic #26~18.04.1-Ubuntu SMP Thu Aug 1 13:51:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ g++ --version
g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
```

**Comment by 9prady9** [comment]
@mickeyil Does the same happen with a simple example also ? - something like stripped down `helloworld/helloworld.cpp` where only single array is printed ? If you haven't tried it, can you please try that.

Also, please try again with `export AF_PRINT_ERRORS=1`.

You can also run the code through gdb and we can see the exact line at which it is failing inside ArrayFire too.

**Comment by mickeyil** [comment]
Here is the output of helloworld_cuda:
```
examples/build/helloworld$ AF_PRINT_ERRORS=1 ./helloworld_cuda 
ArrayFire v3.6.4 (CUDA, 64-bit Linux, build 1b8030c)
Platform: CUDA Toolkit 10.0, Driver: 430.26
[0] GeForce RTX 2070 SUPER, 7980 MB, CUDA Compute 7.5
Create a 5-by-3 matrix of random floats on the GPU
A
[5 3 1 1]
In function cuda::Kernel cuda::buildKernel(int, const string&, const string&, const std::vector<std::basic_string<char> >&, bool)
In file src/backend/cuda/nvrtc/cache.cpp:160
NVRTC Error(7): NVRTC_ERROR unknown


In function void print(const char*, af_array, int, std::ostream&, bool) [with T = float; af_array = void*; std::ostream = std::basic_ostream<char>]
In file src/api/c/print.cpp:87



ArrayFire Exception (Internal error:998):
In function void print(const char*, af_array, int, std::ostream&, bool) [with T = float; af_array = void*; std::ostream = std::basic_ostream<char>]
In file src/api/c/print.cpp:87



In function void af::print(const char*, const af::array&)
In file src/api/cpp/util.cpp:19
terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Internal error:998):
In function void print(const char*, af_array, int, std::ostream&, bool) [with T = float; af_array = void*; std::ostream = std::basic_ostream<char>]
In file src/api/c/print.cpp:87



In function void af::print(const char*, const af::array&)
In file src/api/cpp/util.cpp:19
Aborted (core dumped)
```

**Comment by 9prady9** [comment]
Okay, one step closer, NVRTC compilation of kernel is failing on your card. 

I don't have a RTX super card, can you please clone arrayfire v3.6 branch directly and build the CUDA backend alone.

```bash
$ git clone -b v3.6 https://github.com/arrayfire/arrayfire.git
$ cd arrayfire
$ git submodule update --init --recursive
$ mkdir build && cd build
$ cmake .. -DAF_BUILD_CPU:BOOL=OFF -DAF_BUILD_OPENCL:BOOL=OFF -DBUILD_TESTING:BOOL=OFF
$ make -j4 helloworld_cuda
```
Please apply the following diff before building example.
```diff
diff --git a/src/backend/cuda/nvrtc/cache.cpp b/src/backend/cuda/nvrtc/cache.cpp
index 1226c85c..9a87c46c 100644
--- a/src/backend/cuda/nvrtc/cache.cpp
+++ b/src/backend/cuda/nvrtc/cache.cpp
@@ -75,6 +75,7 @@ using kc_t = map<string, Kernel>;
         char* logptr = log.get();                      \
         nvrtcGetProgramLog(prog, logptr);              \
         logptr[logSize] = '\x0';                       \
+        printf("log \n : %s\n", logptr);\
         AF_ERROR("NVRTC ERROR", AF_ERR_INTERNAL);      \
     } while (0)
 #else
```

When you run the example with this diff, we will know the nvrtc compilation error.

**Comment by mickeyil** [comment]
Building it with your instructions made it work (but produces a warning).

```
$ ./lu_cuda 
WARNING: CUDA driver version(10.2) not part of the CudaToDriverVersion array. Please create an issue or a pull request on the ArrayFire repository to update the CudaToDriverVersion variable with this version of the CUDA Toolkit.
ArrayFire v3.6.4 (CUDA, 64-bit Linux, build 1b8030c5)
Platform: CUDA Toolkit 10.0, Driver: 430.26
[0] GeForce RTX 2070 SUPER, 7980 MB, CUDA Compute 7.5
in
[5 8 1 1]
   Offset: 0
   Strides: [1 5 40 40]
    0.6010     0.5497     0.1583     0.3636     0.6755     0.8966     0.5143     0.0123 
    0.0278     0.2864     0.3712     0.4165     0.6105     0.0536     0.3670     0.3988 
    0.9806     0.3410     0.3543     0.5814     0.5232     0.5775     0.3336     0.9787 
    0.2126     0.7509     0.6450     0.8962     0.5567     0.2908     0.0363     0.2308 
    0.0655     0.4105     0.9675     0.3712     0.7896     0.9941     0.5349     0.6244 

...
```

**Comment by 9prady9** [comment]
Users can ignore that warning, did the linear algebra example also run ?

**Comment by mickeyil** [comment]
The rest of the examples are running. I used your patch to discover that the failure to run from the built binaries were related to a missing ldconfig/LD_LIBRARY_PATH:
```
log 
 : nvrtc: error: failed to open libnvrtc-builtins.so.
  Make sure that libnvrtc-builtins.so is installed correctly.
ArrayFire Exception (Internal error:998):
...
```
But, even with ldconfig correctly set for /opt/arrayfire and the linear algebra tests in a working state, the python tests failed (`python -m arrayfire.tests` latest stable installed by pip).
After removing the /opt/arrayfire in favor of a build using your instructions (and installing the required packages from the Wiki) I got to the desired state of the python tests passing.

**Comment by 9prady9** [comment]
Have you forgotten to setup ldconfig as we explained in [Linux](http://arrayfire.org/docs/installing.htm#Linux) after installation ? I think that is the reason, you faced the issue.

As far as the python goes, I think that depends on how environment is inherited by python setup. I am not super familiar with that aspect @umar456 / @pavanky any idea what would this happen in general ?

**Comment by mickeyil** [comment]
@9prady9 yes, that's why it didn't work in the beginning when I installed from the binary package.

**Comment by 9prady9** [comment]
@mickeyil What is the status of this issue ? Have you been able to successfully use arrayfire (arrayfire-python) from python ?

**Comment by mickeyil** [comment]
@9prady9, no open issue. I confirmed there was a missing  LD_LIBRARY_PATH in the environment. arrayfire-python works great!

**Comment by 9prady9** [comment]
Just wanted to confirm as I wasn't sure. Thanks, enjoy prototyping with arrayfire-python!
