### ISSUE TITLE
GeForce RTX 2080 Ti Returns Zeros

### ISSUE THREAD

**Issue by r-barnes** [arrayfire/arrayfire#2629]
I have a GeForce RTX 2080 Ti, 10990 MB, CUDA Compute 7.5 eGPU connected to my machine via a Razor Core X dock. The eGPU appears in `nvidia-smi` and [GPU Burn](https://github.com/wilicc/gpu-burn) says that things are working fine. However, when I run the [Arrayfire Pi benchmark](http://arrayfire.org/docs/benchmarks_2pi_8cpp-example.htm) and many other AF codes, I only get zeros back:
```
ArrayFire v3.7.0 (CUDA, 64-bit Linux, build 84dccd03)
Platform: CUDA Toolkit 10.1, Driver: 418.87.00
[0] GeForce RTX 2080 Ti, 10990 MB, CUDA Compute 7.5
-1- Quadro P2000 with Max-Q Design, 4032 MB, CUDA Compute 6.1
device:  0.00057 seconds to estimate  pi = 0.00000
  host:  0.52139 seconds to estimate  pi = 3.14126
```
The problem persists with CUDA Version: 10.2 + Driver Version: 430.26.

# What Works 
Further exploration shows AF as returning correct results for the following:

Printing a constant array:
```
//g++ -O3 constant.cpp -laf -lafcuda
#include <arrayfire.h>
using namespace af;

int main(int argc, char ** argv){
  setDevice(0);
  info();
  af_print(constant(10, 10, 10))

  setDevice(1);
  info();
  af_print(constant(10, 10, 10))

  return 0;
}
```

Simple Additions:
```
a = constant(10, 10, 10);
b = constant(10, 10, 10);
af_print(a + b);
```
More complex math:
```
auto a = constant(10, 10, 10);
a += conjg(pow(sqrt(sin(33.4*constant(cfloat(3,4), 10, 10)/43)),3.5));
af_print(a);
```
All of the following CUDA self-tests claim to pass and return results which seem visually correct.
```
./5_Simulations/particles/particles
./5_Simulations/fluidsGL/fluidsGL
./5_Simulations/oceanFFT/oceanFFT
./5_Simulations/nbody/nbody
./5_Simulations/smokeParticles/smokeParticles
./7_CUDALibraries/simpleCUFFT/simpleCUFFT
./7_CUDALibraries/conjugateGradientUM/conjugateGradientUM
./7_CUDALibraries/cuSolverSp_LinearSolver/cuSolverSp_LinearSolver
./7_CUDALibraries/simpleCUFFT_2d_MGPU/simpleCUFFT_2d_MGPU
./7_CUDALibraries/simpleCUFFT_callback/simpleCUFFT_callback
./7_CUDALibraries/simpleCUBLAS/simpleCUBLAS
./7_CUDALibraries/nvJPEG/nvJPEG
./3_Imaging/convolutionFFT2D/convolutionFFT2D
```
I notice that `./7_CUDALibraries/simpleCUFFT/simpleCUFFT` returns all zeros, but so does the CPU code. I also get all zeros for this test when using a GPU which doesn't exhibit the problem (a Quadro P2000).

# What Doesn't Work

The following return all zeros:

Printing an array of random numbers
```
//g++ -O3 constant.cpp -laf -lafcuda
#include <arrayfire.h>
using namespace af;

int main(int argc, char ** argv){
  setDevice(0);
  info();
  af_print(randu(10, 10));

  setDevice(1);
  info();
  af_print(randu(10, 10));

  return 0;
}
```
FFTs
```
//g++ -O3 constant.cpp -laf -lafcuda
#include <arrayfire.h>
using namespace af;

int main(int argc, char ** argv){
  setDevice(0);
  info();
  af_print(fft(constant(10, 10, 10)));

  setDevice(1);
  info();
  af_print(fft(constant(10, 10, 10)));

  return 0;
}
```
The [Arrayfire Pi benchmark](http://arrayfire.org/docs/benchmarks_2pi_8cpp-example.htm).

**Comment by christophe-murphy** [comment]
Closing for now. If you are still having trouble feel free to open a new issue.
