### ISSUE TITLE
ArrayFire on CUDA compute < 2.0

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#263]
Right now the solution is to use the OpenCL backend. 

However there may be un-forseen issues that occur on such hardware because the tests are not running on such hardware.

**Comment by maxruby** [comment]
@pavanky.  Happy new year.  Any chance of checking ArrayFire on CUDA compute < 2.0?

**Comment by pavanky** [comment]
@maxruby I'm still not back in the office. I can have something early next week
