### ISSUE TITLE
Boost v1.71.0 not recognized as greater than v1.70.0

### ISSUE THREAD

**Issue by kriswuollett** [arrayfire/arrayfire#2640]
Output from `cmake`:

```
WARN: Found Boost v1.71.  Required 1.70.0.  Build will download Boost
```

The error is due to int version missing trailing 00. Technically likely a problem with `cmake`, but the easy fix may to be to always use the string-style version compare. Issue #1994 was closed saying that this would be addressed in the v3.6 release.

A pull request will be inbound shortly.

**Comment by StefanBruens** [comment]
You can force the old behavior by setting Boost_NO_BOOST_CMAKE=ON and CMP0093=OLD
