### ISSUE TITLE
Crash in randomEngine

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#2645]
Hi
Here is a strange crash I see with AF 3.6.4 running on CentOS7: 

[unified][029035] [ ../src/api/unified/symbol_manager.cpp:137 ] Attempting: 
[unified][029035] [ ../src/api/unified/symbol_manager.cpp:139 ] Found: libafcpu.so.3
[unified][029035] [ ../src/api/unified/symbol_manager.cpp:146 ] Device Count: 1.
[unified][029035] [ ../src/api/unified/symbol_manager.cpp:137 ] Attempting: 
[unified][029035] [ ../src/api/unified/symbol_manager.cpp:139 ] Found: libafopencl.so.3
[unified][029035] [ ../src/api/unified/symbol_manager.cpp:146 ] Device Count: 4.
[unified][029035] [ ../src/api/unified/symbol_manager.cpp:137 ] Attempting: 
[unified][029035] [ ../src/api/unified/symbol_manager.cpp:139 ] Found: libafcuda.so.3
[platform][029035] [ ../src/backend/cuda/device_manager.cpp:301 ] CUDA supported by the GPU Driver 10.1 ArrayFire CUDA Runtime 10.0
[platform][029035] [ ../src/backend/cuda/device_manager.cpp:359 ] Found 4 CUDA devices
[platform][029035] [ ../src/backend/cuda/device_manager.cpp:383 ] Found device: Quadro RTX 6000 (23.7 GB | ~15556.6 GFLOPs | 72 SMs)
[platform][029035] [ ../src/backend/cuda/device_manager.cpp:383 ] Found device: Quadro RTX 6000 (23.7 GB | ~15556.6 GFLOPs | 72 SMs)
[platform][029035] [ ../src/backend/cuda/device_manager.cpp:383 ] Found device: Quadro RTX 6000 (23.7 GB | ~15556.6 GFLOPs | 72 SMs)
[platform][029035] [ ../src/backend/cuda/device_manager.cpp:383 ] Found device: Quadro RTX 6000 (23.6 GB | ~15556.6 GFLOPs | 72 SMs)
[platform][029035] [ ../src/backend/cuda/device_manager.cpp:404 ] AF_CUDA_DEFAULT_DEVICE: 
[platform][029035] [ ../src/backend/cuda/device_manager.cpp:421 ] Default device: 0
[unified][029035] [ ../src/api/unified/symbol_manager.cpp:146 ] Device Count: 4.
[unified][029035] [ ../src/api/unified/symbol_manager.cpp:194 ] AF_DEFAULT_BACKEND: cuda
[unified][029035] [ ../src/api/unified/symbol_manager.hpp:69 ] Loading: af_create_handle
[unified][029035] [ ../src/api/unified/symbol_manager.hpp:69 ] Loading: af_init
ArrayFire v3.6.4 (CUDA, 64-bit Linux, build 1b8030c)
Platform: CUDA Toolkit 10.0, Driver: 430.50
[0] Quadro RTX 6000, 24221 MB, CUDA Compute 7.5
-1- Quadro RTX 6000, 24221 MB, CUDA Compute 7.5
-2- Quadro RTX 6000, 24221 MB, CUDA Compute 7.5
-3- Quadro RTX 6000, 24218 MB, CUDA Compute 7.5
...
8
[unified][029035] [ ../src/api/unified/symbol_manager.hpp:69 ] Loading: af_randu
[unified][029035] [ ../src/api/unified/symbol_manager.hpp:69 ] Loading: af_get_default_random_engine
...
...
Segmentation fault (core dumped)

(gdb) bt
#0  0x00007fef5703fc50 in af::randomEngine::get() const () from /home/nbuild/pub/Release/lib/libaf.so.3
#1  0x00007fef5704021e in af::randu(af::dim4 const&, af_dtype, af::randomEngine&) () from /home/nbuild/pub/Release/lib/libaf.so.3

**Comment by WilliamTambellini** [comment]
Hum, looks like initializing a randomEngine
af::randomEngine(AF_RANDOM_ENGINE_DEFAULT, static_cast<unsigned long long>(seed))
is a must have ?
Would nt AF create a default random engine if none already created ?
W.

**Comment by 9prady9** [comment]
@WilliamTambellini I believe there are defaults in place usually. Can you please show me the line of code that caused the crash. The code should throw exception if random engine is not set instead of segfaulting.

**Comment by WilliamTambellini** [comment]
Oh no I m sure it was on my side, I was trying to ref a null ptr. All good.
