### ISSUE TITLE
Exclude GraphicsResourceManager if GL not found 

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#2647]
Hello
Here is a build issue if GL not found : 
....
-- Could NOT find OpenGL (missing: OPENGL_INCLUDE_DIR)
...
make
...
[ 25%] Building CXX object src/backend/cuda/CMakeFiles/afcuda.dir/device_manager.cpp.o
In file included from /home/wtambellini/repos/arrayfire/src/backend/cuda/GraphicsResourceManager.cpp:18:0:
/usr/local/cuda-10.0/include/cuda_gl_interop.h:66:19: fatal error: GL/gl.h: No such file or directory
 #include <GL/gl.h>
                   ^
compilation terminated.

Here is what I see in backend/cuda/GraphicsResourceManager.cpp : 

#include <common/graphics_common.hpp>
#define __gl_h_  // FIXME Hack to avoid gl.h inclusion by cuda_gl_interop.h
#include <GraphicsResourceManager.hpp>
#include <cuda_gl_interop.h>

and the start of cuda_gl_interop.h of cuda 10.0 : 

#if !defined(__CUDA_GL_INTEROP_H__)
#define __CUDA_GL_INTEROP_H__
#include "cuda_runtime_api.h"
#if defined(__APPLE__)
#include <OpenGL/gl.h>
#else /* __APPLE__ */
#if defined(__arm__) || defined(__aarch64__)
#ifndef GL_VERSION
#error Please include the appropriate gl headers before including cuda_gl_interop.h
#endif
#else
#include <GL/gl.h>
#endif

Would is be possible to simply exclude any AF Graphics things if GL not found ?
Kind
W.

**Comment by 9prady9** [comment]
@WilliamTambellini Please try these https://github.com/arrayfire/arrayfire/pull/2663 changes. I have tested on centos docker image with no gl headers and works as expected.
