### ISSUE TITLE
Half data type support for single dim mean

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#2652]
Hi
Looks like af::mean not yet supporting f16 : 

  std::vector<float> d = { 1, 2, 3,
        5, 6, 7,
        5, 6, 7,
        1, 2, 3 };
  r = af::mean(af::array(3, 2, 2, d.data()).as(f16), 0);

unknown location(0): fatal error: in "testAF": af::exception: ArrayFire Exception (Function does not support this data type:204):
In function af_err af_mean(void**, af_array, dim_t)
In file src/api/c/mean.cpp:72
Invalid type for argument 1
In function af::array af::mean(const af::array&, dim_t)
In file src/api/cpp/mean.cpp:21

I m going to try to fix it.

**Comment by WilliamTambellini** [comment]
Please limit the scope of that item to single dimension mean.

**Comment by WilliamTambellini** [comment]
https://github.com/arrayfire/arrayfire/pull/2653

**Comment by 9prady9** [comment]
The reason I expanded the scope to statistics is that mean, var, statistics - all of these are usually interlinked in some sort of way in the code. It is easier and better to group this change together instead of handling just mean function.

**Comment by WilliamTambellini** [comment]
Tks.
Though I m calling here for a divide and conquer approach here in order to keep the scope as minimalist as possible and merge it asap. I ve renamed the tille to "single dim mean" because that s all I need at the moment.
Could you please check the jenkins failures ?
Tks

**Comment by 9prady9** [comment]
@umar456 Is working on buildbot related things at the moment.

**Comment by umar456** [comment]
Fixed via #2653
