### ISSUE TITLE
building failure with clFFT-ext missing

### ISSUE THREAD

**Issue by csy19960309** [arrayfire/arrayfire#2655]
I was trying to build the arrayfire source code by strictly following the instructions offered in the wiki except that I used VS2019 Build Tools instead of VS2017. It has been said that clfft is automatically downloaded by Cmake.
    When the building was nearly finished, however, I saw 

> CUSTOMBUILD : CMake error : The following variables are used in this project, but they are set to NOTFOUND.[D:\Code\arrayfire\build\src\backend\opencl\clFFT-ext.vcxproj]

**Comment by 9prady9** [comment]
Can you please share the output of cmake command on your system.

Please also do share the contents of the `build/third_party` folder.

**Comment by csy19960309** [comment]
> Can you please share the output of cmake command on your system.
> 
> Please also do share the contents of the `build/third_party` folder.

@9prady9 .

The output is :

> -- The C compiler identification is MSVC 19.23.28105.4
-- The CXX compiler identification is MSVC 19.23.28105.4
-- Check for working C compiler: f:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: f:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: f:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: f:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - found
-- Found OpenCL: D:/Program Files (x86)/IntelSWTools/OpenCL/sdk/lib/x64/OpenCL.lib (found version "2.0")
-- Downloading https://github.com/KhronosGroup/OpenCL-CLHPP/releases/download/v2.0.10/cl2.hpp
-- Performing Test cplusplus_define
-- Performing Test cplusplus_define - Success
-- Performing Test cxx_compliance
-- Performing Test cxx_compliance - Success
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.0")
-- Found OpenCL: D:/Program Files (x86)/IntelSWTools/OpenCL/sdk/lib/x64/OpenCL.lib (found suitable version "2.0", minimum required is "1.2")
-- Found OpenGL: opengl32
-- Found FreeImage: D:/Code/vcpkg/installed/x64-windows/include
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - no
-- Found Threads: TRUE
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Found FFTW: D:/Code/vcpkg/installed/x64-windows/include
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Checking for [Accelerate]
-- Checking for [vecLib]
-- Checking for [cblas - atlas]
-- Includes found
-- Checking for [openblas]
-- Includes found
-- Looking for cblas_dgemm
-- Looking for cblas_dgemm - found
-- CBLAS Symbols FOUND
-- CBLAS library found
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Could NOT find LAPACK (missing: LAPACK_INCLUDE_DIR)
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Check size of int
-- Check size of int - done
-- Could NOT find MKL (missing: MKL_INCLUDE_DIR MKL_Core_LINK_LIBRARY)
-- Found Boost: D:/Code/vcpkg/installed/x64-windows/include (found version "1.71.0")
CMake Warning (dev) at D:/Program Files/CMake/share/cmake-3.15/Modules/CMakeDependentOption.cmake:38 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.
  For compatibility with older versions of CMake, option is clearing the
  normal variable 'SPDLOG_BUILD_TESTING'.
Call Stack (most recent call first):
  extern/spdlog/CMakeLists.txt:28 (cmake_dependent_option)
This warning is for project developers.  Use -Wno-dev to suppress it.
-- Found OpenCL: D:/Program Files (x86)/IntelSWTools/OpenCL/sdk/lib/x64/OpenCL.lib (found version "2.0")
-- [download 100% complete]
Downloaded Trec4 file from sparse.tamu.edu
Extracted mtx files to test data directory
-- [download 100% complete]
Downloaded bcsstm02 file from sparse.tamu.edu
Extracted mtx files to test data directory
-- [download 0% complete]
-- [download 100% complete]
Downloaded young4c file from sparse.tamu.edu
Extracted mtx files to test data directory
-- [download 100% complete]
Downloaded lpi_vol1 file from sparse.tamu.edu
Extracted mtx files to test data directory
-- [download 0% complete]
-- [download 84% complete]
-- [download 100% complete]
Downloaded lpi_qual file from sparse.tamu.edu
Extracted mtx files to test data directory
-- [download 0% complete]
-- [download 100% complete]
Downloaded oscil_dcop_12 file from sparse.tamu.edu
Extracted mtx files to test data directory
-- [download 56% complete]
-- [download 100% complete]
Downloaded oscil_dcop_42 file from sparse.tamu.edu
Extracted mtx files to test data directory
-- [download 0% complete]
-- [download 1% complete]
-- [download 3% complete]
-- [download 4% complete]
-- [download 5% complete]
-- [download 6% complete]
-- [download 7% complete]
-- [download 8% complete]
-- [download 9% complete]
-- [download 10% complete]
-- [download 11% complete]
-- [download 12% complete]
-- [download 13% complete]
-- [download 14% complete]
-- [download 15% complete]
-- [download 16% complete]
-- [download 17% complete]
-- [download 18% complete]
-- [download 19% complete]
-- [download 20% complete]
-- [download 21% complete]
-- [download 22% complete]
-- [download 23% complete]
-- [download 25% complete]
-- [download 26% complete]
-- [download 27% complete]
-- [download 28% complete]
-- [download 29% complete]
-- [download 30% complete]
-- [download 31% complete]
CMake Warning at test/CMakeModules/download_sparse_datasets.cmake:44 (message):
  Failed to download conf6_0-4x4-20 file from sparse.tamu.edu
Call Stack (most recent call first):
  test/CMakeModules/download_sparse_datasets.cmake:76 (download_mtx)
  test/CMakeLists.txt:14 (include)
CMake Warning at test/CMakeModules/download_sparse_datasets.cmake:45 (message):
  Failure message: "Timeout was reached"
Call Stack (most recent call first):
  test/CMakeModules/download_sparse_datasets.cmake:76 (download_mtx)
  test/CMakeLists.txt:14 (include)
-- Found PythonInterp: D:/Program Files/Python/Python37/python.exe (found version "3.7.4")
-- Configuring done
-- Generating done
-- Build files have been written to: D:/Code/arrayfire/build

As for the folder contents, there are only two directories named CLBlast and clFFT.

Thanks for caring.

**Comment by 9prady9** [comment]
The cmake output looks fine and if you have clFFT folder, that would mean clFFT has been fetched correctly.

Please try removing the clFFT folder under third_party folder and re-run cmake and build command

**Comment by 9prady9** [comment]
@csy19960309 Can you please update on the issue status.

**Comment by csy19960309** [comment]
> @csy19960309 Can you please update on the issue status.

@9prady9. Sorry for forgetting this. I tried what  you had suggested, but failed in the same old way. I found directory clFFT/include empty after the cmake work is done. 
Do I have to close this issue now? I am new to Github and have no idea about the procedures.

**Comment by 9prady9** [comment]
I am not sure how to reproduce the issue on my end - clFFT clones and gets
built fine for me. Is it possible for you to create a docker file that can
help us reproduce it on our end?

Thank you.

**Comment by csy19960309** [comment]
@9prady9 Sorry for being too busy to make a prompt reply. I am a freshman to the docker and afraid that it is a little hard for me to make a Windows container as required. Now I decide to build the source code on WSL instead. As for the building failure on Windows, I suppose that the cause is the cmake argument  _-G "Visual Studio 16 2019" -A x64_. 
Anyway, thanks for the help.
Should I close the issue?

**Comment by 9prady9** [comment]
Can you please try the following diff and let me know how that works out.

```diff
diff --git a/CMakeModules/build_CLBlast.cmake b/CMakeModules/build_CLBlast.cmake
index be2cfce7..7117cd57 100644
--- a/CMakeModules/build_CLBlast.cmake
+++ b/CMakeModules/build_CLBlast.cmake
@@ -46,7 +46,9 @@ ExternalProject_Add(
     UPDATE_COMMAND ""
     PATCH_COMMAND ${CLBLAST_PATCH_COMMAND}
     BUILD_BYPRODUCTS ${CLBlast_location}
-    CONFIGURE_COMMAND ${CMAKE_COMMAND} "-G${CMAKE_GENERATOR}" -Wno-dev <SOURCE_DIR>/
+    CONFIGURE_COMMAND ${CMAKE_COMMAND} "-G${CMAKE_GENERATOR}"
+      "-A${CMAKE_GENERATOR_PLATFORM}"
+      -Wno-dev <SOURCE_DIR>
       -DCMAKE_CXX_COMPILER:FILEPATH=${CMAKE_CXX_COMPILER}
       "-DCMAKE_CXX_FLAGS:STRING=${CMAKE_CXX_FLAGS} -w -fPIC"
       -DOVERRIDE_MSVC_FLAGS_TO_MT:BOOL=OFF
diff --git a/CMakeModules/build_clBLAS.cmake b/CMakeModules/build_clBLAS.cmake
index 8de529e8..3660aa4c 100644
--- a/CMakeModules/build_clBLAS.cmake
+++ b/CMakeModules/build_clBLAS.cmake
@@ -21,7 +21,9 @@ ExternalProject_Add(
     INSTALL_DIR "${prefix}"
     UPDATE_COMMAND ""
     DOWNLOAD_NO_PROGRESS 1
-    CONFIGURE_COMMAND ${CMAKE_COMMAND} "-G${CMAKE_GENERATOR}" -Wno-dev <SOURCE_DIR>/src
+    CONFIGURE_COMMAND ${CMAKE_COMMAND} "-G${CMAKE_GENERATOR}"
+      "-A${CMAKE_GENERATOR_PLATFORM}"
+      -Wno-dev <SOURCE_DIR>/src
       -DCMAKE_CXX_FLAGS:STRING="-fPIC"
       -DCMAKE_C_FLAGS:STRING="-fPIC"
       -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
diff --git a/CMakeModules/build_clFFT.cmake b/CMakeModules/build_clFFT.cmake
index 28be38a3..1f9be0fd 100644
--- a/CMakeModules/build_clFFT.cmake
+++ b/CMakeModules/build_clFFT.cmake
@@ -25,7 +25,9 @@ ExternalProject_Add(
     PREFIX "${prefix}"
     INSTALL_DIR "${prefix}"
     UPDATE_COMMAND ""
-    CONFIGURE_COMMAND ${CMAKE_COMMAND} "-G${CMAKE_GENERATOR}" -Wno-dev <SOURCE_DIR>/src
+    CONFIGURE_COMMAND ${CMAKE_COMMAND} "-G${CMAKE_GENERATOR}"
+      "-A${CMAKE_GENERATOR_PLATFORM}"
+      -Wno-dev <SOURCE_DIR>/src
       -DCMAKE_CXX_COMPILER:FILEPATH=${CMAKE_CXX_COMPILER}
       "-DCMAKE_CXX_FLAGS:STRING=${CMAKE_CXX_FLAGS} -w -fPIC"
       -DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}
```
