### ISSUE TITLE
Inconsistent output for af::matmul(matrix,vector)

### ISSUE THREAD

**Issue by cschreib-ibex** [arrayfire/arrayfire#2659]
Using ArrayFire 3.6.4 binaries for Windows 64bit, downloaded from the ArrayFire website.

We are experiencing small inconsitencies in the calculations done in our project, which I managed to trace back to one function and these lines:
```c++
af::array r1 = af::matmul(m1,v1);     // m1:[10609x10], v1:[10,1]
af::array r2 = af::matmul(m2.T(),v2); // m2:[46,10609], v2:[46,1]
af::array r3 = r1 + r2;
```

This is executed using the CPU backend, and all arrays are 32bit floats.

Depending on what was executed before this function is called, and even though the inputs ```m1,v1,m2,v2``` are exactly the same (checked by saving them to disk using ```saveArray()```), the arrays ```r1,r2,r3``` are slightly different. The relative difference is of order ```1e-5```, so not huge, but definitely noticeable. And it is perfectly replicable too, although these lines are buried deep inside our code base and there's a lot of other calculations going on, so isolating the issue is not easy.

Strangely enough, most of the elements in the arrays are exactly the same; it's just a handful of them which are different, and at the same location in both ```r1```, ```r2```, and ```r3```: elements 1764, 1765, 1767, 1769, 10596, 10600, 10601, 10602, 10603. I don't see a logic to this sequence.

I thought this might be because the JIT queue was different, hence execution is taking a different path and things get computed slightly differently. I don't know how linear algebra is implemented in AF, maybe that's not possible, but I did try calling ```eval()``` on all the input arrays then  ```af::sync()``` prior to the call to ```af::matmul```, but the problem didn't go away.

I managed to get ```r2``` to give consistent results by replacing ```matmul(m2.T(),v2)``` with ```matmulTN(m2,v2)```, but then ```r1``` was still inconsistent. In fact I tried removing ```r2``` altogether and ```r1``` was still giving inconsistent results... On the other hand, if I remove ```r1```, then ```r2``` gives consistent results regardless of whether I use ```matmul``` or ```matmulTN```. So it seems like the problem can be traced down to the first ```af::matmul()```.

I then attempted to investigate this by running the debugger and step inside ArrayFire's code. To do so, I rebuilt ArrayFire 3.6.4 from source using the ```RelWithDebInfo``` build configuration. I didn't change anything specific to the build, and I used LAPACKE and OpenBLAS for the linear algebra libraries. Unfortunately, I could not go further since I could not reproduce the problem with this build...

I'm happy to keep looking into this and figure out whether this is a problem in ArrayFire our in our code which accidentally corrupts the ArrayFire state somehow, but to do this I need either one of the following:
 - the exact build configuration and dependencies that were used to produce the ArrayFire released binaries, 
 - the *.pdb files matching the released binaries (that would be ideal really)

**Comment by cschreib-ibex** [comment]
Thank you very much for the pointer, this may very well be the issue. I'll look into it.

**Comment by cschreib-ibex** [comment]
Confirmed. Perhaps it is worth exposing a function in the AF API to control this, so that the end user (like myself) doesn't have to deal with MKL directly?

**Comment by umar456** [comment]
I am not sure if this is the ideal approach. Because MKL is not the only blas library we use, this function will not be portable. You will need to be aware of which blas library you are linking against to be effective and it may not work with other libraries and therefore give users incorrect expectations. It would be better to just directly call the MKL functions.
