### ISSUE TITLE
cmake not searching/checking the cudnn header file

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#2660]
Looks like the afcuda cmake is not searching/checking that the required cudnn.h file is available: 

cmake
success
make afcuda
...
In file included from /local1/wtambellini/arrayfire/src/backend/cuda/convolve.cpp:15:0:
/local1/wtambellini/arrayfire/src/backend/cuda/cudnn.hpp:13:19: fatal error: cudnn.h: No such file or directory
 #include <cudnn.h>

Expected behavior : cmake to at least fail if cudnn.h not findable in usual suspect dirs (/usr/local/cuda/include, ...)

Ref:
https://github.com/soumith/cudnn.torch/blob/master/cmake/FindCUDNN.cmake

**Comment by 9prady9** [comment]
Can you please test the changes from https://github.com/arrayfire/arrayfire/pull/2661

I have tried on Ubuntu 18.04 where cudnn was installed via deb file. Both of these (ubuntu 18.04 or Arch Linux) setups have `cudnn.h` under `/usr/include` directly or via update-alternatives configuration. How did you install cudnn on your development setup ?
