### ISSUE TITLE
neg is listed as logical operator in the documentation

### ISSUE THREAD

**Issue by noughtmare** [arrayfire/arrayfire#2664]
I think it should be listed in the numeric functions category.

**Comment by 9prady9** [comment]
@noughtmare Are you referring to `array array::operator!() const` method ? Can you please point us tthe documentation URL. Thank you.

**Comment by noughtmare** [comment]
I mean this one: http://arrayfire.org/docs/group__arith__func__neg.htm

**Comment by noughtmare** [comment]
It is listed in the logic category here: http://arrayfire.org/docs/group__logic__mat.htm

**Comment by 9prady9** [comment]
That is not a logical operation. `-` operation returns negated values of whatever values are present in the input array i.e. positive values become negative values and vice versa.

**Comment by noughtmare** [comment]
Yeah, that is what I mean, it is wrongly listed in the logic category here: http://arrayfire.org/docs/group__logic__mat.htm.

**Comment by 9prady9** [comment]
Ah right, our bad. Thank you!
