### ISSUE TITLE
static linking mkl

### ISSUE THREAD

**Issue by flori-uni** [arrayfire/arrayfire#2671]
I try to create an application using arrayfire for a heterogeneous system. Probably I'll use the CPU as well as the GPU. So far the first results are amazing! 

I'm only struggling in finding a suitable solution how to distribute the whole application? Must arrayfire also be installed on the target machine? Currently, I get some errors concerning MKL....

**Comment by rstub** [comment]
Maybe related: #2372

**Comment by 9prady9** [comment]
@rstub I think @umar456 already addressed that by linking MKL libs directly with unified lib - see this file  https://github.com/arrayfire/arrayfire/blob/master/src/api/unified/CMakeLists.txt#L80-L92 This fix was introduced in 3.6.0 release. @flori-uni which version of ArrayFire are you using ?

Also, you titled the issue as static linking mkl ? We don't do static linking at the moment, you can do one of the two things for deployment of your app
1) Copy the dependencies to the target system and set required paths
2) Install the `.sh` file we provided on our website on target system

**Comment by rstub** [comment]
@9prady9 #2372 was reported against 3.6.2 and is still present in 3.6.4.
