### ISSUE TITLE
AF unified master up to 30% slower than 3.6.4

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#2673]
Hello,
I have to call that as today with 
c30d5455f3d60582cb81968551b69fadcfc7c880
AF master is up to 30% slower than 3.6.4 in some cases.
For some (non-batched) NN inference : 
3.6.4  2.81 secs
3.7.0  3.99 secs

One of the root causes is definitely the new event creation introduced in
https://github.com/arrayfire/arrayfire/pull/2526
The fix in 
https://github.com/arrayfire/arrayfire/pull/2574
just reduced the speed drop but did nt totally fix it.
Commenting out 
 auto err = cuEventCreate(e, CU_EVENT_DISABLE_TIMING); 
in 
https://github.com/arrayfire/arrayfire/blob/c30d5455f3d60582cb81968551b69fadcfc7c880/src/backend/cuda/Event.hpp#L26
reduced further the speed drop : 
3.7.0 (no cuda event) : 3.467 secs
but still not as fast as 3.6.4.

TBContinued
W.

**Comment by WilliamTambellini** [comment]
Reproduced with the simple NN example:

$ machine_learning/neural_network_cuda 
ArrayFire v3.6.4 (CUDA, 64-bit Linux, build 1b8030c)
Platform: CUDA Toolkit 10.0, Driver: 418.56
[0] GeForce GTX 1060, 6079 MB, CUDA Compute 6.1
** ArrayFire ANN Demo **
...
Training time: 5.2342 s


$ examples/machine_learning/neural_network_cuda 
ArrayFire v3.7.0 (CUDA, 64-bit Linux, build c30d545)
Platform: CUDA Toolkit 10.0, Driver: 418.56
[0] GeForce GTX 1060, 6079 MB, CUDA Compute 6.1
** ArrayFire ANN Demo **
...
Training time: 6.4344 s

Do you have any logs from your CI/jenkins servers of the time needed to run that example commit after commits since 3.6.4 ?

Kind
W.

**Comment by WilliamTambellini** [comment]
Note: the speed was better (still slower than 3.6.4) just before the "event" change ("Enforce dependencies between allocs and frees using events"): e62570abcbdd7f3fca1552368665be0cbd4fe4a0
$ examples/machine_learning/neural_network_cuda 
ArrayFire v3.7.0 (CUDA, 64-bit Linux, build e62570a)
Platform: CUDA Toolkit 10.0, Driver: 418.56
[0] GeForce GTX 1060, 6079 MB, CUDA Compute 6.1
** ArrayFire ANN Demo **
...
Training time: 5.4631 s

**Comment by umar456** [comment]
I was able to reproduce it on my system and I am looking into it. I need to run a couple of tests to see what is the source of the slowdown. I noticed during our discussions on Skype that the runtimes of the kernels were slower in the new versions.

**Comment by WilliamTambellini** [comment]
Cool. I m using nvrtc 10.0.130: 
$ ll /usr/local/cuda-10.0/lib64/libnvrtc*
lrwxrwxrwx 1 root root       25 Jun 19 17:25 /usr/local/cuda-10.0/lib64/libnvrtc-builtins.so -> libnvrtc-builtins.so.10.0*
lrwxrwxrwx 1 root root       29 Jun 19 17:25 /usr/local/cuda-10.0/lib64/libnvrtc-builtins.so.10.0 -> libnvrtc-builtins.so.10.0.130*
-rwxr-xr-x 1 root root  4612768 Jun 19 17:25 /usr/local/cuda-10.0/lib64/libnvrtc-builtins.so.10.0.130*
lrwxrwxrwx 1 root root       16 Jun 19 17:25 /usr/local/cuda-10.0/lib64/libnvrtc.so -> libnvrtc.so.10.0*
lrwxrwxrwx 1 root root       20 Jun 19 17:25 /usr/local/cuda-10.0/lib64/libnvrtc.so.10.0 -> libnvrtc.so.10.0.130*
-rwxr-xr-x 1 root root 20332456 Jun 19 17:25 /usr/local/cuda-10.0/lib64/libnvrtc.so.10.0.130*

**Comment by WilliamTambellini** [comment]
Let's prune : 
b1f3955c09eabb861fabb1489f2bf16ad24e3e02
sounds good :   
$ examples/machine_learning/neural_network_cuda 
ArrayFire v3.7.0 (CUDA, 64-bit Linux, build b1f3955)
Platform: CUDA Toolkit 10.0, Driver: 418.56
[0] GeForce GTX 1060, 6079 MB, CUDA Compute 6.1
** ArrayFire ANN Demo **
...
Training time: 5.2371

**Comment by WilliamTambellini** [comment]
I see a 1st speed drop coming from 6d6053c84c1cca5ca31322a8df6e117dd9d0d550 
 
$ examples/machine_learning/neural_network_cuda 
ArrayFire v3.7.0 (CUDA, 64-bit Linux, build 6d6053c)
Platform: CUDA Toolkit 10.0, Driver: 418.56
[0] GeForce GTX 1060, 6079 MB, CUDA Compute 6.1
** ArrayFire ANN Demo **
....
Training time: 5.3258 s

@9prady9  were/are you aware about that ?

**Comment by umar456** [comment]
I don't see how that would cause a slowdown. Its just adding a -DOS_LNX flag to the nvcc compilation command.

**Comment by WilliamTambellini** [comment]
Hi @umar456 

$ examples/machine_learning/neural_network_cuda 
ArrayFire v3.7.0 (CUDA, 64-bit Linux, build ee68916)
Platform: CUDA Toolkit 10.0, Driver: 418.56
[0] GeForce GTX 1060, 6079 MB, CUDA Compute 6.1
** ArrayFire ANN Demo **
...
Training time: 5.6016 s

which is much better than 6.4s from the master branch.
Good for me,
Tks.
W.

**Comment by WilliamTambellini** [comment]
Seems to be an afunified speed drop : the speed of master is ok when linking with afcuda:
afcuda 364			28.511 secs
afcuda master (Dec6):	29.289 secs

**Comment by WilliamTambellini** [comment]
I m "rewinding" the master branch from 3.6.4 : 

d1180ec76696152d292df427b81fcb76b4dfae0e 24.3 s Fix array_proxy move constructor.
...
f50155d36e1dce384506927451bc2f25f6ca41ab 24.5 s	Create a make_handle factory for unique_handle
...
c69ec15483cc85f9c7d42dfbabea35c2c8c308b9 24.1 s	Create a unique_handle class to manage C library handles
...
e4e14eb392aae09aa981060fcfab8aa232c219d8 24.6 s Refactor MatrixAlgebraHandle to HandleBase and make it generic
...
f4f92de19029079bddfdfb4f85cb8edcaa99cb94 24.2 s Check the JIT tree size when creating binary and unary nodes (master)
ea56e37eabbcb60beb6e35e40e6756bdad5fe26d 24.0 s Check the JIT tree size when creating binary and unary nodes (the last commit of 3.6.4)

At the moment everything is alright. To be continued.

**Comment by WilliamTambellini** [comment]
Seems to be fixed by
https://github.com/arrayfire/arrayfire/pull/2695
at least on Pascal GPUs.
To be triple confirmed on recent GPUs, testing, please hold few hours before closing that one.
