### ISSUE TITLE
How to copy a sequence of elements from one array to sequence in another array?

### ISSUE THREAD

**Issue by krish021195** [arrayfire/arrayfire#2674]
Hi,

Trying to copy a sequence of elements from one array to a sequence in another array. How to do this in a minimum span of time?

Example code snipet:
      ` array ar_A = constant(0,10,10,u8);
	array ar_B = constant(5,10,10,u8);

	ar_A(seq(0,ar_A.dims(0)-1,2),span) = ar_B(seq(0,ar_B.dims(0)-1,2),span);
     `

Thanks

**Comment by 9prady9** [comment]
@krish021195 Did you time the above code snippet ? It shouldn't take too much of time ? If you did time the code, how did you time the code, please share the timing code snippet also .

**Comment by krish021195** [comment]
@9prady9 The above code snippet does not actually does the work expected. Still the values in array ar_A is same as before. No copy from array ar_B is performed. 
I need to copy the sequence from array ar_B to a sequence in array ar_A with minimum time. How do I do this?

**Comment by 9prady9** [comment]
What is the error message ? The sequence length seems to be same since `A.dims(0)` and `B.dims(0)` are same, and the step size is also same.

Note: You can try running setting the environment variable `AF_PRINT_ERRORS` to `1` to give more detailed error message.

**Comment by krish021195** [comment]
@9prady9 I do not get any error messages when running the above code. But still the value in array ar_A is 0.

**Comment by 9prady9** [comment]
@krish021195 I was able to reproduce this on v3.6.4 tag, however this seems to have been fixed in our development branch(master) already. Kindly wait for the next release where this will be addressed.

**Comment by krish021195** [comment]
@9prady9 Thanks for the update. For the current situation I have tried a work around but it seems to take more time. For testing I have increased the size of the array.

When running the below code It is taking around **~1ms** for just adding a scalar and an array. 

`array ar_A = constant(0,1920,1080,3,u8);
	array ar_B = constant(5,1920,1080,3,u8);
	int i=0;
	while(i<40)
	{
	 af::sync();
	 start1 = timer::start();
	 ar_A(seq(0,ar_A.dims(0)-1,2),span) = ar_B(seq(0,ar_B.dims(0)-1,2),span) + 0;
	 af::sync();
	 printf("processing time : %g\n",timer::stop(start1));
	}`

Let me know your comments on the work around.

**Comment by 9prady9** [comment]
Is it working if you do `af::sync()` after the assign call ? If so, can you try `ar_A.eval()` instead of `af::sync()` and let me know what happens.

In the code I tried, I just did a `af_print(ar_A)` which does an implicit `af::sync()` which didn't print the expected output on v3.6.4 tag.

**Comment by krish021195** [comment]
@9prady9 I have performed a copy by adding the array ar_B with 0 and assigning the result to array ar_A.
It is working because of the addition operation performed. I have used af::sync() for timing the code.

**Comment by 9prady9** [comment]
You can keep that work around if it is working. I doubt it is going to add a significant runtime to the copy operation by itself. The entire line will be converted into a single kernel(generated at runtime - JIT). Adding a scalar to the input array element before assigning to output element shouldn't increase assignment cost by too much.

Also, please use `timeit` functionality described in our tutorial http://arrayfire.org/docs/timing.htm for timing a code snippet based on arrayfire code. A single start/end based timing isn't the correct approach because that will include the kernel generation time on the first run which is of zero cost in subsequent runs in the code as they are internally cached after being generated in the first run.

**Comment by 9prady9** [comment]
Adding a scalar shouldn't take too long that is what I am saying.

The snippet you shared below took me around half millisecond on GTX 1060. Whats the GPU you are running this code on ?

> @9prady9 Thanks for the update. For the current situation I have tried a work around but it seems to take more time. For testing I have increased the size of the array.
> 
> When running the below code It is taking around **~1ms** for just adding a scalar and an array.
> 
> ```
> array ar_A = constant(0,1920,1080,3,u8);
> 	array ar_B = constant(5,1920,1080,3,u8);
> 	int i=0;
> 	while(i<40)
> 	{
> 	 af::sync();
> 	 start1 = timer::start();
> 	 ar_A(seq(0,ar_A.dims(0)-1,2),span) = ar_B(seq(0,ar_B.dims(0)-1,2),span) + 0;
> 	 af::sync();
> 	 printf("processing time : %g\n",timer::stop(start1));
> 	}
> ```
> 
> Let me know your comments on the work around.

**Comment by krish021195** [comment]
@9prady9 I am using Nvidia Jetson Xavier. Yes I am using cuda as my backend. 
I see that when using operator() the time increases. I checked by running code  
1 : `ar_A = ar_B + 0`
2 : `ar_A(seq(0,ar_A.dims(0)-1,2),span) = ar_B(seq(0,ar_B.dims(0)-1,2),span) + 0`

I expect the second code should take less time than the first since only half the original size of the array is involved in the operation.

But the first code seems to take very less time than the second one.

Is this what supposed to happen?

**Comment by 9prady9** [comment]
Speedups on GPU doesn't exactly always translate like that.

In your second case, we are accessing every alternate element which means
the access to global memory are not coalesced. For example of float arrays.
Thread 0 fetches first float and thread 1 fetches 3rd element and so on.
Even GPUs fetch data from memory by word sizes , each word can be 32 bytes,
64 bytes or 128 bytes. Whichever is the word size, each global read has to
read only 4 bytes for each float however memory fetch happens for atleast
32 bytes which is roughly 1/8 under-utilization of  memory bandwidth - to
put in different words, we are reading atleast 32 bytes to get the one
float(4 bytes) required by each thread. On top of that, cache hits/misses
also have an effect. Hence, the counter intuitive runtime numbers.

**Comment by krish021195** [comment]
Thanks on the response. It was really helpful.
