### ISSUE TITLE
Next release ?

### ISSUE THREAD

**Issue by vineelpratap** [arrayfire/arrayfire#2675]
Hi,
 We would like to make use of fp16 support in arrayfire for our project. I understand it works with master but we would be more comfortable using a release branch for the project. Could you cut a release with all the new improvements ? 

Thanks~

**Comment by WilliamTambellini** [comment]
I m calling for a release too but will need that to be fixed/, or at least a workaround first : 
https://github.com/arrayfire/arrayfire/issues/2673

**Comment by WilliamTambellini** [comment]
@umar456  3.7.0 released so that one could be closed. 
@vineelpratap  have you tried 3.7.0 ?
