### ISSUE TITLE
scanByKey / constructor / assignment operator bug

### ISSUE THREAD

**Issue by ipostr08** [arrayfire/arrayfire#2680]
Ran with the latest AF release in VS 2019. I haven't checked the Master. Two GPU setup: Titan V and 2080Ti (both show the same bug). cuda-memcheck does not report any errors.

```
#include <iostream>
#include <vector>
#include <arrayfire.h>

int main()
{
	af::setDevice(0);
	const int SIZE = 41'000;
	std::vector<int> keys(SIZE, 0);
	std::vector<float> vals(SIZE, 1.0f);
	auto valsAF = af::array(SIZE, f32);
	valsAF = af::array(SIZE, vals.data());
	auto keysAF = af::array(SIZE, s32);
	keysAF = af::array(SIZE, keys.data());
	std::cout << valsAF(0).scalar<float>() << std::endl;
	auto result = af::scanByKey(keysAF, valsAF, 0, AF_BINARY_ADD, true);
	std::cout << valsAF(0).scalar<float>() << std::endl;
	return 0;
}

```

Expected result:
1
1

Actual result:
1
34561

Note the double assignment of keysAF and valsAF.

**Comment by 9prady9** [comment]
Thank you for reporting it. This seems to be a problem only in CUDA backend. I am looking into it.

**Comment by 9prady9** [comment]
Also, the code you posted can be further shortened as follows
```c++
std::vector<int> keys(SIZE, 0);
std::vector<float> vals(SIZE, 1.0f);

//entire vector based array can be replaced using af::constant also
auto	valsAF = af::array(SIZE, vals.data());
auto	keysAF = af::array(SIZE, keys.data()); 

std::cout << valsAF(0).scalar<float>() << std::endl;
auto result = af::scanByKey(keysAF, valsAF, 0, AF_BINARY_ADD, true);
std::cout << valsAF(0).scalar<float>() << std::endl;
```

**Comment by 9prady9** [comment]
Something weird is going on, I was able to reproduce the problem couple of times in the initial runs but I am unable to reproduce it anymore.

@umar456 @mark-poscablo @syurkevi Can you please try master branch with above code snippet on your NVIDIA cards and let us know what the result looks like.

**Comment by ipostr08** [comment]
Thank you for looking into this. Even a small change in the code changes this behavior. Here is another example but it's much more complex and I couldn't reduce it further.

```

#include <arrayfire.h>
#include <vector>
#include <cstdio>


class Data
{
public:
	af::array cond;
	af::array sum;
	af::array net;
	af::array r1;

public:
	void init(int cv)
	{
		std::vector<char> c1(cv, 0);
		cond = af::array(c1.size(), c1.data());
		std::vector<float> c2(cv, 0);
		net = af::array(c2.size(), c2.data());
		std::vector<float> c3(cv, 0);
		sum = af::array(c3.size(), c3.data());
		std::vector<unsigned int> c4(cv, 0);
		r1 = af::array(c4.size(), c4.data());
	}
};

class Bug
{
public:
	Data afg;
	const int SIZE = 41'000;

public:
	void calc()
	{
		auto keys = af::array(SIZE, u32);
		for (int q = 0; q < SIZE; q++)
			keys(q) = 0;

		auto keys2 = af::array(SIZE, s32);
		for (int q = 0; q < SIZE; q++)
			keys2(q) = 0;

		auto keys3 = af::array(2, s32);
		for (int q = 0; q < 2; q++)
			keys3(q) = 0;

		auto xscores = af::array(SIZE, f32);
		for (int q = 0; q < SIZE; q++)
			xscores(q) = 0.2f;

		for (int q = 0; q < SIZE; q++)
			afg.cond(q) = 0;


		afg.r1 = af::accum(afg.cond);


		xscores = af::scanByKey(afg.r1, xscores, 0, AF_BINARY_MAX, true);

		afg.sum = af::accum(afg.net);

		auto a1 = af::lookup(afg.sum, keys3);
		std::printf("%f\n", xscores(0).scalar<float>());
		auto a2 = af::scanByKey(keys2, xscores, 0, AF_BINARY_ADD, true);
		std::printf("%f\n", xscores(0).scalar<float>());
	}


	void set()
	{
		af::setDevice(0);
		afg.init(SIZE);
	}

};



int main()
{
	Bug bt;
	bt.set();
	bt.calc();
	return 0;
}


```

**Comment by 9prady9** [comment]
I was able to reproduce it again after reverting the change I made to the code you posted originally. Do you face the issue even after the change I suggested above ?

Also, the way you are filling the array's in [this](https://github.com/arrayfire/arrayfire/issues/2680#issuecomment-560517096) code snippet is very inefficient - accessing elements of `af::array` individually one at a time.

`Data::init()` method looks okay, however it has an unnecessary overhead of using vector which you can avoid by doing the following.
```c++
void init(size_t cv) {
    const af::dim4 dims(cv);
    cond = af::constant(0, dims, b8);
    net = af::constant(0, dims, f32);
    sum = af::constant(0, dims, f32);
    r1 = af::constant(0, dims, u32);
}
```

 `Bug::calc` can be trimmed down by a lot by doing the following
```c++
void Bug::calc() {
auto keys = af::constant(0, SIZE, u32);
auto keys2 = af::constant(0, SIZE, s32);
auto keys3 = af::constant(0, 2, s32);
auto xscores = af::constant(0.2, SIZE, f32);
afg.cond = af::constant(0, SIZE, b8);

afg.r1 = af::accum(afg.cond);

xscores = af::scanByKey(afg.r1, xscores, 0, AF_BINARY_MAX, true);

afg.sum = af::accum(afg.net);

auto a1 = af::lookup(afg.sum, keys3);

std::printf("%f\n", xscores(0).scalar<float>());

auto a2 = af::scanByKey(keys2, xscores, 0, AF_BINARY_ADD, true);

std::printf("%f\n", xscores(0).scalar<float>());
}
```

It seems like you can learn few tricks about vectorization from our tutorial. here's the link
http://arrayfire.org/docs/vectorization.htm

**Comment by ipostr08** [comment]
After the change, it works fine. But I cannot just do this in my production code - I had other scans break.

No worries about performance, this is not my production code. It's just a way to demo the bug without accidentally fixing it. I've actually done quite a bit in order to get the best possible performance, including rewriting some code in CUDA. I think the AF is actually leaving quite a lot of performance on the table: smaller (<10 million element) arrays have almost the same processing time as much larger arrays. The first iteration time seems too long. And adding a support for multiple streams might help. But I must say that scan and reduction operations are impressively fast - I haven't found a way to beat them.

**Comment by ipostr08** [comment]
If case this helps, scoresAF array also gets modified even if its copy is passed as an argument to scanByKey:

```
#include <iostream>
#include <vector>
#include <arrayfire.h>

int main()
{
	af::setDevice(0);
	const int SIZE = 41'000;
	std::vector<int> keys(SIZE, 0);
	std::vector<float> vals(SIZE, 1.0f);
	auto valsAF = af::array(SIZE, f32);
	valsAF = af::array(SIZE, vals.data());
	auto keysAF = af::array(SIZE, s32);
	keysAF = af::array(SIZE, keys.data());
	std::cout << valsAF(0).scalar<float>() << std::endl;
	auto keysAFCopy = keysAF;	
	auto result = af::scanByKey(keysAFCopy, valsAF, 0, AF_BINARY_ADD, true);
	std::cout << valsAF(0).scalar<float>() << std::endl;
	return 0;
}

```

**Comment by ipostr08** [comment]
This could be useful: 
```
R:\afBug\x64\Release>cuda-memcheck --tool initcheck afbug
========= CUDA-MEMCHECK
1
34561
========= Uninitialized __global__ memory read of size 1
=========     at 0x000008f0 in void cuda::scanbykey_first_final<float, char, float, af_op_t=0>(cuda::Param<float>, cuda::CParam<float>, cuda::Param<float, char>, unsigned int, unsigned int, unsigned int, bool, bool)
=========     by thread (223,0,0) in block (0,0,0)
=========     Address 0x8400ea14df
=========     Device Frame:void cuda::scanbykey_first_final<float, char, float, af_op_t=0>(cuda::Param<float>, cuda::CParam<float>, cuda::Param<float, char>, unsigned int, unsigned int, unsigned int, bool, bool) (void cuda::scanbykey_first_final<float, char, float, af_op_t=0>(cuda::Param<float>, cuda::CParam<float>, cuda::Param<float, char>, unsigned int, unsigned int, unsigned int, bool, bool) : 0x8f0)
=========     Saved host backtrace up to driver entry point
=========     Host Frame:C:\WINDOWS\SYSTEM32\nvcuda.dll (cuLaunchKernel + 0x218) [0x1c9c38]
=========     Host Frame:d:\ArrayFire\v3\lib\afcuda.dll (af::operator& + 0x1b90414) [0x1bd7fc2]
=========     Host Frame:d:\ArrayFire\v3\lib\afcuda.dll (af::operator& + 0x1c1183f) [0x1c593ed]
=========     Host Frame:d:\ArrayFire\v3\lib\afcuda.dll (af::operator& + 0x1c2e049) [0x1c75bf7]
=========     Host Frame:d:\ArrayFire\v3\lib\afcuda.dll (af::operator& + 0x16d25c4) [0x171a172]
=========     Host Frame:d:\ArrayFire\v3\lib\afcuda.dll (af::operator& + 0x1969f54) [0x19b1b02]
=========     Host Frame:d:\ArrayFire\v3\lib\afcuda.dll (af::operator& + 0x196f11e) [0x19b6ccc]
=========     Host Frame:d:\ArrayFire\v3\lib\afcuda.dll (af::operator& + 0x1971401) [0x19b8faf]
=========     Host Frame:d:\ArrayFire\v3\lib\afcuda.dll (af::operator& + 0x1b23674) [0x1b6b222]
=========     Host Frame:R:\afBug\x64\Release\afbug.exe (main + 0x1b5) [0x1335]
=========     Host Frame:R:\afBug\x64\Release\afbug.exe (__scrt_common_main_seh + 0x10c) [0x1ff4]
=========     Host Frame:C:\WINDOWS\System32\KERNEL32.DLL (BaseThreadInitThunk + 0x14) [0x14034]
=========     Host Frame:C:\WINDOWS\SYSTEM32\ntdll.dll (RtlUserThreadStart + 0x21) [0x73691]

```

**Comment by 9prady9** [comment]
> After the change, it works fine [EDIT - see below, the simplification doesn't fix uninitialized memory reads].
> 
> Thanks for the advice but no worries about performance, this is not my production code. It's just a way to demo the bug without accidentally fixing it. I've actually done quite a bit in order to get the best possible performance, including rewriting some code in CUDA. I think the AF is actually leaving quite a lot of performance on the table: smaller (<10 million element) arrays have almost the same processing time as much larger arrays. The first iteration time seems too long. And adding a support for multiple streams might help. But I must say that scan and reduction operations are impressively fast - I haven't found a way to beat them.

The first iteration high runtime is expected as that includes device warmup(app startup) and kernel compilations(new type of kernel instantiation happens). I am not sure entirely if streams will help for the case you mentioned. Can you please share some benchmarks you did regarding the less performance for elements lesser than certain threshold. It would help us understand what functions/features are giving lesser performance that way.

Coming to the workaround, doing the following
```c++
std::vector<int> keys(SIZE, 0);
auto keysAF = af::array(SIZE, keys.data());
```
instead of the following
```c++
std::vector<int> keys(SIZE, 0);
auto keysAF = af::array(SIZE, s32);
keysAF = af::array(SIZE, keys.data());
```
is not exactly an accidental fix. Both versions are equivalent expect that the second one has some extra book-keeping involved which can be avoided.

Having said that, I do see the issue here where second version isn't working as it should be. We will look into it as soon as we can.

**Comment by ipostr08** [comment]
Note that cuda-memcheck and my complex example show that the first version does not actually fix the bug. Cuda-memcheck still shows reads from uninitialized memory and my code shows an incorrect result from scanByKey.

I will start a new ticket with the benchmarks as not to clutter this thread. It's not a hard threshold where the performance falls off. 

I think the slow first iteration is a result of more than the device warmup or creating the kernel. It seems like it's several magnitudes slower than it should be. I can create a new ticket with some benchmarks also.

**Comment by ipostr08x** [comment]
I see that a pull request has been made, awesome! I'm wondering how to get this fix working in my program though. Will I need to wait for a new release? If so, any estimate when it might happen? I think it's a pretty substantial bug, so maybe an update to the latest release could be made available? Or might there be a binary Windows version of the Master made available? Or maybe a working x64 VS solution? I've run into several issues when attempting to build (some because of dependencies) and I haven't quite gotten over them.

**Comment by 9prady9** [comment]
We understand the bug fix is an important one. We have been rejuvenating our CI framework since a few weeks which is partially the reason for delay in our next 3.7 release. If you like to raise an expedited request for early binary release for specific OS, you may try our support(https://arrayfire.com/support/) channel. Having said that, We will try to get 3.7 release out there as soon as we can and it is our top priority at the moment.
