### ISSUE TITLE
af::nearestNeighbour() returns incorrect results

### ISSUE THREAD

**Issue by keichi** [arrayfire/arrayfire#2687]
af::nearestNeighbour returns incorrect results with the OpenCL backend. Here are the output of ctest: [CPU (passing)](https://gist.github.com/keichi/37d0746ecd16ed6ccf74e8847f585c7b) and [OpenCL (failing)](https://gist.github.com/keichi/def6faae719ceac2a013eb251a15d019)

- ArrayFire: master(6f5812f1)
- OS: macOS Catalina 10.15.1 (19B88)
- CMake: 3.15.5
- Compiler: Apple clang version 11.0.0 (clang-1100.0.33.12)

Thanks!

**Comment by 9prady9** [comment]
The log shows `Intel(R) Iris(TM) Plus Graphics 655` as the OpenCL device. Did you install Intel's OpenCL runtime or Are you using Apple's OpenCL implementation ? 

If you have installed Intel's OpenCL implementation, can you please make sure the program is picking up that during execution. 

If program is however using Apple's OpenCL implementation, then I am not sure it is worth the effort to put in more development hours to debug the problem as Apple deprecated OpenCL on their platform. Even before deprecation of OpenCL, we have noticed a few issues while using OpenCL implementation of Apple.

I personally would probably try to get Intel OpenCL drivers installed and work around the Apple's stuff.

@umar456 On our team uses MacOS, may be he has other suggestions or pointers.

**Comment by keichi** [comment]
No, I didn't install Intel's OpenCL runtime so I guess I'm using Apple's runtime. I couldn't find Intel's OpenCL runtime on their website. Could you provide a URL?

If Intel isn't providing an OpenCL runtime, I'm okay with the CPU backend since I use Linux servers for large production runs. I was using the OpenCL backend on my macOS just because it has priority over the CPU backend and used by default.

**Comment by 9prady9** [comment]
That's the link

https://software.intel.com/en-us/opencl-sdk/choose-download

Interestingly i didnt see MacOS download option. So, i don't think we can
do anything over there.

You can use CPU backend for your testing by setting the backend as following

af::setBackend(AF_BACKEND_CPU); as the first ArrayFire API call.

**Comment by keichi** [comment]
Thanks, should I close this issue?

**Comment by 9prady9** [comment]
Sure if that was the only problem you faced.

**Comment by umar456** [comment]
@keichi is using the Apple platform. Intel doesn't provide an OpenCL runtime on macOS.

I have an older Iris Pro on an older version of macOS and I didn't run into this issue. I am not sure if I can reproduce this error on my end. I am unsure how I can debug this issue without that version of the hardware.
