### ISSUE TITLE
f16 array scalar multiplication

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#2700]
As today f16array * myfloat outputs a f32 array : 

af::array f16array(1,1, f16);
float scal = 2.0f;
af::array o = scal * f16array;

see o is f32.
Is there a way today to do f16 scalar mult in native half (perhaps using af_half) ?

**Comment by umar456** [comment]
Even though it's not how the types are calculated in standard C++ I can see why we need to return an f16 array in this case. I will try to get a fix for this next week.

**Comment by WilliamTambellini** [comment]
This one is done if I remember right, is nt it @umar456  ?

**Comment by umar456** [comment]
Yes fixed via #2723
