### ISSUE TITLE
test dot_cuda failing on half

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#2706]
Just an error with dot_cuda on half when run through a GTX1080Ti with cuda10.0 : 
$ test/print_info 
ArrayFire v3.7.0 (CUDA, 64-bit Linux, build 70ef1989)
Platform: CUDA Toolkit 10.0, Driver: 440.33.01
[0] GeForce GTX 1080 Ti, 11179 MB, CUDA Compute 6.1

/local/nbuild/jenkins/workspace/AF-Release-Linux/test/dot.cpp:94: Failure
The difference between abs(goldData[elIter]) and abs(outData[elIter]) is 16, which exceeds 0.03, where
abs(goldData[elIter]) evaluates to 25904,
abs(outData[elIter]) evaluates to 25920, and
0.03 evaluates to 0.029999999999999999.
at: 0
/local/nbuild/jenkins/workspace/AF-Release-Linux/test/dot.cpp:106: Failure
The difference between gold and rval is 16, which exceeds 0.03, where
gold evaluates to 25904,
rval evaluates to 25920, and
0.03 evaluates to 0.029999999999999999.
[  FAILED  ] DotF/0.DotF_10, where TypeParam = half_float::half (1 ms)

Perhaps just an approximation error.

**Comment by 9prady9** [comment]
I was able to reproduce this with CUDA 10.2 with 440.44 driver too.

**Comment by WilliamTambellini** [comment]
so the compare in dot.cpp is not flexible enough to support approximation of half:  
template<typename T>
void compare(double rval, double /*ival*/, T gold) {
    ASSERT_NEAR(gold, rval, 0.03);
}
The best would be to specialize the compare for half and use: 
https://en.cppreference.com/w/cpp/numeric/math/nextafter

TBC

**Comment by 9prady9** [comment]
This could be likely an issue related to driver/toolkit or GPU or combination of both. Although the unit test in discussion did fail on GTX 1060 with CUDA 10.2, the same unit test didn't fail on GT 650M with CUDA 9.1

**Comment by umar456** [comment]
This should be a pretty easy fix. Like you suggested. the nextafter and nextbefore functions could alleviate this issue for f16.

This is the line that needs to be fixed: https://github.com/arrayfire/arrayfire/blob/master/test/dot.cpp#L94

**Comment by WilliamTambellini** [comment]
@umar456  ok, I m on it

**Comment by WilliamTambellini** [comment]
hum, actually fixed by:
https://github.com/arrayfire/arrayfire/pull/2775
which was nt only for opencl but also cuda.
Closing.
