### ISSUE TITLE
af::convolve returns erroneous zero values if third-dimension of input array > 4 (only on CUDA)

### ISSUE THREAD

**Issue by pthon** [arrayfire/arrayfire#2709]
I found a strange error affecting the af::convolve function which only occurs using the CUDA backend.

Considering the following snipped, the af::convolve function should return an array with ones, but returns zeros for the fifth element onward:

    #include <arrayfire.h>
    
    int main(void){
        af::setBackend(AF_BACKEND_CUDA);
        af::info();
    
        const int n2 = 8; // error occurs for n2 > 4.
        af::array a = af::constant(1., 1, 1, n2, 1, f64);
    
        af::array filtr = af::constant(0., 3, 3, 3, f64);
        filtr(1, 1, 1) = 1;
    
        af::array a_conv = af::convolve(a, filtr, AF_CONV_DEFAULT, AF_CONV_SPATIAL);
        // Result is zero for the fifth element onward, but should be ones throughout.
        af::print("a_conv", a_conv);
        return 0;
    }

This produces the following output:

> ArrayFire v3.6.4 (CUDA, 64-bit Linux, build 1b8030c5)
Platform: CUDA Toolkit 9.2, Driver: 418.56
[0] Tesla V100-PCIE-16GB, 16131 MB, CUDA Compute 7.0
-1- Tesla V100-PCIE-16GB, 16131 MB, CUDA Compute 7.0
-2- Tesla V100-PCIE-16GB, 16131 MB, CUDA Compute 7.0
-3- Tesla V100-PCIE-16GB, 16131 MB, CUDA Compute 7.0
a_conv
[1 1 8 1]
    1.0000 
    1.0000 
    1.0000 
    1.0000 
    0.0000 
    0.0000 
    0.0000 
    0.0000 

The correct result should only contain ones, however.

The OpenCL and CPU backends yield the correct result. I tested for arrayfire 3.6.4, 3.6.2 and 3.6.1 on linux.

**Comment by 9prady9** [comment]
@pthon What is the rank of convolution, 1D/2D/3D ?

**Comment by 9prady9** [comment]
Current master doesn't have this issue. Most likely, it has been fixed after 3.6.4 release. Let me get back to you with the change that fixes the issue - would help for future reference.

**Comment by pthon** [comment]
In the application we calculate a 3D laplace operation. Here, I adapted the snippet to a minimum working example.

**Comment by 9prady9** [comment]
b5286ef8257993c3edc91317b12d215213ec679a
I believe that fixed this issue.

**Comment by pthon** [comment]
> [b5286ef](https://github.com/arrayfire/arrayfire/commit/b5286ef8257993c3edc91317b12d215213ec679a)
> I believe that fixed this issue.

Perfect, thanks a lot!
