### ISSUE TITLE
speed drop for gemm at f16

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#2721]
Hi
The current master seems to run f16 gemm very slowly :   

$ examples/benchmarks/blas_cuda 0 f16
Device 0 isHalfAvailable ? yes
ArrayFire v3.7.0 (CUDA, 64-bit Linux, build e557d7e)
Platform: CUDA Toolkit 10.0, Driver: 440.33.01
[0] TITAN V, 12067 MB, CUDA Compute 7.0
Benchmark N-by-N matrix multiply at f16 
 128 x  128:   209 Gflops
 256 x  256:  1877 Gflops
 384 x  384:  5125 Gflops
 512 x  512:  8695 Gflops
 640 x  640:  13921 Gflops
 768 x  768:  19676 Gflops
 896 x  896:  24233 Gflops
1024 x 1024:  34177 Gflops
1152 x 1152:  28971 Gflops
1280 x 1280:  36888 Gflops
1408 x 1408:  38955 Gflops
1536 x 1536:  46535 Gflops
1664 x 1664:  30498 Gflops
1792 x 1792:  33420 Gflops
1920 x 1920:  50641 Gflops
2048 x 2048:  53265 Gflops
 ### peak 53264.5 GFLOPS

Few months ago, AF was able to run f16 gemm at the expected peak perf : 
ArrayFire v3.7.0 (CUDA, 64-bit Linux, build 492faf999)
Platform: CUDA Toolkit 10, Driver: 415.18
[0] Quadro GV100, 32471 MB, CUDA Compute 7.0
Benchmark N-by-N fp16 matrix multiply with TensorCore
128 x 128: 97 Gflops
256 x 256: 779 Gflops
384 x 384: 2616 Gflops
512 x 512: 5252 Gflops
640 x 640: 10109 Gflops
768 x 768: 21419 Gflops
896 x 896: 32597 Gflops
1024 x 1024: 39544 Gflops
1152 x 1152: 44033 Gflops
1280 x 1280: 54392 Gflops
1408 x 1408: 58630 Gflops
1536 x 1536: 65728 Gflops
1664 x 1664: 50407 Gflops
1792 x 1792: 50917 Gflops
1920 x 1920: 70645 Gflops
2048 x 2048: 81526 Gflops > about 8x speed up compared to f32 as expected

**Comment by WilliamTambellini** [comment]
hum seems related to version of cuda (10.0 vs 10.1+, cublaLt or not) and/or version of the drivers. TBC.

**Comment by umar456** [comment]
I tested this on a GV100 and the times were pretty good. I noticed you are comparing two different GPUs there. I would suggest running the benchmark on the same card even if the underlying architecture is the same.

**Comment by WilliamTambellini** [comment]
According to the doc the TitanV and GV100 should run f16 at about the same speed if I remember right.
Anyway, the speed seems to be simply sensitive to the cuda and driver versions. Tks.
