### ISSUE TITLE
arrayfire uses CPU on Jetson Nano

### ISSUE THREAD

**Issue by elsucht** [arrayfire/arrayfire#2722]
I successfully compiled arrayfire from git src without CPU- and OpenCL-backend. Only CUDA backend was activated. 
However I am struggling using the library. It looks like that my executables (and some of the examples) are using the CPU and not the CUDA gpu. My small test program (simple additions) is resulting in 100% CPU core usage, but 0% GPU usage.
` af::setBackend(AF_BACKEND_CUDA);
int width = 4000;
int height = 3000;
af::array af_result = af::array (width, height,af::dtype::f32 );
af::array af_img1 = af::array (width, height,af::dtype::f32 );
for(int i=0;i<100;++i){
        af_result += af_img1;
        af_result.eval(); }
af::sync();`
My system is a Jetson Nano (Jetpack 4.2.2 CUDA 10.0.326).
What am I missing?

> ArrayFire v3.7.0 (CUDA, 64-bit Linux, build e557d7ec)
Platform: CUDA Toolkit 10.0, Driver: 10000
[0] NVIDIA Tegra X1, 3964 MB, CUDA Compute 5.3

**Comment by umar456** [comment]
I think this is happening because not  alot of work is being performed on the GPU. Try calling matmul instead of addition. Also these types of questions are better suited for our slack or the google groups. You can find how to join at the bottom of the main README

**Comment by elsucht** [comment]
You are correct.
