### ISSUE TITLE
variance bias parameter

### ISSUE THREAD

**Issue by kriswuollett** [arrayfire/arrayfire#2731]
Does [`af::var(array, bool, dim_t)`](https://github.com/arrayfire/arrayfire/blob/af665bc30b36502e0b164a59a124f43a21100daf/include/af/statistics.h#L57) need to change to `af::var(array, af_var_bias, dim_t)` like as in [`af::meanvar`](https://github.com/arrayfire/arrayfire/blob/af665bc30b36502e0b164a59a124f43a21100daf/include/af/statistics.h#L86)? I am working on learning ML and was trying to debug why downstream a library unit test was broken after I synced to the latest (after a few months of not touching anything) -- it implements its own variance method and used `af::var` as a comparison. Looks like I was caught by the changes in #2710?

Would have hoped downstream wouldn't compile if there was a change in behavior, or there was just a function override for the new interface.

**Comment by kriswuollett** [comment]
BTW, it seems like the documentation in [`statistics.h`](https://github.com/arrayfire/arrayfire/blob/af665bc30b36502e0b164a59a124f43a21100daf/include/af/statistics.h#L49) is now out of date? The var and af_var method docs both say:

> \param[in] isbiased is boolean denoting Population variance (false) or Sample Variance (true)

While the [code](https://github.com/arrayfire/arrayfire/blob/af665bc30b36502e0b164a59a124f43a21100daf/src/api/c/var.cpp#L179) that does the conversion from the `bool` to `af_var_bias` says:

```c++
        af_var_bias bias =
            (isbiased) ? AF_VARIANCE_POPULATION : AF_VARIANCE_SAMPLE;
```

**Comment by umar456** [comment]
Hey @kriswuollett,

I think you are looking at an older commit. This should have been fixed in #2710.

```cpp
        af_var_bias bias =
            (isbiased) ? AF_VARIANCE_SAMPLE: AF_VARIANCE_POPULATION;
```

 Can you make sure that biased variance(sample) gives the correct results?

**Comment by kriswuollett** [comment]
@umar456, thanks for checking for me!

Looking again, the ArrayFire docs/code seem ok. The tests for var (cpu, cuda, and opencl) pass for me at https://github.com/arrayfire/arrayfire/commit/8f767a026290ae2fbde975757b64032e9832c43c. Sorry... looks like I may have browsed to the wrong version of code again on github after clicking on a specific commit!

I just need to figure out what I need to do with the downstream library. I'll close this issue now, since I don't see any issue here currently. I just usually have a bias against `bool` parameters. :-)

**Comment by umar456** [comment]
Yeah, we are trying to move away from boolian parameters as well. Thats why I added that enum. I should port that over to the var function as well.

**Comment by WeiLi233** [comment]
Hi @umar456 I think https://github.com/arrayfire/arrayfire/blob/bc37e8a9942b9af7507c87926b25e21298760aeb/src/api/c/var.cpp#L182 is not correct, as I know, setting biased to true means population variance and to false means sample variance, this result is opposite to the var() function in flashlight, and   will cause a test failure in AutogradTest of flashlight.

**Comment by jacobkahn** [comment]
@WeiLi233 — we don't directly use `af::var` in flashlight, but we're changing the behavior of that test so things work. Thanks for flagging.
