### ISSUE TITLE
OpenCL Pinverse/3 (af_cdouble) Large tests fail

### ISSUE THREAD

**Issue by kriswuollett** [arrayfire/arrayfire#2740]
Priority not that high for me since I don't plan on using OpenCL at the moment -- just thought I'd try building all.

Build info:

* Ubuntu 18.04.4 LTS (newly installed)
* CMake 3.16.3 installed in `/usr/local`
* Installed all recommended / OpenBLAS packages in the [Linux install wiki (current revision)](https://github.com/arrayfire/arrayfire/wiki/Build-Instructions-for-Linux/cda4af51217c6e560653589e3d42d29f62f707b1)
* ArrayFire `2a2d6ff52c7f66dec24caa15a0ee5e9ef1cef1f2` (2020-02-04)
* GPU: RTX 5000, cuda-drivers 440.33.01-1 package, CUDA 10.1 via `cuda_10.1.243_418.87.00_linux.run` (toolkit & samples only), `cudnn-10.1-linux-x64-v7.6.5.32.tgz`, `nccl_2.5.6-1+cuda10.1_x86_64.txz`, `TensorRT-6.0.1.5.Ubuntu-18.04.x86_64-gnu.cuda-10.1.cudnn7.6.tar.gz`.
* CMake command:

```shellscript
cmake -S [...]/src -B [...]/build \
        -DCUDA_TOOLKIT_ROOT_DIR=[...] \
        -DCMAKE_PREFIX_PATH="[...]" \
        -DCMAKE_INSTALL_PREFIX="[...]" \
        -DCMAKE_BUILD_TYPE=Release \
        -DAF_BUILD_CPU=ON \
        -DAF_BUILD_CUDA=ON \
        -DAF_BUILD_OPENCL=ON \
        -DAF_BUILD_FORGE=ON \
        -DAF_BUILD_EXAMPLES=ON \
        -DBUILD_TESTING=ON
```

make test output (the only 2 tests that fail):

```
[ RUN      ] Pinverse/3.Large
/tmp/arrayfire_wBDdK5/src/test/pinverse.cpp:161: Failure
VALUE DIFFERS at (0, 1):
Viewing slice (0:5, 1), dims are (640 480 1 1) strides: (1 640 307200 307200)
                       [0]                 1                 2                 3                 4                 5
out: { [(561.941 960.709)] (755.826 604.878) (943.971 262.068) (703.521 256.705) (830.814 12.1375) (450.494 242.139) }
 in: { [(561.941 960.709)] (755.826 604.878) (943.971 262.068) (703.521 256.705) (830.814 12.1375) (450.494 242.139) }
  Actual diff: 1.4629477426233423e-10
Expected diff: 1.4201166631533368e-10
[  FAILED  ] Pinverse/3.Large, where TypeParam = af::af_cdouble (2599 ms)
[ RUN      ] Pinverse/3.LargeTall
/tmp/arrayfire_wBDdK5/src/test/pinverse.cpp:170: Failure
VALUE DIFFERS at (1, 0):
Viewing slice (0:6, 0), dims are (480 640 1 1) strides: (1 480 307200 307200)
                       0                 [1]                2                 3                 4                 5                 6
out: { (891.248 251.783) [(561.941 960.709)] (492.04 847.835) (688.282 762.804) (915.541 153.299) (789.852 197.421) (268.919 594.701) }
 in: { (891.248 251.783) [(561.941 960.709)] (492.04 847.835) (688.282 762.804) (915.541 153.299) (789.852 197.421) (268.919 594.701) }
  Actual diff: 1.4410944625832187e-10
Expected diff: 1.4201166631533368e-10
[  FAILED  ] Pinverse/3.LargeTall, where TypeParam = af::af_cdouble (2613 ms)
```

**Comment by umar456** [comment]
That's strange. The relative difference is pretty small. The tests should be failing only if the difference is less than 1.e-5 for cdoubles. The values look ok here. @mark-poscablo can you look at what's going on here?

**Comment by kriswuollett** [comment]
Forgot to mention above I am also using Boost 1.72.0 built from source with:

```
./bootstrap.sh
./b2 install --prefix=/usr/local/boost-1.72.0--threading=single,multi \
    --without-graph_parallel --without-mpi --variant=release
```

**Comment by mark-poscablo** [comment]
Looks like this specific test case doesn't use the fixed value of 1e-5 as the accepted error - it calculates it instead based on the dtype and input arrays:

https://github.com/arrayfire/arrayfire/blob/2a2d6ff52c7f66dec24caa15a0ee5e9ef1cef1f2/test/pinverse.cpp#L110-L115

The calculated accepted error looks like it's too strict for this test case. We can modify the test case to use the fixed accepted error instead of the calculated one if it's unnecessarily small.
