### ISSUE TITLE
undefined reference to `pthread_create'

### ISSUE THREAD

**Issue by kapilg1997** [arrayfire/arrayfire#2778]
I am trying to build arrayfire on ubuntu 18.04
cmake version = 3.6.0
I followed build procedure given [here](https://github.com/arrayfire/arrayfire/wiki/Build-Instructions-for-Linux) : 

I have tried the procedure with CPU, CUDA and penCL backend but error is the same.

But while using cmake in build i am getting following errors

Determining if the pthread_create exist failed with the following output:
Change Dir: /home/admin1/asr/wav2/dependencies/arrayfire/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_4fdda/fast"
/usr/bin/make -f CMakeFiles/cmTC_4fdda.dir/build.make CMakeFiles/cmTC_4fdda.dir/build
make[1]: Entering directory '/home/admin1/asr/wav2/dependencies/arrayfire/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_4fdda.dir/CheckSymbolExists.c.o
/usr/bin/cc   -fPIC    -o CMakeFiles/cmTC_4fdda.dir/CheckSymbolExists.c.o   -c /home/admin1/asr/wav2/dependencies/arrayfire/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_4fdda
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_4fdda.dir/link.txt --verbose=1
/usr/bin/cc -fPIC     CMakeFiles/cmTC_4fdda.dir/CheckSymbolExists.c.o  -o cmTC_4fdda 
CMakeFiles/cmTC_4fdda.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x1b): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_4fdda.dir/build.make:97: recipe for target 'cmTC_4fdda' failed
make[1]: *** [cmTC_4fdda] Error 1
make[1]: Leaving directory '/home/admin1/asr/wav2/dependencies/arrayfire/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_4fdda/fast' failed
make: *** [cmTC_4fdda/fast] Error 2

File /home/admin1/asr/wav2/dependencies/arrayfire/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/admin1/asr/wav2/dependencies/arrayfire/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_ebbbf/fast"
/usr/bin/make -f CMakeFiles/cmTC_ebbbf.dir/build.make CMakeFiles/cmTC_ebbbf.dir/build
make[1]: Entering directory '/home/admin1/asr/wav2/dependencies/arrayfire/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_ebbbf.dir/CheckFunctionExists.c.o
/usr/bin/cc   -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_ebbbf.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.10/Modules/CheckFunctionExists.c
Linking C executable cmTC_ebbbf
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_ebbbf.dir/link.txt --verbose=1
/usr/bin/cc -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_ebbbf.dir/CheckFunctionExists.c.o  -o cmTC_ebbbf -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_ebbbf.dir/build.make:97: recipe for target 'cmTC_ebbbf' failed
make[1]: *** [cmTC_ebbbf] Error 1
make[1]: Leaving directory '/home/admin1/asr/wav2/dependencies/arrayfire/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_ebbbf/fast' failed
make: *** [cmTC_ebbbf/fast] Error 2

My CMakeError.log file is as follows

Determining if the pthread_create exist failed with the following output:
Change Dir: /home/admin1/asr/wav2/dependencies/arrayfire/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_4fdda/fast"
/usr/bin/make -f CMakeFiles/cmTC_4fdda.dir/build.make CMakeFiles/cmTC_4fdda.dir/build
make[1]: Entering directory '/home/admin1/asr/wav2/dependencies/arrayfire/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_4fdda.dir/CheckSymbolExists.c.o
/usr/bin/cc   -fPIC    -o CMakeFiles/cmTC_4fdda.dir/CheckSymbolExists.c.o   -c /home/admin1/asr/wav2/dependencies/arrayfire/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_4fdda
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_4fdda.dir/link.txt --verbose=1
/usr/bin/cc -fPIC     CMakeFiles/cmTC_4fdda.dir/CheckSymbolExists.c.o  -o cmTC_4fdda 
CMakeFiles/cmTC_4fdda.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x1b): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_4fdda.dir/build.make:97: recipe for target 'cmTC_4fdda' failed
make[1]: *** [cmTC_4fdda] Error 1
make[1]: Leaving directory '/home/admin1/asr/wav2/dependencies/arrayfire/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_4fdda/fast' failed
make: *** [cmTC_4fdda/fast] Error 2

File /home/admin1/asr/wav2/dependencies/arrayfire/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/admin1/asr/wav2/dependencies/arrayfire/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_ebbbf/fast"
/usr/bin/make -f CMakeFiles/cmTC_ebbbf.dir/build.make CMakeFiles/cmTC_ebbbf.dir/build
make[1]: Entering directory '/home/admin1/asr/wav2/dependencies/arrayfire/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_ebbbf.dir/CheckFunctionExists.c.o
/usr/bin/cc   -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_ebbbf.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.10/Modules/CheckFunctionExists.c
Linking C executable cmTC_ebbbf
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_ebbbf.dir/link.txt --verbose=1
/usr/bin/cc -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_ebbbf.dir/CheckFunctionExists.c.o  -o cmTC_ebbbf -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_ebbbf.dir/build.make:97: recipe for target 'cmTC_ebbbf' failed
make[1]: *** [cmTC_ebbbf] Error 1
make[1]: Leaving directory '/home/admin1/asr/wav2/dependencies/arrayfire/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_ebbbf/fast' failed
make: *** [cmTC_ebbbf/fast] Error 2

**Comment by 9prady9** [comment]
I have tried reproducing the problem using the following docker file and haven't been able to. Can you please edit it as per your environment so that it can help me reproduce the issue on my end.
```Dockerfile
FROM ubuntu:bionic

WORKDIR /

CMD ["/bin/bash"]

RUN apt-get update && \
    apt-get install --yes --no-install-recommends ca-certificates \
            build-essential git libfreeimage-dev wget \
            libopenblas-dev libfftw3-dev liblapacke-dev \
            opencl-headers libboost-all-dev ocl-icd-opencl-dev

RUN apt-get install libidn11

# CMake
RUN cd /usr/src && \
    CMAKE_VERSION=3.6.0 && \
    CMAKE_BINARY=cmake-$CMAKE_VERSION-Linux-x86_64.sh && \
    wget https://cmake.org/files/v3.6/$CMAKE_BINARY && \
    chmod +x $CMAKE_BINARY && ./$CMAKE_BINARY --skip-license --prefix=/usr && \
    rm $CMAKE_BINARY

RUN cd / && git clone --recursive https://github.com/arrayfire/arrayfire.git

RUN cmake --version

RUN cd /arrayfire && \
    mkdir build && cd build && \
    cmake .. -DAF_BUILD_CUDA=OFF -DAF_BUILD_OPENCL=OFF -DCMAKE_BUILD_TYPE=Release -DAF_BUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF

```

**Comment by kapilg1997** [comment]
> I have tried reproducing the problem using the following docker file and haven't been able to. Can you please edit it as per your environment so that it can help me reproduce the issue on my end.
> 
> ```dockerfile
> FROM ubuntu:bionic
> 
> WORKDIR /
> 
> CMD ["/bin/bash"]
> 
> RUN apt-get update && \
>     apt-get install --yes --no-install-recommends ca-certificates \
>             build-essential git libfreeimage-dev wget \
>             libopenblas-dev libfftw3-dev liblapacke-dev \
>             opencl-headers libboost-all-dev ocl-icd-opencl-dev
> 
> RUN apt-get install libidn11
> 
> # CMake
> RUN cd /usr/src && \
>     CMAKE_VERSION=3.6.0 && \
>     CMAKE_BINARY=cmake-$CMAKE_VERSION-Linux-x86_64.sh && \
>     wget https://cmake.org/files/v3.6/$CMAKE_BINARY && \
>     chmod +x $CMAKE_BINARY && ./$CMAKE_BINARY --skip-license --prefix=/usr && \
>     rm $CMAKE_BINARY
> 
> RUN cd / && git clone --recursive https://github.com/arrayfire/arrayfire.git
> 
> RUN cmake --version
> 
> RUN cd /arrayfire && \
>     mkdir build && cd build && \
>     cmake .. -DAF_BUILD_CUDA=OFF -DAF_BUILD_OPENCL=OFF -DCMAKE_BUILD_TYPE=Release -DAF_BUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF
> ```

Actually I just purge removed cuda and opencl and then installed using CPU dependencies with

mkdir build && cd build
cmake .. -DCMAKE_BUILD_TYPE=AF_BUILD_CPU

It seems to work. Closing the issue for now
