### ISSUE TITLE
OpenCL: Non-kernel function variable cannot be declared in local address space

### ISSUE THREAD

**Issue by glavaux2** [arrayfire/arrayfire#2803]
In https://github.com/arrayfire/arrayfire/tree/master/src/backend/opencl/kernel/reduce_blocks_by_key_dim.cl (and similar kernels), arrayfire make us of the following construct:

```
Tk work_group_scan_inclusive_add(__local Tk *arr) {
    __local Tk tmp[DIMX];
    __local int *l_val;
```

My OpenCL compiler complains about it with that error:
input.cl:152:16: error: non-kernel function variable cannot be declared in local address space

It seems that this error is legit from the compiler side according to the specification:
https://www.khronos.org/registry/OpenCL/sdk/2.0/docs/man/xhtml/local.html which indicates
`Variables allocated in the __local address space inside a kernel function must occur at kernel function scope.`

which is not the case here.

**Comment by 9prady9** [comment]
Thank you for reporting this. Interestingly, nvidia OpenCL implementation doesn't complain about this.

I think we can use local address pointer declarations inside non-kernel functions, but not the array declarations. I will raise a PR with fix soon and update here.

**Comment by 9prady9** [comment]
@glavaux2 Can you please test the following patch. 

You can apply the patch via `git apply ocl_rbk.txt`

[ocl_rbk.txt](https://github.com/arrayfire/arrayfire/files/4369051/ocl_rbk.txt)

**Comment by glavaux2** [comment]
Thanks it now compiles, though the OpenCL library now complains about something else
`CL user error: clEnqueueFillBuffer() requires OpenCL version 1.2 or greater.` (that implementation is CL1.1)

I guess that this one is fine, I will try to test that with another OpenCL driver.

**Comment by 9prady9** [comment]
That is odd, we don't use `clEnqueueFillBuffer` anywhere internally. Are you using any custom kernels and using this function ?

**Comment by glavaux2** [comment]
There are those calls in opencl/kernel/reduce_by_key.hpp
```
        // reset flags
        getQueue().enqueueFillBuffer<int>(*needs_another_reduction.get(), 0, 0,
                                          sizeof(int));
        getQueue().enqueueFillBuffer<int>(*needs_block_boundary_reduction.get(),
                                          0, 0, sizeof(int));
```

**Comment by 9prady9** [comment]
Ah, okay. I see. I searched for the OpenCL C API call. My bad.

We almost always had OpenCL 1.1 work fine till now. Looks like this is added recently. We will have to verify if that is going to be problem with different OpenCL implementations. Will keep this issue posted.
