### ISSUE TITLE
Remove dependancy between afunified and mkl

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#2805]
As today, afunified is still linking directly with mkl : 
$ ldd Linux/libraries/arrayfire-3.7.0/lib64/libaf.so
	linux-vdso.so.1 =>  (0x00007fffbe7ae000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f44f43ae000)
	libmkl_core.so => libmkl_core.so (0x00007f44f00d9000)
	libmkl_intel_lp64.so => libmkl_intel_lp64.so (0x00007f44ef561000)
	libmkl_gnu_thread.so => libmkl_gnu_thread.so (0x00007f44edd0e000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f44edaec000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f44ed8cf000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f44ed5c6000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f44ed244000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f44ed02e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f44ecc64000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f44f4a96000)

This is conflicting with : Java, Python, torch, ... needing to LD_PRELOAD and/or full rebuild of third parties.

afunified should be anyway neutral, not linking with any vendor lib like intel mkl (nor nvidia libs).
@umar456  Is there really nothing that could be done ?

**Comment by WilliamTambellini** [comment]
slightly related to: 
https://github.com/arrayfire/arrayfire/issues/2671

**Comment by WilliamTambellini** [comment]
Draft of possible solutions:
1- dynamically loading MKL just before dynloading afcpu : reported not to work perfectly or unsafe 
2- building afcpu with openblas : suboptimal perf and no dynamic JIT CPU architecture support (SSE, AVX, AVX2, AVX512, ...) capable 
3- build afcpu with tiny MKL : https://stackoverflow.com/questions/60707784/howto-build-mkl-tiny
4- static linking with mkl : would severly increase the size of afcpu but to be tried 
5- afcpu to build with either MKL or Intel DNNL : DNNL now offers, in a 20MB lib without any deps, a full JIT cpu support as fast as MKL, also provides fast convolution, elem wise mult, reduction, .... Drawback: no double nor complex support : https://github.com/intel/mkl-dnn
TBC

**Comment by WilliamTambellini** [comment]
building afcpu with static mkl seems to remove the dep. Tks.

**Comment by 9prady9** [comment]
This is addressed in https://github.com/arrayfire/arrayfire/commit/56f7b1faa0c9984b9c6fed0a0317b0309888b20a

Closing this issue
