### ISSUE TITLE
Examples can't find existing libforge.so

### ISSUE THREAD

**Issue by pauljurczak** [arrayfire/arrayfire#2811]
I've built `arrayfire` from source on Ubuntu 18.04. `libforge.so`, `libforge.so.1` and `libforge.so.1.0.5` are in `/usr/local/lib` directory. When I run an example program requiring graphics, I get:
```
ArrayFire Exception (Failed to load dynamic library. :501):
In function void* graphics::ForgeManager::getMainWindow()
In file src/backend/common/graphics_common.cpp:269
Error loading Forge: libforge.so: cannot open shared object file: No such file or directory
Forge or one of it's dependencies failed to load. Try installing Forge or check if Forge is in the search path.
 0# 0x00007F25957F277F in /usr/local/lib/libafcpu.so.3
 1# 0x00007F25969B90DD in /usr/local/lib/libafcpu.so.3
 2# af_create_window in /usr/local/lib/libafcpu.so.3
 3# af::Window::initWindow(int, int, char const*) in /usr/local/lib/libafcpu.so.3
 4# main in ./conway_cpu
 5# __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
 6# _start in ./conway_cpu
```
What is wrong?

**Comment by 9prady9** [comment]
To use forge lib from built path, you can do the following
`LD_LIBRARY_PATH=./build/extern/forge/src/backend ./build/graphics/conway_cpu`

If the path to which ArrayFire is installed(even if built from source) is searchable for executable for running programs, then forge should be found automatically. Can you please check your LD_LIBRARY_PATH value.

**Comment by pauljurczak** [comment]
Thank you for fast response.

`LD_LIBRARY_PATH` doesn't include, `/usr/local/lib`, but it should be on default library search path on Ubuntu. I fixed the problem just by running `ldconfig`.

**Comment by pauljurczak** [comment]
I may reinstall to non-system path the next time, but for now it's good enough evaluation.
