### ISSUE TITLE
Run on Bare-metal

### ISSUE THREAD

**Issue by mahmudemam** [arrayfire/arrayfire#2812]
Can anyone advice, if I can use arrayfire library directly on HW without using LINUX

**Comment by 9prady9** [comment]
We haven't tried that as far as I know.

I would think, we may need to do a major set of changes (depending on target HW) to the STL stuff we use internally, exceptions etc. for ArrayFire to used in embedded HW without Linux. What I can say for certain is that ArrayFire in it's current form cannot be utilized right away on bare-metal setup.

I haven't personally used GPUs in any bare-metal setup. May be someone from our team ( @arrayfire/core-devel ) has an idea/experience.

**Comment by umar456** [comment]
You can probably only get the CPU backend to work in this way if you are lucky. This is not something we intend to support.
