### ISSUE TITLE
libcublasLt.so.10 missing

### ISSUE THREAD

**Issue by erksch** [arrayfire/arrayfire#2818]
Hey guys!

After downloading ArrayFire-v3.7.1_Linux_x86_64.sh and installing I ran a small sample project inspired by the examples with:

CMakeLists.txt
```
project(arrayfire_test)

set(CMAKE_CXX_STANDARD 11)

find_package(ArrayFire)

if(ArrayFire_CUDA_FOUND)
    add_executable(arrayfire_test_cuda main.cpp)
    target_link_libraries(arrayfire_test_cuda ArrayFire::afcuda)
endif()
```

It builds successfully but I get the following error when executing:
```
error while loading shared libraries: libcublasLt.so.10: cannot open shared object file: No such file or directory
``` 

What confuses me, because I am using Cuda 10.0.130 on my machine, and to my knowledge the `libcublasLt` was added with Cuda 10.1, so I don't have it in my cuda-10.0 toolkit libraries (`/usr/local/cuda-10.0/lib64`). On the other hand, my `/usr/local/arrayfire/lib64` includes the library. So why can't it be found? Am I doing something wrong?

**Comment by 9prady9** [comment]
@erksch Did you complete the steps mentioned here - http://arrayfire.org/docs/installing.htm#Linux after installation ?

**Comment by erksch** [comment]
Ah yes, I am an idiot! Thank you for your super fast reply!!
