### ISSUE TITLE
afcuda.dll is too  big

### ISSUE THREAD

**Issue by xichaoqiang** [arrayfire/arrayfire#2822]
The size of afcuda.dll is too  big ,about 1G.
Can I get a smaller one about tens Mbs?

**Comment by 9prady9** [comment]
Is there any specific hardware/GPU you are targeting ? If so, you can custom build for that GPU alone which would reduce the binary size by a good amount.

What is the OS ?

**Comment by xichaoqiang** [comment]
Thanks for your reply.

My OS is Windows 10 X64.

Here is some informations about my system.

ArrayFire v3.7.1 (CUDA, 64-bit Windows, build d9d9b65)
Platform: CUDA Runtime 10.1, Driver: 10010
[0] GeForce GTX 1060, 6144 MB, CUDA Compute 6.1

![image](https://user-images.githubusercontent.com/30900789/78420408-755b5500-7681-11ea-8049-1bc614896379.png)

**Comment by 9prady9** [comment]
If your target GPU is going to be just GTX 1060, the binary can be reduced by a good bit using a custom build for just that architecture.  But if your target GPU isn't fixed, then the earlier suggested specific custom build won't help.

**Comment by xichaoqiang** [comment]
My program is very lightweight, only a few Mb. This library file is too large to distribute.

Arrayfire is brilliant.Here is my result of helloword.cpp

ArrayFire v3.7.1 (CPU, 64-bit Windows, build d9d9b65)
[0] Intel: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz, 24449 MB, Max threads(12)
Dense Conjugate Gradient Time: 39.45ms
Sparse Conjugate Gradient Time: 19.31ms

ArrayFire v3.7.1 (CUDA, 64-bit Windows, build d9d9b65)
Platform: CUDA Runtime 10.1, Driver: 10010
[0] GeForce GTX 1060, 6144 MB, CUDA Compute 6.1
Dense Conjugate Gradient Time: 5.643ms
Sparse Conjugate Gradient Time: 3.995ms

ArrayFire v3.7.1 (OpenCL, 64-bit Windows, build d9d9b65)
[0] NVIDIA: GeForce GTX 1060, 6144 MB
-1- INTEL: Intel(R) UHD Graphics 630, 9779 MB
-2- INTEL: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz, 24449 MB
Dense Conjugate Gradient Time: 5.986ms
Sparse Conjugate Gradient Time: 12.15ms

ArrayFire v3.7.1 (OpenCL, 64-bit Windows, build d9d9b65)
-0- NVIDIA: GeForce GTX 1060, 6144 MB
[1] INTEL: Intel(R) UHD Graphics 630, 9779 MB
-2- INTEL: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz, 24449 MB
Dense Conjugate Gradient Time: 49.65ms
Sparse Conjugate Gradient Time: 32.22ms

ArrayFire v3.7.1 (OpenCL, 64-bit Windows, build d9d9b65)
-0- NVIDIA: GeForce GTX 1060, 6144 MB
-1- INTEL: Intel(R) UHD Graphics 630, 9779 MB
[2] INTEL: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz, 24449 MB
Dense Conjugate Gradient Time: 47.8ms
Sparse Conjugate Gradient Time: 33.05ms

**Comment by 9prady9** [comment]
Unfortunately, at the moment the only way to reduce the windows binary further is to do custom build ArrayFire for specific compute version of nvidia GPU.

Having said that, if you want to ship ArrayFire dlls just for demo purpose and performance is not of great implication you can do a `MinSizeRel` build of ArrayFire and ship that. I haven't done configuration build earlier, so I can't exactly tell you how much will be the exact size in that configuration but it will definitely smaller than any other build configuration.

@umar456 @syurkevi Anything you want to add/suggest ?

**Comment by umar456** [comment]
@xichaoqiang 

This is unfortunately an issue with the way CUDA libraries are built. Because each generation of the NVIDIA GPUs have different assemblies, we need to include all versions with our library. As @9prady9 said you can reduce the size of your own build if you limit it to a small number of GPUs but that may not be an option. We have been working on reducing the size of the binaries with every new release using NVRTC but it will take a good bit of effort to fully convert the entire codebase over to this approach. Even with this change, it is unlikely we will be able to bring the size of the binary to a "tens of Mbs"

Closing this issue because it cannot be fixed by the library. Please continue to post if you have additional questions.
