### ISSUE TITLE
Error message about mkl_intel_thread.dll

### ISSUE THREAD

**Issue by xichaoqiang** [arrayfire/arrayfire#2823]
Here is some informations about my system.

ArrayFire v3.7.1 (CUDA, 64-bit Windows, build d9d9b65)
Platform: CUDA Runtime 10.1, Driver: 10010
[0] GeForce GTX 1060, 6144 MB, CUDA Compute 6.1

ArrayFire v3.7.1 was installed with binary package, and I try run ArrayFire-VS2015 project.

CPU_X64 and OpenCl will show an Error messsage,only Cuda x64(Debug /Release) can be complied and run.

![image](https://user-images.githubusercontent.com/30900789/78420586-f1a26800-7682-11ea-9c5d-ea1020de1045.png)

Here is lib folder of ArrayFire.

![image](https://user-images.githubusercontent.com/30900789/78420593-0c74dc80-7683-11ea-948c-e5daf435b433.png)

**Comment by 9prady9** [comment]
What does the error message say ? (I can see the dll name etc, but the error message isn't in english)

**Comment by xichaoqiang** [comment]
It means "The ordinal 242 could not be located in the dynamic link library"

**Comment by 9prady9** [comment]
Do you have any other Intel MKL installation somewhere else on the system ? Can you please use [dependency walker](https://www.dependencywalker.com/) and check if the right dlls are being used.

Alternatively for a simpler test, you can copy the example executable into the `lib` folder of ArrayFire installation and run it to check if it still shows the same problem.

**Comment by xichaoqiang** [comment]
It will be OK under lib folder of ArrayFire.So it is very strang.

**Comment by 9prady9** [comment]
Then that would mean, some other Intel MKL dll of mostly different version is being picked up the program instead of the one present under `arrayfire/lib` folder. Can you please check if there are other Intel MKL installations on your system.

**Comment by xichaoqiang** [comment]
![image](https://user-images.githubusercontent.com/30900789/78420862-be150d00-7685-11ea-8d70-432a16ddc014.png)
It seems an other MKL is in the computer.How can I do ?

**Comment by 9prady9** [comment]
I don't think there is anything that can be done from ArrayFire installation or settings to resolve this. This is a traditional windows issue - dll conflicts. 

I would suggest you remove both paths from `PATH` environment varialbe and set them up in repsective development projects so that the right dll gets picked by anaconda and ArrayFire for their programs.

**Comment by xichaoqiang** [comment]
Yes,you are right.I think this issue can be closed.
