### ISSUE TITLE
3D Array Error: element-wise multiplication

### ISSUE THREAD

**Issue by xichaoqiang** [arrayfire/arrayfire#2828]
I want element-wise multiplication two 3D error.But  met an error.

With Matlab or Numpy, I can get the correct result.
The result cube dimensions: 1000x1000x100
```
#include <stdio.h>
#include <arrayfire.h>
int main() {
	int N = 1000;
	array A = randu(N, 1, 100);
	array B = randu(1, N, 100);
	array C = A * B;
	return 0;
	}
```

**Comment by syurkevi** [comment]
ArrayFire does not perform broadcasting. Instead, the user must manually specify how the inputs need to be tiled. In your example
```
array A = randu(N, 1, 100);
array B = randu(1, N, 100);
A = tile(A, 1, N);
B = tile(B, N, 1);
array C = A * B;
```

We've considered adding broadcasting in the past and are not against adding it in the future, however it has some ambiguous cases that we haven't reached an agreement on. 
Keep in mind you can also get support for quick questions on our slack channel and google groups.
https://app.slack.com/client/T6NTNP9GX/C6M9AEJTB/user_profile/U6NV9S6HM
https://groups.google.com/forum/#!forum/arrayfire-users
