### ISSUE TITLE
how to add arrayfire library to path

### ISSUE THREAD

**Issue by ZHAOZETAO** [arrayfire/arrayfire#2832]
I am new to linux and I do not have sudo permission. I download arrayfire.sh and extract to home/Download/ArrayFire. But in python, it still can not find arrayfire library. I guess I need to add something to path. The instruction says you will need to set the LD_LIBRARY_PATH environment variable in order to let your shared library loader find the ArrayFire libraries. but I don't know how to do this.

**Comment by 9prady9** [comment]
@ZHAOZETAO https://github.com/arrayfire/arrayfire-python/wiki

**Comment by 9prady9** [comment]
Please raise issues related to wrappers in their respective projects.

I am closing this one. If the python wiki URL I shared earlier doesn't resolve your problem. Feel free to open the issue in https://github.com/arrayfire/arrayfire-python project.
