### ISSUE TITLE
OpenCL backend on thread causes abort due to GLFW (MacOS)

### ISSUE THREAD

**Issue by samuelpowell** [arrayfire/arrayfire#2833]
If I link against the OpenCL backend, and launch computations outside of my main thread, I get an exception and crash.

This appears to be because GLFW initialisation functions (which I understand can only be called from the main thread, at least on OSX) are called, _despite_ the fact I am not using any of the graphics output provided by forge.

The problem goes away if I launch with the ```AF_DISABLE_GRAPHICS``` environment variable set, because GLFW is then not called. Which makes sense. But it also goes away if I link against, e.g., the CPU backend. 

Given that I am not calling the graphics functionality in either case, why is the OpenCL backend trying to init GLFW? Is there any way I can prevent this programmatically?

**Comment by samuelpowell** [comment]
I'm guessing this is related: https://github.com/arrayfire/arrayfire/issues/2062

It appears you have to do some initialisation for potential use of Forge irrespective of usage, is that correct?

**Comment by 9prady9** [comment]
> I'm guessing this is related: #2062
> 
> It appears you have to do some initialisation for potential use of Forge irrespective of usage, is that correct?

I don't think so, it is headless configuration. Is your setup also without a display ?

In a multi-threaded program, each thread has to call `af::setDevice` before doing any computation on that thread. Can you check if that is happening.

Note that graphics related setup is carried out during the program initialization: `af::info()` or `af::setDevice()` that happens in the main thread takes care of it. If you don't have any sort of arrayfire related code in main thread, then I believe that is the reason GLFW is complaining about that.

`AF_DISABLE_GRAPHICS` environment is the way to disable graphics related functionality.

**Comment by samuelpowell** [comment]
Thank you @9prady9.

Yes, I was calling `af::setDevice` in the processing thread, but I was not initialising in the main thread, as it doesn't call arrayfire. Adding `af::info` to the main thread causes the GLFW init to happen there, and all is well.

Is this particular case documented?

**Comment by 9prady9** [comment]
I am not sure, but I am certain we have mentioned in quite a few https://github.com/arrayfire/arrayfire/issues related threaded programs . This is a common practice w.r.t CUDA / OpenCL. But I see your concern about how one can miss this without explicit direction.

We could definitely add a tutorial to our [tutorials section](http://arrayfire.org/docs/tutorials.htm) that has some guidelines, tips and tricks related to threaded programs.

I have raised a new issue to address it - https://github.com/arrayfire/arrayfire/issues/2834

**Comment by samuelpowell** [comment]
Before I close this, one final question. Whatever GLFW init Arrayfire is doing, it stops my GUI (which runs in the main thread) from rendering. Again, things are fine when the graphics disable environment variable is passed. 

If there is no programatic way to inhibit this behaviour, would you be able to point me in the direction of the source so I can see what is being done, and try to interact with this gracefully?

**Comment by samuelpowell** [comment]
Ahhh, okay, I see why I couldn't find it - this actually happens in forge, against which you are linked. In particular, [here](https://github.com/arrayfire/forge/blob/c0a0ee909a4f9f661f244d54b8796261e7e4c815/src/backend/opengl/glfw/window.cpp), do I understand correctly?

**Comment by 9prady9** [comment]
There are couple of things here to understand when it comes to OpenCL. 

- The device contexts that support inter-operation between OpenGL and OpenCL buffers have to be created right in the beginning i.e. we need to use OpenGL context to create contexts, queues etc.
- Forge is ArrayFire's graphics upstream dependency is loaded at runtime. ArrayFire programs will work fine even if they cannot find the forge shared libraries (and their dependencies) as they would consider that session as no graphics support, so all OpenCL contexts etc will be without any OpenGL-OpenCL inter-operation support.

[This section of code](https://github.com/arrayfire/arrayfire/blob/master/src/backend/opencl/device_manager.cpp#L292-L303) is the top of the code-path that enables creation of OpenGL-OpenCL interoperable contexts. As you can see in the Line 292, if `forge loading at runtime fails` or `AF_DISABLE_GRAPHICS is set to 1`, this code-path is ignored and OpenCL backend will behave as if there is no graphics support.

Therefore, you either have to use `AF_DISABLE_GRAPHICS` or make sure forge shared libraries are not distributed with your program. Right now, there is no function in the API that lets you do this. 

In my opinion, having a new function that lets you turn off graphics has it's own set of issues such as the following:
- It has to be the first call in your program from main thread to ArrayFire.
- There is no way for ArrayFire to know where this function is called from i.e. beginning of the program or somewhere later in the code. We cannot restrict it's usage to beginning of the program. This has some implications in OpenCL backend especially.

May I know why you don't want to use the environment variable approach ?

What do you mean by `it stops your GUI` ? Is your GUI also OpenGL based ? Does the GUI continue after few seconds hang-up ? Or it ends in a crash ?

**Comment by samuelpowell** [comment]
Thank you for your detailed explanation, whilst I'm very comfortable with CUDA and OpenGL interop, I have very limited experience with OpenCL, so it is helpful to understand the process. Furthermore, I now understand your point regarding the difficulties of having an API for disabling graphics.

I am happy to use the environment variable in practice, I just wanted to dig down to make sure I understood what was going on.

The GUI uses GLFW and is rendered using OpenGL. The application runs fine, and the render loop is executing, but no window is ever created if arrayfire has executed its initialisation.

**Comment by 9prady9** [comment]
Perhaps, it could be related to issue such as the one mentioned in this https://github.com/glfw/glfw/issues/927 ? I am not sure though, in that github-issue they talk about same but on Windows.

**Comment by samuelpowell** [comment]
Yes, and this

> So GLFW doesn't support multiple copies of itself in the same process (as you've noticed). It doesn't actively prohibit it and it might work on some platforms or some of the time, but the code isn't written with that in mind. 

may explain why there is no error.

If I manage to get any further finding out the issue and a potential workaround I will open another issue. For now, thank you for your help with this.
