### ISSUE TITLE
Slice array error by define range.

### ISSUE THREAD

**Issue by xichaoqiang** [arrayfire/arrayfire#2842]
I want make slice sqe with  the binomial coefficient function.

And I save the combinations result into a array.

Can I use a column of array as a seq to slice another array?

Here is my code

```
int get_R(int StationNum, array OffX, array OffY)
{
//Binomial coefficient or all combinations
std::vector<int> list_i;
for (int ii = 1; ii <= StationNum; ii++)		list_i.push_back(ii);
auto nck2 = nchoosek<int>(list_i, 2);
// convert combinations to array
array C = constant(1, nck2.size(), 3);

for (int i = 0; i < nck2.size(); i++)
{
	for (int j = 0; j < 2; j++)
	{
		C(i, j) = nck2[i][j];
	}
}

//slice OffsetX array from C(:,1)
array x1 = OffX(C(span, 0));

//slice OffsetY array from C(:,2)
array x2 = OffY(C(span, 1));
	
}
```
![image](https://user-images.githubusercontent.com/30900789/79236180-36a67580-7e9f-11ea-9277-0044777e8fde.png)
Error E0304 There is no overloaded function that matches the parameter list
Here is example of array C
![image](https://user-images.githubusercontent.com/30900789/79236532-a583ce80-7e9f-11ea-8cc5-2bebd3fddd8d.png)

**Comment by 9prady9** [comment]
> array C = constant(1, nck2.size(), 3);
 for (int i = 0; i < nck2.size(); i++)
 {
	for (int j = 0; j < 2; j++)
	{
		C(i, j) = nck2[i][j];
	}
 }

Indexing individual elements when the memory is residing on a GPU is going to be very inefficient in terms of performance.

If `nck2` is just another `std::vector` you can easily pass on the data to GPU using 
```c++
array C(nck2.size(), nck2.data())
```
You can get columns from array using `array::col` method
```c++
array col0 = C.col(0); // you can also use what you have, this is more readable
array col1 = C.col(1);

array x1 = OffX(col0); 
array x2 = OffY(col1); 
```
Does the above code snippet work ?

**Comment by xichaoqiang** [comment]
OK,thank you.
I correct it with flat funtion.

**Comment by xichaoqiang** [comment]
My programming habits are still Matlab.Thank you.
