### ISSUE TITLE
How to apply existing function(norm) to each row？

### ISSUE THREAD

**Issue by xichaoqiang** [arrayfire/arrayfire#2843]
I want compute the norm of each row of s matrix and r matrix.How can I do without for loop?
```
	array s = join(1, x1, y1);
	array r = join(1, x2, y2);
```

**Comment by xichaoqiang** [comment]
Here is my code. Is there any more effective way to code it?
```
	array C=nchoosek(StationNum, 2);//Get all combi
	array x1 = OffXY(flat(C.col(0)),0);//source_x
	array x2 = OffXY(flat(C.col(1)),0);//receiver_x
	array y1 = OffXY(flat(C.col(0)),1);//source_y
	array y2 = OffXY(flat(C.col(1)),1);//receiver_y
	array s = join(1, x1, y1);
	array r = join(1, x2, y2);
	array sr = s - r;
	for (size_t i = 0; i < sr.dims(0); i++)
	{
		C(i, 2) = norm(sr.row(i));
	}
```

**Comment by 9prady9** [comment]
@xichaoqiang I don't think there is an alternative to for-loop at the moment for this particular function `norm` since it doesn't have batch support yet.

**Comment by umar456** [comment]
This is not a bug in ArrayFire. Please post these types of questions in the Slack channel or Google groups. You can find the links for these in the README.md file.
