### ISSUE TITLE
Can I give a  implement to 2D matrix with specified axis(0 or 1)

### ISSUE THREAD

**Issue by xichaoqiang** [arrayfire/arrayfire#2844]
I have a 2d matirx. And I want implemet fft to each coloumn of it.
How can I do ?

**Comment by 9prady9** [comment]
[fft](http://arrayfire.org/docs/group__signal__func__fft.htm#ga8b445e474508d96da691a9608dec5403) shuld be able to handle a bunch of vectors.

`fft(in)`

**Comment by xichaoqiang** [comment]
Thanks for your reply.

**Comment by umar456** [comment]
These types of questions should be directed to our Slack channel or google groups. Closing this because this is not a bug in ArrayFire.
