### ISSUE TITLE
cuda error on Ubuntu linux with arrayfire version v3.7.1-1

### ISSUE THREAD

**Issue by Tikhon03** [arrayfire/arrayfire#2856]
I am getting the following error when compiling with cuda:

ArrayFire Exception (Internal error:998):
In function std::vector<char> cuda::compileToPTX(const char*, std::string)
In file src/backend/cuda/jit.cpp:291
NVRTC Error(5): NVRTC_ERROR_INVALID_OPTION

I do not get any such error when compiling for the cpu. I have Ubuntu 20.04, installed just today. Arrayfire v3.7.1-1 installed in /opt via the script. 

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

The gpu is an nvidia GTX 1660 Ti:

01:00.0 VGA compatible controller: NVIDIA Corporation TU116 [GeForce GTX 1660 Ti] (rev a1)
01:00.1 Audio device: NVIDIA Corporation TU116 High Definition Audio Controller (rev a1)
01:00.2 USB controller: NVIDIA Corporation TU116 USB 3.1 Host Controller (rev a1)
01:00.3 Serial bus controller [0c80]: NVIDIA Corporation TU116 [GeForce GTX 1650 SUPER] (rev a1)

The nvidia driver version is

NVIDIA-SMI 440.64       Driver Version: 440.64       CUDA Version: 10.2

As you can see there is a mismatch between the cuda version as listed by the driver vs the nvidia-cuda-toolkit version. The driver is loaded so far as I can tell:

lsmod | grep nvidia
nvidia_uvm            970752  0
nvidia_drm             49152  5
nvidia_modeset       1114112  14 nvidia_drm
nvidia              20430848  725 nvidia_uvm,nvidia_modeset
drm_kms_helper        184320  1 nvidia_drm
ipmi_msghandler       106496  2 ipmi_devintf,nvidia
drm                   491520  8 drm_kms_helper,nvidia_drm
i2c_nvidia_gpu         16384  0

Is the mismatch of the cuda version between the graphics driver and nvidia-cuda-toolkit the problem?

**Comment by umar456** [comment]
That is not the issue. As long as the version listed by the drive is higher than the version listed in the toolkit it should be ok. Can you run your program with these environment variables set:

AF_PRINT_ERRORS=1 AF_TRACE=all

**Comment by Tikhon03** [comment]
I was able to get a little more information:

[mem][5240] [ ../src/backend/cuda/memory.cpp:191 ] nativeAlloc: 4.38 MB 0x7f41fe000000
[mem][5240] [ ../src/backend/cuda/memory.cpp:191 ] nativeAlloc: 4.38 MB 0x7f41fe600000
[mem][5240] [ ../src/backend/cuda/memory.cpp:191 ] nativeAlloc:    1 KB 0x7f41fec00000
In function std::vector<char> cuda::compileToPTX(const char*, std::string)
In file src/backend/cuda/jit.cpp:291
NVRTC Error(5): NVRTC_ERROR_INVALID_OPTION

ArrayFire Exception (Internal error:998):
In function std::vector<char> cuda::compileToPTX(const char*, std::string)
In file src/backend/cuda/jit.cpp:291
NVRTC Error(5): NVRTC_ERROR_INVALID_OPTION

In function void af::array::host(void*) const
In file src/api/cpp/array.cpp:254

If this is not enough, please let me know what else I should do. Thank you.

**Comment by Tikhon03** [comment]
After spending some time debugging at my end, it seems that this may not be an arrayfire error.

**Comment by umar456** [comment]
@Tikhon03 Can you elaborate how you came to that conclusion? Is there anything you could post that would help others if they see the same error on their system?

**Comment by Tikhon03** [comment]
I am using two different interfaces. While the one interface leads to the errors above. With the other there is no problem:

``[platform][1591111065][001916] [ ../src/backend/common/DependencyModule.cpp:55 ] Attempting to load: libforge.so
[platform][1591111065][001916] [ ../src/backend/common/DependencyModule.cpp:58 ] Found: libforge.so
[platform][1591111065][001916] [ ../src/backend/cuda/device_manager.cpp:424 ] CUDA Driver supports up to CUDA 10.2 ArrayFire CUDA Runtime 10.0
[platform][1591111065][001916] [ ../src/backend/cuda/device_manager.cpp:492 ] Found 1 CUDA devices
[platform][1591111065][001916] [ ../src/backend/cuda/device_manager.cpp:518 ] Found device: GeForce GTX 1660 Ti (5.8 GB | ~5493.16 GFLOPs | 24 SMs)
[platform][1591111065][001916] [ ../src/backend/cuda/device_manager.cpp:553 ] AF_CUDA_DEFAULT_DEVICE: 
[platform][1591111065][001916] [ ../src/backend/cuda/device_manager.cpp:572 ] Default device: 0(GeForce GTX 1660 Ti)
[mem][1591111066][001916] [ ../src/backend/cuda/memory.cpp:153 ] nativeAlloc: 4.38 MB 0x7f4a5d400000
[mem][1591111066][001916] [ ../src/backend/cuda/memory.cpp:153 ] nativeAlloc:    1 KB 0x7f4a5da00000
[jit][1591111066][001916] [ ../src/backend/cuda/nvrtc/cache.cpp:328 ] {KER5891556064238943067         : { compile:  151 ms, link:   5 ms, { --gpu-architecture=compute_75 }, GeForce GTX 1660 Ti }}
[mem][1591111066][001916] [ ../src/backend/cuda/memory.cpp:153 ] nativeAlloc:    1 KB 0x7f4a5da00400
[jit][1591111066][001916] [ ../src/backend/cuda/nvrtc/cache.cpp:328 ] {KER10630659000380930707        : { compile:  104 ms, link:   0 ms, { --gpu-architecture=compute_75 }, GeForce GTX 1660 Ti }}
[jit][1591111066][001916] [ ../src/backend/cuda/nvrtc/cache.cpp:328 ] {KER5377988561589749704         : { compile:  101 ms, link:   1 ms, { --gpu-architecture=compute_75 }, GeForce GTX 1660 Ti }}
[jit][1591111066][001916] [ ../src/backend/cuda/nvrtc/cache.cpp:328 ] {KER11230689059033517936        : { compile:  102 ms, link:   1 ms, { --gpu-architecture=compute_75 }, GeForce GTX 1660 Ti }}
[jit][1591111067][001916] [ ../src/backend/cuda/nvrtc/cache.cpp:328 ] {KER12848859620079611880        : { compile:  102 ms, link:   1 ms, { --gpu-architecture=compute_75 }, GeForce GTX 1660 Ti }}
"
I am still not sure why the one interface is working and the other is not. Perhaps with more debugging I can tell you that sometime soon.

**Comment by 9prady9** [comment]
@Tikhon03 Did you get the chance to revisit this issue ? We released 3.7.2 just couple of days back, please check it out also.

**Comment by Tikhon03** [comment]
I checked it just now. It seems I am no longer having the issue with 3.7.2. Thank you for pointing out the new release to me.
