### ISSUE TITLE
BUG: batch matmul wrong results with cuda

### ISSUE THREAD

**Issue by vakopian** [arrayfire/arrayfire#2869]
There seems to be a bug with the **cuda** version of `matmul` in **batch** mode. Below I try to multiply a `16x36` array by a `36x1x256x404` array, both constant 1s. I expect the output to have `36` everywhere. But it's only partially `36` - all columns starting from 256 are `0`.
The following code produces the wrong results at the "right side" of the output:
```
  array lhs = constant(1.0f, 16, 36, f32);
  array rhs = constant(1.0f, 36, 1, 256, 404, f32);
  array p = matmul(lhs, rhs);
  print("right columns", moddims(p(0, 0, seq(0, 5), seq(398, 403)), 6, 6));

```
The output is:
```
right columns
[6 6 1 1]
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
```
This is wrong, as all numbers should actually be `36.0`, not zero.
In fact the "left side" of the result is actually correct:
```
print("left columns", moddims(p(0, 0, seq(0, 5), seq(0, 5)), 6, 6));
```
gives:
```
left columns
[6 6 1 1]
   36.0000    36.0000    36.0000    36.0000    36.0000    36.0000 
   36.0000    36.0000    36.0000    36.0000    36.0000    36.0000 
   36.0000    36.0000    36.0000    36.0000    36.0000    36.0000 
   36.0000    36.0000    36.0000    36.0000    36.0000    36.0000 
   36.0000    36.0000    36.0000    36.0000    36.0000    36.0000 
   36.0000    36.0000    36.0000    36.0000    36.0000    36.0000 
```

Note that, it all works correctly with the CPU back-end. And I have not tried OpenCL. 

After playing a little with the sizes of the large array, I think something goes wrong after the last two dimensions combined exceed `2^16` elements, which hints to some memory limit?
The only "recent" change I could find that may have caused an issue seems to be #2416, but I have no idea if it's really the root cause.

**Comment by 9prady9** [comment]
I have tried to reproduce on latest v3.7.1 release tag and I am unable to reproduce this issue on any of the backends.

Can you please tell us the following information.

1. version of arrayfire you have
2. installed via binary provided on our website or built yourself
3. CUDA GPU info - running helloworld or `af::info()` should get you the basic info we need.

**Comment by vakopian** [comment]
@9prady9 Thanks for looking into this. Indeed it turns out this is only happening when linking with arrayfire that I built locally. It works correctly with binaries provided on the website. Here is the other information you asked for:

1. I've tried it with both 3.7.0 and 3.7.1
2. Built myself using 
```
cmake .. -DCMAKE_BUILD_TYPE=Release -DAF_BUILD_OPENCL=OFF -DAF_BUILD_FORGE=OFF
```
3. af::info() for 3.7.0:
```
ArrayFire v3.7.0 (CUDA, 64-bit Linux, build fbea2aeb)
Platform: CUDA Runtime 10.0, Driver: 410.48
-0- GeForce GTX 1080 Ti, 11179 MB, CUDA Compute 6.1
[1] GeForce GTX 1080 Ti, 11179 MB, CUDA Compute 6.1
```
af::info() for 3.7.1:
```
ArrayFire v3.7.1 (CUDA, 64-bit Linux, build d9d9b658)
Platform: CUDA Runtime 10.0, Driver: 410.48
-0- GeForce GTX 1080 Ti, 11179 MB, CUDA Compute 6.1
[1] GeForce GTX 1080 Ti, 11179 MB, CUDA Compute 6.1
```

I'm going to run the arrayfire tests in my build to see if anything fails. Will report back shortly. Is there anything else I should check?

**Comment by 9prady9** [comment]
You can verify if the executable and/or `libafcuda.so` are using the right set of CUDA libraries using `ldd` . Ideally, we want them to use the same set for both building and executing the program. I am guessing that is the issue.

**Comment by vakopian** [comment]
It looks like pretty much every cuda test is failing in my build.
I only have a single version of cuda installed on the machine (which is both the build machine and where the program is executed). Here is the output `ldd ./src/backend/cuda/libafcuda.so.3.7.0` in my build directory
```
$ ldd ./src/backend/cuda/libafcuda.so.3.7.0
        linux-vdso.so.1 (0x00007ffce7dfb000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8a1e4b7000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f8a1e2af000)
        libnvrtc.so.10.0 => /usr/local/cuda/lib64/libnvrtc.so.10.0 (0x00007f8a1cc93000)
        libcublas.so.10.0 => /usr/local/cuda/lib64/libcublas.so.10.0 (0x00007f8a186fd000)
        libcufft.so.10.0 => /usr/local/cuda/lib64/libcufft.so.10.0 (0x00007f8a12249000)
        libcusolver.so.10.0 => /usr/local/cuda/lib64/libcusolver.so.10.0 (0x00007f8a09b62000)
        libcusparse.so.10.0 => /usr/local/cuda/lib64/libcusparse.so.10.0 (0x00007f8a060fa000)
        libcuda.so.1 => /usr/lib/x86_64-linux-gnu/libcuda.so.1 (0x00007f8a05004000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f8a04c7b000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8a048dd000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f8a046c5000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8a044a6000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8a040b5000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f8a270f5000)
        libnvidia-fatbinaryloader.so.410.48 => /usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.410.48 (0x00007f8a03e68000)
```
Anything suspicious here?

**Comment by 9prady9** [comment]
@vakopian Can you please come up on slack, would be easy to exchange messages quickly.

**Comment by vakopian** [comment]
Look like I need an invite for that. Would you send one to me please? Thanks.

**Comment by 9prady9** [comment]
Here is it, my bad I assumed you were already on the channel.

https://join.slack.com/t/arrayfire-org/shared_invite/MjI4MjIzMDMzMTczLTE1MDI5ODg4NzYtN2QwNGE3ODA5OQ

**Comment by 9prady9** [comment]
After some extensive testing with different toolkit versions and different tags of ArrayFire. The error was only happening with CUDA toolkit 10.0. Newer toolkit versions don't have this problem.

**Comment by 9prady9** [comment]
```
using namespace af;
    array lhs = constant(1.0f, 16, 36, f32);
    for (dim_t d = 100; d < 4000; d += 100) {
        array rhs = constant(1.0f, 36, 1, d, d, f32);
        array p = matmul(lhs, rhs);
        float bottomRight = p(p.dims(0) - 1, p.dims(1) - 1, p.dims(2) - 1, p.dims(3) - 1).scalar<float>();
        if (bottomRight == 36) {
            std::cout << "size " << d << " - ok" << std::endl;
        } else {
            std::cout << "size " << d << " - PROBLEM: found " << bottomRight << ", expecting 36" << std::endl;
        }
    }
```

**Comment by 9prady9** [comment]
Above snippet provided by @vakopian was tested on 10.0, 10.1 and 10.2 toolkit versions. The error is only happening on 10.0.

**Comment by vakopian** [comment]
@9prady9 Thank you so much for all your time and effort to uncover this!
As always amazing support from the AF team!
