### ISSUE TITLE
MKL lib files request

### ISSUE THREAD

**Issue by xichaoqiang** [arrayfire/arrayfire#2880]
Hello, I am using arrayfire to develop software, but I also want to use mkl to develop other functions. I want to use the mkl version used by arrayfire. Can you share the relevant lib files with me?

![image](https://user-images.githubusercontent.com/30900789/81532746-804b8880-9397-11ea-8b57-0871ae1b03aa.png)

**Comment by 9prady9** [comment]
@xichaoqiang The best way to handle this would be download relevant Intel MKL and use that. Given below is the version we used.

Intel MKL Version: 2019.4.245
Intel MKL Download name on website: 2019 Update 4
