### ISSUE TITLE
`convole2NN`: Why can't 0 padding be used?

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [arrayfire/arrayfire#2892]
The function [`convole2NN`](http://arrayfire.org/docs/group__signal__func__convolve2.htm#ga8a6da9b0bf8e0287d71d02e2cd763cde) does not allow for any of the of the values of the `padding` parameter to be 0.

It is relatively common practice to use 0 padding in convolutional layers.

Is this an oversight or a decision? If a decision, why?

**Comment by syurkevi** [comment]
This has been fixed in #2820 
If you don't want to rebuild master I think the C api does not have this issue.
