### ISSUE TITLE
arrayfire_test compilation error

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#2896]
Hello
This is 'just' a compilation error with todays master when building AF in a build folder not called 'build' (eg 'release', or 'debug'):
...
[ 23%] Built target af_cuda_static_cuda_library
In file included from /home/wtambellini/repos/arrayfire/test/./testHelpers.hpp:17:0,
                 from /home/wtambellini/repos/arrayfire/test/arrayfire_test.cpp:11:
/home/wtambellini/repos/arrayfire/test/../include/af/array.h:11:26: fatal error: af/compilers.h: No such file or directory
 #include <af/compilers.h>
                          ^
compilation terminated.

This is probably because the test cmake hardcodes the build folder to be named 'build' :  

target_include_directories(arrayfire_test
  PRIVATE
    .
    ../include
    ../build/include
    ../extern/half/include
    mmio
    gtest/googletest/include)

**Comment by 9prady9** [comment]
Thank you for reporting it. Fixed it in #2898
