### ISSUE TITLE
Document ArrayFire

### ISSUE THREAD

**Issue by umar456** [arrayfire/arrayfire#290]
The new ArrayFire headers are not documented. We need setup a framework for documenting functions. I suggest we use Doxygen so we can move the ArrayFire 2.1 descriptions easily. 

The headers should contain brief and parameter descriptions. Detailed descriptions should be contained in the source code. The goal is to create documentation which is similar to what we have now with updated content.

**Comment by 9prady9** [comment]
I suggest we give a shot to cldoc,  it is very nice.  I started working on it on my local system but It is currently on hold as I am on vacation.

**Comment by Kerkil** [comment]
How is this documentation effort coming along? Is there any documentation (even in progress) that I can refer to at this point?

**Comment by pentschev** [comment]
@pavanky / @umar456 I think this issue can be closed, since we already have documented all/almost all?

**Comment by umar456** [comment]
Documentation has been added. More work needs to happen but the framework is in place.
