### ISSUE TITLE
CUDA is lower than CPU version?

### ISSUE THREAD

**Issue by jjqcat** [arrayfire/arrayfire#2904]
I test the demo  with CUDA version, get  time spend by image threshold about 3000ms, but with CPU version is about 740ms.

CPU version:
E:\CCD-VisionController\Source\DependLib\array3.71\build\bin\Release>adaptive_thresholding_cpu.exe
ArrayFire v3.7.1 (CPU, 64-bit Windows, build default)
[0] Intel: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz, 16234 MB, Max threads(12)
time elapse 739 ms
Press ESC while the window is in focus to exit

CUDA version:
E:\CCD-VisionController\Source\DependLib\array3.71\build\bin\Release>adaptive_thresholding_cuda.exe
ArrayFire v3.7.1 (CUDA, 64-bit Windows, build default)
Platform: CUDA Runtime 10.2, Driver: 11000
[0] GeForce GTX 1660 Ti, 6144 MB, CUDA Compute 7.5
time elapse 3102 ms
Press ESC while the window is in focus to exit

my source code modified as:

	auto start = std::chrono::high_resolution_clock::now();
        array mnt = adaptiveThreshold(sudoku, MEAN, 37, 10);
        array mdt = adaptiveThreshold(sudoku, MEDIAN, 7, 4);
        array mmt = adaptiveThreshold(sudoku, MINMAX_AVG, 11, 4);
        array itt = 255.0f - iterativeThreshold(sudoku);
	auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::high_resolution_clock::now() - start).count();
	printf("time elapse %d ms\n",ms);

**Comment by 9prady9** [comment]
First run of the functions includes kernel compilation and device warm up.  Please use timeit from our timing tutorial to see the actual average run time. http://arrayfire.org/docs/timing.htm

**Comment by jjqcat** [comment]
I have use timeit function to evaluate it.
CUDA version:
E:\CCD-VisionController\Source\DependLib\array3.71\build\bin\Release>adaptive_thresholding_cuda.exe
ArrayFire v3.7.1 (CUDA, 64-bit Windows, build default)
Platform: CUDA Runtime 10.2, Driver: 11000
[0] GeForce GTX 1660 Ti, 6144 MB, CUDA Compute 7.5
pi_function took 0.0107953 seconds
Press ESC while the window is in focus to exit

CPU version:
E:\CCD-VisionController\Source\DependLib\array3.71\build\bin\Release>adaptive_thresholding_cpu.exe
ArrayFire v3.7.1 (CPU, 64-bit Windows, build default)
[0] Intel: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz, 16234 MB, Max threads(12)
pi_function took 0.0688733 seconds
Press ESC while the window is in focus to exit

the result is that CUDA version is faster than CPU version

**Comment by 9prady9** [comment]
Closing since the query has been addressed. @jjqcat Our slack channel is a better place for questions such as these. Here's the invite https://join.slack.com/t/arrayfire-org/shared_invite/MjI4MjIzMDMzMTczLTE1MDI5ODg4NzYtN2QwNGE3ODA5OQ
