### ISSUE TITLE
af_fast / af::fast performs unnecessary synchronization with clEnqueueWriteBuffer.

### ISSUE THREAD

**Issue by elad8a** [arrayfire/arrayfire#2909]
I am trying to use af_fast for feature detection.

I pre-allocate all input and output buffers and then initiate 10 consecutive calls to af_fast.

```
        auto af_vec = afcl::array(cols, rows, my_cl_mem, af::dtype::u8, true);
        af::features features(10000);   

        for (auto i = 0; i < 10; ++i)
        {          
            auto f = features.get();     
            // arrayfire perform a blocking clEnqueueWriteBuffer, why?
            af_fast(&f, af_vec .get(), 20.0f, 9, true, 0.05f, 3u);
        }

```
Analyzing this code with AMD CodeXL, it seems arrayfire somehow decides it should perform 2 synchronous calls to clEnqueueWriteBuffer .

Even if these memory transfers are  somehow necessary (I doubt the first one is, it looks like the implementation just copies the input buffer), there is no reason it should be made synchronous and prevent the CPU thread from enqueuing additional kernels and interleave computations.

**Comment by 9prady9** [comment]
Than you for reporting it.

Yes, both the write buffer calls can go non blocking I think. Not sure why they are blocking at the moment, perhaps it was originally the case but not any more after some refactoring.

In any case, I will send in a fix soon.

**Comment by elad8a** [comment]
@9prady9  thank you very much.

It seems that also af_sort suffers from the same issue.
The implementation synchronize in order to copy 64 bytes of memory after all kernels are enqueued.
I can't see any reason why it can't be async.

**Comment by 9prady9** [comment]
@elad8a Interesting, I did look for other places where enqueueWrite calls were made in kernel folder, sort didn't show up. Let me check.

**Comment by 9prady9** [comment]
We use boost compute for opencl sort implementation, perhaps it is doing is sync but I have to check to confirm that claim. ArrayFire code base though, doesn't have any synchronization points in `af_sort`, I can confirm that.

**Comment by elad8a** [comment]
@9prady9 you are right. I just switched to boost::compute::sort, indeed it causes the sync. I will see if this can somehow be avoided..

**Comment by 9prady9** [comment]
I wonder why boost compute even needs to do it for this .

**Comment by elad8a** [comment]
@9prady9 I think I found the culprit. boost compute dispatch_scan performs a call to the synchronous copy from a temporary std::vector.
```
        // make a temporary copy the input
        size_t count = iterator_range_size(first, last);
        vector<value_type> tmp(count, context);
        copy(first, last, tmp.begin(), queue);

```

**Comment by 9prady9** [comment]
@elad8a Can you tell the header name you found this on ? I found them on [scan](https://github.com/boostorg/compute/blob/a47ff938b78e30362ec8abd466b5a2773d4aae8d/include/boost/compute/algorithm/detail/scan_on_gpu.hpp) but I am not sure scan dispatch is being called for sort.

**Comment by elad8a** [comment]
@9prady9  line 296 on your link, you can put a breakpoint there.

**Comment by 9prady9** [comment]
Yes, I saw that line. What I was saying was, those lines are within `scan_dispatch` which isn't related to sort.

**Comment by elad8a** [comment]
@9prady9 sort calls this function in a loop. In my case i called sort with a boost::compute::vector<float> as argument.

**Comment by 9prady9** [comment]
Okay, I found it now. Sort calls radix sort for some cases, which is in turn calling `exclusive_scan` in [this](https://github.com/boostorg/compute/blob/master/include/boost/compute/algorithm/detail/radix_sort.hpp) file in a loop. 

The vector in the below section is a [custom class from boost compute](https://github.com/boostorg/compute/blob/master/include/boost/compute/container/vector.hpp) and it seems like it is doing a simple copy of the input to do an in-place operation. 
```
        size_t count = iterator_range_size(first, last);
        vector<value_type> tmp(count, context);
        copy(first, last, tmp.begin(), queue);
```
However, it is doing copy to host in some specializations of copy_dispatch function. I haven't explored what are those cases yet. I believe @kylelutz can shed more light on what are those cases clearly and work around for your scenario.
