### ISSUE TITLE
Sort in OpenCL is too slow

### ISSUE THREAD

**Issue by xyang2013** [arrayfire/arrayfire#291]
I followed the suggestion on the page of 'sort segfault #233':
1. Updated the repositories
2. Used the develop branch of the 'compute' project

The previous error disappeared but it was significantly slower than before:
1.
array sortedDistances;
array indices;
sort(sortedDistances, indices, distances, 0);
took 204 seconds

where as
sortedDistances = sort(distances, 0);
took 4 seconds

2. Had two failed tests while the develop branch of 'compute' was used:
105 - Test_sort_by_key_opencl (Failed)
111 - Test_sort_index_opencl(Failed)

**Comment by shehzan10** [comment]
We are aware of the tests failing. This is because sort_index and sort_by_key test data was generated using stable sort and the OpenCL implementation does not have stable sort yet.

However, this does not mean that the sort api is failing. It is simply a mismatch with the test data.

**Comment by xyang2013** [comment]
Thanks Shehzan. I think the sort API is working but the performance was too slow. The commercial version took only 3 seconds to complete (Windows + CUDA backend).

**Comment by shehzan10** [comment]
Yes we are aware of this issue as well. We are using a sequential form of sort (from thrust/Boost.Compute) for higher dimensions. That is for all columns (and higher), we are running the sort kernel in a for-loop.
We will soon implement a full kernel for this.

**Comment by xyang2013** [comment]
I see. Thank you.

**Comment by pavanky** [comment]
@xyang2013 The CUDA backend should not be slower than before. The performance should be similar. The OpenCL backend currently uses Boost.Compute. They are in the process of re-writing their sort functions which should make everything slightly faster.

Are you seeing slow downs on the CUDA side of things as well ?

**Comment by xyang2013** [comment]
Thanks Pavanky. What do you mean by slightly faster? For this sorting, the difference is huge.

**Comment by pavanky** [comment]
@xyang2013 Are you talking about the CUDA backend or the OpenCL backend ?

**Comment by xyang2013** [comment]
Ran it on my laptop with an Nvidia graphic card:

1. Ran OpenCL code for the first time: 204 seconds
2. Second time: 13.6108 seconds
3. Switched to Nvidia backend (got out of memory error which I did not have with version 2.1). Also v2.1 took 3s to complete.

**Comment by pavanky** [comment]
@xyang2013 Thanks for clarifying this. 

Regarding OpenCL: In the OpenCL backend kernels are compiled and cached in the first run. It looks like for sort it is taking an extraordinary amount of time. I'll look into this. That being said, the library we depend (Boost.Compute) is rewriting their code for sort. Hopefully this will reduce the amount of time.

As for the CUDA backend, that is definitely a  bug. Can you paste a stand alone github gist that we can use to reproduce / fix the issue ?

**Comment by pavanky** [comment]
@xyang2013 I created #329 for the issues (out of memory) you are seeing in the CUDA backend. Let us keep this issue about OpenCL for now.

**Comment by pavanky** [comment]
@xyang2013 Can you check to see if #329 is resolved now ?

**Comment by pavanky** [comment]
Looks like this is no longer an issue.
