### ISSUE TITLE
Compiling clBLAS

### ISSUE THREAD

**Issue by xyang2013** [arrayfire/arrayfire#292]
It might not be the right area to raise this issue. Anyways, I tried to build clBLAS and got a make error:

[ 20%] Building C object library/CMakeFiles/clBLAS.dir/tools/tune/storage_data.c.o
make[2]: *** No rule to make target `/opt/AMDAPPSDK-3.0-0-Beta/lib/x86_64/libOpenCL.so', needed by `library/libclBLAS.so.2.3.0'.  Stop.
make[1]: *** [library/CMakeFiles/clBLAS.dir/all] Error 2
make: *** [all] Error 2

When CMake was configured, it was able to identify libOpenCL.so:
Found OPENCL: /opt/AMDAPPSDK-3.0-0-Beta/lib/x86_64/libOpenCL.so

**Comment by shehzan10** [comment]
I just tried this at my end by installed APP SDK 3.0 and it seemed to work fine. I used the commands
```
cmake ../src/ -DBUILD_KTEST=OFF -DBUILD_TEST=OFF -DOPENCL_INCLUDE_DIRS=/opt/AMDAPPSDK-3.0-0-Beta/include -DOPENCL_LIBRARIES=/opt/AMDAPPSDK-3.0-0-Beta/lib/x86_64/libOpenCL.so
make install
```

Would you mind trying those and let me know how it goes?
Also which linux distribution are you running?

**Comment by xyang2013** [comment]
Thank you. That is my work computer. I will try it on Monday. The OS is Ubuntu 14.04

**Comment by xyang2013** [comment]
I got it to work. It was due to a broken link.

**Comment by cmyr** [comment]
I had this same issue, and it was also a broken link: the correct target was in `$AMDAPPSDKROOT/lib/x86_64/sdk`. after `ln -sf sdk/libOpenCL.so.1 libOpenCL.so` make install worked correctly.
