### ISSUE TITLE
API change of 'seq' between ArrayFire 2.1 and 3.0 / beta

### ISSUE THREAD

**Issue by bkloppenborg** [arrayfire/arrayfire#294]
The definition of the sequence-generating function, `seq` has undergone an API change between ArrayFire 2.1 and the open source (beta / 3.0) that should be advertised as it WILL break code that was written for the old ArrayFire.

The old (2.1 and earlier) API of `seq` was defined as follows:

```C++
seq (double first, double last)
seq (double first, double inc, double last)
```

whereas in the new Open Source library (beta / 3.0) the constructor is 

```C++
seq(double begin, double end, double step = 1);
```

notice that the position of the increment / step argument has changed.

**Comment by shehzan10** [comment]
@bkloppenborg  have we fixed this?

**Comment by bkloppenborg** [comment]
No. This is an API change that MUST be noted in the 3.0 release notes. It (probably) will break some AF 2.x code.

**Comment by pavanky** [comment]
This is documented and pushed out in 3.0
