### ISSUE TITLE
API change of 'fftN' between ArrayFire 2.1 and 3.0 / beta

### ISSUE THREAD

**Issue by bkloppenborg** [arrayfire/arrayfire#296]
All FFT functions have underwent an API change between ArrayFire 2.1 and the open source edition of ArrayFire (beta / 3.0)

The 2.1 API had signiatures similar to the following:

```
array af::fft(const array & , int 	pad = -1)
```

whereas the new signature is 

```
array fft(const array& in, double normalize, dim_type odim0=0);
```

This appears to apply to `fft`, `fft2`, `fft3`, `ifft`, `ifft2`, and `ifft3`.

**Comment by pavanky** [comment]
@bkloppenborg 

API has not changed. We added an **additional** function that takes in the normalize parameter.
