### ISSUE TITLE
[Question] When will 3.7.2 be released?

### ISSUE THREAD

**Issue by svenstaro** [arrayfire/arrayfire#2971]
Hey, currently arrayfire 3.7.1 doesn't build against cuda 11 and that's blocking the rebuild in Arch Linux. I'm curious as to whether there's going to be a 3.7.2 with the cuda 11 fix soon or whether I'm better off building from git master (which I'd really rather not do).

**Comment by umar456** [comment]
We have uploaded the binaries to the website and will be announcing the release tomorrow morning. The current v3.7 branch will be tagged as the 3.7.2 release.

**Comment by svenstaro** [comment]
That's great! Thanks. I'll need a tag optimally but the news is good already.

**Comment by 9prady9** [comment]
@svenstaro We have the tag ready now. please check it out.

**Comment by svenstaro** [comment]
Compiles fine!
