### ISSUE TITLE
af::randn creates duplicates with CUDA backend [BUG]

### ISSUE THREAD

**Issue by willat343** [arrayfire/arrayfire#2972]
When creating large af::arrays with af::randn, the resulting sequence is not a truly random sequence, but in fact contains at least 2 of every number for large arrays.

Description
===========

* I originally became aware of the issue because I was listening to sequence, expected white noise however it had a distinct "harsh" audio quality compared to af::randu and using my workaround, this quality disappeared. Testing with an array of length 32768, I found that not a single number in the sequence was present an odd number of times, but some multiple of 2. I was able to verify this with a very small bin histogram plot of the data. I'm using the CUDA backend with a 2080.
* My theory: The CUDA backend generates this sequence by creating blocks of normally distributed random numbers in many threads and then recombines the data together, BUT each of these threads appears to be initiated with the same seed, and therefore the random sequences in the threads are the same. Possible then a fix is to set different seeds in each thread.
* I originally produced this error on 3.6.2 but then confirmed the issue is indeed still present in 3.7.2.
* I used the official installers to install arrayfire.
* I have reproduced this error using all three Random Engines; PHILOX, MERSENNE and THREEFLY.
* As a workaround, I am creating many blocks of size 128 and using af::join to combine them, with each block having a different random seed. This is obviously slow (by ~100 times on my machine).
* I have comfirmed that af::randu does not seem to suffer the same issue.
* This is very reproducible - it always occurs.
* I've put a screenshot below. Top left is the raw signal with a moving average in yellow. Top right is a fft done in matlab which seems somewhat suspicous. Bottom left is the clincher - histogram with tiny tiny bin width showing that each number occurs in a multiple of 2 (possibly pairs)

![arrayfire-randn-32768-points](https://user-images.githubusercontent.com/9509635/87372108-1daa7f00-c5ca-11ea-92b4-3c1caf24d969.png)

Reproducible Code and/or Steps
------------------------------

* `af::array my_array = af::randn(32768, f32);`
* Plot a histogram (e.g. with small bin size) to see even number in every bin.

System Information
------------------

* 3.7.2 and 3.6.2 tested
* Output of `nvidia-smi --query-gpu="name,memory.total,driver_version" --format=csv -i 0`: `name, memory.total [MiB], driver_version GeForce RTX 2080 SUPER, 7981 MiB, 440.100`

Checklist
---------

- [x ] Using the latest available ArrayFire release
- [x ] GPU drivers are up to date

**Comment by umar456** [comment]
Hey @willat343,

Thanks for bringing this to our attention and creating a detailed issue. We will look into this and get back to you in a day or so.

**Comment by battledj** [comment]
Hi @umar456 ,
Just wondering if anyone has had time to review the situation with af::randn?

**Comment by umar456** [comment]
I tried recreating this on my end using the reproduction steps. Here is the code I used and the output:

```
TEST(Random, randn) {
    array a = af::randn(32768, f32);
    af_print(af::histogram(a, 40));
    af_print(sum(af::histogram(a, 40)));
}
```

```
af::histogram(a, 40)
[40 1 1 1]
         2 
         0 
         1 
         2 
        10 
        18 
        21 
        60 
       105 
       139 
       223 
       424 
       628 
       767 
      1156 
      1530 
      1889 
      2186 
      2513 
      2691 
      2911 
      2810 
      2472 
      2389 
      2024 
      1658 
      1337 
       908 
       656 
       466 
       309 
       194 
       122 
        71 
        40 
        12 
         8 
        10 
         2 
         4 

sum(af::histogram(a, 40))
[1 1 1 1]
     32768 
```

There are several odd bins along with the even bins. I am not sure if this is the best way to reproduce the error because we are performing a histogram on floating point values. I would assume a wide range of values would fall within the bin. I will need to investigate further to identify the issue you are experiencing.

**Comment by willat343** [comment]
Hi @umar456, thanks for getting back to me. I reproduce the same results with your test, and it seems I was wrong about every datapoint being a duplicate. Digging a bit deeper, I found that _almost_ every datapoint is a duplicate. To demonstrate this here is my arrayfire code:
```
af::array arr = af::randn(32768, f32);
af::array hist = af::histogram(arr, 32768);
af::array hist_of_hist = af::histogram(hist, 32, -8, 8);
af_print(hist_of_hist);
af_print(sum(hist_of_hist));
af::Window window(1600, 800, "histogram of histogram");
window.hist(hist_of_hist, -8, 8);
```

Code explanation:
- create normally distributed array
- create histogram with same number of bins as elements in the array (this guarantees few elements in each bin)
- the af::Window::hist() function is not very informative on this "hist" array, so perform a histogram on the histogram, effectively counting the frequency of bin sizes
- do some printing and display on a window

Result:
Yes there are very occasional instances where an odd number is found, however ~99% of the histogram bins either have 0, 2, 4 or 8+ elements - indicating that there are duplicates.
![image](https://user-images.githubusercontent.com/9509635/88612747-3e48fd80-d0cf-11ea-90b6-78194ab4f2a8.png)

Further investigation:
Saving this data to a csv file with the following code:
```
float *data_host = arr.host<float>();
std::ofstream file;
file.open("randn.csv");
for (int i = 0; i < 32768; ++i) {
    file << data_host[i] << ", ";
}
file.close();
```
Then in matlab (a similar approach could be done in excel):
```
data = csvread("randn.csv");
subplot(1,2,1);
H = histogram(data, 32768);
subplot(1,2,2);
H2 = histogram(H.Values, 'BinWidth', 0.5);
```

Same result:
![image](https://user-images.githubusercontent.com/9509635/88613489-eb704580-d0d0-11ea-83c3-b05ffd8b5d04.png)

**Comment by umar456** [comment]
The hist array is composed of integer values. The hist_of_hist array array has 32 bins with values between -8 to +8. This means that every other bin is storing half values which wouldn't be possible. Slightly changing your code so that there are 17 bins gives me this result:

```
    af::array arr          = af::randn(32768, f64);
    af::array hist         = af::histogram(arr, 32768);
    af::array hist_of_hist = af::histogram(hist, 17, -8, 8);
    af_print(hist);
    af_print(hist_of_hist);
    af_print(sum(hist_of_hist));
```

```
hist_of_hist
[17 1 1 1]
         0 
         0 
         0 
         0 
         0 
         0 
         0 
         0 
     19554 
      4761 
      3170 
      2272 
      1432 
       862 
       398 
       193 
       126 
```

Which seems ok.

**Comment by willat343** [comment]
Running that code myself yields a different result:
```
af::array arr = af::randn(32768, f32);
af::array hist = af::histogram(arr, 32768);
af::array hist_of_hist = af::histogram(hist, 17, -8, 8);
af_print(hist_of_hist);
window.hist(hist_of_hist, -8, 8);
```
gives:
```
hist_of_hist
[17 1 1 1]
         0 
         0 
         0 
         0 
         0 
         0 
         0 
         0 
     22827 
       348 
      5208 
       331 
      2343 
       167 
       949 
        83 
       512
```
And the plot:
![17-bins](https://user-images.githubusercontent.com/9509635/88742203-f97f9e00-d184-11ea-81d4-2e2ebff1a0a5.png)

Could the difference in results be related to number of threads being spun up or the hardware backend?

**Comment by willat343** [comment]
I just noticed that you used the `f64` data type instead of the `f32` data type and i get your normal results with `f64`!!!
```
hist_of_hist
[17 1 1 1]
         0 
         0 
         0 
         0 
         0 
         0 
         0 
         0 
     39453 
      9080 
      6357 
      4493 
      2971 
      1726 
       828 
       373 
       255
```

So issue lies with `f32`?

**Comment by umar456** [comment]
Interesting.

Running this again on my T2000 with f32 gives me the correct results:

```
    af::array arr          = af::randn(32768, f32);
    af::array hist         = af::histogram(arr, 32768);
    af::array hist_of_hist = af::histogram(hist, 17, -8, 8);
    af_print(hist_of_hist);
    af_print(sum(hist_of_hist));
```

```
seed: 0
hist_of_hist
[17 1 1 1]
         0 
         0 
         0 
         0 
         0 
         0 
         0 
         0 
     18822 
      5290 
      3516 
      2334 
      1453 
       799 
       347 
       134 
        73 

sum(hist_of_hist)
[1 1 1 1]
     32768 
```

Perhaps is a card specific bug. 

# System Info
```
nvidia-smi --query-gpu="name,memory.total,driver_version" --format=csv -i 0
```
```
name, memory.total [MiB], driver_version
Quadro T2000, 3914 MiB, 450.57
```

Just noticed your histogram's values are much larger. Did you change the input size in the last run?

**Comment by umar456** [comment]
Its strange because the architectures are the same(compute 7.5).

Of course if the histogram shows correct results doesn't mean there isn't an underlying problem. This isn't a very good way of measuring the quality of a Random number generator. We have a couple of Chi square tests but they only test the randu function. It will need to be modified to test the randn function as well.

**Comment by willat343** [comment]
> Just noticed your histogram's values are much larger. Did you change the input size in the last run?

I think i had increased the input size while messing about, but can confirm the erroneous output with the 32768 input size:
```
af::array arr = af::randn(32768, f32);
af::array hist = af::histogram(arr, 32768);
af::array hist_of_hist = af::histogram(hist, 17, -8, 8);
af_print(hist_of_hist);
af_print(af::sum(hist_of_hist));
```
```
hist_of_hist
[17 1 1 1]
         0 
         0 
         0 
         0 
         0 
         0 
         0 
         0 
     22827 
       348 
      5208 
       331 
      2343 
       167 
       949 
        83 
       512 

af::sum(hist_of_hist)
[1 1 1 1]
     32768
```

We are working on different hardware so that is my best guess as to why we are seeing different output. Possibly it is bug specific to this GPU, or 8GB of GPU memory, or something else.
```
nvidia-smi --query-gpu="name,memory.total,driver_version" --format=csv -i 0
```
```
name, memory.total [MiB], driver_version
GeForce RTX 2080 SUPER, 7981 MiB, 440.100
```

**Comment by umar456** [comment]
Ok. I was able to reproduce your results on my machine and found the issue. I will push a PR soon.

**Comment by willat343** [comment]
Great to hear! Out of curiousity, what was the root cause?

**Comment by umar456** [comment]
That https://github.com/arrayfire/arrayfire/blob/master/src/backend/cuda/kernel/random_engine.hpp#L256

The third and fourth parameters to that function should be r3 and r4 instead of r1 and r2.
