### ISSUE TITLE
[Perf] Slow approx1 performance in v3.7.x

### ISSUE THREAD

**Issue by greennbeans** [arrayfire/arrayfire#2975]
The performance of the approx1 function is much slower in ArrayFire v3.7.x compared to v3.6.x - I am seeing slow downs of nearly 20x which makes v3.7.x unusable for my application

Description
===========

The behaviour occurs every time on my system. The performance is is present in both CUDA and OpenCL backends (which have similar performance). There appears to be less performance difference in the CPU backend, but it is so slow it doesn't matter. 

The slow behaviour has been observed in v3.7.0, and v3.7.1 as well.
The comparisons are done on official (Windows) installers. Also tested with a self built 3.6.4 based built.

For my application, I don't have a work around - I would like to use v3.7.x as it fixes a number of bugs that I have
run into on v3.6.4, but the performance is unusable for my application.

Reproducible Code
-----------------

The code below shows the performance difference.

   ```
 af::info();
    af::array x = af::constant(0, 2048, 364, 16, af::dtype::f32);
    af::array pos = af::range(af::dim4(2048), 0, af::dtype::f32);
    for (int l = 0; l < 20; l++)
    {
        af::timer start1 = af::timer::start();
        for (int i = 0; i < 1000; i++)
        {
            af::array res = af::approx1(x, pos, AF_INTERP_CUBIC);
            res.eval();
        }
        printf("elapsed seconds: %g\n", af::timer::stop(start1));
    }
```

Timing information for 3.7.2:

ArrayFire v3.7.2 (CUDA, 64-bit Windows, build 218dd2c)
Platform: CUDA Runtime 10.1, Driver: 11000
[0] GeForce RTX 2060, 6144 MB, CUDA Compute 7.5
elapsed seconds: 0.0288055
elapsed seconds: 0.009874
elapsed seconds: 0.00956
elapsed seconds: 3.04784
elapsed seconds: 8.62203
elapsed seconds: 8.73821
elapsed seconds: 8.61206
elapsed seconds: 8.71591
elapsed seconds: 8.62403
elapsed seconds: 9.17842
elapsed seconds: 8.80729
elapsed seconds: 8.67381
elapsed seconds: 8.53085
elapsed seconds: 8.80485
elapsed seconds: 7.90569
elapsed seconds: 9.40247
elapsed seconds: 8.70725
elapsed seconds: 8.63229
elapsed seconds: 8.67862
elapsed seconds: 8.56963

For 3.6.4

ArrayFire v3.6.4 (CUDA, 64-bit Windows, build 1b8030c)
Platform: CUDA Toolkit 10.0, Driver: 11000
[0] GeForce RTX 2060, 6144 MB, CUDA Compute 7.5
elapsed seconds: 0.26505
elapsed seconds: 0.004777
elapsed seconds: 0.0048639
elapsed seconds: 0.217955
elapsed seconds: 0.499306
elapsed seconds: 0.482685
elapsed seconds: 0.484874
elapsed seconds: 0.483749
elapsed seconds: 0.484528
elapsed seconds: 0.482918
elapsed seconds: 0.481947
elapsed seconds: 0.480843
elapsed seconds: 0.481439
elapsed seconds: 0.4833
elapsed seconds: 0.499097
elapsed seconds: 0.481043
elapsed seconds: 0.485016
elapsed seconds: 0.482298
elapsed seconds: 0.495527
elapsed seconds: 0.481028

Hence there is about a 20x performance different 9seconds vs 0.5 seconds.

Also note the first iterations are faster (I am not sure why)

System Information
------------------
ArrayFire Version: v3.7.2
Device: RTX2060 (Both CUDA and OpenCL)
Operating System: Windows 10 2004
Driver version: 11000

Checklist
---------
- [ X] I have read [timing ArrayFire](http://arrayfire.org/docs/timing.htm)

**Comment by 9prady9** [comment]
I was able to reproduce the performance drop. I slightly modified your code snippet to ensure everything before the loop is finished and I m printing the 1000 run avg instead of total time to get an idea of kernel runtime. 

approx1 on (364*16 = 5824) vectors of size 2048.
```cpp
        array x = constant(0, 2048, 364, 16, f32);
        array pos = range(af::dim4(2048), 0, f32);
        printf("Approx1 on 2048x364x16 array with 1d pos\n");
        af::sync();

        for (int l = 0; l < 20; l++) {
            af::timer start1 = af::timer::start();
            for (int i = 0; i < 1000; i++) {
                af::array res = af::approx1(x, pos, AF_INTERP_CUBIC);
                res.eval();
            }
            af::sync();
            printf("trial %d -> elapsed seconds(1000 run avg): %g\n", l, af::timer::stop(start1)/1000.0f);
        }
```
ouput on gtx 1060 over cuda backend
```
ArrayFire v3.7.2 (CUDA, 64-bit Linux, build 218dd2c99)
Platform: CUDA Runtime 10.2, Driver: 450.57
[0] GeForce GTX 1060 3GB, 3012 MB, CUDA Compute 6.1
Approx1 on 2048x364x16 array with 1d pos
trial 0 -> elapsed seconds(1000 run avg): 0.0137677
trial 1 -> elapsed seconds(1000 run avg): 0.0141825
trial 2 -> elapsed seconds(1000 run avg): 0.0138131
trial 3 -> elapsed seconds(1000 run avg): 0.0137778
trial 4 -> elapsed seconds(1000 run avg): 0.0139673
trial 5 -> elapsed seconds(1000 run avg): 0.0135862
trial 6 -> elapsed seconds(1000 run avg): 0.0134919
trial 7 -> elapsed seconds(1000 run avg): 0.013492
trial 8 -> elapsed seconds(1000 run avg): 0.0134923
trial 9 -> elapsed seconds(1000 run avg): 0.0134937
trial 10 -> elapsed seconds(1000 run avg): 0.013493
trial 11 -> elapsed seconds(1000 run avg): 0.0134916
trial 12 -> elapsed seconds(1000 run avg): 0.0134903
trial 13 -> elapsed seconds(1000 run avg): 0.013493
trial 14 -> elapsed seconds(1000 run avg): 0.0134924
trial 15 -> elapsed seconds(1000 run avg): 0.0134918
trial 16 -> elapsed seconds(1000 run avg): 0.0134919
trial 17 -> elapsed seconds(1000 run avg): 0.0134919
trial 18 -> elapsed seconds(1000 run avg): 0.0134941
trial 19 -> elapsed seconds(1000 run avg): 0.0134951
```
With 3.6.4 I am getting an avg runtime of 0.0012. I am looking into it, thank you for reporting it.

**Comment by greennbeans** [comment]
I have managed to do some more tests by building custom versions of ArrayFire. I was able to confirm that the code changes for the new feature "Adding the approx1 and approx2 along any given dimension for all backends" #2297  are responsible for the performance change, and not anything else. The changes to the approx1 kernel slows down about 3.5x for me, and the Interp kernel about 5 times. 

I don't understand why these seemingly small changes have such a huge impact, but I found some success by changing the xdim argument to a template parameter.

**Comment by 9prady9** [comment]
@greennbeans Yes, that is correct. I have already narrowed it down to those changes. And you are correct again, the changes seem trivial upfront, but somehow they increased run time - I think some 64 bit numbers arithmetic is the cause, I am still investigating. I am running through the profiler to exactly identify the source of problem.

**Comment by pavanky** [comment]
Curious. That change was from 2018.  Would it not be part of 3.6 ?

**Comment by 9prady9** [comment]
> Curious. That change was from 2018.  Would it not be part of 3.6 ?

I checked the kernels from 3.6.4 and 3.7.2, 3.6.4 doesn't involve dim for interpolation and associated changes.

**Comment by 9prady9** [comment]
@umar456 @pavanky Found the source of the perf regression. Majority of it (almost 50% of increase in runtime) comes from mainly because of load or arithmetic instructions that involve `xdim` which is runtime argument - earlier it wasn't there as dimension of approx was fixed. Rest of the increase is caused by other instructions that involve stride multiplication along dimension 0, the extra multiplications with flags (`is_*_off` variables). Cleaning up the those extra calculations and moving `xdim` to be a compile time constant, brought the run time similar to the one from 3.6.* versions.

This should be a problem with approx2 also I believe as it uses similar logic w.r.t `xdim`.
