### ISSUE TITLE
[Build] Docker: CUDA11 image build fails with 'nvcc fatal error'

### ISSUE THREAD

**Issue by pthon** [arrayfire/arrayfire#2976]
As v3.7.2 supports CUDA11 I tried to update my docker container accordingly, however, the build fails with: 'nvcc fatal   : Unsupported gpu architecture 'compute_30''

Description
===========
I tried building arrayfire 3.7.2 with the newest nvidia image (nvidia/cuda:11.0-devel-ubuntu20.04).
During compilation, I got the  error below.
The versions tested are listed in the dockerfile.

Is there an officially maintained arrayfire Dockerfile?
I just found this one https://github.com/arrayfire/arrayfire-docker from 2017 which does not compile for current arrayfire versions.

Error Log
---------

```
nvcc fatal   : Unsupported gpu architecture 'compute_30'
CMake Error at af_cuda_static_cuda_library_generated_sparse_arith.cu.o.Release.cmake:220 (message):
  Error generating
  /arrayfire/build/src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir//./af_cuda_static_cuda_library_generated_sparse_arith.cu.o
```

Build Environment
-----------------
Docker image:
```

FROM nvidia/cuda:11.0-devel-ubuntu20.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
    vim \
    htop \
    g++ \
    libcurl4-openssl-dev \
    libglfw3-dev \
    libglu1-mesa-dev \
    build-essential \
    clinfo \
    git \
    cmake \
    libfreeimage-dev \
    libboost-all-dev \
    libfftw3-dev \
    libfontconfig1-dev \
    libfreeimage-dev \
    liblapack-dev \
    liblapacke-dev \
    libopenblas-dev \
    ocl-icd-opencl-dev \
    opencl-headers \
    wget \
    xorg-dev && \
    rm -rf /var/lib/apt/lists/*


RUN git clone --recursive https://github.com/arrayfire/arrayfire.git -b v3.7.2 && \
    cd arrayfire && mkdir build && cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release && \
    make -j && \
    make install && \
    ldconfig && \
    rm -rf ../../arrayfire

```

**Comment by 9prady9** [comment]
@pthon NVIDIA dropped compute  3.0, 3.2  from CUDA 111 onwards, hence the error. This is not a code error.

**Comment by pthon** [comment]
Ok, thanks for the answer. is there a workaround then or should i go with CUDA10?

**Comment by 9prady9** [comment]
There isn't anything we can do as NVIDIA dropped the support. You have to switch back to 10.2, I  don't see any other way.
