### ISSUE TITLE
Make sure math_ptx is generated using the cuda toolkit present on the system. 

### ISSUE THREAD

**Issue by bkloppenborg** [arrayfire/arrayfire#298]
Using ArrayFire a9074ae004827d46112e2294b65c40c8c7d56a1a the following code generates a JIT compilation on the CUDA backend but completes correctly on both the CPU and OpenCL backends. I am using the NVIDIA 331.113 driver installed from the package manager on Ubuntu 14.10 x86_64.

```
    unsigned int size = 64;
    try{
         array A = seq(0, size - 1, 1);
         array output = fft(A, 1.0);
    } catch (af::exception & e) {
        cout << e.what() << endl;
    }
```
The error message is as follows:

```
Press ENTER or type command to continue
Internal error in /home/bkloppenborg/workspace/arrayfire/src/backend/cuda/jit.cpp(300):
CU Error (209)
ptxas application ptx input, line 7; fatal   : Unsupported .version 4.1; current version is '4.0'
ptxas fatal   : Ptx assembly aborted due to errors

/home/bkloppenborg/workspace/arrayfire/src/api/cpp/fft.cpp:19: AF_ERROR 1
```

**Comment by bkloppenborg** [comment]
@shehzan10 asked me to try this example:

'''
    try{
         array A = seq(64);
         A.eval();
         array output = fft(A, 1.0);
    } catch (af::exception & e) {
        cout << e.what() << endl;
    }
'''

The code fails at A.eval() on the CUDA backend with the same error message as before.

**Comment by pavanky** [comment]
@bkloppenborg I have the same laptop. Both codes works just fine on devel. The errors you are seeing may have to do with you using an older version of CUDA on your machine. Can you go to `src/backend/cuda/ptx` and run the following commands ?

```
make clean
make -j4
```

**Comment by bkloppenborg** [comment]
@pavanky your instructions fixed my issue. I have added a comment about this on the wiki.

**Comment by shehzan10** [comment]
How about maintaining different branches on the ptx repo? That way Windows users using other CUDA versions don't face the problem.

**Comment by pavanky** [comment]
@shehzan10 That sounds about right. I will talk to @bkloppenborg and do it

**Comment by bkloppenborg** [comment]
As a followup, if you have this issue you can clone the `math_ptx` branch for CUDA 6.0 from here:

```
git clone https://github.com/arrayfire/math_ptx arrayfire/src/backend/cuda/ptx
cd arrayfire/src/backend/cuda/ptx
git checkout cuda_60
```

and recompile ArrayFire.
