### ISSUE TITLE
[BUG] Compilation error of unified on opencl

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#2989]
Compilation error:
cmake  -DAF_BUILD_OPENCL=OFF ..
...
-- Could NOT find OpenCL (missing: OpenCL_LIBRARY OpenCL_INCLUDE_DIR) 
-- Could NOT find OpenCL (missing: OpenCL_LIBRARY OpenCL_INCLUDE_DIR) (Required is at least version "1.2")
...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wtambellini/repos/arrayfire/release
...
make
...
In file included from /home/wtambellini/repos/arrayfire/src/api/unified/opencl.cpp:13:0:
/home/wtambellini/repos/arrayfire/include/af/opencl.h:14:19: fatal error: CL/cl.h: No such file or directory
 #include <CL/cl.h>
                   ^
compilation terminated.

Description
===========
Did you build ArrayFire yourself or did you use the official installers
myself
Which backend is experiencing this issue? (CPU, CUDA, OpenCL)
unified
Do you have a workaround?
no
Can the bug be reproduced reliably on your system?
yes
compilation of unified

Reproducible Code and/or Steps
------------------------------
Try to build AF on a linux machine wihtout any opencl header installed 

No surprise: the unified lib tries to build  src/api/unified/opencl.cpp even if opencl not found.
Any way to skip src/api/unified/opencl.cpp if no opencl found ?

System Information
------------------
1. ArrayFire version: today master
2. Devices installed on the system: Quadro RTX 3000
3. (optional) Output from the af::info() function if applicable.
4. Output from the following scripts:

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS (whitehaven-mlk X84)
Release:	18.04
Codename:	bionic

name, memory.total [MiB], driver_version
Quadro RTX 3000, 5934 MiB, 440.33.01

clinfo not found.

Checklist
---------
- [X ] Using the latest available ArrayFire release
- [X ] GPU drivers are up to date

**Comment by 9prady9** [comment]
Should be addressed by #2990
