### ISSUE TITLE
[BUG] NVRTC Error(7): NVRTC_ERROR_BUILTIN_OPERATION_FAILURE 

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#2994]
NVRTC Error(7): NVRTC_ERROR_BUILTIN_OPERATION_FAILURE 

Description
===========
* Did you build ArrayFire yourself or did you use the official installers
myself
* Which backend is experiencing this issue? (CPU, CUDA, OpenCL)
cuda
* Do you have a workaround?
no
* Can the bug be reproduced reliably on your system?
yes on AWS G4 (Tesla T4) with drivers 440.95.01, AF built with cuda 10.2
* A clear and concise description of what you expected to happen.
no nvrtc failure
* Run your executable with AF_TRACE=all and AF_PRINT_ERRORS=1 environment
  variables set.
ArrayFire Exception (Internal error:998):
In function cuda::Kernel cuda::buildKernel(int, const string&, const string&, const std::vector<std::basic_string<char> >&, bool)
In file src/backend/cuda/nvrtc/cache.cpp:286
0# 0x00007F8CCD3B735B in bin/libafcuda.so.3
1# 0x00007F8CCD3B98D5 in bin/libafcuda.so.3
2# 0x00007F8CCCFF25A8 in bin/libafcuda.so.3
3# 0x00007F8CCCFF390D in bin/libafcuda.so.3
4# af_join in bin/libafcuda.so.3
5# af_join in bin/libaf.so.3
6# af::join(int, af::array const&, af::array const&) in bin/libaf.so.3

Reproducible Code and/or Steps
------------------------------
coming

System Information
------------------
Please provide the following information:
1. ArrayFire version
ArrayFire v3.8.0 (CUDA, 64-bit Linux, build d087e32b) Platform: CUDA Runtime 10.2, Driver: 440.95
2. Devices installed on the system
T4
4. Output from the following scripts:

lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.8.2003 (Core)
Release:	7.8.2003
Codename:	Core

nvidia-smi --query-gpu="name,memory.total,driver_version" --format=csv -i 0
name, memory.total [MiB], driver_version
Tesla T4, 15109 MiB, 440.95.01

Checklist
---------
- [ ] Using the latest available ArrayFire release
- [X] GPU drivers are up to date (for cuda 10.2)

**Comment by umar456** [comment]
Can you move ~/.arrayfire to ~/.arrayfire_bak and try again? Also can you try the latest master?

**Comment by WilliamTambellini** [comment]
Ok tks @umar456 , trying...
I built with : CUDA_architecture_build_targets: 6.0;6.1;7.0;7.5
Should I also add 7.5+PTX ?

**Comment by 9prady9** [comment]
Tesla T4 is `7.5`. Just that compute version should do fine for debugging purposes and it would faster build relatively.

**Comment by 9prady9** [comment]
@WilliamTambellini We pushed a fix to nvrtc compute check just today. please pull latest master and try again. ty.

**Comment by 9prady9** [comment]
@WilliamTambellini Is this issue still happening with lastest master ?

**Comment by WilliamTambellini** [comment]
No, thanks.
