### ISSUE TITLE
[Perf] [NVIDIA Jetson Xavier NX] 

### ISSUE THREAD

**Issue by HoneyPatouceul** [arrayfire/arrayfire#3004]
Sorry if it is a naïve question, but I'm seeing surprizing results with make test on a NVIDIA Jetson Xavier NX running L4T R32.4R.3. I have successfully built arrayfire master (1405a944) with boost 1-70 headers. according to:
https://github.com/arrayfire/arrayfire/wiki/Build-Instructions-for-Linux 

Got test results [here](https://forums.developer.nvidia.com/t/arrayfire-on-jetson-tx2/147801/6?u=honey_patouceul).

Is such difference from unit test to test suite expected ?

Thanks.

**Comment by syurkevi** [comment]
The tests in [test/convolve.cpp](https://github.com/arrayfire/arrayfire/blob/master/test/convolve.cpp) and the [examples/getting_started/convolve.cpp](https://github.com/arrayfire/arrayfire/blob/master/examples/getting_started/convolve.cpp) are different. Neither is intended to be used as a benchmark. You'll most likely need to write your own for the specific problems you are targetting. If you need a more rigorous benchmarking suite, @umar456  has a good starting point using google/Benchmark here: https://github.com/umar456/arrayfire-benchmarks.

**Comment by HoneyPatouceul** [comment]
Sorry for the confusion and thanks for your useful comments.
