### ISSUE TITLE
Moving SIFT to main repo

### ISSUE THREAD

**Issue by Zultanic** [arrayfire/arrayfire#3007]
Thank you for this awesome library. I would like to know however if there is any plan to move the SIFT algorithm out of non free since it seems that the patent has expired on it. It looks like opencv has already moved the algorithm into the main repo  ([changelog](https://github.com/opencv/opencv/wiki/ChangeLog#version430)  and [issue](https://github.com/opencv/opencv/issues/16736)).
Sift is used a lot in computer vision and having a really fast gpu version easily available would be great.

**Comment by 9prady9** [comment]
@Zultanic Thanks for bringing this to our attention. We will look into it and take necessary steps.

**Comment by 9prady9** [comment]
https://patents.google.com/patent/US6711293B1/en
