### ISSUE TITLE
[BUG] Richardson-Lucy deconvolution

### ISSUE THREAD

**Issue by mtherezien** [arrayfire/arrayfire#3008]
I ran iterativeDeconv with the Richardson-Lucy algorithm and 10 iterations on an image and noticed artifacts that were not present when using the Mathematica implementation of the method. Namely:
- there's is a border a few pixels wide on the left and bottom edges of the image where the pixels are slightly off in value;
- the right edge of the image seems to be convolved with an amplified sine wave, going from a vertical band that's slightly too dark, to a band that's clearly too bright, to a black band at the edge.
- additionally, the entire deconvolved image gets shifted a few pixels to the left.

Attached below are the original blurred image, the output from Mathematica, and the output from arrayfire.

More details:
I have the 3.7.2 version of array fire, installed through the .exe file at array fire.org/download/.
I am using the CPU backend.
I am calling arrayfire from C#
I don't have a workaround, I haven't been able to run any of the other deconvolution algorithms. Looking into that now.
The issue happens consistently.

![Original](https://user-images.githubusercontent.com/62075151/91749518-703dfb80-eb76-11ea-8cd0-8ae403af051b.jpg)
![RL_Mathematica](https://user-images.githubusercontent.com/62075151/91749581-8a77d980-eb76-11ea-8c88-dd3185c5110b.png)
![RL_Arrayfire](https://user-images.githubusercontent.com/62075151/91749590-8ea3f700-eb76-11ea-9689-283908cd01d8.jpg)

**Comment by 9prady9** [comment]
@mtherezien I am the developer who worked on this function. Currently, I am sick and won't be able to look into it until another couple of weeks. We will update here as soon as we have a fix.

Thank you for reporting it.

Also, please share the information regarding below questions for my future reference.

- does the issue happen on all backends
- is with arrayfire installed via installer or have you built it yourself ? If built, please share the build dependencies used.

**Comment by 9prady9** [comment]
@mtherezien Please share the details of other arguments you passed to function. If possible, share a standalone snippet that you are using to generate arrayfire output. Thanks.

**Comment by mtherezien** [comment]
@9prady9 sorry about the late response. The test code I have calls the C++ function from C#, I'll try to put together a C++ snippet today.
In the meantime, the arguments I pass are:
 - the original image converted to ArrayFire array
 - the following kernel array converted to ArrayFire array
[CalculatePSFKernel.txt](https://github.com/arrayfire/arrayfire/files/5356476/CalculatePSFKernel.txt)
 - 10 for the number of iterations
 - 0.000005 for the relaxation factor
 - Richardson-Lucy for the method

**Comment by mtherezien** [comment]
@9prady9 I ran the same AF method directly from C++ and it does not exhibit the artifact. The original issue has to be on my end, my apologies.
