### ISSUE TITLE
[Perf] [OpenCl] Recompiling source code for AMD reduces drastically overhead for OpenCL

### ISSUE THREAD

**Issue by willyborn** [arrayfire/arrayfire#3009]
To optimize the obtained error in ML, I have to use smaller batch sizes.  For the provide example: neural network, a batch size of 48 is ideal.  The overhead increases enormously however.

By recompiling the af sources:
- Windows 10 1909
- VS 2017 (with provided solutions, no options changed)
- openblas
- AMDAPPSDK 3.0
- ArrayFire v3.8.0 (OpenCL, 64-bit Windows, build f2630727)
- Processor: A10 7870K with integrated GPU: [0] AMD: Spectre, 7211 MB

The major difference is related to copies between CPU and GPU.  (Task Manager, Performance, GPU, Copy graph).  With the recompiled version, almost no time is spent here with a much higher GPU occupation as a result.

![image](https://user-images.githubusercontent.com/70607676/92247868-1e73d900-eec8-11ea-95b4-4bd11aae5cfd.png)
Above you can see the total needed time to execute the "neural network" example with a batchsize varying from 32 up to 128.
3.7.2 af: timings with binaries installed through arrayfire installer
3.8 (recomp): timings with binaries installed after recompilation as described above

=============
Is there a reason, that the provided binaries are so much slower?

Thanks,
Willy Born

**Comment by umar456** [comment]
I believe this could have something to do with MKL and how it chooses kernels for blas operations. Try some of the suggestions at the following link and see if you get better results from the binaries:

https://www.pugetsystems.com/labs/hpc/How-To-Use-MKL-with-AMD-Ryzen-and-Threadripper-CPU-s-Effectively-for-Python-Numpy-And-Other-Applications-1637/
