### ISSUE TITLE
[Build] AF 3.7.2 nvcc fatal error

### ISSUE THREAD

**Issue by lfdmn** [arrayfire/arrayfire#3014]
I cannot build af_cuda_static_cuda_library_intermediate_link.o

Description
===========
The device is Jetson Xavier. I'm trying to update from 3.7.0 to 3.7.2

```
| FAILED: src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir/af_cuda_static_cuda_library_intermediate_link.o

nvcc fatal   : Value 'compute_72 --gpu-code=sm_72  --include-path /data/yocto/zeus/build-jetson-xavier/tmp/work/armv8a_tegra194-poky-linux/arrayfire/3.7.2-r0/recipe-sysroot/usr/local/cuda-10.0/include --library-path /data/yocto/zeus/build-jetson-xavier/tmp/work/armv8a_tegra194-poky-linux/arrayfire/3.7.2-r0/recipe-sysroot/usr/local/cuda-10.0/lib' is not defined for option 'gpu-architecture'

```

Build Environment
-----------------
Compiler version: gcc 7.4
Operating system: poky
Build environment:
```
    -DAF_BUILD_CPU=OFF \
    -DAF_BUILD_CUDA=ON \
    -DAF_BUILD_OPENCL=OFF \
    -DAF_BUILD_EXAMPLES=OFF \
    -DAF_BUILD_TEST=OFF \
    -DAF_WITH_GRAPHICS=OFF \
    -DCMAKE_BUILD_TYPE=Release \
    -DNATIVE_BIN_DIR=${WORKDIR}/recipe-sysroot-native/usr/bin \
    -DCUDA_architecture_build_targets=7.2 \
    -DcuDNN_INCLUDE_DIRS=${WORKDIR}/recipe-sysroot/usr/include/ \
```
CMake variables:

**Comment by 9prady9** [comment]
The error seems odd, it is treating compute flags and the next paths also as value of `gpu-architecture` flag. This definitely doesn't happen on regular non-jetson setup as I have ran clean builds very recently.

Can you please attach the whole build log. You can generate one with `make clean && VERBOSE=1 make` command from the build folder, avoid multiple threads as that may jumble up messages.

**Comment by lfdmn** [comment]
That's the case and it's not lying, see step 255:

```
[255/1121] cd /data/yocto/zeus/build-jetson-xavier/tmp/work/armv8a_tegra194-poky-linux/arrayfire/3.7.2-r0/arrayfire-3.7.2/src/backend/cuda && /data/yocto/zeus/build-jetson-xavier/tmp/work/armv8a_tegra194-poky-linux/arrayfire/3.7.2-r0/recipe-sysroot-native/usr/local/cuda-10.0/bin/nvcc "--gpu-architecture=compute_72 --gpu-code=sm_72  --include-path /data/yocto/zeus/build-jetson-xavier/tmp/work/armv8a_tegra194-poky-linux/arrayfire/3.7.2-r0/recipe-sysroot/usr/local/cuda-10.0/include --library-path /data/yocto/zeus/build-jetson-xavier/tmp/work/armv8a_tegra194-poky-linux/arrayfire/3.7.2-r0/recipe-sysroot/usr/local/cuda-10.0/lib" -gencode arch=compute_72,code=sm_72 -DOS_LNX -std=c++14 -Xcompiler -fPIC -Xcompiler -fvisibility=hidden --expt-relaxed-constexpr -I -DBOOST_CHRONO_HEADER_ONLY -DBOOST_COMPUTE_THREAD_SAFE -DBOOST_COMPUTE_HAVE_THREAD_LOCAL -DAF_CUDA -DCUDA_NO_HALF -lculibos -lcublas_static -lcufft_static -lcusparse_static -lcusolver_static -Xcudafe \"--diag_suppress=1427\" -DAFDLL -m64 -ccbin aarch64-poky-linux-g++ -dlink /data/yocto/zeus/build-jetson-xavier/tmp/work/armv8a_tegra194-poky-linux/arrayfire/3.7.2-r0/arrayfire-3.7.2/src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir//./af_cuda_static_cuda_library_generated_blas.cu.o /data/yocto/zeus/build-jetson-xavier/tmp/work/armv8a_tegra194-poky-linux/arrayfire/3.7.2-r0/arrayfire-3.7.2/src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir//./af_cuda_static_cuda_library_generated_cufft.cu.o /data/yocto/zeus/build-jetson-xavier/tmp/work/armv8a_tegra194-poky-linux/arrayfire/3.7.2-r0/arrayfire-3.7.2/src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir//./af_cuda_static_cuda_library_generated_fft.cu.o /data/yocto/zeus/build-jetson-xavier/tmp/work/armv8a_tegra194-poky-linux/arrayfire/3.7.2-r0/arrayfire-3.7.2/src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir//./af_cuda_static_cuda_library_generated_sparse.cu.o /data/yocto/zeus/build-jetson-xavier/tmp/work/armv8a_tegra194-poky-linux/arrayfire/3.7.2-r0/arrayfire-3.7.2/src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir//./af_cuda_static_cuda_library_generated_sparse_arith.cu.o /data/yocto/zeus/build-jetson-xavier/tmp/work/armv8a_tegra194-poky-linux/arrayfire/3.7.2-r0/arrayfire-3.7.2/src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir//./af_cuda_static_cuda_library_generated_sparse_blas.cu.o /data/yocto/zeus/build-jetson-xavier/tmp/work/armv8a_tegra194-poky-linux/arrayfire/3.7.2-r0/arrayfire-3.7.2/src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir//./af_cuda_static_cuda_library_generated_solve.cu.o -o /data/yocto/zeus/build-jetson-xavier/tmp/work/armv8a_tegra194-poky-linux/arrayfire/3.7.2-r0/arrayfire-3.7.2/src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir/./af_cuda_static_cuda_library_intermediate_link.o
```
[arrayfire_build_error.txt](https://github.com/arrayfire/arrayfire/files/5229994/arrayfire_build_error.txt)

Looking at all the afcuda_generated_*.cu.o.cmake.pre-gen and afcuda_generated_*.cu.o.Release.cmake files the CUDA_NVCC_FLAGS are set properly:

`set(CUDA_NVCC_FLAGS --gpu-architecture=compute_72 --gpu-code=sm_72 ...`

The issue seems to be in [build.ninja](https://github.com/arrayfire/arrayfire/files/5230093/build.ninja.txt) that now has a custom command for af_cuda_static_cuda_library_intermediate_link which was not present in 3.7.0 which builds fine.

**Comment by 9prady9** [comment]
I wasn't implying you were lying :) it is often easy to miss quotes in long
lengthy lines.

Can you please try makefile generator with cmake instead of Ninja and let
us know what happens in that case.

**Comment by lfdmn** [comment]
I am building via bitbake so I don't think I can do that.

If I clear CUDA_NVCC_FLAGS, the build proceeds much further and inevitably fail at linking time.

What is the content of CUDA_NVCC_FLAGS on your machine?

**Comment by 9prady9** [comment]
Usually and now, they are empty. They aren't used unless any special flags are required to be set. I am not sure what is going on, unfortunately, I don't have a jetson board to debug this hands on. @umar456 Any ideas/hints ?

**Comment by lfdmn** [comment]
I found I can change the cmake generator using this variable in my recipe:

`OECMAKE_GENERATOR = "Unix Makefiles"`

For with standard makefiles, I get the same error.

In yocto tegra layer CUDA_NVCC_FLAGS is defined as (see [https://github.com/OE4T/meta-tegra/blob/master/classes/cuda.bbclass](https://github.com/OE4T/meta-tegra/blob/master/classes/cuda.bbclass))

```
CUDA_NVCC_FLAGS ?= "${CUDA_NVCC_ARCH_FLAGS} ${CUDA_NVCC_COMPAT_FLAGS} ${CUDA_NVCC_PATH_FLAGS} ${CUDA_NVCC_EXTRA_FLAGS}"
```

and cmake variables added as
```
# The following are for the old-style FindCUDA.cmake module (pre-3.8)
CUDA_EXTRA_OECMAKE = '\
  -DCUDA_TOOLKIT_TARGET_DIR=${STAGING_DIR_HOST}/usr/local/cuda-${CUDA_VERSION} \
  -DCUDA_TOOLKIT_ROOT_DIR=${STAGING_DIR_NATIVE}/usr/local/cuda-${CUDA_VERSION} \
  -DCUDA_NVCC_FLAGS="${CUDA_NVCC_FLAGS}" \
'
```

- CUDA_NVCC_ARCH_FLAGS ?= "--gpu-architecture=compute_72 --gpu-code=sm_72"
- CUDA_NVCC_COMPAT_FLAGS is empty by default
- CUDA_NVCC_PATH_FLAGS has the include and library paths
- CUDA_NVCC_EXTRA_FLAGS is empty by default

So we end up with a long string containing spaces and I guess this is now the issue.

**Comment by lfdmn** [comment]
I managed to build by replacing the space separators with semi-columns in CUDA_NVCC_FLAGS.

```
CUDA_NVCC_FLAGS ?= "${CUDA_NVCC_ARCH_FLAGS};${CUDA_NVCC_COMPAT_FLAGS};${CUDA_NVCC_PATH_FLAGS};${CUDA_NVCC_EXTRA_FLAGS}"
```

I still can't explain why it builds with 3.7.0 without trouble

**Comment by 9prady9** [comment]
> I managed to build by replacing the space separators with semi-columns in CUDA_NVCC_FLAGS.
> 
> ```
> CUDA_NVCC_FLAGS ?= "${CUDA_NVCC_ARCH_FLAGS};${CUDA_NVCC_COMPAT_FLAGS};${CUDA_NVCC_PATH_FLAGS};${CUDA_NVCC_EXTRA_FLAGS}"
> ```
> 
> I still can't explain why it builds with 3.7.0 without trouble

where are you doing these changes ? on command line as parameters to cmake ? Which version of cmake are you using ?

**Comment by lfdmn** [comment]
I've made the changes to the bitbake recipe I made for yocto build system. It generates the extra cmake command line parameters.

The CMake version coming from poky / zeus branch is 3.15.3.

**Comment by 9prady9** [comment]
> I've made the changes to the bitbake recipe I made for yocto build system. It generates the extra cmake command line parameters.
> 
> The CMake version coming from poky / zeus branch is 3.15.3.

I am not familiar with this, I would have to try it out and check if a build for non-jetson environment will generate similar issues. Do please do share the build process if you have it in some sort of dockerfile or something similar.

The cmake version sounds good.

**Comment by lfdmn** [comment]
I don't have it in a form I can share. The ArrayFire recipes are easy to share but I need to find a way to help you setup yocto.

I'll get back to you.

**Comment by lfdmn** [comment]
@9prady9 I've made a repository to share the work [https://github.com/lfdmn/arrayfire-yocto-build/tree/zeus](https://github.com/lfdmn/arrayfire-yocto-build/tree/zeus) with setup and build instructions. Please check the README.md

Yocto builds a full operating system image/distribution, not just arrayfire. You need plenty of disk space, ~82GB for this test distribution. Everything get compiled, even the compiler, that's why. 

I've made a test image that boots the device (TX2 or Xavier), has CUDA, arrayfire and arrayfire-python. You can SSH in at 192.168.1.100 and use arrayfire from python console.

Ideally, the recipes should be published https://layers.openembedded.org/layerindex/branch/master/layers/ and maintained.

**Comment by 9prady9** [comment]
@lfdmn I just got back to full time work today after covid recovery. I shall get back to you in few days after I look into it. Thanks for setting up the repo and others.

That IP looks like LAN IP and not public one. In anycase, let me build the image and I shall ask you further clarifications if I hit any road blocks while setting up your environment.

**Comment by 9prady9** [comment]
@lfdmn Is having a Jetson mandatory to download JetPack ? I am unable to fetch it using SDK manager approach. Is there an alternative  way ?

**Comment by lfdmn** [comment]
@9prady9 ouch, wish you full recovery!

JetPack can be downloaded on Ubuntu 16.04 and 18.04 based distribution and you don't need to have the HW.

I like using LinuxMint. I just checked on the latest version based on Ubuntu 20.04, I cannot install either.

The sdkmanager reads /etc/lsb-release to detected the OS version. I usually make a backup and change the content while using SDK manager

from 

```
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=19.3
DISTRIB_CODENAME=tricia
DISTRIB_DESCRIPTION="Linux Mint 19.3 Tricia"
```

to 

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04.4
DISTRIB_CODENAME=tricia
DISTRIB_DESCRIPTION="Linux Mint 19.3 Tricia"

```

and back when I'm done.

There's no alternative way of fetching the packages. NVidia has made it easy ones again...

**Comment by 9prady9** [comment]
Thats odd, I am on a Ubuntu 18.04.4 based system, elementary OS. It still doesn't enable selection of JetPack version for me.

**Comment by 9prady9** [comment]
Hm, I think I know whats going on.

**Comment by 9prady9** [comment]
Now hitting this, not sure how should I proceed, the JetPack download was successful and the deb being reported is present.
```
ERROR: /home/pradeep/gitroot/ArrayFireWorkspace/arrayfire-yocto-build/sources/meta-tegra/recipes-devtools/visionworks/libvisionworks-tracking_0.88.2.bb: Error executing a python function in <code>:                           | ETA:  0:00:11

The stack trace of python calls that resulted in this exception/failure was:
File: '<code>', lineno: 3, function: <module>
     0001:__anon_20__home_pradeep_gitroot_ArrayFireWorkspace_arrayfire_yocto_build_sources_poky_meta_conf_machine_include_arm_feature_arm_thumb_inc(d)
     0002:__anon_32__home_pradeep_gitroot_ArrayFireWorkspace_arrayfire_yocto_build_sources_poky_meta_classes_patch_bbclass(d)
 *** 0003:__anon_706__home_pradeep_gitroot_ArrayFireWorkspace_arrayfire_yocto_build_sources_poky_meta_classes_base_bbclass(d)
     0004:__anon_1023__home_pradeep_gitroot_ArrayFireWorkspace_arrayfire_yocto_build_sources_poky_meta_classes_insane_bbclass(d)
     0005:__anon_1263__home_pradeep_gitroot_ArrayFireWorkspace_arrayfire_yocto_build_sources_poky_meta_classes_insane_bbclass(d)
     0006:__anon_252__home_pradeep_gitroot_ArrayFireWorkspace_arrayfire_yocto_build_sources_poky_meta_classes_package_bbclass(d)
     0007:__anon_264__home_pradeep_gitroot_ArrayFireWorkspace_arrayfire_yocto_build_sources_poky_meta_classes_package_ipk_bbclass(d)
File: '/home/pradeep/gitroot/ArrayFireWorkspace/arrayfire-yocto-build/sources/poky/meta/classes/base.bbclass', lineno: 590, function: __anon_706__home_pradeep_gitroot_ArrayFireWorkspace_arrayfire_yocto_build_sources_poky_meta_classes_base_bbclass
     0586:
     0587:    needsrcrev = False
     0588:    srcuri = d.getVar('SRC_URI')
     0589:    for uri in srcuri.split():
 *** 0590:        (scheme, _ , path) = bb.fetch.decodeurl(uri)[:3]
     0591:
     0592:        # HTTP/FTP use the wget fetcher
     0593:        if scheme in ("http", "https", "ftp"):
     0594:            d.appendVarFlag('do_fetch', 'depends', ' wget-native:do_populate_sysroot')
File: '/home/pradeep/gitroot/ArrayFireWorkspace/arrayfire-yocto-build/sources/poky/bitbake/lib/bb/fetch2/__init__.py', lineno: 355, function: decodeurl
     0351:    """
     0352:
     0353:    m = re.compile('(?P<type>[^:]*)://((?P<user>[^/;]+)@)?(?P<location>[^;]+)(;(?P<parm>.*))?').match(url)
     0354:    if not m:
 *** 0355:        raise MalformedUrl(url)
     0356:
     0357:    type = m.group('type')
     0358:    location = m.group('location')
     0359:    if not location:
Exception: bb.fetch2.MalformedUrl: The URL: '/home/pradeep/Downloads/nvidia/sdkm_downloads/libvisionworks-tracking-repo_0.88.2_arm64.deb' is invalid and cannot be interpreted

ERROR: Failed to parse recipe: /home/pradeep/gitroot/ArrayFireWorkspace/arrayfire-yocto-build/sources/meta-tegra/recipes-devtools/visionworks/libvisionworks-tracking_0.88.2.bb
```

**Comment by lfdmn** [comment]
Crap, sorry, I completely skipped this message.

How did you define ```NVIDIA_DEVNET_MIRROR```?

For local path, it should be defined as  ```NVIDIA_DEVNET_MIRROR = "file:///home/pradeep/Downloads/nvidia/sdkm_downloads/"```

**Comment by 9prady9** [comment]
@lfdmn I would need some time to get back to this. My old system setup is not accessible anymore, so have to start from scratch. I shall update here once I have an update.

**Comment by mascojames** [comment]
> I cannot build af_cuda_static_cuda_library_intermediate_link.o
> 
> # Description
> The device is Jetson Xavier. I'm trying to update from 3.7.0 to 3.7.2
> 
> ```
> | FAILED: src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir/af_cuda_static_cuda_library_intermediate_link.o
> 
> nvcc fatal   : Value 'compute_72 --gpu-code=sm_72  --include-path /data/yocto/zeus/build-jetson-xavier/tmp/work/armv8a_tegra194-poky-linux/arrayfire/3.7.2-r0/recipe-sysroot/usr/local/cuda-10.0/include --library-path /data/yocto/zeus/build-jetson-xavier/tmp/work/armv8a_tegra194-poky-linux/arrayfire/3.7.2-r0/recipe-sysroot/usr/local/cuda-10.0/lib' is not defined for option 'gpu-architecture'
> ```
> 
> ## Build Environment
> Compiler version: gcc 7.4 Operating system: poky Build environment:
> 
> ```
>     -DAF_BUILD_CPU=OFF \
>     -DAF_BUILD_CUDA=ON \
>     -DAF_BUILD_OPENCL=OFF \
>     -DAF_BUILD_EXAMPLES=OFF \
>     -DAF_BUILD_TEST=OFF \
>     -DAF_WITH_GRAPHICS=OFF \
>     -DCMAKE_BUILD_TYPE=Release \
>     -DNATIVE_BIN_DIR=${WORKDIR}/recipe-sysroot-native/usr/bin \
>     -DCUDA_architecture_build_targets=7.2 \
>     -DcuDNN_INCLUDE_DIRS=${WORKDIR}/recipe-sysroot/usr/include/ \
> ```
> 
> CMake variables:

So this is a bit of a resuscitation of this issue, but my team was able to track this issue down to how `meta-tegra` was setting the NVCC flags. A patch has been applied to meta-tegra that should fix this issue.

**Comment by christophe-murphy** [comment]
Closing for now, let us know if you are still having issues.
