### ISSUE TITLE
DLLs from official installer are missing file version information on Windows

### ISSUE THREAD

**Issue by cschreib-ibex** [arrayfire/arrayfire#3016]
DLLs from the official installer are missing file version information on Windows.

Description
===========
Most DLLs in Windows have a number of useful identifying fields specified in the rick-click menu "Properties > Details" page. This enables, in particular, to confirm that the DLL has indeed the expected version number. This is currently missing from ArrayFire's DLLs, as obtained from the official 3.7.2 installer.

This information can be added by add a resource ``.rc`` file to the build of each dll, which fills in the required information. CMake has support for this by simply adding the ``.rc`` file to the list of source files for the target.

**Comment by 9prady9** [comment]
We will try to get this into the next minor release.

Current work around, although a bit cumbersome, would be to run the program and call `af::info()` function to see the version info. But I do understand it can't be easily cross checked which file on the disk is of this version if there are multiple dlls.

**Comment by cschreib-ibex** [comment]
Thank you!
