### ISSUE TITLE
support batches along 4th dimension

### ISSUE THREAD

**Issue by 9prady9** [arrayfire/arrayfire#302]
Add batch operations for functions along fourth dimension.

**Comment by pavanky** [comment]
Functions affected:

- transpose
- convolve
- morph

May be more. @9prady9 Add to the list.

**Comment by 9prady9** [comment]
- `bilateral` & `meanshift` handles batch along 4th dimension only if the inputs are color images.
- `histogram`
- `medfilt`

**Comment by 9prady9** [comment]
4th dimension batching for `transpose` already completed.

**Comment by 9prady9** [comment]
Finished 4th dimension batching for morph. Commits can be found [here](https://github.com/9prady9/arrayfire/tree/batch4gfor).
