### ISSUE TITLE
[Question]  Convert or copy generic data from/to array fire data

### ISSUE THREAD

**Issue by majid-abdollahi** [arrayfire/arrayfire#3038]
Hello dear friends,

I am working on a project that is already changed to work with array fire and I when I load data to the software I get an array fire array from the platform. So I should cast  or copy this loaded data into a generic int* memory and five it to the old algorithms. After getting results, I should cast or copy them into an array fire array to show on the software because this software is working only with array fire and I cannot change the old algorithms to working with array fire and only we can pass the int* data to them.

Now, how can I do something like code below with array fire? (I mention that i worked with some functions like write, host,copy, and ... but I couldn't to get the right thing)

af::array data;
Convert or copy data to int* memory.
Call_function(int*, int* output);
Convert or copy output to af::array

I need some examples that how can we use the functions I see in the array fire documentation.
All operation is doing on the host at this time.

Thanks

**Comment by 9prady9** [comment]
```c++
array data;
// operate on data on GPU
vector<int> hostArray(data.elements());
array intData = data.as(i32); // This is only required if the data is not integer array already.
                                             //  Nevertheless, this is no cost operation  
                                             //  if data is already integer array
intData.host(hostArray.data());
// Use this integer data on host.
// when you need back on GPU, you can copy it back to GPU.
array backFromHost(intData.data(), dim4( ....));
```
Is that what you are looking for ?

The above can also be further speed up using pinned memory if this kind of usage is very common in your application and the size of the host array is known ahead of time and fixed.

**Comment by majid-abdollahi** [comment]
@9prady9 Thanks for your attention. 

For the first part I wrote something like :
int* data = inputData.as(s32).host<int>();

and for the second one:
af::array(inputData, output);

might there is some spelling error ;)

Thanks.

**Comment by 9prady9** [comment]
Yeah, my bad. I got `i32` from rust mixed up with `s32` enum value of arrayfire. `s32` is correct.

**Comment by majid-abdollahi** [comment]
@9prady9 ;)

**Comment by 9prady9** [comment]
Feel free to close the issue if your question has been addressed.
