### ISSUE TITLE
Sparse-sparse matmul

### ISSUE THREAD

**Issue by ljmartin** [arrayfire/arrayfire#3041]
Hi ArrayFire, 
This software looks great so thanks for providing it. I just wanted to ask if there's any plans to add to the sparse-dense matmul function to allow sparse-sparse matmuls?

The use-case is calculating the pairwise intersections between two sets of sparse binary matrices. This is also the first step in calculating cosine distances between two sparse arrays. I'm afraid I can't suggest any algorithms, just wondering if it's in scope :)

**Comment by 9prady9** [comment]
@ljmartin sparse-dense and sparse-sparse matrix multiplication support is already available in current stable release. You can use the same `matmul` API and the respective backend algorithms are run if the `lhs` and/or `rhs` are sparse.

**Comment by ljmartin** [comment]
thanks :)
