### ISSUE TITLE
[Question] How compile Arrayfire within Docker? Should I link to `stub/libcuda.so`?

### ISSUE THREAD

**Issue by alealv** [arrayfire/arrayfire#3046]
I'm facing an error when building an application that uses `arrayfire` with CUDA as a dependency. The error is best explained [here](https://github.com/facebookresearch/flashlight/issues/256) but I as a summary my question is if when building `ArrayFire` inside a docker based on [nvidia/cuda:10.0-devel-ubuntu18.04](https://gitlab.com/nvidia/container-images/cuda/-/blob/master/dist/10.0/ubuntu18.04-x86_64/devel/Dockerfile) we should link to the [CUDA stub static library](https://gitlab.com/nvidia/container-images/cuda/-/blob/master/dist/10.0/ubuntu18.04-x86_64/devel/Dockerfile#L23) and somehow later be replaced to the host's driver library when running the application?

**Comment by 9prady9** [comment]
I believe you are looking for those lines https://github.com/arrayfire/arrayfire-docker/blob/master/Dockerfile#L24-L29 
The first two lines are needed to build the library if not everything.

Note: The file is from our own repository that shows how to build ArrayFire using Docker. https://github.com/arrayfire/arrayfire-docker

**Comment by alealv** [comment]
Thanks!!!
