### ISSUE TITLE
max(lhs, rhs) problem

### ISSUE THREAD

**Issue by MinChenONFS** [arrayfire/arrayfire#305]
Hello all,

I just wonder what would be the correct implementation of:
" AFAPI array max    (const array &lhs, const array &rhs); "

I tried the following but got "error C2440: '?' : cannot convert from 'af::array' to 'bool'":
#include <iostream>
#include <arrayfire.h>
using namespace std;
int main()
{
	af::array A = af::randn(10,1);
	af::array B = af::randn(10,1);
	max(A,B);
	return 0;
}

**Comment by pavanky** [comment]
@MinChenONFS The code does not seem to be complete. Are you assigning max(A, B) to something ?

**Comment by MinChenONFS** [comment]
Thanks for the quick response Pavan.
I tried both assign and print but both got same error:
af::array C = max(A,B);
af_print(max(A,B));

**Comment by pavanky** [comment]
@MinChenONFS 

Can you try using af::max explicitly ? I am guessing our max is conflicting with std::max

**Comment by MinChenONFS** [comment]
That was my first shot but got this error, so I assumed max should be used out of af::
error C2589: '(' : illegal token on right side of '::'
error C2059: syntax error : '::'
---------------------------------------------
af::array C = af::max(A,B);
af_print(af::max(A,B));

**Comment by pavanky** [comment]
@MinChenONFS If you are using this on Windows, can you add the following on top of main()

```
#undef min
#undef max
```

**Comment by MinChenONFS** [comment]
Worked. Thanks a lot!
Seems like a Windows specific problem?

**Comment by pavanky** [comment]
@MinChenONFS Yes. By default, Visual Studio seems to add macros for min and max causing a conflict with function names with the same name. You can find more about the issue from here: http://support.microsoft.com/kb/143208

Ideally you want to add `NOMINMAX` at the top of your source file (before including any header) or pass it to the compiler as a definition to work around this problem.
