### ISSUE TITLE
[BUG] Error messages from NVRTC are truncated

### ISSUE THREAD

**Issue by cschreib-ibex** [arrayfire/arrayfire#3053]
ArrayFire sets a maximum size for error messages coming through the C API to 1024 characters. This is a problem when an error occurs, say, in ``compileModule()`` because the stack trace itself takes 896 characters and is printed first. This doesn't leave enough room for the actual error message to be included in the error string. 

This could be fixed by increasing the buffer size. A more flexible solution in the long run would be to let the user specify their own buffer and buffer length as parameters of ``af_get_last_error()`` (or a new function, to preserve backward compatibility), as is commonly done in C APIs returning strings.

Description
===========
* Additional details regarding the bug:
 This is the error we got
```
af_sum_all failed. (AF error code: 998, message: In function class cuda::Module __cdecl common::compileModule(const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,const class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > &,const class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > &,const class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > &,const bool)
In file src\backend\cuda\compile_module.cpp:265
NVRTC Error(7): NVRTC_ERROR_BUILTIN_OPERATION_FAILURE
Log: 
nvrtc: error: fa
```
* Did you build ArrayFire yourself or did you use the official installers: official installer for 3.7.2
* Which backend is experiencing this issue: All
* Do you have a workaround: No
* Can the bug be reproduced reliably on your system: Yes (but see below)
* A clear and concise description of what you expected to happen: The whole error message should have been returned.
* Run your executable with AF_TRACE=all and AF_PRINT_ERRORS=1 environment
  variables set: Not relevant.
* Screenshot or terminal output of the results: See above.

Reproducible Code and/or Steps
------------------------------
* Steps or code snippet that can reproduce the bug: Unfortunately this error was reported to us by a customer, so I do not know how the error was triggered (especially not knowing the full error message). Nevertheless, the limitation of 1024 characters is pretty clear in the ArrayFire source code:
https://github.com/arrayfire/arrayfire/blob/82a8c77d5f11202e26e5c31adb6d7c57b40f0c3e/src/api/c/error.cpp#L21
https://github.com/arrayfire/arrayfire/blob/82a8c77d5f11202e26e5c31adb6d7c57b40f0c3e/src/backend/common/err_common.hpp#L211
* A full example will allow us to debug and fix the bug faster: See above.

System Information
------------------
Please provide the following information:
1. ArrayFire version: 3.7.2
2. Devices installed on the system: Not relevant
3. (optional) Output from the af::info() function if applicable: Not accessible.
4. Output from the following scripts: Not accessible.

Checklist
---------

- [x] Using the latest available ArrayFire release
- [ ] GPU drivers are up to date (not relevant)

**Comment by 9prady9** [comment]
`af_get_last_error` could definitely use better logic I guess. Except the nvrtc messages, usually most of the other error messages are quite short, thus the chosen character limit.

The nvrtc error buffers are about 4096 size and they should easily capture the error log which is then forwarded as exception message. I am not quite sure why or how the exception thrown isn't showing the error message on console or log file that captures console output of arrayfire.

**Comment by cschreib-ibex** [comment]
In our setup, the console output is not available, and it is not redirected to any log file. Our only way to obtain error messages is through whatever is returned by ``af_get_last_error``, which has the ``MAX_ERR_SIZE`` limit. The rest of the code seems to be limited by the 4096 limit in https://github.com/arrayfire/arrayfire/blob/82a8c77d5f11202e26e5c31adb6d7c57b40f0c3e/src/backend/cuda/compile_module.cpp#L118

**Comment by 9prady9** [comment]
> In our setup, the console output is not available, and it is not redirected to any log file. Our only way to obtain error messages is through whatever is returned by ``af_get_last_error``, which has the ``MAX_ERR_SIZE`` limit. The rest of the code seems to be limited by the 4096 limit in https://github.com/arrayfire/arrayfire/blob/82a8c77d5f11202e26e5c31adb6d7c57b40f0c3e/src/backend/cuda/compile_module.cpp#L118

Makes sense

**Comment by cschreib-ibex** [comment]
FYI I originally thought the error message was too long because of the stack trace, so I tried using ``af_set_enable_stacktrace(0)`` to disable it. Unfortunately that did not help me, as the problem isn't actually the stack trace being too long, but the calling function's signature being too long (``compileModule(...)``). This is still printed when stack traces are disabled. I don't know if this was intended, but I thought I'd just mention it.

**Comment by 9prady9** [comment]
Can you please share the whole output you are getting - the compileModule function signature line.

**Comment by cschreib-ibex** [comment]
The full string returned by ``af_get_last_error()`` is
```
In function class cuda::Module __cdecl common::compileModule(const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,const class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > &,const class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > &,const class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > &,const bool)
In file src\backend\cuda\compile_module.cpp:265
NVRTC Error(7): NVRTC_ERROR_BUILTIN_OPERATION_FAILURE
Log: 
nvrtc: error: fa
```

I just noticed this is slightly less than 1024 characters. That is because we do something perhaps a little naughty: we prepend some additional information on the error (the error code, actually), and use the generated string to construct an instance of ``af::exception``, which we then throw ourselves (*). This actually hits a different limitation in error message length: ``af::exception`` can only store 1024 characters:
https://github.com/arrayfire/arrayfire/blob/82a8c77d5f11202e26e5c31adb6d7c57b40f0c3e/include/af/exception.h#L24


(*) I know this is a little odd, but our code base has legacy code that was produced using the C API of ArrayFire directly, and we only belatedly started using the C++ API. A lot of our code has still not been ported over... Hence this strange mixture of C and C++ API.

**Comment by 9prady9** [comment]
Thank for sharing it, yeah it is awkwardly too long, I think I know where this is coming from. We will look into it.
