### ISSUE TITLE
[Perf]blas_cpu-example is slower on E5-2695 V4 than on i7-6700

### ISSUE THREAD

**Issue by anates** [arrayfire/arrayfire#3056]
Description
===========
When running the benchmark example blas_cpu on my development machine (i7-6700, 4c/8t), it achieves up to 350 GFlops while utilizing all eight threads. When running the same benchmark on the cluster (E5-2695 v4, 18c/36t), it achieves only up to 80 GFlops and is using a single thread. I can not see a reason for this performance difference.

* Additional information about the performance issues
As mentioned, running the benchmark program blas_cpu the achieved Flops are lower on the cluster machine by a factor of approx. 4.5 compared to my development machine. Moreover, the program only uses a single thread on the cluster compared to eight on the dev. machine.
* Did you build ArrayFire yourself or did you use the official installers
Built it myself based on the latest version on git
* Which backend is experiencing this issue? (CPU, CUDA, OpenCL)
CPU
* Do you have a workaround?
No
* Can the bug be reproduced reliably on your system?
Yes

Reproducible Code
-----------------

Example blas_cpu from the example directory, without changes

System Information
------------------
ArrayFire Version: 3.8.0
Device: Cluster/Development machine
Operating System: n/a
Driver version: n/a

Checklist
---------
- [ x] I have read [timing ArrayFire](http://arrayfire.org/docs/timing.htm)

**Comment by 9prady9** [comment]
@anates Sorry about the delay. What is the BLAS library backend you used to build ArrayFire's CPU backend ?

**Comment by 9prady9** [comment]
In case you are using IntelMKL, please go through the conversation in the issue - https://github.com/arrayfire/arrayfire/issues/3042 it might help to check if some MKL variable can be set to resolve the issue.

**Comment by anates** [comment]
I'm using MKL, but I'm not sure if #3042 will help, after all involved CPUs are Intel CPUs, and therefore the necessary parameters should have been set automatically.

**Comment by 9prady9** [comment]
Can you try setting [`MKL_NUM_THREADS`](https://software.intel.com/content/www/us/en/develop/documentation/mkl-linux-developer-guide/top/managing-performance-and-memory/improving-performance-with-threading/using-additional-threading-control/intel-mkl-specific-environment-variables-for-openmp-threading-control.html) and check if that changes the behavior.

**Comment by 9prady9** [comment]
> Can you try setting [`MKL_NUM_THREADS`](https://software.intel.com/content/www/us/en/develop/documentation/mkl-linux-developer-guide/top/managing-performance-and-memory/improving-performance-with-threading/using-additional-threading-control/intel-mkl-specific-environment-variables-for-openmp-threading-control.html) and check if that changes the behavior.

@anates Any change ? or is it still using single thread ?

**Comment by 9prady9** [comment]
@anates If you have resolved the issue by any changes to you development setup, please share details here for any future users who may face the similar issue.

**Comment by anates** [comment]
@9prady9 Sorry for not answering, but my project focus has shifted a bit, and I was not able to check results, unfortunately. But will update as soon as I get around to test it. Thanks!

**Comment by christophe-murphy** [comment]
Closed for now, if you are still having problems please open a new issue.
