### ISSUE TITLE
[BUG] Empty array behaves different in OpenCL vs CUDA  

### ISSUE THREAD

**Issue by avidov** [arrayfire/arrayfire#3058]
When calling host() on an empty array the process crushes on segmentation fault with OpenCL backend. The same code passes with CUDA backend.

{
  af::array test;
  af::print("test", test);
  std::vector<float> v(100);
  test.host(v.data());
}

OpenCL:
[platform][1606953256][065084] [ /private/home/avidov/multibackend/opencl/arrayfire/src/backend/common/DependencyModule.cpp:55 ] Attempting to load: libforge.so
[platform][1606953256][065084] [ /private/home/avidov/multibackend/opencl/arrayfire/src/backend/common/DependencyModule.cpp:60 ] Unable to open forge
[platform][1606953256][065084] [ /private/home/avidov/multibackend/opencl/arrayfire/src/backend/opencl/device_manager.cpp:204 ] Found 1 OpenCL platforms
[platform][1606953256][065084] [ /private/home/avidov/multibackend/opencl/arrayfire/src/backend/opencl/device_manager.cpp:216 ] Found 2 devices on platform NVIDIA CUDA
[platform][1606953256][065084] [ /private/home/avidov/multibackend/opencl/arrayfire/src/backend/opencl/device_manager.cpp:221 ] Found device Quadro GP100 on platform NVIDIA CUDA
[platform][1606953256][065084] [ /private/home/avidov/multibackend/opencl/arrayfire/src/backend/opencl/device_manager.cpp:221 ] Found device Quadro GP100 on platform NVIDIA CUDA
[platform][1606953256][065084] [ /private/home/avidov/multibackend/opencl/arrayfire/src/backend/opencl/device_manager.cpp:226 ] Found 2 OpenCL devices
[platform][1606953257][065084] [ /private/home/avidov/multibackend/opencl/arrayfire/src/backend/opencl/device_manager.cpp:320 ] Default device: 0
test
[0 1 1 1]
   Offset: 0
   Strides: [1 0 0 0]
<empty>
Segmentation fault

CUDA:
[platform][1606953367][065881] [ /private/home/avidov/arrayfire/src/backend/common/DependencyModule.cpp:55 ] Attempting to load: libforge.so
[platform][1606953367][065881] [ /private/home/avidov/arrayfire/src/backend/common/DependencyModule.cpp:60 ] Unable to open forge
[platform][1606953367][065881] [ /private/home/avidov/arrayfire/src/backend/cuda/device_manager.cpp:424 ] CUDA Driver supports up to CUDA 10.1 ArrayFire CUDA Runtime 10.0
[platform][1606953367][065881] [ /private/home/avidov/arrayfire/src/backend/cuda/device_manager.cpp:492 ] Found 2 CUDA devices
[platform][1606953367][065881] [ /private/home/avidov/arrayfire/src/backend/cuda/device_manager.cpp:518 ] Found device: Quadro GP100 (15.9 GB | ~9860.84 GFLOPs | 56 SMs)
[platform][1606953367][065881] [ /private/home/avidov/arrayfire/src/backend/cuda/device_manager.cpp:518 ] Found device: Quadro GP100 (15.9 GB | ~9860.84 GFLOPs | 56 SMs)
[platform][1606953367][065881] [ /private/home/avidov/arrayfire/src/backend/cuda/device_manager.cpp:553 ] AF_CUDA_DEFAULT_DEVICE: 
[platform][1606953367][065881] [ /private/home/avidov/arrayfire/src/backend/cuda/device_manager.cpp:572 ] Default device: 0(Quadro GP100)
test
[0 1 1 1]
<empty>
 

System info:
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
name, memory.total [MiB], driver_version
Quadro GP100, 16278 MiB, 418.116.00
rocm-smi not found.
clinfo not found.

Built Arrayfire from sourc:
opencl:

cd arrayfire; git checkout v3.7.1; mkdir build; cd build
cmake .. \
  -DCMAKE_BUILD_TYPE=Debug -DAF_BUILD_OPENCL=ON -DAF_BUILD_CUDA=OFF -DAF_BUILD_CPU=OFF \
  -DAF_BUILD_UNIFIED=OFF -DAF_BUILD_EXAMPLES=OFF -DBUILD_TESTING=ON -DAF_BUILD_DOCS=OFF \

cuda:
cd arrayfire; git checkout v3.7.1; mkdir build; cd build
# Only builds the CUDA backend, not CPU or OpenCL 
cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/usr \
  -DCMAKE_BUILD_TYPE=Release -DAF_BUILD_OPENCL=OFF -DAF_BUILD_CPU=OFF \
  -DAF_BUILD_UNIFIED=OFF -DAF_BUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF \
  -DCUDA_architecture_build_targets="6.0;7.0;7.0+PTX" \
  -DcuDNN_LINK_LIBRARY=$CUDNN_LIB_DIR/libcudnn.so.7.6.2 \
  -DcuDNN_INCLUDE_DIRS=$CUDNN_INCLUDE_DIR \
  -DCUDA_cublasLt_static_LIBRARY=$CUDA_HOME/lib64/libcublasLt.so.10.1.0.105

**Comment by avidov** [comment]
Did anybody experienced this issue before ?

**Comment by 9prady9** [comment]
@avidov I was able to reproduce this on `v3.8` branch. It shouldn't seg-fault. Thanks for reporting this. I shall send in a fix soon if master branch also has the same problem.

**Comment by avidov** [comment]
Awesome, thank you for the fix Pradeep! I'll rebase the 2 commits and test if it solves my issue.

**Comment by avidov** [comment]
My use case required also 
https://github.com/arrayfire/arrayfire/pull/3064/commits/f9f3894df7f7506a68d4e209bba36e7469805fc5
https://github.com/arrayfire/arrayfire/pull/3064
Which adds the same fix to af_write_array

**Comment by jacobkahn** [comment]
@9prady9 looks like the CPU backend also allocates a buffer for empty arrays. Should probably update that underlying code as well? I can send a PR if you'd like

**Comment by 9prady9** [comment]
CPU backend's underlying implementation uses malloc for allocation which does the following as per [standard](https://en.cppreference.com/w/c/memory/malloc):

> If size is zero, the behavior of malloc is implementation-defined. For example, a null pointer may be returned. Alternatively, a non-null pointer may be returned; but such a pointer should not be dereferenced, and should be passed to free to avoid memory leaks. 

We don't deference the pointer for the case where the number of elements equals zero which was what was sort of missing in OpenCL backend that caused the error.

As far as how much memory is allocated for `malloc(0)`, I think the answer is `minimum block size allocated for a any allocation request` when malloc returns non-nullptr.

To avoid even that minimum allocation, we can definitely convert the `data` member initialization to a conditional statement to use `nullptr` directly when elements equals zero and only resort to memory manager call when the number of elements are greater than zero. That should basically take care of it. @jacobkahn Sure, you are welcome to send in a PR
