### ISSUE TITLE
[Error] Error loading Forge: No Error on macOS

### ISSUE THREAD

**Issue by hykilpikonna** [arrayfire/arrayfire#3061]
Description
===========

I'm trying to run the code from one example, it compiles, but gives the error below:

Error Log
---------

```
ArrayFire v3.7.3 (OpenCL, 64-bit Mac OSX, build default)
[0] APPLE: AMD Radeon RX 5600 XT Compute Engine, 6128 MB
ArrayFire Exception (Failed to load dynamic library. :501):
In function fg_window graphics::ForgeManager::getMainWindow()
In file src/backend/common/graphics_common.cpp:274
Error loading Forge: No Error
Forge or one of it's dependencies failed to load. Try installing Forge or check if Forge is in the search path.
 0# graphics::ForgeManager::getMainWindow() in /usr/local/Cellar/arrayfire/3.7.3/lib/libafopencl.3.7.3.dylib
 1# graphics::ForgeManager::getWindow(int, int, char const*, bool) in /usr/local/Cellar/arrayfire/3.7.3/lib/libafopencl.3.7.3.dylib
 2# af_create_window in /usr/local/Cellar/arrayfire/3.7.3/lib/libafopencl.3.7.3.dylib
 3# af::Window::initWindow(int, int, char const*) in /usr/local/opt/arrayfire/lib/libaf.3.dylib
 4# main in /Volumes/macWorkspace/CPP/School/cmake-build-debug/./arrayfire

In function void af::Window::initWindow(const int, const int, const char *const)
In file src/api/cpp/graphics.cpp:19
libc++abi.dylib: terminating with uncaught exception of type af::exception: ArrayFire Exception (Failed to load dynamic library. :501):
In function fg_window graphics::ForgeManager::getMainWindow()
In file src/backend/common/graphics_common.cpp:274
Error loading Forge: No Error
Forge or one of it's dependencies failed to load. Try installing Forge or check if Forge is in the search path.
 0# graphics::ForgeManager::getMainWindow() in /usr/local/Cellar/arrayfire/3.7.3/lib/libafopencl.3.7.3.dylib
 1# graphics::ForgeManager::getWindow(int, int, char const*, bool) in /usr/local/Cellar/arrayfire/3.7.3/lib/libafopencl.3.7.3.dylib
 2# af_create_window in /usr/local/Cellar/arrayfire/3.7.3/lib/libafopencl.3.7.3.dylib
 3# af::Window::initWindow(int, int, char const*) in /usr/local/opt/arrayfire/lib/libaf.3.dylib
 4# main in /Volumes/macWorkspace/CPP/School/cmake-build-debug/./arrayfire

In function void af::Window::initWindow(const int, const int, const char *const)
In file src/api/cpp/graphics.cpp:19
zsh: abort      ./arrayfire
```

Build Environment
-----------------
Compiler version: Apple clang version 12.0.0 (clang-1200.0.32.21)
Operating system: macOS Catalina 10.15.7
Build environment: -
CMake variables: -

**Comment by 9prady9** [comment]
@hykilpikonna Is `/opt/arrayfire/lib` or the lib folder under ArrayFire Installation available via DYLD_LIBRARY_PATH/LD_LIBRARY_PATH ?

**Comment by hykilpikonna** [comment]
> @hykilpikonna Is `/opt/arrayfire/lib` or the lib folder under ArrayFire Installation available via DYLD_LIBRARY_PATH/LD_LIBRARY_PATH ?

They are empty. Should I try assigning the paths to these variables?
![image](https://user-images.githubusercontent.com/22280294/101861147-65174600-3b3d-11eb-9a19-a58d747570ef.png)

> Graphics is runtime loaded, even though the ArrayFire builds fine with forge headers. You need the forge library to be available in above environment variables for the program to run. From your log, it seems you have built ArrayFire. Is that correct ? If Yes, please make sure `build/extern/forge/src/backend/`, where `build` is your build-tree path, is in the environment variables mentioned so that runtime loader can find them.

I didn't build ArrayFire, I installed ArrayFire from brew. (The build target thing is called arrayfire but it's just like a bad naming thing, it's actually the example I've compiled). I downloaded Forge separately using the .sh script in their Github releases, installed to `/Users/hykilpikonna/Downloads/Forge-1.0.5`.
![image](https://user-images.githubusercontent.com/22280294/101861611-701ea600-3b3e-11eb-8ba0-f55682fab1ea.png)

**Comment by 9prady9** [comment]
@hykilpikonna If you installed ArrayFire using the binary from our website, then forge library is already packaged and distributed along with ArrayFire libraries. So, you don't need to install forge library separately.

Yes, please ensure that the libraries of ArrayFire installation are in LD_LIBRARY_PATH environment variable. If that doesn't help, please try DYLD_LIBRARY_PATH.

http://arrayfire.org/docs/installing.htm

**Comment by ankane** [comment]
Hey @hykilpikonna, just fyi, Forge is now available on Homebrew with:

```sh
brew install forge
```

**Comment by 9prady9** [comment]
@ankane that souldn't be needed as forge is provided along with the ArrayFire libraries right in the same lib folder of ArrayFire installation. Environment variable `LD_LIBRARY_PATH` or `DYLD_LIBRARY_PATH` should be used to fix that. I am not an Apple expert @umar456 Can you please clarify why and how image not found issues should be resolve on Apple OS.

**Comment by ankane** [comment]
Forge isn't included when ArrayFire is installed with Homebrew, which it sounds like was the issue here ("I installed ArrayFire from brew" in comment above).

**Comment by 9prady9** [comment]
Ah, installation was done via brew not our website binary. I am kind of clueless in that case as I don't have an OSX machine to test that approach. We don't maintain that brew formula and it would be a question to whoever maintains it I think. Also, the version is also quite old for brew's arrayfire.

**Comment by ankane** [comment]
It should be up-to-date. The current version on Homebrew is 3.8.0. https://formulae.brew.sh/formula/arrayfire

**Comment by 9prady9** [comment]
Hm, there is another page that says 3.6.4 I wonder whats the difference between both 
https://formulae.brew.sh/cask/arrayfire

**Comment by ankane** [comment]
That one should be removed. I'll submit a PR to the project.

**Comment by 9prady9** [comment]
Can one formula be set as dependency for another in brew ? If so, forge should be if it isn't provided as part of arrayfire formula.

**Comment by ankane** [comment]
There are dependencies, but from my understanding, Homebrew prefers not to include optional dependencies unless there's some advantage at build time.

**Comment by 9prady9** [comment]
That would be up to homebrew maintainer's decision I would assume. Forge basically provides OpenGL graphics support. 

@hykilpikonna I don't think there is any resolution to this from code or our installer stand point. Feel free to close the issue as @ankane suggested the resolution already.

**Comment by hykilpikonna** [comment]
Thank you! Even though I can't verify this solution right now, it seems like the issue would be resolved after `brew install forge`.
