### ISSUE TITLE
[Question] Different results for same computation using for and gfor: why?

### ISSUE THREAD

**Issue by simonmb** [arrayfire/arrayfire#3079]
I am executing the following code to solve nonlinear equations. The example is with a very small system just for experimenting puposes. I get different results when using for or gfor. Am I doing something wrong?

```c++
af::setDevice(0);
af::info();

float B_array[16] = { 1.0f, 2.0f, 3.0f, 4.0f, 
                      2.0f, 1.0f, 10.0f, 8.0f,
                      3.0f, 10.0f, 1.0f, 12.0f,
                      4.0f, 8.0f, 12.0f, 1.0f };

array B = constant(1.0f, 4, 4, 2);

B(span, span, 0) = array(4, 4, B_array);
B(span, span, 1) = array(4, 4, B_array) + 1;
af_print(B);

float D_array[8] = { 0.2f, 0.3f, 0.4f, 0.1f, 0.5f, 0.5f, 0.3f, 0.2f };
array D = array(4, 1, 2, D_array);
af_print(D);

array A = B * af::tile(D, af::dim4(1, 4, 1));
af_print(A);

const double convergenceThreshhold = 0.00001;
array X = constant(1.0f, 4, 2);
array X2 = constant(1.0f, 4, 2);

for (int k = 0; k < 2; k++) {

    af::array this_A = A(span, span, k);
    af::array this_X = X(span, k);
    af::array this_X2;
    af::array difference;
    do {
        this_X2 = this_X;
        for (int i_row = 0; i_row < 4; i_row++) {
            this_X(i_row) = 1 / af::sum<float>(this_A(span, i_row) * this_X);
        }
        difference = af::abs(af::log(this_X) - af::log(this_X2));
        
    } while (af::anyTrue<bool>(difference > convergenceThreshhold));
    X(span, k) = this_X;
}
af_print(X);

gfor(af::seq k, 0, 1) {

    af::array this_A = A(span, span, k);
    af::array this_X = X2(span, k);
    af::array this_X2;
    af::array difference;
    do {
        this_X2 = this_X;
        for (int i_row = 0; i_row < 4; i_row++) {
            this_X(i_row) = 1 / af::sum<float>(this_A(span, i_row) * this_X);
        }
        difference = af::abs(af::log(this_X) - af::log(this_X2));

    } while (af::anyTrue<bool>(difference > convergenceThreshhold));
    X2(span, k) = this_X;
}

af_print(X2);
```

______________________________________________________
Output
______________________________________________________
ArrayFire v3.7.3 (CPU, 64-bit Windows, build 59ac7b9)
[0] Intel: Intel(R) Xeon(R) CPU E5-1607 v3 @ 3.10GHz

B
[4 4 2 1]

    1.0000     2.0000     3.0000     4.0000
    2.0000     1.0000    10.0000     8.0000
    3.0000    10.0000     1.0000    12.0000
    4.0000     8.0000    12.0000     1.0000

    2.0000     3.0000     4.0000     5.0000
    3.0000     2.0000    11.0000     9.0000
    4.0000    11.0000     2.0000    13.0000
    5.0000     9.0000    13.0000     2.0000

D
[4 1 2 1]

    0.2000
    0.3000
    0.4000
    0.1000

    0.5000
    0.5000
    0.3000
    0.2000

A
[4 4 2 1]

    0.2000     0.4000     0.6000     0.8000
    0.6000     0.3000     3.0000     2.4000
    1.2000     4.0000     0.4000     4.8000
    0.4000     0.8000     1.2000     0.1000

    1.0000     1.5000     2.0000     2.5000
    1.5000     1.0000     5.5000     4.5000
    1.2000     3.3000     0.6000     3.9000
    1.0000     1.8000     2.6000     0.4000

X
[4 2 1 1]

    0.9398     0.5851
    0.4049     0.4005
    0.4414     0.2426
    0.2585     0.2323

X2
[4 2 1 1]

    0.2019     1.0000
    0.1229     1.0000
    0.0883     1.0000
    0.0820     1.0000

**Comment by simonmb** [comment]
The results from the for loop are correct while the others are not,

**Comment by 9prady9** [comment]
@simonmb I just noticed the regular loop inside gfor loop that is not supported. Please go through our GFOR tutorial - http://arrayfire.org/docs/page_gfor.htm to understand how to use GFOR and what are it's restrictions.

**Comment by simonmb** [comment]
@9prady9 thanks, I though I had understood correctly and it was enough to get the data for the "for loop" before I start it. Is there another way to achieve this algorithm?

I could also instead use:

```c++
do {
        this_X2 = this_X;
        this_X = 1 / matmulTN(this_A, this_X);
        difference = af::abs(af::log(this_X) - af::log(this_X2));
} while (af::anyTrue<bool>(difference > convergenceThreshhold));

```

but this does not converge as fast as the other one (without taking into account the influence of solving it in parallel) and sometimes it doesn't even converge at all depending on the satrting values.

**But even more important is the question if the do while loop is allowed?**

**Comment by 9prady9** [comment]
Yes, I wouldn't expect it to converge as it is not equivalent to what you have in the code that uses for loop.
```c++
for (int i_row = 0; i_row < 4; i_row++) {
            this_X(i_row) = 1 / af::sum<float>(this_A(span, i_row) * this_X);
}
```
This line this_X output in each iteration is used in next iteration, there is data dependency across rows from 0 through last row where as the `matmul`'s `this_X` has all ones in it.

I am not sure I am able to understand the target logic here completely. If you can share some pseudo code or abstract algorithm instead of arrayfire port, we might be able to help identify if given logic is parallelizable. If yes, what's the best possible approach using arrayfire.

**Comment by simonmb** [comment]
Yes, I know I am not doing the same with the for loop and the matmul version. But the matmul version is the only version I could come up with that was able to be run in parallel.

The following description is using the same variables as in the example above.
I have a symmetric matrix similar to B (size n, n, 1, 1). This matrix B is multiplied by m vectors D as shown in the code above to several matrices A (size n, n, m, 1). For each of thie matrices A I need to solve the following nonlinear equation system:

1/X_i = sum(A_ij * X_j) over all j

So my idea was to solve these systems in parallel.

I asked a question about the system of equations on mathoverflow [here](https://mathoverflow.net/questions/380277/how-to-solve-this-set-of-equations-as-efficiently-as-possible-efficiently-measu). The equations are better represented there.

**Comment by 9prady9** [comment]
I think I understand your problem statement. If data dependency between each of the iterations in original description code's for loop is an important criteria for faster convergence, then I think there isn't anything that can be done to parallelize such code. GPU based algorithms require some sort of data-parallelism to vectorize the code.

If you can rewrite your algorithm in such a fashion that by doing some additional/duplicate work you can vectorize the code, then you should look into that approach.
