### ISSUE TITLE
Getting segmentation fault

### ISSUE THREAD

**Issue by AleksBL** [arrayfire/arrayfire#3081]
Hello,
I have ran the installer for arrayfire 3.8 in my home directory and added the path to my LD_LIBRARY_PATH, together with installing arrayfire-python through pip. However, when i run the python -m arrayfire.tests, I get the "segmentation fault core dumped" error. Why is this? I have tried with both Arrayfire 3.6 and 3.8, both do this.  I am using a ryzen 5 cpu and its vega 7 igpu

**Comment by 9prady9** [comment]
@AleksBL Try setting the environment variables using the below commands and please paste the outcome here.
```bash
export AF_PRINT_ERRORS=1
export AF_TRACE=all
```

**Comment by AleksBL** [comment]
[platform][1611395394][054177] [ ../src/backend/common/DependencyModule.cpp:99 ] Attempting to load: libforge.so
[platform][1611395394][054177] [ ../src/backend/common/DependencyModule.cpp:102 ] Found: libforge.so
[mem][1611395394][054177] [ ../src/backend/cpu/memory.cpp:146 ] nativeAlloc:    1 KB 0x55cdfd60cc80
In function opencl::DeviceManager::DeviceManager()
In file src/backend/opencl/device_manager.cpp:
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:141 ] Attempting: Default System Paths
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:144 ] Found: libafcpu.so.3
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:151 ] Device Count: 1.
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:141 ] Attempting: Default System Paths
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:144 ] Found: libafopencl.so.3
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:151 ] Device Count: 0.
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:153 ] Skipping: No devices found for libafopencl.so.3
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:141 ] Attempting: .
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:162 ] Failed to load ./libafopencl.so.3: cannot open shared object file: No such file or directory
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:141 ] Attempting: ./src/backend/opencl
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:162 ] Failed to load ./src/backend/opencl/libafopencl.so.3: cannot open shared object file: No such file or directory
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:141 ] Attempting: ../src/backend/opencl
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:162 ] Failed to load ../src/backend/opencl/libafopencl.so.3: cannot open shared object file: No such file or directory
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:141 ] Attempting: src/backend/opencl
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:162 ] Failed to load src/backend/opencl/libafopencl.so.3: cannot open shared object file: No such file or directory
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:141 ] Attempting: /opt/arrayfire-3//lib
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:162 ] Failed to load /opt/arrayfire-3//lib/libafopencl.so.3: cannot open shared object file: No such file or directory
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:141 ] Attempting: /opt/arrayfire-3//lib64
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:162 ] Failed to load /opt/arrayfire-3//lib64/libafopencl.so.3: cannot open shared object file: No such file or directory
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:141 ] Attempting: Default System Paths
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:144 ] Found: libafopencl.so.3
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:151 ] Device Count: 0.
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:153 ] Skipping: No devices found for libafopencl.so.3
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:141 ] Attempting: /opt/arrayfire-3/lib/
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:162 ] Failed to load /opt/arrayfire-3/lib//libafopencl.so.3: cannot open shared object file: No such file or directory
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:141 ] Attempting: /opt/arrayfire/lib/
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:162 ] Failed to load /opt/arrayfire/lib//libafopencl.so.3: cannot open shared object file: No such file or directory
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:141 ] Attempting: /usr/local/lib/
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:162 ] Failed to load /usr/local/lib//libafopencl.so.3: cannot open shared object file: No such file or directory
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:141 ] Attempting: /usr/local/arrayfire/lib/
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:162 ] Failed to load /usr/local/arrayfire/lib//libafopencl.so.3: cannot open shared object file: No such file or directory
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:141 ] Attempting: Default System Paths
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:162 ] Failed to load libcudart.so.11.0: cannot open shared object file: No such file or directory
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:141 ] Attempting: .
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:162 ] Failed to load ./libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:141 ] Attempting: ./src/backend/cuda
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:162 ] Failed to load ./src/backend/cuda/libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:141 ] Attempting: ../src/backend/cuda
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:162 ] Failed to load ../src/backend/cuda/libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:141 ] Attempting: src/backend/cuda
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:162 ] Failed to load src/backend/cuda/libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:141 ] Attempting: /opt/arrayfire-3//lib
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:162 ] Failed to load /opt/arrayfire-3//lib/libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:141 ] Attempting: /opt/arrayfire-3//lib64
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:162 ] Failed to load /opt/arrayfire-3//lib64/libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:141 ] Attempting: Default System Paths
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:162 ] Failed to load libcudart.so.11.0: cannot open shared object file: No such file or directory
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:141 ] Attempting: /opt/arrayfire-3/lib/
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:162 ] Failed to load /opt/arrayfire-3/lib//libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:141 ] Attempting: /opt/arrayfire/lib/
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:162 ] Failed to load /opt/arrayfire/lib//libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:141 ] Attempting: /usr/local/lib/
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:162 ] Failed to load /usr/local/lib//libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:141 ] Attempting: /usr/local/arrayfire/lib/
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:162 ] Failed to load /usr/local/arrayfire/lib//libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][1611395394][054177] [ ../src/api/unified/symbol_manager.cpp:206 ] AF_DEFAULT_BACKEND: cpu
Segmentation fault (core dumped)

**Comment by AleksBL** [comment]
My Arrayfire folder is in my home directory, and I see it is doing something in /usr/local/lib, this folder only has libscalapack.a  python2.7  python3.8 folders. Is this problematic?

**Comment by 9prady9** [comment]
Trace output suggests that only CPU backend successfully loaded that would mean either you don't have the CUDA/OpenCL runtimes installed or they are being not found for some reason.


Also, conflicting Intel MKL installations also may cause such erratic behavior with CPU backend.

Have you tried copying the example to the `arrayfire/lib64` and running it from there ? That basically bypasses the need to have proper environment setup as the executable will look for shared libraries in the current folder first.

You can also try to look at the output of 
```bash
readelf -d libafcpu.so
```
to see which libraries are being picked up.

You can also run `ldd libafcpu.so` to see the extensive list of shared libraries used by CPU backend.

You can run the ldd command on the example executable also.

**Comment by AleksBL** [comment]
output of readelf -d libafcpu.so below, trying to copy the example now.....

Dynamic section at offset 0x1b74b58 contains 34 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libmkl_core.so]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libmkl_intel_lp64.so]
 0x0000000000000001 (NEEDED)             Shared library: [libmkl_intel_thread.so]
 0x0000000000000001 (NEEDED)             Shared library: [libiomp5.so]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
 0x000000000000000e (SONAME)             Library soname: [libafcpu.so.3]
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN]
 0x000000000000000c (INIT)               0x34c668
 0x000000000000000d (FINI)               0x163693c
 0x0000000000000019 (INIT_ARRAY)         0x1d1a128
 0x000000000000001b (INIT_ARRAYSZ)       272 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x1d1a238
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x228
 0x0000000000000005 (STRTAB)             0x94220
 0x0000000000000006 (SYMTAB)             0x26330
 0x000000000000000a (STRSZ)              1462640 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x1d85000
 0x0000000000000002 (PLTRELSZ)           89064 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x336a80
 0x0000000000000007 (RELA)               0x202728
 0x0000000000000008 (RELASZ)             1262424 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0x202628
 0x000000006fffffff (VERNEEDNUM)         5
 0x000000006ffffff0 (VERSYM)             0x1f9390
 0x000000006ffffff9 (RELACOUNT)          30162
 0x0000000000000000 (NULL)               0x0

**Comment by 9prady9** [comment]
> output of readelf -d libafcpu.so below, trying to copy the example now.....
> 
> Dynamic section at offset 0x1b74b58 contains 34 entries:
> Tag Type Name/Value
> 0x0000000000000001 (NEEDED) Shared library: [libmkl_core.so]
> 0x0000000000000001 (NEEDED) Shared library: [libpthread.so.0]
> 0x0000000000000001 (NEEDED) Shared library: [libdl.so.2]
> 0x0000000000000001 (NEEDED) Shared library: [libmkl_intel_lp64.so]
> 0x0000000000000001 (NEEDED) Shared library: [libmkl_intel_thread.so]
> 0x0000000000000001 (NEEDED) Shared library: [libiomp5.so]
> 0x0000000000000001 (NEEDED) Shared library: [libm.so.6]
> 0x0000000000000001 (NEEDED) Shared library: [libc.so.6]
> 0x0000000000000001 (NEEDED) Shared library: [ld-linux-x86-64.so.2]
> 0x000000000000000e (SONAME) Library soname: [libafcpu.so.3]
> 0x000000000000001d (RUNPATH) Library runpath: [$ORIGIN]
> 0x000000000000000c (INIT) 0x34c668
> 0x000000000000000d (FINI) 0x163693c
> 0x0000000000000019 (INIT_ARRAY) 0x1d1a128
> 0x000000000000001b (INIT_ARRAYSZ) 272 (bytes)
> 0x000000000000001a (FINI_ARRAY) 0x1d1a238
> 0x000000000000001c (FINI_ARRAYSZ) 8 (bytes)
> 0x000000006ffffef5 (GNU_HASH) 0x228
> 0x0000000000000005 (STRTAB) 0x94220
> 0x0000000000000006 (SYMTAB) 0x26330
> 0x000000000000000a (STRSZ) 1462640 (bytes)
> 0x000000000000000b (SYMENT) 24 (bytes)
> 0x0000000000000003 (PLTGOT) 0x1d85000
> 0x0000000000000002 (PLTRELSZ) 89064 (bytes)
> 0x0000000000000014 (PLTREL) RELA
> 0x0000000000000017 (JMPREL) 0x336a80
> 0x0000000000000007 (RELA) 0x202728
> 0x0000000000000008 (RELASZ) 1262424 (bytes)
> 0x0000000000000009 (RELAENT) 24 (bytes)
> 0x000000006ffffffe (VERNEED) 0x202628
> 0x000000006fffffff (VERNEEDNUM) 5
> 0x000000006ffffff0 (VERSYM) 0x1f9390
> 0x000000006ffffff9 (RELACOUNT) 30162
> 0x0000000000000000 (NULL) 0x0

Looks like expected output

**Comment by AleksBL** [comment]
Left the computer to sit for some time, that changed its mind, now its working. Thanks for the help.....
