### ISSUE TITLE
A function equivalent to Matlab's linspace

### ISSUE THREAD

**Issue by Kerkil** [arrayfire/arrayfire#309]
Is there a function in ArrayFire that is equivalent to Matlab's linspace (http://www.mathworks.com/help/matlab/ref/linspace.html)? If not, what would be the most concise way to implement the operation in ArrayFire?

**Comment by pavanky** [comment]
@Kerkil We have a function called iota that does something similar. However it currently only works with integer sequences. You can multiply the output of iota with the step size and add the initial value to get the similar behavior.

**Comment by Kerkil** [comment]
@pavanky Cool. Thanks.
