### ISSUE TITLE
Disable CPU backend

### ISSUE THREAD

**Issue by zanazakaryaie** [arrayfire/arrayfire#3090]
Hi. Let me first thank you for open sourcing such a great project 

I have installed arrayfire on Ubuntu using the installer files. I can see that it supports CPU, CUDA, and OPENCL. But the CPU backend works very slow compared to OpenCV. So, I'm looking for a way to disable CPU backend. I don't want arrayfire to fallback to CPU backend when CUDA and OPENCL are not available (for any reason). I thought that putting `target_link_libraries(my_exe ArrayFire::afcuda ArrayFire::afopencl)` in CMakeLists.txt can solve this but now `getAvailableBackends()` shows 2 which means only CUDA is available. In other words, the `target_link_libraries` has ignored `ArrayFire::afopencl`.

**Comment by zanazakaryaie** [comment]
It seems that AF_OPENCL_CPU_OFFLOAD=0 will do this

**Comment by 9prady9** [comment]
> 
> 
> Hi. Let me first thank you for open sourcing such a great project
> 
> I have installed arrayfire on Ubuntu using the installer files. I can see that it supports CPU, CUDA, and OPENCL. But the CPU backend works very slow compared to OpenCV. 

There is a reason for such performance difference between ArrayFire's CPU backend and OpenCV. ArrayFire's CPU backend is pure sequential code and doesn't use any SIMD special instructions whatsoever right now. I believe OpenCV does. There are few areas where we might be on par with OpenCV in CPU backend such as blas, ffts where we use wrap around existing upstream libraries such fftw, intel mkl/openblas etc.

> So, I'm looking for a way to disable CPU backend. I don't want arrayfire to fallback to CPU backend when CUDA and OPENCL are not available (for any reason). I thought that putting `target_link_libraries(my_exe ArrayFire::afcuda ArrayFire::afopencl)` in CMakeLists.txt can solve this but now `getAvailableBackends()` shows 2 which means only CUDA is available. In other words, the `target_link_libraries` has ignored `ArrayFire::afopencl`.

That is not the way to just use a subset of backends from available backends. 
```cmake
target_link_libraries(<target> PRIVATE ArrayFire::afcuda ArrayFire::afopencl)
```
By doing that you are essentially linking to two different libraries which is not same as using unified library `ArrayFire::af` that let's you pick and choose the backend you want to target. The logic of backlend fallback in unified backend is unique to it. Currently it is not customisable.

However, if you want to ignore using CPU backend. You would have to write some additional code in your application while using unified backend that checks for available backends. If there are no CUDA and OpenCL backends, you will report the same to your application and exit the application even if CPU backend is availalbe. You can see below the sample logic to do the same using unified library
```c++
    int backends = getAvailableBackends();

    const bool cuda   = backends & AF_BACKEND_CUDA;
    const bool opencl = backends & AF_BACKEND_OPENCL;
    if (!(opencl || cuda)) {
        // ideally you would have your log framework call here
        printf("Neither CUDA nor OpenCL backends available");
        exit(0);
    }
``` 

> It seems that AF_OPENCL_CPU_OFFLOAD=0 will do this

This is not same as not using CPU backend. The purpose of this environment variable is completely different. As mentioned in the documentation [here](https://arrayfire.org/docs/configuring_environment.htm#af_opencl_cpu_offload), this only stops the offload of certain subset of functions not everything.

**Comment by zanazakaryaie** [comment]
I really appreciate the time you put. Thanks for the informative explanations.
