### ISSUE TITLE
Bump from CUDA Runtime 10.1 to 11.2 on Windows

### ISSUE THREAD

**Issue by michaltakac** [arrayfire/arrayfire#3092]
Hello, on Linux, after installing ArrayFire with the official installer, running CUDA examples shows me CUDA Runtime v11.2. Installing ArrayFire on Windows also with the official installer, I'm seeing CUDA Runtime v10.1.

What is need to to use CUDA Runtime 11.2 on Windows? Can you update the version?

With older 10.1. CUDA runtime, my RTX3090 is unusable.

**Comment by 9prady9** [comment]
Sorry, we haven't update the website yet, but the CUDA 11 based windows installers are available via our archive.

http://arrayfire.s3.amazonaws.com/index.html#!/3.8.0%2F

**Comment by 9prady9** [comment]
Our website has also been updated. Once you click the windows button it shall show the user three options of installers each built with respective CUDA toolkit versions.

**Comment by michaltakac** [comment]
Thank you for the clarification!

I've installed the new version of AF 3.8.0 with CUDA Runtime 11.2 but running `helloworld` example tells me that `CUDA runtime version(11.2) not recognized`:

```
ArrayFire Exception (Runtime error :103):
In function void __cdecl cuda::debugRuntimeCheck(class spdlog::logger *,int,int)
In file src\backend\cuda\device_manager.cpp:441
CUDA runtime version(11.2) not recognized. Please create an issue or a pull request on the ArrayFire repository to update the CudaToDriverVersion variable with this version of the CUDA runtime.

 0# af::array::host in afcuda
 1# af::array::host in afcuda
 2# af::array::host in afcuda
 3# af::array::host in afcuda
 4# af::array::host in afcuda
 5# af::array::host in afcuda
 6# af::array::host in afcuda
 7# af::array::host in afcuda
 8# af::array::host in afcuda
 9# main at C:\Program Files\ArrayFire\v3\examples\helloworld\helloworld.cpp:21
10# invoke_main at d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:79
11# __scrt_common_main_seh at d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
12# __scrt_common_main at d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:331
13
```

11.2 is installed on my system.

```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Jan_28_19:41:49_Pacific_Standard_Time_2021
Cuda compilation tools, release 11.2, V11.2.142
Build cuda_11.2.r11.2/compiler.29558016_0
```

I've also added `%AF_PATH%` and `%AF_PATH%/lib` to Path in environment variable settings.

**Comment by 9prady9** [comment]
@michaltakac I am aware of the root cause for this. Sorry about the inconvience. Looks like the version map was updated only for CUDA 11.1 and wasn't for CUDA 11.2. I will create a new installer tonight or tomorrow and will update our website to reflect the same. Will post you an update here once that is done.

**Comment by 9prady9** [comment]
@michaltakac Updated the fixed installer to website. Please try again, you should be good to go now.

**Comment by michaltakac** [comment]
@9prady9 confirming that the latest installer with CUDA 11.2 works as expected on Windows.
