### ISSUE TITLE
[Question] Which versions of CUDA and OpenCL do 3.8.0 and 3.8.1 support?

### ISSUE THREAD

**Issue by cakeislol3** [arrayfire/arrayfire#3101]
Does 3.8.0 support CUDA 10.0 to CUDA 11.2-1  ?
Does 3.8.0 support OpenCL 2.0 and above?

**Comment by 9prady9** [comment]
@cakeislol3

3.8.0 Linux Installer is built with CUDA 11.1 I think. But that wouldn't stop you from using it with 11.2.

3.8.0 Windows Installers built with CUDA 10.1/10.2 and 11.2 are already available on our website - https://arrayfire.com/download/

**Comment by cakeislol3** [comment]
3.8.0 Linux Installer doesn't seem to work with CUDA 11.2-1

**Comment by 9prady9** [comment]
@cakeislol3 Are you using Ubuntu by any chance ? If so, what is you version of Ubuntu ?

Also, what is the output of the following command
```bash
ldd libafcuda.so
```
on your system ?

**Comment by 9prady9** [comment]
If you are using Ubuntu 18.04 or 20.04, you can install arrayfire via the package manager itself following the instructions mentioned in the release blog post - https://arrayfire.com/arrayfire-v3-8-release/

I was able to reproduce a problem with CUDA 11.2 runtime in a docker container. @cakeislol3 What is the error you are getting when using CUDA 11.2 runtime with ArrayFire 3.8 sh installer ? Please share that. Also, please share the info I have requested [here](https://github.com/arrayfire/arrayfire/issues/3101#issuecomment-792624626)

**Comment by cakeislol3** [comment]
Built arrayfire 3.8.1 from source for CUDA 11.2-1 and it works.

**Comment by tensorfoo** [comment]
> If you are using Ubuntu 18.04 or 20.04, you can install arrayfire via the package manager itself following the instructions mentioned in the release blog post - https://arrayfire.com/arrayfire-v3-8-release/
> 
> I was able to reproduce a problem with CUDA 11.2 runtime in a docker container. @cakeislol3 What is the error you are getting when using CUDA 11.2 runtime with ArrayFire 3.8 sh installer ? Please share that. Also, please share the info I have requested [here](https://github.com/arrayfire/arrayfire/issues/3101#issuecomment-792624626

why doesn't the project work with the cuda version in the official 20.04 repository. 

> The following packages have unmet dependencies:
>  arrayfire-cuda3-cuda-10-2 : Depends: cuda-nvrtc-10-2 but it is not installable

I've got 10.1 installed via nvidia-cuda-toolkit. Is there any reason you depend on a non-standard cuda repository? I would rather not add another apt source unless i absolutely have to, especially when there is an official 20.04 package that will see more traffic.
