### ISSUE TITLE
[Perf] CUDA 11 a hundred times slower than CUDA 10 for some kernels

### ISSUE THREAD

**Issue by cschreib-ibex** [arrayfire/arrayfire#3103]
Our application was developed against CUDA 10.1 for a while. We recently attempted to switch to CUDA 11.2 and performance went down dramatically. This seems to touch on the ArrayFire JIT more than CUDA itself:
 - Application running CUDA 10.1 (cached JIT kernels from CUDA 10.1): total run time 2.5s
 - Application running CUDA 11.2 (cached JIT kernels from CUDA 11.2): total run time 8.4s
 - Application running CUDA 11.2 (cached JIT kernels from CUDA 10.1): total run time 2.9s

Description
===========

* Additional information about the performance issues
* Did you build ArrayFire yourself or did you use the official installers? Official installers for both CUDA 10 and 11
* Which backend is experiencing this issue? CUDA
* Do you have a workaround? Implementing custom CUDA kernels
* Can the bug be reproduced reliably on your system? Yes

Reproducible Code
-----------------

```c++
#include <arrayfire.h>
#include <iostream>

using namespace af;

const std::size_t size1 = 1000;
const std::size_t size2 = 10000;

af::array x;
af::array w;

void test_function() {
    af::array r(af::dim4(size1, size2), x.type());
    gfor(af::seq i, static_cast<float>(size2))
    {
        r(af::span, i) = x - (w(i, 0) + x * w(i, 1) + (x * x) * w(i, 2));
    }

    r.eval();
}

int main() {
    try {
        x = af::randn(size1, f32);
        w = af::randn(size2, 3, f32);
        x.eval();
        w.eval();
        af::sync();

        std::cout << timeit(test_function) << std::endl;

        x = af::array();
        w = af::array();
    } catch (const af::exception& e) {
        std::cout << e.what() << std::endl;
    }

    return 0;
}
```

Timing on CUDA 10: 0.0051
Timing on CUDA 11: 0.51

System Information
------------------
ArrayFire Version: 3.8.0
Device: Nvidia GeForce GTX 1070
Operating System: Windows 10 Professionnal
Driver version: 461.40

Checklist
---------
- [x] I have read [timing ArrayFire](http://arrayfire.org/docs/timing.htm)

**Comment by cschreib-ibex** [comment]
Interestingly, the generated `.cu` kernels are the same from `AF_JIT_KERNEL_TRACE`. But the compiled `.bin` are 5 and 8KB in CUDA 10 and 42 and 152KB in CUDA 11.

**Comment by 9prady9** [comment]
I just checked the recent changes that went to caching JIT kernels logic and they are in the past two months so they aren't in 3.8 for sure.

If the source is same, then the binary generated should be identical or similar unless the toolset changed it's processing somehow. That's my first guess, but we would have to look into it to say for certain.

Nevertheless, we have improved caching logic quite a bit after 3.8 and those improvements should be available in 3.8.1 - coming soon.

**Comment by cschreib-ibex** [comment]
I don't think this has to do with kernel caching. If I increase the dimension of the arrays, I can get runtimes of up to ten seconds. The ratio of CUDA 11 to CUDA 10 runtime remains roughly constant.

**Comment by 9prady9** [comment]
Interesting. Needs some investigation then as what change caused this.

**Comment by cschreib-ibex** [comment]
```grep afcuda.dll "device-debug"``` returns a match on the CUDA 11 build of ArrayFire, but not the CUDA 10 build. Are you shipping a debug build by any chance? :)

**Comment by 9prady9** [comment]
We build `RelWithDebInfo` but I doubt that carries full on debug information.

I am confused with the command you shared. How are you grepping a dll with that itself as first argument ? Also `device-debug` seems like a flag passed to compiling CUDA kernels at runtime. Even that shouldn't be there as it is only passed when `NDEBUG` compile option is set. 

If that is the problem `Application running CUDA 11.2 (cached JIT kernels from CUDA 10.1): total run time 2.9s` that scenario wouldn't happen I  think. I will check on the system these packages are built, but I am fairly confident it is a `RelWithDebInfo` build type. not `Debug` build.

**Comment by 9prady9** [comment]
To be sure I double checked, the mistake happened @cschreib-ibex you are correct. It seems I have uploaded a debug installer. I am extremely sorry, I will update a new installer as soon as I can and send out a notification so that 3.8 users can update their windows installations.

**Comment by cschreib-ibex** [comment]
Ahah happens to the best of us. Glad we caught it! And my bad, the grep command was mis-copied. It should have read `grep "device-debug" afcuda.dll`.

**Comment by 9prady9** [comment]
@cschreib-ibex I have uploaded a new CUDA 11.2 based installer, can you please test it out on your end - you can download it from here http://arrayfire.s3.amazonaws.com/index.html#!/3.8.0%2F

**Comment by cschreib-ibex** [comment]
Yes, performance is back to normal with the latest installer. Thank you!
