### ISSUE TITLE
CUDA cannot convolve 1xn kernels whereas opencl can

### ISSUE THREAD

**Issue by AndyP-APSensing** [arrayfire/arrayfire#3104]
It seems that arrayfire with the CUDA backend cannot perform convoutions with a 1 x n kernel, when n is  between 5 and 18.

This code snippet should demonstrate the issue:
```c++
#include <arrayfire.h>
#include <cstdio>
#include <cstdlib>

using namespace af;

af::array myArr;
af::array m_reference;
int m_arr_size;

void bench_convolve() {
    try {
        array convArr = convolve(myArr, m_reference, AF_CONV_DEFAULT, AF_CONV_AUTO);
        printf("%d\n", m_arr_size);
    }
    catch (af::exception& e) {
        //fprintf(stderr, "%s\n", e.what());
        //throw;
    }
}


int main()
{
    af::info();
    myArr = randu(100, 100);


    for (int i=0; i <= 100; i++) {
        m_arr_size = i;
        m_reference = constant(1.0, 1, m_arr_size);
        bench_convolve();

    }
    return 0;
}
```
If compiled with afopencl, values 0 to 100 are printed.
With afcuda, errors are thrown for values between 6 and 17.  

Does anyone have any ideas for this?

**Comment by 9prady9** [comment]
It is perhaps due to some backend specific restriction. I will take a look and get back to you on that soon.

**Comment by 9prady9** [comment]
What I said earlier is correct, CUDA backend has the below restrictions for two dimension spatial convolution:
- Only square kernels/filters are allowed from size 5 to 17
- Non-square shape kernels/filters can have a maximum of 5 size along any dimension

I think these were dictated based on the shared memory usage and performance issues.

I would suggest you go for frequency domain for such sizes.

**Comment by AndyP-APSensing** [comment]
Interesting, thanks for looking into this. I'm using very long filters, so how are these being computed if the maximum length is 5? 

For other people having a similar issue in the future, it appears to work and be more efficient in arrayfire to reorder the data, use the convolve1 function, then reorder the data back (at least for the shape of data I'm working with).

**Comment by 9prady9** [comment]
When you go for filter length 5 with frequency domain, it runs convolution using ffts.

We have explained how batching works in our documentation of convolve - https://arrayfire.org/docs/group__signal__func__convolve.htm. `convolve` is kind of limited in my opinion but it automatically handles 1D, 2D, 3D data based on some expectations. For more better control on bactching, I think it is better to call `convolve1`,  `convolve2` and `convovle3` directly which is what `convolve` ends up calling based on some checks.

Reorder is not really a no-cost operation, so be watchful of additional runtime it adds. If you can tell us what kind of shapes of filters you are targeting and what is your algorithmic logic, perhaps we can suggest a better workaround.

**Comment by 9prady9** [comment]
@AndyP-APSensing Did you get the chance to try above solution ?

**Comment by AndyP-APSensing** [comment]
I managed to use your example, although I generted new arrays rather than transpose in place.  
When comparing the performance without reordering the input arrays, the CUDA backend is faster than the OpenCL, but both are relatively slow.
With reordering of the arrays and using the convolve1 function, interestingly the OpenCL backend is faster than the CUDA backend.  However, due to other custom kernels I'm restricted to the CUDA backend.

**Comment by 9prady9** [comment]
@AndyP-APSensing When you say both are relatively slow, what is the baseline performance you are using ?

**Comment by AndyP-APSensing** [comment]
> @AndyP-APSensing When you say both are relatively slow, what is the baseline performance you are using ?

I was comparing average execution time with two different processing methods:
(a) convolve1 -> convolve(1xN kernel)
(b) convolve1 -> reorder -> convolve1 -> reorder)

For processing a (and choosing a supported 1xN supported by CUDA backend) the processing was approximately 1.2 seconds per payload for OpenCL and 0.9 seconds for CUDA.
However, processing b resulted in OpenCL taking approximately 0.33 seconds whereas CUDA took 0.6 seconds per payload.

I'm assuming the increase in speed is due to the batching, as the arrayfire documentation doesn't specify a batching for data of type [a b 1 1] and kernel [1 n 1 1].

**Comment by 9prady9** [comment]
I think the speedup is due to coalesced memory access. Can you show me the calls for both approaches (a) and (b)
