### ISSUE TITLE
[BUG] Only half threadripper cpu are used during matrix multiplication testing.

### ISSUE THREAD

**Issue by audryste** [arrayfire/arrayfire#3107]
Why threadripper uses only half cpu count ? I have read somwehre that OpenMP head similar issue.
ArrayFire v3.8.0 (CPU, 64-bit Windows, build d99887ae)
[0] AMD: AMD Ryzen Threadripper 3960X 24-Core Processor Benchmark N-by-N matrix multiply at f32
 128 x  128:    76 Gflops
 256 x  256:   380 Gflops
 384 x  384:   515 Gflops
 512 x  512:   665 Gflops
 640 x  640:   848 Gflops
 768 x  768:   861 Gflops
 896 x  896:   862 Gflops
1024 x 1024:   736 Gflops
1152 x 1152:   983 Gflops
1280 x 1280:   959 Gflops
1408 x 1408:  1019 Gflops
1536 x 1536:   975 Gflops
1664 x 1664:  1058 Gflops
1792 x 1792:  1037 Gflops
1920 x 1920:  1084 Gflops
2048 x 2048:   914 Gflops

Code was taken from your website:

> #include <arrayfire.h>

#include <math.h>
#include <stdio.h>
#include <cstdlib>
#include <string>
using namespace af;
// create a small wrapper to benchmark
static array A;  // populated before each timing
static void fn() {
    array B = matmul(A, A);  // matrix multiply
}
int main(int argc, char** argv) {
    af::setBackend(AF_BACKEND_CPU);
    double peak = 0;
    try {
        int device = argc > 1 ? atoi(argv[1]) : 0;
        setDevice(device);
        const std::string dtype(argc > 2 ? argv[2] : "f32");
        const af_dtype dt = (dtype == "f16" ? f16 : f32);
        if (dt == f16)
            printf("Device %d isHalfAvailable ? %s\n", device,
                isHalfAvailable(device) ? "yes" : "no");
        info();
        printf("Benchmark N-by-N matrix multiply at %s \n", dtype.c_str());
        for (int n = 128; n <= 2048; n += 128) {
            printf("%4d x %4d: ", n, n);
            A = constant(1, n, n, dt);
            double time = timeit(fn);  // time in seconds
            double gflops = 2.0 * powf(n, 3) / (time * 1e9);
            if (gflops > peak) peak = gflops;
            printf(" %4.0f Gflops\n", gflops);
            fflush(stdout);
        }
    }
    catch (af::exception& e) {
        fprintf(stderr, "%s\n", e.what());
        throw;
    }
    printf(" ### peak %g GFLOPS\n", peak);
    return 0;
}
![1](https://user-images.githubusercontent.com/26725810/110538812-250c3300-812d-11eb-85a0-1e16c95b917a.png)

**Comment by 9prady9** [comment]
Yes, we do use OpenMP for CPU backend via upstream libraries for BLAS, FFT etc. It could be about Intel OpenMP implementation on AMD CPU causing the perf degradation.

Please try the [environment variable suggested here](https://www.pugetsystems.com/labs/hpc/How-To-Use-MKL-with-AMD-Ryzen-and-Threadripper-CPU-s-Effectively-for-Python-Numpy-And-Other-Applications-1637/#UsingMKL_DEBUG_CPU_TYPE=5withAMDCPU\'s). Hopefully that is the problem here.

**Comment by 9prady9** [comment]
@audryste Did you get a chance to test the technique mentioned the above post ?

**Comment by audryste** [comment]
I just tested it, but it did not help. 
Command set returns one of environment variable MKL_DEBUG_CPU_TYPE=5 confirming that I did right.
I rebuilt the project, but it still only occupies 50% of CPU performance.

**Comment by audryste** [comment]
@9prady9 Any other sugestions?

**Comment by 9prady9** [comment]
You can try `MKL_NUM_THREADS` which is discussed in the following links
- https://scc.ustc.edu.cn/zlsc/chinagrid/intel/mkl/mkl_userguide/GUID-D1E9F205-6AC9-4C9E-9C3C-5879758FBDDD.htm
- http://www.diracprogram.org/doc/release-12/installation/mkl.html

**Comment by audryste** [comment]
It did help. 
Actually it was: export MKL_DYNAMIC="FALSE"
I got 100 CPU utilization. However, matrix multiplication perfomance did not improved. That was very strange. I guess this is another story of MKL library creators. Thank you for help.

**Comment by WilliamTambellini** [comment]
@audryste  it s hard to get good perf from afcpu even with an intel cpu.
Have you tried to set AF_SYNCHRONOUS_CALLS ?

**Comment by audryste** [comment]
I did test but for matrix multiplication perfomance test sample I did not see improviments on 100 % CPU utilization. But it did improve perfomance a little bit small matrices with 50 % CPU utilization. So, it is still good hint for some people :) Thanks guys for help I am closing as solved.

**Comment by 9prady9** [comment]
> @audryste it s hard to get good perf from afcpu even with an intel cpu.
> Have you tried to set AF_SYNCHRONOUS_CALLS ?

To add more context to what William said:

afcpu blas perf would essentially depend on how easy it is to tweak performance of the upstream library we use for BLAS operations. In the case of Linux installer we provide on our website, it is Intel MKL which chooses non-optimal path for non-Intel CPUs. For all other functions which use our hand written code, it is fundamentally serial execution. The actual runtime of a function(if it doesn't use any upstream library) is the time taken for a sequential algorithm of that particular function. So, it wouldn't take advantage of multiple CPU cores as of today. One advantage of arrayfire API being asynchronous is that a function won't block the main/calling thread if it takes too much time to execute as all algorithms run on a separate thread.
