### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by audryste** [arrayfire/arrayfire#3110]
Why copying memory original cudaMalloc with cudaMemcpy is significantly faster than a standard fire array? 

elapsed seconds CopyDataToDeviceCuda way: 0.086729
elapsed seconds CopyDataToDivceFireArrayStandart way: 0.216245

`
const int elemnts = 100000;
float * xArr = new float[elemnts];
void CopyDataToDeviceCuda() 
{ 
    float *device_ptr;
    cudaMalloc((void **)&device_ptr, elemnts * sizeof(float));
    cudaMemcpy(device_ptr, xArr, elemnts * sizeof(float), cudaMemcpyHostToDevice);
    // Convert the CUDA-allocated device memory into an ArrayFire array:    
    copied = array(1, elemnts, device_ptr, afDevice);
}

void CopyDataToDivceFireArrayStandart() 
{ 
    copied = array(1, elemnts, xArr);
}`

ArrayFire v3.8.0 (CUDA, 64-bit Windows, build d99887ae)
Platform: CUDA Runtime 11.2, Driver: 11020
[0] Quadro P2000, 4096 MB, CUDA Compute 6.1

**Comment by 9prady9** [comment]
@audryste About a week or so ago, I have fixed a problem with our CUDA 11.2 based Windows installer which fixed performance issue. If you installed ArrayFire prior to that, can you please re-install ArrayFire for CUDA 11.2 on Windows once again to ensure you have the latest/fixed installer.
