### ISSUE TITLE
[BUG] Precision differences between CUDA, OpenCL and CPU backend

### ISSUE THREAD

**Issue by BA8F0D39** [arrayfire/arrayfire#3121]
Description
===========
For some functions like exponential, there are weird precision differences between the different backends.

On CUDA float32 and exponential function,

```
	arrayfire::set_backend(arrayfire::Backend::CUDA);
	let v0: [f32; 8] = [0.001, 0.0001, 0.00001, 0.000001, 0.0000001, 0.00000001, 0.0, 1.0];
	let mut a0 = arrayfire::Array::new(&v0, arrayfire::Dim4::new(&[8, 1, 1, 1]));

	a0 = arrayfire::exp(&a0);

	arrayfire::print_gen("a0".to_string(), &a0, Some(20));
```

ArrayFire v3.8.0 (CUDA, 64-bit Linux, build d99887ae)
Platform: CUDA Runtime 11.1, Driver: 460.32.03
[0] GeForce RTX 3090, 24267 MB, CUDA Compute 8.6
Arrayfire version: (3, 8, 0)
Name: GeForce_RTX_3090
Platform: CUDA
Toolkit: v11.1
Compute: 8.6
Revision: d99887ae
a0
[8 1 1 1]
    1.00100052356719970703 
    1.00010001659393310547 
    1.00001001358032226562 
    **1.00000107288360595703** 
    1.00000011920928955078 
    1.00000000000000000000 
    1.00000000000000000000 
    2.71828174591064453125 

On POCL CPU OpenCL.

```
	arrayfire::set_backend(arrayfire::Backend::OPENCL);
	let v0: [f32; 8] = [0.001, 0.0001, 0.00001, 0.000001, 0.0000001, 0.00000001, 0.0, 1.0];
	let mut a0 = arrayfire::Array::new(&v0, arrayfire::Dim4::new(&[8, 1, 1, 1]));

	a0 = arrayfire::exp(&a0);

	arrayfire::print_gen("a0".to_string(), &a0, Some(20));
```

Info String:
ArrayFire v3.8.0 (OpenCL, 64-bit Linux, build d99887ae)
[0] POCL: pthread-AMD Ryzen 7 1700X Eight-Core Processor, 29994 MB
Arrayfire version: (3, 8, 0)
Name: pthread-AMD_Ryzen_7_1700X_Eight-Core Processor
Platform: OpenCL
Toolkit: Portable Computing Language
Compute: 1.2
Revision: d99887ae
a0
[8 1 1 1]
    1.00100052356719970703 
    1.00010001659393310547 
    1.00001001358032226562 
    **1.00000095367431640625** 
    1.00000011920928955078 
    1.00000000000000000000 
    1.00000000000000000000 
    2.71828174591064453125 

On Intel MKL CPU backend

```
	arrayfire::set_backend(arrayfire::Backend::CPU);
	let v0: [f32; 8] = [0.001, 0.0001, 0.00001, 0.000001, 0.0000001, 0.00000001, 0.0, 1.0];
	let mut a0 = arrayfire::Array::new(&v0, arrayfire::Dim4::new(&[8, 1, 1, 1]));

	a0 = arrayfire::exp(&a0);

	arrayfire::print_gen("a0".to_string(), &a0, Some(20));
```

ArrayFire v3.8.0 (CPU, 64-bit Linux, build d99887ae)
[0] Intel: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHzArrayfire version: (3, 8, 0)
Name: Intel
Platform: CPU
Toolkit: GNU Compiler Collection(GCC/G++) 7.5.0
Compute: 0.0
Revision: d99887ae
[0] Intel: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHza0
[8 1 1 1]
    1.00100052356719970703 
    1.00010001659393310547 
    1.00001001358032226562 
    **1.00000095367431640625** 
    1.00000011920928955078 
    1.00000000000000000000 
    1.00000000000000000000 
    2.71828174591064453125

**Comment by 9prady9** [comment]
I was able to reproduce this locally. I shall investigate about why the fourth value only comes out like that even though the 5th and 6th values are much smaller values.

**Comment by 9prady9** [comment]
Just gathering info here
- On reported user system_(RTX 3090,AMD_Ryzen_7_1700X)_: CUDA backend differs from CPU_(Intel: Intel(R) Core(TM) i5-8400 CPU)_/OpenCL
- On my system _(AMD A10 Kaveri, GTX 1060)_: CPU backend differs from CUDA/OpenCL

I am beginning to think this is card/driver specific or some sort of rounding issue on GPUs, but I am not certain about anything yet because only one particular value seems to be effected by what ever is the cause - oddly. Still investigating.

**Comment by 9prady9** [comment]
Based on what I gathered from floating point standards and their errors on CPUs and GPUs, my initial suspicion is correct. It is a floating point arithmetic error. 

I also found a straightforward query on CUDA forums that exactly poses the question you reported here. May be it is your question I wouldn't know. Here is the link to the question https://forums.developer.nvidia.com/t/why-accuracy-cpu-and-gpu-not-equal/35316/1

You will find all the necessary explanation for why the difference in outputs for GPU vs CPU. Note that OpenCL backend in the output shared in original description is actual a CPU device.

**Comment by BA8F0D39** [comment]
Sparse operations are weird on OpenCL and CUDA.


For example sparse multiplication on CUDA.
```
	let dims = arrayfire::Dim4::new(&[4,4,1,1]);
	let a = arrayfire::randu::<f32>(dims);
	
	arrayfire::print_gen("a".to_string(), &a,Some(20));

	let sa =  arrayfire::sparse_from_dense(&a ,arrayfire::SparseFormat::CSR);
	let b = arrayfire::randu::<f32>(dims);
	
	arrayfire::print_gen("b".to_string(), &b,Some(20));

	let c =  arrayfire::matmul(&sa, &b, arrayfire::MatProp::NONE, arrayfire::MatProp::NONE);
	
	arrayfire::print_gen("c".to_string(), &c,Some(20));

```

Info String:
ArrayFire v3.8.0 (CUDA, 64-bit Linux, build d99887ae)
Platform: CUDA Runtime 11.1, Driver: 460.32.03
[0] GeForce RTX 3090, 24267 MB, CUDA Compute 8.6
Arrayfire version: (3, 8, 0)
a
[4 4 1 1]
    0.60095351934432983398     0.06546384096145629883     0.75087487697601318359     0.35434550046920776367 
    0.02775877714157104492     0.54967379570007324219     0.41050708293914794922     0.64502882957458496094 
    0.98055058717727661133     0.28638768196105957031     0.15832817554473876953     0.96748882532119750977 
    0.21263223886489868164     0.34101694822311401367     0.37124758958816528320     0.36364042758941650391 

b
[4 4 1 1]
    0.41647815704345703125     0.67545986175537109375     0.78960984945297241211     0.29075437784194946289 
    0.58144479990005493164     0.61051392555236816406     0.89661705493927001953     0.99409437179565429688 
    0.89618861675262451172     0.52324867248535156250     0.05363517999649047852     0.51427721977233886719 
    0.37121456861495971680     0.55665528774261474609     0.57745659351348876953     0.36702525615692138672 

c
[4 4 1 1]
    1.09281134605407714844     1.03602910041809082031     0.77810728549957275391     0.75601863861083984375 
    0.93850171566009521484     0.92818945646286010742     0.90925931930541992188     1.00235486030578613281 
    1.07593441009521484375     1.45856904983520507812     1.59820723533630371094     1.00631308555603027344 
    0.75453567504882812500     0.74849736690521240234     0.70355659723281860352     0.72521615028381347656 





The same code on POCL OpenCL CPU runtime.

Info String:
ArrayFire v3.8.0 (OpenCL, 64-bit Linux, build d99887ae)
-0- NVIDIA: GeForce RTX 3090, 24267 MB
[1] POCL: pthread-Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz, 29990 MB
Arrayfire version: (3, 8, 0)
Name: pthread-Intel(R)_Core(TM)_i5-8400 CPU @ 2.80GHz
Platform: OpenCL
Toolkit: Portable Computing Language
Compute: 1.2
Revision: d99887ae
ArrayFire v3.8.0 (OpenCL, 64-bit Linux, build d99887ae)
-0- NVIDIA: GeForce RTX 3090, 24267 MB
[1] POCL: pthread-Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz, 29990 MB
a
[4 4 1 1]
    0.60095351934432983398     0.06546384096145629883     0.75087487697601318359     0.35434550046920776367 
    0.02775877714157104492     0.54967379570007324219     0.41050708293914794922     0.64502882957458496094 
    0.98055058717727661133     0.28638768196105957031     0.15832817554473876953     0.96748882532119750977 
    0.21263223886489868164     0.34101694822311401367     0.37124758958816528320     0.36364042758941650391 

b
[4 4 1 1]
    0.41647815704345703125     0.67545986175537109375     0.78960984945297241211     0.29075437784194946289 
    0.58144479990005493164     0.61051392555236816406     0.89661705493927001953     0.99409437179565429688 
    0.89618861675262451172     0.52324867248535156250     0.05363517999649047852     0.51427721977233886719 
    0.37121456861495971680     0.55665528774261474609     0.57745659351348876953     0.36702525615692138672 

c
[4 4 1 1]
    1.09281134605407714844     1.03602910041809082031     0.77810728549957275391     0.75601869821548461914 
    0.93850171566009521484     0.92818945646286010742     0.90925925970077514648     1.00235497951507568359 
    1.07593441009521484375     1.45856904983520507812     1.59820723533630371094     1.00631320476531982422 
    0.75453567504882812500     0.74849730730056762695     0.70355659723281860352     0.72521620988845825195

**Comment by BA8F0D39** [comment]
![image](https://user-images.githubusercontent.com/4108137/114503414-22947180-9be2-11eb-9eff-21299c0f7e09.png)


![image](https://user-images.githubusercontent.com/4108137/114503472-38099b80-9be2-11eb-8855-8c265b3eccd3.png)

**Comment by 9prady9** [comment]
@BA8F0D39 Sorry about the delay, I am looking into any potential programmatic approaches or compiler flags to help such cases. 

As far as I am aware of till date, such accumulated floating point errors have to be handled in the application code as how this error propogates is dependent upon the type of repetitive operations that are taking place.

Please have a look at this paper http://developer.download.nvidia.com/assets/cuda/files/NVIDIA-CUDA-Floating-Point.pdf to get an idea of behaviour you are experiencing. Section 2.2 on on operations and accuracy.


For example, a single matmul call only take care of the error that may come about in that one operation. Error propagation across multiple API calls needs to be handled at the caller level.

@umar456 any hints to try ?

**Comment by BA8F0D39** [comment]
I'll try to use float64 but it seems to be 2x slower.
