### ISSUE TITLE
Linux Build Instructions needs updated boost release link

### ISSUE THREAD

**Issue by brianmcconnel** [arrayfire/arrayfire#3133]
The following item in the linux build instructions is no longer accessible. 
wget https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.gz

https://github.com/arrayfire/arrayfire/wiki/Build-Instructions-for-Linux

Would it be better to point users here:
https://www.boost.org/users/download/#history

**Comment by 9prady9** [comment]
@brianmcconnel Thank you for pointing it out. I have addressed the problem.
