### ISSUE TITLE
[Build]

### ISSUE THREAD

**Issue by agarza5724** [arrayfire/arrayfire#3146]
mysterious cmake error :

#begin error

MKL: Thread Layer(Intel OpenMP) Interface(4-byte Integer)
CMake Error at CMakeModules/FindMKL.cmake:158 (if):
  if given arguments:

    "GREATER_EQUAL" "1900"

  Unknown arguments specified

#end error

Build Environment
-----------------
Compiler version: TDMGCC 10.3.0
Operating system: Windows 10
Build environment: TDMGCC 10.3.0, cmake 3.18.0

**Comment by martin-frbg** [comment]
You'll need to look at iine 158 of the file FindMKL.cmake -- it will  have a conditional instruction like "if <some variable> is greater or equal 1900 do something" and "<some variable>" happens to be undefined in your case. Looking at the current github version of this project, it appears to go looking for the Microsoft Visual C version if it thinks you are on Windows.

**Comment by agarza5724** [comment]
Thank you for responding Martin. I installed MS build tools to its default
location as indicated by this article:
https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-160.
after installation, it prompts you to restart windows 10. I switched
arrayfire builds to v3.7.3 and reran cmake, but the error still persists.
My goal is to get arrayfire successfully built for TDMGCC (latest version).
I don't know if this is really possible, but perhaps the issues i run into
could prove valuable for others. I appreciate you taking the time to look
into this.

**Comment by 9prady9** [comment]
@agarza5724 What is the version/commit that you are building ? Current master has no `IF`  on line 158. What is the initial output of cmake , can you please share that. CMake print's the compiler it is using. If Visual C++ is available, `MSVC_VERSION` variable that is checked against target version `1900`  would work as expected. However, if compiler isn't available, then I would expect CMake to complain much earlier than in `FindMKL` module. Can you please verify your VS installation by creating a simple c++ helloworld example using cmake.

**Comment by agarza5724** [comment]
greetings pradeep,
i am attempting arrayfire v3.7.3. i fixed an issue i had with msbuild tools
and reran cmake from a visual studio command promt. cmake does work with a
few dependencies missing( i'll fix those later). i'll attach my log files
if you prefer to see those.thank you for your help

**Comment by 9prady9** [comment]
Sounds like original issue reported is related to broken VS build tools installation. Therefore, I am going to close the issue. If you face other issues during the build, please feel free to open a new one with corresponding info. You are also welcome to post your queries on our slack community channel.
