### ISSUE TITLE
vcpkg install flashlight-cpu:x64-windows error

### ISSUE THREAD

**Issue by bitnick10** [arrayfire/arrayfire#3154]
Description
===========

Error Log
---------
eaning for the packages you specify.
-- Extracting source C:/Programs/vcpkg/downloads/arrayfire-arrayfire-59ac7b980d1ae124aae914fb29cbf086c948954d.tar.gz
-- Applying patch build.patch
-- Using source at C:/Programs/vcpkg/buildtrees/arrayfire/src/86c948954d-c996b9f837.clean
-- Using C:/Programs/vcpkg/downloads/arrayfire-threads-b666773940269179f19ef11c8f1eb77005e85d9a.tar.gz
-- Cleaning sources at C:/Programs/vcpkg/buildtrees/arrayfire/src/7005e85d9a-64aebcce4b.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Programs/vcpkg/downloads/arrayfire-threads-b666773940269179f19ef11c8f1eb77005e85d9a.tar.gz
-- Using source at C:/Programs/vcpkg/buildtrees/arrayfire/src/7005e85d9a-64aebcce4b.clean
-- Using C:/Programs/vcpkg/downloads/arrayfire-forge-1a0f0cb6371a8c8053ab5eb7cbe3039c95132389.tar.gz
-- Cleaning sources at C:/Programs/vcpkg/buildtrees/arrayfire/src/9c95132389-511398ace8.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Programs/vcpkg/downloads/arrayfire-forge-1a0f0cb6371a8c8053ab5eb7cbe3039c95132389.tar.gz
-- Using source at C:/Programs/vcpkg/buildtrees/arrayfire/src/9c95132389-511398ace8.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: ninja -v
    Working Directory: C:/Programs/vcpkg/buildtrees/arrayfire/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Programs\vcpkg\buildtrees\arrayfire\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:323 (vcpkg_execute_required_process)
  ports/arrayfire/portfile.cmake:69 (vcpkg_configure_cmake)
  scripts/ports.cmake:139 (include)
```

```
cmake
Build Environment
-----------------
Compiler version: Vcpkg version: 2021-05-05-b110959e13f562c2a17d7bd9e352e2dd8d6dc603 Visual studio 2019 16.10
Operating system: Windows 10
Build environment: vcpkg

**Comment by 9prady9** [comment]
@bitnick10 Did you check the vcpkg logs if any required dependencies are being reported as missing by vcpkg ?

**Comment by bitnick10** [comment]
@9prady9 
-- Could NOT find OpenCL (missing: OpenCL_LIBRARY OpenCL_INCLUDE_DIR) 
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "9.0")
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Could NOT find cuDNN (missing: cuDNN_LINK_LIBRARY cuDNN_INCLUDE_DIRS) (Required is at least version "4.0")
-- Could NOT find OpenCL (missing: OpenCL_LIBRARY OpenCL_INCLUDE_DIR) (Required is at least version "1.2")
-- Could NOT find FreeImage (missing: FreeImage_INCLUDE_DIR FreeImage_LINK_LIBRARY) 
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Could NOT find FFTW (missing: FFTW_INCLUDE_DIR FFTW_LIBRARY FFTWF_LIBRARY) 
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Could NOT find LAPACK (missing: LAPACK_INCLUDE_DIR LAPACK_LIBRARIES) 
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Could NOT find MKL: Source the compilervars.sh or mklvars.sh scripts included with your installation of MKL. This script searches for the libraries in MKLROOT, LIBRARY_PATHS(Linux), and LIB(Windows) environment variables (missing: MKL_INCLUDE_DIR MKL_Core_LINK_LIBRARY MKL_Interface_LINK_LIBRARY MKL_ThreadLayer_LINK_LIBRARY) 
-- Could NOT find MKL: Source the compilervars.sh or mklvars.sh scripts included with your installation of MKL. This script searches for the libraries in MKLROOT, LIBRARY_PATHS(Linux), and LIB(Windows) environment variables (missing: MKL_INCLUDE_DIR MKL_Core_STATIC_LINK_LIBRARY MKL_Interface_STATIC_LINK_LIBRARY MKL_ThreadLayer_STATIC_LINK_LIBRARY) 
-- Could NOT find OpenCL (missing: OpenCL_LIBRARY OpenCL_INCLUDE_DIR) 
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "9.0")
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Could NOT find cuDNN (missing: cuDNN_LINK_LIBRARY cuDNN_INCLUDE_DIRS) (Required is at least version "4.0")
-- Could NOT find OpenCL (missing: OpenCL_LIBRARY OpenCL_INCLUDE_DIR) (Required is at least version "1.2")
-- Could NOT find FreeImage (missing: FreeImage_INCLUDE_DIR FreeImage_LINK_LIBRARY) 
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Could NOT find FFTW (missing: FFTW_INCLUDE_DIR FFTW_LIBRARY FFTWF_LIBRARY) 
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Could NOT find LAPACK (missing: LAPACK_INCLUDE_DIR LAPACK_LIBRARIES) 
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Could NOT find MKL: Source the compilervars.sh or mklvars.sh scripts included with your installation of MKL. This script searches for the libraries in MKLROOT, LIBRARY_PATHS(Linux), and LIB(Windows) environment variables (missing: MKL_INCLUDE_DIR MKL_Core_LINK_LIBRARY MKL_Interface_LINK_LIBRARY MKL_ThreadLayer_LINK_LIBRARY) 
-- Could NOT find MKL: Source the compilervars.sh or mklvars.sh scripts included with your installation of MKL. This script searches for the libraries in MKLROOT, LIBRARY_PATHS(Linux), and LIB(Windows) environment variables (missing: MKL_INCLUDE_DIR MKL_Core_STATIC_LINK_LIBRARY MKL_Interface_STATIC_LINK_LIBRARY MKL_ThreadLayer_STATIC_LINK_LIBRARY)

**Comment by 9prady9** [comment]
vcpkg doesn't install complex software dependencies such as CUDA, Intel-MKL, it only checks if there is working installation only. 

Looks like most of them are missing from your system or their installation is broken because usually vcpkg should be able to pick them up if they are installed to standard locations.

Please go through the list of dependencies for ArrayFire and Flashlight on Windows and ensure they are installed on your system. The ones I know vcpkg doesn't handle are CUDA and Intel-MKL. so please check those. I am not aware of flashlight dependencies so please check their wiki page.
