### ISSUE TITLE
[Build] Intel OpenMP on Windows is called libiomp5md.dll/.lib

### ISSUE THREAD

**Issue by tvandera** [arrayfire/arrayfire#3155]
[Build] Intel OpenMP on Windows is called `libiomp5md.dll/.lib` but `findMKL.cmake` looks for `libiomp5.dll/.lib`

-  Intel OpenMP on Windows is called `libiomp5md.dll/.lib`, see docs [here](https://software.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/optimization-and-programming-guide/openmp-support/openmp-library-support/openmp-support-libraries.html)
-  findMKL.cmake: https://github.com/arrayfire/arrayfire/blob/2a2b677431992a8e73b6724bb61e5e3af0c572e0/CMakeModules/FindMKL.cmake#L328
- Building with `MKL_THREAD_LAYER=TBB` works fine on windows.

How do you build binary releases on Windows? With TBB?

**Comment by 9prady9** [comment]
What does the cmake cache variable `MKL_ThreadingLibrary_LINK_LIBRARY` point to in your build setup ?

**Comment by tvandera** [comment]
Hi, it's set as NOTFOUND, see:
https://dev.azure.com/tomvanderaa/tomvanderaa/_build/results?buildId=10&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f&l=14987

**Comment by 9prady9** [comment]
Master branch is finding the correct file for me on windows. what is the branch/commit/version you are building on windows ?

Is Intel-MKL setup correctly ? that is you have to call `setvars` script of oneMKL installation to properly setup Intel-MKL. If it is legacy Intel-MKL, then the name of the setup script is slightly different.

**Comment by tvandera** [comment]
Cool, I'll have a look at `master` and let you know.

**Comment by tvandera** [comment]
Indeed, works fine in `master`, https://github.com/arrayfire/arrayfire/blob/2a2b677431992a8e73b6724bb61e5e3af0c572e0/CMakeModules/FindMKL.cmake#L171

I was making a conda release for ArrayFire 3.7.3, but it also seems ok there:

https://github.com/arrayfire/arrayfire/blob/49b794ab4193e5d976f78f7b6378c545ba3aaf0d/CMakeModules/FindMKL.cmake#L161

Maybe it is Conda-related. I will look further and close this issue here for now.
T.

**Comment by tvandera** [comment]
Seems to be a known conda issue:

https://community.intel.com/t5/Intel-Distribution-for-Python/conda-windows-intel-mkl/td-p/1171643
