### ISSUE TITLE
void cuda::reorder slow when using .device to grab pointer

### ISSUE THREAD

**Issue by AndyP-APSensing** [arrayfire/arrayfire#3172]
I have an algorithm that's intended to run in real-time that performs a few convolution operations in arrayfire (some reorder operations are required so convolve1 can be used), then grabs a pointer to the block of data to run my own CUDA kernel on the data.  When analysing the performance with the Nvidia Visual Profiler, the void cuda::reorder process is taking over 50% of the time.
Is there any way to tell ArrayFire to not perform any reordering or transposing operation when grabbing the pointer, so I can adjust where I grab the data from in my CUDA kernel?

**Comment by umar456** [comment]
I am not sure I understand your question. It sounds to me like you are calling reorder in your code. I don't think the device call will call any reorder operations unless the operation is already part of the queue. Could you provide some code that demonstrates what you are seeing?

**Comment by AndyP-APSensing** [comment]
I've now taken a more detailed look at my code and realised there was an unnessesary reorder operation that I've now removed.
