### ISSUE TITLE
Unknown kernels in NVIDIA visual profiler

### ISSUE THREAD

**Issue by AndyP-APSensing** [arrayfire/arrayfire#3173]
When analysing code performance in NVIDIA visual profiler, there are lots of kernels named similar to KER3175306122031000704.  Is there a way to tell which processes/arrayfire calls these are associated with?

**Comment by umar456** [comment]
What you are seeing are kernels that have been generated at runtime. These kernels are based element wise operations on the af::array object. You can see the contents of these kernels if you set the AF_JIT_KERNEL_TRACE environment variable to a directory or stdout or stderr. 

Example:

AF_JIT_KERNEL_TRACE=stdout ./your_application

**Comment by AndyP-APSensing** [comment]
Thanks, I'm now able to view the contents of the .cu files this generates and can try and trace this back to specific operations in my code.
