### ISSUE TITLE
64 bit integer support

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#318]
Initial support for the following operations:

- add, sub, mul, div
- lt, gt, le, ge, eq, ne
- and, or, bitor, bitand, bitxor
- cast
- lshift, rshift 

Types will include the following:

- s64, i64

**Comment by pavanky** [comment]
@bkloppenborg Anything else that you think might be necessary ?

**Comment by bkloppenborg** [comment]
Right and left bitshift.

**Comment by pavanky** [comment]
Other functions to support include:

```
constant(...)
randu(...)
```
