### ISSUE TITLE
[BUG] The shift() function fails on the CUDA backend.

### ISSUE THREAD

**Issue by Atliac** [arrayfire/arrayfire#3186]
Description
===========
The following codes can't run with the CUDA backend. The CPU and OpenCL function well.

Reproducible Code and/or Steps
------------------------------
```
int main(int argc, char *argv[])
{
    try
    {
        setBackend(AF_BACKEND_CUDA);
        cout << af::infoString() << endl;
        auto v = randu({2, 2});
        af_print(shift(v, 1));
    }
    catch (af::exception &e)
    {
        fprintf(stderr, "%s\n", e.what());
        throw;
    }

    return 0;
}
```
System Information
------------------

ArrayFire v3.8.0 (CUDA, 64-bit Windows, build d99887ae)
Platform: CUDA Runtime 11.2, Driver: 11030
[0] NVIDIA GeForce GTX 1060 6GB, 6144 MB, CUDA Compute 6.1

Checklist
---------

- [x] Using the latest available ArrayFire release
- [x] GPU drivers are up to date

**Comment by umar456** [comment]
What error are you experiencing? Is the result incorrect or are you experiencing an exception? I am able to run it on my system:

```
ArrayFire v3.9.0 (CUDA, 64-bit Linux, build 1ff07ca29)
Platform: CUDA Runtime 11.5, Driver: 495.44
[0] Quadro T2000, 3915 MB, CUDA Compute 7.5

v
[2 2 1 1]
    0.6010     0.9806 
    0.0278     0.2126 

shift(v, 1)
[2 2 1 1]
    0.0278     0.2126 
    0.6010     0.9806 
```

**Comment by Atliac** [comment]
Awkward!
It looks like I did something wrong.
I tried it again today. It works well. 
Thanks for the reply.
