### ISSUE TITLE
How to use arrayfire after build arrayfire on Windows 

### ISSUE THREAD

**Issue by goudanzw** [arrayfire/arrayfire#3191]
Hello, I try to build Arrayfire from source on Windows with CUDA backend. Now I have been get the afcuda.dll and the afcuda.lib. And I have been get installed by using Visual Studio. But when I use the Arrayfire to create code. I found that my afcuda.dll is only 187608KB. I don't know what happend with my build? Please give an answer.
![QQ截图20211119155226](https://user-images.githubusercontent.com/92415225/142586065-d0bb82fe-148e-4abb-aa7a-c25126b08a8e.png)

**Comment by goudanzw** [comment]
![cmd](https://user-images.githubusercontent.com/92415225/142624279-b71a859b-3f22-4453-9765-75fbc1caaeec.png)
While I run code  I meet this question

**Comment by umar456** [comment]
187MB seems reasonable. It looks like you are building a debug build. Can you try to create a Release build?

**Comment by goudanzw** [comment]
> 187MB seems reasonable. It looks like you are building a debug build. Can you try to create a Release build?

Thanks, by create a Release build I solve the problem.
