### ISSUE TITLE
How to use regions with batch support

### ISSUE THREAD

**Issue by goudanzw** [arrayfire/arrayfire#3196]
I want to ues regions with batch support. But I don't know how to use it. Can you give me an example which regions using in 3D array.

**Comment by 9prady9** [comment]
@goudanzw regions doesn't have batch support as of now. You would have to use a for loop for the slices of the 3d array

**Comment by goudanzw** [comment]
> @goudanzw regions doesn't have batch support as of now. You would have to use a for loop for the slices of the 3d array

Ok, thanks a lot.
