### ISSUE TITLE
Interfacing with other GPU libraries

### ISSUE THREAD

**Issue by Kerkil** [arrayfire/arrayfire#320]
I am using ViennaCL for linear algebra functions on GPU. I need to copy/move the data on device (GPU) between ArrayFire and ViennaCL. To do this in OpenCL, I need to access OpenCL context with devices and command queues that was initialized by ArrayFire. Here is info on a similar task in ViennaCL (https://github.com/viennacl/viennacl-dev/issues/114#issuecomment-69395428). How can I access the context and also raw pointer to memory on device in ArrayFire to interface with other GPU libraries?

I am also interested to know if a similar thing can be done with CUDA.

**Comment by Kerkil** [comment]
Along a similar line, is there a way to call a custom kernel in ArrayFire?

**Comment by pavanky** [comment]
@Kerkil You can get the device pointer / buffer from ArrayFire. We infact have a blog post explaining how you can do this over here:

http://arrayfire.com/custom-kernels-with-arrayfire/

Although, the post refers to ArrayFire 2.1, the same things are applicable even now. Examples of custom CUDA and OpenCL kernels can be found in the following links:

- https://github.com/arrayfire/arrayfire_examples/tree/master/opencl
- https://github.com/arrayfire/arrayfire_examples/tree/master/cuda

Please note that we currently have no way to expose the commandQueues in OpenCL. The suggested method here is to make sure every task is synchronized in arrayfire by calling `af::sync()` and then calling your custom function. Information about this is available in the blog post linked at the top.

**Comment by Kerkil** [comment]
@pavanky Thanks. Would it be possible for me to interface ArrayFire with ViennaCL given that the command queues are not exposed? If so, is calling af::sync() offering a solution to that problem as well?

**Comment by pavanky** [comment]
@Kerkil You can definitely interface with ViennaCL. However you will have to call `af::sync()` first and then create / use your own commandQueue. You can use the `helper.h` and `simple.h` files from the opencl example linked above to make things easier for you.

https://github.com/arrayfire/arrayfire_examples/blob/master/opencl/simple.h
https://github.com/arrayfire/arrayfire_examples/blob/master/opencl/helper.h

**Comment by Kerkil** [comment]
@pavanky Great! I will look into it and will get back to you if I have questions. Appreciate your help. Please allow me to keep this question open until I test a few simple cases.

**Comment by Kerkil** [comment]
@pavanky One of the helper functions failed in the case where there are more than one device detected. I am not sure how I can get the number of devices to avoid the error. This code block 
``` 
cl_device_id device;
cl_int err = clGetContextInfo(context, CL_CONTEXT_DEVICES, sizeof(cl_device_id), &device, NULL);
if (err != CL_SUCCESS) {
    printf("OpenCL Error(%d): Failed to get device from context\n");
    throw (err);
}
```
results in the error
```
OpenCL Error(0): Failed to get device from context
```

If I change the code to 
``` 
cl_device_id devices[3];
cl_int err = clGetContextInfo(context, CL_CONTEXT_DEVICES, sizeof(devices), devices, NULL);
if (err != CL_SUCCESS) {
    printf("OpenCL Error(%d): Failed to get device from context\n");
    throw (err);
}
```
then it compiles and runs OK. However, I do not like hardcode the number of devices since it won't be portable. Is there a way to get only the device(s) being used by ArrayFire?

**Comment by pavanky** [comment]
@Kerkil The context should just return one device. I am not sure why it is returning multiple devices. I will look into it tomorrow.

**Comment by Kerkil** [comment]
@pavanky Thanks. Not sure if you need this info. But I am using a Macbook Pro which has 3 OpenCL devices: CPU, Nvidia GPU, and Intel Integrated GPU. clGetContextInfo tried to return all three devices.

**Comment by pavanky** [comment]
@Kerkil I added `afcl::getContext()`, `afcl::getQueue()` and `afcl::getDeviceId()` as helper functions. You should now include `af/opencl.h` (not included by default) to call these functions instead of following the example I linked above. This should make things much easier to interop with other libraries. Please let me know if this works.

**Comment by Kerkil** [comment]
@pavanky Awesome! I will test them and will get you posted. Thanks a lot for the help.

**Comment by kerkilchoi** [comment]
@pavanky I got a build error while building the new devel branch. Looks like af/opencl.h is having trouble locating OpenCL's cl.h on Mac OSX.
```
[ 69%] Building CXX object src/backend/opencl/CMakeFiles/afopencl.dir/platform.cpp.o
In file included from /Users/kerkil/Git/arrayfire/src/backend/opencl/platform.cpp:11:
/Users/kerkil/Git/arrayfire/include/af/opencl.h:10:10: fatal error: 'CL/cl.h' file not found
#include <CL/cl.h>
         ^
1 error generated.
make[2]: *** [src/backend/opencl/CMakeFiles/afopencl.dir/platform.cpp.o] Error 1
make[1]: *** [src/backend/opencl/CMakeFiles/afopencl.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by pavanky** [comment]
@kerkilchoi oops, I forgot about OSX. I updated devel to fix this.

**Comment by kerkilchoi** [comment]
@pavanky Thanks. I temporarily fixed with by changing
```
#include<CL/cl.h>
```
 to
```
#include <OpenCL/OpenCL.h>
```
and built it. I will go ahead and test the code while you update it. Thanks for the help again.

**Comment by Kerkil** [comment]
This code still results in error (CL_ERROR=-30)
```   
    cl_context ctx = afcl::getContext();
    cl_command_queue queue = afcl::getQueue();
    cl_device_id device;

    cl_int err = clGetContextInfo(ctx, CL_CONTEXT_DEVICES,
                              sizeof(device), &device,
                              NULL);
    std::cout << err << std::endl; // This produces -30.
```
Is there a way to check which device is being used by the context returned by `afcl::getContext()`?

**Comment by pavanky** [comment]
@Kerkil You can just use `afcl::getDeviceId()`. It will give you the device id of the current device!

**Comment by pavanky** [comment]
@Kerkil @kerkilchoi Let me know if the issue is resolved.

**Comment by Kerkil** [comment]
@pavanky This somehow creates a linking error:
```
    af::array A(N, N, f32);
    float *dA = A.device<float>();
    af::sync();
    A.unlock();
```
Here is the error log:
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -stdlib=libc++ -mmacosx-version-min=10.7 -o Linspace main.o   -L/usr/local/lib -lafopencl -lafcpu -L/Users/recondev/Git/clBLAS/build/package/lib64 -lclBLAS -framework OpenCL 
Undefined symbols for architecture x86_64:
  "af::array::unlock() const", referenced from:
      wallfilter(unsigned int, unsigned int) in main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Linspace] Error 1
10:10:52: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project Linspace (kit: osx64)
When executing step "Make"
```

**Comment by pavanky** [comment]
@Kerkil A.unlock() is not implemented in 3.0. As far as I can tell, You don't need this in ArrayFire right now.

Also, please do not post unrelated issues under a single subject. If the original issue is resolved, please close this and open tickets for anything else you face.

**Comment by Kerkil** [comment]
@pavanky Sorry for the confusion. Just to be clear, these things were in the example that you provided as an example of calling the custom kernel and also as a means of interfacing with other GPU libraries, which is the original intent of this post.

In my current testing, after I call a function from another GPU library, I tried to return the control of the same device memory to ArrayFire, at which point I bumped into the error posted. So, I thought it was related. 

In the blog post, A.unlock() is used to give the control back to ArrayFire. Is this implicitly done when interfacing with other GPU libraries then in ArrayFire 3.0? I am not clear about how ArrayFire 3.0 figures out when to take the control back after the other libraries finish processing the memory.

Thanks for your help.

**Comment by pavanky** [comment]
@Kerkil 

Right now ArrayFire arrays are not relinquishing control over the buffers. So you will need to make sure the original variable is not going out of scope while you are using the pointer / cl_mem object.

The reason for this is that forcing users to use `var.unlock()` caused many usage problems and memory leaks. This is the reason we decided not to relinquish control by default.

We will be implementing a function that explicitly asks ArrayFire to give up control to the users in the future.

**Comment by Kerkil** [comment]
@pavanky Thanks for the clarification.
