### ISSUE TITLE
FFT

### ISSUE THREAD

**Issue by goudanzw** [arrayfire/arrayfire#3200]
When I run the same FFT multiple times, will the FFT plan be created and destroyed repeatedly?

**Comment by 9prady9** [comment]
If the plan has similar characteristics, no that won't happen as we cache the plans and reuse them whenever possible.

**Comment by goudanzw** [comment]
> If the plan has similar characteristics, no that won't happen as plans are cached and reused whenever possible.

The plan is all same, so fft will run FFT plan and destory once?

**Comment by 9prady9** [comment]
yes, it will be created once, reused and destroyed when program exits or when the cache is full and new plan needs  to be accomodated.

**Comment by goudanzw** [comment]
> yes, it will be created once, reused and destroyed when program exits or when the cache is full and new plan needs to be accomodated.

Thanks a lot, I get it.
