### ISSUE TITLE
[Perf] Test calculation time CPU/CUDA

### ISSUE THREAD

**Issue by yelandgit** [arrayfire/arrayfire#3202]
The CUDA code is slower than CPU code in your test suite. I expected opposite result.
Could you tell me the reason why this happen?

Description
===========
`        Start   1: test_anisotropic_diffusion_cpu
  1/264 Test   #1: test_anisotropic_diffusion_cpu ....   Passed    0.02 sec
        Start   2: test_anisotropic_diffusion_cuda
  2/264 Test   #2: test_anisotropic_diffusion_cuda ...   Passed    1.29 sec
        Start   3: test_approx1_cpu
  3/264 Test   #3: test_approx1_cpu ..................   Passed    3.39 sec
        Start   4: test_approx1_cuda
  4/264 Test   #4: test_approx1_cuda .................   Passed   12.14 sec
        Start   5: test_approx2_cpu
  5/264 Test   #5: test_approx2_cpu ..................   Passed    4.79 sec
        Start   6: test_approx2_cuda
  6/264 Test   #6: test_approx2_cuda .................   Passed    7.00 sec
        Start   7: test_array_cpu
  7/264 Test   #7: test_array_cpu ....................   Passed    0.03 sec
        Start   8: test_array_cuda
  8/264 Test   #8: test_array_cuda ...................   Passed    1.54 sec
        Start   9: test_array_death_tests_cpu
  9/264 Test   #9: test_array_death_tests_cpu ........   Passed    0.02 sec
        Start  10: test_array_death_tests_cuda
 10/264 Test  #10: test_array_death_tests_cuda .......   Passed    2.38 sec
. . .
261/264 Test #261: test_matrixmarket_cpu .............   Passed    0.02 sec
        Start 262: test_matrixmarket_cuda
262/264 Test #262: test_matrixmarket_cuda ............   Passed    1.25 sec
        Start 263: test_jit_test_api_cpu
263/264 Test #263: test_jit_test_api_cpu .............   Passed    0.02 sec
        Start 264: test_jit_test_api_cuda
264/264 Test #264: test_jit_test_api_cuda ............   Passed    1.26 sec

100% tests passed, 0 tests failed out of 264

Total Test time (real) = 1617.01 sec`

Reproducible Code
-----------------
Your test suite

System Information
------------------
Linux Mint 19.3 Tricia (Ubuntu 18.04)
ArrayFire v3.9.0 (CUDA, 64-bit Linux, build 1d03d07e)
Platform: CUDA Runtime 10.1, Driver: 460.91.03
[0] GeForce RTX 2080 Ti, 11019 MB, CUDA Compute 7.5

**Comment by syurkevi** [comment]
Each test is its own process that requires the overhead of launching the cuda driver, as well as the compilation of the cuda kernels, etc.  Many of the data for the tests are also quite small, so the time reflects the overhead more than the computational portion of the code. Try running some of the benchmark examples instead to better measure the difference in computation.
