### ISSUE TITLE
Possibility to download tagged versions

### ISSUE THREAD

**Issue by marbre** [arrayfire/arrayfire#321]
I am currently working on an arrayfire ebuild for the gentoo-science overlay (https://github.com/gentoo-science/sci/pull/312).
In addition to provide the latest version (cloning the repo) it would be nice to offer tagged versions of the master repository, if no releases are available.

**Comment by pavanky** [comment]
@marbre We will do this once we have a stable build. This will likely happen sometime in early february.

**Comment by pavanky** [comment]
This is available now from here: https://github.com/arrayfire/arrayfire/releases/tag/v3.0.0
