### ISSUE TITLE
[Question] Translate a batch of images at the same time

### ISSUE THREAD

**Issue by samsvp** [arrayfire/arrayfire#3213]
I'm using arrayfire and I need to translate a lot of images at once and store it in a new array. The images are contained in a single array of size (w, h, c, b) and the amount by which each image needs to be translated is inside a (2, 1, 1, b) array.

The sequential implementation is as follows
```cpp
for (int i=0; i<b; i++)
{
    float x = coords(0, 0, 0, i).scalar<float>();
    float y = coords(1, 0, 0, i).scalar<float>();
    af::array t_imgs(af::span,af::span,af::span,i) = 
        af::translate(imgs(af::span,af::span,af::span,i), x, y);
}
```
Translate doesn't accept arrays as arguments, so I can't do something like this:
```cpp
gfor(af::seq i, b)
{
    af::array x = coords(0, 0, 0, i);
    af::array y = coords(1, 0, 0, i);
    t_imgs(af::span,af::span,af::span,i) = 
       af::translate(imgs(af::span,af::span,af::span,i), x, y);
```
GFOR also isn't a real parallel for loop, so I can't use `.scalar<float>()` inside it (I can, but the translations will all be the same). 

So, would I need to build a big translation matrix and manually apply it or is there a way to call a function in parallel inside the GPU using arrayfire?

PS: I'm using OpenCL's backend.

**Comment by syurkevi** [comment]
af::translate is a specialization of the more general [af::transform](https://arrayfire.org/docs/group__transform__func__transform.htm#ga3677c5a534ca50a9c8a2611fe0728fd8) that does support batched arguments.

You will need to change your __coords__ matrix (2, 1, 1, b) into a more general __transformations__ matrix with (3, 3, 1, b) or (3, 2, 1, b) dimensions. 

The only other gotcha is the output size arguments must also be specified if you use af::transform in a batching manner. 
Here's a small example snippet:
```
af::array a = af::constant(0, 3, 3, 3, 4);
a(1,1,af::span, af::span) = 1;

af::array T = af::identity(3, 3, 1, 4);
T(0, 2, af::span, 0) = 1;  // translate 0th image "up"
T(0, 2, af::span, 1) = -1; // translate 1st image "down"
T(1, 2, af::span, 2) = 1;  // translate 2nd image 'left"
T(1, 2, af::span, 3) = -1; // translate 3rd image "right"
af_print(T)
af_print(a);
af::array translated = af::transform(a, T.T(), 3, 3); //specify output dims
af_print(translated)
```

Hope this helps! Closing issue, contact us on [ArrayFire-org](arrayfire-org.slack.com) slack for further questions.
