### ISSUE TITLE
[BUG] Potentially invoking undefined behavior due to double underscore __ in identifiers

### ISSUE THREAD

**Issue by jansende** [arrayfire/arrayfire#3217]
I was looking at the source code and noticed that some of the variable names contain double underscores `__`. The C++ standard says the following about this.

> Each identifier that contains a double underscore __ or begins with an underscore followed by an uppercase letter is reserved to the implementation for any use.

This means, that depending on the C++ implementation used, undefined behavior might be invoked, because an implementation might use these identifier in a way that does so. Please check the code, and remove instances of these names.

Example: `src/backend/common/graphics_common.cpp`
```cpp
static const double __log2 = log10(2);
static const double __log4 = log10(4);
static const double __log6 = log10(6);
static const double __log8 = log10(8);
```

For a more detailed explanation, I can recommend https://youtu.be/0vJXQ2VOzEs :smile:

**Comment by 9prady9** [comment]
that is true, a clang tidy check can catch such mistakes quickly. The above identifiers are minor changes.

However, there is one macro `__DH__` (and perhaps a couple of more) which touches lot of files. Refactoring it would be nice but I am not sure if it is worth the effort for this macro. I can see quite a few macro definitions follow this pattern, even in CUDA toolkit - not saying that is an excuse to avoid the change. Just thinking out loud ...

**Comment by jansende** [comment]
My current interpretation of the standard is that double underscores in macros should be fine because they get expanded before translation. However, identifiers should not use them.

**Comment by jansende** [comment]
Well, that's embarrassing! While I remembered that he had a video about this, it has actually been while that I watched it. You are right. Macros cannot have double underscores because the implementation might use some as well.
