### ISSUE TITLE
Unable to compile/link arrayfire

### ISSUE THREAD

**Issue by govindarajan-prashanth** [arrayfire/arrayfire#322]
Hi,

I'm trying to use the arrayfire library for a small piece of code but I get compile/linking errors. Could you please take a look at the attached screenshot?

Thanks!
Prashanth
![compile_error](https://cloud.githubusercontent.com/assets/10480119/5693320/7545027a-98cc-11e4-8ab1-d379df3d5909.png)

**Comment by shehzan10** [comment]
Your LD_LIBRARY_PATH should have /usr/local/cuda-6.5/lib64 instead of cuda/bin.

bin directories are meant to be in PATH and not LD_LIBRARY_PATH. Only library directories are meant to be in LD_LIBRARY_PATH.

**Comment by govindarajan-prashanth** [comment]
Oops my bad. LD_LIBRARY_PATH was set to /usr/local/cuda-6.5/lib64. Here is the updated image:

![compile_error](https://cloud.githubusercontent.com/assets/10480119/5694608/6e683594-9921-11e4-8ae4-134510afe7be.png)

I'm trying to follow the documentation listed here: http://www.arrayfire.com/docs/createprojects.htm#createprojects_linux
as well as the issue reported here: https://github.com/arrayfire/arrayfire/issues/199 but I don't see what the problem is.

Thanks

**Comment by shehzan10** [comment]
You also need to add /usr/local/cuda-6.5/nvvm/lib64 to LD_LIBRARY_PATH.

**Comment by govindarajan-prashanth** [comment]
Got it.

Thanks!
