### ISSUE TITLE
[Question] How have the random engine types been chosen?

### ISSUE THREAD

**Issue by jansende** [arrayfire/arrayfire#3225]
First of all, I know absolutely nothing about random number generators. That being said, I had a look at the generators provided in [`af_random_engine_type`](https://arrayfire.org/docs/defines_8h.htm#a82a3bf91d6dd04661c63632d0fbf4934) and noticed that they are completely different to the ones provided by the [standard library](https://en.cppreference.com/w/cpp/numeric/random). Thus:
> How have you chosen the number generators in ArrayFire and whats the difference to the ones in the standard library?

**Comment by syurkevi** [comment]
The random engine types we use in ArrayFire are better suited to parallelization whereas a lot of the engines in the C++ standard library are sequential. A better explanation can be found here:
https://en.wikipedia.org/wiki/Counter-based_random_number_generator_(CBRNG)
