### ISSUE TITLE
cusparse.dll not found in test_sparse_arith_cuda

### ISSUE THREAD

**Issue by willyborn** [arrayfire/arrayfire#3251]
test_sparse_arith_cuda fails on my system (Windows 10, CUDA 11.3, master [df57c567]) with 
**Exception thrown: read access violation.
_ was 0xFFFFFFFFFFFFFF6F.**

Description
===========
cusparse.dll is not found on my system, resulting in a NULL handle.

When change to module name to "cusparse64_11" iso "cusparse" in the src file "cusparseModule.cpp:25", the corresponding dll is correctly found and the test runs successfully.

DLL path (standard installation of CUDA 11.2):
  C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\bin\cusparse64_11.dll
DLL path (standard installation of CUDA 11.3):
  C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin\cusparse64_11.dll

I have the impression that the .dll file changes name with the major CUDA version.
I did not find a general cusparse.dll somewhere else on my system.

Reproducible Code and/or Steps
------------------------------
System Information
------------------
Windows 10
CUDA 11.3
master [df57c567]

Checklist
---------

- [x] Using the latest available ArrayFire release
- [ ] GPU drivers are up to date

**Comment by umar456** [comment]
Hmm. Interesting. I didn't run into this issue. I need to look again at the tests. Thanks for bringing this to our attention.
