### ISSUE TITLE
[Build] error: ‘af_sum_all_array’ was not declared in this scope

### ISSUE THREAD

**Issue by 3togo** [arrayfire/arrayfire#3253]
/home/eli/gitee/arrayfires/arrayfire/src/api/cpp/reduce.cpp:219:18: error: ‘af_sum_all_array’ was not declared in this scope; did you mean ‘af_save_array’?
  219 |         AF_THROW(af_##fnC##_all_array(&out, in.get())); \

How to fix it?

**Comment by umar456** [comment]
Can you fill out the rest of the information in the build issue template? I don't have enough information to diagnose this problem.

**Comment by 3togo** [comment]
I found the problem. Some files failed to download during the "make" process. 

Many thanks
