### ISSUE TITLE
Using GFOR with col operator

### ISSUE THREAD

**Issue by Kerkil** [arrayfire/arrayfire#326]
Looks like `A.col(i)` takes integer as an input. Is there an alternative way to assign an `af` vector to columns of a matrix in `gfor`? Can I implement something like the following?

```
    af::array A(N, M, f32);
    gfor (af::seq i, M)
    {        
        A.col(i) = af::pow(x, i);        
    }
```

**Comment by pavanky** [comment]
This is a little bit tricky because `seq i` generates an array of size `(M, 1)`; 

You can do something like this:

```
    const int N = 5;
        const int M = 3;
        array x = randu(N, 1);
        array ii = seq(1, M);
        array A = batchFunc(x, ii.T(), pow);

        af_print(x)
        af_print(x*x);
        af_print(x*x*x);
        af_print(A);
```

Results:

```
x [5 1 1 1]
    0.7402
    0.9210
    0.0390
    0.9690
    0.9251

x*x [5 1 1 1]
    0.5479
    0.8482
    0.0015
    0.9389
    0.8559

x*x*x [5 1 1 1]
    0.4056
    0.7812
    0.0001
    0.9097
    0.7918

A [5 3 1 1]
    0.7402     0.5479     0.4056
    0.9210     0.8482     0.7812
    0.0390     0.0015     0.0001
    0.9690     0.9389     0.9097
    0.9251     0.8559     0.7918
```

**Comment by pavanky** [comment]
Alternatively you can do the following:

```
 af::array A(N, M, f32);
    gfor (af::seq ii, M)
    {        
        A(span, ii) = af::pow(x, array(ii).T());        
    }
```

**Comment by Kerkil** [comment]
@pavanky Pretty cool. Both of them work nicely and pretty useful. Thanks again.

**Comment by pavanky** [comment]
@Kerkil Btw `seq(M)` generates [0, M-1]. If you want powers of [1, M], use `seq(1, M)` instead.

**Comment by Kerkil** [comment]
@pavanky Thanks. What I want is equivalent to 
```
for (int i=0; i<M; ++i)
```
and so I think `seq(M)` is what I want.

**Comment by pavanky** [comment]
@Kerkil Actually the gfor alternative I mentioned does not look like its working. Please use the batchFunc for now.

**Comment by Kerkil** [comment]
@pavanky Funny that I actually thought it was working and was checking the value and realized it threw an exception. :) Thanks for the heads up.

**Comment by pavanky** [comment]
@Kerkil Fixed `gfor` in devel. It works now and you don't need to use transpose. Please look at the updated code over [here](https://github.com/arrayfire/arrayfire/issues/326#issuecomment-69803610)

**Comment by Kerkil** [comment]
@pavanky It works smoothly. Thanks. It is very nice to have GFOR in this way. Thanks for the help!
