### ISSUE TITLE
[BUG] MacOS Download link broken on official website

### ISSUE THREAD

**Issue by LilithHafner** [arrayfire/arrayfire#3265]
The [MacOS download link](https://arrayfire.s3.amazonaws.com/3.8.2/ArrayFire-v3.8.2_OSX_x86_64.pkg) on the [official website](https://arrayfire.com/binaries/) gives me the following error:

```
Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>3.8.2/ArrayFire-v3.8.2_OSX_x86_64.pkg</Key>
<RequestId>B4AB3N989RCGSZ10</RequestId>
<HostId>P1jNo0kzuRJD5M1iRYsldlm02aZRRehB935zQBx+bkyoCZEyrktw9ieJWnCifXebgefhBvNvlUU=</HostId>
</Error>
```

**Comment by LilithHafner** [comment]
The link on the website is (first) but should be (second)
https://arrayfire.s3.amazonaws.com/3.8.2/ArrayFire-v3.8.2_OSX_x86_64.pkg
https://arrayfire.s3.amazonaws.com/3.8.2/ArrayFire-3.8.2_OSX_x86_64.pkg

**Comment by edwinsolisf** [comment]
Installer link has been fixed, closing this issue
