### ISSUE TITLE
enabling wgl swap interval feature to control GPU rendering rate for rendering  plots 

### ISSUE THREAD

**Issue by coderboyisongithub** [arrayfire/arrayfire#3272]
while rendering plot on Iris XE GPU usage goes to 70 %.the system heats up for a simple plot.I propose a way to control swap interval in WGL implementation to lower GPU usage.I there way do exist kindly let me know..Its unnecessary to burn GPU for simple plot

**Comment by 9prady9** [comment]
@coderboyisongithub That sounds more like Intel driver issue to me. A simple plot if data rendered never changed, it wouldn't even copy data across buffers. Can you share an example of your plotting program. Have you tried it on any other GPU ?

**Comment by coderboyisongithub** [comment]
@9prady9 
![image](https://user-images.githubusercontent.com/24197201/178113166-18c9c7ff-4cdc-4440-b295-a71f0cb7a90e.png)
this is using 80% gpu...

**Comment by christophe-murphy** [comment]
Closing for now. If you still have questions, please open a new issue.
