### ISSUE TITLE
debug error while use arrayfire in QT

### ISSUE THREAD

**Issue by goudanzw** [arrayfire/arrayfire#3274]
Description
I want to add arrayfire into QT build in Vsiual Studio 2017, but debug error as follows
'af::operator &&': 32 overloads have similar conversions

**Comment by goudanzw** [comment]
the error happen in qmetatype. h: type is not registered please use the q_declare_metatype macro to make it known to QT's meta-object system

**Comment by goudanzw** [comment]
![2ff5d1b5efa409aff6b2aaabb5ffbb0](https://user-images.githubusercontent.com/92415225/178218688-e7d4a1f6-0d2b-48b6-a744-d6f695e616c6.jpg)

**Comment by goudanzw** [comment]
![3a278f117a958a7c30b16c2069c4b23](https://user-images.githubusercontent.com/92415225/178218830-e76efee8-4ef7-450f-aae7-957725b80019.jpg)

**Comment by edwinsolisf** [comment]
This is likely a problem with how QMetatype works in QT. Take a look a the [documentation](https://doc.qt.io/qt-6/qmetatype.html#Q_DECLARE_METATYPE) which basically states that if you want to add the ArrayFire array to QMetatypes, you must use `Q_DECLARE_METATYPE(MyNamespace::MyStruct)` after including the arrayfire header. You may try this fix; however, we cannot guarantee any painless experience with it, as `af::array` was not made with this QT functionality in mind. 
I'm closing this issue but please reopen it, if you still find any problem with ArrayFire.
