### ISSUE TITLE
Undefined reference to af::array::array

### ISSUE THREAD

**Issue by SiddhantKadwe** [arrayfire/arrayfire#3275]
I am using the QR factorization from ArrayFire in my code. My code is similar to the QR factorization example given on the ArrayFire documentation website.

In my Makefile, I have linked `-lafcpu -lafopencl -lafcuda -laf `as well as the path to them.

The only undefined reference I am receiving is:
`undefined reference to af::array::array<double*>(long long, long long, double* const*, af_source)`

Is there anything else that I should link as well?

**Comment by edwinsolisf** [comment]
I was not able to replicate your issue with ArrayFire 3.9.0. It looks like it's not linking correctly to ArrayFire, but those `-lafcpu -lafopencl -lafcuda -laf`  should be enough. 

I'm closing this issue, but feel free to reopen it if you find is there still a problem with ArrayFire.
