### ISSUE TITLE
how to install using the .sh file

### ISSUE THREAD

**Issue by benam2** [arrayfire/arrayfire#3287]
Sorry for the very simple question. How can I install after I Download the `.sh` file from this link [https://arrayfire.com/binaries/](url)?
I have unzipped it but not sure what else I need to do in order to install the package. I really appreciate it if you can help with this.

**Comment by syurkevi** [comment]
We have some installation pages that may be helpful: 
https://arrayfire.org/docs/installing.htm
The gist of it is that the unzipped files just need to be placed somewhere that makes sense on your system. This doesn't have to be within the system directories and can just be some folder like ~/myarrayfire_install_dir/
Then, you'll need to point your compiler and linker to that directory. There are different ways to do that covered here:
https://arrayfire.org/docs/using_on_linux.htm
Hope that helps! Feel free to also reach out on our [ArrayFire-org](arrayfire-org.slack.com) slack channel or on google groups.

**Comment by benam2** [comment]
@syurkevi Thanks so much for quick reply. I really appreciate it.
Could you just please answer 2 questions?
what we planning to do via `echo /opt/arrayfire/lib64 > /etc/ld.so.conf.d/arrayfire.conf 
sudo ldconfig`

The reason Im asking is that I dont have `ld.so.conf.d/` in my `etc` folder and I think I cannot link them then.

Again thanks a lot for helping out on this.

**Comment by benam2** [comment]
@syurkevi Im really sorry but the link you provided for the slack channel does not work.

**Comment by benam2** [comment]
@syurkevi after running `sudo echo /opt/ArrayFire-3.8.2-Linux/lib64 > /etc/ld.so.conf.d/arrayfire.conf`
I get this error `-bash: /etc/ld.so.conf.d/arrayfire.conf: Permission denied`

**Comment by benam2** [comment]
It's been 5 days Im trying to fix the array fire issue. I really appreciate it if you can help me to fix it. I searched it but could not find any relevent things. I think the command should be `sudo echo /opt/ArrayFire-3.8.2-Linux/lib64 > /etc/ld.so.conf.d/` since not only I dont have `arrayfire.conf` but it likes a file not a folder. 
Thanks ~
