### ISSUE TITLE
[BUG] http://arrayfire.com/how-to-write-vectorized-code/ is missing

### ISSUE THREAD

**Issue by pv-pterab-s** [arrayfire/arrayfire#3288]
Description
===========

Reproducible Code and/or Steps
------------------------------

System Information
------------------

Checklist
---------

- [ ] Using the latest available ArrayFire release
- [ ] GPU drivers are up to date

**Comment by edwinsolisf** [comment]
It has been moved to [https://arrayfire.com/blog/how-to-write-vectorized-code/](https://arrayfire.com/blog/how-to-write-vectorized-code/)
