### ISSUE TITLE
clamping function

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#3298]
Add support to clamp values in an array in only 1 pass.
eg:
https://pytorch.org/docs/stable/generated/torch.clamp.html
https://en.cppreference.com/w/cpp/algorithm/clamp

See:
https://github.com/huggingface/transformers/pull/19229/commits/a74612f891699ecdbdb715b7e0773f3be1e2ae3f

```
        # clamp inf values to enable fp16 training
        if torch.isinf(hidden_states).any():
            clamp_value = torch.finfo(hidden_states.dtype).max - 1000
            hidden_states = torch.clamp(hidden_states, min=-clamp_value, max=clamp_value)
```

Description
===========
* What problem are you trying to solve?
inf/-inf values in some f16 arrays
* API of new function
af::array cleanArray = af::clamp(buggyArray, T minValue, T maxValue);

* Algorithms that could be used to implement this feature
af::replace() ? af::select() ?

* Are there other libraries that implement this feature?
torch
https://en.cppreference.com/w/cpp/algorithm/clamp

**Comment by umar456** [comment]
This function already exists in ArrayFire since version 3.4 and it behaves exactly like the functions you listed above. There was an issue in the documentation that categorized the function under the max function. This is address in PR #3330 and should be part of master soon.

**Comment by WilliamTambellini** [comment]
Tks @umar456  I guess that s why I missed it.
