### ISSUE TITLE
ArrayFire does not link against CUDA framework on OS X 10.9, 10.10

### ISSUE THREAD

**Issue by skalarproduktraum** [arrayfire/arrayfire#332]
Hello,

we've experienced the problem that CMake seems to recognize CUDA (v6.5 is installed), but fails to add the correct flags to the compiler command, such that linking fails for libafcuda.dylib and the CUDA-dependent examples: 

```
Linking CXX shared library libafcuda.dylib
ld: file not found: @rpath/CUDA.framework/Versions/A/CUDA for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/backend/cuda/libafcuda.dylib] Error 1
make[1]: *** [src/backend/cuda/CMakeFiles/afcuda.dir/all] Error 2
```

By adding `-F/Library/Frameworks -framework CUDA` to link.txt in `src/backend/cuda/CMakeFiles/afcuda.dir/`, this can be fixed for Makefile builds until the next makefile generation.

(Unfortunately, I do not know how I can coerce CMake to include these flags permanently on OS X, otherwise I would have sent a pull req...)

Thanks!

ulrik

**Comment by pavanky** [comment]
@skalarproduktraum 

In src/backend/cuda/CMakeLists.txt there is a section like this:

```
IF("${APPLE}")
    ADD_DEFINITIONS(-D__STRICT_ANSI__)
    IF(${CMAKE_CXX_COMPILER_ID} STREQUAL "Clang")
        ADD_DEFINITIONS(-stdlib=libstdc++)
        SET(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -stdlib=libstdc++")
        SET(CMAKE_STATIC_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -stdlib=libstdc++")
        SET(CUDA_HOST_COMPILER "/usr/bin/clang++")
    ENDIF()
ENDIF()
```

Please ad the extra line before the final `ENDIF()` like the following to see if the problem is solved for you.

```
SET(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -F/Library/FrameWorks -framework CUDA")
SET(CMAKE_STATIC_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -F/Library/FrameWorks/ -framework CUDA")
```

**Comment by pavanky** [comment]
No longer an issue in devel.
