### ISSUE TITLE
Option to avoid freeing device memory when the array is created with af_device_array

### ISSUE THREAD

**Issue by lavaux** [arrayfire/arrayfire#3347]
Current af_device_array function takes ownership of the memory pointer provided to the function. However this is not necessary desirable when interacting with other frameworks as the memory may be managed by another library independently.

Description
===========

* Allow interaction between several framework running at the same time in the same application. For example I would like to allow CUDA device memory to be sent from CuPY/Torch/JAX to and from ArrayFire
* Add a new function based on `af_device_array` that turns off the memory freeing when the reference count goes to zero inside arrayfire.

The current API of af_device_array is like this:
```c
    AFAPI af_err af_device_array(af_array *arr, void *data, const unsigned ndims, const dim_t * const dims, const af_dtype type);
```

which does not allow to specify that memory should not be cleared.

* Manipulating the memory manager does not sound possible either, as other operations should proceed as usual.

**Comment by umar456** [comment]
The current way to get around this is to call the lock function. This will effectively prevent that pointer from being released by ArrayFire's memory manager.
