### ISSUE TITLE
[Build] liblapack_static.a does not exist in CUDA 12

### ISSUE THREAD

**Issue by mikex86** [arrayfire/arrayfire#3349]
## Description
liblapack_static.a does not exist in CUDA 12, arrayfire/src/backend/cuda/CMakeLists.txt tries to find said library and fails.
Possible work around without fix is creating a symlink from liblapack_static.a to libcusolver_lapack_static.a; file seems to have been renamed.

## Proposed fix
Handle find libcusolver_lapack_static.a after appropriate CUDA version checks in https://github.com/arrayfire/arrayfire/blob/138f12e9f181b8a7bd013323137931aec0f3bd59/src/backend/cuda/CMakeLists.txt#L102

Build Environment
-----------------
Compiler version: clang version 10.0.0-4ubuntu1
Operating system: Ubuntu 22.04 (WSL)
Build environment: CUDA 12.0, vcpkg

**Comment by iivevo** [comment]
Hi, was this ever fixed? I can seem to get a working build with cuda 12>=

**Comment by WilliamTambellini** [comment]
same issue here:
```
$ locate lapack_stat
/usr/local/cuda-11.2/targets/x86_64-linux/lib/liblapack_static.a
/usr/local/cuda-11.6/targets/x86_64-linux/lib/liblapack_static.a
/usr/local/cuda-12.3/targets/x86_64-linux/lib/libcusolver_lapack_static.a
/usr/local/cuda-12.4/targets/x86_64-linux/lib/libcusolver_lapack_static.a

```
for cuda>=12, this seems to work:
```
    af_find_static_cuda_libs(cusolver_lapack_static)
    message(DEBUG "CUDA_cusolver_lapack_static_LIBRARY=${CUDA_cusolver_lapack_static_LIBRARY}")
    target_link_libraries(afcuda
      PRIVATE
        ${CUDA_cusolver_lapack_static_LIBRARY})

```
@edwinsolisf  @christophe-murphy  @umar456  could you please reopen the ticket?
