### ISSUE TITLE
[BUG] CU_CHECK does not check for validity of CUDA messages extracted from error code

### ISSUE THREAD

**Issue by cschreib-ibex** [arrayfire/arrayfire#3353]
The `CU_CHECK` macro, used to report errors from CUDA, uses CUDA functions to convert the error code into human-readable messages. The macro currently does not check if the conversion was successful, and uses the returned `const char*` blindly. This causes crashes when the CUDA environment is badly setup (bad drivers, incorrect initialization, etc.) and the basic error message functions do not succeed.

Description
===========
I arrived there by a convoluted path; I still don't know if this bug report is related to my original problem. But here is the full story.

I have been trying to run a Windows application built with AF, with AF built from source against CUDA 11.8. The desktop on which I run the application has drivers that are below the recommended driver version for CUDA 11.8 (which is 522.6, and I am running 512.15). I expected the application to either run, or error gracefully. But instead it hard-crashed with an access violation inside ArrayFire. 

I have not been able to reproduce this with a simple application, only with our full product. I also wasn't able to debug the ArrayFire build, somehow the `.pdb` don't load. But I noticed that the hard crash disappeared if I cleared my ArrayFire kernel cache on disk. This suggested to me that the crash happened somewhere in the code that loads the kernels from disk. There isn't much code there, so I focused on the main CUDA call:
https://github.com/arrayfire/arrayfire/blob/a230ef46c27588cffe204bb5c465dba30bc08cdd/src/backend/cuda/compile_module.cpp#L458

Looking at the implementation of `CU_CHECK`:
https://github.com/arrayfire/arrayfire/blob/a230ef46c27588cffe204bb5c465dba30bc08cdd/src/backend/cuda/cu_check_macro.hpp#L18-L30

I noticed that there is no error checking on the calls to `cuGetErrorName()` and `cuGetErrorString()`. The documentation of these functions says that they can error only if the provided error code is invalid. So in principle, unless CUDA itself is returning invalid error codes, this should be alright. However the CUDA documentation appears to be inaccurate here.

Indeed, I experimented with this, and managed to trigger an error in a simple CUDA application outside of ArrayFire, by trying to run `cuModuleLoadData()` without having previously called `cuInit()`. In this case, when trying to convert the returned error code from `cuModuleLoadData()`, both `cuGetErrorName()` and `cuGetErrorString()` returned `CUDA_ERROR_NOT_INITIALIZED`, and actually didn't set the output messages to `nullptr`. If used in the `CU_CHECK` macro, this means the strings are left uninitialised, and passed to `snprintf`, which could cause a hard-crash.

I suspect this could be what is happening in my larger application. It may not be, but at any rate, the existing code should be improved to include all the necessary error checking. 

Suggestion:
```c++
    CUresult res1 = cuGetErrorName(res, &cu_err_name);
    CUresult res2 = cuGetErrorString(res, &cu_err_string);
    if (res1 == CUDA_SUCCESS && res2 == CUDA_SUCCESS)
    {
        snprintf(cu_err_msg, sizeof(cu_err_msg), "CU Error %s(%d): %s\n", cu_err_name, (int)(res), cu_err_string);
    }
    else
    { 
        snprintf(cu_err_msg, sizeof(cu_err_msg), "CU Error UNKNOWN(%d): unknown error\n", (int)(res)); 
    }
```

Reproducible Code and/or Steps
------------------------------
 - Build AF from source against CUDA 11.8
 - Run application with older drivers, 512.15.

System Information
------------------
Please provide the following information:
1. ArrayFire version: 3.8.2
2. Devices installed on the system: Nvidia GeForce GTX 1070 8GB
3. (optional) Output from the af::info() function if applicable. 
```
ArrayFire v3.8.2 (CUDA, 64-bit Windows, build 5752f2dc)
Platform: CUDA Runtime 11.8, Driver: 11060
[0] NVIDIA GeForce GTX 1070, 8192 MB, CUDA Compute 6.1
```
5. Output from the following scripts:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 512.15       Driver Version: 512.15       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:65:00.0 Off |                  N/A |
|  0%   43C    P8    13W / 151W |   1921MiB /  8192MiB |      3%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

Checklist
---------

- [x] Using the latest available ArrayFire release
- [ ] GPU drivers are up to date

**Comment by cschreib-ibex** [comment]
`CU_LINK_CHECK` is also affected

**Comment by umar456** [comment]
Hey @cschreib-ibex, Thanks for the detailed description. I am not sure if that code path can be called without a cuInit call but you are right that those return variables should be handled in that code.
