### ISSUE TITLE
[Build]: Problem with OpenCL header opencl.hpp

### ISSUE THREAD

**Issue by ShivamPR21** [arrayfire/arrayfire#3362]
Description
===========

While building Arrayfire, I encountered an error in file `scan_by_key_impl.cpp:10` related to `opencl.hpp` stating that `CL_API_PREFIX__VERSION__2_2_DEPRICATED doesn't name a type; did you mean ‘CL_API_PREFIX__VERSION_1_2_DEPRECATED’?`.

Error Log
---------

```shell
In file included from /home/shivampr21/.venv/pkgs/arrayfire/src/backend/opencl/./cl2hpp.hpp:24,
                 from /home/shivampr21/.venv/pkgs/arrayfire/src/backend/opencl/./types.hpp:12,
                 from /home/shivampr21/.venv/pkgs/arrayfire/src/backend/opencl/./backend.hpp:22,
                 from /home/shivampr21/.venv/pkgs/arrayfire/src/backend/opencl/kernel/scan_by_key/scan_by_key_impl.cpp:10:
/usr/include/CL/opencl.hpp:6881:5: error: ‘CL_API_PREFIX__VERSION_2_2_DEPRECATED’ does not name a type; did you mean ‘CL_API_PREFIX__VERSION_1_2_DEPRECATED’?
 6881 |     CL_API_PREFIX__VERSION_2_2_DEPRECATED cl_int setReleaseCallback(
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     CL_API_PREFIX__VERSION_1_2_DEPRECATED
cc1plus: note: unrecognized command-line option ‘-Wno-unqualified-std-cast-call’ may have been intended to silence earlier diagnostics
make[2]: *** [src/backend/opencl/CMakeFiles/opencl_scan_by_key_af_add_t.dir/build.make:76: src/backend/opencl/CMakeFiles/opencl_scan_by_key_af_add_t.dir/kernel/scan_by_key/scan_by_key_impl.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3222: src/backend/opencl/CMakeFiles/opencl_scan_by_key_af_add_t.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Build Environment
-----------------
Compiler version: g++/gcc 11.3.0 
Operating system: Ubuntu 22.04 
Build environment: 
CMake variables: -DCMAKE_INSTALL_PREFIX=$HOME/opt -DCMAKE_BUILD_TYPE=Releas

**Comment by umar456** [comment]
Hey @ShivamPR21.

This is an error in the OpenCL headers and not in ArrayFire but can you try to build with the latest master. I may have addressed this issue in there to support older versions. If the latest master does not work, can you tell me which versions of OpenCL is installed on your system 22.04 should have the latest headers released by the Khronos group so I am not sure why this error is popping up.

**Comment by syurkevi** [comment]
Closing for now. Feel free to reopen if issue is still failing in current master.
