### ISSUE TITLE
[Build] Conversion to std::vector from af::array via host-function fails

### ISSUE THREAD

**Issue by BOle-ProZ** [arrayfire/arrayfire#3367]
Description
===========

I try to convert a af::array to host memory but the programm crashes. 

If I create an af::array with random values, i can successfully host it and access it like a std::array. But when I start with a QVector which is "converted" to an af::array (which works), I cannot convert back.

Error Log
---------

```

```

Build Environment
![ArrayFire Q](https://user-images.githubusercontent.com/94117204/221211013-5c3c6be8-cb09-4fb3-b9fa-a85f0dd3d3dd.JPG)

-----------------
Compiler version: 
 MSVC v140
Operating system: 
Windows 10
Build environment: 
Qt Creater 4.15; Qt 5.13
CMake variables:

**Comment by umar456** [comment]
I think this is happening because you create an s32(int) array and try to get the float data out of it using the host function. Try first converting to f32 by calling the af::array::as function.

```
af::array ascanAF=af::array(1, inputHisto.height(), toArray);
af::array convertedAscanAF = ascanAF.as(f32)
float* host_nonZero = convertedAscanAF.host<float>();
af::freeHost(host_nonZero);
```

**Comment by BOle-ProZ** [comment]
Hallo Umar,
thank you for the responce. I tried your example. The programm no longer crashes but it doesn't work either. I get the following error code:
Exception at 0x7ffc79fdcd29, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) in afopencl!af::array::host

I am a bit confused by the appearence of "cl" in the error message. I am using a CUDA compatible GPU.

**Comment by melonakos** [comment]
Glad to hear it works in release mode. I don't think we have much insight on your Qt question.

**Comment by umar456** [comment]
I am not sure why it would fail on debug mode and not release. I think Microsoft adds a bunch of extra checks whenever you copy things in debug mode. If you can identify where this error is happening then you could get more insights on the matter. Make sure you are passing and allocating the correct sizes when you are transferring data from host and device.
