### ISSUE TITLE
License Clarification [Question]

### ISSUE THREAD

**Issue by sstarr-vadax** [arrayfire/arrayfire#3374]
I was considered utilizing ArrayFire. However, our legal department has raised concerns about the feasibility of using ArrayFire in any open source project without a commercial license for FFTW. The reasoning is that due to FFTW's GPL requirements, ArrayFire would be obligated to be licensed under GPL as well, which is incompatible with the BSD 3-Clause license of the project.

**Comment by umar456** [comment]
Hi @sstarr-vadax,

If you are building ArrayFire against FFTW and shipping the binaries with your application then you will run into that issue. A way around this is to build and ship ArrayFire against the Intel MKL libraries. These libraries have a license that is better for redistribution for your case. These are the libraries we ship with our official binary installers at https://arrayfire.com/downloads.

**Comment by umar456** [comment]
@sstarr-vadax Please feel free to open the issue again if you have additional questions.

**Comment by cschreib-ibex** [comment]
Hi Umar. We encountered a similar problem recently, and unfortunately we are targeting a linux platform, so MKL is not an option. We do not actually use the FFT functions in ArrayFire in this particular product, so we ended up creating a fork with FFTW stripped out.

Would there be any interest in having this option in the mainline ArrayFire repository?
