### ISSUE TITLE
[BUG] examples/mnist_common.h bool compare(..., ...)

### ISSUE THREAD

**Issue by DearMisaki** [arrayfire/arrayfire#3378]
Description
===========
when I call function std::stable_sort() using this compare function, the program crashed.

Reproducible Code and/or Steps
------------------------------
BEFORE:
bool compare(const std::pair<float, int> l, const std::pair<float, int> r) {
    return l.first >= r.first;
}
AFTER:
bool compare(const std::pair<float, int> l, const std::pair<float, int> r) {
    return l.first > r.first;
}

\>=   ---> >

Checklist
---------

**Comment by edwinsolisf** [comment]
I wasn't able to replicate with ArrayFire 3.9.0 with some of the recent issue fixes. So I'm adding back, the `classify` function back into the naive bayes example.

**Comment by willyborn** [comment]
I noticed the same error as DearMisaki.
Running deep_belief_net_opencl of ArrayFire 3.9.0 (master) with MSVC 2019 in DEBUG mode, is throwing an assert on the compare function used in stable_sort.  (mnist_common.h:line 16)
![Assertion](https://github.com/user-attachments/assets/eeab61af-2cae-43bc-8cc6-237123181841)
![call stack](https://github.com/user-attachments/assets/97fdfae3-38e4-4594-9e3c-b6e31c6daf06)


The same happens for 
- deep_believe_net_cpu, deep_believe_net_cuda, 
- logistic_regression_cpu, logistic_regression_opencl, logistic_regression_cuda
- perceptron_cpu, perceptron_opencl, perceptron_cuda
- bagging_cpu, bagging_opencl, bagging_cuda
- naive_bayes_cpu, naive_bayes_opencl, naive_bayes_cuda
- softmax_regression_cpu, softmax_regression_opencl, softmax_regression_cuda

**cplusplus reference defines the comp function for stable_sort as follows:** 
```
comp
    Binary function that accepts two elements in the range as arguments, and returns a value convertible to bool. The value returned indicates whether the element passed as first argument is considered to go before the second in the specific strict weak ordering it defines.
    The function shall not modify any of its arguments.
    This can either be a function pointer or a function object.
```
Reference: [cplusplus.com](https://cplusplus.com/reference/algorithm/stable_sort/)

**The definition of strict weak ordering is explained an the site of boost:**
```
A Strict Weak Ordering is a [Binary Predicate](https://www.boost.org/sgi/stl/BinaryPredicate.html) that compares two objects,
returning true if the first precedes the second. This predicate must satisfy the standard mathematical definition of a strict weak
ordering. The precise requirements are stated below, but what they roughly mean is that a Strict Weak Ordering has to behave
the way that "less than" behaves: if a is less than b then b is not less than a, if a is less than b and b is less than c then a is less
than c, and so on.
```
Reference: [boost.org](https://www.boost.org/sgi/stl/StrictWeakOrdering.html)

Conclusion:
The compare function should only contain '>' and not '>=' according to the C++ definition.
Comparing the same values should return false.
