### ISSUE TITLE
Matrix multiplication exception

### ISSUE THREAD

**Issue by Kerkil** [arrayfire/arrayfire#338]
af::matmul on MacOSX throws an exception:

```
void testAFMatMul()
{
    const int nr = 48;
    const int nc = 7;

    af::array A = af::randn(nr,nc);
    af::array B = af::randn(nc,nr);

    af::array C = af::matmul(A, B, AF_NO_TRANSPOSE, AF_NO_TRANSPOSE);
//  af::array C = af::matmul(A, B); // This also does not work
    af_print(C);
}
```
The line `af::array C = af::matmul(A, B, AF_NO_TRANSPOSE, AF_NO_TRANSPOSE);` terminated the program with the message `The program has unexpectedly finished.`

**Comment by pavanky** [comment]
Can you put a try catch block around this, catch the exception and display what the exception is ?

You can look at helloworld.cpp to see how this can be done.

**Comment by Kerkil** [comment]
For some reason, I cannot catch the exception. Not sure what I am doing wrong:
```
void testAFMatMul()
{
    std::cout << "test" << std::endl;
    try{

        af::info();

        const int nr = 48;
        const int nc = 7;

        af::array A = af::randn(nr,nc);
        af::array B = af::randn(nr,nc);
        af::array C = af::matmul(A, B, AF_NO_TRANSPOSE, AF_TRANSPOSE);
    } catch (af::exception& e) {
        fprintf(stderr, "%s\n", e.what());
        throw;
    }

}
```
produces
```
Starting /Users/recondev/Projects/build-Linspace-osx64-Debug/Linspace...
test
ArrayFire v3.0.beta (OpenCL, 64-bit Mac OSX, build 931a6c3)
[0] Apple HD Graphics 4000 OpenCL 1.2  Device driver 1.2(Sep 25 2014 22:26:04) FP64 Support(False)
-1- Apple GeForce GT 650M OpenCL 1.2  Device driver 10.0.43 310.41.05f01 FP64 Support(True)
-2- Apple Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz OpenCL 1.2  Device driver 1.1 FP64 Support(True)
The program has unexpectedly finished.
/Users/recondev/Projects/build-Linspace-osx64-Debug/Linspace crashed
```

**Comment by pavanky** [comment]
@Kerkil Can you do "`af::setDevice(1);" before you do `af::info()` and see if the code works ? it could just be that the clBLAS library we are using isn't working well with the iris graphics.

**Comment by Kerkil** [comment]
@pavanky I see the identical behavior with the change:
```
Starting /Users/recondev/Projects/build-Linspace-osx64-Debug/Linspace...
test
ArrayFire v3.0.beta (OpenCL, 64-bit Mac OSX, build 931a6c3)
-0- Apple HD Graphics 4000 OpenCL 1.2  Device driver 1.2(Sep 25 2014 22:26:04) FP64 Support(False)
[1] Apple GeForce GT 650M OpenCL 1.2  Device driver 10.0.43 310.41.05f01 FP64 Support(True)
-2- Apple Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz OpenCL 1.2  Device driver 1.1 FP64 Support(True)
The program has unexpectedly finished.
/Users/recondev/Projects/build-Linspace-osx64-Debug/Linspace crashed
```

Thanks a lot for your help.

**Comment by kerkilchoi** [comment]
@pavanky Just out of curiosity, if I call  `afcl::getQueue()` in the function in which I call `af::matmul` function, then would that value be the same as `&getQueue()()` value in `matmul` function in `backend/opencl/blas.cpp`?

**Comment by Kerkil** [comment]
I tried to get my head around the issue and dug a bit more and found that the build error occurred in clBLAS library. However, I can run their example without experiencing the same issue. Here is the issue submitted to clBLAS: https://github.com/clMathLibraries/clBLAS/issues/59. 

So, this build error seems to occur when the `gemm` function is called from ArrayFire in `blas.cpp.` What could be an issue here?

**Comment by Kerkil** [comment]
Not sure if this is of any help or use: the example for running `clblasSgemm` (https://github.com/clMathLibraries/clBLAS/blob/master/src/samples/example_sgemm.c) builds and runs OK producing the right results for simple cases. I tried to replicate the same test case for ArrayFire (`blas.cpp`), but could not still build the test case despite most of the parameters match.

**Comment by pavanky** [comment]
@Kerkil Thanks for reporting this. I thought the problem may be similar to the one from here: https://github.com/clMathLibraries/clBLAS/issues/53

Perhaps the `example_sgemm.c` is not triggering this behavior because of the sizes ?

**Comment by pavanky** [comment]
As to answer your other question, yes `afcl::getQueue()` and `opencl::getQueue()()` return the same queue.  We currently use only one queue per device. This can be seen by looking at `src/backend/opencl/platform.cpp`

**Comment by TimmyLiu** [comment]
Hi guys, in clBLAS you can use the "make-ktest" utility that dump the kernel and host code for the size and routine of interest. I recommend trying this out and see if the kernel dumped will compile.

**Comment by Kerkil** [comment]
@pavanky Thanks for the info.

*Perhaps the example_sgemm.c is not triggering this behavior because of the sizes ?*
I conjectured that too, but in the test example, I matched the size of the matrices all to 2x2 for simplicity. Also, their values are equal for ArrayFire test example and clBLAS example. 

Also, when ArrayFire calls `sgemm,` there is no build error. I also see the cl error code being 0, which indicates that the kernel compiled fine.

**Comment by Kerkil** [comment]
@pavanky Thanks again for the help. As to the queue, When I printed the two values `afcl::getQueue()` and `opencl::getQueue()()`, they were not the same. I will look into `platform.cpp.`

Please let me know if I can do further.

**Comment by pavanky** [comment]
@Kerkil Thanks for pointing this out. There is perhaps a bug in our DeviceManager. I will look into it ASAP.

**Comment by Kerkil** [comment]
@pavanky @TimmyLiu FWIW, here is my mistakenly submitted issue to clBLAS (https://github.com/clMathLibraries/clBLAS/issues/59). As you see there, there was no build error (note that the error code is 0 - without checking the error code, I just printed out the build log using clBLAS's function, and so the error message at the top is somewhat misleading) despite that the crash clearly happens somewhere in clBLAS currently based on the debugger output.

**Comment by Kerkil** [comment]
@pavanky I did a bit more dig-in.

There seem to be currently two issues:
1) The following code crashes:
```
// Matrix multiplication
void matmulproto()
{
    cl_command_queue queue = afcl::getQueue();

    const int M = 3;
    const int K = 3;
    const int N = 5;

    auto A = af::randn(M,K, f32);
    auto B = af::randn(K,N, f32);
    auto C = af::constant(1,M,N, f32);

    af_print(A);
    af_print(B);
    af_print(C);

    af::sync();

    cl_int err;
    cl_event event;

    err = clblasSgemm( clblasColumnMajor, clblasNoTrans, clblasNoTrans,
                       M,N,K,
                       1,
                       (cl_mem)(A.device<float>()), 0, K,
                       (cl_mem)(B.device<float>()), 0, N,
                       1,
                       (cl_mem)(C.device<float>()), 0, N,
                       0, &queue, 0, nullptr, &event
                       );

    std::cout << event << std::endl;
    std::cout << err << std::endl;

    err = clWaitForEvents( 1, &event );

    std::cout << event << std::endl;
    std::cout << err << std::endl;

    af_print(C);

}
```
The error messages are
```
0x1068f7055
-1023
The program has unexpectedly finished.
```
The first one is an event, the second is the clBLAS error code, and the last line is the run-time error.

2) If you replace
```
    auto A = af::randn(M,K, f32);
    auto B = af::randn(K,N, f32);
    auto C = af::constant(1,M,N, f32);
```
by removing the data types in creating `A,B,` and `C`, then the program does NOT crash, but `clblasSgemm` still does not return the correct results and `C` stays as the original constant matrix.
```
    auto A = af::randn(M,K);
    auto B = af::randn(K,N);
    auto C = af::constant(1,M,N);
```

I am not sure if this is of any use. Also, I am wondering if there are things that need to be fixed in this experiment or anything more that I can do to fix the issue.

**Comment by Kerkil** [comment]
@pavanky 

It appears that the issue is that the context used by ArrayFire and clBLAS are not the same:
```
   cl_int err;
    cl_platform_id platform = 0;
    cl_device_id device = 0;
    cl_context_properties props[3] = { CL_CONTEXT_PLATFORM, 0, 0 };
    cl_context ctx = 0;
    cl_command_queue queue = 0;
    cl_event event = NULL;


    /* Setup OpenCL environment. */
    err = clGetPlatformIDs( 1, &platform, NULL );
    err = clGetDeviceIDs( platform, CL_DEVICE_TYPE_GPU, 1, &device, NULL );

    std::cout << "device: " << device << std::endl;

    device = afcl::getDeviceId();

    std::cout << "device: " << device << std::endl;

    ctx = afcl::getContext();
    queue = afcl::getQueue();

    std::cout << "ctx: " << ctx << std::endl;
    std::cout << "queue: " << queue << std::endl;
//    af::info();

    props[1] = (cl_context_properties)platform;

    ctx = clCreateContext( props, 1, &device, NULL, NULL, &err );
    std::cout << "ctx: " << ctx << std::endl;

    queue = clCreateCommandQueue( ctx, device, 0, &err );
    std::cout << "queue: " << queue << std::endl;

    std::cout << "queue error: " << err << std::endl;
```
returns
```
device: 0x1024400
device: 0x1024400
ctx: 0x7fb6cab00a70
queue: 0x7fb6cab01ba0
ctx: 0x7fb6c84ed330
queue: 0x7fb6c84ec5e0
queue error: 0
```
I could reuse the device returned by `afcl::getDevice()` without any problems, but as soon as I used the context returned by `afcl::getContext()` in placed of a context that is created by 
`
ctx = clCreateContext( props, 1, &device, NULL, NULL, &err );
`
the results become garbage.

I am following `platform.cpp` to see if I can find where this can be addressed.

**Comment by pavanky** [comment]
@Kerkil 

Can you paste the entire code that you are trying to run ? Is there any reason you are trying to use clBLAS instead of af::matmul ? Is this simply part of the debugging process ?

Was the original problem occurring when you were just using ArrayFire matmul ? or were you using that code with something else ?

**Comment by Kerkil** [comment]
@pavanky Yes. It is a part of debugging process. I'd love to just use `af::matmul.` `af::matmul` currently crashes with no defined errors and so I was trying to find out where it crashes. I am doing this exercise to replicate the error with `af::matmul.`

Here is the entire piece of code:
```
void matmulproto()
{
    cl_int err;
    cl_platform_id platform = 0;
    cl_device_id device = 0;
    cl_context_properties props[3] = { CL_CONTEXT_PLATFORM, 0, 0 };
    cl_context ctx = 0;
    cl_command_queue queue = 0;
    cl_event event = NULL;


    /* Setup OpenCL environment. */
    err = clGetPlatformIDs( 1, &platform, NULL );
    err = clGetDeviceIDs( platform, CL_DEVICE_TYPE_GPU, 1, &device, NULL );

    std::cout << "device: " << device << std::endl;

    device = afcl::getDeviceId();

    std::cout << "device: " << device << std::endl;

    ctx = afcl::getContext();
    queue = afcl::getQueue();

    std::cout << "ctx: " << ctx << std::endl;
    std::cout << "queue: " << queue << std::endl;

    props[1] = (cl_context_properties)platform;

    ctx = clCreateContext( props, 1, &device, NULL, NULL, &err );
    std::cout << "ctx: " << ctx << std::endl;

    queue = clCreateCommandQueue( ctx, device, 0, &err );
    std::cout << "queue: " << queue << std::endl;

    std::cout << "queue error: " << err << std::endl;

    const int M = 4;
    const int K = 5;
    const int N = 3;

    cl_float A[M*K] = {
        11, 12, 13, 14, 15,
        21, 22, 23, 24, 25,
        31, 32, 33, 34, 35,
        41, 42, 43, 44, 45,
    };

    cl_float B[K*N] = {
        11, 12, 13,
        21, 22, 23,
        31, 32, 33,
        41, 42, 43,
        51, 52, 53,
    };

    cl_float C[M*N] = {
        11, 12, 13,
        21, 22, 23,
        31, 32, 33,
        41, 42, 43,
    };

    err = clblasSetup( );

    cl_mem bufA = clCreateBuffer( ctx, CL_MEM_READ_ONLY, M * K * sizeof(*A),
                          NULL, &err );
    cl_mem bufB = clCreateBuffer( ctx, CL_MEM_READ_ONLY, K * N * sizeof(*B),
                          NULL, &err );
    cl_mem bufC = clCreateBuffer( ctx, CL_MEM_READ_WRITE, M * N * sizeof(*C),
                          NULL, &err );


    err = clEnqueueWriteBuffer( queue, bufA, CL_TRUE, 0,
        M * K * sizeof( *A ), A, 0, NULL, NULL );
    err = clEnqueueWriteBuffer( queue, bufB, CL_TRUE, 0,
        K * N * sizeof( *B ), B, 0, NULL, NULL );
    err = clEnqueueWriteBuffer( queue, bufC, CL_TRUE, 0,
        M * N * sizeof( *C ), C, 0, NULL, NULL );

    float result[M*N];

    err = clblasSgemm( clblasRowMajor, clblasNoTrans, clblasNoTrans,
                       M,N,K,
                       1,
                       bufA, 0, K,
                       bufB, 0, N,
                       0,
                       bufC, 0, N,
                       1, &queue, 0, nullptr, &event
                       );

    std::cout << event << std::endl;
    std::cout << err << std::endl;

    err = clWaitForEvents( 1, &event );

    err = clEnqueueReadBuffer( queue, bufC, CL_TRUE, 0,
                                M * N * sizeof(*result),
                                result, 0, NULL, NULL );

    clblasTeardown();
}
```

Note that this piece of code works, but I cannot interface this with ArrayFire currently, which is why I love to fix `af::matmul` as soon as I can.

Also note that commenting `ctx = clCreateContext( props, 1, &device, NULL, NULL, &err );` will compile and run fie, but their results are wrong since the context assumed by clBLAS is not the same. 

I am actually quite confused since, apparently, you use the context and queue created by ArrayFire elsewhere without a problem. There seems to be something strange about interoperation between clBLAS and ArrayFire.

**Comment by Kerkil** [comment]
@pavanky Also, to be clear the code above using solely `af::matmul` crashes:
```
void testAFMatMul()
{
    std::cout << "test" << std::endl;
    try{

        af::info();

        const int nr = 48;
        const int nc = 7;

        af::array A = af::randn(nr,nc);
        af::array B = af::randn(nr,nc);
        af::array C = af::matmul(A, B, AF_NO_TRANSPOSE, AF_TRANSPOSE);
    } catch (af::exception& e) {
        fprintf(stderr, "%s\n", e.what());
        throw;
    }

}
```
This crashes with no exception thrown.

**Comment by pavanky** [comment]
@Kerkil 

I am able to reproduce this on one of our machine. Give me some time to dig in and fix it. I am sorry about the delay in this issue, I have been down with the flu for the last couple of days.

**Comment by Kerkil** [comment]
@pavanky No problem! I was just trying to help since I figured that you guys have tons of other stuff to take care of. Also, I love using ArrayFire and would like to contribute as much as I can to make it more widely usable. I think you guys have a cool project.

Again, I deeply appreciate your help. Also, hope you feel better.

**Comment by umar456** [comment]
It looks like the the problem is with clBLAS when you create a OpenCL context with multiple devices. The following example crashes with the same result.

```cpp
// Matrix multiplication
void matmulproto()
{
    cl_int err;
    cl_platform_id platform = 0;
    cl_device_id device[3];
    cl_context_properties props[3] = { CL_CONTEXT_PLATFORM, 0, 0 };
    cl_context ctx = 0;
    cl_command_queue queue = 0;
    cl_event event = NULL;


    /* Setup OpenCL environment. */
    err = clGetPlatformIDs( 1, &platform, NULL );
    err = clGetDeviceIDs( platform, CL_DEVICE_TYPE_GPU, 2, device, NULL );

    std::cout << "device: " << device << std::endl;

    props[1] = (cl_context_properties)platform;

    ctx = clCreateContext( props, 2, device, NULL, NULL, &err );
    std::cout << "ctx: " << ctx << std::endl;

    queue = clCreateCommandQueue( ctx, device[0], 0, &err );
    std::cout << "queue: " << queue << std::endl;

    std::cout << "queue error: " << err << std::endl;

    const int M = 4;
    const int K = 5;
    const int N = 3;

    cl_float A[M*K] = {
        11, 12, 13, 14, 15,
        21, 22, 23, 24, 25,
        31, 32, 33, 34, 35,
        41, 42, 43, 44, 45,
    };

    cl_float B[K*N] = {
        11, 12, 13,
        21, 22, 23,
        31, 32, 33,
        41, 42, 43,
        51, 52, 53,
    };

    cl_float C[M*N] = {
        11, 12, 13,
        21, 22, 23,
        31, 32, 33,
        41, 42, 43,
    };

    err = clblasSetup( );

    cl_mem bufA = clCreateBuffer( ctx, CL_MEM_READ_ONLY, M * K * sizeof(*A),
                          NULL, &err );
    cl_mem bufB = clCreateBuffer( ctx, CL_MEM_READ_ONLY, K * N * sizeof(*B),
                          NULL, &err );
    cl_mem bufC = clCreateBuffer( ctx, CL_MEM_READ_WRITE, M * N * sizeof(*C),
                          NULL, &err );


    err = clEnqueueWriteBuffer( queue, bufA, CL_TRUE, 0,
        M * K * sizeof( *A ), A, 0, NULL, NULL );
    err = clEnqueueWriteBuffer( queue, bufB, CL_TRUE, 0,
        K * N * sizeof( *B ), B, 0, NULL, NULL );
    err = clEnqueueWriteBuffer( queue, bufC, CL_TRUE, 0,
        M * N * sizeof( *C ), C, 0, NULL, NULL );

    float result[M*N];

    err = clblasSgemm( clblasRowMajor, clblasNoTrans, clblasNoTrans,
                       M,N,K,
                       1,
                       bufA, 0, K,
                       bufB, 0, N,
                       0,
                       bufC, 0, N,
                       1, &queue, 0, nullptr, &event
                       );

    std::cout << event << std::endl;
    std::cout << err << std::endl;

    err = clWaitForEvents( 1, &event );

    err = clEnqueueReadBuffer( queue, bufC, CL_TRUE, 0,
                                M * N * sizeof(*result),
                                result, 0, NULL, NULL );

    for(auto &r : result) {
        std::cout << r << " ";
    }

    clblasTeardown();
}
```

Notice that I am using the same code as @Kerkil but I created the context using the Iris Pro and the NVIDIA 750 GTX on my machine. Need to investigate further.

**Comment by pavanky** [comment]
@umar456 Thanks for narrowing it down! Do you want to report this upstream ? I also want to test this on Linux to see if this is failing.

**Comment by pavanky** [comment]
@TimmyLiu Any thoughts on the issue ?

**Comment by TimmyLiu** [comment]
My 2 cents. I did run Umar's code on my windows system with 2 AMD gpus (kaveri and r9 290). I did not see a crash and the output is:
 device: 00000000002DFA08
ctx: 0000000002B7C0E0
queue: 0000000002BF1370
queue error: 0
0000000004461CF0
0
2115 2180 2245 3665 3780 3895 5215 5380 5545 6765 6980 7195 

Also you can create multiple contexts, which is why earlier it was reported afcl:getcontext() was returning different context with clCreateContext(). I am guessing afcl:getcontext eventually calls to clCreateContext()? What I don't understand is why passing a queue created by the context to clBLAS would eventually cause a crash. It is possible that  clBLAS does not like device without double precision support. (which is silly because we are doing sgemm here.) But a quick hack would be setting an environment variable "GPU_DEVICE_ORDINAL". Assuming Iris is the device #0 "export GPU_DEVICE_ORDINAL=1,2" should mask it out. You can try clinfo to confirm.

**Comment by pavanky** [comment]
@TimmyLiu The latest code from @umar456 does not use any ArrayFire at all. It is a stand-alone file. I was unable to reproduce the problem on Linux machine with a GTX 690 (two gpus).

**Comment by Kerkil** [comment]
Cool. This works nicely. Thanks for the efforts to fix this!
