### ISSUE TITLE
OpenCL identity behaves incorrectly

### ISSUE THREAD

**Issue by Kerkil** [arrayfire/arrayfire#339]
I cannot generate an identity matrix larger than 10x10 correctly. For example, the array returned by `af::identity(11,11)` has 0 in the 11-th diagonal element, `af::identity(15,15)` has 5 trailing zero diagonal elements, and so on:
```
    af_print(af::diag(af::identity(11,11)).T());
    af_print(af::diag(af::identity(15,15)).T());
```
result in
```
af::diag(af::identity(11,11)).T() [1 11 1 1]
    1.0000     1.0000     1.0000     1.0000     1.0000     1.0000     1.0000     1.0000     1.0000     1.0000     0.0000 
af::diag(af::identity(15,15)).T() [1 15 1 1]
    1.0000     1.0000     1.0000     1.0000     1.0000     1.0000     1.0000     1.0000     1.0000     1.0000     0.0000     0.0000     0.0000     0.0000     0.0000 
```

**Comment by pavanky** [comment]
@Kerkil Thanks for reporting this. I also found another bug in diag because of this :) It should be fixed now.

**Comment by kerkilchoi** [comment]
@pavanky Cool. Thanks for the help!
