### ISSUE TITLE
oneAPI port fft slower than OpenCL fft by 2-10x [Perf]

### ISSUE THREAD

**Issue by pv-pterab-s** [arrayfire/arrayfire#3429]
oneAPI port fft slower than OpenCL fft by 2-10x. Most likely ArrayFire port issue. Reproduce by running example `fft_opencl` and compare with `fft_oneapi`.

**Comment by syurkevi** [comment]
Caching implemented for better performance in #3462. Remainder of slowdowns must be addressed upstream in MKL and should improve over time.
