### ISSUE TITLE
[Question]How to generate an array according to the rules defined by oneself?

### ISSUE THREAD

**Issue by wujilingfeng** [arrayfire/arrayfire#3431]
How to generate an array according to the rules defined by oneself?
For example , I want to calculate values based on index

**Comment by umar456** [comment]
Can you further elaborate what you want? I don't understand what you mean by "calculate values based on index".

**Comment by wujilingfeng** [comment]
> Can you further elaborate what you want? I don't understand what you mean by "calculate values based on index".

Such as `(i,j)-> i*j`, Calculate the product of matrix indices.Actually, my needs are more complex

**Comment by syurkevi** [comment]
You can generate indices using the [range](https://arrayfire.org/docs/group__data__func__range.htm#gsc.tab=0) functions varying across dim0 or dim1. If you need an overall linear index, you can also use the [iota ](https://arrayfire.org/docs/group__data__func__iota.htm#gsc.tab=0) function.

**Comment by syurkevi** [comment]
Marking issue as closed. Feel free to reach out on [Slack Chat](https://join.slack.com/t/arrayfire-org/shared_invite/MjI4MjIzMDMzMTczLTE1MDI5ODg4NzYtN2QwNGE3ODA5OQ) or
 [Google Groups](https://groups.google.com/forum/#!forum/arrayfire-users) if you have follow-up questions.
