### ISSUE TITLE
[Question]fft error on the Jetson AGX orin

### ISSUE THREAD

**Issue by mpereke** [arrayfire/arrayfire#3450]
I installed ArrayFire from source on the Nvidia Jetson AGX orin.

When I run any of the fft examples I get the following error:

ArrayFire v3.9.0 (CUDA, 64-bit Linux, build 7964d43b9)
Platform: CUDA Runtime 11.4, Driver: for
[0] Orin, 30588 MB, CUDA Compute 8.7
Benchmark N-by-N 2D fft
ArrayFire Exception (Internal error:998):
In function compileModule
In file src/backend/cuda/compile_module.cpp:291
NVRTC Error(6): NVRTC_ERROR_COMPILATION
Log: 
common/half.hpp(41): error: namespace "std" has no member "float_round_style"

common/half.hpp(41): error: namespace "std" has no member "round_to_nearest"

common/half.hpp(45): error: namespace "std" has no member "float_round_style"

common/half.hpp(45): error: namespace "std" has no member "round_to_nearest"

common/half.hpp(710): error: namespace "std" has no member "float_round_style"

common/half.hpp(710): error: namespace "std" has no member "round_to_nearest"

common/half.hpp(721): error: namespace "std" has no member "float_round_style"

common/half.hpp(722): error: namespace "std" has no member "enable_if_t"

common/half.hpp(722): error: expected a "," or ">"

common/half.hpp(721): error: namespace "std" has no member "round_to_nearest"

common/half.hpp(722): error: the global scope has no "value"

common/half.hpp(723): error: namespace "

May you please advice on how to resolve this issue.

Kind Regards
Evans

**Comment by mpereke** [comment]
Issue Resolved

When installing ArrayFire on the Orin from source:

1. Uninstall all the fmt and spdlog libs from the system
2. Install ArrayFire
3. Install the correct version of the fmt and spdlog dynamic libs from source

**Comment by edwinsolisf** [comment]
Closing as issue has been resolved

**Comment by mpereke** [comment]
See link below for fixing the correct version of spdlog and fmt libraries.

https://github.com/arrayfire/arrayfire/wiki/Known-Issues
