### ISSUE TITLE
accessing 8 bit bool array

### ISSUE THREAD

**Issue by hakttari** [arrayfire/arrayfire#346]
Hello,

How can I access the boolean type array in the following code?

array a = constant(1, 5, 5, b8);
BYTE *temp2 = (BYTE *)a.host<bool>(); // working in af2.0, but not in af3.0
bool *temp1 = a.host<bool>(); // not working in both af2.0 and 3.0.

**Comment by pavanky** [comment]
@hakttari Sorry about the delay!

`b8` is stored as `char` internally. You can use the following to access the array.

```
char *temp = a.host<char>();
```
