### ISSUE TITLE
Javascript

### ISSUE THREAD

**Issue by bhack** [arrayfire/arrayfire#348]
Do you think that there will be a possible path for having arrayfire to run on browser. You can see some [benchmarks of different techniques for BLIS here](https://github.com/Maratyszcza/blis-bench/blob/master/README.md). Also [river trail](https://github.com/IntelLabs/RiverTrail/wiki) and [SIMD.js] ( https://software.intel.com/en-us/articles/simd-javascript-faster-html5-apps) ecmascript standardization efforts are quite interesting. See also AMD [furious.js] (https://github.com/amd/furious.js/blob/master/README.md)

**Comment by pavanky** [comment]
While we don't have a version of arrayfire that works in the browser, we have a node wrapper available over here: https://github.com/arrayfire/arrayfire_js
