### ISSUE TITLE
Gfor convolve

### ISSUE THREAD

**Issue by matiasvt** [arrayfire/arrayfire#351]
I need to perform several 1D convolutions.
I was trying to do something like this (in a 1D version):

```
array kernel = array(3, 3, h_kernel, afHost);     // Transfer the kernel to gpu
array images = array(w, h, 10, h_images, afHost); // Transfer the images to gpu
array result = zeros(w, h, 10);
gfor (array idx, 10) {
    // 10 convolutions in parallel
    result(span, span, ii) = convolve(image(span, span, ii), kernel);
}
```

but I understand gfor is not supported right now.  Is there any alternative to do several 1D convolutions in paralell at present?

**Comment by pavanky** [comment]
@matiasvt From the code you showed, it looks like you are trying to do several 2D convolutions. Yet you mention 1D convolution in the issue. Am I missing something here?

**Comment by matiasvt** [comment]
I found that code in SO. It was an example of how to use gfor to perform convolutions in parallel. I wonder if this can still be achieved without the gfor support. I need 1D convolutions but I quoted that code because it was my first idea (gfor).

**Comment by pavanky** [comment]
@matiasvt 

Are you trying to do something like this ?

- You have a "N" signals of length "M" each.
- You have a filter/kernel of length "K"
- You want to convolve each singal with  the single kernel.

or is it a different scenario ?

**Comment by matiasvt** [comment]
I want to do exactly that. I thought I could do the convolution inside a gfor loop. 
The filter is somehow paticular because all the elements are the same. It could be solved like a prefix sum (linear vs cuadratic or n.log(n) convolution) but I have tons of data hence I'm interested in the gfor parallelism.

**Comment by pavanky** [comment]
@matiasvt You can just pass in a 2D array of signals and 1D array of filters to `convolve1`. This should work out of the box.

What are the sizes you are looking to operate at ?

**Comment by pavanky** [comment]
@matiasvt Is your issue resolved?

**Comment by matiasvt** [comment]
Yes, thanks! Sorry for the delayed answer. You've been really helpful.
