### ISSUE TITLE
[BUG] AF_JIT_KERNEL_TRACE with path fails on windows

### ISSUE THREAD

**Issue by errata-c** [arrayfire/arrayfire#3515]
Setting environment variable `AF_JIT_KERNEL_TRACE` to an absolute path on windows fails. Using `stdout` and `stderr` both function as expected.

I've traced the issue back to [src/backend/common/util.cpp](https://github.com/arrayfire/arrayfire/blob/master/src/backend/common/util.cpp?#L128), in the `saveKernel` function.

At line 128, the function call `FILE* f = fopen(ffp.c_str(), "we");` uses 'e' in the mode string, which is a nonstandard extension provided by glibc 2.3+.
This causes the call to fail for the windows binary. 
My installation of ArrayFire is the v3.9.0 release, installed with the provided installer at arrayfire.com.

The 'e' flag makes sure the file handle is released when one of the `exec` functions are called to replace the current process on Linux. This is unnecessary for windows as windows processes are not forked like in Linux.

**Comment by melonakos** [comment]
Hey, thanks for submitting this issue. I think you're right about this. Would you like to make a pull request for this issue?

**Comment by errata-c** [comment]
@melonakos I have submitted the PR for review.
