### ISSUE TITLE
afcuda to use same devices order than nvidia-smi

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#3518]
As today on a multi gpu machine, the order of gpus is different in AFcuda compared to nvidia-smi
The env var
CUDA_DEVICE_ORDER
does not seem to change anything. 

Description
===========
* What problem are you trying to solve?
selecting the gpu to run on
* (Optional) API of new function
none, just internally making afcuda follow the same order of gpu than nvidia-smi 
* (Optional)Are there other libraries that implement this feature?
pytorch

ref
https://stackoverflow.com/questions/52815708/order-of-cuda-devices

**Comment by syurkevi** [comment]
You may be able to set the desired devices corresponding to the native order by using the cuda interface function [setNativeId](https://arrayfire.org/docs/group__cuda__mat.htm#ga9def381dcf53190315f27a478a165b8b).   ArrayFire does not currently base device order from the cuda environment variables, but instead chooses the order based on predicted hardware performance.
