### ISSUE TITLE
exp for complex numbers

### ISSUE THREAD

**Issue by xingchenp** [arrayfire/arrayfire#352]
The function exp() does not accept the parameter of complex value, how to express exp(i*x) or complex value a+ib in mathematics? a is real part and b is imaginary part.

**Comment by pavanky** [comment]
We can implement this internally. But if you want a work around you can use this function instead:
```
array cexp(const array &in)
{
   if (!in.iscomplex()) return exp(in);
   return complex(cos(real(in)), sin(imag(in)));
} 
```

**Comment by xingchenp** [comment]
@pavanky yeah, it works, but there is little problem with your code, I think it should be this : 

array cexp(const array &in)
{
   if (!in.iscomplex()) return exp(in);
   return exp(real(in))*complex(cos(imag(in)), sin(imag(in)));
}

**Comment by pavanky** [comment]
@xingchenp oops you are right. I forgot the eulers formula :)
