### ISSUE TITLE
opencv2

### ISSUE THREAD

**Issue by pannous** [arrayfire/arrayfire#353]
CMake does not search nor find the installed opencv on mac 

Also it seems to be only compatible with opencv3?

`In file included from /opt/arrayfire/src/backend/cpu/Array.hpp:
'opencv2/core/cvdef.h'16 `

FIND_PACKAGE( OpenCV REQUIRED )
Does not help here

**Comment by pentschev** [comment]
@pannous ArrayFire has no dependency to OpenCV, `cvdef.h` is not included in `src/backend/cpu/Array.hpp`, where did you get your ArrayFire sources?

**Comment by pannous** [comment]
Thanks for the hint
Finally got it compiling by removing a conflicting  `/usr/local/include/types.hpp`
and setting `export CXX="/usr/bin/clang++ -std=c++11 -stdlib=libc++"`
