### ISSUE TITLE
Add 16-bit Data Type Support

### ISSUE THREAD

**Issue by nathanjackson** [arrayfire/arrayfire#357]
Supporting 16-bit data would be very useful.  I use 16-bit grayscale imagery all the time, having the ability to process this data without conversion would be very helpful.

Would probably be labeled as 'u16' or 's16'.

**Comment by Medivhita** [comment]
Added this feature in 3.0.1 installer?

**Comment by pavanky** [comment]
@nathanjackson The performance on 16 bit operations is going to be on par or worse than 32 bit operations. Unless you are worried about memory, I think converting to 32 bit and operating on them should be fine. We will leave this issue open for now and address this when we are doing push for mobile / embedded version of arrayfire.

**Comment by nathanjackson** [comment]
Could we add a constructor to read in 16 bit signed\unsigned into 32-bit floats?

**Comment by superchromix** [comment]
this would be very useful - I am also working with 16-bit image data

**Comment by mickeyil** [comment]
Could you add 16-bit support to saving images from array data? (such as 16-bit .png)

**Comment by shehzan10** [comment]
Creating issues https://github.com/arrayfire/arrayfire/issues/1063 for ImageIO and closing this.
