### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by svenstaro** [arrayfire/arrayfire#3614]
Hey, the last release is over a year old. Could you make a new release?

**Comment by melonakos** [comment]
We are working on one now. There are 46 PRs to merge once our new build and test environment are ready. It should be an excellent release with contributions from many in the community.

**Comment by svenstaro** [comment]
Perhaps there should be some kind of public checklist/tracking issue to show that this is being worked on? I don't think all of the current PR will be merged in the short term.

**Comment by melonakos** [comment]
We have set the PRs to be included in the upcoming release in this Milestone:  https://github.com/arrayfire/arrayfire/milestone/35

We're getting close!
