### ISSUE TITLE
[Feature Request] cuSOLVER integration

### ISSUE THREAD

**Issue by Kerkil** [arrayfire/arrayfire#362]
Integration of cuSOLVER to ArrayFire would be pretty cool: https://developer.nvidia.com/cusolver.

[I wish I could find a good equivalent for OpenCL.]

**Comment by pavanky** [comment]
@Kerkil We will be begin doing this as part of #7. Please watch out for our cuda7 branch. I am closing this for now as it seems to be a duplicate.

**Comment by Kerkil** [comment]
Yup. Thanks.
