### ISSUE TITLE
JIT Errors with CUDA 7

### ISSUE THREAD

**Issue by jramapuram** [arrayfire/arrayfire#364]
Hi there,
Running CUDA7 on OSX I get the following error on a simple join. Have not verified on CUDA6.5.

Code:

    af::array a = af::constant(1,2,3); af::array b = af::constant(0,2,3);
    DeviceState::log->info("pre test");
    af_print(af::join(0, a, b));
    DeviceState::log->info("post test");

This produces:

    2015-01-29 12:16:23.406240 [device] info: pre test
    1628, 92
    LOG:
    generated kernel: error: Module does not contain a triple, should be 'nvptx-' or 'nvptx64-'
    target datalayout = "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v16:16:16-v32:32:32-v64:64:64-v128:128:128-n16:32:64"

    define void @KL__s (
    float %val0,
    float* %out,
    i32 %ostr0, i32 %ostr1, i32 %ostr2, i32 %ostr3,
    i32 %odim0, i32 %odim1, i32 %odim2, i32 %odim3,
    i32 %blkx, i32 %blky) {

    entry:

    %tidx = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()
    %bdmx = call i32 @llvm.nvvm.read.ptx.sreg.ntid.x()
    %bidx = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()
    %bidy = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.y()
    %gdmx = call i32 @llvm.nvvm.read.ptx.sreg.nctaid.x()

    %boff = mul i32 %bidy, %gdmx
    %bid  = add i32 %boff, %bidx
    %goff = mul i32 %bid , %bdmx
    %gid  = add i32 %goff ,%tidx
    %idx  = sext i32 %gid to i64
    %el1  = mul i32 %odim0, %odim1
    %el2  = mul i32 %el1  , %odim2
    %el3  = mul i32 %el2  , %odim3
    %cmp0 = icmp slt i32 %gid, %el3
    br i1 %cmp0, label %core, label %end

    end:

    ret void

    core:

    %outIdx = getelementptr inbounds float* %out, i64 %idx
    store float %val0, float* %outIdx

    ret void

    }

    declare i32 @llvm.nvvm.read.ptx.sreg.tid.x() nounwind readnone
    declare i32 @llvm.nvvm.read.ptx.sreg.tid.y() nounwind readnone
    declare i32 @llvm.nvvm.read.ptx.sreg.ntid.x() nounwind readnone
    declare i32 @llvm.nvvm.read.ptx.sreg.ntid.y() nounwind readnone
    declare i32 @llvm.nvvm.read.ptx.sreg.ctaid.x() nounwind readnone
    declare i32 @llvm.nvvm.read.ptx.sreg.ctaid.y() nounwind readnone
    declare i32 @llvm.nvvm.read.ptx.sreg.nctaid.x() nounwind readnone

    !nvvm.annotations = !{!1}
    !1 = metadata !{void (
    float,
    float*,
    i32, i32, i32, i32,
    i32, i32, i32, i32,
    i32, i32
    )* @KL__s,
     metadata !"kernel", i32 1}
    Error in /Users/jramapuram/projects/test/arrayfire/src/backend/cuda/jit.cpp(221):
    NVVM Error (9): Failed to compile program

**Comment by pavanky** [comment]
@jramapuram The problem seems to be with our JIT not "join".

To verify, can you just try to print "a". I am guessing the same error should show up

**Comment by jramapuram** [comment]
Yup, you are right. Is this a CUDA7 specific issue?

**Comment by pavanky** [comment]
@jramapuram 

Looks like CUDA7 is more strict when it comes to parsing NVVM IR. I am fixing the issue as we speak. Expect it to be fixed in an hour or so :)

**Comment by pavanky** [comment]
@jramapuram If you pull from our cuda7 branch, the issue should be fixed.

**Comment by jramapuram** [comment]
Yup, works! Thank you. You rock!
