### ISSUE TITLE
sort_index and sort_by_key are not stable sorts on OpenCL

### ISSUE THREAD

**Issue by shehzan10** [arrayfire/arrayfire#394]
We currently use Boost.Compute's `sort_by_key` API for sort_index and sort_by_by_key ArrayFire functions on the OpenCL backend.

As a consequence of Boost.Compute's sort_by_key not being a stable sort, the sort_index and sort_by_key tests fail on all OSs for the OpenCL backends. There is an issue created for this feature in Boost.Compute https://github.com/kylelutz/compute/issues/377.

For now, we shall disable the index checks for these tests while this issue remains open. This will allow the tests to pass successfully.

**Comment by pavanky** [comment]
@shehzan10 compute currently has stable sort. Can you look into integrating it ?

**Comment by pavanky** [comment]
I think we can close this because of #573 considering there's stable alternatives now.

**Comment by shehzan10** [comment]
Although there is a different function for stable_sort_by_key in boost compute, the regular sort_by_key is also stable.
