### ISSUE TITLE
Program stuck with one CPU core 100%

### ISSUE THREAD

**Issue by MinChenONFS** [arrayfire/arrayfire#436]
Hello ArrayFire community,

We found one strange issue where the program is stuck with 100% CPU usage in one core and idled GPU. A sample code is:

```
#include <iostream>
#include <arrayfire.h>
#include <ctime>
#include <iomanip>
using namespace std;

int main()
{
	int R=1000;
	af::dtype Precision = f32;
	af::array A = af::constant(0.0,1,R,Precision);
	af::array Temp0 = af::constant(0.0,1,R,Precision);
	af::array Temp1 = af::constant(0.0,1,R,Precision);
	clock_t start= clock();
	for (int i=0; i<10000; ++i)
	{
		Temp0 = af::randn(1,R,Precision);
		Temp1 = af::randn(1,R,Precision);
		A += (Temp0 + Temp1);
		//A.eval();
	}
	cout << setprecision(9) << 1000* (clock() - start) / (float)CLOCKS_PER_SEC << " ms." << endl;
	return 0;
}

```
Without A.eval() the program takes 15450ms to run and with idled GPU. Using A.eval() will cure the problem with 520ms run time, but this is not observed with ArrayFire v2.

Is this behaviour intended? Thanks.

**Comment by pavanky** [comment]
@MinChenONFS Can you show the output of `af::info()` ?

**Comment by MinChenONFS** [comment]
ArrayFire v3.0.beta (CUDA, 64-bit Linux, build e1dcfc0)
Platform: CUDA Toolkit 6.5, Driver: 340.65
[0] Tesla M2090, 6144 MB, CUDA Compute 2.0
-1- GeForce 210, 1024 MB, CUDA Compute 1.2
30810 ms. //without .eval()
490 ms. //with .eval()

We see similar thing on a Tesla K40c.
Thanks.

**Comment by MinChenONFS** [comment]
Additional af::info() input for Tesla K40:
ArrayFire v3.0.beta (CUDA, 64-bit Linux, build b6e6105)
Platform: CUDA Toolkit 6.5, Driver: 340.65
[0] Tesla K40c, 12288 MB, CUDA Compute 3.5
-1- GeForce GT 610, 1024 MB, CUDA Compute 2.1

**Comment by pavanky** [comment]
@MinChenONFS I think I know why this is happening. I will require some time to fix this.

**Comment by MinChenONFS** [comment]
Thank you very much Pavan.

**Comment by MinChenONFS** [comment]
Some additional information might be useful: with a more complicated version of similar algorithm, by adding in the .eval() walk-around, we do see the speed up, but at the mean time one CPU core is used at 100% persistently. Not sure if it is related, but seems like there are some inefficiency in here since the algorithm should not be calling CPU at all.

**Comment by pavanky** [comment]
This issue may be related to #373. I am able to reproduce the 100% CPU usage by increasing the for loop size. I am trying to figure out which part of our code is taking up the CPU time. 

I noticed that CPU usage behavior is reproducible on our OpenCL backend as well. Perhaps it has something to do with an STL algorithm we are using internally.

**Comment by pavanky** [comment]
@MinChenONFS Can you please verify if the issue (without .eval()) is resolved ?

**Comment by MinChenONFS** [comment]
We see positive results in first a few tests. Thank you all for the quick turn-around.
