### ISSUE TITLE
Ubuntu build successful but half the tests are failing

### ISSUE THREAD

**Issue by cdeterman** [arrayfire/arrayfire#461]
I have just recently downloaded arrayfire to my Ubuntu system.  I followed the instructions detailed on your [wiki](https://github.com/arrayfire/arrayfire/wiki/Build-Instructions-for-Linux).  When I reached the 'Building ArrayFire' section I don't have a CUDA enabled GPU so my cmake call only enabled OpenCL.

    cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_CUDA=ON -DBUILD_OPENCL=ON

 Everything appears to compile fine following the `make` and `make install` calls.  However, when I run the tests, just over half the tests fail.  In particular tests 2 and 53 to 104 all fail.  When I look in the `Testing/Temporary/LastTest.log` file I see most of the errors are:

    OpenCL Error: Device Not Available when calling clCreateContext

Does this seem familiar or indicative of something I did wrong?  I thought I followed the instructions well enough but something seems off.

**Comment by 9prady9** [comment]
@cdeterman test 2 should be approx on cpu backend, can you please run the test individually and paste the output here.

53 and above are CUDA and OpenCL backend tests.

For OpenCL, which devices are available on your machine? The error you you see in log file usually means something is wrong with the OpenCL libraries setup. It is probably the reason even CUDA tests are failing.

Can you run any one CUDA test separately and paste that output as well here.

You can run tests individually by doing `./build/test/mean_cpu` or `./build/test/mean_cuda`

**Comment by pavanky** [comment]
@cdeterman Can you display the output of the following command:

```
cat /etc/OpenCL/vendors/*.icd
```

**Comment by cdeterman** [comment]
Sorry for the slower response.  The icd is:

`/opt/intel/opencl-1.2-4.5.0.8/lib64/libintelocl.so`

I believe one of the initial points by @9prady9 is likely the problem.  I was informed that my machine had a OpenCL device so I naively pushed forward without checking myself.  After your note, I looked with `lscpi | grep 'VGA'` and discovered that the GPU is an 'Intel Corproation Mobile 4 Series Chipset'.  I don't believe this GPU supports OpenCL so I am looking in to getting a newer chip.

I also ran some tests manually such as `./build/test/mean_opencl`.  The repeated error is `OpenCL Error: Device Not Available when calling clCreateContext`.  Once I get a new GPU installed I will recompile and try again.

**Comment by pavanky** [comment]
@cdeterman You may want to look into this post: http://arrayfire.com/opencl-on-intel-hd-iris-graphics-on-linux/ Beignet is an open source OpenCL driver for recent Intel GPUs. 

The intel SDK will not support Intel GPUs. However it does support the CPUs. So ArrayFire should have picked up your intel CPU as an OpenCL device. I am not sure why you are having a problem. Can you make sure you have installed both the intel OpenCL runtime and intel OpenCL SDK ?
