### ISSUE TITLE
CMake fails on Nvidia Jetson TK1 boards

### ISSUE THREAD

**Issue by stetie** [arrayfire/arrayfire#473]
I am compiling arrayfire on Nvidia Jetson TK1 board with the supplied Ubuntu 14.04 LTS, installed CUDA SDK is 6.0. I am using the latest devel-branch (commit 11f786b4d51bd5b41fbd08fcc85ce512aa9323fd )
**Steps to reproduce:**
Follow the build instructions in the wiki, the command
`cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_CUDA=ON`
results in the following error:
-- MKL library not found
-- Checking for [Accelerate]
-- Checking for [vecLib]
-- Checking for [cblas - atlas]
-- Includes found
-- Libraries found
-- CBLAS library found
-- BLAS Library: /usr/lib/libcblas.so.3;/usr/lib/libatlas.so.3
-- FFTW Found ? TRUE
-- FFTW Library: /usr/lib/arm-linux-gnueabihf/libfftw3.so;/usr/lib/arm-linux-gnueabihf/libfftw3f.so
-- Boost version: 1.54.0
-- Using LIBNVVM_HOME: /usr/local/cuda/nvvm
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_CUDA_LIBRARY (ADVANCED)
    linked by target "afcuda" in directory /mirror/jetson/code/arrayfire/src/backend/cuda

-- Configuring incomplete, errors occurred!

**Possible workaround:**
Invoking
`cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_CUDA=ON -DCUDA_CUDA_LIBRARY=/usr/local/cuda/lib/libcudart.so`
solved the problem for me.

**Comment by shehzan10** [comment]
We missed adding this to the instructions. Our suggested alternate is to run
```
cd /usr/lib/arm-linux-gnueabihf
sudo ln -s tegra/libcuda.so libcuda.so
```

**Comment by stetie** [comment]
Thanks, that works for me now. My workaround from above doesn't, it produces errors while compiling/linking.

**Comment by pavanky** [comment]
Hmm we should perhaps file a bug with CMake or NVIDIA to make sure their FindCUDA.cmake works on tegra devices?
