### ISSUE TITLE
matmulTN Crashes with "Unknown error" exception.

### ISSUE THREAD

**Issue by jeremysalwen** [arrayfire/arrayfire#476]
I build arrayfire from source according the instructions yesterday.  I have a reduced testcase of matmulTN crashing with the exception "Unknown Error"

```
#include <arrayfire.h>

int main(int argc, char** argv) {
  af::array A=af::randu(10,784);
  af::array b=af::randu(10);

  af::array c=af::matmulTN(A, b);
  std::cout<<c.scalar<double>()<<"\n";

}
```

I am on Debian unstable using the AMD OpenCL backend.  Here are the tests that failed
```
        Start  84: Test_reduce_opencl
 84/104 Test  #84: Test_reduce_opencl ...............***Failed    8.29 sec
        Start  86: Test_ireduce_opencl
 86/104 Test  #86: Test_ireduce_opencl ..............***Failed    7.25 sec
        Start  87: Test_diff2_opencl
 88/104 Test  #88: Test_medfilt_opencl ..............***Failed    2.40 sec
        Start 103: Test_mean_opencl
103/104 Test #103: Test_mean_opencl .................***Failed    3.36 sec

```

**Comment by pavanky** [comment]
@jeremysalwen Can you show the output of af::info ?

**Comment by jeremysalwen** [comment]
ArrayFire v3.0.beta (OpenCL, 64-bit Linux, build 1df8764)
[0] AMD     : AMD A8-5550M APU with Radeon(tm) HD Graphics

**Comment by pavanky** [comment]
Can you put a try catch block around your code and display the error ? You can look at helloworld example for reference.

Can you also run the failing tests individually to display errors ?

**Comment by jeremysalwen** [comment]
Here is the output from try-catch 
```
/home/jeremy/arrayfire/src/api/cpp/blas.cpp:36: AF_ERROR 13
```

**Comment by jeremysalwen** [comment]
Here is the output from the opencl_reduce test http://pastebin.com/enVGPrxt

**Comment by pavanky** [comment]
@jeremysalwen I am able to reproduce the mamtul problem. However the tests failing seems to be a bit off. We'll have a similar machine somewhere that we can try to bring up and do the testing.

**Comment by jeremysalwen** [comment]
To be fair, I am running the open source graphics drivers, with the ocl-icd OpenCL loader, and the non-free amd-opencl-icd library (from AMD?) so I'm kind of surprised that OpenCL works at all.  But I have tested some basic opencl libraries, and viennacl works with with OpenCL as well.

**Comment by pavanky** [comment]
@jeremysalwen Thanks for the heads up. If you have written down the information about how to get the setup working, we will try to set it up on our end in the near future.

**Comment by jeremysalwen** [comment]
The setup actually works out of the box for me.  To be specific:

 * Vanilla Debian unstable installation (I'm using the default installed open source drivers)
 * Installed the package ocl-icd-opencl-dev 
 * From the non-free repository installed the packge amd-opencl-icd

**Comment by pavanky** [comment]
@jeremysalwen The matmulTN issue should be fixed now. On a side note, it looks like you may be trying to do something with MNIST (that 784 looks distinctive). Are you using one of our machine learning examples or are you trying to do something from scratch ?

**Comment by pavanky** [comment]
Also can you create a separate issue with the failing tests ?

**Comment by jeremysalwen** [comment]
I'm doing something from scratch.  Originally I was just planning to implement Hessian Free optimization on the CPU, but the project has grown to include a neural network implementation with Adadelta SGD on the GPU...  Depending on how it goes I may turn this into a more general purpose library.
