### ISSUE TITLE
`regions()` crashes on Intel MIC for 32x32 images

### ISSUE THREAD

**Issue by gpryor** [arrayfire/arrayfire#480]
The following,

``` cpp
// Make a random array
const int len = 32;
array r = randn(len, len) * 10.0f;

// Convert to a binary image with thresholding
array in = (r > 5.0f);

// Find connected regions containing the same integer
regions(in);
```

, leads to,

```
*** OPENCL MIC DEVICE HW EXCEPTION ***: Segmentation fault (Address not mapped to object [0x7fe080000000])
```

Other `len` values such as 100 have the problem, as well, but the behavior is non-deterministic. 32 seems to be the best way to get the failure to occur - - about a 95% rate.

**Comment by 9prady9** [comment]
@arrayfire/core-devel Is this still an issue ?

**Comment by pavanky** [comment]
Let's close it as won't fix considering that Intel does not support OpenCL on their current generation anyway.
