### ISSUE TITLE
How best to create onehot vector?

### ISSUE THREAD

**Issue by jeremysalwen** [arrayfire/arrayfire#492]
What is the best way to create a onehot representation of an integer using Arrayfire?

for example, I would like to turn 

```
1
4
2
5
```

into a matrix like

```
010000
000010
001000
000001
```

Where I would give the parameter of the width of the onehot representation (in this case 6).

**Comment by pavanky** [comment]
@jeremysalwen 

Is the output a vector with "nth bit" set or is it a matrix with "nth column" set ?

**Comment by pavanky** [comment]
Nevermind, I re-read the discription. Give me sometime to ponder this.

**Comment by pavanky** [comment]
Ah I see you want to convert the target classes into one hot representation! We do that for our examples in [mnist_common.h](https://github.com/arrayfire/arrayfire/blob/devel/examples/machine_learning/mnist_common.h#L73). Look at the code under "expand". This is not the most efficient way to do things.

We will eventually be adding a function like the following:

```
array onehot = assign(zeros_array, indices, ones_array);
```

**Comment by jeremysalwen** [comment]
What about 

```
af::array x=zeros(numsamples, numclasses);
x(indices=1);
```

**Comment by WilliamTambellini** [comment]
Sparse array should now do similar job.

**Comment by 9prady9** [comment]
Below implementation on top of existing functions seems to be working fine. It assumes, values in `in` array are within the range of `width`.
```c++
array onehot(const af::array in, const unsigned int width) {
    const dim4 dims(in.elements(), width);

    array zeros   = constant(0, dims);
    array dim1Idx = iota(in.elements());
    array lnrIdx  = dim1Idx * in.elements() + in;

    zeros(lnrIdx) = 1;

    return zeros;
}
```

I have timed it using our [timeit](http://arrayfire.org/docs/timing.htm) to check the timings for generating such a matrix from a vector of 1000 elements provided the width is 1000 (same as `in.elements()` in my test case only).
```
./build/examples/helloworld/helloworld_cpu 
ArrayFire v3.8.0 (CPU, 64-bit Linux, build bd6bffded)
[0] AMD: AMD A10-7850K Radeon R7, 12 Compute Cores 4C+8G, 14949 MB
time taken for onehot: 0.00226435 seconds

./build/examples/helloworld/helloworld_opencl 
ArrayFire v3.8.0 (OpenCL, 64-bit Linux, build bd6bffded)
[0] NVIDIA: GeForce GTX 1060 3GB, 3011 MB
time taken for onehot: 0.000264142 seconds
```
For 10 K elements in `in` input array, this `onehot` function takes about 111 milliseconds on CPU backend and 2.5 milliseconds on OpenCL (GTX 1060 GPU).
