### ISSUE TITLE
Rcpp+ArrayFire

### ISSUE THREAD

**Issue by ogamimusashi** [arrayfire/arrayfire#493]
Hello,

This issue was brought here http://webcache.googleusercontent.com/search?q=cache:U8QJlHi_c1IJ:stackoverflow.com/questions/27105137/rcpp-with-arrayfire-library-for-gpu-computing+&cd=1&hl=fr&ct=clnk&gl=fr by user2503795, and Pavan Yalamanchili asked to post this issue on the git repo which i think the user did not.

I'm trying to use arrayfire with Rcpp and i've been trying the simple example provided in the link above. However i'm facing the exact same issue when i'm using sourceCpp:
Error in dyn.load("/tmp/RtmpdhvNqS/sourcecpp_95e63de2fb8/sourceCpp_70642.so") : 
  unable to load shared object '/tmp/RtmpdhvNqS/sourcecpp_95e63de2fb8/sourceCpp_70642.so':
  /tmp/RtmpdhvNqS/sourcecpp_95e63de2fb8/sourceCpp_70642.so: undefined symbol: _ZN2af5arrayD1Ev

Any insight?

Thank you!

**Comment by kafku** [comment]
@ogamimusashi 

 [This package](https://github.com/kafku/RcppFire) might be what you want.
Please note that RcppFire is under development, therefore so buggy.

Thanks.

**Comment by pavanky** [comment]
@kafku Wow thanks for building this! Let us know if you need any help from us.

**Comment by ogamimusashi** [comment]
Kafku:

Thank you very much for this package! i have some issue with it but posted it on the relevant git repo:)

Other than that i'd be interested in knowing  if the issue i reported above is a bug or some error from my part. 
(P.S: i know i posted issues in arrayfire_r, it is not that i'm impatient, it is just that i need to work and arrayfire brings some good prospects :) )

**Comment by pavanky** [comment]
@ogamimusashi Not a problem. Most of the functionality needed for arrayfire_r has been implemented as of #498 

Over the last couple of weeks we have been pushing for ArrayFire 3.0 beta. This has been tagged and "released" as of midnight tonight. We'll get on implementing the supplementary packages soon.

@kafku Your project looks interesting. I have very limited knowledge with Rcpp. Are there any benefits of using Rcpp instead of native R extensions ?

**Comment by kafku** [comment]
@pavanky 
Since I do not know much about native R extensions, it is hard for me to compare these two different approaches for developing R packages.
  
Rcpp looks much simpler, so I always use Rcpp when I want to integrate my C++ code and R.
  
[This file](http://dirk.eddelbuettel.com/code/rcpp/Rcpp-introduction.pdf) tells you about Rcpp in details. It compares Rcpp and native R extensions.
You can find examples for Rcpp in [Rcpp Gallery](http://gallery.rcpp.org/).

**Comment by pavanky** [comment]
@kafku if licenses permit, can we look into replacing arrayfire_r with rcppfire

**Comment by kafku** [comment]
@pavanky 
For now, RcppFire has a lot to fix, so it is better to wait till RcppFire gets stable. According to [this question](http://programmers.stackexchange.com/questions/254737/does-an-rcpp-dependent-package-require-a-gpl-license), R packages which depend on Rcpp reqire GPL.

**Comment by pavanky** [comment]
@kafku Thanks. 

@ogamimusashi Can this issue be closed?

**Comment by ogamimusashi** [comment]
pavan: I didn't find documentation for RcppFire and as kafku said it is still in development so as of now i still can't use any arrayfire related tool. I'd like to know if the issue i brought is a mistake from me(and the original poster) or a problem with arrayfire?

thank you!

**Comment by kafku** [comment]
@ogamimusashi 
I haven't added any examples for using RcppFire.
I checked that the following sample works on centos with CUDA.
```c++  
#include <RcppFire.h>
// [[Rcpp::plugins("cpp11")]]                                                                                                                                                               
// [[Rcpp::depends("RcppFire")]]
                                                                                                                                                                                                                                            
// [[Rcpp::export]]                                                                                                                    
af::array testaf_64(const RcppFire::typed_array<f64> & data)
{                                                                          
    return data * 2;                                                                                                                   
}        
```
Please try this code and notice me if you have any questions or problems by opening new [issues for kafku/RcppFire](https://github.com/kafku/RcppFire/issues).

**Comment by pavanky** [comment]
@ogamimusashi arrayfire_r repo can now be used with arrayfire. Please use the latest devel for the necessary changes.
