### ISSUE TITLE
Make process stuck

### ISSUE THREAD

**Issue by safi-huss** [arrayfire/arrayfire#518]
The make process gets stuck at approx.cpp.o, stdev.cpp.o at around 86%. Not sure if this is of any consequence, but cc1plus processes are in disk sleep.

machine is a Quad Core x64 (low end Pentium).

**Comment by safi-huss** [comment]
After a few runs, I realize it fails at make recipe for convolve_seperable.cpp.

**Comment by 9prady9** [comment]
@safi-huss Convolve has template specializations for certain filter sizes, in fact most of the kernels do have such specializations to speedup the code in known situations. This has increased the compilation time. Does the make process fail, as in terminate, at that point ? or it seems to be hung ?. If it seems to be hung, it could be possible that the compiler is still in the process of compiling the source files

Can you please try building only one backend ([CPU | CUDA | OpenCL]) at a time and check if that is helping.

Note: Please make sure you have the latest changes from master.

**Comment by safi-huss** [comment]
Yes... Stuck seems like a more appropriate description as make does not terminate and other processes seem to be running, albeit slowly.

I am running make after cmake -DBUiLD_CPU=ON as I type this. Will post my results. I notice, even now, the make references a few afopencl files. Such as src/backend/opencl/..../join.c while building for afcpu?

Is this intended behavior?

**Comment by safi-huss** [comment]
Stuck = Hung... Sorry about that.

**Comment by 9prady9** [comment]
Not really, it should only build CPU by default. Look here in [CMakeLists.txt](https://github.com/arrayfire/arrayfire/blob/devel/CMakeLists.txt#L8) for reference. 

To avoid the effect of any cmake cache files, please pass in the following options as well - 
`-DBUILD_CPU=ON -DBUILD_CUDA=OFF -DBUILD_OPENCL=OFF` to `cmake ..`.

**Comment by safi-huss** [comment]
Ah, I thought make clean would take care of this. 

Its running. Afcpu compiles without much issue.

On to afopencl.

**Comment by 9prady9** [comment]
@safi-huss How is the build going on ?

**Comment by safi-huss** [comment]
So afcpu builds without a hitch with just -DBUILD_CPU on. But afopencl runs into the same problems... You were right, the compiler seems to be doing something that grinds the system to a halt.

Also -Wdeprecated warnings. I get quite a lot of them.

**Comment by safi-huss** [comment]
Ok so can I build the library without convolution? Would that require me to make a lot of changes? Or is there a simpler way of doing this?

**Comment by 9prady9** [comment]
You may do it, You would have to remove all the source files related to convolve. Once you do that, CMake should automatically ignore convolution. 

But again, if compiling convolution is taking so long, then there are other functions in the library that take an equivalent amount of time to compile. So disabling function is not a right way to go about it in my opinion. 

**Note**: We have built binaries available on our website. If you just want to play with library, you can directly download the correct binaries from [here](http://arrayfire.com/download/). All you need to do is to just register yourself and then you can download the binary free of cost, no strings attached!

**Comment by safi-huss** [comment]
Understood. I will download the binary to proceed forward. But I would still like to go through the compilation process as an exercise, if you don't mind, (and me picking your brain while I am at it)

That said, I noticed during my last build that swap space was 80% utilized. So I am running a new build after increasing the swap space. Any idea what is the required space for a build process? RAM and Swap space?

**Comment by 9prady9** [comment]
How many threads are using while running the make command, as in `make -j` ? Try running the make process in single thread - `make` and leave it for a while. This necessarily might not reduce the amount of RAM being used but it will reduce the load on the system. However, the downside to running compilation in single thread is that it might take very long time. At ArrayFire, we almost never run make in single thread, so unfortunately i can't give you an estimate right away. Since it also depends on what hardware you have, it wouldn't be accurate as well. 

What is the configuration of your machine ? CPU, RAM etc.

**Comment by pavanky** [comment]
@safi-huss The RAM and SWAP are directly related to the number of threads you are using. If you use "make -j4", ~2GB may be enough. We are also looking into decreasing the memory footprint of our build process.

**Comment by safi-huss** [comment]
So I am running this on a very low end processor (Intel x64 Pentium N3540 4-core) with 2 GB of RAM running on a light debian based distro. I am evaluating arrayfire for possible embedded system use (but it seems more likely that I will have to move to a workstation).

I increase swap space by adding swap files to about 10 GB (just to try it out) but that does not have any affect on the build process. It usually stops/hangs at approx.cpp when trying to build afopencl. afcpu works fine. 

So I have stopped at attempts of building it on this machine. Moving to a new machine soon. Thanks for the help.

**Comment by pavanky** [comment]
@safi-huss We have plans to decreasing the resource limitations for the afopencl compile process. Please check issue #429 for more information.
