### ISSUE TITLE
Add function to manually free allocated, but unused device memory

### ISSUE THREAD

**Issue by bkloppenborg** [arrayfire/arrayfire#520]
If a large computation in ArrayFire is followed by a large custom OpenCL/CUDA kernel, there may not be a sufficient amount of memory available because the ArrayFire memory manager hasn't freed unused memory from the device. It would be useful to expose the `garbageCollect()` function from the backend to the API or otherwise let the user instruct ArrayFire to free all non-used allocated memory.

@pavan, I can propagate the `garbageCollect` function to the frontend fairly easily, but is this how you would prefer for it to be implemented?

**Comment by pavanky** [comment]
This is implemented in the top level now.
