### ISSUE TITLE
Interpreting results of regions()

### ISSUE THREAD

**Issue by safi-huss** [arrayfire/arrayfire#524]
I could not find any documentation on how to interpret the output array object of the regions() function.

**Comment by pentschev** [comment]
The output is basically an array with same size of input image, with connected components labeled from 0 to N, 0 being the background component. A longer documentation can be found in the following link (search for image_func_regions):

https://github.com/arrayfire/arrayfire/blob/devel/docs/details/image.dox

**Comment by safi-huss** [comment]
I went through this document before, but it does not give much details. I basically need information on how to parse the image and based on filtering criteria, mask out certain regions and keep others. I therefore need to extract some info about each region (such center of mass, span, number of pixels etc).

**Comment by 9prady9** [comment]
@safi-huss 

The documentation has been very recently updated to reflect the ArrayFire 3.0 beta API. We are constantly improving the details in documentation. I am working on adding more details to the documentation for regions function as we speak.

Please check back early next week for updated details.

Sorry for the inconvenience.
Pradeep.

**Comment by pavanky** [comment]
Additionally, the `regions` function only provides ids of the connected components in the image. To get the information you can use something like the following:
.
https://gist.github.com/pavanky/f4b9d760f9c4c776446e


The input to these functions is the output of `regions`.

We are going to add these functions natively to ArrayFire in the next couple of days.

**Comment by safi-huss** [comment]
Hi pavan,

I saw the updated documentation, and now I understand. However it seems I am getting some error/misinterpretation in the output.

Input image:
![output-1-pass-kmeans](https://cloud.githubusercontent.com/assets/11514322/6821817/bb9aef86-d2fc-11e4-80f7-3779caf6ea0c.jpg)

Output Image:
![output-connected-regions](https://cloud.githubusercontent.com/assets/11514322/6821848/f59c5724-d2fc-11e4-87e7-6cc6848af5e9.png)

I cant explain the output image based on the the documentation. Or maybe I am doing something wrong.

here is the code snippet:

	saveImage("output-1-pass-kmeans.jpg", img_out);

	array connected_regions = regions(img_out, AF_CONNECTIVITY_8);

	saveImage("output-connected-regions.bmp", connected_regions);

**Comment by 9prady9** [comment]
@safi-huss I was able to reproduce the results, we are looking into it. Thank you for reporting it.

**Comment by 9prady9** [comment]
regions accepts only binary arrays, hence the weird result. Can you please do `regions(img_out.as(u8), AF_CONNECTIVITY_8)`. That should fix your problem. 

The reason the library wasn't complaining was that, there was no check for this function on the input array for it's type. I have added the `.as`call within the library now. If you are using devel, please pull once again to have that change. But doing `.as(u8)` should resolve your issue as is.

**Comment by safi-huss** [comment]
Awesome

**Comment by 9prady9** [comment]
Please close the issue if it is no longer a problem. Thank you.

**Comment by safi-huss** [comment]
Thanks for the help. Closed
