### ISSUE TITLE
results of regions() dont match

### ISSUE THREAD

**Issue by safi-huss** [arrayfire/arrayfire#556]
This code be an algorithmic issue on my end, but it seems regions() function does not give the right amount of regions in an image.

Input image

![output-1-pass-kmeans](https://cloud.githubusercontent.com/assets/11514322/6939400/ceba5262-d885-11e4-89b1-0838bb1005ff.png)

Output image

![output-connected-region-filtered](https://cloud.githubusercontent.com/assets/11514322/6939412/f3029044-d885-11e4-9a96-d5ea9ef531d4.png)

Code snippet

	array connected_regions = regions(img_out.as(u8), AF_CONNECTIVITY_8);

...

	try {
		float * ptr = connected_regions.host<float>();
		for ( int y = 0; y < connected_regions.dims(0); y++ ) {
			for ( int x = 0; x < connected_regions.dims(1); x++ )
			{
				float pixel = ptr[x + y*connected_regions.dims(1)];
				bool label_found = false;
				for ( vector<ConnectedRegion>::iterator iter = con_reg_list.begin(); iter < con_reg_list.end(); iter++ ) {
					if ( iter->index == pixel )
					{
						iter->pixel_count++;
						if (x < iter->left) iter->left = x;
						if (x > iter->right) iter->right = x;
						if (y < iter->top) iter->top = y;
						if (y > iter->bottom) iter->bottom = y;
						label_found = true;
					}
				}
				if (!label_found)
				{
					ConnectedRegion region;
					region.pixel_count = 1;
					region.index = pixel;
					region.left = x;
					region.right = x;
					region.top = y;
					region.bottom = y;
					region.seed.x = x;
					region.seed.y = y;
					region.seed.isRgb = false;

					try {
						float * value = img_out.host<float>();
						region.seed.val = value[x + y*img_out.dims(1)];
						free(value);
					}
					catch (af::exception ex){
						cout << "In Location 2: main.cpp: ";
						cout << ex.what();
					}
					con_reg_list.push_back(region);
				}
			}
		}
	}
	catch (af::exception& ex) {
		cout << "In Location 1: main.cpp: ";
		cout << ex.what();
		return 1;
	}

I then filter the connected regions like this.

	sort(con_reg_list.begin(), con_reg_list.end(), comp_label);
	array connected_region_filtered = constant(0, connected_regions.dims(0), connected_regions.dims(1));
	for ( vector<ConnectedRegion>::iterator iter = con_reg_list.begin(); iter < con_reg_list.end(); iter++ ) {
		if ((iter->pixel_count > 0) && (iter->pixel_count < 5000)) {
			connected_region_filtered +=
					(connected_regions == constant(iter->index, connected_regions.dims(0), connected_regions.dims(1)))*255;
			regions_parsed++;
		}
	}

I dont know for sure but I think there should be more regions in the image. Am I doing something wrong or is regions() acting up for some reason? 

Added associated question: Does regions() work on grayscale images? Or only binary?

**Comment by 9prady9** [comment]
@safi-huss There are couple of issues with the above code.

*  Output of regions cannot be directly saved using `saveImage` for the following two reasons

        * output might have region labels with values more than 255
        * regions labelled with lower values wouldn't be clearly visible to naked eye as 
          they take lower intensity grayscale values.
    You would have to do some post-processing to actually see the regions.
*  Thought the type of input array `regions` expects is u8, the actual values of the array should be 0's and 1's. When regions was originally implemented we didn't have b8(boolean) type for arrays, we shall fix this soon. A quick fix for you in this case would be to threshold your input to before `regions` is called upon such as `array regions_input = image > 0.5f;`

**Comment by 9prady9** [comment]
```
inline float rand01() {
    float ret_val = rand()/(float)RAND_MAX;
    printf("Random value = %f\n", ret_val);
    return ret_val;
}

main(...)
{
// ... ArrayFire regions code
        float m = max<float>(b); // b is regions output

        af::array colors0 = (b==1.0f) * 255.0f * rand01() + (b!=1.0f) * 0.0f;
        af::array colors1 = (b==2.0f) * 255.0f * rand01() + (b!=2.0f) * 0.0f;
        af::array colors2 = (b==3.0f) * 255.0f * rand01() + (b!=3.0f) * 0.0f;

        for (float i=4.0f; i<m; i+=3.0f)
            colors0 += ((b==i) * 255.0f * rand01() + (b!=i) * 0.0f);

        for (float i=5.0f; i<m; i+=3.0f)
            colors1 += ((b==i) * 255.0f * rand01() + (b!=i) * 0.0f);

        for (float i=6.0f; i<m; i+=3.0f)
            colors2 += ((b==i) * 255.0f * rand01() + (b!=i) * 0.0f);

        af::array temp = join(2, colors0, colors1);
        af::array output = join(2, temp, colors2);
        af::saveImage("~/Downloads/output.png", output);
}
```
The above is a simple example how you might want to visually recognize the regions. Obviously i am over using red, blue & green colors by only varying their intensities, which is not probably the way you would want your regions to look like.

Using the above code, the regions image `output` would like below.
![output](https://cloud.githubusercontent.com/assets/3270458/6972197/24071776-d950-11e4-9245-9f12dc6040da.png)

**Comment by 9prady9** [comment]
After PR #560 , regions shall accept only binary images (`array`'s of type `b8`).

**Comment by safi-huss** [comment]
Awesome thanks! Closing issue... though I want to post some code... might help someone down the line.
