### ISSUE TITLE
Problem in DeviceManager() with OpenCL

### ISSUE THREAD

**Issue by KoldoRamirez** [arrayfire/arrayfire#572]
Hello all

I have tried AF in a new PC with an Intel HD4000 and a Nvidia Quadro K1000M. CPU and CUDA versions work well, but OpenCL version fails just before the program starts. The message is:

```
Error in ..\..\..\..\src\backend\opencl\platform.cpp(148):
OpenCL Error: Invalid Value when calling clGetDeviceIDs
Error in ..\..\..\..\src\api\c\data.cpp(193):
```

I cannot debug AF, but I have taken platform.cpp code to a different test program and I have reproduced the error. DeviceManager() constructor does a "for" with all DEVC_TYPES:

```C++
        cl_device_type DEVC_TYPES[] = {
            CL_DEVICE_TYPE_GPU,
#ifndef OS_MAC
            CL_DEVICE_TYPE_ACCELERATOR,
            CL_DEVICE_TYPE_CPU
#endif
        };
...
        for (auto devType : DEVC_TYPES) {
            for (auto &platform : platforms) {
                cl_context_properties cps[3] = {CL_CONTEXT_PLATFORM,
                                                (cl_context_properties)(platform()),
                                                0};
                std::vector<Device> devs;
                try {
                    platform.getDevices(devType, &devs);  // EXCEPTION THROWN HERE
                }
```

Using CL_DEVICE_TYPE_GPU in both cards causes no problem, but when using CL_DEVICE_TYPE_ACCELERATOR for Intel HD4000, getDevices() throws an exception. Testing getDevices(), the first call to clGetDeviceIDs() returns n = 0, and second call returns an error that causes the exception.

```
    cl_int getDevices(
        cl_device_type type,
        VECTOR_CLASS<Device>* devices) const
    {
...
        cl_int err = ::clGetDeviceIDs(object_, type, 0, NULL, &n);   // Returns n = 0
        if (err != CL_SUCCESS) {
            return detail::errHandler(err, __GET_DEVICE_IDS_ERR);
        }

        cl_device_id* ids = (cl_device_id*) alloca(n * sizeof(cl_device_id));
        err = ::clGetDeviceIDs(object_, type, n, ids, NULL);   // Probably calling it with n = 0 causes the error
        if (err != CL_SUCCESS) {
            return detail::errHandler(err, __GET_DEVICE_IDS_ERR);  // EXCEPTION THROWN HERE
        }
...
    }
```

**Comment by pavanky** [comment]
@KoldoRamirez What OS is this on ?

**Comment by KoldoRamirez** [comment]
Hello Pavanky

Windows 7 64 bits.

**Comment by pavanky** [comment]
@KoldoRamirez Were you able to get it working on your machine by just commenting out `CL_DEVICE_TYPE_ACCELERATOR` ?

**Comment by KoldoRamirez** [comment]
Hello Pavanky

By commenting out CL_DEVICE_TYPE_ACCELERATOR and CL_DEVICE_TYPE_CPU, program runs.

I do not know to use the OpenCL C++ bindings. Reading the platforms and devices using C I get:
```
Platform 0: Intel(R) OpenCL
  Device 0 (GPU): Intel(R) HD Graphics 4000; NoFP64 
  No CPU, No Accelerator
Platform 1: NVIDIA CUDA
  Device 0 (GPU): Quadro K1000M; FP64
  No CPU, No Accelerator
```
I am not sure but I think ::clGetDeviceIDs(object_, CL_DEVICE_TYPE_ACCELERATOR, 0, NULL, &n) returns CL_DEVICE_NOT_FOUND for Quadro K1000M, but CL_SUCCESS for Intel HD 4000. However for ::clGetDeviceIDs(object_, CL_DEVICE_TYPE_ACCELERATOR, n, ids, NULL), this card returns CL_INVALID_VALUE.

As AF code expects a CL_DEVICE_NOT_FOUND, it seems it fails with  Intel HD 4000 in my case.

Best regards
Koldo

**Comment by pavanky** [comment]
@KoldoRamirez Can you verify if `clGetDeviceIDs` is returning `CL_SUCCESS` using the C API ? If this is the case it looks like a problem with the OpenCL driver installed on your machine. Can you provide more info about the driver you installed ?

**Comment by KoldoRamirez** [comment]
Hello pavanky

Yes, Intel HD4000 clGetDeviceIDs for CL_DEVICE_TYPE_ACCELERATOR is returning CL_SUCCESS and returns 0 devices, but when calling clGetDeviceIDs the second time to get the devices list, it returns a -30.

In detail. Running:
```C++
#define CHECK_ERROR(err)	if(err != CL_SUCCESS) {printf("\nError %d in line %d", err, __LINE__);	return;}

void Demo1() {
    cl_uint numPlatforms, num_devices;
    CHECK_ERROR(clGetPlatformIDs(0, 0, &numPlatforms));

    cl_platform_id *platforms = new cl_platform_id[numPlatforms];
    CHECK_ERROR(clGetPlatformIDs(numPlatforms, platforms, 0));

    for(cl_uint iPlat = 0; iPlat < numPlatforms; ++iPlat) {
        char* platform_name = new char[1000];
        CHECK_ERROR(clGetPlatformInfo(platforms[iPlat], CL_PLATFORM_NAME, 1000, platform_name, 0));
		printf("\nPlatform %s", platform_name);
		
		cl_platform_id platform = platforms[iPlat];
	    
	  	CHECK_ERROR(clGetDeviceIDs(platform, CL_DEVICE_TYPE_ALL, 0, 0, &num_devices));
	    	
	  	cl_device_id* devices = new cl_device_id[num_devices];
	  	CHECK_ERROR(clGetDeviceIDs(platform, CL_DEVICE_TYPE_ALL, num_devices, devices, 0));
	  	
	  	for(cl_uint device_index = 0; device_index < num_devices; ++device_index) {
            cl_device_id device = devices[device_index];
           
            char* device_name = new char[1000];
        	CHECK_ERROR(clGetDeviceInfo(device, CL_DEVICE_NAME, 1000, device_name, 0));
        	printf("\n Device %s ", device_name);
        	    
            cl_device_type type;                                 
			size_t property_length;                          
			CHECK_ERROR(clGetDeviceInfo(device, CL_DEVICE_TYPE, sizeof(type), &type, &property_length));  
            switch(type) {
			case CL_DEVICE_TYPE_CPU:			printf("(cpu)");		break;	
			case CL_DEVICE_TYPE_GPU:			printf("(GPU)");		break;
			case CL_DEVICE_TYPE_ACCELERATOR:	printf("(Accelerator)");break;	
			}
			delete [] device_name;
        }	        
	    delete [] devices;
        delete [] platform_name;
    }
    delete [] platforms;
}
```
this is got:
```
Platform Intel(R) OpenCL
 Device Intel(R) HD Graphics 4000 (GPU)
Platform NVIDIA CUDA
 Device Quadro K1000M (GPU)
```
But running this (for Intel HD4000):
```C++
void Demo2() {
    cl_uint numPlatforms, num_devices;
    CHECK_ERROR(clGetPlatformIDs(0, 0, &numPlatforms));

    cl_platform_id *platforms = new cl_platform_id[numPlatforms];
    CHECK_ERROR(clGetPlatformIDs(numPlatforms, platforms, 0));

	cl_platform_id platform = platforms[0];
	    
	CHECK_ERROR(clGetDeviceIDs(platform, CL_DEVICE_TYPE_ACCELERATOR, 0, 0, &num_devices));
	    	
	cl_device_id* devices = new cl_device_id[num_devices];
	CHECK_ERROR(clGetDeviceIDs(platform, CL_DEVICE_TYPE_ACCELERATOR, num_devices, devices, 0));
	
	delete [] devices;
    delete [] platforms;
}
```
a -30 error id got.

Setting cl_platform_id platform = platforms[1]; (NVIDIA CUDA)

a -1 error is got, that is right.

A more complete output of HD 4000 platform is:
```
      CL_DEVICE_VENDOR: Intel(R) Corporation
      CL_DEVICE_PROFILE: FULL_PROFILE
      CL_DEVICE_VERSION: OpenCL 1.1
      CL_DRIVER_VERSION: 8.15.10.2639
      CL_DEVICE_OPENCL_C_VERSION: OpenCL C 1.1
      CL_DEVICE_COMPILER_AVAILABLE: 1
      CL_DEVICE_MAX_COMPUTE_UNITS: 16
      CL_DEVICE_MAX_CLOCK_FREQUENCY: 350
      CL_DEVICE_MAX_WORK_GROUP_SIZE: 512
      CL_DEVICE_ADDRESS_BITS: 64
      CL_DEVICE_MEM_BASE_ADDR_ALIGN: 1024
      CL_DEVICE_MAX_MEM_ALLOC_SIZE: 425721856
      CL_DEVICE_GLOBAL_MEM_SIZE: 1702887424
      CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE: 65536
      CL_DEVICE_GLOBAL_MEM_CACHE_SIZE: 2097152
      CL_DEVICE_GLOBAL_MEM_CACHELINE_SIZE: 64
      CL_DEVICE_LOCAL_MEM_SIZE: 65536
      CL_DEVICE_PROFILING_TIMER_RESOLUTION: 80
      CL_DEVICE_IMAGE_SUPPORT: 1
      CL_DEVICE_ERROR_CORRECTION_SUPPORT: 0
      CL_DEVICE_HOST_UNIFIED_MEMORY: 1
      CL_DEVICE_PREFERRED_VECTOR_WIDTH_INT: 1
      CL_DEVICE_PREFERRED_VECTOR_WIDTH_LONG: 1
      CL_DEVICE_PREFERRED_VECTOR_WIDTH_FLOAT: 1
      CL_DEVICE_PREFERRED_VECTOR_WIDTH_DOUBLE: 0
      CL_DEVICE_NATIVE_VECTOR_WIDTH_INT: 1
      CL_DEVICE_NATIVE_VECTOR_WIDTH_LONG: 1
      CL_DEVICE_NATIVE_VECTOR_WIDTH_FLOAT: 1
      CL_DEVICE_NATIVE_VECTOR_WIDTH_DOUBLE: 0
      CL_DEVICE_EXTENSIONS: cl_khr_icd cl_khr_global_int32_base_atomics cl_khr_g
lobal_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_
extended_atomics cl_khr_gl_sharing cl_khr_d3d10_sharing cl_intel_dx9_media_shari
ng cl_khr_3d_image_writes cl_khr_byte_addressable_store
```

**Comment by 9prady9** [comment]
@KoldoRamirez It appears to be a incorrect implementation of the API `clGetDeviceIDs`. According to OpenCL specification, when we query a platform for number of devices for a device type which is not available it is supposed to return `CL_DEVICE_NOT_FOUND` error code. However, it is returning CL_SUCCESS here with n set to zero which is incorrect.

Can you please check if you are using the latest OpenCL library.

**Comment by KoldoRamirez** [comment]
Hello Pavanky

I have tested the same code in a different computer but with the same card (Intel HD4000). 
In the second computer AF starts perfectly and clGetDeviceIDs behaviour is right . 
All output about OpenCL driver is the same in both PC, but the driver version, that is 
- 8.15.10.2639 for the bad
- 9.17.10.3517 for the good

...so I will try to update driver.

Best regards
Koldo

**Comment by KoldoRamirez** [comment]
Hello Pavanky

After updating graphics driver, AF starts perfectly in OpenCL :-)

In addition I would like to ask you to review two details:
- The initial error was thrown before program starts. This means that program is unable to catch it so program fails miserably. I would like you have a way to catch this exception.
- Program fails when a platform fails. However, if there are more than one platform, AF is unable to take the next available and maybe healthy platform/card.

Best regards
Koldo

**Comment by pavanky** [comment]
@KoldoRamirez 

We were handling the exceptions assuming the drivers are implementing the OpenCL spec properly. In your case an (old) Intel OpenCL driver was breaking the specification.

We can "solve" issues that you faced by doing some hacks, but they can have some unforseen problems. With that in mind, we'd rather keep our context handling mechanisms the way they are.

**Comment by KoldoRamirez** [comment]
Hello Pavanky

I agree with your comments and for me this issue is satisfactorily closed.

Anyway I would prefer if my source code could catch all exceptions thrown by AF. As this exception is thrown by AF BEFORE program is started, my source is unable to catch it so program crashes in an ugly manner.

Thank you for your support :-)

Best regards
Koldo
