### ISSUE TITLE
Feature: a function similar to fftfreq of numpy that tells frequencies of each output element

### ISSUE THREAD

**Issue by cdeepakroy** [arrayfire/arrayfire#573]
It would be nice to have a function similar to numpy's [fftfreq](http://docs.scipy.org/doc/numpy/reference/generated/numpy.fft.fftfreq.html#numpy.fft.fftfreq) that tells the frequency values of each element of the output of the fft functions. Or atleast, improve the documentation to make it very precise and clear unlike a very vague one provided by [fftw](http://www.fftw.org/fftw3_doc/The-1d-Discrete-Fourier-Transform-_0028DFT_0029.html#The-1d-Discrete-Fourier-Transform-_0028DFT_0029). I am guessing the same format is also used by arrayfire. This would save a lot of trouble with implementing things based on ffts such as the issue that i am currently facing with implementing derivatives that i have posted [here](http://stackoverflow.com/questions/29572719/what-are-the-frequencies-of-each-element-of-fft-output-in-arrayfire-for-computi) on stackoverflow. 

If you sift through fft based questions on many forums, the trouble pretty much boils down to whether or not the correct frequencies are used for each element for downstream calculations. 

I find so much of variations in the way normalization is done, the way these output frequencies are ordered, and poor documentation that reading things from one toolkit and applying it to the other doesnt seem to give expected results. 

It would be nice if such a function is provided by every toolkit so it saves a lot of developer time in debugging corner cases.

**Comment by pavanky** [comment]
@cdeepakroy I do not think there are a lot of variations in the way FFTs are ordered. FFTW, CUFFT and CLFFT all provide the outputs in the same order. ArrayFire's output follows the behavior other scientific packages like numpy / scipy. The inconsistency however can come from the normalization. 

Some notes about the way FFTS in ArrayFire behaves:

- The forward transform is not normalized. The inverse transform is normalized by the number of elements. 

- All transforms are converted to Complex to complex internally. This means the output of IFFT is always complex (even if the imaginary parts are 0). The output of FFT is always full (as opposed to storing only the non-redundant parts).

>  Or atleast, improve the documentation to make it very precise and clear unlike a very vague one provided by fftw.

We will add more information before we have a stable release of 3.0

**Comment by pavanky** [comment]
> It would be nice if such a function is provided by every toolkit so it saves a lot of developer time in debugging corner cases.

Please mention what these corner cases are. We need a better understanding of what the issues are so we can try to fix them.
