### ISSUE TITLE
Stucking with CUDAx64

### ISSUE THREAD

**Issue by Medivhita** [arrayfire/arrayfire#585]
Hi

I installed Visual studio 2013, cuda 6.5 toolkit and arrayfire betav3 (that installer...just install and append the path on environment variables)  on my GeForce 740M (compute capability 3.5).

CPUx64 and CLx64 seems work but with CUDAx64 i am still stucked at start

![immagarrayfire](https://cloud.githubusercontent.com/assets/12011614/7217156/00f93840-e61b-11e4-8627-f8434ab72d28.png)

**Comment by pavanky** [comment]
@Medivhita Can you tell us what nvidia driver you have installed on your system ?

**Comment by Medivhita** [comment]
The installed driver on GT 740M is 350.12 (release date 4/13/2015).

The driver is the same installed on another GPU (GTX 660 Ti) on another PC with old version of arrayfire 2.1 and it work fine.

**Comment by shehzan10** [comment]
Hey

Would you mind hitting break when it is stuck and give us a stack trace if available?

**Comment by Medivhita** [comment]
@shehzan10 

![immaginetestcuda](https://cloud.githubusercontent.com/assets/12011614/7236747/1097ed64-e797-11e4-9108-f51d11f46004.png)

**Comment by shehzan10** [comment]
Ah well, I guess that the dll was built in release mode so it wont show a useful stack trace. Sorry for that.

Can you switch from Debug mode to Release mode and see if the problem persists?

**Comment by ckeitz** [comment]
I had this same problem while getting set up on my laptop (hybrid system - GeForce 840M + Integrated Intel).

Mine started working after I:
1 - Verified environment variables
2 - Verified dependency dlls were in the ArrayFire/lib folder
3 - Executed a CUDA example

I might recommend executing one of the CUDA examples (installed by the toolkit) to make sure your CUDA platform is behaving.

**Comment by Medivhita** [comment]
@shehzan10 

I did your suggestion switching to release...it was still stucked...so i waited some more seconds...voilà...a fast output. I deleted the cuda folder and repeated the same with "debug" mode. It works...just wait some more seconds(maybe i need more 4 GB ram?)

Same "issue" with others examples like black_holes:options.

**Comment by shehzan10** [comment]
That's good to hear. It's just probably taking a bit of time to load all the symbols.
I'm quite certain that if you run it again, it wont take even that much time to load.
I don't think it has much to do with RAM.

**Comment by Medivhita** [comment]
well i'd like to thank all... @shehzan10 @ckeitz  @pavanky  for your "fast" help ^^
