### ISSUE TITLE
Use out of place fft transform whenever possible

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#590]
Currently all fft transforms in all backends use in place transformations. Use out of place when possible.

Check if the performance is better before doing this.

**Comment by pavanky** [comment]
@pentschev Can you do some performance analysis to see what are the times for each of the following in cuFFT, clFFT and FFTW for complex floats:

- Copying input to output, followed by inplace FFT
- Performing out of place FFT

**Comment by pentschev** [comment]
@pavanky you'll find the benchmarks in [1] and the code used to generate them in [2].

[1] https://gist.github.com/pentschev/9e7c50c1321d2b7c067d
[2] https://github.com/pentschev/fft_benchmark

**Comment by pavanky** [comment]
Currently all transforms in arrayfire are complex to complex. As @pentschev has shown, in place and out of place perform about the same for these transforms. Created a [new issue](https://github.com/arrayfire/arrayfire/issues/613) to deal with R2C and C2R transforms.
