### ISSUE TITLE
Ensure CMake creates installers in Linux and OSX 

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#595]

**Comment by shehzan10** [comment]
Isn't it already creating installer?

**Comment by bkloppenborg** [comment]
@shehzan10 , no, they are creating .tar.gz files instead of .rpm or .debs. 

@pavanky Should we look into the open build service for this or just ship he stock Debian debs and RedHat rpms made by CMake??

**Comment by shehzan10** [comment]
How would you incorporate examples into debian packages? Have a just lib, a just dev and another examples debian to install the examples?
How about have a libarrayfire, libarrayfire-dev (has include files) packages, and then ship a run file to install the examples and a makefile to build them?

**Comment by bkloppenborg** [comment]
@shehzan10 install examples the same place we already do. They can be compiled independently of ArrayFire now.

I like the idea of making separate packages, but I doubt many people will be using the runtime all by itself at the moment. If we were to do this, we should probably use OpenBuildService to make distro-specific packages.

**Comment by pavanky** [comment]
@bkloppenborg Is this issue fixed ?

**Comment by bkloppenborg** [comment]
Linux is complete. OSX packages as a self-extracting zip. Not sure if this is the ideal solution. Instructions need to be written for non-package manager solutions.

**Comment by pavanky** [comment]
I think we can close this issue then.
