### ISSUE TITLE
Add readme to example directory

### ISSUE THREAD

**Issue by bkloppenborg** [arrayfire/arrayfire#606]
Example directory does not contain any instructions for installation or compilation. Add a readme file to help people out.

**Comment by pavanky** [comment]
@bkloppenborg Is this necessary after especially after the post build instructions we have ?

**Comment by bkloppenborg** [comment]
After people install ArrayFire we should have something in the example directory that tells them how to use it. Perhaps just a README file that points to our docs or wiki would be sufficient.

**Comment by pavanky** [comment]
Fair enough. Just put what information you think is relevant.
