### ISSUE TITLE
ArrayFire OpenCL not working with NVIDIA 349 drivers

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#626]
- This is on an up to date Arch Linux System
- The same problem shows up with `clinfo`
- ArrayFire 2.1 does *not* seem to have the same problem
- Possibly an issue with a function being called in `cl.hpp` that was not used in ArrayFire 2.1

**Comment by pavanky** [comment]
Not able to reproduce this on an Ubuntu docker image using the same driver.

**Comment by pavanky** [comment]
Checked again, `clinfo` seems to be working in the Ubuntu image. ArrayFire still fails.

**Comment by 9prady9** [comment]
this is not happening on my Arch machine. Examples are also running fine.

**Comment by pavanky** [comment]
The problem seems to be the libOpenCL.so file that is installed from "ocl-icd" package in AUR. Removing the package and performing a clean build solved the problem.
