### ISSUE TITLE
harris_cuda fails due to not finding FreeImage even though it's installed

### ISSUE THREAD

**Issue by anshumang** [arrayfire/arrayfire#638]
This is the output log -
ArrayFire v3.0.beta (CUDA, 64-bit Linux, build 393d00d)
Platform: CUDA Toolkit 6.5, Driver: 346.29
[0] Tesla K40c, 11520 MB, CUDA Compute 3.5
-1- Tesla C2050, 3072 MB, CUDA Compute 2.0
** ArrayFire Harris Corner Detector Demo **

Error: Image IO requires FreeImage. See https://github.com/arrayfire/arrayfire
/opt/data1/share/users/anshuman/arrayfire/src/api/cpp/imageio.cpp:20: AF_ERROR 10
terminate called after throwing an instance of 'af::exception'

This is the dpkg output -
dpkg -L libfreeimage-dev
/.
/usr
/usr/include
/usr/include/FreeImage.h
/usr/include/FreeImagePlus.h
/usr/lib
/usr/lib/libfreeimageplus.a
/usr/lib/libfreeimage.a
/usr/share
/usr/share/doc
/usr/share/doc/libfreeimage-dev
/usr/share/doc/libfreeimage-dev/FreeImage3154.pdf.gz
/usr/share/doc/libfreeimage-dev/copyright
/usr/lib/libfreeimage.so
/usr/lib/libfreeimageplus.so
/usr/share/doc/libfreeimage-dev/changelog.Debian.gz

**Comment by shehzan10** [comment]
Can you install the libfreeimage3 package?

**Comment by anshumang** [comment]
dpkg -L libfreeimage3
/.
/usr
/usr/lib
/usr/lib/libfreeimageplus-3.15.4.so
/usr/lib/libfreeimage-3.15.4.so
/usr/share
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/libfreeimage3
/usr/share/doc
/usr/share/doc/libfreeimage3
/usr/share/doc/libfreeimage3/changelog.Debian.gz
/usr/share/doc/libfreeimage3/copyright
/usr/lib/libfreeimageplus.so.3
/usr/lib/libfreeimage.so.3

**Comment by anshumang** [comment]
Does the order matter? I installed libfreeimage3 followed by libfreeimage-dev

**Comment by shehzan10** [comment]
What are the values for `FREEIMAGE_INCLUDE_PATH` and `FREEIMAGE_LIBRARY` in CMake?
Did you clear the cache and try?

**Comment by anshumang** [comment]
No didn't clear the CMake cache. Did a clean rebuild. Trying clear cache.
This is the cmake -L output => 
CMake Error: The source directory "/opt/data1/share/users/anshuman/arrayfire/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
-- Cache values
BUILD_CPU:BOOL=ON
BUILD_CUDA:BOOL=ON
BUILD_DOCS:BOOL=OFF
BUILD_EXAMPLES:BOOL=ON
BUILD_GTEST:BOOL=ON
BUILD_OPENCL:BOOL=OFF
BUILD_TEST:BOOL=ON
CMAKE_BUILD_TYPE:STRING=
CMAKE_INSTALL_PREFIX:PATH=/opt/data1/share/users/anshuman/arrayfire/install
CUDA_BUILD_CUBIN:BOOL=OFF
CUDA_BUILD_EMULATION:BOOL=OFF
CUDA_HAVE_GPU:BOOL=TRUE
CUDA_HOST_COMPILER:FILEPATH=/usr/bin/cc
CUDA_SDK_ROOT_DIR:PATH=CUDA_SDK_ROOT_DIR-NOTFOUND
CUDA_SEPARABLE_COMPILATION:BOOL=OFF
CUDA_TOOLKIT_ROOT_DIR:PATH=/usr/local/cuda
CUDA_VERBOSE_BUILD:BOOL=OFF
FFTWF_LIB:FILEPATH=/usr/lib/x86_64-linux-gnu/libfftw3f.so
FFTWL_LIB:FILEPATH=/usr/lib/x86_64-linux-gnu/libfftw3l.so
FFTW_LIB:FILEPATH=/usr/lib/x86_64-linux-gnu/libfftw3.so
INTEL_COMPILER_DIR:STRING=
INTEL_MKL_DIR:STRING=
INTEL_MKL_SEQUENTIAL:BOOL=OFF
LIBNVVM_HOME:PATH=/usr/local/cuda/nvvm
NVVM_H:FILEPATH=/usr/local/cuda/nvvm/include/nvvm.h
NVVM_LIB:FILEPATH=/usr/local/cuda/nvvm/lib64/libnvvm.so
USE_RELATIVE_TEST_DIR:BOOL=OFF
WITH_COVERAGE:BOOL=OFF

**Comment by anshumang** [comment]
Didn't have FREEIMAGE_INCLUDE_PATH and FREEIMAGE_LIBRARY. Found after clearing CMake cache.

**Comment by anshumang** [comment]
Is there a way to rebuild a specific example?

**Comment by shehzan10** [comment]
I really don't need all those values.
Just go into the build directory, do `ccmake ..`, do toggle for advance and check the freeimage variables.
Otherwise run cmake -LA. Please post only the freeimage values here.

**Comment by anshumang** [comment]
The freeimage values weren't there before. Now they are after clearing the cache.
FREEIMAGE_INCLUDE_PATH:PATH=/usr/include
FREEIMAGE_LIBRARY:FILEPATH=/usr/lib/libfreeimage.so

I did a rebuild of arrayfire. Now the build instructions says 'make test' to build the examples and the tests.
Can I just build a specific example?

**Comment by shehzan10** [comment]
So now it was detected by CMake. Yup, rebuild arrayfire. Do ldd on libafcuda.so and verify that freeimage is correctly linked.
You do not have to run make test. You can simply run the example that should have been built.
Worst case, delete build/examples and do make again. It should rebuild the examples.

**Comment by anshumang** [comment]
Got it :+1:

**Comment by anshumang** [comment]
hmm..that's weird..
ldd output =>
ldd ./src/backend/cuda/libafcuda.so
        linux-vdso.so.1 =>  (0x00007fffa5dd0000)
        libcudart.so.6.5 => /usr/local/cuda/lib64/libcudart.so.6.5 (0x00007f5a4613b000)
        libcublas.so.6.5 => /usr/local/cuda/lib64/libcublas.so.6.5 (0x00007f5a44698000)
        libcufft.so.6.5 => /usr/local/cuda/lib64/libcufft.so.6.5 (0x00007f5a41c74000)
        libnvvm.so.2 => /usr/local/cuda/nvvm/lib64/libnvvm.so.2 (0x00007f5a40db1000)
        libcuda.so.1 => /usr/lib/x86_64-linux-gnu/libcuda.so.1 (0x00007f5a3ff05000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5a3fc01000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5a3f8fb000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5a3f6e4000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5a3f31f000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5a3f11b000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5a3eefc000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f5a3ecf4000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f5a4ad28000)

**Comment by shehzan10** [comment]
Would you mind doing a clean build from scratch? Delete the build directory and start again.
From the output you gave, it doesn't look like it actually tried to link free image.

So delete the directory and run the steps again. Before doing make after cmake, check the freeimage values as earlier to verify. And then build it

**Comment by anshumang** [comment]
Works finally.
Output =>
ArrayFire v3.0.beta (CUDA, 64-bit Linux, build 393d00d)
Platform: CUDA Toolkit 6.5, Driver: 346.29
[0] Tesla K40c, 11520 MB, CUDA Compute 3.5
-1- Tesla C2050, 3072 MB, CUDA Compute 2.0
** ArrayFire Harris Corner Detector Demo **

Corners found: 4

corners_x [4 1 1 1]
   Offsets: [0 0 0 0]
   Strides: [1 4 4 4]
       240 
       240 
       399 
       399 

corners_y [4 1 1 1]
   Offsets: [0 0 0 0]
   Strides: [1 4 4 4]
       160 
       319 
       160 
       319 

hit [enter]...
Sorry for not reading the README thoroughly....thanks for the quick support.
