### ISSUE TITLE
Logical ops array type inconsistent

### ISSUE THREAD

**Issue by FilipeMaia** [arrayfire/arrayfire#658]
When doing something like c = a < b; the type of c is u8 which is not considered a boolean according to c.isbool(). This doesn't make sense and causes problems if one tries to use the result for example on a call to where(c,a,b) (c will be interpreted as an array of indices instead of a boolean array which the user would expect).
There seems to be two possible solutions. Either make the operators use b8 or make isbool() return true for u8.

**Comment by pavanky** [comment]
@FilipeMaia This bug has been fixed in devel. I am assuming you are using the installer from the website. We are going to make a final release pretty soon so you should have an installer with the fixed version. If not you can build the devel branch to get the fix.

Here is my experiment:

```
        af::array a = randu(5, 5);
        af::array b = randu(5, 5);
        af::array c = a < b;
        printf("%d, %d, %d\n", c.type(), b8, c.isbool());
```
Output:
```
4, 4, 1
```
