### ISSUE TITLE
Bug in af_get_last_error

### ISSUE THREAD

**Issue by FilipeMaia** [arrayfire/arrayfire#665]
[err_common.cpp:157](https://github.com/arrayfire/arrayfire/blob/devel/src/api/c/err_common.cpp#L157 src/api/c/err_common.cpp) is ```str[*len] = '\0';``` when it should be ```(*str)[*len] = '\0';```
This also prevents compilation with clang.

**Comment by pavanky** [comment]
@FilipeMaia Do you want to send in a pull request to fix this ?

**Comment by FilipeMaia** [comment]
Sure.
