### ISSUE TITLE
Add support for N-D arrays (for N greater than 4)

### ISSUE THREAD

**Issue by futurely** [arrayfire/arrayfire#677]
Your CEO said that the C functions supported up to 4-D arrays in his talk at this year's NVIDIA GTC while [Blobs are N-D arrays (for N not necessarily equals 4)](https://github.com/BVLC/caffe/pull/1970) in Caffe. 

@umar456, your ml_lab implemented neural networks that were much more concise than Caffe. What do you think about this?

**Comment by pavanky** [comment]
We are going to either integrate with or implement features available in Caffe and Torch.  Most of these extra dimensions are for holding data in a particular format and do not signify a specific meaning. This will require us to implement classes on top of the existing af::array class to emulate more "dimensions".

However we can not change the underlying base class.
