### ISSUE TITLE
Sort function - wrong index values (CPU backend)

### ISSUE THREAD

**Issue by munnybearz** [arrayfire/arrayfire#678]
ArrayFire v3.0.beta (CPU, 64-bit Mac OSX, build 1e1e85b)

The index values returned by the sort function are wrong:

```c++
    const float test[] = { 2, 3, 1 };
    array arr(3, test);
    af_print(arr);

    array vals, inds;
    sort(vals, inds, arr);
    af_print(vals);
    af_print(inds);
```

Output:

```
arr [3 1 1 1]
    2.0000
    3.0000
    1.0000

vals [3 1 1 1]
    1.0000
    2.0000
    3.0000

inds [3 1 1 1]
         2
         0
         1
```

Expected output:

```
inds [3 1 1 1]
         1
         2
         0
```

**Comment by shehzan10** [comment]
The indices are correct.
The way indices are represented are `val = array(inds)`.
So [1, 2, 3] = [2, 3, 1](2, 0, 1).

Can you describe why you expected them to be 1, 2, 0?

**Comment by munnybearz** [comment]
Ahhh I seee.. sorry, I thought the indices were indices of the original array! I will adjust my code
