### ISSUE TITLE
Integrate with cuDNN that the most popular deep learning frameworks have adopted

### ISSUE THREAD

**Issue by futurely** [arrayfire/arrayfire#688]
The recently released [cuDNN](https://developer.nvidia.com/cuDNN) v2 has superior performance acceleration compared with any other deep learning kernels. "Several widely used machine learning frameworks support cuDNN acceleration, including UC Berkeley’s Caffe, NYU's Torch, and University of Montreal’s Theano, as well as many other software projects." 

Lack of cuDNN is a major blocker to implement a high performance deep learning framework with arrayfire.

Caffe
https://github.com/BVLC/caffe/pull/2038
https://github.com/BVLC/caffe/search?utf8=%E2%9C%93&q=cudnn

Torch7
https://github.com/soumith/cudnn.torch

Theano
https://github.com/Theano/Theano/pull/2356
https://github.com/Theano/Theano/search?utf8=%E2%9C%93&q=cudnn

**Comment by pavanky** [comment]
This needs to be a separate project or a fork. We can not support cuDNN in mainline arrayfire as it is hardware specific.

**Comment by futurely** [comment]
Even CXXNET has caught up.
https://github.com/dmlc/cxxnet/search?utf8=%E2%9C%93&q=cudnn

Those DL libraries use compile time flags to set macros to enable cuDNN acclerated codes. If the users don't have the required hardware and opt out cuDNN, the legacy GPU kernels still function well.

I wonder if you want to do some benchmarks against some other implementations before giving up.
https://github.com/soumith/convnet-benchmarks

**Comment by pavanky** [comment]
I didn't say we are giving up. I was just making a point that the development for this should perhaps happen in a different repo.

**Comment by umar456** [comment]
I think what @pavanky is trying to say is that cDNN is an excellent library but it need to be used in conjunction with ArrayFire rather than a part of ArrayFire itself. Perhaps a machine learning library which makes use of ArrayFire and cuDNN. We have plans to create something like this in the near future.

**Comment by jramapuram** [comment]
Can cuDNN not be integrated into the src/backend/cuda calls?
Obviously cuDNN cannot help improve OpenCL, CPU backends..

**Comment by pavanky** [comment]
@jramapuram The base ArrayFire needs to be the following.

- Provide highly performant parallel programming primitives that enable users to build high level programs.

- Provide the same consistency across all platforms.

We would love to support cuDNN in ArrayFire. But it is too high level of a library and also device dependent. I think the best course of action for us would be to start a machine learning project. This would integrate with cuDNN and other machine learning libraries out in the open. We would also try to port the same functionality to OpenCL in that library.

I created a new repo to address this: https://github.com/arrayfire/arrayfire_ml/issues/1

We will begin contributing to this soon.

**Comment by jramapuram** [comment]
Makes sense, thanks!
