### ISSUE TITLE
ArrayFire versioning scheme

### ISSUE THREAD

**Issue by ghisvail** [arrayfire/arrayfire#692]
Dear ArrayFire developers,

Could you guys clarify the versioning scheme you have adopted for the ArrayFire development ? I saw that each backend has a soversion set to the major version of ArrayFire, which is currently 3. Does it mean, you guys commit not to break the ABI for subsequent minor releases of the project, i.e. 3.1, 3.2...?

Best regards,
Ghis

**Comment by umar456** [comment]
Hi ghisvail

We are committed to solidifying the ABI before we release. We are currently in the process of auditing our interface to make sure we can keep this contract for the foreseeable future. We plan to follow the guidelines outlined in the [Apache Portable Runtime Project](https://apr.apache.org/versioning.html).

**Comment by ghisvail** [comment]
Thanks for clarifying. That would be great if you guys conform with the APR guidelines from a packaging point of view. Good luck with that and keep up the good work !

**Comment by pavanky** [comment]
I think we need to be explicit about the architectures we are willing to maintain ABI stability for in each version. There may be architectures on which ArrayFire **builds** that we do not have internally. 

For this reason, I think it is fair to start the "contract" for the following architectures on Linux.

- x86
- x86_64
- ARM
- ARM64 (using gcc)
