### ISSUE TITLE
Link failures following fce4ad5

### ISSUE THREAD

**Issue by munnybearz** [arrayfire/arrayfire#696]
My software fails to link following commit fce4ad5. I've isolated it to that change by continuously rebuilding arrayfire and trying to link my software. The commit before that one works fine.

The link errors appear like this:

```
meow.o: In function `main':
/home/ubuntu/meow/meow.cpp:92: undefined reference to `af::array::array<double>(int, int, double const*, af::af_source_t, int)'
/home/ubuntu/meow/meow.cpp:92: undefined reference to `af::moddims(af::array const&, int, int, int, int)'
toptest.o: In function `TopTest::getTests(af::array const&)':
/home/ubuntu/meow/toptest.cpp:18: undefined reference to `af::constant(int, int, af_dtype)'
stdevtest.o: In function `StdevTest::getTests(af::array const&)':
/home/ubuntu/meow/stdevtest.cpp:11: undefined reference to `af::mean(af::array const&, int)'
/home/ubuntu/meow/stdevtest.cpp:12: undefined reference to `af::stdev(af::array const&, int)'
make: *** [meow] Error 1
```

I'm using clang++ 3.6.1 and G++ 5.1.0 on Ubuntu x86_64. Let me know if you need any more info.

**Comment by pavanky** [comment]
@munnybearz Can you do a clean build and see if this is still failing ? If some of the files are pre-compiled this may be causing issues.

**Comment by munnybearz** [comment]
Hi Pavan,

Thanks for responding so quickly as usual :)

I started by completely deleting the arrayfire directory and downloading the latest devel source to build from scratch, which still gave the link errors. Then I did the following sequence of commands each time to test the next commit:

(in arrayfire/build)
git reset --hard <commit id>
rm -rf *
cmake .. -DCMAKE_BUILD_TYPE=Release
make -j10
make install

Then proceeded in my software:

make clean (which just rm -rf all the obj's and binary)
make

Is this sufficient?

**Comment by pavanky** [comment]
That should be sufficient for arrayfire. But the link errors you are seeing seem to come from your project. So I am assuming some object files in your project are not deleted ? Or perhaps your project is finding header files from an older version of ArrayFire.

**Comment by pavanky** [comment]
@munnybearz any updates

**Comment by munnybearz** [comment]
Hi. I haven't been able to solve this so far :(

I've definitely cleaned every trace of compiled files in my project dir. I've been really trying to figure out why it won't link. I'm using the -v option in the compile and link commands and it looks correct. The include path list shows the include directories being used and I checked that array.h and defines.h were updated.

For now I've just branched off from efbd29e and cherry picked all the changes after that except fce4ad5. It builds and links successfully. I need to revisit this issue on the weekend.

**Comment by pavanky** [comment]
is this happening for all backends or just cpu ?

**Comment by pavanky** [comment]
Can you also post a sample of your project so we can try to reproduce the problem ?

**Comment by pavanky** [comment]
btw, can you check if you are able to build tests in arrayfire ?

**Comment by munnybearz** [comment]
Hi, yes all the tests and examples build. I haven't tried the opencl backend. I'll prepare an EC2 ami which shows the issue.

**Comment by pavanky** [comment]
@munnybearz hey I think we just figured out the issue. If you are testing this, can you put "#define ARCH_64" before including any ArrayFire headers and see if that fixes the issue ?

**Comment by munnybearz** [comment]
ah that looks interesting! Ok I'm rebuilding the latest devel arrayfire libs now and will try this define. will update in a mo

**Comment by munnybearz** [comment]
YES THAT WORKED!! I added a -DARCH_64 in my compiler flags and I can build and link successfully now with the latest devel :+1:

**Comment by pavanky** [comment]
Arlight, thanks for confirming! We are fixing it in our library as we speak.
