### ISSUE TITLE
Linear Algebra functions

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#7]
Possible libraries for CPU:
- netlib's LAPACK
- netlib's PLASMA
- Intel's MKL

Possible libraries for CUDA:
- MAGMA
- CULA

Possible libraries for OpenCL:
- clMAGMA
- ViennaCL

**Comment by Kerkil** [comment]
@pavanky Is there anything that I can use to decompose a matrix to find a orthogonal factor of a matrix as in http://www.arrayfire.com/docs/group__factor__mat.htm?

**Comment by Kerkil** [comment]
@pavanky I was pretty excited briefly. ;)

**Comment by pavanky** [comment]
@Kerkil I am sorry! I accidentally put the wrong issue number in a commit. Merging it in accidentally closed this issue.

**Comment by pavanky** [comment]
@Kerkil The functions are in devel now. The OpenCL versions dont work with intel GPUs on OSX right now. Other than that they are pretty close to stable.

**Comment by RoyiAvital** [comment]
@pavanky, Could you recap the current state?
If I'm on Windows or OSX and there's no GPU, what would be used?
If I have GPU (OpenCL) what would be used?

Does any of those require downloading another pack or is it built in the installer on your site?

Thank You.

**Comment by pavanky** [comment]
@RoyiAvital 

We still do not support automatic switching of backends, you will need to recompile the code with the necessary backend. If you do not have a GPU on a machine you can use the CPU backend. If you have a NVIDIA GPU you can use the CUDA version, if not you can use the OpenCL version.

The installer with linear algebra is not available right now. We are in the process of making the installer available this week. Please stay tuned for the 3.0 announcement that will come out soon.

**Comment by RoyiAvital** [comment]
@pavanky,
I didn't get.

Let's say I'm a developer, I'm writing a code using ArrayFire.
I compile it and send it to another machine.

Let's say I have OpenCL GPU and he doesn't, will it work?
What CPU back end will be used?

**Comment by pavanky** [comment]
You can write code *once* using ArrayFire. You can then compile three versions.

- application_cpu.exe
- application_cuda.exe
- application_opencl.exe

To *compile* these files you do not need to have any special hardware on the development machine. You just need ArrayFire installed on the machine.

Based on the hardware available, the user can run one of these three files and get the same behavior. For example:

- User A has NVIDIA GPUs, he can run  `application_cuda.exe`.
- User B has Intel integrated GPUs, he can run `application_opencl.exe`
- User C does not have discrete or integrated GPUs, he can run `application_cpu.exe`

This topic is going out of scope of this ticket. If you have more questions, please open a new issue so we can discuss it there.
