### ISSUE TITLE
gfor incorrect result and bug with inplace operations in gfor

### ISSUE THREAD

**Issue by Giels** [arrayfire/arrayfire#700]
http://archive.arrayfire.com/arrayfire/c/page_gfor.htm
specifies that the following invocations of gfor should be equivalent:

```
gfor (array i, 5)
gfor (array i, 0, 4)
gfor (array i, 0, 1, 4)
```
(Although I realize the documentation for gfor is out of date, given that it uses array rather than seq).

But that is not the case in 3.0_beta:

```     
    auto mat1 = af::randu(5, 1, f32);
	auto mat2 = af::randu(5, 1, f32);

	gfor(af::seq i, 0, 1, 4){
		af_print(mat1);
		mat2(i) = mat1(i) + 3.0;
		af_print(mat2);
	}
```

```
mat1 [5 1 1 1]
    0.4107 
    0.8224 
    0.9518 
    0.1794 
    0.4198 

mat2 [5 1 1 1]
    3.4107 
    0.7104 
    0.5201 
    0.3569 
    0.1437 
```
(Assignments for any but the first element were skipped - changing `last` or `inc` doesn't affect this result).

Whereas

```	
    auto mat1 = af::randu(5, 1, f32);
	auto mat2 = af::randu(5, 1, f32);

	gfor(af::seq i, 5){
		af_print(mat1);
		mat2(i) = mat1(i) + 3.0;
		af_print(mat2);
	}
```

```
mat1 [5 1 1 1]
    0.4107 
    0.8224 
    0.9518 
    0.1794 
    0.4198 

mat2 [5 1 1 1]
    3.4107 
    3.8224 
    3.9518 
    3.1794 
    3.4198 
```

As for inplace operators, replacing `mat2(i) = mat1(i) + 3.0;` by `mat1(i) += 3.0;` yields 

```
In function /path/arrayfire-3.0_beta/src/api/c/assign.cpp(36):
Invalid argument at index 0
Expected: (outDs.ndims()>=iDims.ndims())
terminate called after throwing an instance of 'af::exception'
Aborted
```

As I understand, this should be working.

(Please tell me if I should split these issues).

**Comment by Giels** [comment]
Looks like the first problem is actually an issue with the documentation, since the arguments are passed to seq via __VA_ARGS__, and seq uses begin, end, step order instead of begin, step, end as is the case in the documentation.

**Comment by pavanky** [comment]
@Giels This is definitely a bug. This may be related to #697 Thanks for reporting this.

**Comment by pavanky** [comment]
Yes, this is a problem in documentation. We need to fix it.

**Comment by pavanky** [comment]
This is fixed in the current documentation in devel. It will be fixed on the website is updated.

**Comment by umar456** [comment]
Documentation not updated...yet

**Comment by pavanky** [comment]
Updated docs. Will be uploading the installers soon.
