### ISSUE TITLE
Inconsistent camel case

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#713]
- [x] alltrue --> allTrue
- [x] anytrue --> anyTrue
- [x] setunion --> setUnion
- [x] setunique --> setUnique
- [x] setintersect --> setIntersect
- [x] fftconvolve --> fftConvolve
- [ ] medfilt --> medianFilter (medFilt) ?
- [ ] corrcoef --> corrCoef ? (this is similar to matmul, should it even change?)
- [x] meanshift --> meanShift
- [x] colorspace --> colorSpace

**Comment by pavanky** [comment]
@umar456 We need to figure this out today.

**Comment by pavanky** [comment]
@pentschev add stuff as you find here.

**Comment by pavanky** [comment]
While I am here, shouldn't these also change:

- erode3d --> erode3
- dilate3d --> dilate3 ?

**Comment by pentschev** [comment]
Also those:

* deviceprop --> deviceProp
* colorspace --> colorSpace
* histequal --> histEqual

**Comment by pavanky** [comment]
- rgb2gray --> rgbToGray
- rgb2hsv --> rgbToHsv
- hsv2rgb --> hsvToRgb
- gray2rgb --> grayToRgb

**Comment by pavanky** [comment]
I think deviceInfo feels more natural than deviceProp.
