### ISSUE TITLE
Allow usage of system-installed GTest for the build of the test suite

### ISSUE THREAD

**Issue by ghisvail** [arrayfire/arrayfire#715]
Dear ArrayFire developers,

It would be nice from a packaging perspective to modify the build system slightly so that the test suite can be built using the system-distribution GTest rather than the embedded one. Perhaps with a conditional include of "build_gtest.cmake" based on the results of a ```find_package(GTest)``` ?

EDIT: typo

Cheers,
Ghis

**Comment by shehzan10** [comment]
I double checked this. We did that have before.
@pavan @umar I'll add an option now for USE_SYSTEM_GTEST, which when turned on uses find_package(gtest).

**Comment by shehzan10** [comment]
Fixed by #716

**Comment by pavanky** [comment]
@ghisvail Can you verify if this fixes your issue ?

**Comment by ghisvail** [comment]
All good guys, thanks for addressing this.
