### ISSUE TITLE
Centralized location for path management

### ISSUE THREAD

**Issue by ghisvail** [arrayfire/arrayfire#721]
Dear ArrayFire developers,

This is more of a suggestion than a requirement, but for downstream packaging (again) we often need to relocate part of the installation tree to more suitable locations. As it stands now, that means patching individual CMakeLists.txt files in the ArrayFire source tree, which is not ideal and could be made easier by centralizing path management.

Could you guys provide such centralized place where all of the installation paths are set (for instance in the root CMakeLists.txt or under a separate CMake/AFInstallDirs.cmake module) and, for additional packaging niceness, let the individual paths be overridden when calling CMake ?

This would reduce the amount of patching downstream and should be fairly straightforward to implement. Many CMake projects do implement this sort of thing, or use GNUInstallDirs to let CMake handle it.

Many thanks,
Ghis

**Comment by pavanky** [comment]
@ghisvail Can you send in a PR with the suggested changes ? It would be easier this way than us trying to figure out which parts of the installation need to be configured individually.

**Comment by bkloppenborg** [comment]
@ghisvail , I guess you are suggesting we set up some options like what follows, correct?

```
set(AF_INSTALL_BIN_DIR bin CACHE PATH "Installation directory for executables")
set(AF_INSTALL_LIB_DIR lib CACHE PATH "Installation directory for libraries")
set(AF_INSTALL_INC_DIR include CACHE PATH "Installation directory for headers")
set(AF_INSTALL_DATA_DIR share/${PROJECT_NAME} CACHE PATH "Installation
directory for data files")
```

**Comment by ghisvail** [comment]
@bkloppenborg 
Yes something along these lines would be perfect. I would also add the following:
```
set(AF_INSTALL_DOC_DIR share/doc/${PROJECT_NAME} CACHE PATH "Installation path for documentation")
set(AF_INSTALL_CMAKE_DIR share/cmake/${PROJECT_NAME} CACHE PATH "Installation path for CMake modules")
```

@pavanky 
I am happy to submit a PR for this, unless @bkloppenborg is already on it.

**Comment by bkloppenborg** [comment]
@ghisvail , please feel free to submit a PR. The CMake configure scripts for ArrayFire use a relative path to keep the code portable, so we might need to modify the scripts slightly.

**Comment by ghisvail** [comment]
@bkloppenborg 
Yes I figured the RPATH stuff on OSX may become broken as a result. I don't have an OSX dev machine to test that on though.

You guys might also want to take this opportunity to enable RPATH support (optionally please) on Linux.

**Comment by bkloppenborg** [comment]
@umar456 , could you verify these modifications did not break the RPATH on your Mac?
