### ISSUE TITLE
Memory leak in OpenCL backend

### ISSUE THREAD

**Issue by unbornchikken** [arrayfire/arrayfire#735]
Continued from this: https://github.com/arrayfire/arrayfire/pull/734

The actual issue is there: https://github.com/unbornchikken/arrayfire/blob/devel/src/backend/opencl/Array.cpp#L283

Look, if there is an OpenCL buffer, and there is a CLBuffer reference to this in the heap, and this CLBuffer never gets deleted, then the reference wil hold forever, and OpenCL buffer won't get released, because **its ref. count will never reach zero**. So there is a memory leak in the heap of size_t and on the GPU of buffer size!

When was the last time you see a C++ code that behaved correctly when there was a `new` without a corresponding `delete` anywhere? :)

My PR was wrong because I though that it is assumed that (cl_mem)(data) will outlive the asynchronous copy operation for sure. Despite it was wrong that leak is still there.

I mentioned if that I thought at first is not the case, you have to create and event that fires when the copy gets finished, and you gotta delete that CLBuffer in its callback, eg:

```C++
void
writeDeviceDataArray(Array<T> &arr, const void * const data, const size_t bytes)
{
    if (!arr.isOwner()) {
        arr = createEmptyArray<T>(arr.dims());
    }

    cl::Buffer& buf = *arr.get();

    const cl::Buffer* data_buf = new cl::Buffer((cl_mem)(data));

    cl::Event e;
    
    getQueue().enqueueCopyBuffer(data_buf, buf,
                                 0, (size_t)arr.getOffset(),
                                 bytes,
                                 nullptr,
                                 e);
                                 
    e.setCallback(
    CL_COMPLETE,
    [](cl_event event, cl_int status, void* userData)
    {
        delete (cl::Buffer*)userData;
    },
    data_buf);


    return;
}
```

**Comment by unbornchikken** [comment]
Just for the record, if I remember correctly, command queue holds references to passed memory arguments. If it's true then my PR was correct as was, because despite data_buf gets released when stack collapses, the queue will hold an other reference to data. I don't remeber if queu behaves like this or not though.

**Comment by pavanky** [comment]
Keep in mind that cl::Buffers do not increment the reference count on creation (i.e. they do not call clRetainMemObject). However they do decrement the reference count in the destructor (i.e. they call clReleaseMemObject).

This results in a reference count being decreased by 1 when a cl::Buffer takes in a cl_mem and then goes out of scope (instead of just keeping the original reference count). This is the reason we had that ugly hack in the original code base. 

I just reopened your PR after a colleague pointed out how it could be fixed.

**Comment by unbornchikken** [comment]
Yeah I missed that Buffer(cl_mem) is just calls Wrapper(cl_mem), so this actually doesn't get leaked on the GPU side, that's why you haven't noticed it with a GPU profiler. PR updated. Thanks.

**Comment by pavanky** [comment]
No worried. I lost a bet once to @umar456 making similar assumptions to what you did.
