### ISSUE TITLE
array_proxy indexing

### ISSUE THREAD

**Issue by munnybearz** [arrayfire/arrayfire#744]
Hi guys,

With the new array_proxy class, I can't seem to be able to do things like this:

```
    array A = constant(0, 5);
    af_print(A.rows(0, 4).rows(0,3));
```

The first call to rows() gives an array_proxy, and the second call to rows() gives me a compiler error saying there is no rows() method in the array_proxy class:

```
main.cpp:52:27: error: no member named 'rows' in 'af::array::array_proxy'
```

I'm currently working around this by doing:

```
    array A = constant(0, 5);
    array B = A.rows(0, 4);
    af_print(B.rows(0,3));
```

Please could you advise if the functionality has been dropped or is an oversight?

**Comment by umar456** [comment]
Looks like we missed a couple of member functions. Should be fixed soon.
