### ISSUE TITLE
Make all submodules external projects

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#750]
This would make it easier for us to package all the necessary files to build arrayfire into a single archive. It would also reduce the pain of us having to update the submodule tags frequently. We could point assets and data dirs to always download master.

Things to change

- [ ] arrayfre/data
- [ ] arrayfire/assets
- [ ] gtest

**Comment by pavanky** [comment]
@umar456 @shehzan10 thoguths ?

**Comment by umar456** [comment]
If you want to make gtest a external project then fine. but we need to keep data and assets as submodules because if we update the data in the future it will break older test commits.

**Comment by pavanky** [comment]
I was just suggesting we can link to master. We can link external builds to a particular commit as well (like we are doing for clBLAS, clFFT and Boost.Compute).

**Comment by shehzan10** [comment]
So solve the problem that umar states, we can use commit IDs. They'll work same was as the submodule commits work.

See build_boost_compute.cmake

**Comment by pavanky** [comment]
I emailed github support asking if there was a way to automatically archive submodules in their "releases". This is the response I received:

> The archives automatically included with a release don't include submodules. If you want to include submodules, you can build a source tarball that includes the submodules manually upload it to the release as a release asset.

So I guess that is a reasonable alternative to what I am suggesting here. If you guys feel like it's too much work to change the submodules, we can just do this.

**Comment by pavanky** [comment]
Making them external projects does not solve the issue the original issue I was thinking about. closing as won't fix.
