### ISSUE TITLE
FindCBLAS.cmake should use pkg_config to find CBLAS

### ISSUE THREAD

**Issue by marbre** [arrayfire/arrayfire#761]
I am currently preparing an ebuild to package arrayfire-3.0.0 for the [Gentoo science overlay](https://github.com/gentoo-science/sci). Ebuilds to build 3.0_beta and from git are already available.
I noticed that a patch I wrote for the previous ebuilds is still necessary to find CBLAS. On Gentoo CBLAS can be found via `pkg_config`, as done with applying this [patch](https://github.com/marbre/sci/blob/arrayfire/sci-libs/arrayfire/files/arrayfire-9999-FindCBLAS.patch). Providing this patch is absolutely okay for the release and our ebuild, but it would be nice to see the usage of `pkg_config` in one of the next arrayfire releases. IMHO this is already implemented to find LAPACKE.
Unfortunately, I won't find enough time within the next weeks to modify the `FindCBLAS.txt` by myself and send a pull request, therefore this report.

**Comment by pavanky** [comment]
This is fixed in hotfixes-3.1.1
