### ISSUE TITLE
Inconsistent naming convention of functions

### ISSUE THREAD

**Issue by unbornchikken** [arrayfire/arrayfire#765]
I can see that cameCase and lowercase naming of functions is mixed. It seems newer ones are cameCased and old ones are lowercased. Is there a plan to move toward cameCase naming convention for all functions?

**Comment by 9prady9** [comment]
@unbornchikken Yes, we are following cameCased naming convention for 3.0 version (Version 2.1 used to have lowercased naming convention). To avoid breaking old code straight away, we added lowercased functions as well for this release, but they are marked as deprecated and any use of those functions should throw a warning during user application code compilation. If you do find anything that is not following convention, please report it here and we shall make sure to correct it.

Thank you

**Comment by pavanky** [comment]
We deprecated lower case only functions. The only exceptions I can remember are moddims and matmul 

Are there other functions you found that are not camel case?

**Comment by unbornchikken** [comment]
I think you've already figured out that I'm the guy who's making the [Node.js binding of Array Fire](https://github.com/unbornchikken/fire-js). So I think I've been seeing more Array Fire functions beside each other recently than you have. :D

Here is what I've found so far:

```C++
dim4.ndims -> dim4.nDims
isero -> isZero
array.numdims -> array.numDims
array.isanyting -> array.isAnything
randu -> randU
randn -> randN
expm1 -> expM1
lgamma -> lGamma
tgamma -> tGamma
log1p -> log1P
acosh -> aCosH // sin, tan, etc
moddims -> modDims
stdev -> stDev
```

Actually I'm creating corrected aliases in Fire.js, eg: https://github.com/unbornchikken/fire-js/blob/master/src/mathfunctions.cpp#L110

**Comment by pavanky** [comment]
I am sorry but almost all of these are standard names used in the C / C++ Standard libraries. We are only trying to camel case our *function* names (not methods) if they  something we came up with. If this is the entire list, I think we are going to close this as wont fix.

**Comment by unbornchikken** [comment]
I understand. It's your decision but I think it could be better to stick with the convention that standard lib uses altogether then instead of mixing things up, because it's kinda confusing. Anyway I wish that issue be the toughest one that I can come up with while I'm on the porting work. :) Now I gotta go to figure out how to do `gfor` in Node.js. Thanks for your time!

**Comment by pavanky** [comment]
I highly suggest you not use `gfor` as is when porting to other languages. Under the hood all it does is the following. This is a nicety that we enabled back in the day, but all the functionality that uses gfor can be accomplished without using it. 

We have an alternative function called `batchFunc` which uses function pointers that provides essentially the same functionality.

**Comment by unbornchikken** [comment]
It's new for me. I cannot see anything about it in the documentation. Could you point me to the right direction? Should I open a new issue for this question?

**Comment by pavanky** [comment]
A new issue would be better. We have purposely left batchFunc out of the documentation for now.
