### ISSUE TITLE
Support Visual Studio 2015

### ISSUE THREAD

**Issue by shehzan10** [arrayfire/arrayfire#766]
The following tasks need to be completed for Visual Studio 2015 Support:

- [x] Merge PR #760
- [x] Fix scope resolution in tests
- [x] Send in a PRs to clBLAS, clFFT, Forge
- [x] Build FreeImage Static with VS 2015. Also send in PR to upstream.
- [x] Await CUDA support for VS 2015

**Comment by pavanky** [comment]
@shehzan10 Does the ArrayFire binary work with VS 2015 ? Or is this more of an internal change ?

**Comment by shehzan10** [comment]
When using the binaries, the header defines.h needs to change, but for now user's can fix it at their end. The binaries themselves do not need to change.

The tasks listed above are for building ArrayFire from source on Visual Studio 2015.

**Comment by pavanky** [comment]
Can you create a subtask for the hotfix then ? We can send it out in 3.0.1

**Comment by pavanky** [comment]
More importantly, does the snprintf stuff need to be in our header file ?

**Comment by shehzan10** [comment]
Visual Studio 2015 support for CUDA has been added in NVIDIA Nsight™ Visual Studio Edition 5.0 Release Candidate 1

**Comment by shehzan10** [comment]
Closed by #1064
