### ISSUE TITLE
Question: calculating the inverse of a matrix

### ISSUE THREAD

**Issue by unbornchikken** [arrayfire/arrayfire#771]
Is there a function or is there a plan to include a function for matrix inverse calculation? I'm trying to implement Levenberg–Marquardt for a NN. I can do LU decomposition of course, but it might be more performant when there is a direct support for it.

**Comment by pavanky** [comment]
There is a function called [inverse](http://www.arrayfire.com/docs/group__lapack__ops__func__inv.htm).

**Comment by unbornchikken** [comment]
How did I miss this is beyond me. Extra mega uber cool! Thanks!

**Comment by pavanky** [comment]
There is also [solve](http://www.arrayfire.com/docs/group__lapack__solve__func__gen.htm) which might be appropriate for Levenberg-Marquardt.

**Comment by unbornchikken** [comment]
Yes, it is. Awesome, thanks.
