### ISSUE TITLE
Fix graphics bugs on OSX and AMD GPUs on linux

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#772]
This might be a problem in upstream, bug in forge. Creating this issue as a place holder for upstream.

Issue was noticed on the following platforms:
- [x] OS X
- [ ] Integrated Graphics Card on AMD APUs.

Will mark them as they are fixed.

**Comment by 9prady9** [comment]
Issue was noticed on the following platforms:
- [ ] OS X
- [ ] Integrated Graphics Card on AMD APUs.
Will mark them as they are fixed.

**Comment by 9prady9** [comment]
OS X issues are fixed and currently available in devel.

**Comment by 9prady9** [comment]
@pavanky Are you still seeing this problem on AMD APUs ?

**Comment by pavanky** [comment]
@9prady9 Last I checked, it is still an issue.

**Comment by 9prady9** [comment]
@pavanky @mlloreda @umar456 Can we have this tested on AMD APU for Linux ? It is definitely not an issue on Windows for AMD APU the last time I checked.

**Comment by mlloreda** [comment]
Sure thing, @9prady9. It'll be nice to finally have an update on this issue.

**Comment by 9prady9** [comment]
Closing this place holder bug. Please track this issue in the related upstream project https://github.com/arrayfire/forge/issues/94
