### ISSUE TITLE
Docs are not accessible from the left side menu

### ISSUE THREAD

**Issue by unbornchikken** [arrayfire/arrayfire#781]
If I open up the docs at function list (http://www.arrayfire.com/docs/group__arrayfire__func.htm), and hit sin, I get:

http://www.arrayfire.com/docs/group__arith__func__sin.htm

If I open up the categorized list (http://www.arrayfire.com/docs/group__trig__mat.htm), and hit sin from there, I get:

http://www.arrayfire.com/docs/group__arith__func__sin.htm

So far so good. But hitting sin from http://www.arrayfire.com/docs/group__trig__mat.htm page's tree menu on the left side of screen, I get:

http://arrayfire.com/docs/group__trig__func__sin.htm

404

**Comment by pavanky** [comment]
The second and third links are exactly the same.. I also tried going doing this manually in two different browsers. I am not able to reproduce this error.

**Comment by unbornchikken** [comment]
Clearing the browser cache solved the problem for me, sorry. Atleast you known that cachning is working properly.
