### ISSUE TITLE
Blue screen of death under Intel HD Graphics in OpenCL

### ISSUE THREAD

**Issue by CsatiZoltan** [arrayfire/arrayfire#782]
Running the built-in example pi.cpp with the OpenCL configuration caused a blue screen of death when invoked with the command-line argument responsible for the device. Processor: Intel Celeron 1000M.
P.s.: In version 3.0 beta this bug hasn't occurred.

**Comment by 9prady9** [comment]
@CsatiZoltan How did you acquire ArrayFire ?

* If you used installer, can you try installing ArrayFire using the non-graphics installer.
* If you built it from source, please try building ArrayFire without graphics and run the pi example again.

This should let us if this problem is related to ArrayFire-graphics or OpenCL as a whole on your machine.

**Comment by pavanky** [comment]
@9prady9 We do not have the non graphics installer on our website. 

@shehzan10 Can you link to a non graphics build from our ci ?

**Comment by CsatiZoltan** [comment]
@9prady9 I downloaded it from the Arrayfire website http://arrayfire.com/download/ version Windows, v3.0 (64-bit).

**Comment by shehzan10** [comment]
Download: [Windows Installer without Graphics](http://ci.arrayfire.org/view/Installer/job/arrayfire-windows-installer/lastSuccessfulBuild/artifact/ArrayFire-nogl-v3.0.0-c047384.exe)

**Comment by CsatiZoltan** [comment]
Thanks. Was the problem with my machine?

**Comment by pavanky** [comment]
@CsatiZoltan We are not sure. We do not have a similar machine to test on our end. Can you check if the installer without graphics is running correctly ?

**Comment by CsatiZoltan** [comment]
Can I install the no-graphics version while the graphics version is still installed, or I have to uninstall that before?

**Comment by pavanky** [comment]
@CsatiZoltan It is best if you uninstall the previous version.

**Comment by 9prady9** [comment]
@CsatiZoltan Did you get a chance to check this again ?

**Comment by CsatiZoltan** [comment]
Fortunately blue screen doesn't occur any more, "just" the program termination (I use version 3.0.1., build 17db1c9 with the same configuration as mentioned at the beginning of this post). By the way, if I run the OpenCL backend with command-line argument 1 (i.e. on the processor), I get the following results:
device: 0.87702 seconds
   host: 1.44039 seconds
How should I interpret them? The GPU of the processor is faster than the CPU itself?

**Comment by 9prady9** [comment]
Yes, Device is taking less time than the host for computing Pi using Monte-Carlo method.

I didn't quite understand what you meant by program termination ? is it natural termination or otherwise ?

**Comment by CsatiZoltan** [comment]
I use a Hungarian Windows 7, so I don't know the exact name for the crash. However, it should somehow read as "abnormal program termination" (this kind occurs for example when you don't free allocated memory in Visual Studio).

**Comment by 9prady9** [comment]
Does it throw any message with the words "pure virtual function" or something of sorts ?

**Comment by CsatiZoltan** [comment]
No, it doesn't, just crashes.

**Comment by 9prady9** [comment]
Oh, i forgot to mention something earlier. Can you run the program from command line after doing
`SET AF_PRINT_ERRORS = 1` . This should print additional information when the program crashes.

**Comment by CsatiZoltan** [comment]
I will definitely try it tomorrow on that laptop and write you what happens. By the way, is that normal that on a computer where I have a core i5 2500K processor with built-in GPU (HD graphics 3000) and a discrete GPU (Geforce GTX 560), Arrayfire only offers the CPU and the Geforce GPU, not the integrated GPU?

**Comment by 9prady9** [comment]
I think you need to install Intel OpenCL run time library for the integrated GPU to actually show up as a valid OpenCL device.

**Comment by CsatiZoltan** [comment]
I can't install it, because it causes error similar to this message: the installer does not fulfil the minimum requirements. Since I have Windows 7 64 bit, I chose: https://downloadcenter.intel.com/download/24964/Intel-Iris-Iris-Pro-and-HD-Graphics-Driver-for-Windows-7-8-8-1-64-bit . Nevertheless, it is not a very important feature for me, hence I have a discrete GPU. Thanks for your instructions. Tomorrow I will post my detailed Arrayfire error.

**Comment by CsatiZoltan** [comment]
I retested the OpenCL issue and posted three images about it. First, I run it from the command line and then the solution file was debugged in Visual Studio. The cursor shows where the problem occurred.

![pi](https://cloud.githubusercontent.com/assets/12742890/8225723/5596ee72-1598-11e5-8ef1-78c55be319a7.PNG)
![pi_debugger](https://cloud.githubusercontent.com/assets/12742890/8225725/5597cf4a-1598-11e5-9b43-42dd5d5ee197.PNG)
![vs2013](https://cloud.githubusercontent.com/assets/12742890/8225724/5597b29e-1598-11e5-93a3-063b16a18542.PNG)

**Comment by 9prady9** [comment]
@CsatiZoltan Thank you for sharing the info. I think this needs further investigation to pint point the root cause of the issue. AS we have already said, we do not have Intel Celeron 1000M in house but i saw that you also mentioned another processor ' i5 2500K'. Is this issue happening on both of the machines with these processors ? 

In any case, i have to check if the i5 you mentioned is available in our stock.

**Comment by CsatiZoltan** [comment]
Unfortunately I cannot select the GPU of the i5 processor, because OpenCL does not recognise it and - as I have written above - I cannot install the OpenCL runtime library.

**Comment by 9prady9** [comment]
@CsatiZoltan Unfortunately, we don't have the I5 you mentioned in our stock as well. I am afraid, you have to debug this problem in Debug mode which won't be of much help unless you are using ArrayFire Debug Binary. I don't think you can find them on our website ( @pavanky correct me if i am wrong) but you can build them yourself. Instructions for that are available [here](https://github.com/arrayfire/arrayfire/wiki/Build-Instructions-for-Windows) and it is quite simple once all the required upstream libraries are installed.

**Comment by CsatiZoltan** [comment]
I managed to install the OpenCL driver and now ArrayFire recognises the integrated GPU. So it was the problem, thanks. The topic can be closed.

**Comment by 9prady9** [comment]
I am glad that you got it working. Happy Coding!
