### ISSUE TITLE
Graphics does not work in none of the configurations

### ISSUE THREAD

**Issue by CsatiZoltan** [arrayfire/arrayfire#783]
I am using an Intel Celeron 1000M processor and no discrete video card. I cannot run the examples that require graphics under none of the configurations (CPU, OpenCL, CUDA). The fact that CUDA doesn't work is natural, since the is no CUDA-capable GPU in my laptop.

**Comment by 9prady9** [comment]
@CsatiZoltan  Can you please run the graphics example from command line after you set the variable `AF_PRINT_ERRORS` to `1`. For windows, it would be `set AF_PRINT_ERRORS = 1` and then run the graphics example. It should print out some error information, can you share that over here. Does any window show up ? or the program crashes right away ?

**Comment by CsatiZoltan** [comment]
Running the example conway_CPU.exe from ../examples/graphics forder under 64bit Windows 7 shows a blank window with title "Conway's Game of Life using ArrayFire" and then crashes. According to the command prompt: 
`c:\Program Files\ArrayFire\v3.0.0\examples\graphics>set AF_PRINT_ERRORS = 1

c:\Program Files\ArrayFire\v3.0.0\examples\graphics>conway_cpu.exe
ArrayFire v3.0.0 (CPU, 64-bit Windows, build 86426db)
This example demonstrates the Conway's Game of Life using ArrayFire
There are 4 simple rules of Conways's Game of Life
1. Any live cell with fewer than two live neighbours dies, as if caused by under
-population.
2. Any live cell with two or three live neighbours lives on to the next generati
on.
3. Any live cell with more than three live neighbours dies, as if by overcrowdin
g.
4. Any dead cell with exactly three live neighbours becomes a live cell, as if b
y reproduction.
Each white block in the visualization represents 1 alive cell, black space repre
sents dead cells
InfoLog:
No errors.

ArrayFire Exception(998): Internal error
In C:\workspace\af_installer\arrayfire\src\api\cpp\graphics.cpp:19`

**Comment by CsatiZoltan** [comment]
I also tried to run those graphics-based examples on another computer (Intel Core i5 2500K, Nvidia GeForce GTX 560) with CUDA installed but experienced the same issue. Strange, because everything other than graphics works like a charm.

**Comment by 9prady9** [comment]
@CsatiZoltan We have made some major changes to how OpenGL rendering happens in the upstream library ([forge](https://github.com/arrayfire/forge)) used by ArrayFire for graphics. We are going to make a hot fix release (3.0.1) for ArrayFire on Monday. Also, you need OpenGL 3.3 capable hardware for ArrayFire graphics to work.

We will upload the 3.0.1 installers on Monday, please give it another try with those.

**Comment by CsatiZoltan** [comment]
I have already downloaded it from ci and installed. The good news is that some graphics examples run correctly (like `fractal`, ). However, when an image is loaded (like `fast`) or in some machine_learning examples (where there is no graphics at all) I get a run-time error. The interesting is that in case of `fast`, the error "FreeImage Error Handler: FreeImage_Load: failed to open file ../../assets/examples/images/lena.ppm
ArrayFire Exception(103): Runtime error" occurs only when running the generated .exe, while it runs perfectly when I run it from Visual Studio. What can be the problem?

**Comment by shehzan10** [comment]
If you have copied the examples into a different directory, then you will need to change the ASSETS_DIR macro. Go into Project Properties -> C/C++ -> Preprocressor -> Preprocressor Definitions. Change ASSETS_DIR to point to the location of AF_PATH/assets.

Note: We can't use $(AF_PATH)/assets because AF_PATH contains the Path using \, which when read by C++ uses it as escape characters which messes up the path. So you will need to do something like ASSETS_DIR="C/Program Files/ArrayFire/v3/assets"

PS. So I just figured out a way to have this use the AF_PATH variable. I will update the installer and build it. You should be able to download it sometime later today.

**Comment by shehzan10** [comment]
http://arrayfire.com/installer_archive/3.0.1/ArrayFire-v3.0.1.exe this should make the examples portable without modification

**Comment by 9prady9** [comment]
@CsatiZoltan Is this still a persistent issue ?

**Comment by CsatiZoltan** [comment]
As soon as I get home, I try it out!

**Comment by CsatiZoltan** [comment]
With the new installer, the only error it puts while building the `kmeans` example is:
`ArrayFire Exception(203): Invalid input size
In C:\workspace\af_inst_source\src\api\cpp\array.cpp:530`.
I also modified the preprocessor to point to the installation directory\folder_where_kmeans_is, but the result is the same. By the way, I installed Arrayfire to a different drive, not C:\, where the OS is.

**Comment by CsatiZoltan** [comment]
I reinstalled into the default installation path, but the result is the same.

**Comment by 9prady9** [comment]
Glad the issue is resolved.
