### ISSUE TITLE
OPENCL matrix initialization problem

### ISSUE THREAD

**Issue by KoldoRamirez** [arrayfire/arrayfire#784]
When initializing bidimensional array with host array with afOPEN_CL only first data is copied.
If the array is unidimensional, it is initialized properly;

Tested code
```
void main() {
	info(); 
	int h_buffer[] = {0, 1, 2, 3, 4, 5};
	array A(2, 3, h_buffer);  
	af_print(A);
}
```

Output with afCPU
```
ArrayFire v3.0.0 (CPU, 64-bit Windows, build 86426db)
A [2 3 1 1]
         0          2          4
         1          3          5
```

Output with afOPEN_CL
```
Device[1] has no support for OpenGL Interoperation
ArrayFire v3.0.0 (OpenCL, 64-bit Windows, build 86426db)
[0] INTEL   : Intel(R) HD Graphics 4000
-1- INTEL   : Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
-2- Experimental OpenCL 2.0 CPU Only Platform: Intel(R) Core(TM) i5-3320M CPU @
2.60GHz
A [2 3 1 1]
         0 -1163005939 -1163005939
-1163005939 -1163005939 -1163005939
```

Using moddims the result is the same:
```
void main() {
	info(); 
	int h_buffer[] = {0, 1, 2, 3, 4, 5};
	array A(6, h_buffer);  
	A = moddims(A, 2, 3);
	af_print(A);
}
```

**Comment by shehzan10** [comment]
I tested this and it seems to work fine on my devices, however, I do not have a HD Graphics device.

Can you test your other devices and see if the problem persists?

**Comment by KoldoRamirez** [comment]
It only fails with device 0 (Intel(R) HD Graphics 4000). The devices 1 and 2, based on CPU, work perfectly.

**Comment by shehzan10** [comment]
I was able to get my hands on the HD graphics (4600) machine and it works fine for me.

Can you run the helloworld example? The D array in the helloworld example is initialized using the host array method. Let's see if you face the same problem there too.

I tried add/changing the following:
* using floats instead of ints
* explicitly passing and not passing afHost

In all cases it worked fine. So I am unable to pin point the issue.

**Comment by pavanky** [comment]
@KoldoRamirez Can you mention the driver version you are using ?

**Comment by KoldoRamirez** [comment]
This is the output of helloworld:
```
Device[1] has no support for OpenGL Interoperation
ArrayFire v3.0.0 (OpenCL, 64-bit Windows, build 86426db)
[0] INTEL   : Intel(R) HD Graphics 4000
-1- INTEL   : Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
-2- Experimental OpenCL 2.0 CPU Only Platform: Intel(R) Core(TM) i5-3320M CPU @
2.60GHz

create a 5-by-3 matrix of random floats on the GPU
A [5 3 1 1]
    0.4107    -0.0013    -0.0013
   -0.0013    -0.0013    -0.0013
   -0.0013    -0.0013    -0.0013
   -0.0013    -0.0013    -0.0013
   -0.0013    -0.0013    -0.0013

element-wise arithmetic
B [5 3 1 1]
    0.4993    -0.0013    -0.0013
   -0.0013    -0.0013    -0.0013
   -0.0013    -0.0013    -0.0013
   -0.0013    -0.0013    -0.0013
   -0.0013    -0.0013    -0.0013

Fourier transform the result
C [5 3 1 1]
         (0.4940,-0.0053)          (-0.0013,-0.0013)          (-0.0013,-0.0013)

         (-0.0013,-0.0013)          (-0.0013,-0.0013)          (-0.0013,-0.0013)

         (-0.0013,-0.0013)          (-0.0013,-0.0013)          (-0.0013,-0.0013)

         (-0.0013,-0.0013)          (-0.0013,-0.0013)          (-0.0013,-0.0013)

         (-0.0013,-0.0013)          (-0.0013,-0.0013)          (-0.0013,-0.0013)


grab last row
c [1 3 1 1]
         (0.0000,0.0000)          (-0.0013,-0.0013)          (-0.0013,-0.0013)
zero out every other column
ArrayFire Exception(202): Sequence is invalid
In C:\workspace\af_installer\arrayfire\src\api\cpp\seq.cpp:77
```

**Comment by KoldoRamirez** [comment]
This is curious. Running this code:
```
    info(); 
    int h_buffer[] = {0, 1, 2, 3, 4, 5};
    array A(6, h_buffer);  
    af_print(A);
    A = moddims(A, 2, 3);
    af_print(A);
```
This is got:
```
Device[1] has no support for OpenGL Interoperation
ArrayFire v3.0.0 (OpenCL, 64-bit Windows, build 86426db)
[0] INTEL   : Intel(R) HD Graphics 4000
-1- INTEL   : Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
-2- Experimental OpenCL 2.0 CPU Only Platform: Intel(R) Core(TM) i5-3320M CPU @
2.60GHz
A [6 1 1 1]
         0
         1
         2
         3
         4
         5

A [2 3 1 1]
         0 -1163005939 -1163005939
-1163005939 -1163005939 -1163005939
```
Unidimensional array is well initialized, but when converting it to bidimensional, it fails.

**Comment by KoldoRamirez** [comment]
Hello Pavanky. These are the device properties:
```
Intel(R) HD Graphics 4000
CL_DEVICE_VENDOR: Intel(R) Corporation
CL_DEVICE_PROFILE: FULL_PROFILE
CL_DEVICE_VERSION: OpenCL 1.1
CL_DRIVER_VERSION: 9.17.10.3517
CL_DEVICE_OPENCL_C_VERSION: OpenCL C 1.1
CL_DEVICE_COMPILER_AVAILABLE: 1
CL_DEVICE_MAX_COMPUTE_UNITS: 16
CL_DEVICE_MAX_CLOCK_FREQUENCY: 350
CL_DEVICE_MAX_WORK_GROUP_SIZE: 512
CL_DEVICE_ADDRESS_BITS: 64
CL_DEVICE_MEM_BASE_ADDR_ALIGN: 1024
CL_DEVICE_MAX_MEM_ALLOC_SIZE: 425721856
CL_DEVICE_GLOBAL_MEM_SIZE: 1702887424
CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE: 65536
CL_DEVICE_GLOBAL_MEM_CACHE_SIZE: 2097152
CL_DEVICE_GLOBAL_MEM_CACHELINE_SIZE: 64
CL_DEVICE_LOCAL_MEM_SIZE: 65536
CL_DEVICE_PROFILING_TIMER_RESOLUTION: 80
CL_DEVICE_IMAGE_SUPPORT: 1
CL_DEVICE_ERROR_CORRECTION_SUPPORT: 0
CL_DEVICE_HOST_UNIFIED_MEMORY: 1
CL_DEVICE_PREFERRED_VECTOR_WIDTH_INT: 1
CL_DEVICE_PREFERRED_VECTOR_WIDTH_LONG: 1
CL_DEVICE_PREFERRED_VECTOR_WIDTH_FLOAT: 1
CL_DEVICE_PREFERRED_VECTOR_WIDTH_DOUBLE: 0
CL_DEVICE_NATIVE_VECTOR_WIDTH_INT: 1
CL_DEVICE_NATIVE_VECTOR_WIDTH_LONG: 1
CL_DEVICE_NATIVE_VECTOR_WIDTH_FLOAT: 1
CL_DEVICE_NATIVE_VECTOR_WIDTH_DOUBLE: 0
CL_DEVICE_EXTENSIONS: cl_khr_icd cl_khr_global_int32_base_atomics cl_khr_g
lobal_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_
extended_atomics cl_khr_gl_sharing cl_khr_d3d10_sharing cl_intel_dx9_media_shari
ng cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_event
```

**Comment by pavanky** [comment]
@KoldoRamirez you are using a relly old driver which may be buggy. Can you install the following:
https://downloadcenter.intel.com/download/24964/Intel-Iris-Iris-Pro-and-HD-Graphics-Driver-for-Windows-7-8-8-1-64-bit

**Comment by KoldoRamirez** [comment]
Hello Pavanky. Both Dell (http://www.dell.com/support/home/es/es/esdhs1/product-support/servicetag/7ZT0LV1/drivers?s=BSD) and Microsoft (through the update driver option in System) say that my driver is updated.

I have downloaded the installer in the link you enclosed but when running it says "Error: This computer does not meet the minimum requirements for installing the software.".

Dell reports that my laptop is from Mid 2012 and 9.17.10.3517 driver seems to be from March 2014.

**Comment by shehzan10** [comment]
Looks like this is a known problem from the intel forums. Try the solutions on these links:
https://communities.intel.com/message/216054

http://www.intel.com/support/graphics/sb/CS-022355.htm

**Comment by shehzan10** [comment]
I was able to install the [HD 3000 driver](https://downloadcenter.intel.com/download/24971/Intel-HD-Graphics-Driver-for-Windows-7-8-8-1-64-bit) on my laptop (i7 2720 + HD Graphics 3000). However, I eventually realized that the driver meant for HD Graphics < 4000 only includes OpenCL Runtime for CPU and not for the graphics GPU. So I have not been able to get OpenCL on the HD 3000 on my laptop.

The other thing is that the driver versions installed are different from the installer versions. So 9.xx (mine is 9.17.10.4559, 5/26/2015) aren't old as such in terms of versions, but they are in terms of date the driver was released.

The ["latest"](https://downloadcenter.intel.com/download/24964/Intel-Iris-Iris-Pro-and-HD-Graphics-Driver-for-Windows-7-8-8-1-64-bit) drivers are only for 4x00 (excludes 4000). That's why those drivers error out with the minimum requirements problem.

I think it is highly doubtful that the Intel would actually be releasing an OpenCL runtime driver for the integrated GPUs older than the 4000 series.

**Comment by KoldoRamirez** [comment]
Uuups. It seems that Dell is smarter than us. I have followed the instructions but finally Windows opens up a window telling that the installed driver is the best for the computer and refuses to install the newest just unzipped from Intel...
Sincerely, HD4000 is a low end card for laptops so AF performance with it is not the best, and I understand if you prefer not to support it

**Comment by pavanky** [comment]
Closed the issue as it seems to be a problem with the driver.
