### ISSUE TITLE
Question: synchronization of array constructors

### ISSUE THREAD

**Issue by unbornchikken** [arrayfire/arrayfire#785]
There http://www.arrayfire.com/docs/group__opencl__mat.htm you write:

*"Please note: the af::array constructors are not thread safe. You may create and upload data to cl_mem objects from separate threads, but the thread which instantiated ArrayFire must do the cl_mem to af::array conversion."*

Is it correct? Because if ArrayFire methods are not thread safe, that not inherently means that those are not callable from other threads, because with mutexes access correlation could be estabilished. But if ArrayFire's array initialization uses thread local storage, then of course the abover note is correct, despite mutex based synchronization arrays must be initialized on ArrayFire's main thread.

**Comment by umar456** [comment]
We are not using thread local storage for these variables so they can be accessed by multiple threads.  That statement is correct in that we do not currently have any mechanism to protect memory being accessed from multiple threads. There are a few static variables which need to be protected before we can guarantee the thread safety of the library. There are also some issues with OpenGL/OpenCL which may cause access issues from different threads but we need to perform more tests on that front. Thread safety is a important issue for us and we plan on providing that guarantee in later releases.

**Comment by unbornchikken** [comment]
Thanks. 

The situation that I having at [Fire.js](https://github.com/unbornchikken/fire-js) is that arrays are created on main and on libuv's thread pool's threads too, and functions called with this manner too. If an ArrayFire function has a predictable O(1) time of execution on all supported platform then it's wrapped synchronously, if not, then it wraped asynchronously. The latter means they are invoked on the pool which means the thread of invocation is kinda random. I'm using a [simple mutex](https://github.com/unbornchikken/fire-js/blob/master/src/guard.h) to ensure that there can be no ArrayFire calls in parallel. This is achieved at Fire.js I'm having no synhronization issues so far.

I have plan to provide an integration layer between Fire.js and my [OpenCL binding](https://github.com/unbornchikken/NOOOCL) module. So for doing this that ArrayFire guard should be exposed to JavaScript layer to ensure that NOOCL calls won't interfere with Fire.js ones. So I think with this, ArrayFire and native OpenCL are gonna be live together in happiness even there are many threads involved. 

So I think *"the thread which instantiated ArrayFire must do the cl_mem to af::array conversion."* have to be intead *"the thread which instantiated ArrayFire must be synchronized with the thread that do cl_mem to af::array conversion."*, haven't it?

**Comment by pavanky** [comment]
@umar456 @unbornchikken What is the status of this issue ? Can this be closed ? Are there any actionable items that need to happen ?
