### ISSUE TITLE
af::array::array_proxy::array_proxy(const array_proxy &other) broken

### ISSUE THREAD

**Issue by FilipeMaia** [arrayfire/arrayfire#787]
The [current implementation](https://github.com/arrayfire/arrayfire/blob/devel/src/api/cpp/array.cpp#L562) dereferences ``impl`` before it being allocated.

**Comment by pavanky** [comment]
@FilipeMaia Can you send this PR to our hotfixes-3.0.1 branch? I think this is important fix that should go in there.
