### ISSUE TITLE
Reduce the memory overhead for copy-on-write

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#791]
Assignment operation performs a copy-on-write. However this is not necessary if there are no additional references to the array being assigned. We should check for this and reduce the memory overheads accordingly.

There are two ways to do this:

- Keep the list of child arrays referencing the parent. Make the copies of either the parent or the children based on the memory considerations. This will need to be done for each backend.

- Keep track of the number of references and only perform a copy if there are additional references left. By it's nature, I think this should be done in the C++ API.

**Comment by unbornchikken** [comment]
Does array's copy constructor involves copy-on-write too?

**Comment by pavanky** [comment]
`array::copy()` performs a deep copy. Everything performs a copy on write.

**Comment by unbornchikken** [comment]
I have the follwing situation: in the Node.js wrapper I have to put the wrapped instances to the heap. Since arrays are not moveable, I have to use its copy contructor. The original array goes out of scope immediatwlly, I'm holding the reference only for the one in the heap. Does ot involve deep copying, or not?

**Comment by pavanky** [comment]
You are wrapping the C++ API. We increment the reference count when you are doing the copy constructor, so the internal data is not destroyed when the `array` is destroyed. The underlying data is only destroyed when the reference count hits zero.

The way you are handling it in the project right now should be fine.

**Comment by pavanky** [comment]
This is the relevant code. You can see that we are retaining the internal object (incrementing the ref count)  and holding on to a separate reference of the internal data structure.

```
array::array(const array& in) : arr(0)
    {
        AF_THROW(af_retain_array(&arr, in.get()));
    }
```
