### ISSUE TITLE
Implement af::copy()

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#792]
This is a variation of to array.copy() and array.write(). This is a temporary work around to perform the assignment operator without the copy on write.

```
af::copy(A, B, idx1, idx2, idx3, idx4);
```

**Comment by pavanky** [comment]
@umar456 I am not entirely sure if this function serves any purpose once #791 is resolved. But it would be nice to have a function that works around the copy-on-write.

**Comment by pavanky** [comment]
The code could be as simple as this:

```
void copy(array &out, const array &in, 
               const index &s0 = span, const index &s1 = span,
               const index &s2 = span, const index &s3 = span)
{
    af_array lhs = out.get();
    af_array rhs = in.get();
    af_index_t indices[] = {s0.get(), s1.get(), s2.get(), s3.get()};
    af_err err = af_assign_gen(&lhs, lhs, 4, indices, rhs);
    if (err != AF_SUCCESS) throw af::exception("Failed to copy", __FILE__, __LINE__  - 1, err);
}
```

**Comment by umar456** [comment]
This would be a useful function but we need to think of a better name. Perhaps overwrite, modify, or assign. Copy could have several meanings in C++ which could become confusing.
