### ISSUE TITLE
build failure with Mac OS X 10.8

### ISSUE THREAD

**Issue by glehmann** [arrayfire/arrayfire#794]
Mac OS X 10.8 is using libstdc++ from gcc 4.2.1, that does not have `shared_ptr` defined in `std`.

    /tmp/arrayfire--forge20150609-12531-4ixan6/forge-af3.0/src/font.hpp:65:14: error: no type named 'shared_ptr' in namespace 'std'

it is possible to use libc++, but it becomes quite difficult to link with other libraries.

**Comment by glehmann** [comment]
Note that I'm perfectly fine if you say that libc++ is mandatory — this is either to get a fix, or to make it clear that arrayfire should not be packaged in homebrew for Mac OS X 10.8.

**Comment by pavanky** [comment]
Can you post the issue to https://github.com/arrayfire/forge ?

**Comment by pavanky** [comment]
The easiest fix would be to have a flag that uses boost when it can not find C++11 support. That said we are using `shared_ptr` in arrayfire as well (in CPU and OpenCL backends). Why is the issue not popping up over there ?

**Comment by glehmann** [comment]
Sorry I've been able to go a bit further, following the advices from https://github.com/Homebrew/homebrew-science/pull/2353
`std::shared_ptr` is found now. Note that I had the same problems in arrayfire — just copied the wrong error message.

I still have a problem though:

~~~~
In file included from /tmp/arrayfire20150609-13191-4lc7rs/arrayfire/src/backend/cpu/blas.cpp:12:
In file included from /tmp/arrayfire20150609-13191-4lc7rs/arrayfire/src/api/c/handle.hpp:17:
/tmp/arrayfire20150609-13191-4lc7rs/arrayfire/src/backend/cpu/cast.hpp:38:33: error: variable has incomplete type 'std::complex<float>'
    To eval(std::complex<float> in)
                                ^
/System/Library/Frameworks/vecLib.framework/Headers/vForce.h:31:19: note: forward declaration of 'std::complex<float>'
        template<> class complex<float>;
                         ^
In file included from /tmp/arrayfire20150609-13191-4lc7rs/arrayfire/src/backend/cpu/blas.cpp:12:
In file included from /tmp/arrayfire20150609-13191-4lc7rs/arrayfire/src/api/c/handle.hpp:17:
/tmp/arrayfire20150609-13191-4lc7rs/arrayfire/src/backend/cpu/cast.hpp:47:34: error: variable has incomplete type 'std::complex<double>'
    To eval(std::complex<double> in)
                                 ^
/System/Library/Frameworks/vecLib.framework/Headers/vForce.h:32:19: note: forward declaration of 'std::complex<double>'
        template<> class complex<double>;
                         ^
~~~~

any idea?

**Comment by pavanky** [comment]
@umar456 Can you look at this ?

**Comment by umar456** [comment]
Thats an odd error because we are including the [complex header](https://github.com/arrayfire/arrayfire/blob/devel/src/backend/cpu/cast.hpp#L14). I can't seem to reproduce it on 10.9. Do you know the compiler being used on your machine?

**Comment by pavanky** [comment]
@glehmann Is this still a problem ?

**Comment by tdsmith** [comment]
Yes, this is still a problem on OS X 10.8. Here is a log of a failing build: https://gist.github.com/95ce627dcb1ed4736967

The compiler configuration is as follows:
OS X: 10.8.5-x86_64
Xcode: 5.1.1
CLT: 5.1.0.0.1.1396320587

**Comment by tdsmith** [comment]
I should note that neither Gaëtan or I actually intend to use the software on 10.8 ourselves, but we noticed this failing on Homebrew's build server. I would personally be content with a declaration that Arrayfire supports 10.9+.

**Comment by pavanky** [comment]
@umar456 What do you think about supporting only 10.9+?

**Comment by umar456** [comment]
We will only be supporting ArrayFire on OSX 10.9 and later.
