### ISSUE TITLE
Indexing causing crashes

### ISSUE THREAD

**Issue by FilipeMaia** [arrayfire/arrayfire#795]
The following programs causes a crash on my system:

```
#include <arrayfire.h>

int main(){
  af::array A = af::array(10);
  for(int i = 0;i<10;i++){
    A(i) = 0;
  }
  A(1) = 1;
  A(3) = 1;
  af::array idx = af::where(A);
  af_print(idx);
  af::array::array_proxy C(A(idx));
  printf("%d\n", C.numdims());
  af_print(C);
  af_print(A);
  return 0;
}
```

The result is:
```
idx [2 1 1 1]
   Offsets: [0 0 0 0]
   Strides: [1 2 2 2]
         1
         3

1
libc++abi.dylib: terminating with uncaught exception of type af::exception: ArrayFire Exception(204): Function does not support this data type
In /Users/filipe/src/arrayfire/src/api/cpp/array.cpp:725
Abort trap: 6
```
I'm not sure what's the cause. The crash only happens sometimes, and sometimes the exception is different suggestion some uninitialised memory or something.

**Comment by umar456** [comment]
The array_proxy class should not be created in user code. It is only used for internal purposes to assign and index an array in a consistent format. You can achieve the same thing by assigning the A(idx) value to an af::array object:

~~~cpp
#include <arrayfire.h>

int main(){
  af::array A = af::array(10);
  for(int i = 0;i<10;i++){
    A(i) = 0;
  }
  A(1) = 1;
  A(3) = 1;
  af::array idx = af::where(A);
  af_print(idx);
  af::array C(A(idx));                               // Changed this line
  printf("%d\n", C.numdims());
  af_print(C);
  af_print(A);
  return 0;
}
~~~

This should be documented in the array_proxy class definition or we need to somehow prevent the creation of these classes in user code.

**Comment by pavanky** [comment]
I think we should just document it for now. No need to change the class.
