### ISSUE TITLE
zero length arrays cause problems

### ISSUE THREAD

**Issue by FilipeMaia** [arrayfire/arrayfire#799]
The following program shows a problem but I think the issues are more widespread:
```
#include <arrayfire.h>
int main(){
  af_print(af::array(0,f32)); 
  return 0;
}
```
This program outputs:
```
libc++abi.dylib: terminating with uncaught exception of type af::exception: ArrayFire Exception(202): Invalid input argument
In /Users/filipe/src/arrayfire/src/api/cpp/util.cpp:22
af::array(0,f64) Abort trap: 6
```

Zero length arrays are not uncommon; in my case I stumbled on it as the result of a where() call.
A few of the problematic asserts I found:
- [af_reorder](https://github.com/arrayfire/arrayfire/blob/master/src/api/c/reorder.cpp#L33)
- [af_moddims](https://github.com/arrayfire/arrayfire/blob/master/src/api/c/moddims.cpp#L42)

**Comment by munnybearz** [comment]
Agreed, I do things like this in my code:
```
    array nans = isNaN(values);
    if (anyTrue<bool>(nans))
        values(nans) = 0;
```

I'd love to be able to simplify this code to:

```
    values(isNaN(values)) = 0;
```

I can't do this right now because sometimes isNaN will return an empty vector and then the assign will fail.

**Comment by FilipeMaia** [comment]
Also empty sequences could be potentially useful.

**Comment by pavanky** [comment]
While this particular issue hasn't been solved, two new functions are in devel that might be helpful.

@munnybearz 

Instead of doing values(isNaN(values)) = 0, you could do this:

```
replace(values, isNaN(values), 0);
```

**Comment by pavanky** [comment]
There is also this:

```
array res = select(condition, a, b);
```

This does an element wise operation in the following manner:

```
c[i] = cond[i] ? a[i] : b[i];
```

If you want similar operation done in place use `replace` as mentioned in the previous comment.

**Comment by munnybearz** [comment]
Thank you guys. Both these methods are useful. I will give it a go

**Comment by munnybearz** [comment]
both the replace() and select() functions massively worsened performance for me (0.4x), so I'm back to doing:

```
    array nans = isNaN(values);
    if (anyTrue<bool>(nans))
        values(nans) = 0;
```

FYI my values data is f64, dims 54000 x 200 x 1 x 1

**Comment by pavanky** [comment]
@munnybearz Is the performance for when the if condition true ?

**Comment by munnybearz** [comment]
Yes it is almost always true

**Comment by brryan** [comment]
Just wanted to add that I have a similar issue with the `af::setUnion` function. One would expect the union of an empty array and a length > 0 array to return the second array. It would be very convenient to not have to handle the four possible cases (first input array empty, second input array empty, both input arrays empty, neither input array empty) explicitly in my code.
