### ISSUE TITLE
gtest submodule not found

### ISSUE THREAD

**Issue by munnybearz** [arrayfire/arrayfire#809]
Unable to build ArrayFire. Tested on Ubuntu 14.04 and Mac OS X Yosemite

➜  /tmp  git clone https://github.com/arrayfire/arrayfire.git
Cloning into 'arrayfire'...
remote: Counting objects: 22591, done.
remote: Compressing objects: 100% (68/68), done.
remote: Total 22591 (delta 20), reused 0 (delta 0), pack-reused 22523
Receiving objects: 100% (22591/22591), 5.04 MiB | 2.82 MiB/s, done.
Resolving deltas: 100% (15696/15696), done.
Checking connectivity... done.

➜  /tmp  cd arrayfire

➜  arrayfire git:(master) git submodule init
Submodule 'assets' (https://github.com/arrayfire/assets) registered for path 'assets'
Submodule 'test/data' (https://github.com/arrayfire/arrayfire_data) registered for path 'test/data'
Submodule 'test/gtest' (http://git.chromium.org/external/googletest.git) registered for path 'test/gtest'

➜  arrayfire git:(master) git submodule update
Cloning into 'assets'...
remote: Counting objects: 94, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 94 (delta 7), reused 4 (delta 4), pack-reused 86
Unpacking objects: 100% (94/94), done.
Checking connectivity... done.
Submodule path 'assets': checked out '77ba8d3c8dc399c49da7413774b71985ce989a09'
Cloning into 'test/data'...
remote: Counting objects: 643, done.
remote: Total 643 (delta 0), reused 0 (delta 0), pack-reused 643
Receiving objects: 100% (643/643), 7.70 MiB | 3.21 MiB/s, done.
Resolving deltas: 100% (269/269), done.
Checking connectivity... done.
Submodule path 'test/data': checked out '8b4a85eb89118028b4da524f0d734969baa4b0f2'
Cloning into 'test/gtest'...
fatal: http://git.chromium.org/external/googletest.git/info/refs not valid: is this a git repository?
Clone of 'http://git.chromium.org/external/googletest.git' into submodule path 'test/gtest' failed

➜  arrayfire git:(master) ✗

**Comment by shehzan10** [comment]
This issue has already been fixed in the hotfix branch via c3f83cd7. We will be merging it into the other branches today.

Google changed their git Http protocol from http to https which is the reason it's broken. 

Ill leave this issue open until we merge the branches.

**Comment by pavanky** [comment]
fixed in master and devel.
