### ISSUE TITLE
Sparse matrix support for all backends

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#821]
Figure out the list of alternatives that exist and implement the following functions:

- [x] Sparse matrix Creation
  - [x] From Dense
  - [x] From CSR arrays
  - [x] From COO arrays
- [ ] Format Conversion
  - [x] To Dense
  - [ ] CSR <--> COO
- [x] Matrix multiply 
  - [x] CSRMM (sparse matrix, dense matrix with options for sparse)
  - [x] CSRMV (sparse matrix, dense vector with options for sparse)
- [x]  ~~Sparse Matrix Transpose (Same as CSR --> CSC)~~ Transpose is an available option for matmul.

Use [cuSparse](http://docs.nvidia.com/cuda/cusparse/) for CUDA, [clSparse](https://github.com/clMathLibraries/clSPARSE) for OpenCL.
CPU can use either MKL or fallback. For distribution installers, we will use MKL, with the possibility of a fallback option which will need to be implemented from scratch.

**Comment by pavanky** [comment]
@shehzan10 Can you look at the potential library options for CPU sparse support?

Some of these functions are fairly easy to implement. We could implement our own versions if there are not any standard free libraries out there.

**Comment by shehzan10** [comment]
The enum for the type of storage will be `af_sparse_type` (could also use `af_sparse_matrix_type` but I think that will be too long).

`af_sparse_type` will contain `dense`, `COO`, `CSR`, `CSC`. Do we need powers of 2 ordering for this or will a natural number sequence be enough?
Note: CSC will not be supported on OpenCL unless,
* clSparse starts supporting it
* We use the CPU fallback implementation that we will implement.

The C-struct `af_sparse_array` will be internal and will be exposed as a void*. This will allow more flexibility in the future.
The C++ API will contain a new class `af::sparse` (or) `af::sparse_array`. It's members will be the struct pointed, the type of storage, functions to handle common tasks like get().

`af::matmul` will be overloaded to handle this sparse input, and a new C function `af_matmul_sparse` will be added. I don't think we need a dot operation as well.
Will matmul will have the restriction of running the same storage types?

Will sparse functions also need to support transposing options?

**Comment by ghisvail** [comment]
> Use cuSparse for CUDA, clSparse for OpenCL.

Just as an FYI, `clSPARSE` is on my packaging backlog but it is not compatible with OpenCL 2.0 yet which is Debian's default. You guys might want to push for it upstream?

**Comment by pavanky** [comment]
@ghisvail I'll talk it out with Kent :) 

Just curious, do you know if Debian (or any other distro) ships a cpu sparse blas library ?  We could not find anything in our search. So we are planning to use MKL for our binary installers and do a separate open source implementation as a fall back.

**Comment by ghisvail** [comment]
> Just curious, do you know if Debian (or any other distro) ships a cpu sparse blas library ?

[suitesparse](http://faculty.cse.tamu.edu/davis/suitesparse.html) ?

It's what numpy / scipy uses as a backend for sparse numerics.

**Comment by pavanky** [comment]
@ghisvail It is GPL and I am not entirely sure it has a sparse matrix * dense matrix library.

**Comment by UniqueFool** [comment]
It may be also worth taking a look at one of these two libraries, both of which are MIT-licensed and seem to have bleeding-edge sparse matrix support, often even outperforming other alternatives:

https://github.com/ddemidov/vexcl
http://viennacl.sourceforge.net/

**Comment by pavanky** [comment]
@UniqueFool any links to said benchmarks ?

**Comment by UniqueFool** [comment]
I guess, it would be best to ask them directly, because their benchmarks are mentioned in their docs.
Anyway, here's the corresponding ViennaCL benchmark: 

http://viennacl.sourceforge.net/viennacl-benchmarks.html

In the case of VexCL, the benchmarks seem to be part of the source tree: http://sbel.wisc.edu/documents/TR-2015-01.pdf

**Comment by pavanky** [comment]
Looks like VexCL only has SpMV which is technically just a scan_by_key operation. 

We'll need to benchmark ViennaCL with cuSparse 7.5 and clSparse to get a better understanding of their capabilities.

**Comment by UniqueFool** [comment]
They do have a few benchmarks in their repository, i.e. either these could be adapted or used "as is": https://github.com/viennacl/viennacl-dev/tree/master/examples/benchmarks

BTW: Here's a stackoverlow discussion comparing vexCL and viennaCL: http://stackoverflow.com/questions/20154179/differences-between-vexcl-thrust-and-boost-compute

**Comment by pavanky** [comment]
I am aware of the projects. What was surprising is the claim that they beat cuSparse on NVIDIA hardware. I'll need to verify the results independently.

**Comment by UniqueFool** [comment]
yes, doing that makes obviously sense before spending any time coding something ...

**Comment by WilliamTambellini** [comment]
Hi guys, 
I see this issue to be in AF 3.4, to be released in few days. 
Is this issue almost done ?
Thanks

**Comment by shehzan10** [comment]
You can follow the progress in #1319.  It will be a part of the 3.4.0 release.

**Comment by pavanky** [comment]
@WilliamTambellini To add to what @shehzan10 said, CUDA and CPU backends are supported right now in a feature branch. We are in the process of adding support for the OpenCL backend.

**Comment by pavanky** [comment]
This is fixed in devel

**Comment by ghisvail** [comment]
What did you guys end up using for sparse support on CPU and OpenCL? Your own impl, or a dependency?

**Comment by 9prady9** [comment]
@ghisvail CPU and OpenCL only support CSR/COO to dense conversions and they are in-house implementations.

**Comment by shehzan10** [comment]
You can see the features currently supported on the top comment in this issue.
Right now, CPU can either use MKL or a fallback native code.
OpenCL is completely written from scratch. clSPARSE had not one but many deal breakers for us to use.

The following items are going to be supported in the near future (may not happen prior to 3.4):
* Transpose support
* Conversion between storage formats
* OpenCL-CPU fallback for unified memory devices (cpu/on board graphics - similar to blas/lapack)

**Comment by shehzan10** [comment]
#1641 and #1653 Completes the scope of this issue.
