### ISSUE TITLE
Sparse matrix support for OpenCL backend

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#823]
Use clSPARSE to implement the following functionalities.

- [ ] Sparse (CSR) matrix creation
- [ ] Conversion to dense
- [ ] Matrix multiply (vector and matrix)
- [ ]  CSR to CSC conversion (does not exist in clSPARSE)

**Comment by ghisvail** [comment]
Could `clSPARSE` be used for the linear algebra part ?

**Comment by pavanky** [comment]
Yes that was the idea. clSPARSE was not public information when the issue was opened :p

**Comment by pavanky** [comment]
I fixed the description now :)

**Comment by shehzan10** [comment]
Merging into #821
