### ISSUE TITLE
Provide a changelog in the source tree

### ISSUE THREAD

**Issue by ghisvail** [arrayfire/arrayfire#827]
It does not need to be particularly detailed, but a changelog would be a nice thing to have. Choice of naming convention and format is up to you.

**Comment by pavanky** [comment]
@ghisvail We already have a release notes page: https://github.com/arrayfire/arrayfire/blob/master/docs/pages/release_notes.md 

Do you want something more specific?

**Comment by ghisvail** [comment]
My bad, I just did not search deep enough. I am used to changelog files at the root of the source tree. That's fine as it is. Closing.
