### ISSUE TITLE
Make CPU backend Async

### ISSUE THREAD

**Issue by umar456** [arrayfire/arrayfire#832]
The OpenCL and CUDA backend functions in ArrayFire are asynchronous whereas the CPU backend is not. We need to unify the behavior of all of the backends so that they are consistent.

Function coverage w.r.t each file in `<REPOSITORY_ROOT>/src/backend/cpu/*.cpp`:
- [x] approx.cpp
- [x] Array.cpp
- [x] assign.cpp
- [x] bilateral.cpp
- [x] blas.cpp
- [x] cholesky.cpp
- [x] convolve.cpp
- [x] copy.cpp
- [x] diagonal.cpp
- [x] diff.cpp
- [x] fast.cpp
- [x] fftconvolve.cpp
- [x] fft.cpp
- [x] gradient.cpp
- [x] harris.cpp
- [x] hist_graphics.cpp
- [x] histogram.cpp
- [x] homography.cpp
- [x] hsv_rgb.cpp
- [x] identity.cpp
- [x] iir.cpp
- [x] image.cpp
- [x] index.cpp
- [x] inverse.cpp
- [x] iota.cpp
- [x] ireduce.cpp
- [x] join.cpp
- [x] lookup.cpp
- [x] lu.cpp
- [x] match_template.cpp
- [x] math.cpp
- [x] meanshift.cpp
- [x] medfilt.cpp
- [x] morph.cpp
- [x] nearest_neighbour.cpp
- [ ] orb.cpp
- [x] plot3.cpp
- [x] plot.cpp
- [x] qr.cpp
- [x] random.cpp
- [x] range.cpp
- [x] reduce.cpp
- [x] regions.cpp
- [x] reorder.cpp
- [x] resize.cpp
- [x] rotate.cpp
- [x] scan.cpp
- [x] select.cpp
- [x] set.cpp
- [x] shift.cpp
- [x] sift.cpp
- [x] sobel.cpp
- [x] solve.cpp
- [x] sort_by_key.cpp
- [x] sort.cpp
- [x] sort_index.cpp
- [x] surface.cpp
- [x] susan.cpp
- [x] svd.cpp
- [x] tile.cpp
- [x] transform.cpp
- [x] transpose.cpp
- [x] triangle.cpp
- [x] unwrap.cpp
- [x] where.cpp
- [x] wrap.cpp

**Comment by pavanky** [comment]
I think this should be merged with https://github.com/arrayfire/arrayfire/issues/113

**Comment by 9prady9** [comment]
Are you computations going to be moved to a secondary thread ?

**Comment by umar456** [comment]
@pavanky I think this is a different issue. We are not exposing the queue with this but eventually that issue will also need to be addressed.

@9prady9 Yeah, I think that is the only way.

**Comment by unbornchikken** [comment]
And don't forget to make other blocking stuff asynchronous on GPU backends too. I mean compiling and/or loading kernels. Anything that blocks. Thanks.

**Comment by unbornchikken** [comment]
Since you gotta create a worker thread, you could improve this methods with it to make'em non blocking on CUDA and OpenCL too: https://github.com/arrayfire/arrayfire_js/issues/2
