### ISSUE TITLE
Looking for CL_VERSION_* - not found

### ISSUE THREAD

**Issue by pannous** [arrayfire/arrayfire#836]
cmake complains:
Looking for CL_VERSION_* - not found
 even though OpenCL is successfully installed and used in other apps on the Mac.

 what might have gone wrong?

**Comment by pavanky** [comment]
Is it finding other OpenCL versions ?

**Comment by pannous** [comment]
no

**Comment by pavanky** [comment]
Can you tell us the OS version you are using ?

**Comment by pannous** [comment]
OpenCL is successfully installed and used in other apps **on the Mac**.

**Comment by pavanky** [comment]
@pannous I was asking if you are using Yosemite or Mavericks or something else.

**Comment by pannous** [comment]
sorry, Yosemite

**Comment by pavanky** [comment]
This is what the output of cmake looks on our OSX build machine (also uses Yosemite)
```
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - not found
-- Looking for CL_VERSION_1_1
-- Looking for CL_VERSION_1_1 - not found
-- Looking for CL_VERSION_1_0
-- Looking for CL_VERSION_1_0 - not found
-- Found OpenCL: /System/Library/Frameworks/OpenCL.framework
```

It does not find CL_VERSION_X_Y, but it does find the OpenCL framework. The `not found` messages are pretty harmless. 

Is cmake is finding OpenCL.framework on your machine ?

**Comment by pannous** [comment]
ouch, yes, please kill me.

 I will eventually open another ticket for the build errors which we are getting
