### ISSUE TITLE
Bug in grad

### ISSUE THREAD

**Issue by shehzan10** [arrayfire/arrayfire#839]
CUDA and OpenCL have a bug that causes the second last column and row to get wrong values.
Occurs for sizes > 32.

**Comment by shehzan10** [comment]
Correction: Only happens for 32n + 1  on dim0 and 8n + 1 on dim1

**Comment by pavanky** [comment]
@shehzan10 Can you reply in the forum mention that it has been resolved and the fix should be out in the installers next week.
