### ISSUE TITLE
Implement lock and unlock in C and C++ API

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#844]
```
array::lock();
array::unlock();
```

`array::lock()` will be useful when you want arrayfire to not destroy the data pointer when the created array goes out of scope.

`array::unlock()` will be useful when a user wants to give back control to arrayfires memory manager.

**Comment by pavanky** [comment]
I don't see a case when `array::release()` will ever be useful. Infact it may be dangerous to introduce it!

**Comment by FilipeMaia** [comment]
I guess the obvious case is if you called retain, but later changed your mind. Sure if can be dangerous, and you should point that out in the documentation, but as with any powerful tool, one has to use it wisely.

**Comment by pavanky** [comment]
@FilipeMaia The way `retain` works is that it increments the internal data pointer by creating a new `af_array`. So the `release` needs to be called on the new `af_array`. Calling release on the old array will cause double free issues. So the use cases will be something like the following.

Simple usecase
```
array a(x, y, z, d_ptr, afDevice);
a.retain(); // Forget about it
```

If you want to release later.

```
array a(x, y, z, d_ptr, afDevice);
af_array lock = a.retain();
...
...
// I want to release now
af_release_array(lock);
```

**Comment by pavanky** [comment]
Thinking about it, whatever I mentioned now feels a bit kludgy. I am going to rethink the way it is implemented.

**Comment by pavanky** [comment]
Incrementing the reference count seems to be a rather bad way to do this. We have internal functions that remove a buffer from the memory manager entirely. We can expose those functions from the C api and use them as lock and unlock as needed.
