### ISSUE TITLE
exp() of a complex number

### ISSUE THREAD

**Issue by shie0041** [arrayfire/arrayfire#845]
It would be useful if exp() handled complex inputs.  One solution would be to allow a second argument for the function representing the imaginary part of the input.  For example

exp(A,B)

could be calculated as cos(A) + i*sin(B).  An alternative would be to have the function auto-recognize whether the input is complex.  If so it would perform this operation under the hood.

**Comment by pavanky** [comment]
@shie0041 The formula is a bit wrong, check #352 for the proper formula.
