### ISSUE TITLE
Wait bar

### ISSUE THREAD

**Issue by CsatiZoltan** [arrayfire/arrayfire#846]
It would be nice if a wait bar like MATLAB's `waitbar` would be implemented and would be available in for and gfor loops.

**Comment by pavanky** [comment]
gfor is technically not a "loop". It asks the program to perform all the batched operations inside the code block to be done in parallel.

As for doing it in a for loop, waitbar is just a glorified `printf`. You can achieve what you want with the following macro.

```
#define WAITBAR(progress, ...) do { \
    printf("\rProgress: %2.2f.", progress);\
    printf(__VA_ARGS__);\
    fflush(stdout);\
}
```

Then you can do something like this:

```
WAITBAR(step / steps);
WAITBAR(step / steps, "Current error: %lf", err);
```

**Comment by CsatiZoltan** [comment]
All right, but I thought of a graphical display, like [this](http://www.mathworks.com/help/matlab/ref/waitbar.html). Is it difficult to create for a person who is not proficient in C++ and graphics?

**Comment by pavanky** [comment]
@9prady9 Can we do something in forge ?

**Comment by CsatiZoltan** [comment]
What do you mean? I don't know this expression.

**Comment by pavanky** [comment]
@9prady9  is one of our developers. forge is our graphics library. I was pinging him to see if something like this can be done in our graphics library and then used in arrayfire.

**Comment by CsatiZoltan** [comment]
Oh, I see.

**Comment by 9prady9** [comment]
@CsatiZoltan & @pavanky Sure, it can be done. We need to work out the details of how it would fit into forge and the code flow. I am not aware of this `waitbar` from matlab. From the look of it, it seems to be like just a progress bar. So, probably it will be a window of it's own (more like a class of it's own type) but with a bar indicating progress and some text above it.

**Comment by CsatiZoltan** [comment]
I agree, that window should just serve as a progress bar.

**Comment by umar456** [comment]
This function is out of the scope of ArrayFire. ArrayFire is a compute library, and it should not be responsible for UI related operations like this. I can see many issues which will complicate building, shipping, and it will add unnecessary OS specific dependencies into the library.

**Comment by CsatiZoltan** [comment]
Ok, logical.
