### ISSUE TITLE
Incorrect af::max() calculation when input array has an af::NaN

### ISSUE THREAD

**Issue by munnybearz** [arrayfire/arrayfire#860]
ArrayFire v3.0.2 (CPU, 64-bit Linux, build 0c828ed)

The following code produces an incorrect af::max() result:

```
array A  = randu(5);
A(3) = af::NaN;
af_print(A);
af_print(af::max(A));
```

The output says the max is 0.5328, whereas I can see it is 0.7556:

```
A [5 1 1 1]
0.0000
0.1315
0.7556
nan
0.5328

af::max(A) [1 1 1 1]
0.5328
```

Also when the last value in the array is NaN, max returns NaN.. it seems its running max is reset when it hits a NaN

**Comment by pavanky** [comment]
@umar456 There are two ways we can deal with this:

- Always ignore nan and do the operations on the remaining values. This will not affect `min` and `max`, but I am not sure what the behavior of `sum` should be when an array has nans.

- Provide a new entry point where users who think their array might contain nans and provide them with an option to ignore it.

There will not be much performance hits either way as far as I can tell.

**Comment by umar456** [comment]
I think we can ignore `nan`s for `min` and `max`. For sum and other reduction functions we should return `nan`.

**Comment by pavanky** [comment]
There may be use cases in statistics where the option to ignore nans is useful. We need a mechanism to do that for sum / mean / std etc as well.

**Comment by shehzan10** [comment]
Is it possible to use a state variable rather than an option in the API? That way the API remains consistent. Something like
`af_ignore(AF_NaN_REDUCTION | AF_NaN_ALL | AF_NaN_STATISTICS);`
The arguments being enums.
