### ISSUE TITLE
32bit Support

### ISSUE THREAD

**Issue by paoloviviani** [arrayfire/arrayfire#864]
Is it possible to use/build Arrayfire on 32bit platforms? At least for the CPU backend, as CUDA dropped 32bit support from version 7 onwards.

**Comment by pavanky** [comment]
@paoloviviani Which OS are you looking at ? We have Linux version building on 32 bit systems for Tegra. We have had *some* success of doing the same on Windows but we don't plan to actively support it.

**Comment by paoloviviani** [comment]
I'm interested in both Windows and Linux (mostly Windows), but the target architecture would be x86. I can understand that there is no will to support win32 architectures, but I was asking since that would probably be a dealmaker for me, as I need backward compatibility with win32 stuff.

**Comment by pavanky** [comment]
@shehzan10 has some information about how to build ArrayFire on 32 bit windows. It should **build** fine. We just do not actively test it. If you face some problems, you can create issues and we will try to figure it out.

**Comment by shehzan10** [comment]
To build CPU (and OpenCL) for 32 bit, you will need to do the following:
* Obtain/Build 32-bit versions of the dependencies (FFTW, LAPACKE, FreeImage, GLFW, GLEW)
* Build with generator as "Visual Studio 12 2013".

You can modify the [arrayfire-windows-scripts](https://github.com/shehzan10/arrayfire-windows-scripts) to work with the 32-bit versions.

**Comment by pavanky** [comment]
@paoloviviani 

As shehzan mentioned the biggest issue for building 32 bit libraries is getting the 32 bit libraries. We have not invested time in it because we do not have enough demand for it.

However we have customized solutions available from our company. If you want to pursue that route, you can contact us via support@arrayfire.com

**Comment by paoloviviani** [comment]
Ok, thanks for the useful information!
