### ISSUE TITLE
Improved uniform random number generation

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#868]
Add the following types of random number generators across all backends to make them consistent

- [x] Mersenne twister (present in cuRand and std::random, not present in clrng)
- [ ] xorwow (present in curand, needs cpu and opencl implementations)
- [ ] MRG32K3a (present in curand and clrng, needs cpu implementation)
- [x] Threefry (from Random123) (needs to be ported from Random123 to CUDA and CPU backends) 
- [x] Philox (from Random123) (needs to be ported from Random123 to all backends)

**Comment by shehzan10** [comment]
Add new random number generation functions as JIT operations on uniform/normal random number generation:

* exponential(lamdba): `x = log(1 - u) / (-lambda)`, where u is the uniform number
* gamma(r, lambda)
* chi-squared: gamma distribution with r = n / 2, lambda = 2.
* non-central chi-squared
* Poisson

Useful links:
https://en.wikipedia.org/wiki/Relationships_among_probability_distributions
http://www.azimuthproject.org/azimuth/show/Transforming+uniform+random+variables+to+other+distributions
