### ISSUE TITLE
New plotting functions

### ISSUE THREAD

**Issue by CsatiZoltan** [arrayfire/arrayfire#872]
Will ArrayFire have various new plotting functions, like surface plot, mesh plot, volume visualization functions, etc., such as Jacket had?

**Comment by pavanky** [comment]
@CsatiZoltan For various reasons we can not reuse the graphics functions Jacket had. We have begun a independent library, [forge](https://github.com/arrayfire/forge) that uses more modern versions of OpenGL and is also more modular.

Please file any visualization requests you have over there. Once the necessary functions are available upstream in forge, they will be available fairly quickly in arrayfire.
