### ISSUE TITLE
Documentation for 3.1.0

### ISSUE THREAD

**Issue by unbornchikken** [arrayfire/arrayfire#885]
https://github.com/arrayfire/arrayfire/issues/824 continued.

- [x] lookup
- [x] af_lookup
- [x] af_index_gen
- [x] af_assign_gen
- [x] af_assign_seq
- [x] array operator%
- [x] array.T
- [x] array.H
- [x] everything in af/cuda.h
- [x] C functions in af/opencl.h

----

Broken documentation

- [x] complex(real, imag) does not show up

**Comment by pavanky** [comment]
array.S ?

**Comment by unbornchikken** [comment]
Sorry, H.
