### ISSUE TITLE
Add version guards for new functions going to 3.1

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#887]
The following macros need to be added:

```
#ifndef AF_API_VERSION
#define AF_API_VERSION $MAJOR$MINOR
#endif
```

For the 3.1 release `#define AF_API_VERSION 31` and  will be defined.

Once the macros have been defined, all new functions added since 3.0 will be inside an `#if AF_API_VERSION >= 31` guard. The list of new functions include:

This enables the users to revert back to an older version of the header file by simply doing something like this in user code:

```
#define AF_API_VERSION 30
#include <arrayfire.h>
```

The above snippet ensures the code being compiled does not use any functions from ArrayFire 3.1

- [x] AFAPI array sum(const array &in, const int dim, const double nanval);
- [x] AFAPI array product(const array &in, const int dim, const double nanval);
- [x] AFAPI af_err af_sum_nan(af_array *out, const af_array in, const int dim, const double nanval);
- [x] AFAPI af_err af_product_nan(af_array *out, const af_array in, const int dim, const double nanval);
- [x] AFAPI af_err af_sum_nan_all(double *real, double *imag, const af_array in, const double nanval);
- [x] AFAPI af_err af_product_nan_all(double *real, double *imag, const af_array in, const double nanval);
- [x] AFAPI array sigmoid (const array &in);
- [x] AFAPI af_err af_sigmoid (af_array *out, const af_array in);
- [x] AFAPI af_err afcu_get_stream(cudaStream_t* stream, int id);
- [x] AFAPI af_err afcu_get_native_id(int* nativeid, int id);
- [x] AFAPI array select(const array &cond, const array  &a, const array  &b);
- [x] AFAPI array select(const array &cond, const array  &a, const double &b);
- [x] AFAPI array select(const array &cond, const double &a, const array  &b);
- [x] AFAPI void replace(array &a, const array  &cond, const array  &b);
- [x] AFAPI void replace(array &a, const array  &cond, const double &b);
- [x] AFAPI af_err af_select(af_array *out, const af_array cond, const af_array a, const af_array b);
- [x] AFAPI af_err af_select_scalar_r(af_array *out, const af_array cond, const af_array a, const double b);
- [x] AFAPI af_err af_select_scalar_l(af_array *out, const af_array cond, const double a, const af_array b);
- [x] AFAPI af_err af_replace(af_array a, const af_array cond, const af_array b);
- [x] AFAPI af_err af_replace_scalar(af_array a, const af_array cond, const double b);
- [x] AFAPI af_err af_lock_device_ptr(const af_array arr);
- [x] AFAPI af_err af_unlock_device_ptr(const af_array arr);
- [x] AFAPI af_err af_set_size(const af_window wind, const unsigned w, const unsigned h);
- [x] AFAPI array dog(const array& in, const int radius1, const int radius2);
- [x] AFAPI array unwrap(const array& in, const dim_t wx, const dim_t wy,
- [x] AFAPI array sat(const array& in);
- [x] AFAPI array ycbcr2rgb(const array& in, const YCCStd standard=AF_YCC_601);
- [x] AFAPI array rgb2ycbcr(const array& in, const YCCStd standard=AF_YCC_601);
- [x] AFAPI af_err af_dog(af_array *out, const af_array in, const int radius1, const int radius2);
- [x] AFAPI af_err af_unwrap(af_array *out, const af_array in, const dim_t wx, const dim_t wy,
- [x] AFAPI af_err af_sat(af_array *out, const af_array in);
- [x] AFAPI af_err af_ycbcr2rgb(af_array* out, const af_array in, const af_ycc_std standard);
- [x] AFAPI af_err af_rgb2ycbcr(af_array* out, const af_array in, const af_ycc_std standard);
- [x] AFAPI void copy(array &dst, const array &src,
- [x] AFAPI void fftInPlace(array& in, const double norm_factor = 1);
- [x] AFAPI void fft2InPlace(array& in, const double norm_factor = 1);
- [x] AFAPI void fft3InPlace(array& in, const double norm_factor = 1);
- [x] AFAPI void ifftInPlace(array& in, const double norm_factor = 1);
- [x] AFAPI void ifft2InPlace(array& in, const double norm_factor = 1);
- [x] AFAPI void ifft3InPlace(array& in, const double norm_factor = 1);
- [x] AFAPI af_err af_fft_inplace(af_array in, const double norm_factor);
- [x] AFAPI af_err af_fft2_inplace(af_array in, const double norm_factor);
- [x] AFAPI af_err af_fft3_inplace(af_array in, const double norm_factor);
- [x] AFAPI af_err af_ifft_inplace(af_array in, const double norm_factor);
- [x] AFAPI af_err af_ifft2_inplace(af_array in, const double norm_factor);
- [x] AFAPI af_err af_ifft3_inplace(af_array in, const double norm_factor);
- [x] AFAPI af_err af_fft_r2c (af_array *out, const af_array in, const double norm_factor, const dim_t pad0);
- [x] AFAPI af_err af_fft2_r2c(af_array *out, const af_array in, const double norm_factor, const dim_t pad0, const dim_t pad1);
- [x] AFAPI af_err af_fft3_r2c(af_array *out, const af_array in, const double norm_factor, const dim_t pad0, const dim_t pad1, const dim_t pad2);
- [x] AFAPI af_err af_fft_c2r (af_array *out, const af_array in, const double norm_factor, const bool is_odd);
- [x] AFAPI af_err af_fft2_c2r(af_array *out, const af_array in, const double norm_factor, const bool is_odd);
- [x] AFAPI af_err af_fft3_c2r(af_array *out, const af_array in, const double norm_factor, const bool is_odd);
- [x] AFAPI void print(const char *exp, const array &arr, const int precision);
- [x] AFAPI int saveArray(const char *key, const array &arr, const char *filename, const bool append = false);
- [x] AFAPI array readArray(const char *filename, const unsigned index);
- [x] AFAPI array readArray(const char *filename, const char *key);
- [x] AFAPI int readArrayCheck(const char *filename, const char *key);
- [x] AFAPI void toString(char **output, const char *exp, const array &arr,
- [x] AFAPI af_err af_print_array(af_array arr);
- [x] AFAPI af_err af_print_array_gen(const char *exp, const af_array arr, const int precision);
- [x] AFAPI af_err af_save_array(int *index, const char* key, const af_array arr, const char *filename, const bool append);
- [x] AFAPI af_err af_read_array_index(af_array *out, const char *filename, const unsigned index);
- [x] AFAPI af_err af_read_array_key(af_array *out, const char *filename, const char* key);
- [x] AFAPI af_err af_read_array_key_check(int *index, const char *filename, const char* key);
- [x] AFAPI af_err af_array_to_string(char **output, const char *exp, const af_array arr,
- [x] AFAPI features harris(const array& in, const unsigned max_corners=500, const float min_response=1e5f, const float sigma=1.f, const unsigned block_size=0, const float k_thr=0.04f);
- [x] AFAPI void nearestNeighbour(array& idx, array& dist,
- [x] AFAPI features susan(const array& in,
- [x] AFAPI af_err af_harris(af_features *out, const af_array in, const unsigned max_corners, const float min_response, const float sigma, const unsigned block_size, const float k_thr);
- [x] AFAPI af_err af_nearest_neighbour(af_array* idx, af_array* dist,
- [x] AFAPI af_err af_susan(af_features* out, const af_array in, const unsigned radius, const float diff_thr, const float geom_thr,
- [x] af_wrap
- [x] wrap

**Comment by pentschev** [comment]
I think it would be simpler to have a macro that would allow comparison:

```
#define AF_VERSION 310
#if AF_VERSION >= 310
#endif
```

**Comment by pavanky** [comment]
Well that would be simpler yes. However we are using `AF_VERSION` as a string currently. We can perhaps appropriate a different name.

**Comment by pentschev** [comment]
Yeah, forgot about it. We can use something like `AF_VERSION_NUM`, I can't think of anything more appropriate right now.

**Comment by shehzan10** [comment]
We can use AF_API_VERSION.
We could possibly then use AF_FORCE_API_VERSION if we want to force a specific version.

Note: Ideas from cuda.h.

**Comment by pentschev** [comment]
+1 for the above.

**Comment by pavanky** [comment]
`AF_API_VERSION` it is.

**Comment by pavanky** [comment]
@9prady9 @shehzan10 @pentschev 

Can you append the list of new functions being added to 3.1 in this issues description ?

**Comment by pavanky** [comment]
@shehzan10 Update the list of functions here

**Comment by shehzan10** [comment]
Here is a preliminary list:
- [ ] AFAPI array sum(const array &in, const int dim, const double nanval);
- [ ] AFAPI array product(const array &in, const int dim, const double nanval);
- [ ] AFAPI af_err af_sum_nan(af_array *out, const af_array in, const int dim, const double nanval);
- [ ] AFAPI af_err af_product_nan(af_array *out, const af_array in, const int dim, const double nanval);
- [ ] AFAPI af_err af_sum_nan_all(double *real, double *imag, const af_array in, const double nanval);
- [ ] AFAPI af_err af_product_nan_all(double *real, double *imag, const af_array in, const double nanval);
- [ ] AFAPI array sigmoid (const array &in);
- [ ] AFAPI af_err af_sigmoid (af_array *out, const af_array in);
- [ ] AFAPI af_err afcu_get_stream(cudaStream_t* stream, int id);
- [ ] AFAPI af_err afcu_get_native_id(int* nativeid, int id);
- [ ] AFAPI array select(const array &cond, const array  &a, const array  &b);
- [ ] AFAPI array select(const array &cond, const array  &a, const double &b);
- [ ] AFAPI array select(const array &cond, const double &a, const array  &b);
- [ ] AFAPI void replace(array &a, const array  &cond, const array  &b);
- [ ] AFAPI void replace(array &a, const array  &cond, const double &b);
- [ ] AFAPI af_err af_select(af_array *out, const af_array cond, const af_array a, const af_array b);
- [ ] AFAPI af_err af_select_scalar_r(af_array *out, const af_array cond, const af_array a, const double b);
- [ ] AFAPI af_err af_select_scalar_l(af_array *out, const af_array cond, const double a, const af_array b);
- [ ] AFAPI af_err af_replace(af_array a, const af_array cond, const af_array b);
- [ ] AFAPI af_err af_replace_scalar(af_array a, const af_array cond, const double b);
- [ ] AFAPI af_err af_lock_device_ptr(const af_array arr);
- [ ] AFAPI af_err af_unlock_device_ptr(const af_array arr);
- [ ] AFAPI af_err af_set_size(const af_window wind, const unsigned w, const unsigned h);
- [ ] AFAPI array dog(const array& in, const int radius1, const int radius2);
- [ ] AFAPI array unwrap(const array& in, const dim_t wx, const dim_t wy,
- [ ] AFAPI array sat(const array& in);
- [ ] AFAPI array ycbcr2rgb(const array& in, const YCCStd standard=AF_YCC_601);
- [ ] AFAPI array rgb2ycbcr(const array& in, const YCCStd standard=AF_YCC_601);
- [ ] AFAPI af_err af_dog(af_array *out, const af_array in, const int radius1, const int radius2);
- [ ] AFAPI af_err af_unwrap(af_array *out, const af_array in, const dim_t wx, const dim_t wy,
- [ ] AFAPI af_err af_sat(af_array *out, const af_array in);
- [ ] AFAPI af_err af_ycbcr2rgb(af_array* out, const af_array in, const af_ycc_std standard);
- [ ] AFAPI af_err af_rgb2ycbcr(af_array* out, const af_array in, const af_ycc_std standard);
- [ ] AFAPI void copy(array &dst, const array &src,
- [ ] AFAPI void fftInPlace(array& in, const double norm_factor = 1);
- [ ] AFAPI void fft2InPlace(array& in, const double norm_factor = 1);
- [ ] AFAPI void fft3InPlace(array& in, const double norm_factor = 1);
- [ ] AFAPI void ifftInPlace(array& in, const double norm_factor = 1);
- [ ] AFAPI void ifft2InPlace(array& in, const double norm_factor = 1);
- [ ] AFAPI void ifft3InPlace(array& in, const double norm_factor = 1);
- [ ] AFAPI af_err af_fft_inplace(af_array in, const double norm_factor);
- [ ] AFAPI af_err af_fft2_inplace(af_array in, const double norm_factor);
- [ ] AFAPI af_err af_fft3_inplace(af_array in, const double norm_factor);
- [ ] AFAPI af_err af_ifft_inplace(af_array in, const double norm_factor);
- [ ] AFAPI af_err af_ifft2_inplace(af_array in, const double norm_factor);
- [ ] AFAPI af_err af_ifft3_inplace(af_array in, const double norm_factor);
- [ ] AFAPI af_err af_fft_r2c (af_array *out, const af_array in, const double norm_factor, const dim_t pad0);
- [ ] AFAPI af_err af_fft2_r2c(af_array *out, const af_array in, const double norm_factor, const dim_t pad0, const dim_t pad1);
- [ ] AFAPI af_err af_fft3_r2c(af_array *out, const af_array in, const double norm_factor, const dim_t pad0, const dim_t pad1, const dim_t pad2);
- [ ] AFAPI af_err af_fft_c2r (af_array *out, const af_array in, const double norm_factor, const bool is_odd);
- [ ] AFAPI af_err af_fft2_c2r(af_array *out, const af_array in, const double norm_factor, const bool is_odd);
- [ ] AFAPI af_err af_fft3_c2r(af_array *out, const af_array in, const double norm_factor, const bool is_odd);
- [ ] AFAPI void print(const char *exp, const array &arr, const int precision);
- [ ] AFAPI int saveArray(const char *key, const array &arr, const char *filename, const bool append = false);
- [ ] AFAPI array readArray(const char *filename, const unsigned index);
- [ ] AFAPI array readArray(const char *filename, const char *key);
- [ ] AFAPI int readArrayCheck(const char *filename, const char *key);
- [ ] AFAPI void toString(char **output, const char *exp, const array &arr,
- [ ] AFAPI af_err af_print_array(af_array arr);
- [ ] AFAPI af_err af_print_array_gen(const char *exp, const af_array arr, const int precision);
- [ ] AFAPI af_err af_save_array(int *index, const char* key, const af_array arr, const char *filename, const bool append);
- [ ] AFAPI af_err af_read_array_index(af_array *out, const char *filename, const unsigned index);
- [ ] AFAPI af_err af_read_array_key(af_array *out, const char *filename, const char* key);
- [ ] AFAPI af_err af_read_array_key_check(int *index, const char *filename, const char* key);
- [ ] AFAPI af_err af_array_to_string(char **output, const char *exp, const af_array arr,
- [ ] AFAPI features harris(const array& in, const unsigned max_corners=500, const float min_response=1e5f, const float sigma=1.f, const unsigned block_size=0, const float k_thr=0.04f);
- [ ] AFAPI void nearestNeighbour(array& idx, array& dist,
- [ ] AFAPI features susan(const array& in,
- [ ] AFAPI af_err af_harris(af_features *out, const af_array in, const unsigned max_corners, const float min_response, const float sigma, const unsigned block_size, const float k_thr);
- [ ] AFAPI af_err af_nearest_neighbour(af_array* idx, af_array* dist,
- [ ] AFAPI af_err af_susan(af_features* out, const af_array in, const unsigned radius, const float diff_thr, const float geom_thr,

**Comment by pavanky** [comment]
@shehzan10 is this a result of grep :p ? Looks good and comprehensive!

**Comment by shehzan10** [comment]
Yeah `git diff v3.0.2 HEAD include/af | grep AFAPI`.  That gave a good list but had to remove the functions that were moved between files.

**Comment by pavanky** [comment]
[ ] af_wrap
[ ] wrap
