### ISSUE TITLE
Add 64 bit integer support for relevant functions

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#900]
List of functions:

- [x] bilateral
- [x] iota
- [x] range
- [x] diff1
- [x] diff2
- [x] minfilt
- [x] medfilt
- [x] maxfilt
- [x] flip
- [x] histogram
- [x] af_join_many
- [x] match_template
- [x] mean_shift
- [x] median
- [x] median_all
- [x] morph
- [x] morph3d
- [x] accum
- [x] set unique
- [x] set intersect
- [x] shift
- [x] sobel
- [x] sort
- [x] tile

**Comment by shehzan10** [comment]
- [ ] bilateral
- [ ] iota
- [ ] range
- [ ] diff1
- [ ] diff2
- [ ] minfilt
- [ ] medfilt
- [ ] maxfilt
- [ ] flip
- [ ] histogram
- [ ] af_join_many
- [ ] match_template
- [ ] bilateral
- [ ] mean_shift
- [ ] median
- [ ] median_all
- [ ] morph
- [ ] morph3d
- [ ] accum
- [ ] set unique
- [ ] set intersect
- [ ] shift
- [ ] sobel
- [ ] sort

**Comment by pavanky** [comment]
@shehzan10 Can you modify the original issue ?

**Comment by shehzan10** [comment]
Issues with the unsupported functions:
* Image processing functions currently have not been added.
* Sort: Boost.Compute uses long instead of long long which causes incompatibility issues.
* Set, Median uses sort
