### ISSUE TITLE
Possibly add device properties for CPU backend

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#903]
Right now it just provides a warning and does not return anything.

One bit of feedback we received over email says the following:

> Would it be possible to return some suitable information, e.g. platform=CPU or x86_64?

@umar456 @shehzan10 @9prady9 thoughts ?

**Comment by umar456** [comment]
It should be possible via https://en.wikipedia.org/wiki/CPUID

**Comment by shehzan10** [comment]
If we are going to provide any information, we might as well go all the way and do it properly.
I think it would be best to write a simple library for this. There are a few that exist for Java (https://github.com/dblock/oshi) but nothing for C/C++.

**Comment by pavanky** [comment]
Here is my suggestion:

- d_name can be retrieved from CPUID and the number of cores can be appended to it.
- d_platform will be just CPU to be "CPU" 
- d_toolkit will be the compiler + version
- d_compute will either be "unknown" or "SSE2/SSE3/AVX" if we can query the hardware capability.

At the very least we should return something like "x86_64 8 core", "CPU", "gcc 5.1", "unknown"

**Comment by shehzan10** [comment]
Problems with this approach:
* CPUID is mainly for x86. ARM, powerpc etc have special registers. Hence the implementation will be extremely messy.
* The compiler version for the library may be different from the compiler version for the application/examples

**Comment by pavanky** [comment]
@shehzan10

- Agree about CPUID
- I think it is important to provide information about what the compiler is compiled with. It should not matter if the downstream applications are compiled with something else.

**Comment by umar456** [comment]
It could also be important to list the BLAS and FFT libraries used.

**Comment by pavanky** [comment]
That information is not important for this function. We can have it in the backend specific headers.

**Comment by 9prady9** [comment]
@pavanky @umar456 using `cpuid` getting the information on x86 arch seemed fairly easily enough. But, on ARM, it seems like we need privileged access to read cp15 registers that can provide us with the cpuid information. Let me know how should we proceed. I personally think, we don't have any other option other than reading `/proc/cpuinfo` on ARM machines but again i don't know how this would work on windows 8 phones (this is not a concern for us right now though)

**Comment by pavanky** [comment]
@9prady9 Let the thread and other fields for ARM be "unknown"  for 3.1. We'll deal with this later. Just support x86 fully for now.

**Comment by 9prady9** [comment]
ok. Will send in a PR soon with x86 details.
