### ISSUE TITLE
Default values of rgb2gray and gray2rgb are not consistent.

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#912]
If you do gray2rgb(rgb2gray(image)) you get different values compared to the input. I think this should result in the same output.

**Comment by 9prady9** [comment]
@pavanky `rgb2gray` is calculated using `r*0.2126f+g*0.7152f+b*0.0722f` however, `gray2rgb` is mere tiling of gray scale image along the channel dimension or channels that are created using different scale factors for each channel. Irrespective of the method used for conversion, it is not possible for `gray2rgb(rgb2gray())` to result in original color image without any additional information.

**Comment by pavanky** [comment]
Closing because silly on my part.
