### ISSUE TITLE
Assigning single element array to a vector array is broken

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#924]
code to reproduce:

```
array a = randu(5);
array b = randu(1);
a(span) = b;
```

This code worked in 2.1

**Comment by shehzan10** [comment]
I tested this for a matrix and that seems to fail (not covered in this issue). It looks like matrix and other higher dimensions worked in 2.x.
It also looks like binary ops worked for single value array + vector/matrix pairs in 2.1.
Any thoughts on supporting those?

Some sample code:
```
array V = randu(5);
array M = randu(5, 5);
array S = randu(1);

array V(span) = S; // Works. Fixed by this issue.
array M(span, span) = S; //Breaks
array A = V + S; // Breaks. Worked in 2.1
array B = M + S; // Breaks. Worked in 2.1
```

**Comment by pavanky** [comment]
@shehzan10 `M(span) = S` should work. Can you verify that?

**Comment by shehzan10** [comment]
Yeah that works. But no arithmetic/elwise operations.

**Comment by shehzan10** [comment]
Should we reopen this for 3.2?
