### ISSUE TITLE
Change default stream of CUDA backend

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#926]
The default stream used to launch all CUDA kernels should not be stream 0. Launching a kernel on stream0 synchronizes all other streams. 

We should create a new stream and use that instead.

Changes to make:
- Launch all kernels with a stream parameter

**Comment by 9prady9** [comment]
include/af/cuda.h:
* afcu_get_stream
* afcu_get_native_id

```
getStream()
getNativeId()
```
