### ISSUE TITLE
ImageIO in Memory

### ISSUE THREAD

**Issue by shehzan10** [arrayfire/arrayfire#930]
The plan is to add API to allow images to be loaded from/written to host side memory. FreeImage has the necessary API to do this.

Possible ArrayFire side API is:
```
array loadImageFromMemory(const void *ptr);  // Decodes and deep copies the image binary pointer to an array. Note the missing is_color argument.

void* saveImageToMemory(const char* file_ext, const array &in); // Deep copies and encodes the input array into a stream created by FI. 
```

In save to memory, the stream needs to be freed using FI API call at the end of its use. 
We can either copy it into a user defined buffer and return this to the user (immediately deleting the stream) and ask the user to free that memory similar to the host function.
The other option is to ask the user to call an AF api that in turn calls the FI api to free this memory.

**Comment by 9prady9** [comment]
shouldn't loadImageFromMemory take meta data to figure what the data layout is ?

**Comment by shehzan10** [comment]
The ptr should contain binary data including the image type, sizes etc. In a general case, loadImageFromMemory should be called only on a ptr that is returned from saveImageFromMemory.
