### ISSUE TITLE
Update tags for ArrayFire dependencies to latest stable version

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#947]
- [x] Boost Compute
- [x] clBLAS
- [x] clFFT
- [x] Forge

**Comment by shehzan10** [comment]
The last time I checked, I think clBLAS/clFFT had components from OpenCL 1.2 added to its develop branch. Just be mindful of this when updating.

**Comment by 9prady9** [comment]
@pavanky Forge has been updated. I did this in yesterday's PR #942

**Comment by pavanky** [comment]
Moving to 3.2 because of failures.
