### ISSUE TITLE
Fix documentation for af::array constructors

### ISSUE THREAD

**Issue by rggjan** [arrayfire/arrayfire#950]
In the documentation of the af::array constructor it is unclear when the data from a host pointer is copied. In most of the constructors documentation:

http://www.arrayfire.com/docs/group__construct__mat.htm#ga8c330c41d6e06b0dea9377ef02762c6f
http://www.arrayfire.com/docs/group__construct__mat.htm#gabd3d95b130bdb2d7e713414687e6b15a
http://www.arrayfire.com/docs/group__construct__mat.htm#gaaa8fab98447367bc4eaf3d7bc61d8ff5 
...

it simply says: *This function copies data from the location specified by the pointer to an array on the device*

However, at one place:

http://www.arrayfire.com/docs/group__construct__mat.htm#gaa2ebe6a7b991fbe6231321138e79121c

it states: *Note that this is a synchronous copy. The elements are not actually filled until this array is evaluated or used in the evaluation of some other expression that uses this array object.*

Questions:
* Should this say "asynchronous"? Because _synchronous_ means, it *is* filled right away, if I am not mistaken, while _asynchronous_ means it's filled later.
* I assume its the same for all function, this should be unified.

And, most importantly:
* Does this mean, the data at the pointer has to be valid as long as the array or copies of the array are around?
* What if I need to free the data at the pointer? Is it enough to run _eval()_ on the array to make it copy the data to the device?

**Comment by 9prady9** [comment]
@rggjan We apologize for the misleading statement in the documentation. Yes, as of 3.0.2 the copies are synchronous and are blocking in nature. However, this is going to change with 3.1.0 minor release. From 3.1.0 on-wards, these constructor calls will result in asynchronous copy, hence making the above statement valid with the correction of the word `synchronous` to `asynchronous`. This behavior is already available in `devel` for CUDA backend. You can follow #832 for the progress on CPU backend. We are trying to make the behavior consistent across all backends for 3.1.0

Before 3.1.0, you don't need to keep the pointer alive once you call the constructor. However, from 3.1.0 on-wards should you choose to free the memory on host immediatel, you would have to do an `array::eval()` call before doing so.

**Comment by rggjan** [comment]
Good to know, thanks for the clarifications!

**Comment by pavanky** [comment]
@rggjan Sorry about the confusion. The constructors are still going to be blocking and synchronous in 3.1.0 as well. We made other kinds of internal memory copies asynchronous internally. 

 The documentation is wrong simply. We need to fix it.

**Comment by 9prady9** [comment]
@rggjan My bad i got confused with some other changes we did for memory copies internally.What @pavanky says is correct.

**Comment by umar456** [comment]
ne098541wtmjbagimqwy256in8v264519ypnj a

**Comment by umar456** [comment]
8q9v8y26452y7wr5n3i1fzdxusqmkhedglnrsuvxy1346-[\][
