### ISSUE TITLE
incorrect transposition

### ISSUE THREAD

**Issue by AgapovO** [arrayfire/arrayfire#956]
I use arrayfire lib with Intel MKL on the windows. There is the problem with the function 

```C++
array transpose(const array& in, const bool conjugate = false);
```
from include\af\blas.h. When I make conjugate transpose of a matrix this function works fine. But when I try make conjugate transpose of a vector (matrix with size N*1) this function make transpose only (without conjugation).

**Comment by shehzan10** [comment]
A quick look at the code and yes, this is a bug. When the input is a vector, we simply change the meta data.
A fix for this should be out soon.
