### ISSUE TITLE
af::plot function

### ISSUE THREAD

**Issue by maxineliuqun** [arrayfire/arrayfire#972]
Hi,

I am trying to use "af::plot" to plot a vector, but it does not display any plots. Here is a sample code:

		int width = 2540;
		af::array Y = af::constant<float>(62280.0, (width), f32);
		af::array X = af::seq((double)1, (double)width);

		af::Window plotWin("plot");
		while (!plotWin.close())
			plotWin.plot(X, Y);

I would appreciate any help! Thanks!

**Comment by 9prady9** [comment]
@maxineliuqun I was able to reproduce the issue and i am looking into it. Will let you know as soon as we find something useful. Thanks for reporting this.

**Comment by 9prady9** [comment]
I believe this is an upstream up from forge where one of the corner cases wasn't appropriately handled. Will fix it in the upstream and it should get fixed in ArrayFire once Forge tag# is updated.

Upstream bug [reference](https://github.com/arrayfire/forge/issues/44)

**Comment by maxineliuqun** [comment]
Thank you for looking into it, Pradeep!

On Wed, Aug 26, 2015 at 3:29 PM, Pradeep Garigipati <
notifications@github.com> wrote:

> I believe this is an upstream up from forge where one of the corner cases
> wasn't appropriately handled. Will fix it in the upstream and it should get
> fixed in ArrayFire once Forge tag# is updated.
>
> Upstream bug reference <https://github.com/arrayfire/forge/issues/44>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arrayfire/arrayfire/issues/972#issuecomment-135175621>
> .
>



-- 
Qun (Maxine) Liu,
Software Engineer,
Varian Medical Systems, Inc.
Email: maxineliuqun@gmail.com
Website: qunmaxineliu.weebly.com

**Comment by 9prady9** [comment]
@maxineliuqun this is fixed in devel now.
