### ISSUE TITLE
Support batches along indices for approx1 and approx2 

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#978]
Currently each batch of the input uses the same pos0 and / or pos1.  New functionality would enable each batch of inputs to have their own set of positions to approximate.

**Comment by shehzan10** [comment]
Why does this need 3.2? We can ship it in 3.1.1. There is not change in API.

**Comment by pavanky** [comment]
@shehzan10 This is a feature improvement not a bug fix.
