### ISSUE TITLE
Expose Array<T>.isOwner() function

### ISSUE THREAD

**Issue by FilipeMaia** [arrayfire/arrayfire#985]
Currently there's no way to know if an array is an indexed array or not and certain functions (such as af_moddims) behave differently depending on the type of the array.
Exposing Array<T>.isOwner() would allow the user to predict figure this out.

**Comment by pavanky** [comment]
`af_get_ref_count` is a good indicator.

**Comment by pavanky** [comment]
Dealing with this issue over here: https://github.com/arrayfire/arrayfire/issues/1131
