### ISSUE TITLE
tar xvfj arrayfire-full-3.1.0.tar.bz2: "tar: This does not look like a tar archive"

### ISSUE THREAD

**Issue by marbre** [arrayfire/arrayfire#987]
Finally trying to get a working arrayfire build for Gentoo finished, I ran into the following issue, when working with the full source code archive:
~~~
marbre@thornydevil ~/tmp $ tar xvfj arrayfire-full-3.1.0.tar.bz2 
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
~~~
Gentoos latest stable versions are
* bzip2 Version 1.0.6, 6-Sept-2010.
* tar (GNU tar) 1.27.1

`bunzip2 arrayfire-full-3.1.0.tar.bz2 && tar xvf arrayfire-full-3.1.0.tar` works fine. Any suggestions? 

I would like to avoid overwriting the default, src_unpack() of the  ebuilds,.

**Comment by pavanky** [comment]
@marbre Thanks for reporting this. We'll try to update the archive soon.

**Comment by pavanky** [comment]
The archive has been updated to the proper format now.

**Comment by pavanky** [comment]
@marbre Just reminding you that you may need to remove the *_nonfree*" files from the repo depending on the policies of gentoo.

**Comment by marbre** [comment]
I think as long as the nonfree code isn't build, and the default is currently set to not build it, and nothing from it is installed by cmake this shouldn't be a problem(?).
Anyway, I will add the license and an optional use flag to enable it, if the user wishes to do .

**Comment by pavanky** [comment]
@marbre The default options do not build it.

**Comment by marbre** [comment]
Thank you for the updated archive. We now ArrayFire 3.0.2 and 3.1.0 with CPU, CUDA and OpenCL backend available for Gentoo (provided in the gentoo-science overlay).

Next, the ebuilds will probably be improved to allow BUILD_GRAPHICS and BUILD_NONFREE.
