### ISSUE TITLE
OSX build for cuda toolkit 7.5

### ISSUE THREAD

**Issue by cornsuite** [arrayfire/arrayfire#992]
The ArrayFire 3.1.0 installation package for OSX seem to contain a version of `libafcuda.3.1.0.dylib` library that has been linked with NVIDIA CUDA Toolikt version 7.0.
However, CUDA Toolkit 7.0 is not available even in the nvidia archives: https://developer.nvidia.com/cuda-toolkit-archive. Thus the ArrayFire install package for OSX is currently not usable: when running a simple program linked with ArrayFire I get an error: `dyld: Library not loaded: @rpath/libcudart.7.0.dylib`

Would you please consider recompiling ArrayFire for CUDA Toolkit 7.5?

I understand that I can recompile ArrayFire myself, but it would be good to have a working installation package in the official site.

Here is the output of "otool -L" on my box: 
```
$ otool -L /usr/local/lib/libafcuda.3.1.0.dylib
/usr/local/lib/libafcuda.3.1.0.dylib:
	@rpath/libafcuda.3.dylib (compatibility version 3.0.0, current version 3.1.0)
	@rpath/libcudart.7.0.dylib (compatibility version 0.0.0, current version 7.0.29)
	@rpath/libcublas.7.0.dylib (compatibility version 0.0.0, current version 7.0.29)
	@rpath/libcusolver.7.0.dylib (compatibility version 0.0.0, current version 7.0.29)
	@rpath/libcufft.7.0.dylib (compatibility version 0.0.0, current version 7.0.29)
	@rpath/libnvvm.3.dylib (compatibility version 3.0.0, current version 3.0.0)
	/usr/local/cuda/lib/libcuda.dylib (compatibility version 1.1.0, current version 7.0.29)
	@rpath/libforge.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/AGL.framework/Versions/A/AGL (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```

**Comment by shehzan10** [comment]
We will be shipping v3.1.1 built with CUDA 7.5. The ArrayFire v3.1.0 installers will remain CUDA 7 and will not be upgraded. We are looking at releasing v3.1.1 early next week.

It looks like the archives are not linked properly on NVIDIA's website. I guess they'll fix this sooner rather than later.

**Comment by FilipeMaia** [comment]
In the meantime you can get packages directly from http://developer.download.nvidia.com/compute/cuda/repos/

**Comment by FilipeMaia** [comment]
Oh I see you want the OSX version: http://developer.download.nvidia.com/compute/cuda/7_0/Prod/network_installers/cuda_7.0.29_mac_network.dmg

**Comment by vakopian** [comment]
Thank you. Please, feel free to close the issue

**Comment by cornsuite** [comment]
Thank you very much
