### ISSUE TITLE
Install destination of CMake configuration

### ISSUE THREAD

**Issue by marbre** [arrayfire/arrayfire#993]
Currently, or at least with the ebuilds for Gentoo Linux I have written, the CMake configuration of ArrayFire is installed to `/usr/share/ArrayFire/cmake/`. Shouldn't the configuration be installed to `/usr/share/cmake/ArrayFire/`?

**Comment by pavanky** [comment]
@marbre

This option is configurable. You can set it using the `AF_INSTALL_CMAKE_DIR` option. You can use it to put the cmake files anywhere gentoo expects them to be.

**Comment by pavanky** [comment]
You can look at the other available options in `CMakeModules/AFInstallDirs.cmake`

**Comment by marbre** [comment]
@pavanky Thank you for clarification and the hint on `CMakeModules/AFInstallDirs.cmake`.
